은행 창구 매니저 [STEP1] 요한, aCafela coffee, 호박
yagom-academy/ios-bank-manager pull request #100
Opened 2021-12-20 13:06 UTC by hoBahk

안녕하세요 쿠마!! @leejun6694 

은행 창구 매니저 Step1 PR 작성하여 보내드립니다.😄
잘부탁드립니다!🙏 

# 조언을 듣고싶은 점

## 유닛 테스트

### 1. 어디까지 테스트할지?

Queue 타입을 만들고 유닛테스트 코드 작성을 하며 '어떤 기능까지 테스트할지', '테스트 케이스는 무엇을 할지'가 고민이었습니다. 저희는 메서드단위로 적당한? 테스트케이스를 선정하게 되었는데 쿠마는 어떤 기준으로 테스트할 기능과 테스트 케이스를 선정하시는지 궁금합니다

### 2. 테스트만을 위한 코드를 만들어도 될까요?

Queue가 비었는지 테스트 하기 곤란했어요. head와 tail이 private 프로퍼티라서, isEmpty 프로퍼티를 테스트 코드에 사용했어요.

그리고 private 프로퍼티에 접근할 수 있는 모델을 테스트용으로 따로 만드는건 어떤가요? 코드를 복사해서 internal로 바꿔서 쓰는것도 생각했어요. 이래도 될까요?

```swift
// 아래 코드를 Tests에 넣기
struct QueueTest<T> {
    var head: Node<T>?
    weak var tail: Node<T>?
    ...
}
```

### 3. 테스트에서 빌드 타겟이 낮다고 에러가 발생하는 경우

![image](https://user-images.githubusercontent.com/90945013/146771281-9d04cf18-4f2e-40d6-a0c3-944f25bdfd69.png)

Development Target을 10.15버전으로 설정 하고 프로젝트를 진행하였는데 아래와 같이 최소 macOS 11.0버전 이상을 사용해야한다는 에러가 발생하였습니다.

> <unknown>:0: error: compiling for macOS 10.15, but module 'BankManagerConsoleApp' has a minimum deployment target of macOS 11.0: /Users/bagbyeongho/Library/Developer/Xcode/DerivedData/BankManagerConsoleApp-dqypvgeqyvfercdoqawwhvgnrjaz/Build/Intermediates.noindex/BankManagerConsoleApp.build/Debug/BankManagerConsoleApp.build/Objects-normal/arm64/main~partial.swiftmodule
Command MergeSwiftModule failed with a nonzero exit code
> 

모두 Xcode 버전은 같은데 10.15버전에서도 빌드가 되는 캠퍼(M1, OS: 12.x버전)도 있고 11.0버전 이상 되어야 빌드가 되는 캠퍼(M1, 인텔, OS: 11.x버전)가 있어 CPU나 버전으로는 해답을 찾을수가 없었습니다.
이를 해결하기 위해 이유를 구글링도 해보았지만 답을 찾을 수 없었습니다. 그래서 현재는 Development Target을 11.0버전으로 맞추었습니다. 
쿠마는 혹시 이런 오류를 경험 해보신 적이 있으실까요?

### 4. @testable import 오류

테스트 모듈과의 연결을 위해 @testable import를 사용하려고 하였습니다. 그런데 모듈을 찾을 수 없다는 아래와 같은 에러가 발생하였습니다. 

> Could not find module 'BankManagerConsoleApp' for target 'x86_64-apple-macos'; found: arm64, arm64-apple-macos, at: /Users/bagbyeongho/Library/Developer/Xcode/DerivedData/BankManagerConsoleApp-dqypvgeqyvfercdoqawwhvgnrjaz/Index/Build/Products/Debug/BankManagerConsoleApp.swiftmodule
> 

현재는 파일마다 일일이 테스트 모듈을 Target Membership으로 체크해주었습니다.
command Line Tool에서 유닛 테스트를 사용하는 것은 처음인데 이 오류가 command Line Tool과 관련이 있을까요? 아니면 다른 이유가 있을지 궁금합니다! 🤔

2021-12-21 02:43 UTC, leejun6694 requested changes
요한, aCafela coffee, 호박 안녕하세요 : )
기능 구현을 잘 해주셨는데, 몇 가지 리뷰를 남겼습니다.
확인 부탁드려요~~!

2021-12-21 03:01 UTC, leejun6694 commented
> 1. 어디까지 테스트할지?

이번 step 은 프로젝트를 구현하기 위한 기초 작업을 진행한 것이라, test 범위가 더 애매하게 느껴지셨을 것 같습니다.
지금과 같은 구현에선 저도 method 가 스펙에 맞게 잘 구현되었는지 테스트해볼 것 같아요ㅎㅎ

> 2. 테스트만을 위한 코드를 만들어도 될까요?

여러가지 방법이 있을 것 같은데, test file 내에 extension 과 접근 제어로 관리해주는 방법도 있습니다 : )
한번 고민해볼까요?

> 3. 테스트에서 빌드 타겟이 낮다고 에러가 발생하는 경우

개발 환경 등의 이유로 발생하는 에러는 저도 답변드리기가 조금 어렵네요ㅠㅡㅜ

> 4. @testable import 오류

@testable import 관련해서 구글링하면 비슷한 사례가 몇가지 나오네요!
참고 부탁드려요~~!

2021-12-21 03:03 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        head = nil
node 들이 메모리에서 해제되었는지 확인해보셨을까요?

2021-12-21 08:53 UTC, aCafela-coffee commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private weak var tail: Node<T>?
`clear()` 함수를 쓸때 `head`만 없애면 체인형태로 모든 노드가 없어지게 하려고 했어요.
`tail` 을 strong으로 갖고 있으면 현재구조에선 `dequeue()` 에서 tail을 별개로 해제해야 합니다!

2021-12-21 08:54 UTC, aCafela-coffee commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    func peek() -> T? {
어떻게 구분하면 좋을까요?🤔 별도의 extension으로 두거나 주석을 추가해줄까 고민해봤는데 메서드 앞에 mutating 이 있어서 서로 모아만 놔도 쉽게 구분된다고 생각했습니다

2021-12-21 08:54 UTC, aCafela-coffee commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        if isEmpty {
swift스럽게 수정해봤습니다!

```swift
mutating func dequeue() -> T? {
    let value = head?.value
    head = head?.next
    return value
}
```

2021-12-21 08:55 UTC, aCafela-coffee commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        init(_ value: S, next: Node? = nil) {
우선 질문을 정확히 이해하고자 재질문드리면, Node 타입의 생성자 ‘Argument Label이 생략된 것'을 말씀하신건지, value라는 이름이 어색하신건지 궁금합니다

전자(‘Argument Label이 생략된 것')가 어색하다는 뜻으로 가정하고 저희 의견을 말씀드리면, String(value)처럼 argument가 하나인 경우 label을 생략하는 경우가 많은 것 같았습니다
저희가 판단하기로는 생성자가 하나뿐이라 Argument Label이 없어도 헷갈리지 않을것 같습니다.

2021-12-21 08:55 UTC, aCafela-coffee commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private class Node<S> {
`Node`를 다른 곳에서 쓸 필요가 없으니 숨겼습니다.
나중에 `Node`타입을 밖으로 빼더라도 이름이 `Node`로 같아 `Queue` 타입은 수정할 필요가 없을 것 같습니다.

2021-12-21 08:57 UTC, aCafela-coffee commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        head = nil
`tail`을 확인하는 코드를 추가합니다.
```swift
func test_큐에_1과2를_enqueue하고_dequeue를_두번하면_tail은_nil이다() {
    //given
    var queue = QueueTestDouble<Int>()
    
    //when
    queue.enqueue(1)
    queue.enqueue(2)
    _ = queue.dequeue()
    _ = queue.dequeue()
    
    //then
    XCTAssertNil(queue.tail)
}
```

2021-12-21 08:58 UTC, YohanBlessYou commented on BankManagerConsoleApp/Tests/Tests.swift
> +class Tests: XCTestCase {
알고는 있었는데 넣을 생각을 못했네요! 코드가 짧아서 꼭 넣어야 할까?에 대해 저희끼리 논의를 해보았고, 넣는 방향으로 결정하여 테스트 코드에 추가했습니다 :)

- 주어진 상황(값) : given
- 이를 사용하는 행위(기능) : when
- 결과 대조 : then

2021-12-21 08:58 UTC, YohanBlessYou commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +            let node = Node(value)
그렇네요! if와 else 모두에 공통적으로 포함된 코드는 중복이 없도록 빼내었습니다!

2021-12-21 08:59 UTC, hoBahk commented on BankManagerConsoleApp/Tests/Tests.swift
> +        _ = queue.dequeue()
```swift
@discardableResult
mutating func dequeue() -> T? {
    let value = head?.value
    head = head?.next
    return value
}
```
위와 같은 방법도 있지만, 반환값을 사용하리라 예상되는 함수라서 이번에는 사용하지 않았습니다!

테스트 코드에서는 `dequeue()` 의 반환값을 사용하지 않지만, BankManagerConsoleApp에서는 `dequeue()` 의 반환값을 사용할 것이라 생각되어서 warning이 일부러 발생하도록 했습니다!

현업에서 저희와 같은 의도대로 사용되는 일이 있을까요!? 🤔

2021-12-21 18:56 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    func peek() -> T? {
method 순서로 정리해보는건 어떨까요?

2021-12-21 18:57 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        if isEmpty {
if 문을 사용하게 된다면, return 이 따라오는 구조여서 `guard` 를 생각해봤습니다ㅎㅎ
if 문 없이 지금처럼 구현해주신 것도 너무 좋습니다~~!

2021-12-21 18:59 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        init(_ value: S, next: Node? = nil) {
네ㅎㅎ 의견 감사합니다 : )

2021-12-21 19:01 UTC, leejun6694 commented on BankManagerConsoleApp/Tests/Tests.swift
> +        _ = queue.dequeue()
추후에 구현 방향을 생각해준 부분은 너무 좋습니다.
다만, 결국 테스트 코드에서 사용되지 않을 것이라면 위 예시처럼 구현해도 괜찮지 않을까요?
@discardable 은 return 값을 사용해도 되고, 안해도 되니까요ㅎㅎ

2021-12-21 19:02 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    func peek() -> T? {
약간의 주석이 추가되어도 좋겠네요 : )

2021-12-21 19:03 UTC, leejun6694 commented
질문에 대한 답과 리뷰 내용을 잘 반영해주셔서 감사합니다 : )
몇가지 코멘트를 추가했는데, 확인 부탁드려요.
step 2 도 잘 부탁드립니다~!!

2021-12-21 19:03 UTC, merged

2021-12-22 05:23 UTC, YohanBlessYou commented on BankManagerConsoleApp/Tests/Tests.swift
> +        _ = queue.dequeue()
저희 내부적으로도 말씀해주신 것처럼 @discardable을 붙일까 말까에 대한 호불호가 갈렸었습니다. 최종적으로는 테스트코드가 조금 지저분해지더라도 Product 코드에 warning이 뜨도록 하여 실수를 방지하는데 더 중점을 두었습니다!