은행 창구 매니저 [STEP 1] Lily, 숲재
yagom-academy/ios-bank-manager pull request #106
Opened 2021-12-21 05:57 UTC by forestjae

안녕하세요 그린! @GREENOVER 
Lily와 숲재입니다. Step 1 완료하여 PR 보내드립니다 !
고민한 점과 궁금한 점 아래와 같이 보내드리니 확인 부탁드려요 😁
이번 프로젝트도 잘 부탁드립니다 🙇🏻‍♂️🙇🏻

---
## 고민한 점
**1. Queue의 Clear메서드 구현**
```swift
    mutating func removeAll() {
        head = nil
        tail = nil
    }
```
Queue의 `Clear`메서드를 구현하기 위해 LinkedList에 구현 된 `RemoveAll`메서드를 사용하였습니다. 이 과정에서 LinkedList의 head에 nil을 할당하면 tail을 제외한 모든 Node가 deinit이 되는것을 확인할 수 있었습니다. 따라서 head와 tail에 nil을 할당하는 것으로 연결리스트가 가지고 있는 모든 Node를 삭제하는 함수를 구현했습니다. tail만 남아있게 되는 이유는 `LinkedList` 타입에서 참조를 계속 해주고 있기 때문이라고 생각이 되는데, tail변수를 굳이 약한 참조할 필요는 없는 것 같아 그대로 두었습니다.
<br>

**2. Struct와 Class중 어느것을 선택할지** 
`Node`,`LinkedList`와 `Queue`를 구조체와 클래스 중 어떤 타입으로 구현할지 고민했습니다.

`Node`는 `LinkedList`의 `next`프로퍼티로 전달될 때 참조로 전달되는 것이 효율적이라 판단하여 클래스를 선택했습니다.
그리고 `LinkedList`와 `Queue`는 class를 사용해야할 이유가 없는 것 같아서 디폴트로 struct를 사용하라는 애플의 권고에 따라서 struct로 구현했습니다.
<br>

## 궁금한점

**1. Unit Test 네이밍** 
Unit Test의 테스트 네이밍을 어떤 컨벤션을 사용할지 고민해보았습니다.

Should, When을 명시적으로 기재해서 테스트의 조건과 기대 결과를 구분하여 표현했습니다.
When에 뒤따르는 내용은 테스트할 메서드에 대한 내용만 기재해주었습니다. 테스트를 위해 전제되어야하는 선행 코드에 대한 내용은 생략해주었습니다.(아래 코드에서는`queue.enqueue(1)`)

```swift
  func test_Should_returnValueIs1_When_dequeue() {
        queue.enqueue(1)
        let returnValue = queue.dequeue()
        XCTAssertEqual(returnValue, 1)
    }
```
그린이 보시기에 저희가 생각한 네이밍이 적절하다고 생각하시나요? 조언 부탁드립니다.

---
읽어주셔서 감사합니다 🙏🏻

2021-12-21 07:46 UTC, GREENOVER requested changes
@yeahg-dev @forestjae 
안녕하세요 두분!
구면이네요😁
이번 프로젝트도 2주간 저또한 잘~ 부탁드립니다!
우선 스텝1 기한내에 잘 구현해주시느라 너무 고생 많으셨습니다🙌
전체적으로 코드의 짜임새와 근거들이 잘 녹아 있어 리뷰하기 수월했습니다!
그럼 리뷰해보도록 하겠습니다🚀
***
### 칭찬 드리고 싶은 부분
- 커밋을 정말 세세하게 진행해주신 점 💯
- 리드미를 스텝 진행하면서 작성하고 계신점 진짜 최고 💯💯💯
- 연결리스트와 큐 구현에서 전반적으로 네이밍이 좋은점 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. Queue의 Clear메서드 구현
- 우선 결론을 말씀드리면 지금 구조에서 지금 구현은 딱 좋다고 생각합니다.
이건 선택사항이겠지만 tail에 대해 어떻게 구현해주고 정의해주는지에 따라 다를것 같아요.
만약 tail을 computed property로 만들어 head의 정보를 가지고 구성해준다면 removeAll 메서드에서 tail에 nil을 주는 과정을 필요 없을거에요.
그렇지만 그건 현재 구현해주신 구조에선 맞지 않기에 패스..!
지금 구현으로 가도 고민해주신 결론이 잘 반영되었고 추후 스텝에서도 문제 없다고 판단됩니다🙌
2. Struct와 Class중 어느것을 선택할지
- Node를 클래스 타입으로 가져가신점에는 백프로 동의합니다👍
아마 노드 자체를 구조체로 만들 수는 없을거에요.
그리고 이건 선택의 문제이지만 LinkedList를 Class, Struct로 구현해도 양방향 모두 이상은 없습니다.
다만 어떤 파생될 차이가 있을까요?
저도 정확하게 딱 이렇게하고 답드리기에는 지식이 부족하네요🥲
커뮤니티나 여러 사이트에서도 의견이 분분한데 한번 도움이 될만한 소스를 공유드려보겠습니다!
(사용언어는 제외하고 개념의 기조를 봐주세요..!)
https://www.linkedin.com/pulse/linked-list-c-classes-structures-ankit-pruthi/
https://www.quora.com/Why-we-use-struct-for-linked-list-instead-of-classes
***
### 궁금하신점에 대한 저의 의견
1. Unit Test 네이밍
- 정말 네이밍중에서도 가장 스타일이 많이 갈리는게 유닛 테스트 메서드 네이밍이라고 생각하는데..
지금 유닛 테스트 코드 네이밍 저는 좋은것 같아요!
카멜케이스와 스네이크케이스가 혼용되서 사실 더 가독성이 좋아져보이긴 합니다.
사실 저는 스네이크케이스만을 사용하고 있고 Should, When의 명시적 기대효과와 조건을 네이밍에 녹이진 않고 있어요.
메서드 네이밍만을 따져보면 가독성은 어떻게보면 두분이 하신것보다는 떨어지는건 사실입니다.
다만 코드내에서 충분히 전달이 될 수 있을거라 생각하고 저도 아직 어떤게 맞다 자주쓰인다 이렇게 판단되는 근거는 없지만
제가 저렇게 하고 있는 이유는 애플의 공식문서 및 애플의 테스트 코드 컨벤션을 보고 따르고 있습니다.
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/04-writing_tests.html
저도 이참에 조금 고민을 또 해봤는데 애플에서 이렇게 한다고 사실 가독이 안좋은걸 무조건 따를순없고
찾아보니 많은 iOS 개발자들이 두분의 방식대로 하더라구요🤔
https://www.appsdeveloperblog.com/naming-ios-unit-test-methods/
그래서 저도 이참에 바꿔볼까 생각도 들었습니다.
저의 넋두리가 길었네요ㅋㅋ..
결론적으로는 훌륭한 네이밍이라고 생각해요!
***
### 보완되었으면 좋을 부분
1. LinkedList의 추가 구현
- 리뷰 코멘트에도 남겨두긴 했지만 조금 자세히 말씀드려보면 사실 지금의 연결 리스트 구현은 정말 간단한 구현이라고 보이고 
연결 리스트의 장점을 활용할 수 없다고 보입니다.
큐를 구현하기 위한 연결 리스트에 초점이 맞춰져서 현재 단순 큐에서는 해당 연결 리스트의 구현으로는 충분하다고 판단되지만
추후 어떤 요구사항들이 올지도 모르고 어떻게 필요사항들이 바뀔지 모르는 상황에서 연결 리스트를 구현할때는 다른 부분을 배제하고
딱 분리시켜 연결 리스트를 구현해봄이 어떨까 싶습니다🙋🏻
우선적으로 큐를 구현할때 Double Stack과 LinkedList의 차이와 장단점을 파악해보고 LinkedList의 장점을 구현해보면 어떨까요?
2. UnitTest
- 네이밍은 정말 훌륭합니다👍
다만 조금 더 테스트 케이스를 다양하게 구현해보면 어떨까요?
지금은 enqueue, dequeue, peek, clear 등 하나씩의 테스트 케이스만 있는데
각 메서드별 성공, 실패 등 최소 2개씩은 나올 수 있을것 같아요.
제네릭 타입별로도 다양하게 해볼 수도 있을것 같고..?
만약 가능하다면 좀 더 다양한 케이스로 유닛 테스트를 진행하는것이 더 테스트 다운 코드 같아 보입니다!
현재는 테스트를 했다라고만 보여질뿐 이거 정말 꼼꼼한 테스트인가? 라는 신뢰는 조금 떨어집니다😭
***
두분 다시 한번 수고 많으셨습니다..!
어쩌다보니 리뷰와 코멘트가 많아졌네요😅
거를 부분은 걸러 들으셔도 무방합니다!
조금 보완을 해볼 순 있을것 같아서 한번 더 수정을 거치고 리뷰 요청을 주시면 그때 머지하도록 해볼께요..!
만약 다른 의견이 있다면 꼭 편하게 말씀해주세요🙌

2021-12-21 07:46 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +        XCTAssertEqual(returnValue, 1)
returnValue라는 상수를 생성하여 지금처럼 값을 넣어주고 비교하는것과
```swift
XCTAssertEqual(queue.dequeue(), 1)
```
로 표현하는것과 어떤 차이가 있을까요?🤔

2021-12-21 07:46 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +    var queue: Queue<Int> = Queue<Int>()
setUpWithError 메서드를 사용하여 큐를 초기화하지 않고 요렇게 사용한 이유가 궁금합니다🙋🏻
어떤차이가 있었나요?

2021-12-21 07:46 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +     queue = Queue<Int>()
띄어쓰기 컨벤션이 무너진것 같습니다🤭

2021-12-21 07:46 UTC, GREENOVER commented on README.md
> +<br>
오랜만에 리드미를 스텝을 진행하면서 작성하시는분을 뵙네요👍
정말 최고입니다..!💯💯💯
꼭 마지막 스텝까지 조금씩 쌓아가봐요~!ㅎㅎ

2021-12-21 09:26 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +//  Created by 1 on 2021/12/20.
제 맥북의 아이디가 1이라...ㅋㅋㅋㅋㅋ그렇슴다...ㅎㅎ

2021-12-21 09:29 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +				33B3602E2770850400EE24A6 /* Queue.swift */,
Model 폴더로 묶어주었습니다!

2021-12-21 09:34 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +}
말씀해주신 부분을 간과했던 것 같습니다. Nested Type으로 LinkedList구조체 내부에 Node Class를 넣어주었습니다 !

2021-12-21 09:36 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
빈 큐를 생성할 때 쓰이는 이니셜라이져입니다. 추후 프로젝트 시 사용될 것 같아 만들어 두었습니다!

2021-12-21 09:45 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +//  Created by 1 on 2021/12/20.
아하! 정말 진짜 찐으로 그냥 궁금해서 여쭤봤습니다ㅋㅋㅋ

2021-12-21 09:47 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +}
좋습니다! 만약 해당 노드 클래스를 더이상 상속해서 사용하거나 그렇지 않는다면 final 키워드를 붙여 성능을 높여줌은 어떨까요?

2021-12-21 09:48 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        guard isEmpty else {
## `guard`
조건에 부합하지 않을 때 early exit을 하고 싶을 때 사용합니다.

## `if`
조건에 따른 분기 처리를 해줄 때 사용합니다.

2021-12-21 09:50 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        guard isEmpty else {
그럼 이 로직에서는 guard가 적합한걸까요??

2021-12-21 09:54 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
첫번째 노드의 data를 반환하는 Queue의 `peek`메서드에서 사용하기 위해 first를 구현해주었습니다.
그래서 last는...구현할 필요가 없다고 생각했습니다~

2021-12-21 09:56 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        items.append(data: data)
언더스코어 사용하여 수정하였습니다!

2021-12-21 09:58 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +    func test_Should_isEmptyIsFalse_When_enqueue3() {
가독성 향상을 위해 같이 모여서 의미를 이루는 단어들이 한 뭉텅이로 표현하려 했습니다!

2021-12-21 10:01 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +        XCTAssertEqual(returnValue, 1)
상수에 담아주었을 때 가독성이 더 좋다고 생각했습니다~!

또 다른 차이가 있으면 알려주시면 감사하겠습니다!🤩

2021-12-21 10:07 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +    var queue: Queue<Int> = Queue<Int>()
위 방법이 테스트 할 객체를 만들어주는 유일한 방법이라 생각했던 것 같습니다.

그런데 묵시적 옵셔널로 선언만 하고 setUpWithError메서드로 초기화해주는게 더 적절해 보여서 수정했습니다!

2021-12-21 10:08 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +     queue = Queue<Int>()
🤭 수정했습니다...

2021-12-21 10:09 UTC, yeahg-dev commented on README.md
> +<br>
끝까지 쌓아가보겠습니다~~ 끝까지 지켜봐주세요...😬

2021-12-21 10:12 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
아하 이해했습니다!👍

2021-12-21 10:13 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +    func test_Should_isEmptyIsFalse_When_enqueue3() {
제 테스트 메서드 코드 네이밍보다 의미전달이 좋네요👍

2021-12-21 10:14 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleTests/QueueTests.swift
> +        XCTAssertEqual(returnValue, 1)
스타일의 차이겠지만? 
사실 상수/변수를 만들어주는 메모리의 아주 근소한 차이가 있겠지만 그것은 무시해도 될 정도이기에
지금 구현해주신것과 같이 해주는것이 더 가독은 좋겠네요!

2021-12-21 10:15 UTC, GREENOVER commented on README.md
> +<br>
충분히 하실수 있으리라 봅니다..! 화이팅🙌

2021-12-21 10:17 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        guard isEmpty else {
아 혹시 오해하실까봐...🤭
적합하지 않아서 의도적인 질문은 아니였습니다!
요것도 스타일의 차이이기에 어떤 스타일을 가지셨나 궁금해서 여쭤봤습니다.
다만 guard 사용 시에 말씀하신것처럼 빠른 탈출 시 유리한데 현재 else에 로직이 들어가 있어 
if로 분기 처리해주는것과 다를게 없다고 느껴졌습니다!

2021-12-22 07:08 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
## Double Stack
- 스위프트에서는 두개의 array로 보통 구현을 하는데, 
Queue에서 enqueue, dequeue를 할 때 array에서 `append()`, `removeLast()`와 `reversed()`를 사용해서 각각 O(1)이지만,
중간 요소를 추가 삭제할 때는  링크드리스트보다 좀 더 여러단계를 거쳐서 비용이 많이 듭니다
- array는 탐색이 O(1)이어서 중간요소를 접근하는데는 효율적이지만, 요소를 삭제하거나 추가하는데는 O(n)의 비용이 든다고 생각했습니다.
- 추가적으로 `append()`를 실행할 때 새로운 메모리를 할당해야할 경우에는 O(n)이 될 수도 있습니다.(흔하지는 않은 경우지만)

## Linked List
- 단방향에서 양방향, 원형 링크드리스트로 수정이 가능하고, 확장에 열려있다.
- 추가, 삭제가 O(1)이지만 탐색은 O(n)이므로 **결국 탐색을 고려하면** 추가, 삭제가 Double Stack과 큰 차이가 없는게 아닐까...생각했습니다. 이부분에 대해서 그린은 어떻게 생각하시는지 궁금합니다!

저희가 내린 결론은 더블스택과 링크드리스트에서 중간 데이터를 추가하거나 삭제하는데는 큰 차이가 없을 것이라 판단했습니다.
오히려 더블스택이 값타입이기 때문에, 클래스를 사용하는 링크드 리스트보다 더 성능상으로 이점이 있을 것이라 생각해봤습니다.(뇌피셜...)
이에 대한 그린의 의견도 들어보고 싶습니다~

2021-12-22 07:16 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
@yeahg-dev 
그럴수 있겠네요! 동의합니다.
그렇다면 탐색을 해주는 findNode같은 메서드가 있으면 어떨까요?🤔
결국 하나의 메서드 (insert, remove)에서 탐색과 추가 삭제를 같이 해주느냐
아니면 두 메서드를 별도 분리해서 두 로직을 태우느냐의 선택사항일것 같아요.
어떤쪽이 더 괜찮아 보이시나요?

2021-12-22 07:32 UTC, yeahg-dev commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
탐색과 추가,삭제를 두 메서드로 분리해서 두 로직을 태우는 쪽으로 결정했습니다.
좀 더 재사용성이 높을 것이라 생각했기 때문입니다~

2021-12-22 09:56 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
remove(at: index)와 insert(data, at: index) 메서드를 구현해 주었습니다 !

2021-12-22 10:51 UTC, forestjae commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +}
final 키워드 추가하였습니다 !

2021-12-22 10:56 UTC, forestjae commented
> LinkedList의 추가 구현

의견 주신대로, 요구사항에서 LinkedList로 Queue를 구현하라고 한 이유가 있을 것 같다고 생각했습니다. LinkedList의 장점인 요소를 추가 삭제할때 시간복잡도가 O(1)이라는 것을 떠올려 `insert(at:)`메서드와 `remove(at:)`메서드를 추가 구현했습니다. 

> UnitTest

말씀하신대로 다양한 케이스 추가 해 보았습니다. 다만, `Int`외에 다른 타입을 택한 `Queue`를 만들 때 테스트 함수 내부에서 별도로 생성 해 주었는데요, 다른 좋은 방법이 있을지 궁금합니다!

2021-12-22 23:00 UTC, GREENOVER approved these changes
두분 스텝1 수정하시느라 고생많으셨습니다!!
전체적으로 잘 보완되었고 필요 요구사항도 다 잘 들어가 있어서 어프로브 후 머지하겠습니다ㅎㅎ
아 질문해주신 테스트 관해서는 여러 타입으로 테스트 할 시 테스트 코드 내에서 하는게 제일 저는 적합하다고 봅니다.
추가로, 현재 테스트에서 실패 케이스가 거의 없는데 추후 보완이 되면 더 좋을것 같다고 생각합니다🙋🏻
그외에는 정말 잘 구현해주셨습니다👍
그 외 하나 메서드명에 관해 리뷰 코멘트로 마이너하게 남겨봤습니다.
확인해보시면 좋을것 같아요!
고생하셨어요ㅎㅎ
스텝2에서 뵈요!

2021-12-22 23:01 UTC, merged