은행 창구 매니저 [STEP 1] yeha, 호댕
yagom-academy/ios-bank-manager pull request #110
Opened 2021-12-21 08:41 UTC by yanghojoon

안녕하세요 도미닉! @AppleCEO 
은행 창구 매니저 Step 1 마무리되서 PR 보내드립니다! 

이번 프로젝트 잘 부탁드립니다 🙏 
감사합니다 🙇 

## 고민했던 점

### Singly Linked List 구현

- Linked List에 원소를 조금 더 효율적으로 추가하기 위해 `tail` 변수를 생성했습니다.
- Linked List를 Queue의 타입으로 이용할 수 있게 스텝 요구사항이었던 `Enqueue, Dequeue, Clear, Peek, isEmpty` 를 Linked List 내부에 구현했습니다. 
후에 동료들과 이야기하다가 Queue 타입을 따로 구현하는게 맞다고 판단해서 Queue 타입을 추가로 구현했습니다. 
Linked List도 그에 맞추어 네이밍을 수정했습니다.
- Linked List의 `removeAll()` /  `removeFirst()`메서드의 로직을 고민했습니다.
    
   ```swift    
   mutating func clear() {
       while head != nil {
       	   head = nil
    	   head = head?.next
       }
   }
   ```
    
    처음에는 위 코드처럼 head가 nil이 아닐 때, head에 nil을 할당해주고 head를 `head?.next`로 이동시켜서 모든 원소를 돌며 일일히 삭제해주는 방법을 사용했습니다.
    하지만 LLDB를 통해 확인해보니 head에 nil을 할당한다면 이어지는 모든 Node도 nil이 할당되어 전부 비워지는 것을 확인했습니다. tail에는 저희가 직접 특정한 Node를 할당해주어 `head = nil` 만으로는 nil이 할당되지 않는 것을 확인할 수 있었습니다. 
    
   <img width="484" alt="스크린샷 2021-12-21 오후 5 04 47" src="https://user-images.githubusercontent.com/90880660/146898189-ee09f9bb-db52-43c2-970f-372186a0ad34.png">

   head에 추가한 Node가 전부 들어가 있는 것을 확인할 수 있었습니다.
   따라서 반복문을 사용하지 않고 head와 tail에 각각 nil을 할당해서 모든 LinkedList를 삭제하는 방법을 선택했습니다. 
    

### Unit Test

- 옵셔널 타입인 sut을 바인딩해주기 위해 `XCTUnwrap`을 사용했습니다.
    
    `setUpWithError()` 에서 sut을 할당해주고 `tearDownWithError()` 에서 다시 nil로 할당하려면 sut을 옵셔널 타입으로 선언해야 했습니다. 하지만 매번 이를 바인딩해줘야 하는 불편함이 있었는데, 이 때 사용할 수 있는 `XCTUnwrap`을 찾아 사용했습니다. 
    
    만약 강제 추출을 통해 바인딩을 해주게 되면 Fatal Error가 발생하며 앱이 아예 종료되는 문제가 있지만, `XCTUnwrap`을 사용하면 테스트가 실패했다고 알려줘서 테스트 코드에 사용하기 더 적합하다고 생각했습니다. 또한 `guard let`, `if let`을 통해 바인딩하는 것보다 간단하여 적합하다고 판단했습니다. 
    

---

## 해결이 되지 않은 점

- 이미 생성되어 있었지만, 이번 스텝에서 사용하지 않는 파일을 남겨두어도 괜찮을지 궁금합니다.
    - BankManager는 다음 스텝에서 이용할 것같아 남겨두었고, main은 삭제하면 Command Line Tool의 경우 main.swift에서 시작이 되기 때문에  에러가 나서 남겨두었습니다.

---

## 조언을 얻고 싶은 부분

- 테스트 코드도 기존의 배포 코드와 컨벤션을 동일하게 주는 것이 좋을지 궁금합니다.
- 저희는 변/상수에 할당해줄 때와 함수를 호출할 때 개행을 해주었습니다. 
도미닉은 어떤 방식을 선호하시는지 궁금합니다.

2021-12-22 02:48 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.

@ye-ha @yanghojoon 고생하셨습니다.

몇가지 개선하면 좋은 점들 남겨놨습니다.

테스트 코드도 기존의 배포 코드와 컨벤션을 동일하게 주는 것이 좋을지 궁금합니다.
- 네 동일하게 주는 편입니다. 어떤 부분을 말하는지 조금 더 자세히 말씀해주시면 좋겠네요! 기존의 파일들의 컨벤션을 잘 따르도록 작성하게 되는데 테스트 코드는 다르게 할 필요가 있을까요?

저희는 변/상수에 할당해줄 때와 함수를 호출할 때 개행을 해주었습니다.
도미닉은 어떤 방식을 선호하시는지 궁금합니다.
- 변수를 할당해주는 부분과 함수를 호출하는 부분을 개행해서 나눠줬다는 말씀이시죠? 저도 그 부분은 개행을 해주는 편입니다.

2021-12-22 02:48 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +struct LinkedList<Type> {
오우 T라고 안 줄여쓰고 Type 을 쓴 것 아주 좋습니다! 👍

2021-12-22 02:48 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
이 부분 else 를 안 쓰고 작성해볼 수 있을까요?
저는 else 를 코딩하면서 거의 사용하지 않습니다.
어떤 점에서 else 를 안 쓰는 것이 좋을까요?

2021-12-22 02:48 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
큐의 기본 메소드들을 잘 구현해보셨군요.
dequeue 의 경우에는 가장 앞에 값을 가져와야하는 것으로 아는데 이렇게 메소드를 작성하면 리턴 값이 없군요.
스위프트에서는 메소드의 구현부가 1줄이면 return 을 생략할 수 있지만 저는 생략하지 않는 편입니다.
이렇게 return 을 생략한 코드와 생략하지 않은(return이 필요하지 않은) 코드가 섞여있다면 어떤 점이 안 좋을까요?

2021-12-22 02:48 UTC, AppleCEO commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +    }
이렇게 반복되는 코드들을 함수에 넣어서 처리한 부분 좋습니다~ 💯

2021-12-22 02:48 UTC, AppleCEO commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +    func test_isEmpty_shouldReturnExactBooleanType() throws {
테스트명을 보면 "isEmpty 는 불리언 타입을 리턴하는 것으로 예상된다" 라고 해석되는데요.
테스트는 False 인지를 확인하는 것으로 보이네요.
테스트명과 테스트 코드의 내용이 좀 다른 것 같습니다.
어떻게 개선해 볼 수 있을까요?

2021-12-22 02:48 UTC, AppleCEO commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +    }
성공할 때와 실패할 때가 테스트에 있으면 좋겠습니다.
예를 들면 큐에 아무 데이터가 없을 때 peek 을 하면 nil이 리턴된다,
그리고 1을 넣은 상태에서 peek을 하면 1이 리턴된다.
이런 식으로 테스트명도 조금 더 명확하고 하나의 테스트가 더 추가되면 좋겠네요! 🔢

2021-12-23 11:57 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
else를 쓰게 되면 어떤 조건인지 가독성이 떨어지는 단점이 있을 것같습니다! 
if-else문을 쓰게 되면 guard문을 쓸 때보다 탭을 하나 더 쳐야하는 개인적인 단점도 있을 수 있다고 생각합니다. 
이 부분은 두 조건 다 처리를 해주어야 해서 guard의 else 내에 처리를 해준 후 return 하도록 변경해보았는데요. 
혹시 더 개선할 여지가 있을까요?

2021-12-23 11:58 UTC, yanghojoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
일단 `return`을 생략하는 경우 값을 반환하고 있는지 헷갈릴 수 있기 때문에, `return`을 붙여주는 것이 더 좋다고 판단하여 수정했습니다! 

다만 `dequeue`메서드의 경우 `peek`으로 List의 첫 번째 값을 반환할 수 있어서, `dequeue`에서도 값을 반환한다면 유사한 기능이 겹치게 된다고 판단했습니다. 
따라서 `dequeue`의 경우 값을 따로 반환하진 않고 List의 첫 번째 값을 빼주는 함수로 구현해줬는데, 통상적으로 사용하는 `dequeue`처럼 값을 반환해주는 것이 더 좋을까요?

2021-12-23 12:21 UTC, yanghojoon commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +    func test_isEmpty_shouldReturnExactBooleanType() throws {
`test_isEmpty_withEmptyLinkedList_shouldReturnTrue` 이렇게 조금 더 구체적으로 네이밍 수정했습니다!

2021-12-23 12:21 UTC, yanghojoon commented on BankManagerConsoleApp/LinkedListTest/LinkedListTest.swift
> +    }
peek의 경우도 아무 데이터가 없을 경우와 데이터가 들어있는 경우를 나눠서 테스트 진행해봤습니다!

테스트 명도 이에 맞춰 수정 완료했습니다.

2021-12-23 13:58 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
네 제 생각에는 그게 약속이어서 마음대로 수정해주는 것보다는 통상적인 기능으로 구현해주는 것이 좋다고 생각합니다.
예를 들어 다른 사람이 코드를 유지보수하게 되면 dequeue 는 당연히 첫 요소를 반환하면서 제거하는 것이라고 생각하고 사용하는데 예상과 다른 동작에 놀랄 수 있을 것입니다.
(다른 사람이라고는 했지만 몇달 후에 자신이 사용하려고 해도 놀랄 수 있습니다!)

2021-12-23 14:08 UTC, merged