은행 창구 매니저 [STEP2] 호랭이, 니콜라스
yagom-academy/ios-bank-manager pull request #114
Opened 2021-12-23 15:22 UTC by horeng2

@protocorn93 
@Kim-EunsooSilver

step2 PR제출합니다!
많은 고민과 시행착오가 있었는데 PR에 잘 담겼는지 모르겠네요 😂
이번 리뷰도 잘부탁드립니다!
감사합니다☺️

---
## 1. 고민했던 점

- Banker타입을 처음에는 인원수를 고려하지 않고 구현했다가, n명의 은행원이 있다는 요구사항을 확인하고 Bank타입 안에서 bankers라는 배열로 정의했습니다.
- 은행의 업무시간을 계산하기 위해 Timer 클래스 사용에 대한 고민을 했습니다. 저희가 수시간 동안 연구(?) 해본 결과 저희의 상황에는 맞지 않는 방식으로 결론을 내렸고 `CFAbsoluteTimeGetCurrent()` 를 사용하여 은행의 업무시간을 계산하였습니다.
    - Timer클래스를 사용한다면 프로그램을 실행하는 내내 0.01초마다 timeCount라는 변수에 0.01씩을 더해주는 방식을 생각했었는데, 이렇게 된다면 실행하는 동안 계속적으로 0.01초마다 연산이 반복되기 때문에 지금처럼 처음과 끝시간만을 이용해서 한번만 계산하는 것이 더 효율적이라고 생각했습니다.
- BankManager와 Main의 역할에 대한 고민을 했습니다. 프로젝트 포크시에 기본 생성된 파일이기에 파일명에 맞게끔 설계했습니다.
- 총업무시간 계산결과를 소수점둘째자리까지 나타내기 위해서 NumberFormatter를 사용했습니다.
- 메뉴에서 1을 선택했을 때 작업을 실행하고 2를 선택했을 때 종료를 하는 부분에서 wile문을 사용한 이유
    - 1을 선택해서 작업이 수행이 끝난 뒤에 다시 메뉴를 호출해서 새롭게 은행을 개점해야할 수도 있는데, 이부분을 isExit와 wile문을 사용해서 2가 입력되기 전까지 반복해서 메뉴를 선택할 수 있도록 설계하였습니다. switch문에서 2를 선택했을 경우에만 isExit가 true로 바뀌기 때문에 wile문이 종료되고 프로그램이 종료됩니다.

## 2. 조언을 얻고 싶은 부분

- 메뉴가 은행개점/종료 두개뿐인데 이렇게 갯수가 적은 경우에도 enum으로 관리하는게 좋을까요?
- 은행 업무를 위해 은행원 객체를 생성하고, 고객을 clientQueue에 넣고, 총 영업시간을 계산하는 등의 일이 매니저의 역할인지 은행의 역할인지 그 경계에 대해서 고민을 했습니다. 고민의 결과로는 영업시간을 계산해서 출력하는 일만 매니저에서 수행하게 하고, 나머지는 은행 업무의 일종이라고 생각해서 지금과 같이 코드를 짜봤는데 이런 부분은 주관적인 판단으로 해야하는 건지, 나름의 기준이 있는 건지 궁금합니다.

## 3. 트러블 슈팅

- `sleep` 에 대한 잘못된 사용
    - 예시: `sleep(UInt32(0.7))`
        - 이유: sleep은 파라미터로 UInt32, UInt64등 Int으로만 설정이 가능하다.
    - 개선사항: `Thread.sleep(forTimeInterval: 0.7)`

2021-12-24 01:42 UTC, protocorn93 requested changes
@horeng2 @Kim-EunsooSilver 모두 수고하셨어요!! 시간을 다루는게 쉽지 않았을텐데, 많은 시행착오가 있으셨을것같네요👍

## 고민했던 점 

> 은행의 업무시간을 계산하기 위해 Timer 클래스 사용에 대한 고민을 했습니다. 저희가 수시간 동안 연구(?) 해본 결과 저희의 상황에는 맞지 않는 방식으로 결론을 내렸고 CFAbsoluteTimeGetCurrent() 를 사용하여 은행의 업무시간을 계산하였습니다.

- 이 고민의 과정을 좀 더 상세히 알 수 있을까요?? 말씀해주신 사례말고 무언가 더 있을 것 같아서요 🤔

## 조언을 얻고 싶은 부분 

> 메뉴가 은행개점/종료 두개뿐인데 이렇게 갯수가 적은 경우에도 enum으로 관리하는게 좋을까요?

- 네 저는 이 부분은 `enum`으로 관리하는게 더 좋아보이네요! 

> 은행 업무를 위해 은행원 객체를 생성하고, 고객을 clientQueue에 넣고, 총 영업시간을 계산하는 등의 일이 매니저의 역할인지 은행의 역할인지 그 경계에 대해서 고민을 했습니다. 고민의 결과로는 영업시간을 계산해서 출력하는 일만 매니저에서 수행하게 하고, 나머지는 은행 업무의 일종이라고 생각해서 지금과 같이 코드를 짜봤는데 이런 부분은 주관적인 판단으로 해야하는 건지, 나름의 기준이 있는 건지 궁금합니다.

- 음 사실 이 부분은 정확한 정답은 없다고 생각해요. 저는 보통 리팩토링을 진행할 때 이 프로퍼티를 이 객체가 정말 갖고 있어야하는가에 대해 고민을 해보아요. 그렇게 되면 자연스럽게 해당 프로퍼티를 사용하는 메서드들도 분류가 되겠죠? 그리고 그렇게 프로퍼티와 메서드들로 묶인 그룹을 별도의 객체로 분리해내려해요. 리펙토링의 과정은 이러합니다. 

처음부터 객체를 만드는 시점에선, 메시지들에 대해서 고민을해요. "업무 시작해", "시간 측정해", "결과 출력문 보여줘" 등등의 요청이 있을테고, 이를 적절히 처리할 객체들에 대해서 생각을 합니다. 

"시간 측정해"라는 메시지를 받은 객체는 관련 퍼블릭 메서드를 정의하겠죠? 그리고 내부 구현을 작성해나가면서 필요한 프로퍼티들은 해당 객체 내부에 선언이 될거구요. 그러면 자연스럽게 본인의 역할을 수행하는데 필요한 프로퍼티들만 갖게 되고, 메서드 역시 외부에서 요청한 메시지에 응답을 하는 메서드들만 갖게될거에요! 

저는 보통 이런식으로 역할을 나누고 코드를 작성하려해요!

2021-12-24 01:42 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  mutating func prepareBanker() {
`Bank` 객체가 `Banker` 객체 생성의 역할을 가져가기보단 외부에서 `Banker` 객체 인스턴스 배열을 주입해주는게 어떨까요? 

현재는 `Banker` 객체의 생성자가 비어있지만, `Banker`의 기느이 추가될 수록 이에 따라 `Banker`의 생성자도 변화가 있을 수 있을거에요. 그렇게 되면 `Bank`가 `Banker`를 만드는데 필요한 정보까지 알아야하기 때문에, `Bank`가 알고 있어야하는 정보가 너무 많아질것 같아요. 

이렇게 하나의 객체가 많은 정보를 알게된다면, 변경에 취약한 구조를 유발할수있어요

2021-12-24 01:42 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    for _ in 0..<numberOfBankers {
`forEach` 대신 `for-in`을 사용하기로 결정한 이유가 궁금하네요 🤔

2021-12-24 01:42 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    for _ in 0..<numberOfBankers {
스탭2에선 `forEach`를 사용하지 않으시네요?! 이유가 있으실까요?

2021-12-24 01:42 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  func workingTime() -> String {
시간 측정 및 관리를 담당하는 별도의 객체를 만들고, `Bank`에 주입해서 `Bank`가 해당 객체에 의존하게 만드는건 어떨까요?

2021-12-24 01:42 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +      for _ in 1...numberOfClients {
시작 index를 1로 하신 이유가 있을까요?

2021-12-24 01:42 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    for sequence in 1...numberOfClients {
제가 추측했을 때, 출력문에서 "1번째"로 출력을 위해 `index`를 1부터 시작하고 있는 것 같은데요~
출력을 위한 포맷팅은 별도로 출력을 담당하는 곳에서 +1을 해서 출력하는게 더 좋습니다. 

비즈니스 로직과 화면 출력이 강하게 결합되어 있는 부분이라고 할 수 있을 것 같아요. 화면 출력은 화면 출력을 담당하는 곳에서 처리해주는게 더 올바른 역할분배같습니다.

2021-12-24 01:42 UTC, protocorn93 commented on BankManager.swift
> +        var bank: Bank = Bank(numberOfBankers: 1)
메뉴별 실행 코드도 별도의 메서드로 분리하는게 가독성에 더 도움이 될 것 같습니다.

2021-12-24 01:42 UTC, protocorn93 commented on BankManager.swift
> +        isExit = true
비록 한줄자리 코드라도 말이죠! 😊

2021-12-24 01:42 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  let numberOfClients = Int.random(in: 10...30)
이 프로퍼티가는 개방되어있는 이유가 결국 업무 종료 후 결과를 알려주는 문구를 출력할 때 필요해서인 것 같은데요~ 

결국 업무 종료 문구를 외부에서 출력하고 있어서 그런 것 같아요. 업무 종료 문구를 출력하는 것은 `Bank`의 역할로 가져오는게 적절할 것 같아요.

2021-12-24 05:42 UTC, horeng2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  let numberOfClients = Int.random(in: 10...30)
`Bank`의 `doBank()` 내부로 이동했습니다.

2021-12-24 05:42 UTC, Kim-EunsooSilver commented on BankManager.swift
> +      switch choiceMenu {
enum타입으로 정의했습니다!

2021-12-24 05:42 UTC, Kim-EunsooSilver commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  mutating func prepareBanker() {
Banker의 수를 결정하고 생성하는 부분을 BankManager에서 담당하게 수정했습니다. BankManager에서 Banker의 객체 생성 후 Bank객체에 의존성을 주입하고 있습니다.

2021-12-24 05:42 UTC, horeng2 commented on BankManager.swift
> +        isExit = true
```swift
while true {
      let choiceMenu = self.chooseMenu()
      
      switch choiceMenu {
      case Menu.openBank.rawValue :
        operateBank(numberOfBankers: numberOfBankers)
      case Menu.exit.rawValue :
        return
      default :
        print("잘못된 입력입니다. 확인해주세요.")
      }
    }
```

 `isExit = true`를 메서드로 빼서 사용할 방법을 고민했는데, `while`문을 종료하는 조건이 `isExit=true`이기 때문에 메서드의 반환값으로 `true`를 받는다면

`isExit = closeBank()` 와 같은 형식이 되고, 이렇게 사용한다면 가독성과 구조 모두 현재와 다른 점을 못느껴서 위와 같이 수정해봤습니다. 혹시 저희가 생각하지 못한 부분이 있을까요?

2021-12-24 05:43 UTC, horeng2 commented on BankManager.swift
> +        var bank: Bank = Bank(numberOfBankers: 1)
실행코드를 `operateBank`라는 별도의 메서드로 분리했습니다

2021-12-24 05:43 UTC, horeng2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    for sequence in 1...numberOfClients {
`index`를 0부터 시작하고, 출력을 위해서 +1을 해주는 것은 `Banker`에서 처리 후 출력하도록 수정했습니다.

2021-12-24 05:44 UTC, Kim-EunsooSilver commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    for _ in 0..<numberOfBankers {
`forEach`가 아직 손에 익지 않아서 사용하지 않았던 것 같습니다. 😂 피드백 주신 내용으로 `forEach`에 대해서 조금 더 알아보고 사용하기 적절해보이는 곳을 `forEach`로 변경했습니다.

2021-12-24 05:44 UTC, horeng2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +      for _ in 1...numberOfClients {
1번 고객부터 업무를 처리한다는 생각에 이렇게 설계했는데, 아래의 코멘트를 참고하여 함께 수정했습니다!

2021-12-24 05:44 UTC, horeng2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  func workingTime() -> String {
`OperatingTimeManager` 타입을 만들어서 해당 객체에서 시간 측정 및 관리 기능을 담당하도록 하고 `Bank`가 해당 객체에 의존하도록 수정했습니다.

2021-12-24 05:45 UTC, horeng2 commented
## **고민했던 점**

> 은행의 업무시간을 계산하기 위해 Timer 클래스 사용에 대한 고민을 했습니다. 저희가 수시간 동안 연구(?) 해본 결과 저희의 상황에는 맞지 않는 방식으로 결론을 내렸고 CFAbsoluteTimeGetCurrent() 를 사용하여 은행의 업무시간을 계산하였습니다.
> 
- 이 고민의 과정을 좀 더 상세히 알 수 있을까요?? 말씀해주신 사례말고 무언가 더 있을 것 같아서요 🤔

→ **`scheduledTimer(withTimeInterval:repeats:block:)`**  을 사용하는 것을 시도했습니다. **`withTimeInterval`** 에 지정한 시간마다 block내부의 코드를 실행하도록 하였습니다. block내부에서는 timeCount라는 변수에 0.01을 더해주는 코드를 작성했습니다.

2021-12-26 11:48 UTC, protocorn93 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    for _ in 0..<numberOfBankers {
잘하셨어요! 👍 고차함수를 적극적으로 활용해보는걸 연습해보세요!

2021-12-26 11:49 UTC, protocorn93 commented on BankManager.swift
> +        isExit = true
네네 이 방법이 훨씬 간결한것같아요!

2021-12-26 12:22 UTC, merged