은행 창구 매니저 [STEP 2] 아리, 허황
yagom-academy/ios-bank-manager pull request #115
Opened 2021-12-24 02:59 UTC by hwangjeha

# PR

안녕하세요 델마 @delmaSong  🙌🏻
아리 @leeari95 , 허황 @hwangjeha입니다.
은행 창구 매니저 프로젝트 STEP 2 구현 완료해서 PR 보냅니다. 😊
타입간의 책임 분리를 위해 많은 고민을 했던 부분이 있어서 그 부분에 대한 조언이 꼭 필요합니다!!!
이번 피드백도 잘부탁드립니다~ 🙇🏻‍♀️

궁금했던 점, 조언이 필요한 부분 이 외에 저희가 놓친 부분이나 부족한 부분이 있다면 번거롭더라도 한번 더 짚어주시면 감사하겠습니다.🙏🏻

## 고민했던 점

### 1. SOLID의 단일 책임 원칙

- 구현한 타입들 각각 하나의 책임만 갖도록 고민해보았습니다.
    - `출력문`까지도 은행원, 은행이 해야할 일이 아니라고 판단되었기 때문에 따로 출력만 하는 타입(ViewController)을 만들어 `Delegate 패턴`을 활용하여 분리해주었습니다.
    - 요구사항 예시에 맞춰 출력을 해주기 위해 NumberFormatter를 활용하는 부분이 필요했는데, 이 부분은 은행에서 직접 처리하는 건 적합하지 않다는 생각이 들었습니다. 따라서 따로 타입으로 빼주어 static 메소드로 구현해주었습니다.

### 2. 순환참조

- `Delegate 패턴`을 사용하기 위해서 `모델 타입` 별로 `viewController`를 만들어주었습니다.
    - `모델 타입`은 `delegate`로 `viewController`를 가지고 있고 `viewController`은 자기 자신을 `delegate`로 넘겨주기 위해 `모델 타입`을 가지고 있어 `순환 참조`가 발생합니다.
    - `모델 타입`의 `delegate`를 weak 키워드(약한 참조)를 사용해 `순환참조`를 해결할 수 있습니다.
- Delegate 패턴 작성시 네이밍에 대한 고민을 해보았습니다.
    - 구글의 [Swift Style Guide](https://google.github.io/swift/#delegate-methods)를 참고하여 네이밍을 하였습니다.
        
        > The term “delegate’s source object” refers to the object that invokes methods on the delegate. For example, a `UITableView` is the source object that invokes methods on the `UITableViewDelegate` that is set as the view’s `delegate` property.
        > 

## 궁금했던 점 / 조언이 필요한 부분

- Delegate 패턴 구현을 위해 기존 모델 타입에 변경사항이 생겼는데 이게 올바른 것인지 잘 판단이 서질 않습니다.
    - 기존 구조체였던 타입들을 `class`로 변경해준 부분이 추후 retain count 추적 비용이 발생할 것이라는 우려가 생겼는데요. 이 부분에 대한 델마의 생각이 궁금합니다.
- Delegate 패턴 사용시 강한 순환 참조 발생을 예방하기 위해 weak 키워드를 사용해주었더니 와일드카드 패턴으로 생성한 인스턴스가 생성과 동시에 해제가 되었습니다.
    - 인스턴스를 생성한 후 참조를 하지 않는다면 weak 키워드 보다는 와일드카드 패턴을 사용하는 것이 적합한 것일까요?
    - weak 키워드를 사용하고 와일드 카드 패턴을 사용하지 않는다면 생성 후 호출되지 않는 인스턴스에 xcode 경고가 뜨는 문제가 있습니다. 사용하지 않는 인스턴스에 뜨는 경고 문구를 안뜨게 하는 방법이 있는지도 궁금합니다🧐
        
       
    ![image](https://user-images.githubusercontent.com/27428188/147310209-7561b51d-cb6b-4e3d-8f5e-bf2bcd6f6945.png)

        
        ```swift
        final class Bank {
            private let bankClerk: BankClerk
            private var customerQueue = Queue<Customer>()
            var delegate: BankDelegate?
        ...
        }
        
        func run() {
            let bankClerk = BankClerk()
            let bank = Bank(bankClerk: bankClerk)
            let bankManager = BankManager(bank: bank)
            let _ = BankClerkViewController(bankClerk: bankClerk)
            let _ = BankViewController(bank: bank) 
        ...
        }
        ```
        
- 단일 책임 원칙에 맞게 역할을 Delegate 패턴을 활용하여 분리해주었습니다. 하지만 확장성을 고려했을 때 이게 올바르게 설계한 것이 맞는지 너무 오버 엔지리어닝한 부분은 아닌지 판단이 어렵습니다. 이 부분에 대해 델마의 조언이 필요합니다!

아직 많이 부족하지만 잘 부탁드리겠습니다. 😁

2021-12-24 14:24 UTC, delmaSong requested changes
아리 허황 안녕하세요 😃
객체의 역할을 분리하려는 노력이 눈에띄는 코드였습니다 👍🏼
Delegate 패턴 자체 사용이나 네이밍등은 알맞게 해주신 것 같아요.
Xcode warning은 lint를 이용해 경고가 뜨는 세부 규정을 수정해주는 방향으로 안뜨게 만들 수 있을 것 같네요.
그리고 궁금하다고 하신 점 포함해 제가 코드를 보면서 개선하면 좋을만한 점에 대해서는 아래 코멘트를 남겼으니 확인해주세요 😃 수고많으셨습니당

2021-12-24 14:24 UTC, delmaSong commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        }
`Date`가 아니라 `CFAbsoluteTime`을 사용하신 이유가 무엇인지 궁금합니다.

2021-12-24 14:24 UTC, delmaSong commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManagerViewController.swift
> +
무슨 플래그인지 더 명확하면 좋겠어요

2021-12-24 14:24 UTC, delmaSong commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        delegate?.bankClerk(DidFinishWork: customer.waitingNumber)
작업에 시간차를 두는 방법에 `Thread.sleep` 말고 또 무엇이 있었나요?
그리고 `Thread.sleep`을 선택하신 이유와 기준이 무엇인지 궁금합니다.

2021-12-24 14:24 UTC, delmaSong commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    while bankManagerViewController.isFlag {
음.. 제가 코드를 보고 추측하기로는 각 역할에 따른 작업과 콘솔에 출력하는 작업을 분리하고자 ~ViewController 타입을 생성하신 것 같아요.
콘솔 출력까지도 역할을 나누고자 하신 점은 좋았으나 콘솔 앱에서까지 출력을 분리? 라는 생각이 들었어요.
좋은 시도라고 생각은 해요. 그런데 pr description에 적어주신 것 처럼 생성만 되면 되는 객체를 이렇게까지(할당하지 않으면 바로 해제되고, 사용하지 않을건데 변수에 할당해 warning을 받는) 만들어야 하나? 
콘솔 출력을 분리하고 싶었다면 차라리 BankManager나 Bank가 모두 출력을 위한 각각의 ~ViewController에 동작을 전달하니까 출력만을 위한 객체가 별도로 존재해서 메시지등을 전달받아 출력하는 역할만을 하도록 만드는 건 어땠을까 싶어요

그리고 추후 UI에 적용하기 위해 이런 방식을 이용했다고 하셨는데, Bank나 BankManager별로 각각의 화면을 가지게 될까요?
아니면 한 화면 내에서 은행, 은행원, 고객이 함께 보여질까요? 지금은 잘 모르겠죠? ㅎㅎ

되도록 현재 단계에서 요구하는 부분까지만 최소한으로 구현하는 것이 좋을 것 같아요. 내가 다음 단계의 요구사항을 지레짐작해 구현한다면 내 예상과 같다면 정말 다행이겠지만 그러지 않을 확률이 크고, 요구사항이란 자주 바뀌게 될 가능성이 매우 크거든요. 그래서 현재 단계에서 명확하게 정해진 부분까지만 구현을하고 다음 단계는 그 다음에 생각하는 것이 좋을 것 같아요.
최소한의 기능만 빠르게 작업해버릇하는 습관을 들이시길 추천드립니다. 내 예상과 다르면 1차적으로 작업하느라 고생이고 또 다시 수정하느라 두번 일하게 되는거니까요.

2021-12-26 11:49 UTC, hwangjeha commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankClerkViewController.swift
> +class BankClerkViewController {
ConsoleApp에서 출력문은 UIApp의 View라고 생각했고, 사용자의 입력을 받는 부분은 Controller라고 생각해 ConsoleApp에도 ViewController 타입을 생성해 주었습니다.
추후 프로젝트의 구조를 개선하면서 다시 한번 네이밍은 고민해 보겠습니다.

2021-12-26 11:51 UTC, leeari95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/BankManagerDelegate.swift
> +}
오.. 참고해서 한번 개선해보도록 하겠습니다!

2021-12-26 11:52 UTC, leeari95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/BankClerkDelegate.swift
> +}
헉.. 놓친부분이 있었네요! 짚어주셔서 감사합니다 ☺️

2021-12-26 12:03 UTC, leeari95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Message.swift
> +enum Message {
뱅크매니저에서만 사용하는 상수로 BankMenagerMessage 라는 이름으로 수정하였습니다!

2021-12-26 12:07 UTC, hwangjeha commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Message.swift
> +                          2 : 종료
Menu 타입의 타입 프로터티로 `1`,`2`을 대체해서 개선해 보았습니다.

2021-12-26 12:22 UTC, leeari95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/DecimalNumberFormatter.swift
> +        return totalTime
이 부분은 구지 NumberFormatter 인스턴스를 생성해가며 포맷팅 하지 않아도 된다는 판단이 들어서 Double 타입을 확장 시켜주는 방법으로 개선해보았습니다.
(이번 프로젝트 예시는 소수점 2자리까지만 보여주면 되기 때문에 String의 format을 활용해도 충분히 충족 가능하다는 생각이 들었습니다.)

2021-12-26 12:43 UTC, leeari95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        }
일단 처음에 사용할 때에는 구글링을 해서 가져다가 쓴 메소드인데요.
델마의 피드백을 받고 다시한번 찾아보니 Date는 Foundation, CFAbsoluteTime은 Core Foundation에 위치하고 있네요.
이 둘의 [차이점](https://stackoverflow.com/questions/3773776/corefoundation-vs-foundation)을 한번 찾아보았는데요.  
메모리 누수 관련 이유 때문에, 그리고 Foundation 없이는 앱을 개발하기 어렵다는 이유 등등...
많은 프로그래머가 Core Foundation의 기능보다는 Foundation의 기능을 선호한다는 [이야기](https://stackoverflow.com/questions/20582495/core-foundation-vs-foundation-or-core-foundation-foundation)인 것 같습니다.
따라서 저희는 Date를 활용하여 시간측정을 하면 좋을 것 같다는 결론이 나왔는데.. 이 부분에 대해서 잘 찾아본 것이 맞는지 조언좀 부탁드립니다!

2021-12-26 12:56 UTC, hwangjeha commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManagerViewController.swift
> +
isRunning로 변경했습니다.😊

2021-12-26 13:26 UTC, leeari95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        delegate?.bankClerk(DidFinishWork: customer.waitingNumber)
Thread.sleep를 선택한 이유는 이 방법 외에는 다른 방법으로 딜레이를 주는 방법을 모르고 있던 상황이였습니다.

그래서 다른 방법을 찾아보았더니 딜레이 주는 방법은 두가지가 더 있는 것 같습니다.

- 타이머를 활용하는 방법
- DispatchQueue.main.asyncAfter를 활용하는 방법

이 두가지 방법을 적용해보려고 했으나... 
Timer의 경우 RunLoop를 직접 실행하도록 관리해야하는 부분 때문에
`Thread.Sleep`으로 간단히 스레드를 잠재우는 것이 더 낫다는 판단이 들었고,
DispatchQueue.main.asyncAfter도 사용해보았으나 내부 코드가 아예 실행되지 않는 문제를 마주하게 되었습니다.
이 부분에 대해서 해결해보려고 했으나... 해결하지 못했어요. 조언 부탁드리겠습니다!

```swift
// BankClerk 내부 메소드 ...
    func work(for customer: Customer) {
        delegate?.bankClerk(didStartWork: customer.waitingNumber)
        DispatchQueue.main.asyncAfter(deadline: .now() + workSpeed) {
            self.delegate?.bankClerk(didFinishWork: customer.waitingNumber)
        }
    }
```

2021-12-27 06:50 UTC, delmaSong approved these changes
코멘트 달아주신 사항은 구두로 이야기 마쳤습니다.
메인쓰레드 관한 건 메인 쓰레드의 역할을 한번 찾아보시면 도움이 될 것 같아요! 그래도 모르겠다 싶으시면 dm 주세요 ㅎㅎ
수고 많으셨습니다! 다음 스텝에서 뵈어요 😃👍🏼

2021-12-27 06:50 UTC, merged