은행 창구 매니저 [STEP 2] 제인, 차차
yagom-academy/ios-bank-manager pull request #118
Opened 2021-12-24 07:49 UTC by siwonkim0

안녕하세요 찰리 @kcharliek 🙇‍♀️
은행 창구 매니저 Step 2 완료하여 PR 보내드립니다.
이번 스텝에서는 객체간 역할을 분리하기 위해 delegate 패턴을 적용해보았는데 하다보니 코드가 너무 복잡해진게 아닌가라는 생각이 듭니다. ㅜㅜ
그래서.. 구현한 코드 흐름을 최대한 알기 쉽게 UML로 표현해보았습니다 !

정말 개선할 점이 많을 것 같습니다. 😅
잘 부탁드립니다! 👍

## 구현 흐름 (UML)

![](https://i.imgur.com/0ULWxpO.jpg)

## 고민했던 부분

### 1. 객체 지향 프로그래밍에 대해

객체들은 각각 역할과 책임을 갖고, 서로 메시지(요청)를 보내 협력할 수 있도록 구현해보고자 했습니다. 

- `BankClerk` (= 은행원)
    - 고객 업무 처리 진행
    - 은행에게 업무 마감을 알림
- `Bank` (= 은행)
    - 고객 queue 보유
    - 은행원에게 일을 시작할 것을 알림
    - 은행 업무 종료 관리 
- `BankManager` 
    - 은행 개점
    - 은행의 고객 queue를 채우는 기능 
    - 사용자에게 출력되는 기능 담당 
- `Customer` (= 고객)
    - 대기열 번호 보유
    - 업무 처리에 소요되는 시간 보유

요구사항에서는 은행/고객 타입만 있었지만, 은행 내에서 실질적으로 작업을 처리하는 은행원 타입을 추가해봤습니다.

 또한 최대한 위 구조를 기반으로 코드로 옮겨보려고 노력했습니다. 

### 2. Delegate 패턴 구현에 대한 부분 
두 가지 부분에 대해 Delegate 패턴을 사용하였습니다.
1. `Bank` <-> `BankClerk`
: 서로 작업을 요청하고, 작업이 종료됨을 알리기 위해 사용했습니다
2. `Bank`와 `BankClerk` -> `BankManager` (`BankDelegate`, `BankClerkDelegate` 프로토콜 채택)
: `Bank`와 `BankClerk`가 사용자에게 보여줄 메세지를 직접 프린트하지 않고 `BankManager`에서 대신 해주기 위해 사용했습니다. (추후 UIApp으로 전환시, 현재 print되고 있는 부분들이 UI요소와 연결될 부분이라고 생각하였습니다.)

### 3. Delegate 패턴의 순환참조 방지

`Bank`와 `BankClerk`가 서로 참조하고 있는 구조가 되어 순환 참조가 발생하여 메모리 누수가 발생할 수 있을거라 생각했습니다. 

이에 `BankClerk`가 가지는 `bank`를 `weak`로 구현하여 메모리 누수를 방지해주었습니다.

## 질문드리고 싶은 부분 

### 1. Delegate 패턴 

저희가 구현한 것 처럼 delegate 패턴을 적용하게 되면 실행 흐름을 쉽게 알아보기 어려울 것 같다는 생각을 했습니다. 

 A객체가 B객체에 요청하여 하나의 작업이 수행되는 것이 아니라, A객체가 요청하면 B객체를 거쳐 C객체에서 처리되는 듯한 구조로 보여, 이러한 구조가 바람직하지 못한 것인지, 그렇다면 어떤 방식으로 개선할 수 있을지 궁금합니다. 

저희 프로젝트의 예시로 보자면 `Bank` 타입에서 업무를 모두 하기보다는 실질적인 업무 처리를 `BankClerk` 타입에서 할 수 있도록 구현했습니다. 

결과적으로 `Bank` 타입이 `BankClerk`와 `BankManager` 사이에서 중간자(?) 역할을 하게 되는 것 같다고 생각했습니다. 이에 `BankClerk` 타입을 제거하고, 모두 `Bank`에서 처리하도록 해줘야 할 지 고민했으나, 그래도 각각의 역할이 분담되는 것이 추후에 개별적으로 담당하는 기능이 추가된다거나 할 때 이점이 있지 않을까 생각하여 이와 같이 구현하게 되었습니다.

### 2. Delegate 패턴 구현시 상호 의존도에 대한 부분

`Bank`와 `BankClerk` 사이에서 delegate 패턴을 구현하면서 각각 서로의 타입을 알고 있도록 구현하였습니다. 이에 상호 의존도가 올라가게 되어 의존성이 높은 코드가 될 거라고 생각했습니다. 

이에 각각을 지칭할 수 있는 프로토콜을 생성하여 특정 타입이 아니라 추상 타입에 의존하도록 해야하나 고민했으나, 현재와 같이 특수한 "은행~은행원" 관계만을 위한 구현에서는 오버엔지니어링이 될 것 같다는 우려가 있었습니다. 

이러한 상황에서도 의존성을 고려해서 프로토콜을 생성하여 관계를 구현해줘야 하는 것인지 궁금합니다!

### 3. 확장가능성에 대한 부분 

프로젝트를 진행하며 추후 Step이 남아있음을 알고 있어서 그런 것인지, 최대한 확장 가능한 코드를 짜야한다는 생각을 하게 되는 것 같습니다. 이에 처음에는 굳이 필요하지 않은 protocol을 생각해보기도 하는 등 너무 멀리보는(?) 듯한 느낌이 들었습니다. 

현업에서는 어느정도로 추후의 상황을 가정하고 확장 가능하게 구현하시는지, 선택하는데 있어 기준이 있는지 궁금합니다

2021-12-26 03:31 UTC, kcharliek commented
### 고민했던 부분

1. 객체 지향 프로그래밍에 대해

은행에 은행원이 있는 건 당연하죠. 실제 은행을 기준으로 각각의 역할을 고민하셨고, 이를 코드로 옮기려고 한 방향에 대해 칭찬 해드리고싶습니다. Real World 는 치밀하게 설계되었고 이미 검증된 결과로, 이를 코드로 옮겼을 때 좋은 구조가 나올 것은 자명합니다. 잘 하셨습니다.

2. Delegate Pattern 고민 잘 해주셨고 현재 구조에 대해 이견없습니다. Delegate Pattern -> weak 를 어쩌면 공식화할 수도 있겠습니다만, 이를 고민없이 당연하게 쓰는 건 지양해야할 것입니다. 잘 해주셨고 지금처럼 메모리 관점에서 계속 생각 해주세요.

2021-12-26 03:45 UTC, kcharliek commented
### 질문에 대한 답변

1, 2. Delegate Pattern 에 대해

이 부분은 코드레벨로 검토해보고 코드 쪽에서 코멘트드리겠습니다.

3. 확장 가능성에 대해

https://github.com/yagom-academy/ios-exposition-universelle/pull/106#issuecomment-987492521 쪽에 코멘트 드렸던 부분이 있습니다. 참고해보시고 부족한 내용이 있다면 Discord로 추가 답변 드리겠습니다!

2021-12-26 03:59 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Extension/Double+format.swift
> +    var formatted : String {
`formatted` 기능 확장이 아니라 특정 스펙 구현을 extension으로 했다고 생각해요. 특정 기능을 위한 extension 인 만큼 이를 재사용하기 어려울 것 같은데요. 저는 재사용하기 어려운 extension에 대해서 부정적입니다. 기능 구현을 extension으로 해야할 경우 사용하는 파일에서 private extension으로 구현하고 다른 파일에서는 인덱싱 되지 않도록 숨기는 것이 좋다고 생각합니다.

어떻게 formatted 되었는지, 이름을 보고 유추하기 어렵습니다.
format type을 enum으로 정의해두고 이를 주입받는 식으로 구현 해보

2021-12-26 03:59 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var customerQueue: Queue<Customer> = Queue<Customer>()
변하지 않는 값은 let으로 정의 해주세요.

2021-12-26 04:02 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var delegate: BankDelegate?
Delegate Method는 내 Method지만 이를 다른 곳에 위임할 뿐입니다. BankDelegate 는 Bank의 것이니 Bank file안에 함께 있으면 맥락을 이해하기 좋을 것 같습니다.

2021-12-26 04:06 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        self.bank.bankClerk.delegate = self
`self.bank.bankClerk.delegate` 이 스타일이 괜찮은지 여쭤보신 것이군요.
저는 이런 구조가 된 것이 BankManager 가 Bank의 기능을 가져갔기 때문이라고 생각합니다. 
BankManager와 Bank를 합칠 수 있을까요. 제 생각에는 은행이 최상위 기능이 되어도 될 것 같은데요. 이를 누군가가 꼭 들고있어야할까요.

2021-12-26 04:15 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        Thread.sleep(forTimeInterval: TimeInterval(customer.processingTime))
Current Thread가 Main이라면 Main이 잠자게 될 수도 있을 것 같은데요. Thread 를 Sleep하지 않고 다른 방법으로 처리할 수 있을까요. 꼭 잠자는 Thread가 Main이 아니더라도 Thread가 아무일도 하지 않는 식의 처리는 리소스 낭비같습니다.

2021-12-26 04:24 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    weak var bank: Bank?
관계를 생각해보면 Bank는 부모, BankClerk는 자식이라고 할 수 있을 것 같은데요. 자식이 부모를 알고있는 상황은 바람직하지 않습니다. 그 밖에 view가 VC를 알고 있는 상황도 같은 맥락에서 좋지 않아요. 이 때 많이 사용하는 패턴이 Delegate Pattern입니다. bank 참조를 제거하고 Delegate Pattern을 사용하는 방향으로 다시 고민해봐주세요.

2021-12-26 04:29 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    func printBeginWorkMessage(of customer: Customer) {
객체로부터 Print 메서드를 분리해내고싶다면, BankManager 와 같은 곳에 짬처리(?) 하는 것 보다 BankPrinter를 두어 주입하는 식으로 해보는 것은 어떨까요.

2021-12-26 04:35 UTC, kcharliek requested changes
1. Bank와 BankManager를 합치는 것. (혹은 BankManager를 더 쪼개서 나누는 것)
2. BankPrinter를 두는 것

위 두개를 필수 수정 내용으로 하겠습니다.

2021-12-27 05:52 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var customerQueue: Queue<Customer> = Queue<Customer>()
`let`으로 변경하도록 하겠습니다!

2021-12-27 05:54 UTC, siwonkim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var delegate: BankDelegate?
오오 그렇게 하면 이해가 쉬울 것 같아요. BankDelegate는 bank에 BankClerkDelegate는 clerk에 합치겠습니다 ~!

2021-12-27 06:41 UTC, siwonkim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var customerQueue: Queue<Customer> = Queue<Customer>()
수정하였습니다!

2021-12-27 06:44 UTC, siwonkim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        self.bank.bankClerk.delegate = self
팀원과 이야기해본 결과 Bank가 최상위기능이 되어도 될 것 같다고 판단하여 BankManager을 삭제하고 customerQueue를 셋업하는 역할을 Bank가 하도록 수정하였습니다.

2021-12-27 06:44 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    func printBeginWorkMessage(of customer: Customer) {
말씀해주신 것 처럼 Manager가 너무 포괄적인 의미를 가지는 것 같습니다..! 이에 특정 기능에 중점을 두도록 하여 `BankPrinter`를 만들어 각각 프로토콜을 채택해주었습니다.

2021-12-27 06:53 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Extension/Double+format.swift
> +    var formatted : String {
`BankPrinter`내에 `private extension`으로 구현해주어 해당 파일내에서만 사용하는 기능으로 제한하였습니다.

2021-12-27 06:59 UTC, siwonkim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Extension/Double+format.swift
> +    var formatted : String {
double extension을 private extension으로도 해보고 fileprivate extension으로도 변경해보았는데요, private 이나 fileprivate 이나 같은 파일 내에서는 extension의 기능을 동일하게 사용할 수 있다는 사실을 확인하였습니다. private의 경우 정의된 scope내에서만 기능을 사용할 수 있다고 알고있었는데 한 파일 안에서 다른 scope에서도 기능 사용이 어떻게 가능한 것인지 의문점이 들었습니다. 
<img width="744" alt="스크린샷 2021-12-27 오후 3 58 10" src="https://user-images.githubusercontent.com/60725934/147443946-0f76f73b-6c85-4625-b9c5-45b0e374ac83.png">
 또한 private extension 으로 접근제어자를 설정해주었는데 다른 파일에서 사용하려고 하면 fileprivate 레벨이라서 사용이 불가능하다는 에러 메세지가 뜨는데, 이런 경우 private와 fileprivate 를 동일하게 취급하기 때문에 그런건지도 궁금합니다!

2021-12-27 07:25 UTC, siwonkim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    weak var bank: Bank?
Transactionable 프로토콜을 생성하였고 자식이 부모를 들고있지 않게 만들어주기위해
BankClerk에서 bank 프로퍼티의 타입을 Transactionable 로 변경해주었습니다~!

2021-12-27 09:10 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        Thread.sleep(forTimeInterval: TimeInterval(customer.processingTime))
말씀주신 것 처럼 현재 어떤 쓰레드가 sleep이 되는지 확인이 어렵다는 점, 그리고 자원을 비효율적으로 사용할 수 있다는 점에서 DispatchGroup, DispatchWorkItem을 사용하여 해결해봤습니다. 

시간의 딜레이가 필요한 부분은 DispatchGroup의 `wait()` 메서드를 사용하여 대체했습니다. 직접적으로 Thread를 정지시킨다기보다는, 특정 group의 작업이 끝나기를 동기적으로 기다린다는 것으로 이해했는데, 이렇게 개선하는 방식이 바람직한지 궁금합니다!

2021-12-27 09:14 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var delegate: BankDelegate?
delegate method 'weak' 참조 확인 부탁드립니다.

2021-12-27 09:19 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    let bank = Bank(bankClerk: bankClerk)
main에서 Bank를 생성하는 로직이 조금 부담스러운데요.
Bank 내부에서 모두 세팅하는 식은 어떨까요.

혹은 Bank가 Printer정도만 들고있고,
Bank와 BankCleark의 생성 & 주입은 Factory가 해도 괜찮을 것 같습니다.

2021-12-27 09:23 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    var delegate: BankClerkDelegate?
weak 참조 확인부탁드립니다.

2021-12-27 09:25 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var delegate: BankDelegate?
앗 놓친 부분이 있었네요..! delegate pattern이 사용되는 부분에는 `weak` 참조를 주겠습니다!

2021-12-27 09:26 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var customerQueue: Queue<Customer> { get }
customerQueue 를 직접 넘겨주는 것이 과하다는 느낌이 듭니다.
get으로 넘겨주기는 하지만, reference이기 때문에 dequeue와 같은 수정 동작은 여전히 처리가능하고요. 사이드 이펙트가 발생할 수도 있을 것 같습니다. method로 기능을 제공하는 것은 어떨지 고민 부탁드립니다.

2021-12-27 09:27 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    var delegate: BankClerkDelegate?
위에서 언급주신 것 처럼 동일하게 `weak` 참조 달아주도록 하겠습니다!

2021-12-27 09:27 UTC, kcharliek approved these changes

2021-12-27 09:29 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    weak var bank: Bank?
Transaction이라는 단어가 개발쪽에서 여러 의미를 담고있는 만큼 처음 봤을 때 바로 이해가 되지 않았습니다. BankTransactionable 정도로 명확하게 하는 건 어떨지 제안드려봅니다.

2021-12-27 09:31 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        Thread.sleep(forTimeInterval: TimeInterval(customer.processingTime))
물론입니다. 저는 Timer를 썼을 것 같기도 하고요. 다른 방법들도 있을 것 같은데 좋은 방법 선택하셨습니다.

2021-12-27 09:34 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/Extension/Double+format.swift
> +    var formatted : String {
같은 파일에서 정의했다면, scope가 파일이되고요. 이 때 private과 fileprivate은 동일하게 취급합니다.

2021-12-27 12:25 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    weak var bank: Bank?
말씀주신 것 처럼 조금 더 명확한 `BankTransactionable`로 변경했습니다!

2021-12-27 12:26 UTC, ChaminLee commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var customerQueue: Queue<Customer> { get }
말씀주신 사이드 이펙트를 고려하여, 큐를 관리하는 메서드를 bank내에 만들어 이를 넘겨주도록 수정하였습니다! 
이에 customerQueue에서 dequeue하여 전달해주는 `dequeue` 메서드 하나, 큐가 비어있는지 확인하는 `isCustomerQueueEmpty` 메서드를 생성하였습니다.

2021-12-27 13:18 UTC, siwonkim0 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    let bank = Bank(bankClerk: bankClerk)
파라미터로 BankPrinter 인스턴스를 전달받아서 Bank 인스턴스를 생성하는 BankFactory 타입을 만들어주었습니다! 
```swift
struct BankFactory {
    static func createBank(with delegatee: BankPrinter) -> Bank {
        let bankClerk = BankClerk(delegatee: delegatee)
        let bank = Bank(bankClerk: bankClerk, delegatee: delegatee)
        
        return bank
    }
}
```

main에서는 BankFactory.createBank로 생성된 bank 인스턴스를 불러옵니다.
```swift
let bankPrinter = BankPrinter()
let bank = BankFactory.createBank(with: bankPrinter)
```

2021-12-27 13:29 UTC, merged