은행 창구 매니저 [STEP 2] yeha, 호댕
yagom-academy/ios-bank-manager pull request #121
Opened 2021-12-24 14:06 UTC by yanghojoon

안녕하세요. 도미닉! **[@AppleCEO](https://github.com/AppleCEO)**

은행 창구 매니저 Step 2 PR 요청 드립니다!

하루 종일 설계하고, 작성하고, 리팩터링을 해보았는데요. 
많은 고민을 했어서 작은 부분이라도 개선할 방향을 이야기해주시면 저희에게 큰 도움이 될 것같습니다. 🙏 

이번 PR도 잘 부탁드립니다. 감사합니다 🙇

## 고민했던 점

### 고객

- 고객 모델을 어떻게 구현할지 고민했습니다. 동료들과 대화를 통해 리팩터링하여 최종적으로 이렇게 구현했습니다.
    
    ```swift
    struct Client {
        let clientNumber: Int
        
        init(_ clientNumber: Int = 0) {
            self.clientNumber = clientNumber
        }
    }
    
    struct Clients {
        private var waitingLine = Queue<Client>()
    		...
    }
    ```
    
- 그리고 `Bank Manager` 와 메서드를 통해 협력할 수 있게 구현해보려고 노력했습니다.

### Protocol

- POP의 개념을 배워서 사용해보려고 했습니다. 처음에는 `BankClerk` 내부에 해야 하는 일을 구현을 해줬습니다. 하지만 `BankManager`에서도 `BankClerk`의 인스턴스를 생성해서 사용해줘야 하는 만큼 타입 간의 의존성이 높아진다고 판단했습니다.
- 그래서 어떤 일을 해야하는지 프로토콜로 구현한 후 extension을 통해 default implement를 해주었습니다. 이렇게 해당 프로토콜을 채택하는 객체는 내부에 메서드를 따로 작성하지 않아도 적합한 일을 할 수 있도록 구현해줬습니다.
    
    ```swift
    protocol Workable {
        func work(for client: Int)
    }
    
    extension Workable {
        func work(for client: Int) {
            print("\(client)번 고객 업무 시작")
            Thread.sleep(forTimeInterval: 0.7)
            print("\(client)번 고객 업무 완료")
        }
    }
    ```
    

### Dispatch Queue

- `Dispatch Queue`를 어디에 생성해야 할 지 고민했습니다.
    
    처음에는 직접 일을 하는 `BankClerk`에 `Dispatch Queue`를 생성하도록 구현했습니다. 
    하지만 `Dispatch Queue`가 일을 시켜야 하는 만큼, `BankManager`에서 `Dispatch Queue`를 생성해서 `BankClerk`에게 일을 시킬 수 있도록 수정했습니다. 
    
- 저희가 수정한 내용은 아래와 같습니다.
    
    `BankManager` 가 `Managable` 프로토콜을 채택하고 있습니다. 
    
    ```swift
    protocol Managable {
        func giveWork(to clerkNumber: Int) -> DispatchQueue
    }
    
    extension Managable {
        func giveWork(to clerkNumber: Int) -> DispatchQueue {
            return DispatchQueue(label: "clerk\(clerkNumber)")
        }
    }
    ```
    
    `giveWork` 메서드에서 DispatchQueue를 만들어서 반환하고 있습니다. 
    
    ```swift
    private func manageClerk(_ clerkNumber: Int, for client: Int) {
            giveWork(to: clerkNumber).sync {
                clerk.work(for: client)
            }
        }
    ```
    

### 코드 실행에 따른 소요 시간 계산

- 코드 실행에 따른 소요 시간을 어떻게 계산할 지에 대해 고민했습니다. 
처음에는 실행에 걸리는 0.7초의 시간에 고객 수를 곱하여 계산하려고 했으나, 이렇게 계산할 경우 약간의 연산 딜레이를 포함하지 못했고, 여러 쓰레드가 일을 하게 된다면 이에 대응할 수 없었습니다.
- 따라서 업무를 시작하고 끝나는 시간을 `CFAbsoluteTime` 을 통해 받아온 뒤 이 둘의 차이를 계산할 수 있도록 구현했습니다.
    
    ```swift
    mutating private func dequeueWaitingLine() {
        let startTime: CFAbsoluteTime = CFAbsoluteTimeGetCurrent()
            
        while clients.startTask() > Bank.emptyWaitingLine {
            manageClerk(clerkNumber, for: clients.startTask())
            clients.completeTask()
        }
          
        let endTime: CFAbsoluteTime = CFAbsoluteTimeGetCurrent()
        duration = endTime - startTime
    }
    ```
    

---

## 조언을 얻고 싶은 부분

### 네이밍

- enum Menu에서 은행 상태를 고려해서 open, close로 사용했는데 따로 명사로 구현하는 것이 좋을까요?

### 파일 분리

- 어떤 방법이 좋을지 고민하다가 아래 방법들을 시도해보았습니다. 
권장하지 않는 방법, 더 좋은 방법이 있다면 조언 부탁드립니다.
    - 타입 별로 폴더링을 시도해보았습니다.
    - `Double + NumberFormatter`
        - extension의 이름과 하는 일로 제목을 붙이는 방법이 있다는 것을 알게 되어 시도해보았습니다.

### main.swift 내에서 함수 배치

- 함수를 호출 순서대로 배치하는 것과 중요한 순서대로 배치하는 것 중 고민했습니다.
저희는 아래처럼 호출 순서대로 배치를 해보았습니다. 
도미닉은 파일 내에서 함수를 어떤 순서로 배치하시는지 궁금합니다.
    
    ```swift
    fileprivate func printMenu() {
        print(Menu.initialMessage, terminator: " ")
    }
    
    fileprivate func receiveInput() -> String {
        guard let input = readLine() else {
            return Menu.Option.invalidInput
        }
        
        return input
    }
    
    fileprivate func runMenu(with input: String) {
        var bankManager = BankManager(clerkNumber: 1)
    
        switch input {
        case Menu.Option.open:
            bankManager.operateBankSystem()
            printMenu()
            runMenu(with: receiveInput())
        case Menu.Option.close:
            return
        default:
            print(Menu.Error.wrongInput)
            printMenu()
            runMenu(with: receiveInput())
        }
    }
    
    printMenu()
    runMenu(with: receiveInput())
    ```

2021-12-26 14:41 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.
@ye-ha , @yanghojoon 고생하셨습니다~!
POP 를 활용한 부분 인상적이었습니다.
몇가지 코멘트 남겨놨으니 고민해보면 좋겠습니다!

질문에 대답
enum Menu에서 은행 상태를 고려해서 open, close로 사용했는데 따로 명사로 구현하는 것이 좋을까요?
- 보통 open, close 같은 일반적인 명사는 다른 예약어로 활용되고 있을 가능성이 높아서 사용을 조심하는 것이 좋습니다. open 의 경우에는 아시는 것처럼 접근제어자로도 사용되는 명사라서 잘못 사용하면 오류를 일으키거나 혼돈을 일으킬 수 있습니다.

extension의 이름과 하는 일로 제목을 붙이는 방법이 있다는 것을 알게 되어 시도해보았습니다.
- 네 그런 방식은 현업에서도 많이 쓰이는 것으로 알고 있습니다. 객체, 타입 별로 파일을 따로 만드는 방법 좋습니다~

도미닉은 파일 내에서 함수를 어떤 순서로 배치하시는지 궁금합니다.
- 보통 뷰컨트롤러 등 객체 안에서 함수를 만드는 경우가 많아서 그런 경우를 기준으로 말씀드리겠습니다. 객체 안 에서 함수를 만들면 호출되는 순서를 참고는 하지만 그 순서가 그렇게 중요하지는 않습니다. 어차피 객체가 다 선언이 되고 사용이 되기 때문에 순서가 다르다고 오류가 발생하지는 않습니다. 예를 들어주신 부분은 다른 객체를 만들어 그 객체 안에서 메소드로 선언해주면 더 좋을 것 같습니다.

2021-12-26 14:41 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Clients.swift
> +    let clientNumber: Int
보통 객체명과 같은 단어는 이름에서 빼는 편입니다.
그냥 number 라고만 하면 어떤 번호인지 헷갈릴 수는 있겠는데요.
어떻게 이름을 정해볼 수 있을까요?

2021-12-26 14:41 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Queue.swift
> +    @discardableResult
discardableResult 를 사용해보셨군요~ 💯

2021-12-26 14:41 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Namespace/Menu.swift
> +        """
하드코딩하지 않고 이렇게 상수로 선언한 부분 좋습니다~ 🔢

2021-12-26 14:41 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Workable.swift
> +}
Workable 이라는 프로토콜명은 어떤 일이 가능한 것인지 불명확하네요.
더 좋은 프로토콜명이 있을까요?

2021-12-27 05:39 UTC, yanghojoon commented on BankManager.swift
> +    var duration: CFAbsoluteTime = .zero
`totalWorkingTime`로 조금 더 명확하게 수정했습니다!

2021-12-27 06:06 UTC, yanghojoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Workable.swift
> +}
한 단어로는 표현하기가 어렵다고 판단되어 `bankingWorkable`이라는 네이밍으로 바꿔보았습니다. 
은행 업무라는 것을 조금 더 명확하게 표현해봤는데 괜찮은 네이밍일까요?

2021-12-27 06:12 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        let numberOfClients = Int.random(in: 10...30)
총 수를 의미하는 total number만 남겨두고 number 라는 네이밍은 모두 삭제해보았습니다!

2021-12-27 06:12 UTC, yanghojoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Clients.swift
> +    init(_ clientNumber: Int = 0) {
클라이언트를 식별하기 위한 값인 만큼 `identifier`로 수정해봤습니다!
매개변수도 생략하지 않고 `identifier`로 받을 수 있도록 구현했습니다.

2021-12-27 06:13 UTC, yanghojoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Clients.swift
> +    let clientNumber: Int
객체명과 겹치지 않도록 `identifier`로 변수명을 수정했습니다.

2021-12-27 06:18 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        let numberOfClients = Int.random(in: 10...30)
numberOfClients 는 totalClientCount 로 변경하고, number 은 identifier 로 수정해보았습니다!

2021-12-27 08:28 UTC, ye-ha commented on BankManager.swift
> +    let clerkNumber: Int
clerk 번호를 BankClerk 내부로 옮겨보았습니다!

2021-12-27 12:32 UTC, AppleCEO commented
1. 의존성 주입에 대해 알아보고 
var clients = Clients()
let clerk = BankClerk()
이 쪽 코드 부분을 개선해 볼 수 있을까요?

2021-12-27 13:47 UTC, ye-ha commented
더 짚어주셔서 감사합니다!
말씀해주신 내용 공부해보고, 적용해보았습니다.

2021-12-27 13:58 UTC, ye-ha commented
추가로 struct `BankManager`에서 많은 외부 요소들을 필요로 하고 있는데요. 
많은 일을 하고 있어서 그렇다고 느껴져서 기능을 분리해보고자 `Bank`라는 새로운 타입을 만들어서 `announceClose` 메서드를 분리해볼까? 생각했습니다. 하지만 `BankManager`와 마찬가지로 외부 요소가 필요했습니다. 
`BankManager`가 이렇게 많은 프로퍼티를 가지고 있어도 괜찮은지 궁금합니다.

2021-12-28 00:40 UTC, AppleCEO commented
여러가지 시도해보는 것 좋다고 생각합니다. 그리고 수정하신 부분처럼 생성자 안 에서 생성자를 사용하는 것은 조금 가독성이 떨어질 것 같아요.
그 부분 개선해보면 좋겠습니다.

2021-12-28 00:42 UTC, AppleCEO commented
현업에서는 훨씬 많은 프로퍼티들을 가지고 있는 경우도 있습니다. 그러나 말씀하신대로 프로퍼티가 많아지는 것을 경계하고 만약 관련된 프로퍼티들을 하나의 다른 객체에 모으는 식으로 프로퍼티를 줄여갈 수 있을 것 같습니다. 그런 부분도 참고해보면 좋겠습니다.

2021-12-28 00:57 UTC, merged