은행 창구 매니저 [STEP 3] yeha, 호댕
yagom-academy/ios-bank-manager pull request #132
Opened 2021-12-28 12:35 UTC by yanghojoon

안녕하세요. 도미닉! **[@AppleCEO](https://github.com/AppleCEO)**

은행 창구 매니저 Step 3 PR 요청을 드립니다!

이번 PR도 잘 부탁드립니다. 감사합니다 🙇🙏

## 🤔 고민했던 점

### 3명(예금 2명, 대출 1명)이 일하도록 구현하는 방법에 대해 고민했습니다.

- 3명이 일하는 것처럼 Thread를 사용하려면 어떻게 구현해야 하는지 고민했습니다.
- 처음에는 `Custom Serial Queue`로 `Dispatch Queue`를 직원마다 생성해서 구현을 해야하나 고민했습니다.
- 여러 가지로 실험을 해보다가 `global.async` 큐를 하나 만들어서 구현을 했습니다.
    - 또한 `async`로 쓰레드에 일을 준 후 바로 `announceClose` 메서드가 실행되지 않도록 `DispatchGroup()` 을 만들어 `DispatchQueue`  를 만들 때 `group` 인자를 주었습니다.
    - 그 후 `startBankTask` 메서드를 실행하고 바로 `announceClose` 메서드가 실행되지 않도록 `dispatchGroup.wait()` 를 해줬습니다.

### DispatchSemaphore의 사용

- 처음에는 Semaphore에 3을 주고 while 문 내부에서 다시 예금과 대출에 각각 Semaphore를 2와 1로 주는 방법으로 구현하려고 했습니다.
- 하지만 이렇게 구현을 하니 처음에 3번의 일처리가 동시에 시작되긴 했으나, 예금과 대출에 접근하는 쓰레드의 수를 제어할 수 없었습니다.
- 따라서 전체를 제어하는 Semaphore를 없에고, 예금과 대출에 해당하는 Semaphore를 각각 생성한 후 taskType에 따른 각각의 작업을 수행할 수 있도록 구현했습니다.

```swift
private func startBankTask() {
        let depositSemaphore = DispatchSemaphore(value: Bank.depositClerkCount)
        let loanSemaphore = DispatchSemaphore(value: Bank.loanClerkCount)
        
        while let taskType = clients.informTaskType(),
              let clientIdentifier = clients.dequeueWaitingLine() {
            DispatchQueue.global().async(group: dispatchGroup) {
                switch taskType {
                case .deposit:
                    depositSemaphore.wait()
                    self.clerk.work(for: clientIdentifier, task: taskType)
                    depositSemaphore.signal()
                case .loan:
                    loanSemaphore.wait()
                    self.clerk.work(for: clientIdentifier, task: taskType)
                    loanSemaphore.signal()
                }
            }
        }
    }
```

### BankManager에서 구조체를 사용했을 때의 문제점

- 모두 구조체 타입으로 만들어서 진행하다가 `Escaping closure captures mutating 'self' parameter`  에러를 만나 다른 타입을 참조할 수 있도록 `BankManager` 를 클래스로 바꾸어주었습니다.

### 사소한 고민과 궁금증

- 강제 언래핑 관련
```swift
let names = ["Zoey", "Chloe", "Amani", "Amaia"]
let randomName = names.randomElement()!
// randomName == "Amani"
```
    
고객 생성시 업무 타입 (예금, 대출 중 하나)을 지정해주는 부분에서 `randomElement()` 를 guard문으로 처리해서 사용했습니다. [문서](https://developer.apple.com/documentation/swift/string/2997145-randomelement)의 코드 예시에서 강제 언래핑(!)을 해준 부분을 보고 질문드립니다. 저희는 강제 언래핑을 사용하지 말라고 배우고, 규칙대로 구현하고 있지만.. 위처럼 실패할 수 없는 경우라면 강제 언래핑을 사용하는 경우도 있을지 궁금합니다.  
    

---

## 🙏 조언을 얻고 싶은 부분

### `startBankTask` 메서드 관련

`startBankTask` 메서드 내부의 `DispatchQueue`에 일감을 주는 부분을 분리하려는 시도도 했지만, 저희가 의도했던 대로 동작하지 않았습니다. 그래서 아래 코드처럼 작성하게 되었습니다. 저희가 생각하지 못했던 부분이나 로직이나 기능 분리 등 개선할 부분이 있을까요?

```swift
private func startBankTask() {
        let depositSemaphore = DispatchSemaphore(value: Bank.depositClerkCount)
        let loanSemaphore = DispatchSemaphore(value: Bank.loanClerkCount)
        
        while let taskType = clients.informTaskType(),
              let clientIdentifier = clients.dequeueWaitingLine() {
						// DispatchQueue에 일감을 주는 아래 부분
            DispatchQueue.global().async(group: dispatchGroup) {
                switch taskType {
                case .deposit:
                    depositSemaphore.wait()
                    self.clerk.work(for: clientIdentifier, task: taskType)
                    depositSemaphore.signal()
                case .loan:
                    loanSemaphore.wait()
                    self.clerk.work(for: clientIdentifier, task: taskType)
                    loanSemaphore.signal()
                }
            }
        }
    }
```

- 시도한 방법:
    - dispatchWorkItem 변수로 생성
        - `DispatchQueue.global().async(group: dispatchGroup, execute: workItem)` 처럼 사용하고 싶었습니다.
        - `while let` 으로 `taskType` 과 `clientIdentifier` 를 매번 고객 대기열에서 꺼내오는 로직이라 `workItem` 내부에서 필요한 요소가 많아서 안됐습니다.
    - 별도의 메서드로 분리
        - 아래 부분을 메서드로 분리해보았지만, 고객 대기열에서 `dequeue` 해온 대로 하나씩 메서드로 들어가서 → 쓰레드가 하나씩 생성되고 → 모든 고객의 업무 시작 문구가 먼저 찍히는 이슈가 있었습니다.
        
        ```swift
                let depositSemaphore = DispatchSemaphore(value: Bank.depositClerkCount)
                let loanSemaphore = DispatchSemaphore(value: Bank.loanClerkCount)
                
        
                DispatchQueue.global().async(group: dispatchGroup) {
                        switch taskType {
                        case .deposit:
                            depositSemaphore.wait()
                            self.clerk.work(for: clientIdentifier, task: taskType)
                            depositSemaphore.signal()
                        case .loan:
                            loanSemaphore.wait()
                            self.clerk.work(for: clientIdentifier, task: taskType)
                            loanSemaphore.signal()
                        }
                    }   
        ```
        

### 매개변수 VS Namespace

- 예금과 대출 각각을 담당하는 직원의 수를 어떤 식으로 처리할 지 고민했습니다.
- 처음에는 조금 더 유연한 코드를 위해선 예금과 대출을 담당하는 직원의 수를 `BankManager`의 인스턴스를 생성할 때 직접 받는 것은 어떨지 고민했습니다.
- 하지만 예금, 대출 업무를 수행할 때 걸리는 시간과 담당하는 직원의 수는 직접 받아줄 필요는 없다고 판단했고 하드코딩을 피하도록 `Namespace`로 구현해줬습니다.

도미닉이라면 어떤 식으로 구현하셨을지 궁금합니다! 

### operateBankSystem 메서드 관련

- `BankManager` 타입 내부에서 필요한 메서드를 호출하는 용도의 퍼블릭한 메서드를 만들자고 생각했습니다. 그래서 `operateBankSystem` 메서드를 만들었고, 이 메서드를 제외하고는 모두 `private` 으로 지정해주었습니다.
- 그런데 요구사항에 맞게 구현하다보니 총 운영시간 체크하는 프로퍼티와 `DispatchGroup.wait()` 코드가 들어가게 되었습니다.
- 상기의 목적이라면 분리하는 것이 맞을지, 아니면 이정도는 괜찮을지, 아니면 기능이 너무 많은지 등등 도미닉은 이 메서드에 대해 어떻게 생각하시는지 궁금합니다.

---

2021-12-28 14:35 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
@ye-ha & @yanghojoon 고생하셨습니다.
코드가 전체적으로 간결한 느낌이 들었습니다.
저번주보다 성장한 느낌이 드네요!
몇가지 코멘트 남겨봤습니다. 참고해서 조금 더 개선해보면 좋겠습니다.

질문에 대한 답변
저희는 강제 언래핑을 사용하지 말라고 배우고, 규칙대로 구현하고 있지만.. 위처럼 실패할 수 없는 경우라면 강제 언래핑을 사용하는 경우도 있을지 궁금합니다.
- 애플의 공식 문서이지만 결과 값을 바로 보여주려고 강제 언레핑을 사용하지 않았나 싶습니다. 실패할 수 없는 경우라고 하셨지만 만약 names 배열이 비어있는 상태에서 강제 언레핑을 했으면 어떻게 되었을까요?

startBankTask 메서드 관련
- 상세하게 시행착오와 어떤 부분을 느꼈는지 정리해주셨군요! 이렇게 정리해놓으면 나중에 비슷한 상황에 발생했을 때 다시 한번 살펴볼 수 있고 더 공부해볼 수 있어서 좋다고 생각합니다!
depositSemaphore.wait()
self.clerk.work(for: clientIdentifier, task: taskType)
depositSemaphore.signal()
이 3줄이 비슷한데 반복되고 있는 것 같아서 그 부분이 개선되면 좋겠는데 세마포어를 나누어야해서 어쩔 수 없었을까요?

개선할 부분은 저도 한번 내일 더 찾아보고 답변드리겠습니다. 같이 회의실에서 더 자세한 내용을 이야기해봐도 좋을 것 같네요!

매개변수 VS Namespace
- Namespace 는 열거형을 활용한 내용을 말씀하는거죠? 저는 현재 구조도 괜찮다고 생각합니다!

operateBankSystem 메서드 관련
- 이 정도면 괜찮다고 생각합니다. 보통 메소드의 길이는 20줄 정도를 멕시멈으로 생각하는데요. 길이도 짧고 시간을 측정하는 코드가 이 메소드에서 주요한 기능이기 때문에 현재도 괜찮은 것 같아요~

2021-12-29 13:56 UTC, yanghojoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Namespace/Bank.swift
> +        }
`timeNeeded`로 네이밍 수정했습니다!!

2021-12-29 13:56 UTC, yanghojoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Namespace/Bank.swift
> +        }
말씀해주신 `koreanName`이 괜찮은 것 같아 네이밍 수정했습니다!!

2021-12-30 05:45 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Clients.swift
> +    mutating func dequeueWaitingLine() -> Int? {
이 부분은 고심 끝에 `takeTurn` 으로 바꿔보았습니다. 고객 대기열에 대기하는 고객이 차례가 되어 dequeue된다는 의미를 담아보았는데요. 혹시 다른 아이디어도 있을까요? 🤔

2021-12-30 05:46 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Clients.swift
> +            guard let taskType = Bank.Task.allCases.randomElement() else {
말씀해주신대로 상수를 생성해서 guard문 조건에 넣어보았습니다!

2021-12-30 05:48 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Clients.swift
>          return client.identifier
옵셔널 체이닝을 사용하니 훨씬 깔끔해보입니다..! 
옵셔널 체이닝을 사용한 부분을 바로 반환하지 않고, 상수에 넣어서 반환해보았습니다.

2021-12-30 07:08 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
>  fileprivate func runMenu(with input: String) {
MenuOperation 이라는 struct를 만들어보았습니다!

2021-12-30 07:10 UTC, ye-ha commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
>      let clerk = BankClerk()
main.swift 내에서 인스턴스를 생성해서 메서드 통해 의존성 주입해보았습니다. 
함수나 객체 안에서 객체를 생성하게 되면 의존성이 높아져서 변화에 유연하게 대응하기 어렵다고 생각합니다.

2021-12-30 07:16 UTC, merged