Step2: 우선순위와 다중처리 구현 (Joons/GREEN)
yagom-academy/ios-bank-manager pull request #14
Opened 2021-01-08 13:25 UTC by GREENOVER

Step2 우선순위와 다중처리 구현하였습니다.
Step1에서의 로직을 Step2에 온전히 적용하려니 문제가 발생해 리팩토링하였습니다.
리뷰 부탁드립니다~ 👍 

[구현한 점]
1. 고객 우선순위, 업무 종류 열거형 타입 정의
 -. 우선순위에 따라 고객 큐 sort
 -. 업무 종류에 따라 다른 업무 시간 (taskTime) 적용

2. DispatchQueue를 이용한 비동기 업무 처리
 -. 은행원 3명에 대해 비동기로 업무를 처리 할 수 있도록 구현
 -. 각 은행원은 여러 고객의 업무를 동시에 하지않고 한 고객의 업무가 종료되면 다음 대기 고객을 받도록 구현

3. DispatchSemaphore를 이용한 스레드 점유 처리
 -. checkEnd() 메서드에서 모든 은행원의 일이 끝났을 때 세마포어 시그널을 이용하여 closeBank() 메서드를 호출하여
     업무 마감을 처리하도록 구현

4. 실제 업무 처리 시 해당 시간만큼 지연되도록 구현
 -. Thread.sleep을 이용하여 실제 대출/예금 업무에 따라 각 은행원들의 업무 처리 시간이 실제로 반영되도록 구현

5. 여러명의 은행원의 업무 동시성을 고려하여 총 업무시간에 대한 계산 및 구현
 -. 각 은행원의 총 걸린 업무 시간을 비교하여 은행원 배열을 sort 한 뒤 제일 소요시간이 긴 은행원이 마지막 업무를 본것으로 판단하여
    해당 은행원의 시간을 총 업무 시간으로 고려하여 구현

2021-01-10 09:46 UTC, yagom requested changes
리뷰가 늦어져서 미안해요.

세마포어의 활용이 눈에 띄네요. 여러 고민이 많았겠습니다.
몇 가지 고민포인트와 질문 남겨두었어요.

기획의 변경이나 추가사항이 발생하면 이렇게 구조적으로 리펙토링 할 일이 생길 수 있습니다. 최대한 리펙토링이 이뤄지지 않아도 변경할 수 있는 유연한 구조를 갖게 하려면 어떤 방법이 좋을지 프로젝트 회고때 돌아보면 좋을것 같아요 :)

꼭 수정했으면 하는 위험한 코드가 있어서 수정을 요청합니다.

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +class Banker {
은행원을 구조체에서 클래스로 변경한 이유가 있나요?

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +                workDone()
오잉? 일이 끝나야 notWorking이 되는게 아니고, notWorking으로 설정하면 일을 끝내는거예요?

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +            changeBankerCondition()
이름만으로 어떤 동작을 주는지 유추할 수 없었어요.
flipCondition 등의 이름은 어때요? 어디서 어디로 바뀌는지 도무지 알 수가 없었어요

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +        if let customer = customer {
customer가 꼭 필요한 메서드라면 guard를 사용하는 것이 의미전달이나 가독성 면에서 더 낫지 않을까요?

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +    var priority: CustomerPriority
`CustomerPriority`를 `Customer` 타입의 Nested Type으로 구현하면 의미도 더 명확하고, 타입 이름도 짧게 사용할 수 있을 것 같아요. 외부에선 `Customer.Priority`처럼, 고객의 우선순위라는 것을 더 명확히 볼 수도 있고요.

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +    private var dispatchQueue = DispatchQueue.global()
별도의 dispatch queue를 생성하지 않고, global queue를 사용한 이유가 있나요?

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +    private func checkBankerIsWorking(_ windowNumber: Int) {
메서드 이름은 일을 하는지 확인한다는 이름인데, 실제로는 내부에서 여러가지 일을 하는것 같네요.
메서드 내부에서 들여쓰기가 2단계 이상 가지 않도록 해보세요.

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +    private var semaphore = DispatchSemaphore(value: 0)
세마포어의 value가 0인 것은 어떤 것을 의미하나요?

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +    private func checkEnd() {
이 메서드에서도 들여쓰기가 두 칸 이상 가지 않도록 해보면 어떨까요?

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +        numberOfCustomers = 0
`numberOfCustomers`는 은행에 현재 머물고 있는 고객의 수인지, 다녀간 수인지, 총 수인지 중의적으로 해석할 여지가 있을 것 같은데요, 이름을 변경한 이유가 있을까요?

2021-01-10 09:46 UTC, yagom commented on BankManagerConsoleApp/BankManagerConsoleApp/BusinessType.swift
> +    case 대출 = 2
case 이름은 영어로 해주는게 어떨까요?
rawValue를 활용하기 위함인 것 같다고 생각하지만, 좀 더 세련된 방법이 있을지도 몰라요!

2021-01-10 09:46 UTC, yagom commented on BankManager.swift
> +            Thread.sleep(forTimeInterval: customer.taskTime)
sleep 말고 다른 방법은 없었나요? DispatchQueue의 다른 유용한 방법은 없었을까요?

2021-01-10 09:46 UTC, yagom commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
>      let numberOfCustomers:UInt = UInt.random(in: 10...30)
띄어쓰기

2021-01-10 09:46 UTC, yagom commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +        let businessType:Int = Int.random(in: 1...2)
띄어쓰기

2021-01-10 09:46 UTC, yagom commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +func timeSetting(_ type: Int) -> Double {
`duration(for type: Int)`는 어때요?
그리고 Int는 1이 무엇인지, 2가 무엇인지 전혀 모르겠습니다.
1년 뒤의 내가 이 코드만 보더라도 이해할 수 있게 수정해보면 좋을것 같습니다.

2021-01-10 09:46 UTC, yagom commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +        customers.append(Customer(waiting: number, taskTime: taskTime, priority: CustomerPriority(rawValue: Int.random(in: 1...3))!, businessType: BusinessType(rawValue: businessType)!))
좀 더 안전하고 좋은 코드가 분명히 있을거예요

2021-01-12 12:51 UTC, elddy0948 commented on BankManager.swift
> +class Banker {
DispatchQueue를 사용하는 과정에서 task 클로저가 @escaping () -> Void 형식이므로, mutating 메소드를 사용하면 @escaping 클로저를 사용할 수 없어서 class로 변경했습니다. 😄

2021-01-12 12:52 UTC, elddy0948 commented on BankManager.swift
> +                workDone()
은행원의 행동 과정이 고객을 받고(working) -> 업무를 처리 -> 업무 종료시 은행원이 처리한 업무에 대한 정보를 전달(workDone()) -> 자신의 상태를 notWorking으로 변경 라는 흐름으로 생각하여서 이 코드를 작성했습니다. 😄

2021-01-12 12:52 UTC, elddy0948 commented on BankManager.swift
> +    private var dispatchQueue = DispatchQueue.global()
global queue는 concurrent queue의 형식이므로 동시에 작업을 처리하기 위해서 global queue를 사용했습니다. 😄

2021-01-12 12:52 UTC, elddy0948 commented on BankManager.swift
> +    private var semaphore = DispatchSemaphore(value: 0)
value 의 값은 여러 용도로 사용할 수 있는데, 3개(은행원 3명)의 스레드를 동기 시키기 위해서는 0을 넣었습니다. 이렇게 하면 signal()과 wait() 쌍을 맞출 수 있게 되어 wait에서 깨어나는 시점을 동기화 할 수 있기 때문입니다.😀

2021-01-12 12:52 UTC, elddy0948 commented on BankManager.swift
> +        numberOfCustomers = 0
이 변수가 의미하는 것은 은행을 방문한 총 고객의 수를 뜻하는데, 기존의 visitedCustomers는 고객의 수를 뜻하기 보다는 방문한 고객들. 이라는 의미로 읽혀서 numberOfCustomers로 변경했습니다. 하지만, 고객의 수 인지, 다녀간 수인지, 중의적으로 해석할 여지가 있어서,  totalVisitedCustomers로 변경하였습니다. 😄

2021-01-12 12:56 UTC, elddy0948 commented
[수정한 부분]

- changeBankerCondition() -> flipCondition()로 좀 더 동작 방식에 알맞는 메서드 명으로 변경해 보았습니다.
- Func work() 에 if let customer = customer -> guard let customer = customer로 customer는 꼭 필요하기 때문에 없다면 오류를 표시해줄 수 있게 guard let 구문을 사용해 보았습니다.
- Nested Type을 활용한 Customer.Priority 구현
- Thread.sleep 대신 DispatchQueue의 asyncAfter를 활용하여 보았습니다. 
- 기능들을 좀 더 세분화 하여 메서드의 깊이를 줄이고자 노력했습니다. 😯

2021-01-12 13:26 UTC, yagom approved these changes
고민이 많았겠습니다!
들여쓰기가 많아질수록 재상용에 불리한 코드가 될 가능성이 높다고 생각해보면 좋습니다 :)

다음 스텝으로 갑시다!

2021-01-12 13:26 UTC, yagom commented on BankManager.swift
> +        guard let customer = customer else {
guard를 사용하면 조건의 중요함을 한껏더 알 수 있죠!

2021-01-12 13:26 UTC, yagom commented on BankManager.swift
> +    func workDone() {
소소한 코멘트지만 동사가 앞에 오는 형태가 낫지 않을까해요.
doneWorking 정도...? 영어가 짧아서 어렵네요 허허

2021-01-12 13:26 UTC, yagom commented on BankManager.swift
> +    enum Priority: Int, CaseIterable {
훨씬 좋네요!

2021-01-12 13:26 UTC, yagom commented on BankManager.swift
> +        var describing: String {
@zdodev 소대, 아마 제가 이것을 이야기했던것 같아요 :)

2021-01-12 13:26 UTC, yagom commented on BankManager.swift
> +    var priority: Customer.Priority
오... 프로퍼티의 순서가 바뀐 이유가 있나요?

2021-01-12 13:26 UTC, yagom commented on BankManager.swift
> +    private func countOfTotalTime() {
이름은 숫자를 반환할 것 같은데, 숫자를 반환하진 않네요 ㅎㅎ

2021-01-12 13:26 UTC, merged

2021-01-13 02:07 UTC, GREENOVER commented on BankManager.swift
> +    var priority: Customer.Priority
nested Type으로 Priority 열거형을 먼저 정의한다음 priority 변수가 해당 열거형 타입을 받아온다고 생각하여 흐름상 Priority 정의 다음 priority 변수 선언이 이뤄지는게 맞다고 생각했습니다. 그런데 현재 코드에서 제일 마지막 프로퍼티 부분에 위치하는것보다 Priority 정의한 후 바로 밑에 선언하는것이 더 가독이 좋을것 같다고 생각이 듭니다😯

2021-01-13 02:11 UTC, GREENOVER commented on BankManager.swift
> +    private func countOfTotalTime() {
해당 메서드는 은행원들의 공통된 시간을 제외한 은행원 3명의 일 시작과 끝의 총 소요시간을 구하기 위해 은행원들의 시간을 비교하여 총 소요시간을 businessTimes로 정해주는 기능을하여 총시간을센다 라는 의미에서 countOfTotalTime으로 네이밍을 해봤는데, 야곰 코멘트를 보니 총시간을 세는것보다 비교하거나 정한다는 의미의 네이밍이 더 적절할것 같습니다..! 다음 스텝에서 해당 네이밍을 더 가독성있게 변경해봐야겠습니다ㅎㅎ🐻