은행 창구 매니저 [Step1]  Eddy, dudu
yagom-academy/ios-bank-manager pull request #144
Opened 2022-04-25 09:29 UTC by kimkyunghun3

안녕하세요 @TTOzzi  은행 창고 매니저 STEP1 PR 보냅니다!
부족한 점이 너무 많으니, 많이많이 지적하고 개선해 주세요!!
첫 리뷰 잘 부탁드립니다. 열심히 하겠습니다!!

## 고민한점 및 궁금한점

### test 코드와 실제 코드의 커밋 단위

테스트 코드 와 실제 코드를 작성했는데 커밋 단위를 어떻게 나누어야할지 고민이 되었습니다.
예를 들어, TDD 형식으로 테스트코드 작성 후 실제 코드 작성하게 되면 두 가지 다른 코드(테스트 코드, 실제코드)가 생기게 되는데 커밋 단위를 따로 해야할지 아니면 한번에 묶어서 같이 기능구현으로 넣어야 할지 정확한 기준을 파악하기 어려웠습니다.
이런 부분에서 커밋단위를 정하는 것은 저희가 협의한 바로 해야할지 아니면 대부분 쓰는 단위가 있는지 궁금합니다!

### 이미 검증된 매서드를 다른 매서드의 테스트에서 사용하는것

테스트 코드에서 테스트 코드 메서드 하나당 하나의 테스트만 이루어 져야 한다고 생각합니다.
하지만 저희가 아래의 코드 같이 했을 경우 enqueue, clear, isEmpty 세가지의 메서드를 한 곳에서 사용한 것 같은데 

```swift
    func test_Queue에_enqueue_2번하고_clear하면_isEmpty가_true로_나온다() {
        // given
        sut.enqueue(10)
        sut.enqueue(20)

        // when
        sut.clear()

        // then
        XCTAssertTrue(sut.isEmpty)
    }
```

이러한 경우 여러개의 테스트를 한 것인지, 아니면 그 위 메서드에서 이미 검증되었다면 사용이 가능한지 궁금합니다.

2022-04-25 17:59 UTC, TTOzzi requested changes
고생하셨습니다 에디, 두두! 🙇 
작업 속도가 엄청 빠르시네요..! (첫날에 PR까지 올라와있어서 살짝 당황했습니다 ㅋㅋ)
테스트 케이스에 given, when, then 을 명확히 나눠주셔서 어떤 것을 테스트하고자 하는지 명확하게 알 수 있어서 좋았습니다.

### test 코드와 실제 코드의 커밋 단위

커밋 단위, 커밋 메세지 양식 같은 건 전부 팀(개인)이 정하기 나름인 것 같아요.
명확한 기준을 갖고 일관되게 맞춰지기만 한다면 어떻게 하시던 문제 없다고 생각합니다!
다만, 다른 사람과 협업하는 경우의 커밋은 커밋되는 코드가 정상적으로 빌드되는 코드여야한다는 것은 지켜져야 할 것 같아요 :thinking:

### 이미 검증된 매서드를 다른 매서드의 테스트에서 사용하는것

하나의 메서드만 독립적으로 테스트할 수 있다면 더 좋겠지만, 지금 로직에서는 어쩔 수 없이 다른 메서드를 호출해야 할 것 같네요.
특정 테스트 케이스가 실패했을 때, 어떤 이유로 실패했는지만 이해할 수 있도록 테스트 케이스들이 작성된다면 크게 문제 없을 것 같습니다.

코멘트 몇 개 남겨두었는데, 이해가 어려운 부분이 있다면 너무 오래 고민하지 마시고 언제든지 말씀해주세요 🙏

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
개인적인 생각으론 이렇게 메인이 되는 로직을 수행하기 위한 전제 조건을 만족하지 못했을 때, 빈 값을 반환하는(early-return) 등의 예외처리는 if 문보다 guard 문이 이해하기 더 쉬운 것 같아요 🤔

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            head = head?.next
여기서 반환할 `head`가 바라보고 있던 `next`는 비워줄 필요 없을까요? 👀

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    let list: LinkedList<Element>
`Queue`의 용도에 맞게, `Queue`가 제공해주는 인터페이스만으로 내부 데이터에 접근하도록 `private` 접근제어자를 설정해주면 더 좋을 것 같아요!

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
`LinkedList`가 있어야만 `Queue`를 생성할 수 있나요?  
이 `Queue`를 가져다가 사용할 때, 항상 `Element` 타입이 일치하는 `LinkedList`를 먼저 만들어줘야 한다면 불편하지 않을까요? 🤔

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +    }
`setUpWithError`와 `tearDownWithError`은 어느 시점에 실행되고 어떤 상황에 사용해야 할까요? 👀 

`XCTest` 프레임워크에서는 각 테스트 케이스를 실행할 때, 하나의 테스트 케이스당 하나의 테스트 클래스 인스턴스(`LinkedListTest`)를 각각 생성해서 실행하게 됩니다.

지금 구현에선 
```suggestion
    let sut: LinkedList<Int> = LinkedList<Int>()
```
요렇게 선언해도 의도하신대로 동작할 거예요.

앱 전역에서 상태를 공유하는 싱글톤 객체나 데이터베이스 등과 의존성을 가지는 테스트 케이스를 작성할 때, 각 테스트 케이스에서의 수정이 다른 테스트 케이스의 결과에 영향을 줄 수 있으니 `setUpWithError`와 `tearDownWithError` 내부에 테스트를 위한 설정, 초기화 코드를 작성해줘야 하고 지금은 굳이 사용할 필요 없어보이네요!

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertEqual(data, 10)
`peek`과 `removeFirst`와의 차이는 반환한 값을 리스트에서 제거하느냐, 제거하지 않느냐인 것 같은데요.
지금은 저기 `peek` 호출부에 `removeFirst`를 호출해도 테스트가 통과할 것 같네요 🤔 
`peek` 이 실행된 이후, 리스트에 값 변경이 없는지도 함께 체크해주면 더 좋을 것 같아요!

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertEqual(data, 10)
추가로 단위 테스트는 성공하는 케이스도 중요하지만, 실패하는 케이스도 테스트되어야 합니다.
언제든 예외 상황은 발생할 수 있으니까요. (여긴 실패..? 라 표현하긴 조금 애매하긴 하네요)
빈 리스트에서 `peek` 을 호출했을 때 의도한대로 `nil`을 반환하는지도 테스트해주면 좋을 것 같습니다 🙂

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        let data = sut.removeFirst()
여기도 위에 `peek` 테스트 케이스에서 남긴 코멘트와 동일해요!

2022-04-25 17:59 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/QueueTest.swift
> +        let data = sut.dequeue()
이곳의 `dequeue`와 `peek`도 `LinkedListTest`에 코멘트 드린것과 같이 성공하는 케이스에서의 조건과 실패하는 테스트 케이스가 추가되면 더 좋을 것 같아요!

2022-04-26 01:21 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
아래와 같이 바꿔주었습니다..!
이중부정인것 같아서, 쓰지 않았는데, 
이런 경우에는 guard를 쓰는게 훨씬 더 맞는거 같습니다 :)

```swift
guard head != nil else {
   return nil
}
```

2022-04-26 01:23 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            head = head?.next
![스크린샷 2022-04-26 오전 10 20 55](https://user-images.githubusercontent.com/52434820/165200142-3cbd2e27-9753-476a-941e-67ad383777c2.png)

저희가 실험해보았을 때 `removeFirst()` 메서드 호출마다 소멸자가 실행되기 때문에 자동으로 head에 nil이 들어간다고 생각했습니다. 따로 바라보고있는 `head`의 `next`를 비워줄 필요가 없다고 생각했는데, 혹시 저희가 실험한 것이 잘못된 것이거나 생각을 잘못한 것일까요?

2022-04-26 01:26 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    let list: LinkedList<Element>
접근제어자 추가해줬습니다..! 깜박했네요 ㅠㅠ
```swift
private let list: LinkedList<Element>
```

2022-04-26 01:28 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
아래와 같이 변경해 주었습니다!
```swift
private let list = LinkedList<Element>()
```

의도는 기본값을 가지는것보다 외부에서 주입해주는 형태로 사용하려고 했습니다..!

2022-04-26 01:41 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +    }
저희가 처음 생각했을 때 `setUpWithError`와 `tearDownWithError` 이 두 메서드는 테스트 코드 내에서 공유되어 sut이 사용되고 있기에 테스트 코드 작성시 마다 이 sut이 초기화가 스스로 되지 않아서 매번 테스트 메서드를 실행하기전에 위의 두 메서드를 통해 초기화 해줘야한다고 생각했습니다. 하지만 또치가 해주신 방법으로 해보니 테스트코드가 다 잘 돌아갔으며 매번 끝난 후 sut이 empty가 되는 것을 확인했습니다.
그러면 실제 `setUpWithError`와 `tearDownWithError` 이 메서드는 테스트 코드에서의 공유된 자원이 아닌, 실제 코드에서 공유된 자원이 있을때만 초기화를 해줘야하는 메서드인건가요? 

```swift
let sut: LinkedList<Int> = LinkedList<Int>()
```
이 코드는 매 테스트 메서드가 실행되기 전마다 초기화가 되는게 맞는건가요?

2022-04-26 01:48 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertEqual(data, 10)
```swift
    func test_LinkedList에_값들을_append했을때_peek를_두번호출해도_값변경없이_동일한값이_나온다() {
        // given
        sut.append(10)
        sut.append(20)

        // when
        let firstData = sut.peek
        let secondData = sut.peek

        // then
        XCTAssertEqual(firstData, secondData)
    }

    func test_LinkedList가_비어있을때_peek를_호출하면_nil를_반환해야한다() {
        XCTAssertNil(sut.peek)
    }
```
peek을 두번 호출해서 다른 상수에 대입 후에 같은지 비교해서 값이 변하는지 확인했습니다. 

또한 실패 케이스를 작성해서 빈 리스트일 때 peek를 호출하면 nil이 나오는지 확인했습니다!

2022-04-26 01:53 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        let data = sut.removeFirst()
```swift
    func test_LinkedList가_비어있을떄_removeFirst를_호출하면_nil를_반환해야한다() {
        XCTAssertNil(sut.removeFirst())
    }

    func test_LinkedList에_한번_append하고_removeFirst를_호출하면_isEmpty가_나온다() {
        // given
        sut.append(10)

        // when
        _ = sut.removeFirst()

        // then
        XCTAssertTrue(sut.isEmpty)
    }
```

두가지 테스트 케이스를 통해 실패 케이스와 empty여부도 파악했습니다!

2022-04-26 02:04 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerTest/QueueTest.swift
> +        let data = sut.dequeue()
```swift
    func test_Queue가_비어있을때_dequeue하면_nil이나온다() {
        XCTAssertNil(sut.dequeue())
    }

    func test_Queue에_값들을_enqueue하고_dequeue를_했을때_값이_두번쨰_enqueue한값과_달라야한다() {
        // given
        sut.enqueue(10)
        sut.enqueue(20)
        sut.enqueue(30)

        // when
        let data = sut.dequeue()

        // then
        XCTAssertNotEqual(data, 20)
    }
```

실패 케이스와 실제로 값이 바뀌는지를 확인하는 테스트 코드 두개를 작성했습니다!

2022-04-26 02:05 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertEqual(data, 10)
전체적으로 테스트 케이스가 조금 많이 부실했네요 .. ㅠㅠ
모든걸 다 커버할 수는 없겠지만, 최대한 촘촘하게 짜보려고 노력하겠습니다!!

2022-04-26 02:10 UTC, kimkyunghun3 commented
말씀해주신 리뷰를 보니 테스트 코드가 미흡한 부분이 있었던 것 같습니다! 다음 스텝부터는 더 꼼꼼하게 테스트 코드 작성 해보겠습니다!
좋은 피드백해주셔서 많이 생각해볼 수 있었습니다 감사합니다 👍

2022-04-26 06:03 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            head = head?.next
저희도 이부분이 헷갈려서 위와같은 실험을 해봤습니다

만약에 head.next가 남아있다면, 그 다음 노드의 deinit은 호출될 수 없었다고 생각합니다 
(누군가가 가리키고 있으므로 ARC가 0이 될 수가 없음..!)

근데 호출된걸로 보아하니, head = head.next를 하면서, 원래 head가 가리키고 있던 node가 메모리에서 해제되고, 해당 node가 가리키고 있던 node.next 연결도 끊어졌다고 생각했습니다

2022-04-26 11:17 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
외부로부터 주입받는 경우도 고려해야 한다면, 전달하는 인자의 기본값을 설정해주는 방법도 있을 것 같아요 🤔 
Swift에서 제공해주는 다른 Collection 타입들처럼 여러개의 생성자를 제공해줄 수도 있겠네요.

2022-04-26 11:45 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +    }
> 그러면 실제 setUpWithError와 tearDownWithError 이 메서드는 테스트 코드에서의 공유된 자원이 아닌, 실제 코드에서 공유된 자원이 있을때만 초기화를 해줘야하는 메서드인건가요?

실제 코드에서 공유된 자원일 수도 있긴 하지만, 테스트 케이스의 로직이 실제 코드에 영향을 주면 안되기에 다른 예시를 들어야 할 것 같아요 🤔 

예를 들어 `UserDefaults`와 의존성을 가지고 외부로부터 `UserDefaults.standard`를 주입받아 로컬에 값을 저장하는 로직을 가지고 있는 객체가 있어요.
이 객체를 테스트할 땐, 실제 앱의 로직에 영향을 주면 안되기에 `standard`에 접근하지 않고 `init(suiteName:)`으로 테스트에서만 사용할 `UserDefaults`를 만들어서 주입해줄거에요.
그러면 데이터가 저장되는 곳이 분리되어 실제 앱 로직엔 영향을 주지않지만, 어찌됐건 데이터를 저장은 하기 때문에 전역에서 공유하게되어 각 테스트 케이스의 로직이 서로 영향을 주는 형태가 됩니다.
이 때 각각의 테스트 케이스가 실행되기 전, 후 상태를 초기화해주기위해 `setUpWithError`와 `tearDownWithError`를 사용하게 될거에요.

> let sut: LinkedList<Int> = LinkedList<Int>()
이 코드는 매 테스트 메서드가 실행되기 전마다 초기화가 되는게 맞는건가요?

넵 요거 확인해보시려면 `LinkedList` 생성 시점에 로그를 찍어 테스트 케이스 개수만큼 찍히는지 확인할 수 있겠네요.
약간 깊게 들어가면 https://github.com/apple/swift-corelibs-xctest/blob/main/Sources/XCTest/Private/XCTestCaseSuite.swift#L25-L28 케이스마다 클래스의 인스턴스를 생성해주는 것을 코드로도 확인할 수 있습니다!

2022-04-26 11:48 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertEqual(data, 10)
헉 부실하다뇨..!
깔끔하게 잘 짜주셔서 더 자세히 리뷰할 수 있었어요 👍

2022-04-26 11:53 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertEqual(firstData, secondData)
음! 두 값이 동일한 것을 확인하는 건 첫 번째 값이 삭제되지 않았는지 확인하기 위함이죠?
지금은 뽑아온 데이터가 첫 번째 값이 맞는지는 확인할 수 없을 것 같아요 🤔 
꺼내온 값이 10 인지 확인하는 로직은 남겨두는 게 좋을 것 같습니다.

2022-04-26 11:53 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertTrue(sut.isEmpty)
여기도 꺼내온 값이 (다른 엉뚱한 값일리는 없지만..)10이 맞는지 확인해주면 더 좋을 것 같아요!

2022-04-26 11:54 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerTest/QueueTest.swift
> +        XCTAssertNotEqual(data, 20)
여기도 마찬가지로 `dequeue` 해온 값이 맞는지도 확인해주면 좋을 것 같네요!
(저~기 아래 peek 두요!)

2022-04-26 11:58 UTC, TTOzzi approved these changes
추가로 리뷰할만한 중요한 부분은 없는 것 같아 다음 스텝 진행을 위해 머지할게요~!
혹시나 제가 놓친 부분이 있다면 말씀해주세요!
고생하셨습니다 🙇

2022-04-26 11:58 UTC, merged

2022-04-27 13:17 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerTest/QueueTest.swift
> +        XCTAssertNotEqual(data, 20)
### dequeue

```swift
        // given
        sut.enqueue(10)
        sut.enqueue(20)
        sut.enqueue(30)

        // when
        let data = sut.dequeue()

        // then
        XCTAssertEqual(data, 10)
        XCTAssertNotEqual(data, 20)
```

### peek

```swift
        // given
        sut.enqueue(10)
        sut.enqueue(20)

        // when
        let firstData = sut.peek
        let secondData = sut.peek

        // then
        XCTAssertEqual(firstData, 10)
        XCTAssertEqual(firstData, secondData)
```

이렇게 바꿔보았습니다

2022-04-27 13:18 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertTrue(sut.isEmpty)
### removeFirst

```swift
        // given
        sut.append(10)

        // when
        let data = sut.removeFirst()

        // then
        XCTAssertEqual(data, 10)
        XCTAssertTrue(sut.isEmpty)
```

다음과 같이 변경하였습니다

2022-04-27 13:19 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerTest/LinkedListTest.swift
> +        XCTAssertEqual(firstData, secondData)
### Peek

```swift
        // given
        sut.append(10)
        sut.append(20)

        // when
        let firstData = sut.peek
        let secondData = sut.peek

        // then
        XCTAssertEqual(firstData, 10)
        XCTAssertEqual(firstData, secondData)
```

위와 같이 변경하였습니다