은행 창구 매니저 [Step1] OneTool, Red
yagom-academy/ios-bank-manager pull request #145
Opened 2022-04-25 18:04 UTC by cherrishRed

@jungseungyeo
안녕하세요 린생☺️
프로젝트 첫번째 PR보냅니다!
잘 부탁드립니다🙇🏻‍♂️🙇🏻‍♀️

## 고민했던 것들
* LinkedList 가 존재하는데 Queue 구조체를 따로 만들어주어야 하는지
* 구조체와 클래스

### LinkedList 가 존재하는데 Queue 구조체를 따로 만들어주어야 하는지
>지금 코드에서 `Queue` 가 하는 일은 `LinkedList` 의 메서드를 그대로 가져와서 호출해 주고 있습니다. 우선은 구현 요구사항에서 `Queue` 를 구현 할 `LinkedList` 를 만들라고 하셔서 두개를 모두 구현했습니다. 저희가 의견을 나누기로는 두개가 똑같은 역할을 하고 있는 클래스 이기 때문에 한개만 존재해도 괜찮다고 생각하는데 이 둘을 따로 구현하게 하신 이유가 궁금합니다. 

### 구조체와 클래스
>struct로 구현해줬을 때, mutating 선언을 하여 사용했었습니다. 하지만 mutating 선언이 많아지게 되면 struct를 값이 변하는 경우가 많아서 사용하는 의미가 적어진다고 생각하여 class로 바꿔주었는데, mutating 선언이 많아져도 구조체를 선택해주어야 하는 경우가 있을까요?

## 조언 받고 싶은 내용
* `Queue` `LinkedList` `Node` 를 묶는 폴더명
* mint와 brew install swiftLint와 cocoa pod의 차이를 정확히 모르겠습니다.

### `Queue` `LinkedList` `Node` 를 묶는 폴더명
>View의 경우에서는 이러한 역할을 해주는 것들을 모두 Model에 넣어주었기에, Group 이름에 대하여 고민할 일이 없었습니다. 하지만 command line tool을 사용할 때에는 이런 역할을 하는 것들을 묶어주는 폴더명이 필요하다고 생각했지만, 마땅한 Group 이름이 떠오르지 않아서 묶어주지 못했는데 린생은 보통 이런 경우 어떤 폴더명을 사용하시나요?

### mint와 brew install swiftLint와 cocoa pod의 차이
>저희가 swiftLint 를 설치하는 과정에서 많은 시행착오가 있었습니다. 
처음에는 SPM 을 사용해서 swiftLint 를 설치했으나, 오류가 났습니다.

<img title="SPM swiftLint 설치 화면" src="https://i.imgur.com/nZII5Hm.png/">

그래서 swiftLint 공식 홈페이지에 나온 SPM 을 commandLine Tool 로 이용하기 위한 Mint 를 설치하고 진행하였으나, 또 오류가 낫습니다.😭
저희는 SPM 오류라고 생각해서 cocoa Pod을 통해서 설치를 진행했지만 또 오류가 났습니다. 

아카펠라가 조언해 주신 바로는 레드가 M1 을 사용하고 있어서 폴더 경로가 달라서 나는 오류로 폴더 경로를 재설정 해주면 된다고 하셨습니다. 

레드는 cocoa Pod 을 이용해서 설치를 성공하였고 원툴은 계속 permission denied 오류가 계속 나서 결국엔 xcode 를 지우고 재설치 하였습니다.

이 과정에서 아카펠라가 homebrew 를 이용해서 swiftLint 를 설치할 수 있다고 이야기 해주셨는데, homebrew 통해서 설치 하는 것과 의존성 관리 도구를 통해 설치하는 것의 차이점이 궁금합니다. 
homebrew 통해서 설치하면 저희가 의존성을 수동으로 관리해 주어야 하는 걸까요?

2022-04-26 13:12 UTC, jungseungyeo requested changes
### LinkedList 가 존재하는데 Queue 구조체를 따로 만들어주어야 하는지

`구현하면서 이건 아닌거 같다는 느낌을 받았을거같아요. 그러다는 건 뭔가 놓친 부분이 있다는 의미에요. Queue의 기능을 LikedList로 모든 걸 만든거 같아요. pop의 기능은 queue의 기능보다는 stack의 기능이죠? 차라리 면접이나 자주나오는 stack두개로 queue를 구현해 보는 거는 어떤가요? queue로만 구현해도 좋습니다. ㅎㅎ`

### 구조체와 클래스

`변경이 자주 일어난다면 struct가 아닌 class를 사용하는게 좋죠, 단순히 struct와 class의 차이가 참조의 관점으로만 존재하는게 아니예요. 각각 메모리 위치와, 적재 시점이 다르기 때문에 꼭 변경부분만 생각하지말고 좋합적이 관점에서 무엇이 좋을지 고민하면 더욱 좋을거 같아요. 지금 같은 경우는 class를 사용하는게 너무 좋았습니다. ㅎㅎ`

### Queue LinkedList Node 를 묶는 폴더명

`그룸은 협업이나 개인이 잘 알 수 있는 것을 두는것이 좋아요. 그래서 정해진 규칙은 없지만 위 와 같이 알고리즘은 Utile이라는 공통화 된 부분을 만드는 폴더를 만들구 두는 편이예요 ㅎㅎ`

### mint와 brew install swiftLint와 cocoa pod의 차이

`에러 메시지를 같이 보여주면 알수있는데 현재로는 잘 알 수가 없네요 ㅠ m1이라고 하시면 인텔의 암축방식으로 모듈을 생성하는 것을 m1에서 가져올려고하니 에러를 발생하는 문제로 인식이 되네요 ㅎㅎ 이 부분은 m1 cocoapod install을 검색하면 나와있어요 ㅎㅎ`
https://ondemand.tistory.com/340

`두 SPM, cocoapod은 차이가 있어요. SPM 같은 처음 xcode가 실행하여 build를 하여 앱 개발을 하는 경우 build시간에 포함이 되지 않지만 처음 모듈을 빌드하는 시간을 기다려야 한다는 단점이 존재합니다. 그런데 cocoapod인 경운 build시점에 모듈을 빌드를 돌려 프로젝트 총 빌드 시간에 포함이 되게됩니다. ㅎㅎ`

`swiftLint의 경우 회사별로 custom을 하여 사용하는 편이라 Bomebrew로 사용하는 것을 많이 보았는데요. 수동으로 관리한다는 생각하면 좋을거같아요. 기본으로 제공하는 것 말고도 특정 폴더에서는 적용을 하지 않거나 하거나 이렇게 작성하는 편입니다.ㅎㅎ`

레드, 원툴 고생하셨어요. 제가 코멘트 했던 부분에서 코멘트 달아주시고, queue를 stack 두개로 구현하는 것도 고려해보면 좋을거 같아요 ㅎㅎ

2022-04-26 16:54 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func pop() -> T? {
그렇네요! `removeFirst` 로 네이밍 수정했습니다!

2022-04-26 16:55 UTC, cherrishRed commented on BankManagerConsoleApp/QueueTests/QueueTests.swift
> +    func test_deQueue() {
저희가 테스트명을 지어두고 수정한다고 한 것을 까먹었네요😅
`test_append_3번_후에_isEmpty호출_removeAll호출_결과가_true인지`
이와 같은 자세한 이름으로 수정 했습니다!

2022-04-26 17:25 UTC, kimt4580 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +final class LinkedList<T> {
LinkdList는 단 반향성이고, DoubleLinkdList는 양방향성으로 양쪽에서 접근이 가능한 차이가 있다고 생각합니다!

2022-04-26 17:25 UTC, kimt4580 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +        return linkedList.removeAll()
수정 완료 했습니다!

2022-04-26 17:29 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        tail = nil
이 부분에 대해서 `Node` 에 `deinit` 을 넣고 실험을 해보았는데 해지가 되지 않더라구요. 

저희가 구현한 `LinkedList` 가 `DoubleLinkedList` 라서 `previous` 와 `next` 가 모두 참조를 하고 있어 순환참조가 일어나 해지가 되지 않았습니다. 
`previous` 프로퍼티를 `weak` 참조로 바꿔주어 순환 참조가 일어나지 않도록 수정 했습니다.

2022-04-26 17:41 UTC, kimt4580 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    var peek: T? {
함수는 매개변수가 있고, 연산 프로퍼티는 매개변수를 사용할 필요가 없습니다. 매개변수를 사용하지 않는 상황에서 메서드와 연산 프로퍼티중 연산 프로퍼티가 컨벤션이나 성능이 더 좋다는 것을 알게되어서 사용하게 되었습니다.

2022-04-26 17:57 UTC, cherrishRed commented
@jungseungyeo
린생☺️ 리펙토링 완료했습니다!!

리펙토링 사항
- [x] Listable protocol 생성
- [x] Double Stack List 구현
- [x] Double Linked List 의 순환참조 오류 해제
- [x] 테스트 코드 테스트 네이밍 수정
- [x] Mock 객체를 이용해 테스트 코드 수정

린생 조언해 주신 부분 수정했습니다!

## 🤔 추가적인 질문

### 똑같은 테스트 코드 다른 자료구조
현재 `LinkedList` 와 `DoubleLinkedList` 가 같은 프로토콜을 채택하고 있기 때문에, 테스트 코드가 완전히 같습니다. 테스트 코드를 이런식으로 작성해도 되는 건가요?

### Mock 객체 작성법
`Queue` 를 테스트 해주기 위해서, `MockList` 객체를 간단히 작성하였는데, 이 객체가 더 단순해야 하는 건가요? 복잡해야 하는 건가요? 

```swift
fileprivate final class MockList<Element>: Listable {
    var isEmpty: Bool {
        return true
    }
}
```
처음에는 저희는 위의 처럼 간단하게 작성해 주는 것으로도 이야기를 했었는데요 어떤 방식이 좋을까요?

2022-04-27 00:42 UTC, jungseungyeo approved these changes
레드, 원둘 고생하셨어요. 

Stack을 이용해서 Queue를 만드는 코드를 보면서 잘 이해가 되었는지 모르겠네요? 또 Queue를 구현하기 위해서 protocol을 정의하고 그 protocol을 DoubleStack과 LinkedList에 채택하여 Queue에 들어갈 수 있게 추상화하는 코드를 작성하는 부분이 너무 좋았습니다 ㅎㅎ

## 질문 답변

### 똑같은 테스트 코드 다른 자료구조

`기능이 같은 것은 테스트 결과도 같을 수 있다고 생각하면 좋을거같아요. 그래서 내부 객체가 변경 되어도 테스트는 통과되면 성능상 문제가 없게구나 하고 유추할수가있는거죠. 무조건 똑같다고 생각하면 안되지만 일반적으로 결과가 같다면 성능도 같다고 생각하는 편이예요 ㅎㅎ 그만큼 잘 만들었다는 거죠 ㅎㅎ 고생하셨습니다 `

### Mock 객체 작성법

`복잡하고 복잡하지 않는다는 기준의 대해서 고민하고 계시네요 ㅎㅎ 그 부분은 너무 신경쓰지마세요 중요한것은 테스트가 가능한지 불가능한지의 대해서 고민하면 좋을거같아요. 현재 코드에서는 실패 case가 없지만 실패또한 테스트를 해야 한다면 내부를 실패하게 구현하는 것이 아닌 주입을 통해서 그냥 false을 return하던지 성공이면 그냥 true을 return하는 형식으로 단순해 하는 편입니다.`

// 성공
``` swift
class MockObject {
    private let resultValue: Bool
    init(resultValue: Bool) {
       self.resultValue = resultValue
    }
    
    func result() -> Bool {
      return resultValue
    }
}
```

`위와 같이 작성해 give 시점에 true를 넣어주면 성공, false을 넣어주면 실패의 대한 응답값이 오겠죠? 위와 같이 작성하여 사용해요. 실제 객체에서는 내부에서 성공을 시킬려고 많은 로직이 있었겠지만 그냥 테스트 할려는 객체에서는 실패 성공, 여부만 알면 되기 떄문에 응답 값을 단순화하여 보내주는거죠  위와 같이 단순화 한다고 생각하면 좋을거같아요.  결론은 테스트가 가능한 정도로만 단순화하면 문제는 없다라고 생각하면 좋을거같아요.`

레드, 원툴 고생하셨습니다. 코멘트 보시고 다음 스텝 진행하면 좋을거같아요 ㅎㅎ 수고하셨습니다.

2022-04-27 00:42 UTC, jungseungyeo commented on BankManagerConsoleApp/Tests/DoubleStackTests/DoubleStackTests.swift
> +    func test_append_3번_후에_isEmpty호출_removeAll호출_결과가_true인지() {
true인지보다는 true가 된다 와 같이 확실 한 결과를 말해주면 좋습니다 :)  전의 비해서 네이밍이 너무 좋네요 ㅎㅎ

2022-04-27 00:42 UTC, jungseungyeo commented on BankManagerConsoleApp/Utils/DoubleStack.swift
> +final class DoubleStack<T>: Listable {
구현해 보니 어떤가요? 느낌이 오시나요? Listable이라는 기능으로 구현해야 하는 부분을 정하고 내부는 다르게 구현하는 모습 너무 좋습니다 ㅎㅎ

2022-04-27 00:43 UTC, jungseungyeo commented
질문 중 답변을 못한 부분이 있었네요 연산프로퍼티는 장점 중 하나는 메모리 count를 올리지 않고 접근이 가능하다는 장점이 있어요. 그래서 메모리 관리 측면에서도 장점이 있습니다. ㅎㅎ

2022-04-27 00:43 UTC, merged