은행 창구 매니저 [STEP1] 쿼카, 두기
yagom-academy/ios-bank-manager pull request #152
Opened 2022-04-26 07:59 UTC by doogie97

@Monsteel 
안녕하세요!토니! STEP1 완료해서 PR보냅니다!
잘부탁드립니다!😁😄

## 조언 받고 싶은 내용

### 1. dequeue와 peek이 공존할때 굳이 dequeue메서드에 반환값이 있어야하는지 의문
똑같이 값을 가져오기위한 목적이라서 `peek`하나로 가져가되 `removeFirst`는 첫 요소에대한 삭제만 진행해준다면 되지않을까요?

### 2. list와 Node의 의존성 분리
큐는 단지 큐만을 위해서 존재한다고 생각하는데 의존성 분리가 필요할지
더 이상 확장될 상황이 없다고 생각해 진행하지 않았는데 토니의 생각은 어떤지 궁금합니다!

2022-04-26 14:32 UTC, Monsteel requested changes
안녕하세요 쿼카, 두기~
은행창구 매니저 프로젝트 리뷰어 토니입니다~

Step1 진행하시느라 수고 많으셨습니다.
리뷰는, 간단한 코멘트 위주로 몇가지만 남겨보았어요! 확인 부탁드립니다! 🙌 

추가로, 남겨주신 **조언 받고 싶은 내용**을 이해하는데에 어려움이 있네요..😓
조금 더 상세하게 남겨주시면 답변에 도움이 될 것 같아요! 🙏

쿼카 두기 모두 수고하셨어요 🙌

2022-04-27 05:24 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +final class Node<Element> {
https://github.com/yagom-academy/ios-bank-manager/pull/152/commits/07f5c110750c5589e90eb83c35378ee2cb8c9ee0
말씀하신대로 Node는 LinkedList내부에서만 사용되고 있어서  LinkedList로 이동시켜주었습니다.
저희가 class내부에 class가 있는 구조를 만들어본 적이 없어서 생각해보지 못한 것 같습니다

여기서 추가적으로 여쭤보고 싶은게 Node의경우는 참조를 통해 구현이되고 있는데 LinkedList는 참조도 상속도 되지 않는 타입이니까 struct로 생성해도 무관하다고 생각이 들었는데 mutating을 사용한다는 것이 마음에 걸리는데
토니는 어떻게 생각하시나요?

2022-04-27 05:26 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        guard !isEmpty else { return }
보통 얼리리턴을 할 때는 guard문을 사용한다고 알고있어서 guard문을 사용한다고 해서 guard문을 통해 작성하게 되었습니다
근데 사실 저희도 if문을 통해 리턴해주는 것이 가독성 측면에서는 더 좋다고 생각하는데 어떻게 생각하시나요?

2022-04-27 05:32 UTC, Quokkaaa commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        guard !isEmpty else { return }
https://github.com/yagom-academy/ios-bank-manager/pull/152/commits/533fbfb25988066736bd90530ab92d518a3c0101
if문으로 수정하였습니다.

2022-04-27 05:43 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +import Foundation
일단 말씀해주신 Node파일 같은경우는 삭제를 해주었기 때문에 반영은 안하게 되었습니다
다만 궁금한게 Node에서 뿐만 아니라 LinkedList나  Queue의 경우에도 Foundation을 임포트 하지 않아도 정상적으로 작동이 되는데 Foundation 을 import해야지만 사용할 수 있는 타입이나 메서드가 없다면  어떤 파일을 만들던지 import Foundation을 지워주는게 좋을 까요?

2022-04-27 06:04 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func append(data: Element) {
data는 노드에 들어가게될 아직 정해지지 않은 타입의 data이기 때문에 data라는 매개변수를 통해 받게 되었고 Element는 그 data의 타입이기 때문에 두 키워든 아예 다른 부류라고 생각이 들었습니다
즉, Element는 큐에서 다룰 노드들의 타입, data는 그 노드의 타입에 맞는 값(데이터) 으로 혼용될 이유가 없다고 생각을 했는데 토니가 어떤 부분에서 헷갈릴 수 있을 것 같다고 하신건지 궁금합니다!

2022-04-27 08:18 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +import Foundation
`import Foundation`을 함으로써 얻을 수 있는 효용이 있을까요? 🙋🏻‍♂️ 
`불필요한 import를 하는것 vs 불필요한 import를 모두 제거하는 것` 이 두가지 경우를 두고, 효용의 가치를 비교해서 판단하시면 좋을것 같아요. 🙌

2022-04-27 08:26 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        guard !isEmpty else { return }
`early return` 할 때 `guard`문을 사용하는 본질적인 이유가 무엇인가요?
`보통 ~해서, 일반적으로 ~ 하기에`와 같은 이유는 본질을 이해하고 사용하는데에 방해가 됩니다.

`guard`문보다 `If`문을 사용했을 때 가독성 측면에서 더 높은 효용이 느껴집니다.
가독성을 포기하면서 `guard`문을 사용했을 때 얻을 수 있는 이점이 있을까요?

2022-04-27 08:35 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        guard !isEmpty else { return }
저희도 해당 부분에 있어서는 토니의 생각에 전적으로 동의합니다
앞으로는 코드 작성함에 있어서 "보통 이렇게 하던데" 라는 생각은 버리고 현재 상황에 가장 알맞는 코드를 작성할 수 있도록 하겠습니다!

2022-04-27 08:48 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +final class Node<Element> {
Node를 `struct로 생성해도 무관하다고 생각` 하신 이유와, `struct에 mutating을 사용한다는 것이 마음에 걸리`신 이유를 함께 적어주시면 좋을것 같아요 🙌

2022-04-27 09:15 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +final class Node<Element> {
설명이 많이 부족해서 죄송합니다...ㅠㅠ

일단, Node는 참조를 통해 메모리에 남아있기 때문에 class를 써야 한다고 생각했고 
struct를 써도 무관하다고 생각한 부분은 Linked List입니다

LinkedList는 상속도 참조도 하지 않으니  heap영역을 사용하지 않는 값타입으로 성능 적인 측면에서 struct를 사용하는 것이 좋을 것이라고 생각을 했습니다
그런데 LinkedList를 struct로 만들게 된다면 mutating키워드를 사용하게 되다보니 결국 값의 변경을 위해 복사를 해놓는 비용이 생기게 되는데 이걸 상쇄시킬 만큼의 성능적 이득이 있을지 아니면 크게 차이가 없으니 사용하고 싶은 걸 사용하면 되는 것인지를 여쭤봤습니다!

2022-04-28 01:10 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    func append(data: Element) {
https://github.com/yagom-academy/ios-bank-manager/pull/152/commits/2fd9b768716c4203bfe5e3b9fa02d9c930a54e53
예시를 들어서 자세하게 설명해 주셔서 감사합니다!
말씀하신대로 Element라고 제네릭을 적어줬고 그 시점에서 혼용될 가능성이 있을 것 같습니다
다만 구분을 해주고싶은 마음은 동일해서 마지막에 제안해 주신 대로 newElement로 이름을 변경하기로 했습니다!

2022-04-28 05:41 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Node.swift
> +final class Node<Element> {
우선 `상쇄시킬 만큼의 성능적 이득이 있을지`를 먼저 파악해 보시면 좋을 것 같아요.

"~를 사용하는게 ~보다 더 성능이 잘나온다더라"는 이야기만 듣고 움직이는 개발자는 많습니다.
다만, 실제로 얼마나 성능이 차이나는지 확인해보고 직접 판단하는 개발자는 드물지요.
못해도 둘의 성능 비교를 정량적으로 한 아티클을 보고 판단하는 노력은 필요합니다.

이건 제가 답변을 드리기보단, `상쇄시킬 만큼의 성능적 이득이 있을지`를 파악해보시면 두기와 쿼카가 스스로 결론을 내릴 수 있을것 같습니다. 🙌

2022-04-29 00:30 UTC, Monsteel approved these changes
두기 쿼카 모두 Step1 진행하시느라 수고하셨습니다~! 🙌

좋은하루 보내세요 ☀️

2022-04-29 00:30 UTC, merged