은행 창구 매니저 [STEP1] Lingo, Cathy
yagom-academy/ios-bank-manager pull request #153
Opened 2022-04-26 08:08 UTC by cathy171

@stevenkim18 
안녕하세요 스티븐! 
은행 창구 매니저 STEP1 PR 보냅니다. 잘 부탁드립니다!

## UML
![](https://i.imgur.com/jJIMmpe.png)

---

## [STEP 1]
### 고민 및 해결한 점

**💡 Xcode의 Command Line Tools로 만들어진 App에 XCTest를 추가하는 과정에서 `target x86_64...; found: arm64` 에러가 발생했습니다.**

![](https://i.imgur.com/B5gK6Jy.png) 

<img width="400px" src="https://i.imgur.com/vCrXVEh.png"/> <br/>

저희는 인텔 맥과 M1 맥 사이에서 발생한 문제라고 생각했고 다음과 같은 시도를 해보았습니다.

1. Build Setting의 `Always Embed Swift Standard Library`설정 값 변경
2. x86_64 와 arm64 관련 설정 값 변경을 시도
3. Build Phase의 Compile Source 항목에 테스트할 코드를 추가

1, 2번의 방법으로는 문제를 해결할 수 없었으며 3번의 방법으로 해결할 수 있었습니다. 3번의 방법은 BankManagerConsoleAppTest 타겟에서 사용하는 BankManagerConsoleApp 파일들의 Target Membership를 추가하는 것과 같다는 것을 알 수 있었고 추가한 후 testable를 제거했더니 문제가 해결할 수 있었습니다.

<img width="400px" src="https://i.imgur.com/9qaVHjm.png"/> <br/>
<img width="400px" src="https://i.imgur.com/AeiwbrX.png"/>

### 조언 받고 싶은 점
**💡 `Swift Lint`에서 `line_length`가 적용되지 않는 현상**
```
disabled_rules:
  - multiple_closures_with_trailing_closure

excluded:
  - Pods
  
opt_in_rules:
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_multiple
  - operator_usage_whitespace

line_length: 99
indentation: 2
```
위와 같이 `swiftLint` 파일에 `line_length`를 99줄로 설정해주었는데 적용이 되지 않았습니다. 기본적인 설정이 120줄로 되어있는데 저희가 임의적으로 설정을 해주고 싶을 때는 어떻게 설정해야하는지 궁금합니다.

**💡 프로젝트 요구조건에는 Queue를 구현하기 위해 LinkedList를 구현하도록 되어있는 것에 대하여**
Queue를 구현하기 위해 LinkedList를 구현하도록 되어있고 요구사항에 맞게 LinkedList를 구현했습니다. 
저희가 구현하면서 `Node -> LinkedList -> Queue`가 아닌 `Node -> Queue`로 바로 구현해도 될 것 같다는 얘기가 나왔었는데 LinkedList를 생략하고 구현해도 되는지 궁금합니다.

2022-04-27 17:00 UTC, stevenkim18 commented
안녕하세요! 링고 캐시 반갑습니다!! 

제가 더 잘 부탁드려요!!

리뷰는 제가 일방적으로 알려드리는 자리가 아닌 서로 의견을 주고 받는 자리입니다!! 절대 정답은 없어요!! 제가 틀릴 수도 있어요!! 그러면 근거를 가지고 꼭 반박해주세요!

저도 많이 두분께 배워가겠습니다!!

한가지 당부 그리고 싶은 것은 어떻게 하면 더 잘 커뮤니케이션을 할 수 있을지 고민해주세요!! PR을 보내는 것도 2주 동안 저와 소통하는 부분들등 다양하게 고민해주시고 질문해주세요!!

## 고민 및 해결한 점

> **Xcode의 Command Line Tools로 만들어진 App에 XCTest를 추가하는 과정에서 `target x86_64...; found: arm64` 에러가 발생했습니다.**
> 
- 저도 최근에 인텔 맥을 사용하시는 분과 협업을 한적이 없는데.. 이런 이슈는 처음 보내요.
- 이번 프로젝트 부터 swiftLint때문에 Pods을 사용하시면서 생길 수 있는 문제가 아닐까 의심됩니다. 한번 이전 프로젝트에서도 에러가 나는지 확인해주세요.
- 3번과 같은 방법으로 해결할 수 있지만 썩 좋은 방법은 아닙니다. 타켓을 잘 분리해주어야 나중에 앱과 테스트를 나눠서 관리하기 용이합니다.
- 그래도 일단 이방법으로 진행해봅시다!!

> **`Swift Lint`에서 `line_length`가 적용되지 않는 현상**
> 
- `line_length` 가 테스트 코드에 적용이 안된건가요? 코드를 받아서 테스트를 해봤는데 lint 애러가 안나네요! 같이 확인해봐야 할 것 같아요!

> **프로젝트 요구조건에는 Queue를 구현하기 위해 LinkedList를 구현하도록 되어있는 것에 대하여**
> 
- 왜 링크드 리스트를 생략하고 구현하겠다고 생각하셨나요? 그냥 배열로만 큐를 구현하는 것이면 Node가 필요가 있나요?

2022-04-27 17:35 UTC, stevenkim18 requested changes

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankList.swift
> +struct BankList<T> {
링크드 리스트는 클래스가 아니고 구조체로 선언하신 이유가 있나요?

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankList.swift
> +struct BankList<T> {
이 연결 리스트는 그냥 연결 리스트인데 앞에 Bank를 붙인 이유가 있나요?

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankList.swift
> +  private var tail: BankNode<T>?
head만 있어서 구현이 될탠데 tail을 넣으신 이유가 있나요?

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +final class BankNode<T> {
여기도 앞에 Bank를 붙이신 이유가 있을까요?

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +final class BankNode<T> {
Node에는 class로 선언하신 이유가 있나요?

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +  var next: BankNode<T>?
외부에서 프로터피를 접근해야하나요?

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +  }
init으로 `next`도 같이 초기화 해줄 수는 없을까요?

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +    XCTAssertEqual(output, nil)
`XCTAssertEqual` 말고 nil을 검사할 수 있는 다른 함수가 있습니다!! 한번 찾아보세요!

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +  }
상수로 테스트 하는 것보다 변수로 담아서 테스트를 하는 것이 더 의미 있지 않을까요?
```swift
let value = 1
// given
self.sut?.enqueue(value)
// when
let output = self.sut?.peek
// then
XCTAssertEqual(output, value)
```

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +  }
이 테스트 위의 예시와 같이 고민해주세요!!

2022-04-27 17:35 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +    XCTAssertEqual(output, false)
true, false 도 다른 함수로도 테스트 할 수 있습니다!!

2022-04-27 17:37 UTC, stevenkim18 commented
### 테스트에 대해서
- 테스트 케이스가 너무 적고 예상 가능한 범위내입니다. 
- 만약 큐에 1억개가 들어가면 어떻게 될까요? 
- 조금 더 다양한 케이스를 고민해주세요!!
- queue는 테스트 하셨는데 list는 테스트 안하신 이유가 있으신가요?

2022-04-28 01:22 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankList.swift
> +struct BankList<T> {
List는 상속과 identity가 필요하지 않다고 생각하였고 참조타입인 클래스가 아닌 값 타입인 구조체로 구현했습니다.

2022-04-28 01:34 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +final class BankNode<T> {
동적 메모리 영역인 힙을 사용하는 참조타입과 달리 구조체는 정적 메모리 영역인 스택만 사용하기 때문에 구조체는 컴파일 단계 에서 고정된 메모리 크기를 가지고 있어야하는데 Node 내부의 Node 내부를 프로퍼티로 가지게 되면 Node[Node[Node[Node... 로 무한한 크기를 가지게 되기 때문에 에러가 발생하게 됩니다. 

따라서, LinkedList는 구조체로 Node는 클래스로 next 프로퍼티를 통해 다음 Node를 참조하도록 구현했습니다.

2022-04-28 01:59 UTC, cathy171 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankList.swift
> +struct BankList<T> {
프로젝트에 맞게 BankQueue에 사용되는 연결리스트라고 생각해서 BankList로 네이밍을 했었는데, 다시 생각해보니 큐에 사용되는 연결리스트일 뿐인 것 같아서 linkedList로 수정하였습니다.

2022-04-28 02:00 UTC, cathy171 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +final class BankNode<T> {
위 BankList과 같은 이유로 네이밍 수정하였습니다!

2022-04-28 02:13 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankList.swift
> +  private var tail: BankNode<T>?
Stack이라면 데이터의 삽입과 삭제되는 곳이 일치하기 때문에 head만으로 구현이 가능할 것 같은데 Queue는 데이터를 삽입할 곳과 삭제 될 곳의 위치가 다르기 때문에 tail이 필요하여 구현하게되었습니다.

2022-04-28 02:31 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +  var next: BankNode<T>?
외부에서 프로퍼티를 읽기만 하기 때문에 `private(set)`을 사용하여 읽기전용 프로퍼티로 변경했습니다.
대신 next의 경우 이후에 추가되는 노드를 연결해야하므로 `setNext()`라는 메서드를 구현하여 next의 값을 변경할 수 있도록 했습니다!

2022-04-28 02:34 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +  }
노드가 최초로 생성될 때는 next가 nil이기 때문에 nil를 기본값으로 설정하여 변경했습니다!
노드가 생성될 때 이후에 생성될 노드를 알 수가 없는데 생성자에 next를 구현할 필요가 있을 지 고민이 되었습니다.
```swift
init(_ data: T?, _ next: Node<T>? = nil) {
  self.data = data
  self.next = next
}
```

2022-04-28 02:51 UTC, cathy171 commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +    XCTAssertEqual(output, nil)
넵! `XCTAssertNil` 함수를 사용해서 테스트하도록 수정하였습니다!

2022-04-28 02:51 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +    XCTAssertEqual(output, false)
위의 `XCTAssertNil` 처럼 `XCTAssertTrue`, `XCTAssertFalse` 를 사용하여 변경했습니다

2022-04-28 02:59 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +  }
기존에는 상수로 되어있기 때문에 변경하려고 할때 하나하나 변경해야하는 문제가 있었던 것 같습니다. 
스티븐이 말씀해주신 것처럼 분리하여 수정했습니다.

2022-04-28 03:00 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleAppTest/BankQueueTests.swift
> +  }
위와 동일하게 변경했습니다!

2022-04-28 08:17 UTC, llingo commented
**왜 링크드 리스트를 생략하고 구현하겠다고 생각하셨나요? 그냥 배열로만 큐를 구현하는 것이면 Node가 필요가 있나요?**
> 저희는 배열을 쓰려고 한 것이 아니라.. 기존 LinkedList에서 Node에 대한 로직을 구현해주었던 것을 Queue에서 바로 구현하는 것이 어떨까? 라고 생각했습니다. 

> 예를 들어, 기존에는 LinkedList에서 Node를 처리하고 Queue는 가져다 쓰는 것만 했었는데
```swift
// 링크드리스트
mutating func append(_ data: T?) {
  let newNode = Node(data)
  if head == nil {
    head = newNode
  } else {
    tail?.setNext(newNode)
  }
  tail = newNode
}

// 큐
mutating func enqueue(_ data: T?) {
  list.append(data)
}
```

> 큐 자체에서 로직을 처리하는 것은 어떨까? 라는 의문에서 나온 질문이었습니다!
```swift
// 큐
mutating func enqueue(_ data: T?) {
  let newNode = Node(data)
  if head == nil {
    head = newNode
  } else {
    tail?.setNext(newNode)
  }
  tail = newNode
}
```

> 🤔  만약, 내부에서 사용하는 리스트를 프로토콜로 지정하여 교체하여 쓰도록 설계한다면 LinkedList의 구현이 필요할 수 있다는 생각도 들었습니다.

---

**queue는 테스트 하셨는데 list는 테스트 안하신 이유가 있으신가요?**
> 구현된 큐에서는 리스트의 메서드를 호출하기만 하기 때문에 큐를 테스트 한다는 것은 리스트도 테스트를 한다는 것이라고 생각하여 테스트를 따로 진행하지 않았습니다.

2022-04-29 10:44 UTC, stevenkim18 commented
수정 된 것 확인했습니다!! 몇가지 질문이 있는 그것은 디코로 물어볼게요 ㅎㅎ
머지하겠습니다!

2022-04-29 10:44 UTC, merged