은행 창구 매니저 [STEP2] Eddy, dudu
yagom-academy/ios-bank-manager pull request #154
Opened 2022-04-27 14:12 UTC by FirstDo

안녕하세요 @TTOzzi 은행 창고 매니저 STEP2 PR 보냅니다!
지난 리뷰를 통해 많은 부분을 배웠고 반영하려고 노력했습니다!
요번 STEP 2도 잘부탁드립니다 :) 

![](https://i.imgur.com/f2zdiWu.png)

### 고민한점 및 궁금한점

### Struct vs Class

#### 구조체가 참조타입을 프로퍼티로 가지고 있는 경우

STEP1에서 LinkedList를 class로, Queue를 struct로 구현했는데, 어차피 Queue는 내부에 LinkedList라는 참조타입을 가지고 있는데 struct로 구현하는것이 큰 의미가 있는지 궁금합니다.

내부에 참조타입이 있으면 구조체도 heap에 할당되는걸로 알고있는데(정확하지 않습니다 ㅠㅠ 더 찾아보겠습니다), struct타입에게 기대하는 성능이나, 값이 불편하므로 얻을수 있는 안정성에 있어서 의미가 있는지궁금합니다..!

#### 구조체의 mutating 키워드

또 이번에 BankManger, Bank, BankClerk, Customer를 모두 구조체로 구현하였는데, mutating이 붙은 매서드가 꽤 많았습니다. 구조체의 경우, 값의 변경자체가 불가능하기에, mutating 매서드에서 프로퍼티 값을 바꿀경우, 통째로 복사해서 새 구조체를 만드는것으로 알고있는데요, mutating이 무조건 나쁜건 아니지만, 그냥 final class로 구현하는게 더 효율적이지 않을까?(물론 구조체가 복사되는 빈도에 따라서 다르겠지만요!) 하는 생각이 있는데, 또치는 이부분에 대해서 어떻게 생각하시나요?

### Thread.sleep()

명세서에 은행원이 일을 처리하는 시간이 0.7초라고 되어 있어서, 이 부분을 어떻게 구현할지 고민했습니다
최종적으로는 Thread.sleep() 를 사용해서 실제로 0.7초간 멈추게 했습니다. 이 방법말고 asyncafter 같은 방식으로 실행을 지연시키는 방식도 생각해봤는데, 저희 생각에 이 방법은 점원이 0.7초간 일을 하는게 아니라 작업시작을 지연시키는 것이라고 생각해서 해당방법을 채택하지 않았습니다.

sleep를 활용했는데 괜찮은 선택이였을까요?

### testcode 작성 가능여부

#### private 매서드 테스트 여부

저희가 STEP2 에서 작성한 코드는 private 접근제어자가 설정되어 있어서 테스트 코드에서 테스트 하기 어려웠습니다.

- 테스트를 안하고 넘어가는 게 맞는지
- 존재하지 않는 역할을 구조체로 만들어서 그 내부에 메서드를 넣고 테스트 하는 방식을 생각도했습니다. 예를 들어 묵찌빠게임에 비교하는 메서드인 compare() 가 있는데 이를 private으로 내부접근을 불가능하게 한다면 이를 테스트할 수 없습니다. 그래서 이를 심판이라는 구조체를 만들어서 이 메서드를 구조체 내부로 하게 된다면 테스트가 가능하지 않을까 생각했습니다. 그래서 이렇게 하는 방식이 괜찮은 방식일지, 테스트 코드를 위한 분리가 아닐지 아니면 OOP적인 접근이 되면서 테스트 코드 작성이 되는 것인지 궁금합니다!
- private 매서드는 그 매서드를 호출하는 internal 매서드들에 의해서 암시적으로 테스트가 된다고 생각해서, internal 매서드들만 테스트 해주면 될지

이러한 방식으로 테스트 코드를 작성하도록 하는게 옳은 방향일지 궁금합니다.

#### STEP2의 비지니스 로직 테스트 방법

그리고 사실 Queue나, LinkedList 같은 자료구조는 테스트함수를 짜기가 쉬웠는데, 이번에 구현한 로직은 테스트 코드를 짜기가 쉽지가 않더라구요 ㅠㅠ
Bank의 open()같은 매서드나, BankClerk의 work() 같은 매서드를 테스트해보고 싶었는데.. 뭘 어떻게 해야할지 감이 안잡혀서요. 이런부분은 어떤식으로 해야할까요?

### testcode 메서드 테스트 하는 단위

테스트 코드 내에서 또치가 말해주신 리뷰를 보니 하나의 메서드에 XCTAssert() 매서드 여러개를 호출하라고 하신것으로 이해했습니다!
하나의 테스트함수는 하나의 기능만 테스트 하라고 배운것 같은데, 그 기능이라는 말이 어디까진지 궁금했습니다.
예를들면, 아래와 같은 테스트 함수에서

```swift
  func test_LinkedList에_값들을_append했을때_peek을_호출하면_처음append한값이나오고_LinkedList의_데이터가_변하지않는다() {
        // given
        sut.append(10)
        sut.append(20)

        // when
        let firstData = sut.peek
        let secondData = sut.peek

        // then
        XCTAssertEqual(firstData, 10)
        XCTAssertEqual(firstData, secondData)
    }

```

`첫번째 값을 꺼내오는지 + LinkedList의 상태를 변화시키지 않는지` 두개를 테스트 한것이니 분리해야 한다는 의견이 있었고
`peek이라는 기능` 하나를 테스트 했으니 괜찮다는 의견도 있었습니다

전자로 생각하면 함수를 분리해야할것 같고, 후자로 생각하면
테스트 함수 작성에 익숙치가 않아서 아직 너무 미흡합니다..!
또치의 도움이 절실합니다

2022-04-29 12:06 UTC, TTOzzi requested changes
안녕하세요 에디, 두두!

어쩌다보니 데드라인을 꽉꽉 채워서 리뷰를 남겨드리게 됐네요 :sweat:
빨리 해드리려고 했는데 늦어져서 죄송합니다.

### Struct vs Class

엇 스텝1 에서 `LinkedList`, `Queue` 모두 클래스로 구현하지 않으셨나요?!
`Queue` 만 구조체로 구현하셨었다면 아마 코멘트를 남겼을 것 같아요 :thinking:
말씀하신대로 `Queue` 자체는 복사해서 옮겨지더라도 내부  `LinkedList`가 참조 타입이라 사실상 구조체로 구현하는 게 의미가 없을 것 같네요.

성능도 고려하면 좋겠지만, 클래스/구조체가 가진 특성으로 유추할 수 있는 의미에 맞게 사용해서 코드로 의도를 명확하게 표현하는 것이 중요하다고 생각해요. 이런 면에서 값의 불변으로 얻는 안정성은 충분히 의미 있다고 생각합니다.

지금 구현에서는 구조체로 구현되어 mutating 메서드를 호출하기 위해 사실상 할당 후 변경이 일어나지 않는 프로퍼티임에도 변수로 선언된 부분이 있어 오히려 코드를 이해하기 더 어렵게 만드는 것 같아요. 
값이 변경됐을 때 새로운 구조체를 만들어서 할당하는 등의 동작이 필요해서 구조체로 구현한 것이 아니라면 클래스로 구현하는 게 더 좋을 것 같습니다 :thinking:

### Thread.sleep()

요건 코멘트로 남겼어요!

### testcode 작성 가능여부

요것도 테스트가 가능한 구조를 작성하기 위한 코멘트를 남겨두긴 했는데요.

> - 존재하지 않는 역할을 구조체로 만들어서 그 내부에 메서드를 넣고 테스트 하는 방식을 생각도했습니다. 예를 들어 묵찌빠게임에 비교하는 메서드인 compare() 가 있는데 이를 private으로 내부접근을 불가능하게 한다면 이를 테스트할 수 없습니다. 그래서 이를 심판이라는 구조체를 만들어서 이 메서드를 구조체 내부로 하게 된다면 테스트가 가능하지 않을까 생각했습니다. 그래서 이렇게 하는 방식이 괜찮은 방식일지, 테스트 코드를 위한 분리가 아닐지 아니면 OOP적인 접근이 되면서 테스트 코드 작성이 되는 것인지 궁금합니다!

말씀하신 방법이 `묵찌빠 게임` 객체에서 승/패 여부를 판단하는 로직을 `심판` 객체로 분리해서 `묵찌빠 게임`으로 주입해주는 구조를 만들고 각각을 테스트 하는 것을 말씀하신거라면  정말 좋은 접근이라고 생각해요 :thumbsup:
연관성이 있는 메서드들도 각각 테스트를 위해 객체로 분리하는 정도가 아니라면.. 테스트를 위한 분리라기보단 역할별로 분리한다고 봐야겠네요.

private 메서드의 테스트는 사람마다 의견이 갈릴 수 있는데, private으로 선언된 메서드를 외부에서 직접 호출하는 일은 없을테니 저는 외부로 노출되는 메서드의 테스트만 수행되면 된다고 생각합니다 :thinking:

### STEP2의 비지니스 로직 테스트 방법

지금은 구조가 테스트하기 어려운 구조로 짜여져있어 설명 드리기가 어렵네요 🥲

`Bank`를 예시로 들어보자면 일단 내부에서 랜덤값으로 `Customer`를 생성해버리면 외부에선 사실상 몇 명의 `Customer`를 생성했는지 알 수 없기에 `Customer` 생성의 책임을 다른 객체로 옮기고 `Bank`는 `Customer`를 주입받는 구조가 되어야 할 것 같구요.

의존성을 가지는 객체인 `BankClerk`의 `work` 메서드로 `Customer`를 잘 넘겨주는지를 확인해야 하는데, 이를 위해선 `BankClerk` 또한 추상화해서 외부로부터 주입받도록 구현되어야 합니다.
테스트에선 구체타입 `BankClerk`가 아닌 `work(for:)` 메서드를 강제하는 프로토콜을 채택한 모의 객체를 주입해줘서 구체타입 `BankClerk` 가 어떻게 구현되어 있는지와 관계없이 `Bank` 의 로직만 독립적으로 테스트하게 될거에요.

그리고 코멘트에도 남기긴 했는데 뷰의 영역(`print` 호출)은 테스트하기 어려워서.. 작업이 완료됐을 때 결과를 전달하는 로직을 구현하고 그 값이 예상한 값인지 테스트해야 할 것 같아요.

제가 쓴 글을 제가 읽어봐도 이해가 잘 안되는데.. 혹시나 이거 보시고 너무 어려우면 말씀해주세요 🙏
(그렇다고 말을 잘하는 것도 아니니 기대하진 마시길..)

### testcode 메서드 테스트 하는 단위

음 저는 " `peek이라는 기능` 하나를 테스트 했으니 괜찮다" 는 쪽이긴 한데..
`첫번째 값을 꺼내오는지 + LinkedList의 상태를 변화시키지 않는지` 를 각각 분리했을 때 어떤 이점을 얻을 수 있는지 궁금해요! :eyes:
예시로 보여주신 것 처럼 작성해도 `첫번째 값을 꺼내오는지 + LinkedList의 상태를 변화시키지 않는지` 둘 중 하나에서만 실패하는 경우 어디에서 실패했는지 이유를 로그로 보여줘서 오히려 코드만 늘어나고 테스트 코드를 이해하는데엔 큰 차이가 없을 것 같아서요 :thinking:



-----



남겨드린 답변 중 좀 어려운 내용도 섞여있는데, 이해안되는 부분 있으면 언제든지 말씀해주세요!
고생하셨습니다 :bow:

2022-04-29 13:17 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private let clerk = BankClerk()
저희가 생각했을 때 Clerk이라는 것을 사용하게 되면 놀고 있는 점원에게 손님을 할당시켜줘야 하는데 어떤 점원이 놀고 있는지 어렵다고 판단해서 
```swift 
let semaphore = DispatchSemaphore(value: 6)
semaphore.wait()
clerk.work(customer) // 정확히 어떤 점원에게 일을 할당해야하는지 알 수 없음
semaphore.signal()
```
이런식으로 호출을 하면 논리적으로도 말이 안된다고 판단해서 이를 은행창구가 손님을 받아서 하는게 더 말이 된다고 생각했습니다. 그래서 네이밍 수정을 했습니다!

프로토콜을 활용해서 외부에서 주입받도록 수정했습니다! 

```swift
protocol BankWindow { }

extension BankWindow {
    func work(for customer: Customer) {
        print("\(customer.waitingNumber)번 고객 업무 시작")
        Thread.sleep(forTimeInterval: 0.7)
        print("\(customer.waitingNumber)번 고객 업무 완료")
    }
}
```

2022-04-29 13:24 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    func work(for customer: Customer) {
STEP3가 이미 공개되었기에..

STEP3에서 은행창구를 대출창구, 예금창구로 나누고, 
해당 창구에서 근무하는 은행원을 semaphore(value: 명) 으로 설정해서 동시성을 구현할 예정입니다..!

그래서 BankWindow으로 추상화 했고, 추후 각각 채택해여 구현할 예정입니다 :)

2022-04-29 13:37 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        Thread.sleep(forTimeInterval: 0.7)
메인스레드가 아닌 다른 스레드에서 동작하게끔 수정했습니다!
```swift
        DispatchQueue.global().sync {
            Thread.sleep(forTimeInterval: 0.7)
        }
```

2022-04-29 13:52 UTC, FirstDo commented on BankManager.swift
> +        case .none:
Swift의 Optional은 열거형입니다
some과 none으로 이루어져 있는것으로 알고있습니다

```swift
case .some(Wrapped)
case .none
```

switch문은 비교값으로 Optional값을 받을 수 있고
Optional값과 nonOptional 값의 == 비교는 가능한 것으로 알고있습니다

그래서 .bankOpen, .exit과 같은 nonOptional 값과 MenuOption? 값이 비교가 가능했던것 같습니다

```swift
switch inputUserOption() {
case .bankOpen:
    break
case .exit:
    break
case .none:
    break
}
```

그리고 열거형 case가 두개인데,
그 두개에 다 걸리지 않으면, 남은건 nil 값 밖에 없으므로, .none 이라는 케이스를 사용했습니다

2022-04-29 14:52 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            waitingQueue.enqueue(Customer(waitingNumber: number))
BankManger에서 Bank는 단 한번만 초기화 되고, 해당 Bank을 이용해서 반복적인 실행을 하므로, 초기화 시점에 해당 코드를 작성할 수가 없었습니다. 
그래서 부득이 하게, add()라는 매서드를 만들어주어서, 외부에서 해당 매서드를 호출해 Queue에 Customer를 주입해주는 형태로 변경하였습니다

Customer

```swift
protocol Customer {
    var waitingNumber: Int { get }
    init(waitingNumber: Int)
}

extension Customer {
    static func randomCustomers() -> [Self] {
        var customers = [Self]()
        let customerCount = Int.random(in: 10...30)
        for number in 1...customerCount {
            customers.append(Self(waitingNumber: number))
        }

        return customers
    }
}
```

BankManager
```swift
bank.add(customers: BankCustomer.randomCustomers())
bank.open()
```

Bank
```swift
    func add(customers: [Customer]) {
        customers.forEach { customer in
            waitingQueue.enqueue(customer)
        }
    }
```

2022-04-29 17:32 UTC, TTOzzi commented on BankManager.swift
> +        case .none:
정확히 이해하고 계신 것 같습니다 😊
추가로 개인적인 의견을 살짝 덧붙이자면.. 정상 동작과 예외처리를 함께 처리하기보단 `nil`이 반환되는 예외 상황은 명시적으로 `guard` 문을 사용하는 게 더 이해하기 쉬운 코드 같아요.
지금은 `inputUserOption`의 반환값이 `none` 케이스를 가지는 것인지, `Optional`이라 `none` 케이스가 있는 것인지 구현부를 보지 않고는 알기 어려울 것 같아서요 🤔

2022-04-29 18:25 UTC, TTOzzi approved these changes
피드백 반영 속도가 굉장히 빠르시군요 ㄷㄷ
semaphore를 언급하신 부분은 다음 스텝에 반영되는 내용인거죠? 요건 다음에 구현하신 내용보고 코멘트 드릴게요!

수정하신 부분에 대한 코멘트 남겨뒀고, 수정할 부분이 있다면 다음 스텝을 진행하면서 수정해보아요 🙂 
제가 남겨드리는 피드백은 100% 반영할 필요 없고, 에디와 두두가 이야기해보시고 좋은 방향이라고 생각된다면 반영해주시면 됩니다 🙏 
저도 제 경험을 토대로 달아드리는 코멘트도 있어서 항상 맞는 방향이라고 생각하진 않아요.
이건 아닌 것 같은데.. 싶으면 언제든지 말씀해주세요. 

그럼 고생하셨습니다!

2022-04-29 18:25 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var delegate: BankResultDelegate?
지금은 `BankResultDelegate`를 채택하는 객체가 구조체임을 알고 있고, 앞으로 다른 객체가 채택할 일이 없을 것 같긴 하지만..
언제든 클래스가 채택할 수 있기 때문에 순환 참조를 방지하기 위해 `delegate` 는 항상 `weak`로 선언되어야 합니다.
다음 스텝 진행하면서 수정해보면 좋을 것 같아요!

2022-04-29 18:25 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
> +    init(waitingNumber: Int)
`Customer` 타입을 사용하는 곳에서 `Customer`가 `waitingNumber`를 받는 생성자를 갖고 있음을 알 필요가 있을까요? 👀 
프로토콜의 구현 의도가 `Customer`를 채택한 프로토콜은 꼭 이 생성자를 구현해야 하는 것을 명시해주기 위함이 아니라 타입의 추상화를 위함이라면 `Customer`를 사용하는 곳의 시점에서 구현되어야 할 것 같아요.

2022-04-29 18:25 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
> +            customers.append(Self(waitingNumber: number))
여기서 사용하고 있었군요..!

2022-04-29 18:25 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
> +}
프로토콜의 구현부를 비우고, `extension`으로 `work(for:)` 메서드를 구현해주신 이유가 궁금해요 👀 
해당 비즈니스 로직은 추상타입 `BankWindow`보단 구체타입인 `BankCommonWindow`가 가져야 할 로직 같아보여서요.
`BankWindow`를 채택하는 모든 객체가 0.7초의 딜레이를 가지고 스레드를 재우는 동작을 해야할까요?
딜레이가 다를수도, 동작 방식이 다를수도 있을 것 같습니다. 
`BankWindow` 프로토콜은 `work(for:)` 메서드를 가지고 있음을 보장하는 정도가 딱 추상 타입으로서의 역할인 것 같아요.

2022-04-29 18:25 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
> +}
추가로 여기도 `print` 출력부를 뷰의 영역이라 생각한다면 분리해주는 게 좋을 것 같아요.
좀 더 쉽게 이야기하면 지금 콘솔 앱의 `BankWindow`를 뷰가 있는 앱으로 옮겼을 때 `print`로 출력되고 있는 정보를 뷰로 전달해 보여줄 수 있는 구조인가.. 를 생각해보시면 될 것 같습니다!

2022-04-29 18:25 UTC, TTOzzi commented on BankManager.swift
> +}
추가로 `Delegate` 프로토콜과 내부 메서드의 네이밍에 대한 가이드라인은 없지만, 대부분 애플의 `Delegate` 네이밍을 따라가는 편입니다.
`Delegate` 패턴을 사용할 때 애플에서 제공해주는 `Delegate` 프로토콜과 같은 형태의 일관적인 네이밍을 채택하면 다른 개발자들이 봤을 때도 이해가 더 쉬울 것 같아요.
프로토콜의 네이밍은 누구의 동작을 위임하는지 알 수 있도록, 메서드의 네이밍은 "프린트 해줘!" 보단 "나 ~~ 했어!" 의 형태가 되어야 할 것 같네요.
대표적으로 자주 사용되는 [UIScrollViewDelegate](https://developer.apple.com/documentation/uikit/uiscrollviewdelegate)를 참고해서 바꿔볼 수 있을까요? 👀

2022-04-29 18:25 UTC, merged

2022-04-30 10:43 UTC, FirstDo commented on BankManager.swift
> +}
protocol의 위치를 Bank로 옮겨주었습니다 :)
네이밍과, 매서드 네이밍도 다음같이 변경했습니다..!

```swift
protocol BankDelegate {
    func bankWorkDidFinish(count: Int, hour: String)
}
```

2022-04-30 10:46 UTC, FirstDo commented on BankManager.swift
> +    }
다음과 같이 변경하였습니다

```swift
extension BankManager: BankDelegate {
    func bankWorkDidFinish(count : Int, hour: String) {
        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(count)명이며, 총 업무 시간은 \(hour)초입니다.")
    }
}
```

2022-04-30 10:48 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    var delegate: BankResultDelegate?
프로토콜에 AnyObject를 채택해서 weak으로 선언할 수 있게 해줬습니다
```swift
weak var delegate: BankDelegate?
```

2022-04-30 11:53 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
> +            customers.append(Self(waitingNumber: number))
넵 해당 Customer 타입 모두 랜덤한 데이터를 생성할 수 있게 해주려는 의도였습니다..!

2022-04-30 11:53 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
> +    init(waitingNumber: Int)
기본구현으로 Customer 생성자를 만들려고 하니 이니셜라이저가 필요하더라구요..!
아래에서 더 적었습니다

2022-04-30 11:55 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +class Bank {
깜박했습니다.. ㅠㅠ
예전에 다른 리뷰어께 private, final 요런 키워드는 컴파일러에게 알려주는것도 있지만, 다른 개발자에게 의도를 더욱 명확히 전달하는 면에서 더 의미있다는 말씀을 해주셨던것 같네요!

2022-04-30 12:00 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
> +}
Delegate를 활용해서 print 출력하는 부분을 수정했습니다.
```swift 
protocol BankWindowDelegate: AnyObject {
    func customerWorkDidStart(customer: Customer)
    func customerWorkDidFinish(customer: Customer)
}
```

```swift

extension BankManager: BankWindowDelegate {
    func customerWorkDidStart(customer: Customer) {
        print("\(customer.waitingNumber)번 고객 업무 시작")
    }
    
    func customerWorkDidFinish(customer: Customer) {
        print("\(customer.waitingNumber)번 고객 업무 완료")
    }
}
```

```swift
    private lazy var bank: Bank = {
        var bankWindow = BankCommonWindow()
        bankWindow.delegate = self
        
        let bank = Bank(window: bankWindow)
        bank.delegate = self
        
        return bank
    }()
```
bankWindow와 Bank 델리게이트 채택하는 부분을 위와 같이 수정했습니다!

2022-05-01 03:30 UTC, FirstDo commented on BankManager.swift
> +        case .none:
또치의 피드백을 보고 guard let 으로 바인딩을 해주려고 했으나 그냥 invalidInput이라는 케이스를 하나 더 만들어서 잘못된 입력일 경우 해당 케이스를 가지게 해주었습니다 :)

```swift
private enum MenuOption: String {
    case bankOpen = "1"
    case exit = "2"
    case invalidInput
}
```

```swift
        switch inputUserOption() {
        case .bankOpen:
            bank.add(customers: BankCustomer.randomCustomers())
            bank.open()
            start()
        case .exit:
            break
        case .invalidInput:
            print("잘못 입력했습니다. 다시 입력해주세요")
            start()
        }
```

```swift
    private func inputUserOption() -> MenuOption {
        guard let userInput = readLine()?.trimmingCharacters(in: .whitespaces),
              let userSelection = MenuOption(rawValue: userInput) else { return .invalidInput }
        
        return userSelection
    }
```