은행 창구 매니저 [STEP2] Taeangel, Tiana
yagom-academy/ios-bank-manager pull request #156
Opened 2022-04-28 08:44 UTC by Taeangel

안녕하세요 @lina0322 STEP2 PR보냅니다.
잘부탁드립니다. 🙏🏿

### 고민한 점
1. Node 파일 이동 대신 private 으로 설정
* enqueue할 때 Node를 알 필요가 없다고 판단해서 LinkedList의 append 메서드의 매개변수와 내부에서 Node를 생성하도록 수정했습니다.
* Node가 사용되는 곳이 LinkedList 뿐이어서 Node 타입을 private으로 접근 제어자를 수정했습니다.

2. 하드 코딩 지양
* 처음에는 nested type으로 Constant를 만들어서 사용했습니다.
* 그런데, 이 타입이 정의된 목적은 하드 코딩을 하지 않는 것뿐이고 외부에서 사용되지 않을 것 같아서 private으로 타입의 접근제어자를 설정하고 기존에 있던 타입의 외부로 위치를 위동시켰습니다.

3. DispatchQueue.global().sync
* async의 경우 block을 하지 않고 진행하기 때문에 기능요구서에서 바라는 바와 맞지 않습니다.
* async로 한 경우 아래와 같이 재귀함수가 의도대로 동작하지 않아서 반복 구문이 종료되지 않습니다.

<img src="https://i.imgur.com/q4R5t1P.png" height="600">

* main.sync의 경우 deadlock이 발생해서 사용할 수 없습니다.

4. 소수점 내림
```swift
extension Double {
    var formatSecondDecimal: String {
        return String(format: "%.2f", floor(self * 10) / 10 )
    }
}
```
* Double을 extension해서 연산 프로퍼티로 원하는 형태로 값이 나오도록 구현했습니다.
* 직원이 일을 하는 매서드(work)에서 0.7초 동안 sleep을 하도록 했습니다.
* 이때, 은행 업무 시간 중(bank.open이후) 직원이 print문을 실행하는 등의 다른 부수적인 일을 진행해서 `0.7 X 반복 횟수` 만큼 나오지 않습니다.
* 따라서, 불필요한 값을 버리기 위해 소수점 한자리에서 내림을 하도록 10을 곱하고 floor 매서드를 통해 내림을 진행하고 다시 10을 나누는 것으로 해결했습니다.

### 궁금한 점

* struct의 mutating을 사용하여 값을 복사하여 메모리를 사용하는 경우와 class를 사용하여 heap 메모리를 사용하는 방법중에 어느것이 메모리 낭비가 더 심한지 궁금합니다.

2022-05-02 04:32 UTC, lina0322 requested changes
안녕하세요~~ STEP2도 알차게 해내셨군요!
좋습니다^_^

PR 보내주신 내용에 

`async의 경우 block을 하지 않고 진행하기 때문에 기능요구서에서 바라는 바와 맞지 않습니다.
async로 한 경우 아래와 같이 재귀함수가 의도대로 동작하지 않아서 반복 구문이 종료되지 않습니다.`
이런 말씀을 해주셨는데요! 두번째 문장에서 의도대로 동작하지 않는다는 부분이 block을 하지 않기 떄문에 발생하는 문제인가요?👀 
둥글둥글하게 말씀해주셔서, 알고 계신건지 모르고 계신건지 정확히 파악이 안되어 조금 자세히 말씀 부탁드립니당🙏

또 main.sync의 경우 deadlock이 발생한다고 하셨는데, deadlock은 어떤걸까요??😀

마지막으로 class와 struct관련해서는 
[관련 아티클](https://betterprogramming.pub/classes-vs-structs-basics-and-memory-management-4707714d82e7) 읽어보시면,
두분이서 충분히 답을 얻으실 수 있을 것 같네요.

화이팅🎉

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    let number: Int
number는 고객 고유 번호인가요??

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    }
LGTM👍

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +}
상수화 좋습니다!

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var clientCount: Int = DefaultNumber.clientCount.rawValue
enum의 카운트를 변경하는 것 보다, Bank자체가 생성될때 수를 넣어주는건 어떨까요?👀
지금처럼 기본 값도 가지고 있고요! 
비슷한 이유로 Bank가 생성될때 은행 자체가 고객을 생성한다기보다는 주입받는건 어떻게 생각하세요?
역할의 범위를 어디까지로 나누는지에 따라 다를거같긴한데, 은행이 손님을 생성하는건 어색할 수 있을 것 같아서요!

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
고객의 수가 입력되고, 고객을 `생성`한다기보다 고객에게 대기번호를 numbering하는 느낌도 좋을 것 같네요!

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +}
String에 extension하는 것도 가능할 것 같아요!

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +import CoreFoundation
CoreFoundation을 import한 이유는 무엇인가요??

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    private var bank: Bank = Bank()
위에서 나왔던 이야기랑 마찬가지로 바로 BankManager가 Bank를 생성하는 것 보다 좋은 방법이 있을거에요!

2022-05-02 04:32 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +            bank.clerks[0].work(client: client)
clerks[0]은 다소 위험해보이네요.
안전한 인덱스를 사용한다거나, 배열 자체가 가지고 있는 프로퍼티를 사용하는게 좋을거같아요!!

2022-05-02 08:20 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Client.swift
> +    let number: Int
```swift
struct Client {
    let waitingNumber: Int
} 
```
으로 네이밍을 변경 하였습니다.

2022-05-02 08:53 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var clientCount: Int = DefaultNumber.clientCount.rawValue
[cfb404b](https://github.com/yagom-academy/ios-bank-manager/pull/156/commits/cfb404bb4c883f6372a4e2e8692fa9e5a0ee3cfe)

Bankmanage에서 주입받도록 수정하였습니다.

2022-05-02 09:00 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +import CoreFoundation
CFAbsoluteTimeGetCurrent를 사용하기 위해 CoreFoundation를 import했습니다.

2022-05-02 09:10 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    private var bank: Bank = Bank()
외부에서 bank 값을 주입받도록 init을 생성했습니다.

2022-05-02 09:11 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +            bank.clerks[0].work(client: client)
first 프로퍼티를 사용해서 값에 접근하도록 수정했습니다!

2022-05-02 09:12 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +            bank.clerks[0].work(client: client)
```swift
extension Array {
  subscript(safe index: Int) -> Element? {
    return self.indices ~= index ? self[index] : nil
  }
}
``` 
이렇게 수정할 수도 있고 배열자체가 가지고 있는 프로퍼티를 사용하는 방법이 있을것 같습니다.

2022-05-02 09:14 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +}
```swift
extension String {
    static var empty: Self {
        return ""
    }
}
```
String에 extension 하여 연산프로퍼티로 변경하였습니다.

2022-05-02 09:50 UTC, Kim-TaeHyun-A commented
안녕하세요! 엘림😀 @lina0322 
코멘트 주신 것 감사드립니다.
아래 질문주신 것에 대해 답변했는데 확인 부탁드립니다😆

---

1. async vs sync
> 위 이미지에서 보인 문제는 bank가 영업을 종료했을 때 실행해야하는 것을 제대로 기다리지 못해서 발생한 문제입니다. 따라서, group으로 async로 구문을 실행시키고 wait해서 완료되기를 기다리면 될 것 같습니다.
> async는 실행이 완료되는 것을 기다리지 않고 이후 명령어를 실행하지만 sync는 완료되기를 기다리는 것으로 알고 있습니다.
> 완료되기를 기다리기에 block된다고 볼 수 있을 것 같습니다.

2. deadlock
> 작업이 끝나기를 기다리는 sync의 특성 때문에 Block-wait가 발생한다고 합니다.
> main 스레드는 sync가 끝나기를, sync는 main 스레드의 Block-wait이 끝나기를 기다리는 상태가 되어서 deadlock이 생깁니다.
> 따라서, 어떤 명령어도 수행되지 못하는 상태가 됩니다.


3. 구조체 vs 클래스
> 공유해 주신 링크를 감사드려요😀 상황에 따라 다른 것 같지만 쓰레드에서의 안전성이나 컴파일 측면에서 보면 일반적으로 구조체를 사용하는 것이 더 좋을 것 같네요!

2022-05-02 09:59 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
[0f68bb9](https://github.com/yagom-academy/ios-bank-manager/pull/156/commits/0f68bb9a0e1b40127e090775e982819c76686b01)

메서드의 네이밍을 수정해보았습니다.

2022-05-04 06:38 UTC, lina0322 approved these changes
두 분 고생하셨습니다! 다음 스텝에서 또 해봅시당👍

2022-05-04 06:39 UTC, merged