은행 창구 매니저 [STEP 2] grumpy, marisol
yagom-academy/ios-bank-manager pull request #158
Opened 2022-04-28 14:13 UTC by grumpy-sw

안녕하세요 올라프! @1Consumption
Step2 PR입니다! 잘부탁드립니다🙇‍♀️
___

### 고민한점
#### 📌 1. Bank 인스턴스를 재사용할 수는 없을까?
- 사용자의 입력으로 은행개점이 되었을 때, 현재 코드에서는 그 때 마다 `Bank` 인스턴스를 새로 생성하여 업무 처리를 진행하고 있습니다. `BankManager`가 `Bank`를 프로퍼티로 가지면서 필요할 때마다 값을 설정하여 사용하는 게 더 나은 방법인지 고민이 되었습니다. 
```swift=
if input == bankOpenMenu {
    let bank = Bank(numberOfTeller, randomNumber(in: customerRange))
    ...
}
```
변경을 시도했지만 mutating 키워드로 인해 바꿔야 할 부분이 너무 많아 일단 보류했는데요... 😓 올라프의 생각은 어떠신지 궁금합니다.

#### 📌 2. Customer 타입은 struct로 해야할까 class로 해야할까?
- Customer 타입을 struct로 할지 class로 할지 고민했습니다. 기능상 struct이어도 되지 않을까해서 처음에 struct으로 구현을했었는데, 제네릭에 쓰일 타입은 프로토콜이나 클래스로 제한된다는 내용을 공식문서에서 발견했습니다. Node와 Linked List, Queue의 제네릭에 Customer 타입만 받기 위해서 Customer 타입을 class로 구현했습니다.

#### 📌 3. n명의 은행원이 근무한다는 조건을 어떻게 구현할 것인가?
- 프로젝트의 요구사항에 은행 타입에는 n명의 은행원이 근무한다는 조건이 있지만, 은행원이 어떻게 고객의 업무처리를 돕는지에 대해서는 명시되어 있지 않습니다. 그래서 여러 가능성을 고민해봤지만 일단 콘솔 앱의 요구사항에 따라 단 한 명의 은행원이 근무한다고 가정했습니다. 결국 `numberOfTeller`로 은행원의 수를 관리하기는 하지만, Bank 타입에서는 하나의 `Teller` 인스턴스를 프로퍼티로 쓰고 있습니다. 이 부분을 이번 스텝에서 어떻게 변경해야 할까요?

2022-04-29 17:00 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    }
randomNumber를 만드는 메소드니까 동사형으로 `generate~` 가 되면 좋겠어요.

2022-04-29 17:01 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Teller.swift
> +    }
👍

2022-04-29 17:02 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        head = headNode.next
이미 head 자체가 node인데 굳이 node를 붙여줄 이유가 있을까? 라는 생각이 드네요.

2022-05-02 03:27 UTC, grumpy-sw commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
넵! `addCustomerInLine()` 로 변경했습니다!

2022-05-02 03:31 UTC, grumpy-sw commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
다음 스텝에서 다중 처리를 구현하면서 `DispatchGroup`과 `DispatchQueue`로 바꿔보도록 하겠습니다!

2022-05-02 03:32 UTC, grumpy-sw commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        }
`enum BankManagerMenu`를 만들고 `if menu == .open`과 같이 비교하도록 수정했습니다.

2022-05-02 03:32 UTC, marisol-develop commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +        head = headNode.next
head가 없을때 return nil 하기 위해서 옵셔널 바인딩을 해주었는데 head와 동일한 네이밍을 할 수 없어서 headNode로 네이밍을 지었습니다.🥲

2022-05-02 03:33 UTC, grumpy-sw commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    }
명확한 타입의 리턴값이 있는 메서드는 명사형으로 사용하는 것이 좋다고 생각해서 명사형으로 사용했습니다 😓 `generateRandomNumber`로 수정했습니다!

2022-05-02 03:35 UTC, grumpy-sw commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +}
Customer 타입을 구조체로 변경했습니다!
다만 Node와 LinkedList, Queue까지 모두 변경해줘야 했는데요, 스텝 1에서 Generics 기능을 활용하여 구현하라는 조건이 마음에 걸려 빈 프로토콜인 `Waitable`프로토콜을 생성하고 이를 채택하도록 만들었습니다.

2022-05-02 03:37 UTC, grumpy-sw commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +final class LinkedList<T: Customer> {
'해당 클래스를 상속받은 서브클래스이거나', '해당 프로토콜을 채택하거나' 라는 제약조건이기 때문에, 의미상 구조체가 들어갈 수는 없겠군요. 위의 코멘트처럼 `<T: Waitable>`로 변경하고 Customer 구조체가 Waitable 프로토콜을 채택한 형태로 수정했습니다!

2022-05-02 03:38 UTC, marisol-develop commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue/LinkedList.swift
> +final class LinkedList<T: Customer> {
swift Generics 공식문서에서 아래와 같이 설명하고 있는데요 (https://docs.swift.org/swift-book/LanguageGuide/Generics.html)

> Type constraints specify that a type parameter must inherit from a specific class, or conform to a particular protocol or protocol composition.
타입 매개 변수가 특정 클래스에서 상속되거나 특정 프로토콜을 준수해야한다

Customer를 struct로 바꾸고 제네릭에 넣으면 
“Type ’T’ constrained to non-protocol, non-class type ‘Customer’”라는 오류가 뜨는 것 같습니다. 😭
그래서 Waitable이라는 프로토콜을 만들어서 Customer가 Waitable이라는 프로토콜을 준수하도록 변경해보았습니다.

위에서 올라프께서 하신 “제네릭의 제약사항이 클래스와 프로토콜만 가능하다 인거 같아서요”라는 말씀이 제가 이해한 “제네릭에는 클래스와 프로토콜이 들어와야 한다”와 다른 의미인걸까요?

2022-05-02 15:03 UTC, 1Consumption requested changes

2022-05-02 15:03 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    }
👍

2022-05-02 15:03 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +}
디코에서 말했듯이 waitable 프로토콜은 불필요해보입니다.

2022-05-02 15:33 UTC, marisol-develop commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +}
제네릭에 불필요하게 타입 제약을 주려다 만든 프로토콜이었는데, 삭제했습니다!

2022-05-03 11:10 UTC, merged