은행 창구 매니저 [STEP 2] Onetool, Red
yagom-academy/ios-bank-manager pull request #159
Opened 2022-04-28 15:10 UTC by kimt4580

@jungseungyeo
안녕하세요 린생☺️
프로젝트 STEP2 PR보냅니다!
잘 부탁드립니다🙇🏻‍♂️🙇🏻‍♀️

## 🤔 고민했던 것들
* 꼬리재귀 
* 프로퍼티 옵져버, KVO, delegate
* n명이 근무하는 것을 구현

### 꼬리재귀 
![start](https://i.imgur.com/UpbldfZ.png)

![action](https://i.imgur.com/0ip4gTt.png)

![active](https://i.imgur.com/YEU4j8o.png)

처음엔`openBank` 메서드를 재귀로 구현하게 되어서 메서드가 Queue에 계속해서 쌓였습니다.
재귀 메서드를 꼬리재귀 형태로 구현할 경우 swift 의 컴파일러는 꼬리재귀 최적화를 해주어서 Queue에 쌓이지 않도록 해준다고 알고 있어, `openBank`와 `doWorking` 메서드를 분리해 `doWorking` 메서드가 꼬리재귀 형태가 되도록 만들어 주었습니다.

![compiler](https://i.imgur.com/NRvCk9O.png)
컴파일러 최적화를 위해, Optimization Level 설정을 해주었습니다.
Optimization Level 의 Debug 와 Release를 Optimize for Size[-Osize], 또는 Optimize for Speed[-O] 둘중에 하나로 설정해주면 된다는 것을 알았고, 메모리로 공간의 최적화를 우선으로 할 것인지 시간을 우선으로 할 것인지를 선택하는 것이였습니다. 

### 프로퍼티 옵져버, KVO, delegate
처음엔 BankManager 가 Banker 의 customer 변수에 Cutomer 을 할당 해주면, 프로퍼티 옵저버를 이용해서 손님의 일을 처리해주고 print 문을 찍어주는 구현을 했습니다. 
```swift
class Banker {
    var customer: Customer? {
        didSet {
            work()
        }
    }
    
    func work() {
        guard let customerNumberTicekt = customer?.numberTicekt else {
            return
        }
        
        print("\(customerNumberTicekt)" + Const.startWorking)
        usleep(useconds_t(Const.workTimeForCustomer * Const.microsecond))
        print("\(customerNumberTicekt)" + Const.endWorking)
        customer = nil
    }
}
```
이렇게 되면 `Banker` 의 `customer` 가 `nil` 이 될때, `BankManager` 가 그것을 tracking 하고 있다가 새로운 손님을 할당 해주어야 했습니다. 
`KVO` 를 이용해서  `Banker` 의 `customer` 를 tracking 하려고 했지만 `customer` 의 타입이 저희가 정해준 타입이었기 때문에 실패했습니다. 

값을 넘겨줄 때, `delegate` 패턴을 이용해서 값을 넘겨주는 것도 구상 했었지만 `Banker` 에서 `BankManager` 로 값을 전달해야 할 일이 없어져서 의미가 없어 삭제 했습니다. 

### n명이 근무하는 것을 구현 
지금은 은행에 1명이 근무하지만 여러명이 근무한다는 것을 구현하기 위해서 은행을 개설할 때, 은행원의 수를 받을 수 있도록 설정하고 초기 값을 1로 설정했습니다.
은행원의 수의 따라 bankers Array에 은행원을 생성해 넣어주었습니다. 

```swift
private var bankers: [Banker] = []

init(numberOfBanker: Int = Const.defaultBankerCount) {
    initialize(numberOfBanker: numberOfBanker)
}

private func initialize(numberOfBanker: Int = Const.defaultBankerCount) {
    numberOfCustomer = Int.random(in: Const.customerRange)
    for numberTicekt in Const.startCount...numberOfCustomer {
        customers.enQueue(data: Customer(numberTicekt: numberTicekt))
    }
    
    for _ in Const.startCount...numberOfBanker {
        bankers.append(Banker())
    }
}
```
init 을 다른 메서드로 나눠준 이유는 초기화를 또 사용하는 곳이 또 있기 때문에 저렇게 설정 했습니다. 

## 😭 조언 받고 싶은 내용
* 하드코딩 없애기 
* useconds_t

### 하드코딩 없애기 
`Const` `enum` 을 이용해서 하드 코딩을 없애 주었습니다. 
그런데 `BankManager` 객체의 `openBank() -> Bool` 메서드의 
```swift
 print("오늘 업무를 처리한 고객은 총 \(numberOfCustomer)명이며, 총 업무 시간은 \(String(format: Const.twoDecimal, wholeWorkTime))초 입니다.")
```
이 부분을 어떻게 Const 로 만들어 주어야 할지 모르겠습니다. 
```swift
enum Const {
    static let todayWorkCustomerIs = "오늘 업무를 처리한 고객은 총"
    static let numberOfPeopleAndWholeWorkingTimeIs = "명이며, 총 업무 시간은"
}
```
이런식으로 작성하는 것은 뭔가 이상하다고 저희는 생각했습니다. 
이렇게 문자 사이사이에 문자열 보간법을 사용할 경우 어떻게 하드 코딩을 지양할 수 있을지 궁금합니다. 

### useconds_t
```swift
usleep(700000)
```
이러한 형태에서, Const를 사용하여 수정해주었습니다. 하지만 컴파일러가 에러를 보냈고
```swift
//Const.workTimeForCustomer = 0.7, Const.microsecond = 1000000

usleep(useconds_t(Const.workTimeForCustomer * Const.microsecond))
```
위와 같이 수정하라고 제안하였습니다. 컴파일러의 제안대로 수정하였고, 정상 작동했습니다. 하지만 어느 상황에서 사용하는 것인지 궁금하여 `useconds_t`에 대해서 공식문서나 구글링을 하였지만 찾을 수 없어서 이렇게 질문을 남기게 되었습니다. 어떤 것을 의미하고 어느 상황에서 사용하는 걸까요?

2022-05-02 13:02 UTC, cherrishRed commented on BankManager.swift
> +    private func openBank() -> Bool {
네 역할을 분리 해주었습니다.

2022-05-02 13:03 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +    var customer: Customer?
네 캡슐화를 지키도록 구조를 다시 계선 했습니다. 지금은 Banker 가 customer 변수 자체를 가지고 있지 않고 메서드의 파라미터로 받고 있습니다.

2022-05-02 13:04 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +        usleep(useconds_t(Const.workTimeForCustomer * Const.microsecond))
Thread.sleep 으로 방식을 바꿨습니다!

2022-05-02 13:05 UTC, cherrishRed commented on BankManagerConsoleApp/Enum/Const.swift
> +    static let endWorking = "번 고객 업무 종료"
상수들을 하나의 파일에 모아 두었다가, 린생이 이야기 하신 것 처럼 확인하기 더 어려워 지는 것 같아서, 사용하는 각각의 파일들의 Const 의 extension 을 만들어 배치해 주었습니다.

2022-05-02 13:08 UTC, cherrishRed commented on BankManager.swift
> +            print(Const.wrongInput)
`UserChoice` 라는 enum 타입을 만들어 switch 문의 default 를 없애 주었습니다.

2022-05-02 13:09 UTC, cherrishRed commented on BankManager.swift
> +        _ = bankers.map { banker in
map 은 배열의 값들을 일정한 규칙에 따라 변경하여 새로운 배열을 리턴해 줄 때 사용합니다. 
여기에서는 저희의 사용법이 조금 잘 못 되었던 것 같습니다.

2022-05-02 13:09 UTC, cherrishRed commented on BankManager.swift
> +        initialize()
`reset` 이라는 명칭을 가진 메서드로 수정하였습니다.

2022-05-02 13:20 UTC, cherrishRed commented on BankManager.swift
> +            doWorking()
`doWorking` 메서드 안에서 호출하는 `manageBankers` 의 시간 복잡도는 O(n) 으로 계산하였고, `doWorking` 자체만의 시간 복잡도도O(n) 이어서 최종적으로 `doWorking` 은 O(n) 으로 계산하였습니다.

2022-05-02 13:22 UTC, cherrishRed commented on BankManager.swift
> +    func decideOpenBank() {
`decideOpenBank` 는 재귀를 하고 있는 메서드 입니다. 
최약의 케이스의 안에서 호출하고 있는 메서드들중 차수가 가장 높은 것을 계산해보니, O(2^n)이었습니다. 

>O(2^n)은 기하급수적 복잡도(exponential complexity)라고 부르며, Big-O 표기법 중 가장 느린 시간 복잡도를 가집니다.

저희가 만든 메서드가 아주 느린 메서드 인 것을 알게 되었습니다. 😭

2022-05-02 13:24 UTC, cherrishRed commented
@jungseungyeo
린생! 저희 리펙토링 완료 했습니다!

리뷰를 달아주신 것 바탕으로 수정하였습니다!

리펙토링 사항
- [x] Bank 객체 생성
- [x] 각 객체 간의 캡슐화와 은닉화
- [x] 재귀 제거 
- [x] usleep -> Thread.sleep 으로 변환
- [x] UserChoice enum 생성 (switch 문의 default 제거)
- [x] initialize -> reset 으로 변경
- [x] openBank 메서드 역할 분리
- [x] DispatchQueue를 이용
- [x] DispatchSemaphore 를 활용해 Banker의 수 정해주기
- [x] Manageable 이라는 프로토콜로 Bank 와 BankManager 사이의 의존성 낮추기

2022-05-03 11:36 UTC, jungseungyeo requested changes
원툴, 레드 고생하셨습니다.

몇가지 수정 되어야 하는 부분이 있어서 코멘트 남겼습니다.
전이랑 비교하여 많은 개선이 되었네요 ㅎㅎ 너무 좋습니다

Const를 사용하는 곳으로 이동한 부분이랑 재귀를 안쓰고 DispatchQueue를 사용하는 부분이 좋았습니다.

여기서 thread를 사용하는데 있어서 비동기 로직이다보니 몇가지 문제가 있어서 코멘트 남겼습니다. 혹시 작업하다가 궁금한 점이 있으면 알려주세요 ㅎㅎ

2022-05-03 11:36 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func manageBanker() {
Thread가 여기서 3개가 생기네요 ㅠㅠ..
![image](https://user-images.githubusercontent.com/32052386/166443319-8618ff83-f3f8-4235-ac8e-f595c5f6370a.png)

실행 후 
![image](https://user-images.githubusercontent.com/32052386/166443413-b2f6dfea-52a1-4ed3-84f7-09d5117a8398.png)

또 작업이 순차적으로 동작이 되지 않네요 1번째 고객이 먼저 끝나야 맞을거같습니다. 

![image](https://user-images.githubusercontent.com/32052386/166443505-95265f5d-1d1e-4da6-8f52-388f0cda5abe.png)

1번째로 왔는데 제일 늦게 해주면 화나지 않을까요..? ㅠㅠ 비동기 로직이 보시면 좋을거같아요 ㅎㅎ

DispatchSemaphore가 글로벌로 존재하면 안될거같습니다.

2022-05-03 11:36 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +        let runloop = RunLoop.current
런루프가 무엇인가요? 이것이 동작되는 원리가 무엇일까요?
DispatchqueueAfeter의 차이가 무엇일까요? 현재 어느 기능이 맞을까요?

https://stackoverflow.com/questions/55131532/difference-between-dispatchsourcetimer-timer-and-asyncafter

이 글을 참고하면 좋을거같습니다 ㅎㅎ

2022-05-03 11:36 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +        let runloop = RunLoop.current
Timer는 주로 런루프 기반으로 동작이 되어 선호하는 방식은 아니예요. Dispatchqueue를 사용하여 queue 이용하여 동작하는 것을 선호하고 있습니다.

2022-05-03 11:36 UTC, jungseungyeo commented on BankManager.swift
> +        while result == true {
```suggestion
     whilte workBank() { }
```

위와 같이 변경하면 불필요한 변수는 안생길거같아요

2022-05-03 11:36 UTC, jungseungyeo commented on BankManager.swift
> +        case UserChoice.start:
```suggestion
        case .start:
```

이렇게 사용하는 편입니다. ㅎㅎ

2022-05-03 11:36 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            wholeWorkTime += Const.workTimeForCustomer
이건 그냥 for문을 돌린 횟수만큼 더하는거 아닌가요? 정말로 동작이 된 시간을 구하면 좋을거같아요

2022-05-03 13:34 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func manageBanker() {
저희가 Semaphore 가 잘 작동하는지 확인하려고 3 으로 주고 테스트 한 코드를 푸시한 것 같습니다. 
1로 바꾸고 푸쉬했습니다!

2022-05-03 13:35 UTC, cherrishRed commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            wholeWorkTime += Const.workTimeForCustomer
CFAbsoluteTimeGetCurrent 메서드를 이용해 동작 시작시간과 동작 종료시간을 구해서, 연산하여 처리하였습니다!

2022-05-03 13:37 UTC, cherrishRed commented on BankManager.swift
> +        while result == true {
넵! 위와 같이 수정했습니다!

2022-05-03 13:53 UTC, kimt4580 commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +        let runloop = RunLoop.current
런루프는 어떠한 이벤트가 생겼을 때, 스레드에게 일을 시키거나 쉬도록 하는 스레드 관리 Loop입니다. 동작 원리는 이벤트가 발생하면 두 가지 소스(input source, timer source)를 수신해서 핸들러를 실행하는데, 언제 실행 할지 결정해 줍니다. 결정해주는 방법으로는 run()이 있습니다. Timer는 반복이 필요할 때 사용되고, asyncAfter는 한번만 실행할 때 많이 사용됩니다. 또한 Timer보다 asyncAfter의 정확도가 더 높다는 것을 알게되었고, Timer는 asyncAfter 보다 자원을 덜 소모하며, 더욱 세부적인 설정이 가능한 것 같습니다.

asyncAfter로 변경해주었습니다!

2022-05-03 13:55 UTC, cherrishRed commented
@jungseungyeo 
린생 리펙토링 하였습니다!

- [ ] 은행원의 수를 1로 변경(세마포 수 변경)
- [ ] 컨벤션 수정 (불필요한 변수 제거)
- [ ] 직접 메서드 실행 시간 구하도록 로직 변경
- [ ] timer를 asyncAfter 로 변경

2022-05-04 01:34 UTC, jungseungyeo approved these changes
레드, 원툴 고생하셨습니다.

해당 step에서 많은 수정이 있었는데요. Thread를 다루다보니 수정상항이 많아 졌던거 같습니다. 
작업을 하면서 어느 정도 GCD의 이해가 되었는지 모르겠네요 ㅎㅎ 

고생하셨습니다. 다음 step 진행 부탁드립니다. ㅎㅎ

2022-05-04 01:34 UTC, merged