은행 창구 매니저 [STEP2] 우롱차, Minseong
yagom-academy/ios-bank-manager pull request #160
Opened 2022-04-28 15:28 UTC by Minseong-yagom

@yoo-kie 
안녕하세요~ 개굴😊
STEP2 PR 완료 하였습니다!
잘 부탁드리겠습니다~🍀 
## UML
<img src="https://user-images.githubusercontent.com/94295586/165787482-95ae1880-7195-40d6-9deb-64a6c6ca1dac.jpg" width="1000" height="500"/>

## 고민한점
1. 설계를 하고 코드를 짜다 보니 기능 단위로 커밋을 하고 싶은데 다른 객체에서 기능을 가져와서 써야하다 보니 아직 미구현 된 상황이 많았습니다 이러한 경우 커밋을 어떻게 해야 하는게 좋은건가요??

## 조언 받고 싶은 부분 
1. 
```swift
static let finishMessageFormat = "업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 %d명이며, 총 업무시간은 %.2f초입니다."
String(format: BankProcessConstant.finishMessageFormat, totalClientCount, totalWorkingTime)
```
- BankProcess 부분에서 명수와 총 업무시간을 받는 더 좋은 방법이 있는지 궁금합니다

2022-05-01 04:15 UTC, dnwhd0112 commented
고민한 점 +
스텝2를 설계하고 코드를 다 짜고 보니 변경에 대한 고려를 1도 안했다는게 느껴졌습니다. 이에 대한 해결 방안으로는 pop 밖에 없나요???

2022-05-01 16:55 UTC, yoo-kie requested changes

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +    }
clerkCount와 spendingTimeForAClient는 상수를 전달받아 Bank에서 프로퍼티로 대입되고 있는데요. Bank 내부에서만 사용되는 상수라면 굳이 전달받지 않고 Bank 내부 자체 상수로 추가해서 사용하면 되지 않을까요?

아래의 제안과 같이 외부 주입은 Bank에서 필요하지만 Bank와 강하게 결합(의존)되어지지 않을 데이터만 전달해주면 좋을 것 같습니다.
```suggestion
    init(clientQueue: Queue<Client>) {
        self.clientQueue = clientQueue
    }
```

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    }
BankClerk의 work 메서드 내부에는 "할당 받은 고객의 업무를 주어진 시간동안 처리하는 작업"만 있어야 적절한 역할을 한다고 생각합니다. 그런데 work 메서드 내부에서 고객을 할당받고 업무 데이터까지 갱신시켜주고 있네요. 고객을 할당하고, 업무 데이터를 갱신시켜주는 것은 Bank에서 할 순 없을까요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +        self.spendingTimeForAClient = spendingTimeForAClient
spendingTimeForAClient도 위에서 말씀드렸던 상수들과 같이 외부에서 전달받지 않고 BankClerkConstant에 추가해주세요.

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +        }
bankClerk가 work 메서드를 호출하는 시점에서 업무 처리가 필요한 client도 여기에서 dequeue하여 전달해줄 순 없을까요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +    }
고객에 대한 네이밍은 customer와 client 중 하나로 통일시켜주시길 바랍니다-!

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/ClientManager.swift
> +struct ClientManeger {
ClientManeger는 어떤 역할하는 타입인가요? 현재는 clientQueue를 생성하고 반환하는 메서드만 존재하는데요. 그건 clientQueue가 필요한 시점에서 구현되어도 될 것 같습니다.

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/ClientManager.swift
> +    }
상수를 굳이 외부에서 전달받을 필요가 있을까요? 내부에서 자체적인 Constant를 구현하시고 사용하셔도 될 것 같습니다.

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/ClientManager.swift
> +    }()
`Int.random(in: minClientCount...maxClientCount)` 여러군데에서 사용되지 않고 복잡한 연산이 필요하지 않은 데이터 같은데요. lazy var로 선언하여 클로저로 프로퍼티를 만드신 이유가 있을까요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    private enum BankClerkConstant {
BankClerk 내부에 작성되어 있는 Constant이며 private으로 접근제어가 되고 있기 때문에 네이밍에 BankClerk가 중복해서 들어가지 않아도 될 것 같습니다.
```suggestion
    private enum Constant {
```

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    private let spendingTimeForAClient: Double
저는 변수와 상수를 네이밍할 때 간결 명료하게 꼭 유의미한 사용성을 가지지 않는다면 관사(a/an/the)는 생략합니다.

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +        static let maxClient = 30
변수 상수 네이밍은 어떤 값을 표현하는지 명확하게 표현해주시는걸 권장드립니다. 예를 들어 clerkCount와 같이 minClient에 최소 고객의 수를 의미하도록 Count를 붙여줘서 숫자 데이터임을 명확하게 해주는걸 추천드립니다.
```suggestion
        static let minClientCount = 10
        static let maxClientCount = 30
```

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +                                      maxClientCount: BankProcessConstant.maxClient)
clientManeger를 프로퍼티로 선언한 이유가 있으실까요? Bank로의 의존성 주입 때문이라면 init 메서드 내부에서만 초기화 후 전달해주면 되지 않을까요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +                    spendingTimeForAClient: BankProcessConstant.spendingTimeForAClient)
이미 위에서 언급했지만 상수 clerkCount과 spendingTimeForAClient는 실제 사용되는 타입 내에서 선언되는게 맞지 않을까요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +    }
사용성 확장을 위해 "입력:" 프린트문을 분리하여 연산 프로퍼티로 입력된 값을 반환하는 연산 프로퍼티로 선언하는건 어떨까요?
```suggestion
    private var readInput: String {
        guard let input = readLine() else {
            return ""
        }
        return input
    }
```

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +            start()
start()와 startWorking() 네이밍에 혼선이 있을 수 있을것 같습니다. startWorking은 openBank와 같이 의미를 명확히 해주는 것은 어떨까요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +struct Menu {
코드를 리뷰하다보니 BankProcess만 있어도 될 것 같은데요. `Menu` struct이 별도로 필요한 이유가 있나요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +        static let InputMessage = "입력: "
변수명은 소문자로 시작하는 카멜케이스를 준수하여주시길 권장드립니다.

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +        static let finsh = "2"
각 상수들이 어떤 값을 의미하는지 직관적으로 알 수 있는 네이밍이면 좋을 거 같아요.
ex. 내용(input) + 역할(Message)
```suggestion
        static let bankOpenInput = "1"
        static let finishInput = "2"
```

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +    }
printBankFinish 메서드를 위해 사용되는 데이터(프로퍼티)들이 모두 Bank 내부에서 사용되고 있는데요. 그럼 완료 메세지를 print해주는 메서드는 Bank에 작성하는건 어떨까요?

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    }
while문을 무한 루프로 사용하고 return으로 종료조건을 갖는건 위험해보이네요. 커멘트에서 언급했던 것과 같이 BankClerk가 client를 배정하는 방식을 다시 한번 고민해보시면서 iterator를 함께 개선해보시길 추천드립니다.

2022-05-01 16:55 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +    private(set) var finishedClientCount = 0
printBankFinish를 Bank로 옮기면 두 프로퍼티의 private 접근제어도 가능하겠네요.

2022-05-01 16:59 UTC, yoo-kie commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    unowned private var bank: Bank
unowned가 무엇일까요? 그리고 왜 추가하셨나요?

2022-05-02 07:59 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +    }
하지만 이렇게 할 경우 clerkCount나 spendingTimeForAClient가 바꾸는게 굉장히 불편해질텐대 이 경우 저 두개를 바꿔서 테스트하는게 좀 힘들꺼 같아요! 변할일이 없다면 내부에서 상수로 두는게 맞는거 같습니다.

2022-05-02 08:04 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    }
제가 생각한거는 BankClerk이 자율적으로 일을 하는것이였습니다. 그렇기 때문에 Bank로 부터 적절한 요청을 하고 적절한 요청을 보내도록 설계하였습니다. Bank에서 모든것을 관리하는 경우
 점원들이 일하는지 안하는지에 대한 상태를 검사하는게 필요할것이라 생각되어서 이렇게 짠 느낌도 있습니다. 또한 현실에서도 은행원이 자율적으로 하기 때문에 Bank가 갱신하는게 어색하다고 느꼇습니다. 하지만 개굴이 보기에 하위(BankClerk)이 상위(Bank)의 데이터를 갱신시키는것이 이상하다고 보시면 수정하도록 하겠습니다.
While문은 무한루프로 사용하지 않도록 하겠습니다.

2022-05-02 08:04 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +        self.spendingTimeForAClient = spendingTimeForAClient
알겠습니다.

2022-05-02 08:05 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +        }
알겠습니다. 다른 방식도 생각해보도록 할게요!

2022-05-02 08:05 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +    }
앗... 저희가 다 못바꿧네요 바꾸도록 하겠습니다.

2022-05-02 08:08 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/ClientManager.swift
> +struct ClientManeger {
알겠습니다. 이부분은 필요한곳에서 func을 통하여 만들도록 수정하겠습니다.

2022-05-02 08:08 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/ClientManager.swift
> +    }
이부분도 수정하도록 하겠습니다.

2022-05-02 08:09 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/ClientManager.swift
> +    }()
랜덤한 갯수로 생성을 하였을때 그 랜덤한 숫자값이 기록되어야된다고 생각했습니다.

2022-05-02 08:10 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    private enum BankClerkConstant {
앗 감사합니다.

2022-05-02 08:10 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    private let spendingTimeForAClient: Double
감사합니다!

2022-05-02 08:10 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +        static let maxClient = 30
항상 네이밍은 어렵네요... 감사합니다.

2022-05-02 08:12 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +                                      maxClientCount: BankProcessConstant.maxClient)
그 이유는 Bank 내부에서 clientManeger를 생성하는게 이상하다고 생각했습니다.

2022-05-02 08:12 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +                    spendingTimeForAClient: BankProcessConstant.spendingTimeForAClient)
네 수정하도록 하겠습니다.

2022-05-02 08:14 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +    }
이 방식으로 수정해보록 하겠습니다.

2022-05-02 08:15 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +            start()
동의합니다! 네이밍을 조금 더 고민해보겠습니다.

2022-05-02 08:19 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +struct Menu {
역할을 너무 분리한거 같아요. 사용자에게 메뉴를 보여주는걸 표시할 곳과 실제로 프로세스를 돌리는곳은 나누어야 된다고 생각하였습니다.

2022-05-02 08:19 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +        static let InputMessage = "입력: "
앗... 수정하도록 하겠습니다.

2022-05-02 08:19 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +        static let finsh = "2"
네! 확실히 개굴이 쓴 네이밍이 좋네요!

2022-05-02 08:21 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +    }
위쪽에서도 이야기 했듯이 사용자와 상호작용을 하는 역할은 BankProcess라고 생각하여 구조를 짯습니다! 만약 이 방식이 잘못됬다면 고치도록 할게요 ㅠ

2022-05-02 08:21 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/Bank.swift
> +    private(set) var finishedClientCount = 0
맞습니다.

2022-05-02 08:22 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    unowned private var bank: Bank
unowned를 사용한건 Bank와 BankClerk이 관계 때문입니다. 은행원은 은행에 소유되 있다고 생각하여 은행 없는 은행원은 존재하지 않는다고 판단하였기 때문입니다. unowned를 사용한 이유는 순환참조로 인한 메모리 낭비를 피하기 위해서입니다.

2022-05-02 08:54 UTC, yoo-kie commented
안녕하세요 우롱차, Minseong!

이번 Step2 PR은 1에 비해 많은 작업이 필요하셨던거 같아요😅 고생 많으셨습니다!
PR에서 역할 분리를 위해 고민하신게 느껴져서 관련된 커멘트 몇가지 남겨보았습니다. 그리고 제가 남긴 커멘트는 그대로 반영하기보다 제안이라고 받아들여주시고 두 분의 의견대로 진행하시면 될 것 같습니다!

고생하셨습니다.

2022-05-02 12:59 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/Menu.swift
> +struct Menu {
이부분은 수정하지 않겠습니다!

2022-05-02 13:10 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Console/BankProcess.swift
> +    }
수정하였습니다!

2022-05-02 13:11 UTC, dnwhd0112 commented on BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +    unowned private var bank: Bank
저 친구는 삭제하였습니다.

2022-05-04 12:19 UTC, yoo-kie approved these changes

2022-05-04 12:19 UTC, merged