은행 창구 매니저 [STEP2] 쿼카, 두기
yagom-academy/ios-bank-manager pull request #161
Opened 2022-04-29 06:49 UTC by doogie97

# 은행 step2 PR

@Monsteel 
안녕하세요!토니! STEP2 완료해서 PR보냅니다!
잘부탁드립니다!😁😄

## 조언 받고 싶은 내용

### 1. 매직 리터럴, 매직 넘버에 대한 고민

의견 1: 매직넘버처리는 해주면 가독성이 향상되고 유지보수에 좋기에 처리를 해주는게 좋지 않을까?
의견 2: 여러 곳에서 사용하게 된다면 유지보수 상향에는 동의하나 지금은 한 곳에서만 사용하는데 코드를 늘리면서 까지 유지보수를 신경써야 할까, 상황에 따라 다르지만 무조건적인 매직넘버, 매직리터럴 처리가 과연 가독성이 좋다고 할 수 있을까?

```swift
bankClerk.work(customer: customer)
totalCustomerCount += Constant.numberOne
```
1. 1이라는 값을 할당하는 방법과 Constant.numberOne로 할당하는 방법 중 어느게 가독성에 더 좋아보인다고 생각 하시나요 ?

2. 아래와 같은 부분에서는 전자가 더 가독성이 좋다는 생각이듭니다.
추가로 프로퍼티가 중간에 껴있는데 이를 기점으로 매직넘버를 처리하는 상수를 만드려고도 했으나 naming에 여러의미를 담는게 더 가독성이 좋아질까 ? 라는 의문이듭니다.

[Before]
```swift
func printCloseMessage() {
        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(count)명이며, 총 업무시간은 \(seconds)초입니다.")
}
```

[After]
```swift
func printCloseMessage() {
        print("\(Constant.endWork+Constant.totalWorkTime)\(totalCustomerCount)\(Constant.numberOfPeople+Constant.totalWorkTime)\(workingTime)\(Constant.seconds)")
}
```

3. 매직넘버로 enum을 생성해주었으나 하나의 매직넘버를 처리하기위해 enum이라는 타입을 만드는게 메모리관점에서 좋을지 ??에대한 의문이 듭니다.

### 2. 시간을 측정하는 코드들을 하나의 메서드 묶는 방법이 있을까요 ?

[A방법]
```swift
func checkTime() {
    let startTime = CFAbsoluteTimeGetCurrent()
        sendCustomerToClerk()
        let durationTime = CFAbsoluteTimeGetCurrent() - startTime
}
```
```swift
    mutating func start() {
        receiveCustomer()
        checkTime()
        workingTime = String(format: Constant.twoDecimalPlaces, durationTime)
        printCloseMessage()
    }
```
[B방법]
```swift
    mutating func start() {
        receiveCustomer()
        let startTime = CFAbsoluteTimeGetCurrent()
        sendCustomerToClerk()
        let durationTime = CFAbsoluteTimeGetCurrent() - startTime
        workingTime = String(format: Constant.twoDecimalPlaces, durationTime)
        printCloseMessage()
    }
```
A방법으로 하게되면 checkTime()이라는 메서드가 시간계산과 은행업무처리하는 기능을 둘다 포함하게 되는데 checkTime()이라는 메서드 명을 통해서는 sendCustomerToClerk()의 기능을 갖고있는지 아닌지 분간이 되지 않고, 메서드 네이밍에 두개의 기능을 담는 포괄적인 단어를 찾지못해 B방법으로 최종 마무리를 하게되었습니다.
토니라면 두 방법 중에 어떤 방법을 선택하실 것 같나요? 둘 다 아니라면 어떤 방향으로 코드를 작성하는게 좋을까요?

2022-04-29 15:31 UTC, Monsteel requested changes
안녕하세요 쿼카 두기~!
즐거운 금요일 저녁이네요.(뭔가 다 적고나면 토요일이 되어있을것 같지만요..ㅎ 😇)

Step1에 이어 Step2도 구현하시느라 수고 많으셨습니다 🙌

먼저 남겨주신 조언받고 싶은 내용에 대해 코멘트를 남겨볼게요.

### 1. 매직 리터럴 매직 넘버에 대한 고민
이번 Step에서 쿼카와 두기가 중점적으로 고민한 부분이 이부분이 아닐까 하는 느낌이 들었어요.
같은 의도로 쓰여진 질문도 있는것 같아서, 전체적인 의문에 대한 포괄적인 답변을 드릴 수 있도록 할게요.
혹시나 부족한 부분이 있으면 코멘트 부탁드립니다.

> 1이라는 값을 할당하는 방법과 Constant.numberOne로 할당하는 방법 중 어느게 가독성에 더 좋아보인다고 생각 하시나요 ?

`BankManager.swift:11` 코멘트와 겹치는 내용입니다.

numberOne을 상수로 선언해서 얻으려고 하신 장점이 어떤 부분이신지, 유지보수 측면에서 과연 어떤 이점이 있는지 고민해보시면 좋을것 같아요.

> 2. 아래와 같은 부분에서는 전자가 더 가독성이 좋다는 생각이듭니다.
추가로 프로퍼티가 중간에 껴있는데 이를 기점으로 매직넘버를 처리하는 상수를 만드려고도 했으나 naming에 여러의미를 담는게 더 가독성이 좋아질까 ? 라는 의문이듭니다.

우선, 이 부분에서도 Message의 일부를 상수로 선언하여 어떤 장점을 얻으려고 하셨나요?
그리고 그 장점이 가독성을 해친다는 단점을 상쇄할만큼 큰 효용의 가치가 있나요?

`프로퍼티가 중간에 껴있는데 이를 기점으로 매직넘버를 처리하는 상수를 만드려고도 했으나 naming에 여러의미를 담는게 더 가독성이 좋아질까 ?
` 이 부분에 대해서는 예시를 들어주시면 조금 더 도움이 되는 피드백을 드릴 수 있을것 같아요 🙌

> 3. 매직넘버로 enum을 생성해주었으나 하나의 매직넘버를 처리하기위해 enum이라는 타입을 만드는게 메모리관점에서 좋을지 ??에대한 의문이 듭니다.

우리는 enum으로 선언해서 해당 .swift파일에서 사용하는 상수들을 하나로 묶어 가독성이 더 좋게하고, 사용성을 더 좋게 만드는 등의 이점을 얻었습니다.

(`메모리관점에서`라는 말이 `성능`을 의미하시는거라면,) 
이런 이점을 포기할 만큼 enum 타입을 만드는데 있어, 성능적인 유의미한 수치는 나오지 않을것 같다는 생각이 듭니다.

추가로, static value를 많이 사용하는건 메모리 관리 관점에서 치명적일 수 있습니다.
관련해서 static value가 어떻게 작동하는지, 왜 치명적일 수 있는지 한번 찾아보면 좋을것 같아요.

너무 상수선언에 강박을 가지지 않으셔도 될 것 같아요. 오히려 가독을 해칠 수 있고 하드코딩했을 때 더 알아보기 쉽고 유지보수가 용이한 코드가 나올수도 있답니다 :)

### 2. 시간을 측정하는 코드들을 하나의 메서드 묶는 방법이 있을까요 ?
> A방법으로 하게되면 checkTime()이라는 메서드가 시간계산과 은행업무처리하는 기능을 둘다 포함하게 되는데 checkTime()이라는 메서드 명을 통해서는 sendCustomerToClerk()의 기능을 갖고있는지 아닌지 분간이 되지 않고, 메서드 네이밍에 두개의 기능을 담는 포괄적인 단어를 찾지못해 B방법으로 최종 마무리를 하게되었습니다.
토니라면 두 방법 중에 어떤 방법을 선택하실 것 같나요? 둘 다 아니라면 어떤 방향으로 코드를 작성하는게 좋을까요?

쿼카와 두기가 어떤 포인트에서 고민이 되시는지, 어떤 방향을 원하시는지 알 것 같군요.
상세하게 적어주셔서 감사합니다.

두가지를 적어주셨지만 뭔가 둘다 마음에 드시는 방법은 아니셔서 질문을 남겨주신것 같아서 새로운 방법을 제시해 드려 보겠습니다.

"시간을 측정하는 코드"를 아예 별도의 파일로 분리해서 "시간을 측정하는 기능"에 대해 관심사를 분리하는 방법도 있겠습니다. 예를들어,

```swift
class TimeCheckService {
  func start(
    ...
  ) {
    //Anything
  }
  
  private func checkTime(
    ...
  ) {
    //Anything
  }
}
```
정도로 힌트를 드려볼 수 있지 않을까 싶습니다.
코드의 구조가 조금 더 정돈될수도 있겠네요.

==

리뷰에 대해 몇가지 코멘트를 남겨봤습니다. 상수에 대한 리뷰는 필요에 따라 생락해 주시면 감사하겠습니다!

2022-04-29 15:31 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankManager.swift
> +        static let empty = ""
one, two, empty를 상수로 선언해서 얻으려고 하신 장점이 어떤 부분일까요?
개인적으로 이런 단일한 값은 상수로 빼서 얻을 수 있는 이점이 딱히 없다고 생각해서 그냥 하드코딩 할 것 같긴 합니다.

그리고 추가로 1,2,3,4,5 ... 숫자가 이렇게 늘어날 경우 모든 케이스에 대해 상수를 선언하는건 괜히 번거로운 작업이 되지는 않을까 염려되긴 합니다

2022-04-29 15:31 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Bank.swift
> +    private enum Constant {
enum을 사용해서 상수를 선언해 주신 부분 굉장히 좋습니다 🙌

2022-05-02 01:15 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Bank.swift
> +        static let totalWorkDoneCustomer = "오늘 업무를 처리한 고객은 총 "
이 부분과 아래 코멘트 달아주신 부분들은 메세지 전달함에 있어서 하드코딩을 하는 것이 더 가독성이 좋다고 판단하여 제거해주었습니다

2022-05-02 01:26 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankManager.swift
> +        static let empty = ""
저희도 그 부분이 염려되서 해당 부분은 하드코딩으로 사용하기로 했습니다!

2022-05-02 01:29 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +        static let endWork = "번 고객 업무 시작"
이 부분은 각각 workStartText 와 workEndText로 변경하였습니다!

2022-05-02 01:29 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Bank.swift
> +        while customerQueue.isEmpty == false {
지금까지 코드 작성할 때 앞에 !를 통해 부정을 하게 될 경우 가독성이 안좋아지는 경우가 많아 아무 생각없이 == false로 작성한 것 같습니다 근데 지금 해당 코드는 !를 통해 부정을 하는 것이 더 가독성이 좋아보여 수정하였습니다

2022-05-02 01:29 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Bank.swift
> +    mutating func start() {
저희도 조금 모호한 것 같아 openBank로 수정하였습니다!

2022-05-02 01:50 UTC, doogie97 commented
시간을 측정하는 코드를 별도의 파일로 분리해서 만든다고 했을 때 주신 힌트만으로는 저희가 어떻게 해야할 지 잘 생각이 나지 않아서 다른 방법을 시도해봤는데요

시간을 측정하는 기능을 말씀하신대로 다른 파일로 빼는 것이 아닌 메서드로 빼주었는데 그렇게 할 경우 아래와 같이 시간이 측정되지 않는 문제가 발생하였습니다
![image](https://user-images.githubusercontent.com/82325822/166174677-1a096221-8eff-438c-8fea-a5121ff2d979.png)
왜 시간이 측정이 되지 않는지 파악하기가 어려웠습니다
만약 시간측정에 대한 문제를 해결하게 된다면 이런 방식에 대해서 토니는 어떻게 생각하시나요?

2022-05-03 02:08 UTC, Monsteel commented
@doogie97 안녕하세요~ 답변이 늦어 죄송합니다 🙏

적용해주신 방법은, 두기가 남겨주셨던 포인트들
> A방법으로 하게되면 checkTime()이라는 메서드가 시간계산과 은행업무처리하는 기능을 둘다 포함하게 되는데 checkTime()이라는 메서드 명을 통해서는 sendCustomerToClerk()의 기능을 갖고있는지 아닌지 분간이 되지 않고, 메서드 네이밍에 두개의 기능을 담는 포괄적인 단어를 찾지못해 B방법으로 최종 마무리를 하게되었습니다.
토니라면 두 방법 중에 어떤 방법을 선택하실 것 같나요? 둘 다 아니라면 어떤 방향으로 코드를 작성하는게 좋을까요?

이 충분히 해결될 수 있어 보입니다! 👀 굉장히 신선한 접근이네요!

다만, function 이라는 네이밍 대신 조금 더 명확한 value였으면 좋겠다는 생각이 들긴 합니다!✍🏻

2022-05-03 07:02 UTC, Monsteel requested changes
코드에 대해 간단한 리뷰 남겼습니다~!
위에 답변드렸던 내용을 포함해서 확인하신후 다시 리뷰요청 부틱드립니다 🙏

2022-05-03 07:02 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +        static let workEndText = "번 고객 업무 시작"
이 부분은 `Constant`로 남겨놓으신 이유가 있을까요?

2022-05-03 07:02 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankManager.swift
> +        static let menu = "1 : 은행개점\n2 : 종료\n입력 : "
이 부분은 `Constant`로 남기셔서 얻으려고 하신 이점이 어떤것들이 있으신가요?! [하드코딩 vs 상수분리]
그리고, menu의 정보를 담고있는게 아닌, menu정볼르 표히시하는 message의 느낌이 강해 보입니다. 조금더 적절한 네이밍을 찾아보면 좋겠어요 ✍🏻

2022-05-03 07:02 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankManager.swift
> +            return selectMenu()
별도로 오류에 대한 안내 처리는 필요하지 않을까요? 👀

2022-05-03 08:13 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankManager.swift
> +            return selectMenu()
"잘못된 선택입니다." 라는 문구를 프린트 할 수 있도록 하였습니다!

2022-05-03 08:17 UTC, doogie97 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankClerk.swift
> +        static let workEndText = "번 고객 업무 시작"
사실 이 부분은 단순히 하드코딩 방지를 위해서 만든게 맞으나
STEP3 내용을 살펴봤을 때 두개의 업무로 나눠지는 것으로 확인했으며, 각각의 업무 메서드마다 static상수를 생성해 주는 것 보다 해당 메서드에 알맞는 메세지를 작성하는 것이 더 가독성이 좋고 불필요한 static상수를 생성하는 것을 방지할 수 있을 것이라고 생각해 메서드 내부로 이동하였습니다!

2022-05-03 08:24 UTC, Quokkaaa commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankManager.swift
> +        static let menu = "1 : 은행개점\n2 : 종료\n입력 : "
하드코딩을 방지하고 enum으로 상수분리를 해주면서 정돈된 느낌을 받을 수 있어서 이렇게 작성했습니다!

2022-05-03 09:03 UTC, doogie97 commented
<img width="613" alt="image" src="https://user-images.githubusercontent.com/82325822/166427508-400e0c13-8582-4863-8655-0d326d4943d4.png">

저희가 생각했던 클로저를 매개변수로 받을 때 위와같이 작성하면 문제가 없이 잘 작동이 됩니다

<img width="727" alt="image" src="https://user-images.githubusercontent.com/82325822/166427581-c22e1aa2-efbc-4df1-b6fc-4e6b79105435.png">

그런데 이렇게 하게 된다면 위와 같은 오류가 발생하게 되는데 아마 sendCustomerToClerk이 mutating함수라서 발생하는 오류라고 생각은 하나 해당 오류에 대해서 찾아봐도 마땅한 이유를 모르겠어서 여쭤보고 싶습니다

<img width="378" alt="image" src="https://user-images.githubusercontent.com/82325822/166427690-034b6866-c15a-4808-97c7-cd577826839e.png">

참고로 mutating이 아닌 함수는 잘 작성이 됩니다...🥲


일단 최종 커밋 형태는 아래와 같이 작성했습니다!
```swift
    mutating func openBank() {
        receiveCustomer()
        workingTime = timeCheck {
            sendCustomerToClerk()
        }
        printCloseMessage()
    }
```

2022-05-04 01:20 UTC, Monsteel approved these changes
남겨주신 코멘트에 대해서는 아래 두가지 질문에 대한 답변을 생각해 보시면 좋을것 같아요.

struct에서 mutating을 적어주는 이유가 무엇일까요?
() -> Void 타입으로 정의한 clouser에 mutating 함수는 왜 허락되지 않을까요?

단순히 해당 오류에 대한 정보를 찾아볼 수 있겠지만, 오류가 발생했을 때 유사 케이스를 찾아 해결하기 보다는 발생한 메세지가 무엇을 의미하고, 왜 발생하는지에 대해 탐구해보면 좋을것 같아요.

이번 케이스 같은 경우에는 많은 사람들이 경험하지 않았거나, 여러가지 케이스에서 발생하는 오류라 쿼카와 두기가 처해있는 상황과 fit한 case가 나오지 않았을 가능성이 있어 보입니다.

Step2 수고많으셨습니다~

2022-05-04 01:21 UTC, merged