은행 창구 매니저 [STEP3] Eddy, dudu
yagom-academy/ios-bank-manager pull request #163
Opened 2022-04-30 16:13 UTC by kimkyunghun3

안녕하세요 @TTOzzi  STEP3 PR보냅니다.
STEP2의 추가적인 수정사항과 STEP3 새로운 기능을 구현했습니다.

기본적인 부분(protocol extension으로 분리, 접근제어자, final 키워드)을 자꾸 놓치는것 같아 해당 부분에 신경을 더 써봤습니다

약간의 문제가 있습니다..
STEP2 수정사항도 STEP3 Branch에서 한다음 PR을 했어야 했는데, STEP2에서 작성하고, 새 기능들만 STEP3에서 작성해 버려서 리뷰하시기 불편할것 같아요.. ㅠㅠ 죄송합니다

잘부탁드립니다 :)

## 궁금한점

### STEP2 수정사항 관련

#### Delegate를 weak으로 선언하는 부분

프로토콜에 AnyObject를 채택해서 weak으로 선언할 수 있게 해줬습니다!

```swift
weak var delegate: BankDelegate?
```

수정하는 중에 의문이 하나 들었는데요!
weak을 쓰려면 무조건 프로토콜에 AnyObject를 채택해줘야 하는데 그러면 앞으로 구조체에는 해당 프로토콜 채택을 못하지 않나..? 라는 생각이 들었어요

다시 생각을 해봤는데, 어차피 UIKit에서는 대부분 Delegate의 주체들이 ViewController다 보니 상관없을것 같다는 생각이 들었습니다

#### bank 클로저 속 bank, bankWindow delegate 채택 

```swift
private lazy var bank: Bank = {
    var bankWindow = BankCommonWindow()
    bankWindow.delegate = self

    let bank = Bank(window: bankWindow)
    bank.delegate = self

    return bank
}()
```

BankManager에서 bankWindow 프로퍼티를 가진다는게 논리적으로 조금 이상하다고 판단했습니다.
하지만 이곳에서 delegate = self로 해줘야 하기 때문에 이를 bank 클로저를 활용해서 내부로 은닉했는데 이렇게 쓰면 괜찮을지 궁금합니다.

아니면 다른 방법을 사용해야 할지 궁금하네요!

### STEP3

#### 항상 weak self를 써도 될까요?

찾아본 결과, DispatchQueue.global().async 여기서는 weak self를 사용하지 않아도 순환참조 오류가 나지 않는다는것을 알았습니다.

항상 궁금했던게, 그냥 무조건 `[weak self]`를 쓰면 안되나요?
제 생각에는, 매번 escaping closure인지 확인하고, 메모리릭이 발생하는지 개발자가 확신할수가 있나? 라고 생각해서 그냥 `[weak self]`를 쓰면 안전한게 아닌가.. 라는 생각입니다

```swift
DispatchQueue.global().async(group: group) {
    switch customer.workType {
    case .loan:
        self.loanWindow.receive(customer)
        loanSemaphore.signal()
    case .deposit:
        self.depositWindow.receive(customer)
        depositSemaphore.signal()
    }
}
```

#### 세마포어 global Thread 로직 부분를 분리할 수 있을까?

switch가 두번 이루어 지는게 어쩔 수 없이 global thread만을 호출하기 위해서 필요한 로직인 것 같은데, 코드를 보았을 떄 깔끔해보이지 않는다는 느낌을 받았습니다.

그래서 이부분을 개선할 수 있을까 생각해보았지만 떠오르는게 없어서 혹시 이 부분을 개선해야 하는지 아니면 이렇게 사용할 수 밖에 없는지 궁금하네요!

```swift 
while !waitingQueue.isEmpty {
    guard let customer = waitingQueue.dequeue() else { return }

    switch customer.workType {
    case .loan:
        loanSemaphore.wait()
    case .deposit:
        depositSemaphore.wait()
    }

    DispatchQueue.global().async(group: group) {
        switch customer.workType {
        case .loan:
            self.loanWindow.receive(customer)
            loanSemaphore.signal()
        case .deposit:
            self.depositWindow.receive(customer)
            depositSemaphore.signal()
        }
    }

    handledCustomerCount += 1
}
```

#### 프로퍼티 사용 vs 클래스 내 메서드로 활용 vs extension 활용

이전코드

```swift
   private var businessHours: String {
        let difference = endTime - startTime
        let flooredDifference = floor(difference * 10) / 10
        return String(format: "%.2f", flooredDifference)
    }
```

이후코드

```swift 
fileprivate extension Double {
    var formattedTime: String {
        let difference = floor(self * 10) / 10
        return String(format: "%.2f", difference)
    }
}
```

이 프로퍼티를 extension를 활용해서 리팩토링을 했습니다.
하지만 드는 생각이 프로퍼티를 사용하는 것과 extension를 사용하는 것, 아니면 메서드로 만드는 것이 성능이나 다른 부분에 있어서 차이가 있는건지? 아니면 그냥 스타일/가독성 차이인지 궁금합니다.

예를 들어, 프로퍼티나 메서드 사용은 클래스 내에서 성능을 떨어트린다거나 아니면 가독성에서 extension보다 떨어진다거나 등의 이유로 바꾸는 것인지 궁금합니다!

2022-05-02 10:44 UTC, FirstDo commented
# 추가로 궁금한점

현재 코드는 문제가 있습니다.. ㅠㅠ
아래와 같은 dummy data로 테스트 했습니다

![](https://i.imgur.com/hfozHUE.png)

## DispatchQueue를 쓰는방법1

### 문제점: 결과가 제대로 나오지 않습니다

![](https://i.imgur.com/uV7mSWo.png)

0, 1, 9, 10 이 예금업무라서 대출업무와 무관하게 실행되어야 하는데,
0, 1이 수행되고 모든 대출업무가 끝난후 9, 10이 수행됩니다.. ㅠㅠ
main에서 semaphore.wait()을 해서 그런가, 결과가 생각대로 출력되지 않습니다

```swift
private func sendCustomerToClerk() {
        let group = DispatchGroup()
        let depositSemaphore = DispatchSemaphore(value: 2)
        let loanSemaphore = DispatchSemaphore(value: 1)

        while !waitingQueue.isEmpty {
            guard let customer = waitingQueue.dequeue() else { return }

            switch customer.workType {
            case .loan:
                loanSemaphore.wait()
            case .deposit:
                depositSemaphore.wait()
            }

            DispatchQueue.global().async(group: group) {
                switch customer.workType {
                case .loan:
                    self.loanWindow.receive(customer)
                    loanSemaphore.signal()
                case .deposit:
                    self.depositWindow.receive(customer)
                    depositSemaphore.signal()
                }
            }

            handledCustomerCount += 1
        }

        group.wait()
    }

```

## DispatchQueue를 쓰는방법2

### 문제점: Thread수가 고객 수 만큼 생성됩니다

![](https://i.imgur.com/DbnSGrV.png)

동작은 잘되는데, global큐에서 sema.wait()을 하다보니 
애초에 sema.wait()에 걸리기 전에 thread가 만들어져 버려서 Thread가 너무 많이 생성됩니다.. ㅠㅠ

```swift
    private func sendCustomerToClerk() {
        let group = DispatchGroup()
        let depositSemaphore = DispatchSemaphore(value: 2)
        let loanSemaphore = DispatchSemaphore(value: 1)

        while !waitingQueue.isEmpty {
            guard let customer = waitingQueue.dequeue() else { return }

            DispatchQueue.global().async(group: group) {
                switch customer.workType {
                case .loan:
                    loanSemaphore.wait()
                    self.loanWindow.receive(customer)
                    loanSemaphore.signal()
                case .deposit:
                    depositSemaphore.wait()
                    self.depositWindow.receive(customer)
                    depositSemaphore.signal()
                }
            }

            handledCustomerCount += 1
        }

        group.wait()
    }
```

## OperationQueue를 쓰는방법

그래서 정말 해결을 하려고 노력했는데, thread를 은행원수만큼 제한하면서 제대로 동작하게 하는게 생각이 안났습니다 ㅠㅠ

그래서 다음으로 든 생각이 OperationQueue와 maxConcurrentOperationCount 속성을 사용하면 최대 작업개수를 제한할 수 있으므로, 요구사항을 만족시킬 수 있을것 같았습니다. 

```swift
    private func sendCustomerToClerk() {
        
        let loanQueue = OperationQueue()
        let depositQueue = OperationQueue()
        
        while !waitingQueue.isEmpty {
            guard let customer = waitingQueue.dequeue() else { return }
            
            switch customer.workType {
            case .loan:
                loanQueue.addOperation {
                    self.loanWindow.receive(customer)
                }
            case .deposit:
                depositQueue.addOperation {
                    self.depositWindow.receive(customer)
                }
            }
            
            handledCustomerCount += 1
        }
    }
```


### 궁금한점

해결은 했는데, 기존 DispatchQueue 방식에서 Semaphore과 group을 이용해서 이 문제를 해결하는 방법이 있을까요?

2022-05-02 17:13 UTC, TTOzzi requested changes
안녕하세요 에디, 두두!
주말까지 빡세게 달리시는 모습에 놀고있다가 자극 많이 받았습니다 👍 
쉬엄쉬엄 하셔요 그러다 나중에 지칠수도 있어요..!

### Delegate를 weak으로 선언하는 부분

음.. 구조체를 `delegate` 로 할당하는 케이스가 있을까요?
구조체 인스턴스를 `delegate` 로 할당하는 순간 값이 복사되어 할당될텐데 이런 동작을 의도할 경우가 있을지 모르겠어요  :thinking:

### bank 클로저 속 bank, bankWindow delegate 채택

코멘트로 남겨뒀습니다!

### 항상 weak self를 써도 될까요?

순환참조를 떠나서 `weak` 로 캡처리스트를 만들어 넘겨준 클로저와 그렇지 않은 클로저는 동작에 어떤 차이가 있을까요?

클로저의 내부 로직이 캡처한 인스턴스가 없어졌을 때 동작하지 않아야 한다면 `weak`로 캡처하고, 클로저 내부 로직이 캡처한 인스턴스를 살려두면서 꼭 실행되어야 한다면 강하게 캡처해서 전달해야 할 것 같아요.
말씀하신 `addOperation`도 순환참조는 발생하지 않더라도, 강하게 캡처한 채로 `OperationQueue`를 일시정지 한다면 아마 그 작업이 완료될 때 까지 캡처한 `self`를 살려둘 것 같아요.
의도에 맞게 사용하면 될 것 같습니다.

클로저 사용으로 인한 순환참조는 특정 인스턴스를 캡처한 클로저를 그 인스턴스가 프로퍼티로 가질 때 발생하니 따로 생각해줘야 할 것 같구요.

만약 클로저를 사용할 때 `escaping closure`의 구분이 어렵고 언제 `weak`로 캡처해야할 지 판단하는 게 어렵다면, 컴파일러에게 맡기는 것도 하나의 방법이라고 생각해요.
Swift 5.3 이전엔 클로저 내부의 `self` 명시가 필수였지만, 5.3 버전부터 순환 참조가 발생할 가능성이 없는 코드에 대해선 `self`의 생략을 허용합니다.
https://github.com/apple/swift-evolution/blob/master/proposals/0269-implicit-self-explicit-capture.md
항상 `self`를 생략해서 코드를 작성하다가, 컴파일러가 알려주면 캡처하는 코드를 작성해주면 될 거예요 :slightly_smiling_face:

### 프로퍼티 사용 vs 클래스 내 메서드로 활용 vs extension 활용

음 개인적으론 범용적으로 사용되는 로직만 `extension` 으로 구현하는 것을 선호합니다만 이건 사람마다 의견이 다를 수 있을 것 같아요 :thinking:
누군가가 "이건 왜 `extension`으로 구현했나요?" 하고 질문했을 때, 이유만 설명할 수 있다면 어떻게 구현하던 상관없다고 생각합니다.

----

항상 말씀드렸듯이 이해안되는 부분이 있다면 말씀해주세요 🙏 
고생하셨습니다 🙇

2022-05-02 17:13 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
>          return customers
```suggestion
        let customerCount = Int.random(in: 10...30)
        let customers = (1...customerCount).map(makeCustomer)
        return customers
```
고차함수를 사용하면 이렇게도 표현할 수 있을 것 같아요.

2022-05-02 17:13 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
> +    var workType: Banking
`workType` 이 변경될 수도 있는 건가요? 👀

2022-05-02 17:13 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
> +    var workType: Banking { get }
`BankWindow`를 사용하는 곳에서 `BankWindow`가 `workType`을 가지고 있음을 알아야 하는 건가요?
`BankWindow` 프로토콜 구현의 목적이 `BankLoanWindow`, `BankDepositWindow`의 추상화라면, `BankWindow`를 사용하는 곳에서 필요로 하는 인터페이스만 노출되는 형태가 되어야 할 것 같아요.

2022-05-03 01:27 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            }
훨씬 더 깔끔하네요!
제안주신대로 바꿨습니다

2022-05-03 01:29 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
>          return customers
```swift
    static func randomCustomers() -> [Self] {
        let customerCount = Int.random(in: 10...30)
        let customers = (1...customerCount).map(makeCustomer)

        return customers
    }
```

제안주신대로 바꿨습니다!
훨씬 깔끔해졌네요 :)

2022-05-03 01:30 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
> +    var workType: Banking
이런실수를.. ㅠㅠ let으로 바꿔주었습니다
```swift
let workType: Banking
```

2022-05-03 01:34 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
> +    var workType: Banking { get }
목적이 추상화가 맞고, 그래서 BankWindow라는 프로토콜은 receive라는 동작과, workType이라는 프로퍼티를 가져야 한다고 생각했습니다.
근데 지금보니 실제로 쓰질 않네요.. ㅠㅠ

꼭 필요로 하는 인터페이스만 노출되도록 더 신경쓰겠습니다
pop와 추상화가 너무 어렵네요.. ㅠㅠ 처음 해보는거라서

2022-05-03 01:40 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankCustomer.swift
> +}
Banking으로 분리해줬습니다!!

2022-05-03 03:22 UTC, kimkyunghun3 commented on BankManager.swift
>          bank.delegate = self
```swift
// BankWindow
protocol BankWindow: AnyObject {
    func receive(_ customer: Customer)
    var delegate: BankWindowDelegate? { get set }
}

protocol BankWindowDelegate: AnyObject {
    func customerWorkDidStart(_ bankWindow: BankWindow, customer: Customer)
    func customerWorkDidFinish(_ bankWindow: BankWindow, customer: Customer)
}

// Bank
extension Bank: BankWindowDelegate {
    func customerWorkDidStart(_ bankWindow: BankWindow, customer: Customer) {
        delegate?.customerWorkDidStart(self, waitingNumber: customer.waitingNumber, workType: customer.workType)
    }

    func customerWorkDidFinish(_ bankWindow: BankWindow, customer: Customer) {
        delegate?.customerWorkDidFinish(self, waitingNumber: customer.waitingNumber, workType: customer.workType)
    }
}

// BankManager
extension BankManager: BankDelegate {
    func customerWorkDidStart(_ bank: Bank, waitingNumber: Int, workType: Banking) {
        print("\(waitingNumber)번 고객 \(workType.name)업무 시작")
    }
    
    func customerWorkDidFinish(_ bank: Bank, waitingNumber: Int, workType: Banking) {
        print("\(waitingNumber)번 고객 \(workType.name)업무 완료")
    }
    
    func bankWorkDidFinish(_ bank: Bank) {
        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(bank.customerCount)명이며, 총 업무 시간은 \(bank.duration.formattedTime)초입니다.")
    }
}

```
요렇게 이벤트 전달이 되도록 구현했습니다!

2022-05-03 03:23 UTC, FirstDo commented on BankManager.swift
> +    }
BankDelegate를 UIScrollView를 참고하여 다음과 같이 바꿔주었습니다.
첫번째 인자: 위임하는 객체로 변경

그리고 기존 customer를 넘겨주어서 BankManger와 Customer의 의존성이 생겼는데, 출력에 필요한 정보인 waitingNumber, workType만을 넘겨주도록 변경하였습니다

```swift
    func bankWorkDidFinish(_ bank: Bank)
    func customerWorkDidStart(_ bank: Bank, waitingNumber: Int, workType: Banking)
    func customerWorkDidFinish(_ bank: Bank, waitingNumber: Int, workType: Banking)
```

2022-05-03 03:28 UTC, kimkyunghun3 commented on BankManager.swift
> +    func bankWorkDidFinish(count : Int, hour: String) {
해당 delegate를 채택해서 사용하는 입장에서 생각해보면, 첫번째 인자로 위임하는 주체를 넘긴다면 훨씬 더 다양하고 유연한 구현을 할 수 있기 때문이라고 생각했습니다

ex)
```swift
func bankWorkDidFinish(_ bank: Bank) {
    //bank에 접근해서 뭐든지 할 수 있음..!!
}
```

2022-05-03 05:05 UTC, kimkyunghun3 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        depositQueue.waitUntilAllOperationsAreFinished()
저희가 이해한 바로는 차단하지 않고 wait 시키는 경우에는 괜찮다고 생각했습니다.

2022-05-03 14:28 UTC, TTOzzi commented on BankManager.swift
> +    private lazy var bank: Bank = {
아하 이해했습니다! 
말씀하신 내용도 lazy를 사용하는 이유가 될 수 있긴 하지만,  lazy 하게 생성하는 것은 다중 스레드에서 동시에 접근했을 때 2개 이상의 인스턴스가 만들어지는 상황이 생길 수도 있어요.
생성에 비용이 많이 든다거나 하는 이유로 늦게 생성되어야 하는게 아닌, 단순 `self` 할당을 위해서라면 생성자 내부에서 해줘도 될 것 같습니다 🙂

2022-05-03 14:37 UTC, TTOzzi commented on BankManager.swift
> +    func bankWorkDidFinish(count : Int, hour: String) {
구현에 정답은 없지만, 주로 한 객체가 여러 객체의 동작을 위임받았을 때 누가 호출했는지 구분하기 위해 사용했던 것 같아요 🤔 
예를들면.. 뷰컨 하나에 UITextField가 여러 개 있고, 그 UITextField들의 delegate 로 뷰컨이 할당된 상황이 있을 수 있겠네요.

2022-05-03 14:38 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            }
오해하실까봐..! 이런 방법도 있다는 것을 알려드리기 위함이지 무조건 변경하라는 코멘트는 아니었어요!

2022-05-03 14:46 UTC, TTOzzi approved these changes
리뷰 이후 수정사항도 커밋을 잘 나눠주셔서 보기 편하네요 😊
디엠으로 말씀드린대로 메인스레드를 잡고 있는 부분은 다음 스텝에서 해결해보아요.
그럼 머지할게요! 고생하셨습니다~! 🙇

2022-05-03 14:46 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
> +class BankLoanWindow: BankWindow {
`final`은 습관적으로 붙여주는 게 좋아요! 👮‍♂️

2022-05-03 14:46 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
>      let workType: Banking = .loan
프로토콜에서 `workType`이 없어졌으니 이 친구도 `private`으로 숨길 수 있겠네요! 👮

2022-05-03 14:46 UTC, merged

2022-05-03 15:08 UTC, FirstDo commented on BankManager.swift
> +    private lazy var bank: Bank = {
lazy가 그런문제가 있는지 처음알았습니다..!
주의해야겠네요..!

2022-05-03 15:11 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
> +class BankLoanWindow: BankWindow {
왜 계속 까먹는건지 모르겠어요.. ㅠㅠ
class만 보면 무조건 final을 붙이는 습관을 가지도록 해야겠습니다..!!!!

2022-05-03 15:12 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
>      let workType: Banking = .loan
처음 설계는 그래도 나름(?) 괜찮았던것 같은데, 
중간중간 변경사항이 있을때 그거에 맞춰서 다시 접근제어자라던가 final이라던가 붙여주는걸 저희가 잘 못하네요.. 
신경쓰겠습니다!!

2022-05-03 15:28 UTC, TTOzzi commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
>      let workType: Banking = .loan
ㅋㅋㅋ 지금도 충분히 잘 하고 계십니다 👍

2022-05-04 07:10 UTC, FirstDo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankWindow.swift
>      let workType: Banking = .loan
private 붙여주었습니다..!!