은행 창구 매니저 [STEP2] Lingo, Cathy
yagom-academy/ios-bank-manager pull request #164
Opened 2022-05-01 06:58 UTC by llingo

@stevenkim18 
안녕하세요 스티븐! STEP 2 PR 보냅니다. 
잘부탁드립니다 🙇🏻

## UML
<img width="600px" src="https://i.imgur.com/qF1W2p2.png"/>

---

### 고민 및 해결한 점

**BankManager, Bank의 Client를 생성하는 역할과 책임에 대하여**
Client를 생성해주는 역할을 BankManager와 Bank 중 어디에 부여할지 고민을 하였고 BankManager에 부여하기로 하였습니다. 

**BankManager에서 재귀함수를 사용하지 않고 재시작을 하는 것에 대해**
기존에는 BankManager의 start 메서드의 `재시작`을 구현하기 위해 재귀함수를 사용했었습니다. 재귀함수는 호출될때마다 스택에 계속 쌓게되어 스택오버플로우 가능성이 있다고 생각했고 이를 해결하기 위해 다음과 같은 방법을 고민했습니다.

1. 꼬리 재귀 최적화 방법
2. 반복문을 사용하여 종료하는 사용자 입력이 올때 반복문을 탈출하는 방법

![](https://i.imgur.com/6O2DhCB.png)

`꼬리 재귀 최적화`는 Swift 컴파일러가 제공하는 최적화이며 메서드가 불릴때마다 스택에 쌓는 것을 방지할 수 있었습니다. 하지만, DEBUG 모드에서는 최적화 설정이 되어있지 않기 때문에 사용하지 않기로 결정했고 반복문을 통한 `재시작`을 할 수 있도록 구현했습니다.

**매직리터럴을 방지하기 위한 네임스페이스 설정에 대하여**
코드의 유지보수와 가독성을 높이기 위해 각 파일에서 `Constants` `Message` `Menu` 열거형을 사용하여 매직 넘버와 매직리터럴을 제거해주었습니다.

**네이밍**
각 메서드가 하고있는 역할에 맞게 메서드 네이밍을 수정하였습니다.

```swift
// 예시)
execute -> executeBankTask
close -> displayCloseMessage
```

### 조언 받고 싶은 점

**타입 간의 의존성 사이클에 대하여**
타입 간의 의존성 사이클이 발생하면 A가 변경될때 (A->B->C)로 영향을 끼치기 때문에 좋지 못한 설계라고 들었던 적이 있는데 아래와 같이 `Bank -> Client, Bank -> BankTask -> Client`와 같은 경우는 사이클이 생기지 않기 때문에 괜찮은 설계인지 더 개선해야하는 설계인지 궁금합니다!

<img width="600px" src="https://i.imgur.com/xfR0TXj.png"/>

**재시작을 구현하기 위해 반복문을 사용한 것에 대하여**
반복문을 통해 재시작을 구현하면서 생긴 이중 들여쓰기를 제거하기 위해 아래의 코드처럼 start 메서드를 구현했습니다. while문의 `{}`안이 비어있게 되어 보기 좋지 않은 것 같은데 더 좋은 방법이 있을지 궁금합니다.
```swift
func start() {
  while selectMenu() {}
}

private func selectMenu() -> Bool {
  displayMenu()
  guard let input = readLine(),
        let menu = Menu(rawValue: input)
  else { return true }

  switch menu {
  case .open:
    let bank = Bank(limit: Constants.limit)
    createClients().forEach { bank.addClient($0) }
    bank.open()
    return true
  case .exit:
    return false
  }
}
```

2022-05-02 15:39 UTC, stevenkim18 requested changes

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  private var totalExecuteTime: Double = .zero
`private var totalClientCount = 0` 이렇게 쓰면 더 짧게 사용할 수 있어요!
저는 짧게 쓸 수 있다면 타입을 추론하게 사용합니다!

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  }
limit 보다는 은행원 명수를 뜻하는 네이밍이 더 좋지 않을까요?

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    while !clientQueue.isEmpty, let client = clientQueue.dequeue() {
`!`를 사용하면 가독성이 떨어져 보입니다. `clientQueue.isEmpty == false` 는 어떠신가요?

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  }
프린트만 하는 역할을 함수하나가 차지해버리니 좀 아까운 것 같습니다.

다른 곳에서는 바로 print 함수를 사용하셨는데 여기에는 따로 타입 메소드로 만드신 이유가 있을까요?

더 좋은 방법은 없을까요?

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    else { return true }
```swift
guard let input = readLine(),
      let menu = Menu(rawValue: input) else { return true }
```
저는 이게 더 좋은 것 같은데 어떻게 생각하세요? ㅎㅎ

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +      createClients().forEach { bank.addClient($0) }
배열을 돌면서 한명씩 client를 추가하는 것이 아니라 배열을 통째로 bank에 넣어줄 수도 있지 않을까요?

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    }
`waitingNumber`가 중복되는데 어떻게 하면 줄일 수 있을까요?

2022-05-02 15:39 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankTask.swift
> +  }
`execute` 함수 왜 더블을 리턴하나여? 

실제 소요되는 시간이 아닌 0.7을 곱해서 출력하는 이유가 있을까요?

2022-05-03 01:24 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  private var totalExecuteTime: Double = .zero
0을 직접 쓰게되면 매직넘버 사용하기 때문에 하드코딩 되어있다고 생각했고 저희는 그것을 방지하기 위해 매직넘버를 제거하였습니다.
혹시, 0을 직접 쓰는 것은 하드코딩에 해당하지 않는 건지 궁금합니다 🙇🏻

2022-05-03 01:28 UTC, cathy171 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  }
최대 고객 수를 의미하는 `maxClient`로 네이밍을 더 명확하게 수정하였습니다.

2022-05-03 01:30 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    while !clientQueue.isEmpty, let client = clientQueue.dequeue() {
말씀하신대로 가독성을 높이기 위해 `clientQueue.isEmpty == false`로 변경했습니다.

2022-05-03 01:38 UTC, cathy171 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +  }
네 말씀해주신대로 print 출력만 하는 메서드를 제거하였습니다!

2022-05-03 01:45 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    else { return true }
이번 프로젝트의 코딩 컨벤션 룰에서 [스타일 쉐어 가이드](https://github.com/StyleShare/swift-style-guide#%EC%A4%84%EB%B0%94%EA%BF%88) 를 채택했기 때문에 해당 문서에서 정의한 `guard else` 표현법으로 작성했었습니다.
<img width="700px" src="https://user-images.githubusercontent.com/94151993/166393198-50dab740-59f0-412a-b7b3-d28e44cee86d.png"/>

이번 프로젝트에서는 스티븐이 추천해주신 방법으로 수정해보았습니다!
```swift
guard let input = readLine(),
      let menu = Menu(rawValue: input) else { return true }
```

2022-05-03 01:54 UTC, cathy171 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +      createClients().forEach { bank.addClient($0) }
client를 한명씩 추가하는 것에서 client 배열을 넣어주는 것으로 변경하였습니다.

2022-05-03 02:01 UTC, llingo commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    }
1. Client 타입에서 멤버와이즈 생성자를 사용하지 않고 지정 생성자를 하는 방법
2. BankManager에서 중복되던 waitingNumber 변수명을 변경하는 방법

이 있었고 저희는 멤버 와이즈 생성자를 유지하는 방향으로 2번 방법을 채택하여 수정했습니다!

```swift
for number in 1...Int.random(in: Constants.range) {
  let client = Client(waitingNumber: number)
  clients.append(client)
}
```

2022-05-03 02:15 UTC, cathy171 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankTask.swift
> +  }
- BankTask에서 시간을 측정하도록 했고 Bank에서 사용하기 때문에 Double을 리턴해주었습니다.
- STEP3에서는 비동기를 사용하여 처리하기 때문에 실제 소요되는 시간을 계산해줄 필요가 있어보이지만 STEP2에서는 비동기를 사용하지 않기 때문에 0.7을 더해주었습니다.

STEP3에서는 직접 시간을 측정하도록 변경할 예정입니다.🙇

2022-05-04 04:30 UTC, stevenkim18 commented
구두로 리뷰 드렀습니다!!!

머지하겠습니다!

2022-05-04 04:30 UTC, merged