은행 창구 매니저 [STEP3] 파프리, 마이노
yagom-academy/ios-bank-manager pull request #166
Opened 2022-05-02 13:56 UTC by Mino777

# 은행 창구 매니저 [STEP3]
@Monsteel 
안녕하세요 토니!!!!
STEP3 구현 완료하여 PR 요청 드립니다!!!
잘 부탁드립니다!!!🙇‍♂️

---

## 구현내용
- BankService: 은행 업무와 관련된 Enum
- 업무에 따른 고객 큐 분리
- 업무에 따른 은행원 업무 할당
- 비동기 처리

---

## UML
![](https://i.imgur.com/omd7L1K.png)

---

## 실행화면
![](https://i.imgur.com/CGOX2dN.gif)

---

## 고민한 점 및 질문

### 1. UML
- 이전 스텝에서 조언해주신걸 토대로 Constants를 재구성 해보았습니다. 토니가 말씀해주신 부분이 맞을까요?!

### 2. 확장성
이번 프로젝트에서는
고객(`Client`)의 은행업무(`BankService`)에 따라
해당 업무를 담당하는 은행원(`BankClerk`)이 해당 고객의 업무를 처리 할 수 있어야 했습니다.
이를 위해`Bank` 의 프로퍼티로
`private let depositClientQueue = Queue<Client>()`
`private let loanClientQueue = Queue<Client>()`
를 두었습니다.

추후에 은행업무가 다양해지거나, 은행원이 담당할 수 있는 업무가 하나 이상이 되는 경우 새롭게 Bank에 해당 업무를 보기위한 고객들의 큐를 프로퍼티로 두어야하고, 코드 안에서 수정해야하는 부분이 많음을 느꼈습니다.
좀 더 확장이 유연하게 될 수 있도록 수정하고 싶은데, 이를 위해 공부할만한 키워드를 던져주실 수 있으실까요?!

### 3. Data Race

* Xcode의 기본 기능인 Thread Sanitizer을 통해 Data Race가 발생하는지 확인하였습니다.
![](https://i.imgur.com/RsHWKYQ.png)

위의 이미지와 같은 Threading Issue를 확인 할 수 있었습니다.
- 해당 부분을 해결하기 위해 linkedList의 removeFirst() 메서드에서 Serial Queue와 flags 파라미터의 값을 barrier로 시도를 해보았지만 해결하지 못하였습니다.

### 4. 은행원 수 == Thread의 수
- 은행원 수 만큼만의 Thread를 생성하기 위해 은행원 배열만큼을 for문을 돌려 해당 횟수 만큼만 global().async를 통해 thread를 생성하도록 하였습니다.

감사합니다!!!

2022-05-03 07:48 UTC, Monsteel requested changes
안녕하세요 파프리 마이노~! 빠르게 리뷰드리지 못해 죄송합니다! 🙏

남겨주신 코드는 잘 확인했고, 간단한 코멘트 몇개만 남겼습니다! 아주 잘 해주고 계세요.
그럼, 남겨주신 질문에 대해서 제 생각을 말씀드려볼게요!

> 이전 스텝에서 조언해주신걸 토대로 Constants를 재구성 해보았습니다. 토니가 말씀해주신 부분이 맞을까요?!

네.

>추후에 은행업무가 다양해지거나, 은행원이 담당할 수 있는 업무가 하나 이상이 되는 경우 새롭게 Bank에 해당 업무를 보기위한 고객들의 큐를 프로퍼티로 두어야하고, 코드 안에서 수정해야하는 부분이 많음을 느꼈습니다.
좀 더 확장이 유연하게 될 수 있도록 수정하고 싶은데, 이를 위해 공부할만한 키워드를 던져주실 수 있으실까요?!

음 이 부분에 대해서 특정 키워드를 중심으로 공부해서 해결할 수 있는건 아닌것 같아요.
구조에 대한 내용이라, 파프리와 마이노가 지금까지 배우신 내용을 활용해서 해당 내용에 대해서 충분히 고민해 보시면서, 두분이 느끼신 포인트를 해결해 보실 수 있을것 같아요!

일단, dictionary, enum, array 같은 것들로.. 뭔가 잘 하면 확장성을 높이는 구조를 설계해볼 수 있을것 같긴 한데, 위 키워드에 한정되지 마시고 여러 방면으로 설계에 대해 고민해 보시면 좋을것 같아요!

> 위의 이미지와 같은 Threading Issue를 확인 할 수 있었습니다.

간단하게 말하면, 현재 dataRace오류는 같은 queue를 여러 쓰레드에서 사용하고 있어서 발생하고 있는 문제인것 같아요. `Bank.swift:83` 라인에 브레이크 포인트를 찍고 실행해 보시면서, queue에 하나의 쓰레드가 접근하는지, 여러 쓰레드가 접근하고 있는지를 파악해보시면, 해당 문제를 해결하시는데에 도음이 될 것 같아요.

해당 문제에 대해 조금 더 고민을 해보셨으면 하는 마음으로 조심스럽게 코멘트를 남겼는데, 원인을 찾으시는데에 도움이 되셨는지 모르겠습니다. 일단 한번 보시고, 그래도 이해가 잘 안되시면 저에게 말씀해주세요. 조금 더 자세하게 설명드릴 수 있도록 하겠습니다~!

> 은행원 수 만큼만의 Thread를 생성하기 위해 은행원 배열만큼을 for문을 돌려 해당 횟수 만큼만 global().async를 통해 thread를 생성하도록 하였습니다.

이 부분에 대해서는 위에 남긴 dataRace 오류의 원인을 파악해보시면... 이 부분에 대해 추가적으로 뭔가 말씀하실 내용이 생기실수도 있을것 같군요 😇

2022-05-03 07:48 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankService.swift
> +enum BankService: CaseIterable {
BankService의 종류들을 나타낸 enum 인것 같은데, BankServiceType 처럼 조금 더 명확한 네이밍으로 수정하면 어떨까요? ✍🏻

2022-05-03 07:48 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankService.swift
> +extension BankService: CustomStringConvertible {
같은 파일 내에 extension으로 분리한 것 좋습니다 💯

2022-05-03 07:48 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        self.service = service
코드 내에서 BankService 타입의 변수이름이 service / bankService 두가지로 혼용되어 사용되고 있습니다. 
하나로 일원화하는건 어떨까요? 🙋🏻‍♂️

2022-05-03 07:48 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankService.swift
> +extension BankService: CustomStringConvertible {
`CustomStringConvertible` 좋네요!

2022-05-03 12:28 UTC, Mino777 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        self.service = service
bankService로 일원화 했습니다!
감사합니다!!

2022-05-03 12:28 UTC, papriOS commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankService.swift
> +enum BankService: CaseIterable {
네! BankServiceType으로 수정했습니다!

2022-05-03 14:44 UTC, Mino777 commented
@Monsteel 

토니!! 피드백 반영 해보았습니다!
좋은 리뷰 매번 너무 감사드립니닷😆

---

*1. Data Race*
- LinkedList의 removeFirst() 메서드에서 head를 write하는 과정에서 Data Race가 계속해서 발생하는 것을 확인했습니다.
- Data Race를 해결하기 위해선 해당 부분이 Thread-Safe를 보장해야 된다고 생각했습니다.
- 따라서 해당 부분을 SerialQueue를 활용해 리팩토링 하였습니다.

```swift
private let lockQueue = DispatchQueue(label: "lockQueue")

...

func removeFirst() -> Element? {
        var element: Element?
        
        lockQueue.sync {
            guard let removedNode = head else {
                return
            }
            head = removedNode.next
            element = removedNode.element
        }
        
        return element
    }
```

*2. BankServiceType의 변화에 대한 대처*
`Bank` 의 프로퍼티로 BankServiceType에 해당하는 Queue를 각각 가지고 있어야했습니다. 이에 대한 대처로 Dictionary 자료구조를 이용해 BankServiceType의 확장에 동적으로 대응이 가능하도록 수정했습니다. 

```swift
//main.swift

private func createQueueDictionary() -> QueueDictionary {
    var queueDictionary: QueueDictionary = [:]
    
    BankServiceType.allCases.forEach { bankService in
        queueDictionary.updateValue(Queue<Client>(), forKey: bankService.description)
    }
    
    return queueDictionary
}
```

2022-05-04 07:28 UTC, Monsteel approved these changes
수고하셨어요~~ 파프리 마이노~!~! 🚀🚀

2022-05-04 07:28 UTC, merged