은행 창구 매니저 [STEP3] Taeangel, Tiana
yagom-academy/ios-bank-manager pull request #170
Opened 2022-05-04 07:31 UTC by Kim-TaeHyun-A

안녕하세요 엘림 @lina0322  STEP3 PR보냅니다.🙇🏻🙇‍♀️

---

### 고민한 점
1. BankClerk
* step2에서 배열로 정의했던 은행 직원을 쓰레드로 변경했습니다.
* 세마포어(S = S-1 ⇒ S를 0로 만들어 다른 프로세스가 들어 오지 못하도록 함 -> 내부 수행이 끝나면 S를 증가시킴)를 사용해서 비동기 스레드를 돌리는 스레드의 개수를 제어하려고 했습니다.

2. notify vs wait
* notify를 사용하여 스레드가 다끝나기를 기다렸다 원하는 작업을 실행 하려 하였으나 notify은 스레드 작업이 끝날때까지 기다리는 것이 아니라 스레드 작업이 끝났다고 알려주는 기능이였습니다. 그래서 wait를 사용하여 원하는 작업이 끝날때까지 기다려서 문제를 해결하였습니다.

3. 스레드 중간에 return이 있는 경우의 문제점
- 만약 semaphore.wait(), semaphore.signal() 중간에(쓰레드 중간에) return이 있으면 영업 시간이 부족하게 나옵니다.
    
* return 이후 명령어 수행하지 않고 실행 중이던 모든 모든 스레드가 바로 반환 → 진행 중이던 스레드도 아래 명령어 수행 않고 같이 종료되는 듯 → defer{ } 안에 넣으면 수행하는 것으로 보임(이유: 메서드 종료 직전에 꼭 수행하는 부분)
    
4. 타입 역할 구분
* bankmanager와 bank의 기능을 명확히 구별하기가 애매하였습니다. 그래서 
bank의 운영과 가이드와 같은 기능을 bankmanager로 분리했고 은행업무와 같은 기능은 bank로 분리하였습니다.

5. Measureable 프로토콜
* 시간 측정하는 메서드를 프로토콜의 extension에 정의했습니다.

2022-05-05 15:26 UTC, lina0322 requested changes
여러분, 안녕하세요~ step3까지 오시느라 고생하셨습니다!🎉

코드를 살펴보니 여러분이 각각의 은행 직원을 만든게 아니라, 
clerks라는 은행원집단(??)을 만들어서
거기서 세마포어 총 벨류 3으로 돌아가고 있는 형태더군요.
저는 큐 하나를 하나의 사람으로 봐야하지 않을까? 하는 생각이 있었는데 새로운 관점이라 좋았습니다!

시간이 되신다면, 제가 생각했던 것 처럼
직원 한명이 하나의 queue를 가지고, 은행 매니저가 직원들에게 분배해주는 방식도 해보시면 좋을 것 같아요~
지금과 다른점이 많아서 더 많은 공부를 할 수 있게 될겁니다!!

또, 요구사항이 다소 명확하지 않긴 하지만 아예 대출을 한명이 전담하는 거라면, 
지금처럼 하나의 창구(queue)에 모든 손님들이 가는건 다소 어색함이 있을 것 같아요!
차라리 예금 queue, 대출 queue가 있는 것도 좋은 방법일 것 같고요.

---

고민하셨던 부분중에 notify관련해서는 notify랑 wait를 비교하는 것 보다 notify vs wait/signal을 함께 비교해보시면 좋을 것 같고요!!
스레드 작업이 다 끝나면 notify에서 원하는 작업을 하시면 되는데, 작성해주신 내용이 잘 이해가 안가네요ㅎㅎ... 예를들어 지금 모든 업무가 끝났을때, 문구 출력하는 것에 활용할 수 있지 않을까 하는 생각이 듭니다!!

그리고 Measureable을 분리해서 프로토콜을 사용해보신건 아주 좋았는데요!!👍
사실 은행만 사용할 기능인데 굳이 분리했어야하나? 라는 생각도 들어요~😅

---

쭉 보시고 궁금한거나 이해안가시는 부분 있으면 또 말씀해주세요!!🙇🏻‍♀️

2022-05-05 23:06 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var totalClients: Int {
```swift
 private var totalClientsCount: Int {
        return Int.random(in: ClientCount.minimum.rawValue...ClientCount.maximum.rawValue)
    }
```
로 변경하였습니다.

2022-05-05 23:33 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    static let loan = DispatchSemaphore(value: ClerkCount.loan)
이전 스탭에서도 enum으로 직원을 구현했어서 굳이 바꾸지 않았습니다.
enum의 경우 case가 없으면 인스턴스를 생성하기 어렵다고 알고 있습니다.

네이밍의 경우 clerks라는 단어를 추가해서 직원들이라는 것을 표현하도록 수정했습니다

2022-05-05 23:34 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var totalClients: Int {
조언해주신대로 수정했습니다

2022-05-05 23:43 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        let semaphore = client.task.clerk
clerks 대신 bankWindows로 네이밍을 변경했습니다.

2022-05-05 23:43 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +private enum ClerkCount {
SemaphoreValue로 네이밍 변경했습니다.

2022-05-05 23:43 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        let semaphore = client.task.clerk
```swift
 static let bankWindows = DispatchQueue(label: "bankWindows", attributes: .concurrent)
```
으로변경하였습니다

2022-05-05 23:45 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        guideBank()
bank manager가 start하기보다는 openBank로 은행시작을 알리고 
printDescription보다는 guideBank으로 손님을 안내하는게 자연스럽다고 생각하여 변경하였습니다.

2022-05-05 23:52 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Task.swift
> +    case loan = "대출"
```swift 
private enum Guide: String {
    case menu = """
    1 : 은행 개점
    2 : 종료
    """
    case input = "입력: "
    case error = "잘못 눌렀습니다."
    
    static func closeDescription(totalDuration: Double, clientCount: Int) {
        print("""
              업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(clientCount)명이며, \
              총 업무시간은 \(totalDuration.formatSecondDecimal)초입니다.
              """)
    }
}

```
Guide 열거형에 넣어주었습니다.

2022-05-05 23:52 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +              """)
```swift 
private enum Guide: String {
    case menu = """
    1 : 은행 개점
    2 : 종료
    """
    case input = "입력: "
    case error = "잘못 눌렀습니다."
    
    static func closeDescription(totalDuration: Double, clientCount: Int) {
        print("""
              업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(clientCount)명이며, \
              총 업무시간은 \(totalDuration.formatSecondDecimal)초입니다.
              """)
    }
}

```
Guide 열거형에 넣어주었습니다.

2022-05-06 00:21 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Task.swift
> +    var clerk: DispatchSemaphore {
[d643c99](https://github.com/yagom-academy/ios-bank-manager/pull/170/commits/d643c99740d732dce0451c698338d26edcb85684)

Task에 어울리지 않는 프로퍼티를 제거하고 BankClerk에서 메서드를 통해 client의 업무에 맞는 세마포어를 찾는 식으로 변경했습니다.

2022-05-06 00:25 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Task.swift
> +    case loan = "대출"
여기는 task를 구분하는 case이고 BankClerk에 있는 것은 semaphore를 구분하는 것이라 역할이 다르다고 생각됩니다.

2022-05-06 00:27 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Utils/Protocol/Measurable.swift
> +    func measureTime(of task: () -> Void) -> Double {
extension으로 기본 구현을 제공해서 프로토콜에서 구현하기를 요구하는 사항들이 없기 때문에 빈 프로토콜을 만들게 되었습니다.
빈 곳에 줄바꿈이 있다면 주석으로 empty라고 표기할 수도 있을 것 같습니다.

2022-05-06 00:30 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            workGroup.wait()
조언해주신대로 수정했습니다.

2022-05-06 00:57 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
>      }
스탭 2에서 Queue를 내부에서 만들었다가 외부 주입 받도록 수정했습니다. 이번에 다시 보니 안에서 은행에서 큐를 가지고 있는 것이 자연스러워보입니다. client는 bank에 있을 때만 그 역할이 의미있다고 생각되어서 client를 안애서 생성합니다.

2022-05-06 03:42 UTC, Kim-TaeHyun-A commented
안녕하세요 엘림 @lina0322 
피드백 감사드립니다.
답변 달았는데 확인 부탁드립니다.😆


```
시간이 되신다면, 제가 생각했던 것 처럼
직원 한명이 하나의 queue를 가지고, 은행 매니저가 직원들에게 분배해주는 방식도 해보시면 좋을 것 같아요~
지금과 다른점이 많아서 더 많은 공부를 할 수 있게 될겁니다!!

또, 요구사항이 다소 명확하지 않긴 하지만 아예 대출을 한명이 전담하는 거라면,
지금처럼 하나의 창구(queue)에 모든 손님들이 가는건 다소 어색함이 있을 것 같아요!
차라리 예금 queue, 대출 queue가 있는 것도 좋은 방법일 것 같고요.
```

9e34b4d373e6a149ef80010a7423ae2f257d517c

위에서 조언해주신 방식으로 리팩토링을 하였는데 엘림이 의도하신 방향이 맞을까요?

```
고민하셨던 부분중에 notify관련해서는 notify랑 wait를 비교하는 것 보다 notify vs wait/signal을 함께 비교해보시면 좋을 것 같고요!!
스레드 작업이 다 끝나면 notify에서 원하는 작업을 하시면 되는데, 작성해주신 내용이 잘 이해가 안가네요ㅎㅎ... 예를들어 지금 모든 업무가 끝났을때, 문구 출력하는 것에 활용할 수 있지 않을까 하는 생각이 듭니다!!
```
notify의 command line tool에서 사용하면 제대로 동작하지 않는 것 같아서 notify와 wait의 차이에 대해 고민했다고 작성했던 거 였습니다.

notify와 wait/signal을 비교하면 notify는 그룹이 끝나기를 기다렸다가 대기 중이던 비동기 그룹들이 다 끝나면 원하는 작업을 수행합니다.(notify 대신에 group.wait()을 작성하고 다음 명령어로 원하는 작업을 작성해도 되는 것을 알고 있습니다.) wait/signal의 경우 value를 변경하여 접근 가능한 스레드 개수를 조절합니다.

```
그리고 Measureable을 분리해서 프로토콜을 사용해보신건 아주 좋았는데요!!👍
사실 은행만 사용할 기능인데 굳이 분리했어야하나? 라는 생각도 들어요~
```
이번 프로젝트에서는 은행에서만 사용했지만 만약 프로젝트가 확장되면 다른 곳에서도 사용될 수 있을 것 같아서 프로토콜로 구현했습니다.

2022-05-06 17:24 UTC, lina0322 requested changes

2022-05-08 04:38 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +private enum ClientCount: Int {
private이 타입에 붙으면 fileprivate처럼 사용이 가능하지만 좀더 의미를 명확히 하기위해 fileprivate이 적합해 보여 fileprivate이 적합해 보입니다.

2022-05-08 04:51 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private let workGroup = DispatchGroup()
BankClerk에서 사용하던 group는 필요가 없다고 판단하여 삭제하고 Bank에서만 group를 사용하도록 수정하였습니다.

2022-05-08 04:52 UTC, Taeangel commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +                BankClerk.work(client: client, group: workGroup)
전체를 감싸고 있는 DispatchQueue만 그룹 지정해도 될 것 같습니다.

2022-05-08 04:56 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
>      }
기능분리를 위해 범용적으로 보이는 기능은 프로토콜로 분리하는 것이 적절해보였는데요. 이 때문에, 은행 오픈에 대한 이유가 다르게 생각될 줄 몰랐습니다. 의도치 않은 오해를 막기 위해 프로토콜로 뺀 내용을 다시 타입 내부로 넣었습니다!

2022-05-08 05:25 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
>      }
프로토콜보다도 호출되는 방식에서 오해가 생긴 것 같다는 생각에 기존에 시간 측정을 위한 메서드를 아예 삭제하고 bank open하는 메서드를 호출하는 곳과 close하는 곳을 비슷하게 이동시켰습니다.
이 과정에서 close하는 메서드가 모든 스레드가 완료하기를 기다려야해서 bankclerk의 work 메서드에 기존과 같이 group을 인자로 전달하도록 변경했습니다.

2022-05-08 05:37 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Task.swift
> +    case loan = "대출"
Task 타입에서 연산 프로퍼티로 값을 반환하도록 수정해서 중복되는 case가 다른 타입에는 없도록 수정했습니다. 이해가 잘 안 됐는데 다시 설명해주셔서 감사드립니다.🙇‍♀️🙇🏻

2022-05-08 05:49 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +    static func findClerk(for client: Client) -> DispatchSemaphore {
반환타입으로 나오는 세마포어가 직원과 관련있다고 생각해서 findClerk이라고 네이밍했었는데 모호하다고 느껴질 수 있는 것 같아서 semaphore가 들어가도록 변경했습니다.

2022-05-08 05:51 UTC, Kim-TaeHyun-A commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        guideBank()
BankManager를 실제 은행의 매니저라고 생각하여 네이밍을 변경했습니다. 그러나 이 타입에서 메뉴를 반복적으로 실행하는 부분으로 프로그램적인 매니저의 기능을 하고 있는 것으로 생각되어 기존 네이밍으로 수정했습니다.

2022-10-06 08:59 UTC, closed without merging