Step4
yagom-academy/ios-bank-manager pull request #178
Opened 2022-05-06 08:58 UTC by grumpy-sw

안녕하세요 올라프!⛄️ @1Consumption 

우선 지난 2주동안 정말 감사했습니다🤲🤲
여러모로 많은 도움을 주셨고, 저희 또한 많은 것을 얻어간 것 같아 굉장히 뿌듯합니다!

마지막으로 step4 PR 보냅니다! 
고민한점과 프로젝트를 진행하면서 궁금했던 점들, 작성해보았습니다
잘부탁드립니다~ 🙇‍♂️🙇‍♀️
___
### 고민한점

#### 🧐 1. 대기중에 있는 고객을 업무중으로 어떻게 보낼 수 있을까?
- 고객을 대기중에 보내고, 업무중에 보내고, 업무중에서 제거하기 위해 `CustomerSendable` Protocol을 생성했습니다. stackView의 subview들인 Label들을 배열로 받고, 배열을 돌면서 대기중에 있는 label의 text와 일치하면 removeFromSuperView를 해주는 방식으로 대기중에 있는 고객을 삭제하고 업무중에 새로 라벨을 추가해주었습니다. 업무중에 있는 고객을 제거할 때도 동일한 방법으로 했습니다.

#### 🧐 2. 초기화 기능을 어떻게 구현해야 할까?
- 프로젝트 문서의 내용은 다음과 같습니다.
    > 초기화 버튼을 누르면 대기중인 고객과 타이머 모두 초기화됩니다.

    저희는 이 중에서 대기 중인 고객을 초기화하는 방법이 쉽게 떠오르지 않아 많은 고민을 했습니다. 결국 뷰 컨트롤러에서 `bankManager`를 통해 직접 구현했던 큐의 `clear`기능을 호출하는 방법으로 구현했는데요, 이 기능을 위해 `private`하지 않은 추가적인 메서드가 생성된다는 게 너무 아쉬운 부분입니다.  

#### 🧐 3. Model과 ViewController를 어떻게 연결할까?
- Console App에서 구현한 Model를 UIApp의 ViewController에 어떻게 연결할지 고민했습니다. Notification Center과 Delegate Pattern을 생각해봤는데요, Notification Center는 알림을 받는 대상이 다수일때 쓰는 것이 적절하지 않을까 생각했습니다. Delegate Pattern을 구현하기 위해 CustomerSendable 프로토콜을 구현해서 
    - Customer가 enqueue 되는 시점
    - teller가 일을 시작하는 시점
    - 업무가 끝나는 시점
마다 ViewController에게 customer 정보를 알려주어, ViewController에서 StackView에 Subview를 추가하는 등의 적절한 행동을 해주도록 했습니다.

#### 🧐 4. 업무시간을 측정하는 Timer를 어떻게 구현해야 할까?
- 한 번에 하나의 입력만 처리할 수 있는 메인 쓰레드의 특성 상, 실시간으로 업무시간을 카운팅하기 위해서는 일정한 주기로 계속해서 UI를 갱신하는 함수를 호출해줄 것으로 생각했습니다. 그렇기 때문에 사용자가 화면을 클릭하고 아래로 스크롤을 하는 상황에서 (꾹 누르고 있기 때문에) 백그라운드로 해당 함수가 실행되어야 한다고 예상했고 따라서 백그라운드에서도 동작하는 `DispatchSourceTimer`를 사용하여 구현하였습니다.

### 조언을 얻고 싶은 부분
#### ❓ Console App의 파일을 UIApp에 어떻게 가져와야 할까?
- 처음에는 Add file to “BankManagerUIApp”을 써서 파일들을 가져오려고 했는데요, Xcode에 옮겨와지기는 하지만 디렉토리에는 해당 파일들이 생성되어 있지 않아서, 저희는 파일들을 모두 새로 생성해서 하나하나 복사붙여넣기로 옮겼습니다ㅠㅠ 혹시 다른 Xcode에 있는 .swift 파일을 가져올 수 있는 방법이 있을까요?

#### ❓ extension
- View를 구성하는 코드까지 전부 포함하다 보니 View Controller의 크기가 너무나도 커져버렸습니다. 이렇게 너무 많은 코드를 담고 있는 경우에 원하는 코드의 위치를 찾기가 쉽지 않았는데요, extension 단위로 파일 분리가 가능한 것으로 보이는데 이렇게 View Controller를 작은 단위의 여러 파일로 나누어도 괜찮은가요? 복잡한 파일을 나누어 필요한 부분만 쉽게 찾을 수 있다는 의견과 오히려 파일 분리가 여러 문제가 될 수 있다는 의견이 둘 다 맞는 것 같아 의견을 듣고 싶습니다.

2022-05-06 12:59 UTC, 1Consumption requested changes
안녕하세요 그럼피 마리솔~
2주 동안 고생 많으셨습니다! 💪💪💪

------------------------------

아래는 남겨주신 코멘트에 대한 제 생각입니다.

🧐 2. 초기화 기능을 어떻게 구현해야 할까?
프로젝트 문서의 내용은 다음과 같습니다.

초기화 버튼을 누르면 대기중인 고객과 타이머 모두 초기화됩니다.

저희는 이 중에서 대기 중인 고객을 초기화하는 방법이 쉽게 떠오르지 않아 많은 고민을 했습니다. 결국 뷰 컨트롤러에서 bankManager를 통해 직접 구현했던 큐의 clear기능을 호출하는 방법으로 구현했는데요, 이 기능을 위해 private하지 않은 추가적인 메서드가 생성된다는 게 너무 아쉬운 부분입니다.

> ☃️ 모든 메소드나 프로퍼티가 private일 이유는 없습니다. 외부에서 접근해야만 하는 기능이라면 internal로 선언해야만 하죠. 저는 이 부분이 매우 자연스럽다고 느꼈어요.

❓ Console App의 파일을 UIApp에 어떻게 가져와야 할까?
처음에는 Add file to “BankManagerUIApp”을 써서 파일들을 가져오려고 했는데요, Xcode에 옮겨와지기는 하지만 디렉토리에는 해당 파일들이 생성되어 있지 않아서, 저희는 파일들을 모두 새로 생성해서 하나하나 복사붙여넣기로 옮겼습니다ㅠㅠ 혹시 다른 Xcode에 있는 .swift 파일을 가져올 수 있는 방법이 있을까요?

> ☃️ 디렉토리를 그대로 복사하고, 엑스코드 상에서 file을 추가할 수 있습니다!
<img width="2304" alt="image" src="https://user-images.githubusercontent.com/37682858/167135138-7788ce2f-a036-4666-85a7-b203af6dd9f3.png">
<img width="2304" alt="image" src="https://user-images.githubusercontent.com/37682858/167135074-038f32c7-9957-4859-b975-4e3c3040bbb8.png">


❓ extension
View를 구성하는 코드까지 전부 포함하다 보니 View Controller의 크기가 너무나도 커져버렸습니다. 이렇게 너무 많은 코드를 담고 있는 경우에 원하는 코드의 위치를 찾기가 쉽지 않았는데요, extension 단위로 파일 분리가 가능한 것으로 보이는데 이렇게 View Controller를 작은 단위의 여러 파일로 나누어도 괜찮은가요? 복잡한 파일을 나누어 필요한 부분만 쉽게 찾을 수 있다는 의견과 오히려 파일 분리가 여러 문제가 될 수 있다는 의견이 둘 다 맞는 것 같아 의견을 듣고 싶습니다.

> ☃️ 글쎄요... 이부분에 대해서는 코멘트에 남겼습니다만, 우선 View와 Model의 역할을 어디까지로 볼건지에 대해서 고민을 해보셔야할 거 같습니다! extension으로 나눈다고 해서 역할을 나눴다고 생각하면 안됩니다. 
ViewController를 작은 단위의 여러 파일로 나눈다 <- 제가 이해하기로는 ViewController의 역할을 나눈다 라고 이해했는데, 그렇다면 매우 좋은 선택입니다. 모든 객체는 오직 한가지의 역할만 해야하니까요.

---------------------------------------

2주 사이에 많이 성장하신 거 같아서 기분이 좋습니다.👏

다음 프로젝트에서도 더 성장하시길 바라면서... 이번 리뷰를 마치겠습니다.

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        stackView.distribution = .fill
이 두 프로퍼티의 기본값은 모두 `fill` 이라서 굳이 넣어주지 않아도 되지 않을까요?

> This property determines how the stack view lays out its arranged views perpendicularly to its axis. The default value is [UIStackView.Alignment.fill](doc://com.apple.documentation/documentation/uikit/uistackview/alignment/fill?language=swift). For a list of possible values, see [UIStackView.Alignment](doc://com.apple.documentation/documentation/uikit/uistackview/alignment?language=swift).

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }()
이런식으로 view 생성시 반복되는 코드는 method로 빼면 좋을 거 같아요.
만약 이 방식을 채택한다면, `lazy var` 는 무엇이고 왜 사용해야 하는지도 같이 학습해주세요.

``` swift
private lazy var someStackView: UIStackView = makeStackView(axis: .horizontal, alignment: .fill, distribution : .fillEqually, spacing: 10)

private func makeStackView(axis: NSLayoutConstraint.Axis, alignment: UIStackView.Alignment, distribution: UIStackView.Distribution, spacing: CGFloat) -> UIStackView {
    let stackView = UIStackView()

    stackView.translatesAutoresizingMaskIntoConstraints = false
    stackView.axis = axis
    stackView.alignment = alignment
    stackView.distribution = distribution
    stackView.spacing = spacing

    return stackView
}
```

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        button.heightAnchor.constraint(equalToConstant: 30).isActive = true
초기화와 동시에 오토레이아웃을 잡아주고 있네요! 그런데 아래에 `configureConstraints()` 메소드가 있어서 이 메소드에서 같이 하면 좋겠습니다.
추가적으로 클로저를 통해 View를 만들 때 클로저 내부에서 설정해주는 프로퍼티의 기준이 궁금합니다.

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    var currentTimerState: TimerState = .timerNotRunning
이부분은 View가 아닌 Model에 들어가야 하지 않을까요?

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +final class BankManagerViewController: UIViewController, CustomerSendable {
프로토콜을 채택할 때는 이런 방식보다는 아래와 같은 방식을 선호합니다. (가독성을 위해)

``` swift
protocol ProtocolA {
    func a()
    func b()
}

final class SomeViewController: UIViewController {
    
    // do something....
}

extension SomeViewController: ProtocolA {
    
    func a() {
        // do something...
    }

    func b() {
        // do something...
    }
}
```

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
하나의 메소드에서 모든 View에 대한 계층 구조와 레이아웃을 잡아주고 있네요! 각 View 별로 메소드로 분리하고, `configure()` 메소드에서는 분리한 메소드를 호출만 하면 어떨까요?

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        }
여기를 `DispatchQueue.main.async`로 감싸준 이유가 있을까요?

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
`execute(_:)` 라는 이름이 더 적절해보입니다.

그리고 Timer를 다루는 부분도 Model로 빠지는게 맞지 않을까요?
그럼피와 마리솔이 생각하는 View의 역할은 어디까지 일까요?

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        }
이부분은 guard문보다는 if let 문이 더 적절해보입니다. 두 조건식이 모두 성공함과는 상관없이 대기중 레이블과 업무중 레이블들은 없어져야 하니까요.
그리고 `subviews` 자체를 `[UILabel]` 로 형변환 하지말고, `subviews`를  순회하며 `UILabel`로 형변환 하면 어떨까요? compactMap을 사용해보세요.

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
이부분도 `DispatchQueue.main.async`로 감싸준 이유가 있어보입니다. 이유를 알 수 있을까요?

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
ViewController의 extension이 아니라 model로 빠져야할 거 같아요.

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +    var delegate: CustomerSendable?
혹시 `weak` 라는 키워드를 아시나요? 아신다면 delegate 패턴에 어떻게 적용되어야 할까요?

2022-05-06 12:59 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +
불필요한 공백 같습니다!

2022-05-07 11:09 UTC, grumpy-sw commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        stackView.distribution = .fill
> The default value is [UIStackView.Distribution.fill](https://developer.apple.com/documentation/uikit/uistackview/distribution/fill).

alignment뿐만 아니라 distribution도 fill이 기본값이더라구요! 이 부분은 삭제했습니다!

2022-05-07 11:51 UTC, grumpy-sw commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        button.heightAnchor.constraint(equalToConstant: 30).isActive = true
기존 코드에서 저희의 기준을 말씀드리면
- configureConstraints(): 다른 UIView들과의 관계를 제약조건으로 설정할 때(예: 스크롤 뷰의 X축과 superView인 스택 뷰의 X축을 일치시킬 떄)
- 클로저 내부: 다른 UIView와 관계 없이 본인만의 높이나 너비를 설정할 때
이런 기준으로 작성하고 있었는데, 메소드의 기능에 맞게 해당 메소드 내부로 이동시켰습니다!

2022-05-07 12:53 UTC, grumpy-sw commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
Layout의 변화와 직접적으로 관련있는 작업이기 때문에, 메인 쓰레드에서 호출되도록 위와 같이 `DispatchQueue.main.async`로 감싸주었습니다.

2022-05-07 13:02 UTC, marisol-develop commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +    var delegate: CustomerSendable?
reference type에서 순환참조에 의한 메모리 누수를 방지하기 위해서 weak 키워드를 사용하는 걸로 알고 있습니다.
CustomerSendable 프로토콜이 NSObject를 상속 받도록 하여 클래스만 해당 프로토콜을 채택하도록 하고, 순환참조 방지를 위해 weak var 키워드를 작성해주었습니다.

2022-05-07 15:50 UTC, marisol-develop commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
timer 관련된 메서드들을 model에 옮겨주었습니다!

2022-05-07 15:53 UTC, marisol-develop commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        }
말씀해주신대로 compactMap을 사용해서 UILable로 형변환을 해주고나서 슈퍼뷰로부터 삭제해주었습니다.
형변환을 compactMap에서 해주다보니 waitings와 workings에서 바인딩이 필요하지 않게 되네요!

2022-05-07 15:56 UTC, marisol-develop commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
동사형인 execute로 변경해주었습니다!

저희도 얘기해봤을때 타이머를 Model에서 갖고 있는게 맞다고 생각해서 Model에 BankingTimer 구조체를 만들어서 delegate으로 시간을 업데이트 하도록 변경했습니다.

2022-05-07 15:57 UTC, grumpy-sw commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }()
lazy var는 프로퍼티가 처음 사용되기 전까지는 초기화를 하지 않는 방법입니다. 
확인해 본 결과 Build 후 View Controller가 초기화되면서 내부 저장 프로퍼티 초기화가 내부 메소드 호출 가능한 시점보다 먼저이기 때문에 `private let someStackView: UIStackView = makeStackView()` 와 같이 사용할 수 없었던 것이었습니다..
이 방법을 몰라서 여러 시도를 하다가 변경을 포기했는데 ㅠㅠ 예시를 들어주신 것처럼 메소드를 통해 초기화를 할 수 있게 해주므로 반복되는 코드를 줄일 수 있었습니다!

2022-05-07 15:58 UTC, grumpy-sw commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    var currentTimerState: TimerState = .timerNotRunning
BankingTimer 타입을 만들고 그곳으로 이동시켰습니다!

2022-05-07 15:58 UTC, marisol-develop commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +        }
UI를 변경하는 부분이어서 main.async로 감싸야 한다고 생각했었는데, 해당 removeLabel 메서드를 호출하는 addToWorkingList가 이미 main.async에서 메서드를 호출하고 있기 때문에 불필요하다고 생각해서 삭제했습니다.

2022-05-07 15:59 UTC, grumpy-sw commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +final class BankManagerViewController: UIViewController, CustomerSendable {
프로토콜 채택하는 부분을 나누고 구현 메서드를 그곳으로 이동시켰습니다 :)

2022-05-07 16:00 UTC, marisol-develop commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    }
감사합니다!
각 view 별로 constraints와 structure를 잡아주는 메서드를 만들어서 configureView라는 메서드에서 분리한 메서드들을 모두 호출해주었습니다!🙇‍♀️

2022-05-09 00:34 UTC, 1Consumption approved these changes
👍

2022-05-09 00:34 UTC, 1Consumption commented on BankManagerUIApp/BankManagerUIApp/BankManagerViewController.swift
> +    private lazy var workingLabel: UILabel = makeLabel(text: "업무중", alignment: .center, font: .preferredFont(forTextStyle: .largeTitle), textColor: .white, backgroundColor: .systemIndigo)
더 나아가 이런 방법도 있답니다ㅎㅎ
``` swift
final class A {
    
    private lazy var stackViewA: UIStackView = makeStackView(with: .a)
    private lazy var stackViewB: UIStackView = makeStackView(with: .b)
    private lazy var stackViewC: UIStackView = makeStackView(with: .c)
    private lazy var stackViewD: UIStackView = makeStackView(with: .d)
    
    private func makeStackView(with style: Style.StackView) -> UIStackView {
        let stackView = UIStackView()
        stackView.translatesAutoresizingMaskIntoConstraints = false
        stackView.alignment = style.alignment
        stackView.spacing = style.spacing
        stackView.axis = style.axis
        
        return stackView
    }
}

extension A {
    
    enum Style {
        
        enum StackView {
            
            case a
            case b
            case c
            case d
            
            var spacing: CGFloat {
                switch self {
                case .a:
                    return 1
                    
                case .b:
                    return 2
                    
                case .c:
                    return 3
                    
                case .d:
                    return 4
                }
            }
            
            var alignment: UIStackView.Alignment {
                switch self {
                case .a:
                    return .center
                    
                case .b:
                    return .leading
                    
                default:
                    return .fill
                }
            }
            
            var axis: NSLayoutConstraint.Axis {
                switch self {
                case .a:
                    return .horizontal
                    
                case .b:
                    return .horizontal
                    
                case .c:
                    return .vertical
                    
                case .d:
                    return .vertical
                }
            }
        }
    }
}
```

2022-05-09 00:35 UTC, merged