은행 창구 매니저 [STEP1] Kiwi, Kay
yagom-academy/ios-bank-manager pull request #181
Opened 2022-06-27 08:43 UTC by kiwi1023

안녕하세요  @corykim0829 ! 
어쩌다 보니 인사 한번없이 PR을 먼저보내내요.. 이점 양해 부탁드립니다!
STEP1완료 하였습니다. 많이 부족하지만 앞으로 리뷰 잘 부탁드리겠습니다 !
감사합니다!

# 배운개념 📚 :
1. 의존성 관리도구 (CocoaPods의 실제 적용 실습 차원)
의존성의 의존성까지 자동으로 관리해준다.
누구나 쉽게 어떤 의존성이 애플리케이션에 있는지 알 수 있다.
처리방법이 간단하기 때문에 시간을 절약해주고 안정성을 보장한다.

# 궁금한점 ❓ :
저희가 Linked-List로 구현한 큐를 시험해보려 했습니다.
이전 사용하던 방식대로 `@testable import BankManagerConsoleApp` import를 해주려 했습니다. 하지만, 아래와 같은 에러 문구가 발생하여 사진과 같이 각각의 BankManagerQueue, LinkedList, Node 파일의 타겟 멤버쉽을 체크 해주었습니다.
> [Could not find module 'BankManagerConsoleApp' for target 'x86_64-apple-macos'; found: arm64-apple-macos, at:/Users/kay/Library/Developer/Xcode/DerivedData/BankManagerConsoleApp-acslyqhrplbojmgnotygnhtucvdv/Index/Build/Products/Debug/BankManagerConsoleApp.swiftmodule`]

![](https://i.imgur.com/jadukdq.png)

`@testable import BankManagerConsoleApp`에서 나오는 에러를 어떻게 처리해야 하는지 알려주시면 감사 하겠습니다.

2022-06-28 07:42 UTC, corykim0829 requested changes
수고 하셨습니다 Kiwi, Kay! 👏👏

테스트 설정 관련해서 질문을 주셨는데, 제가 직접 해보니 잘 되더라구요!

<img width="538" alt="image" src="https://user-images.githubusercontent.com/34022757/176120378-4da2ec86-e1aa-42fb-af6e-6b750506ced1.png">
오른쪽이 제가 테스트로 만들어본 프로젝트입니다. Kiwi, Kay 프로젝트에는 test 파일 말고 다른게 추가되어있는걸 볼 수 있었어요! (이것 때문에 import가 안되는 것 같아요)

저는 `유닛 테스트 번들`로 추가했는데, 유닛 테스트로 잘 추가하셨을까요? 이 부분 확인 부탁드려요 🙏
그리고 프로덕트 설정에 들어가서 Edit Scheme에서도 테스트 추가를 해주셔야합니다!

Command line tool 앱에서는 import를 하지 않아도 테스트 빌드는 가능합니다. @testable 명시는 internal 까지 테스트 가능하도록 하기 위한 어노테이션입니다! 참고하세요!

2022-06-28 07:42 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerQueueTest/BankManagerQueueTest.swift
> +class BankManagerQueueTest: XCTestCase {
테스트 깔끔하네요 😀 근데 peek에 대한 테스트도 추가되면 좋을 것 같아요

2022-06-30 05:34 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerQueueTest/BankManagerQueueTest.swift
> +class BankManagerQueueTest: XCTestCase {
https://github.com/yagom-academy/ios-bank-manager/pull/181/commits/064b83085076a348c5af406be081b16a8b090e5b

말씀해주신 peek에 대한 테스트도 추가 해주었습니다!

2022-06-30 05:51 UTC, corykim0829 approved these changes
수고하셨습니다!!

다음 스텝 목표 일정 저에게 말해주시고 스텝 진행하면 될 것 같아요!

2022-06-30 05:51 UTC, merged