은행 창구 매니저 [STEP1] unchain, BaekGom
yagom-academy/ios-bank-manager pull request #182
Opened 2022-06-27 09:11 UTC by unchain123

# 은행 창구 매니저 STEP1 PR
@jryoun1 
안녕하세요 제이크!
첫번째 PR드립니다.
새로운 프로젝트 2주동안 잘 부탁드리겠습니다. 

## 고민한점
 - git 에서 pull 을 받을때 마다 Pods에 있는 파일들이 없어지는 현상이있어서 pod install을 실행했습니다 -> 나중에 다시 pull을 받아보니 Pods파일이 없어지는 현상이 사라져서 해결되었습니다
  
 - SwiftLint 파일 생성후 disabled rules를 적용 시키려고 했으나Trailing_Whitespace 는 적용이 안되었습니다 -> trailing_whitespace 로 변경후 적용이 되었습니다.
## 궁금한점
- Pods파일이 사라지는 것이 gitignore파일에 넣어줘서 그런것이라고 판단을 햇었는데 나중에는 이런 현상이 없어지는 것을 확인했습니다. 왜 다시 안없어지게 됐는지 궁금합니다.

## 트러블슈팅
- 처음 UITest작성시 testable을 사용해서 진행하려고 할때 아래와 같은 문제가 발생해서 scheme을 추가하고 타겟을 설정해서 해결을 했습니다.

|문제화면|해결방법|해결방법2|
|:---:|:---:|:---:|
|<img src="https://i.imgur.com/EPGfR5v.png" width="250" height="250">|<img src="https://i.imgur.com/G8JnAWA.png" width="250" height="250">|<img src="https://i.imgur.com/d3LSvvP.png" width="250" height="250">|

- 그 후에 UItest 진행시 아래와 같은 에러가 unchain의 맥(M1)에서만 발생하고 baekgom의 맥(Intel)에서는 발생하지 않았습니다.
```
Could not find module 'BankManagerConsoleApp' for target 'x86_64-apple-
macos'; found: arm64-apple-macos, 
at:/Users/kay/Library/Developer/Xcode/DerivedData/BankManagerConsoleApp-
acslyqhrplbojmgnotygnhtucvdv/Index/Build/Products/Debug/BankManagerConsoleApp
.swiftmodule
```
- 하지만 다시 commit을 하고 pull을 받아서 테스트 코드를 진행해 보니 testable도 사용이 가능하고 위와 같은 에러가 발생하지 않았습니다.

- 어떤 이유에서 저런 에러가 났던건지 이게 M1과 인텔의 차이에서 오는 에러인지 저희의 휴먼에러인지 알고 싶습니다.

2022-06-28 14:01 UTC, jryoun1 requested changes
@unchain123 @Baek-Gom-95 
안녕하세요 언체인, 백지 🙋‍♂️
백지라고 하면 될까요? 아니면 백곰이라고 해야하나요?!  

빠르게 step1을 진행해주셨네요 👍🏻
전반적으로 자료구조들도 깔끔하게 잘 구현해주셨습니다 👏 
크게 리뷰해드릴만한 내용이 없던 것 같습니다.

몇가지 궁금한 점과 수정될만한 부분들을 코멘트 남겨보았습니다 🙏🏻
확인 부탁드립니다

### 궁금한 점
> Pods파일이 사라지는 것이 gitignore파일에 넣어줘서 그런것이라고 판단을 햇었는데 나중에는 이런 현상이 없어지는 것을 확인했습니다. 왜 다시 안없어지게 됐는지 궁금합니다.

음,, 일단 말씀하신대로라면 gitignore에 Pods 파일을 넣어두셨다면 Pods 파일은 remote로 올라가지 않았을 것 같습니다. 따라서 pull을 할 때마다 새롭게 pod install을 해주어야하는게 맞습니다. 
하지만 코멘트에서 말씀드린대로 현재 `Pods/` 를 작성하신 gitignore의 위치가 잘못된 것 같습니다. 
그래서 뭔가 오류가 발생한 것 같습니다. 🤔 왜 해결이 되었는지는 잘 모르겠네요. 

다른 코멘트에서도 남겨드렸는데 이 부분 Pods, Podfile, Podfile.lock에 대해서 한 번 알아보시면 좋을 것 같습니다. 이때 Pods파일을 github에 올리지 않는 이유와 협업할 때 무엇을 github에 올려야하는지, 그리고 pod install은 무엇인지에 대해서도 같이 알아보시면 도움이 될 것 같네요 🙏🏻

> 처음 UITest작성시 testable을 사용해서 진행하려고 할때 아래와 같은 문제가 발생해서 scheme을 추가하고 타겟을 설정해서 해결을 했습니다.

말씀해주신 것은 UITest가 아니라 UnitTest인 것 같네요 🙏🏻
관련된 오류는 찾아봤더니 일단 휴먼에러는 아닌 것 같습니다. 
M1과 Intel맥의 차이라기보다는 M1에서 사용할 때 문제가 있는 경우인 것 같습니다. 
관련된 질문들과 답변이 forum에 있으니 한 번 참고해보시면 좋을 것 같습니다. 🙏🏻
[Apple forum](https://developer.apple.com/forums/thread/667440) [도움이 될 만한 비슷한 글](https://velog.io/@danna-lee/iOS-could-not-find-module-for-target-x8664-apple-ios-simulator-found-arm64-arm64-apple-ios-simulator-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0)

2022-06-29 01:12 UTC, unchain123 commented on BankManagerConsoleApp/BankItemQueueTest/BankItemQueueTest.swift
> +    func test_deQueue_리스트에서_맨앞에_갚을제거하는지() {
변경해 주었습니다.

2022-06-29 01:13 UTC, unchain123 commented on BankManagerConsoleApp/BankItemQueueTest/BankItemQueueTest.swift
> +        let testNumber = "1"
expectedNumber로 변경했습니다.

2022-06-29 01:28 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankItemQueueTest/BankItemQueueTest.swift
> +    var sut: BankItemQueue<String>!
- if let, guard let 등의 방법이 있습니다
- 테스트 코드 영역이기 때문에  어플 구동에는 영향을 주지않고 크래시가 나더라도 앱이 꺼지는 현상이 없기 때문에 오히려 강제 언래핑을 사용해서 문제가 생긴 부분을 바로 파악이 가능헤서 더 직관적으로 확인이 가능한 이점이 있다고 생각합니다.

2022-06-29 01:39 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList/Node.swift
> +class Node<T> {
- class 에 있는 프로퍼티 값을 LinkedList 에서 참조해서 사용해야 하기 때문에 class 를 선택했습니다

2022-06-29 01:39 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList/LinkedList.swift
> +struct LinkedList<T> {
- 다른 기존 타입으로부터 상속받거나 자신을 상속할 필요가 없기 때문에 struct 를 선택했습니다
- struct 에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당하다 생각했습니다

2022-06-29 01:39 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList/BankItemQueue.swift
> +struct BankItemQueue<T> {
- 다른 기존 타입으로부터 상속받거나 자신을 상속할 필요가 없기 때문에 struct 를 선택했습니다
- struct 에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당하다 생각했습니다

2022-06-29 01:41 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList/Node.swift
> +    var data: T?
data가 옵셔널인 이유는 이 링크드리스트를 이용하면서 data에 값이 할당이 되기 전에 그 값에 접근하게 되면 오류가 발생할 수 있기 때문에 미리 옵셔널로 지정해 주어서 앱 구동시 충돌이 일어나는 것을 방지하기 위함 입니다.

2022-06-29 01:50 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankItemQueueTest/BankItemQueueTest.swift
> +    func test_isEmpty호출시_비어있지않으면_False반환하는지() {
False -> false 로 변경해주었습니다 😊

2022-06-29 01:53 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/Podfile.lock
> +PODS:
- Podfile : 우리가 설치하고픈 라이브러리가 무엇인지, 이를 코코아팟한테 알려주기 위해  작성하는 것이 바로 Podfile입니다.
- Podfile.lock : 어떤 팟의 어떤 버전을 받았는지를 기록하는 것입니다.

2022-06-29 01:54 UTC, unchain123 commented on BankManagerConsoleApp/Podfile.lock
> +PODS:
|   unchain  | BaekGom    |
| --- | --- |
|<img src= https://i.imgur.com/UUsWfKC.png width=1000, height=250>|<img src= https://i.imgur.com/BQJfC1r.png width=1000, height=250>|

Podfile.lock 을 둘다 확인한 결과 같은 버전을 사용하고 있음을 확인 할 수 있었습니다.

2022-06-29 12:34 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList/Node.swift
> +    var data: T?
> data가 옵셔널인 이유는 이 링크드리스트를 이용하면서 data에 값이 할당이 되기 전에 그 값에 접근하게 되면 오류가 발생할 수 있기 때문

이라고 해주셨는데 그러한 경우가 어떤 경우가 있을까요? 🤔

2022-06-29 12:35 UTC, jryoun1 commented on .gitignore
> +Pods/
`# Pods/` 가 이미 있는데 주석을 풀어주면 되지 않을까요? 🤔

2022-06-29 12:38 UTC, merged

2022-06-29 12:41 UTC, unchain123 commented on .gitignore
> +Pods/
아! 넵 맞습니다