은행 창구 매니저 [STEP1] - 현이, 그루트
yagom-academy/ios-bank-manager pull request #183
Opened 2022-06-27 12:44 UTC by Groot-94

@GREENOVER  안녕하세요 그린! 
현이@seohyeon2 와 그루트@Groot-94 입니다! 🧏‍♂️
Step1 첫 PR 보냅니다! 이번 프로젝트 잘 부탁드립니다!

## 📌 배경
- 은행 창구 매니저 앱
- 은행에 도착한 고객이 임시로 대기할 대기열(큐, Queue) 타입구현.
## 📌 작업 내용
#### Node
- Linked-list 의 노드를 구현했습니다.
#### LinkedList
- CustomerQueue를 구현하기 위한 Linked-List를 구현했습니다.
#### CustomerQueue
- 고객이 임시로 대기할 Queue타입을 구현했습니다.
## 📌 테스트 방법
- UnitTest를 이용한 테스트
## 📌 리뷰 노트
#### 메서드를 연산프로퍼티로 사용하는 방식의 장점이 궁금합니다.
- 저희는 매개변수가 없고, 내부의 구현이 한 줄로 끝나는 함수는 가독성을 위해서 연산프로퍼티로 변경하였습니다.
- 이 부분이 단순한 가독성 이외에 어떤 장점이 있을지 궁금합니다.

2022-06-28 00:40 UTC, GREENOVER requested changes
@Groot-94 @seohyeon2 
안녕하세요 두분!
만나서 반갑습니다🙇🏻
다시 한번 인사드려요ㅎㅎ
잘 부탁드리며 그럼 2주간 은행 매니저 꼭 뿌셔보자구요!!🙌
우선 이번 스텝1 너무 빠르고 잘 해주셔서 고생 많으셨습니다🥳🥳🥳
전체적으로 노드, 링크드리스트, 큐를 관심사를 잘 세분화해서 각자 구현을 잘해주셨어요👍
조금 보완되면 좋을 부분들 위주로 리뷰 드려보겠습니다..!
***
### 칭찬 드리고 싶은 부분
- 커밋 이력 관리를 잘 해주셔서 리뷰하기 편했습니다 💯
- 각 파일을 잘 나누고 관심사 별로 딱딱 잘 들어가있어서 가독성도 좋고 너무 좋네요 💯
- 테스트 코드까지 갓벽합니다 💯
***
### 리뷰노트에 대한 저의 의견
- 우선 연산 프로퍼티를 사용함에 있어서 저는 크게 두가지를 이점으로 생각하고 있습니다!
말씀하신것처럼 첫번째로는, 가독성이죠!
아무래도 메서드에서 할일을 피할 수 있으며 프로퍼티 선언 시 응집해 관심사를 모아줄 수 있는것이 가독성 향상에 많은 도움이 될 것이며 추후 유지보수에도 편리하겠죠.
또한 코드의 양도 연산 프로퍼티를 사용하면 조금이라도 줄 수 있으니 클린 코드가 되지 않을까 싶어요.
두번째로, 관심사 분리와 겹치는 내용인데 은닉화 할 시에도 편리합니다.
예를들어 A라는 타입에서 a라는 평범한 저장 프로퍼티가 있고 b라는 프로퍼티는 a가 존재하느냐에 따라 Bool 값을 가지는 변수라고 생각해보죠..!
그러면 B라는 타입에서 A라는 타입을 초기화 시키고 사용할때 a와 b가 모두 저장 프로퍼티로 존재한다면 a와 b의 값을 모두 지정해주거나 혹은 A 타입에서 a 프로퍼티를 판단해 b의 값을 저장시키는 메서드를 만들고 이를 호출해야겠죠?
근데 그렇게도 할 수 있겠지만 그렇다면 B라는 타입은 b를 직접 접근할 필요가 없을때도 있을것이고 굳이 b값까지 주는것은 B가 하는 역할에 어긋날 수 있다고 생각해요.
반면 연산 프로퍼티를 사용한다면 위의 이슈들을 깔끔하게 해결해줄 수 있어요.
즉 B라는 타입에서는 A를 이니셜할때 a만 지정해주면 모두 끝낼 수 있지 않을까해요ㅎㅎ
저는 이렇게 생각했는데 여러분들이 제 의견을 듣고 사용 기준의 정립이 되면 좋겠습니다!
제가 말재주가없어서.. 이해가 안간다면 꼭 말씀해주세요🙇🏻
***
### 보완되면 좋을것 같은 부분
- 코멘트에서도 언급은 드렸었는데 현재 LinkedList 구조상 append, remove에서 index를 통해 작업해줄 수 없는 단점이 있는것 같아요..!
요 부분 한번 확인해보시면 어떨까 싶습니다🙋🏻
- 전반적으로 테스트 코드 너무 좋아요!
그런데 실패 시의 케이스들도 같이 추가되면 어떨까요?
지금은 다 성공의 케이스라고 느껴져서 TDD에서 무언가 빠진 느낌이 듭니다🤔
***
다시 한번 너무 고생 많으셨고 언제든 리뷰 재요청을 해주시면 빠르게 또 확인해보겠씁니다!~
좋은 하루 되세요🙇🏻

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        return head == nil ? true : false
return 코드도 꼭 들어가야할까요~?
만약 그렇지 않다면 왜 그럴까요🤔

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    init(head: Node<T>? = nil, tail: Node<T>? = nil) {
요런 컨벤션은 어떠세요~?
저는 파라미터가 2개 이상이 되면 강제적으로 개행을 해줘서 아래와 같은 컨벤션을 사용하는데,
가로로 길어지는것보다 세로로 길어지는 컨벤션을 선호하는 편입니다🙋🏻
이유는 모든 작업자의 기기 사이즈가 다를것이기에 가로로 길어지면 가독성을 간혹 해칠때가 많더라구요ㅠ
이건 정말 스타일의 차이입니다!
아~ 이런것도 있구나 하고 보시면 충분합니다👍
```swift
init(
  head: Node<T>? = nil,
  tail: Node<T>? = nil
) {
...
}
```

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +
이슈는 아니지만 여러분들 엑코에서 컴파일 시 7번 라인에서 
`Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
`
요런 워닝 못보셨나요~?

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private var linkedList = LinkedList<T>()
이니셜라이저를 통해 초기화 시켜주는것과 어떤 차이가 있을까요~?
또 어떤 방식이 더 여러분들 방향성에 유용할까요?ㅎㅎ

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func append(data: T) {
현재 append는 바로 뒤에만 data를 추가해줄 수 있는데 만약 중간에 data를 넣어주고 싶을때는 어떡할까요~?🤔

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +final class LinkedList<T> {
LinkedList를 클래스 타입으로 만들어주신 이유가 있나요?🙋🏻

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +final class CustomerQueue<T> {
큐를 클래스 타입으로 만들어주신 이유가 있을까요?🙋🏻

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func remove() -> T? {
위 append와 마찬가지로 중간 data를 제거해줘야할때는 현재 방법으로만은 충분하지 않을것 같아요🤔

2022-06-28 00:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = nil
tail 제외하고 head만 nil해줘도 괜찮은가요?🙋🏻

2022-06-28 03:13 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = nil
LLDB를 사용해서 테스트 했을때 tail에 값에 남아있는걸 확인했습니다... 저희는 `head 에서 tail을 참조하지 않으면 ARC로 인해 tail이 자동으로 메모리에서 사라진다고 생각을 했는데 그게 아니였네요!` 
혹시 append 함수에서 
```swift 
tail = head 
```
이렇게 tail에 head를 참조해줬기 때문에 남아있는게 맞을까요..?

[94a23ed](https://github.com/yagom-academy/ios-bank-manager/pull/183/commits/94a23edd6c04c4c732a6c3b56d8a0e1d17c128c8)

2022-06-28 03:15 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +				MACOSX_DEPLOYMENT_TARGET = 12.2;
변경 기준은 제 맥북 사양이었습니다..😅

테스트파일에 대한 스키마를 추가해주고, 테스트를 실행해보니 제 맥북과 호환이 되지 않아 아래와 같은 에러가 발생하였습니다.🥲 
제 맥북이 테스트에 적용된 버전보다 낮아서 발생한 것이기에, 제 맥북 사양에 맞추었습니다..!
```
Cannot test target “LinkedListTest” on “My Mac”: My Mac’s macOS 12.2.1 doesn’t match LinkedListTest’s macOS 12.3 deployment target.
```

2022-06-28 03:15 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func remove() -> T? {
이번 프로젝트에서 만든 Linked List는 Queue를 위해서 구현했기 때문에 FIFO 방식으로 값을 꺼내고 넣어준다고 생각해서 구현하지 않았습니다. 말씀해주신 부분은 따로 구현해보도록 하겠습니다!

2022-06-28 03:16 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +final class LinkedList<T> {
이번 프로젝트에서 만든 Linked List는 Queue를 위해서 구현했기 때문에 FIFO 방식으로 값을 꺼내고 넣어준다고 생각해서 구현하지 않았습니다. 말씀해주신 부분은 따로 구현해보도록 하겠습니다!

2022-06-28 03:16 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func append(data: T) {
이번 프로젝트에서 만든 Linked List는 Queue를 위해서 구현했기 때문에 FIFO 방식으로 값을 꺼내고 넣어준다고 생각해서 구현하지 않았습니다. 말씀해주신 부분은 따로 구현해보도록 하겠습니다!

2022-06-28 03:20 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +final class LinkedList<T> {
Linked List에서 사용하는 Node는 값을 참조하는 특성을 이용한 구조라고 생각을 했습니다. 그래서 Node를 Class로 구현했고, Node를 실제로 사용하는 LinkedList도 Node를 사용하면서 참조타입의 특성을  이용한다고 생각해서 Class로 구현했습니다. 저희가 생각하는게 맞을까요..?

2022-06-28 03:21 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +final class CustomerQueue<T> {
위의 내용과 동일한 이유입니다. Linked List를 사용하기 때문에 구조체로 사용해도 결국 Class와 같은 성질을 가진다고 생각을 했습니다.

2022-06-28 03:21 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +final class CustomerQueue<T> {
final 키워드를 사용하면 메서드, 프로퍼티, 서브 스크립트를 재정의 하는 것을 방지할 수 있다고 알고 있습니다.
이러한 이점때문에 상속을 포기해야 하지만,
이번 스텝에서는 CustomerQueue가 상속 하는 경우가 없다고 생각했기에 final 키워드를 작성하였니다.

2022-06-28 03:24 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +
수정했습니다..!

[7829ace](https://github.com/yagom-academy/ios-bank-manager/pull/183/commits/7829aceea0b04365706dac96ec4e0ab0350bc369)

2022-06-28 03:29 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        head = nil
기본적으로 강한 참조 싸이클을 가지게 되어 head를 없애줘도 그를 참조하는 tail 인스턴스는 해제가 안될거에요..!
그렇기에 이를 해제하기 위해서는 모든 참조를 해제 시켜줘야할거에요🙋🏻
그렇지 않다면 지금처럼 메모리 누수가 날것 같아요!
한번 ARC의 역할을 더 보시면 도움이 될것 같습니다 ㅎㅎ
참고로 리뷰어중 한명인 라자냐의 ARC에 관한 포스팅이 아주 도움이 개인적으로 많이 되어서 공유드립니다🙌
https://velog.io/@wonhee010/ARC

아..! 그리고 마지막 질문주신 수정이 제가 생각한게 맞습니다ㅎㅎ

2022-06-28 03:29 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func append(data: T) {
음 제네릭한 범용적인 LinkedList, Queue 구현과는 조금 거리가 있어보여요..!
왜냐하면 추후 스텝에서 어떤 요구사항을 만날지 모르기에 Queue는 아니더라도 LinkedList에서는 현재 구현에 맞게 커스텀하게 구현하는것보다 범용적인 구현이 좋을것 같아요🤔
예를들어 중간에 위치한 고객이 기다리다가 랜덤하게 가버리는 요구사항이 나올수도 있는것도 충분히 가능한 사항이라고 볼 수 있을것 같아요! (추후 프로젝트 요구사항이 아닌 가정의 상황입니다ㅎㅎ)
우리는 꼭 추후 유지보수에도 초점을 맞춰주는 과정이 필요합니다🙌

2022-06-28 03:29 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +final class LinkedList<T> {
정답은 없습니다!
그런데 보통 클래스 vs 구조체 모두 사용할 수 있다면 대부분은 클래스를 사용하는 이점을 꼭 들고가야하지 않는 다면 성능적으로도 그렇고 구조체를 사용하도록 권장하고 있어요..!
Node는 클래스로만 가능할것같고 말씀하신 LinkedList에서 참조 타입의 특성을 어떻게 이용될 수 있을까요?

2022-06-28 03:29 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +final class CustomerQueue<T> {
요기도 위 코멘트와 상동합니다ㅎㅎ

2022-06-28 03:39 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        return head == nil ? true : false
비교연산자로 비교하는 부분만 남겨두게 수정했습니다!

return도 삭제했습니다!
getter만 사용하는 프로퍼티고 단일 코드라 return이 없어도 암시적으로 반환 해주기 때문입니다!

2022-06-28 03:40 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    init(data: T, next: Node<T>? = nil) {
수정했습니다!

2022-06-28 03:48 UTC, Groot-94 commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +    func test_enqueue가_잘되는지() {
단순하게 생각했을때 가독성의 차이라고 생각합니다. 
1. 한글로 모두 작성하는 경우 : 전체적인 가독성은 뛰어나지만, 메서드 이름을 한글로 작성하는데 어려움이 있다고 생각합니다.
2. 한글 + 영어로 작성하는 경우 : 어떤 부분을 한글로 해야 할 지 영어로 해야 할 지 기준을 잡는데 어려움이 있지만, 적절한 기준을 정한다면 보는 사람에겐 가장 가독성이 좋을거라고 생각합니다.
3. 영어로 모두 작성하는 경우 : naming 부분이 힘들다고 생각합니다. 영어를 못 하는 사람에게는 가독성도 떨어지지 않을까 생각합니다..

저희는 사실 따로 기준을 잡고 작성하진 않았습니다. Test 를 함께 하면서 테스트를 해야하는 특정 메서드 같은 고유명사는 영어로 작성하고, 나머지는 한글로 풀어썼습니다.

2022-06-28 03:50 UTC, seohyeon2 commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +    var sut: CustomerQueue<Int>!
if let, guard let 등과 같이 옵셔널 바인딩으로 nil 값을 처리하는 방법이 있습니다!

테스트 파일에서 강제 언래핑을 사용함으로서 얻은 이점은 간결성과 테스트 코드에 대한 집중도 향상이 아닐까 생각합니다.

테스트 파일에서는 앱이 크래시나는 경우를 고려해주지 않아도 된다 생각하여 강제언래핑을 사용했습니다.
이로 인해 옵셔널 바인딩으로 처리했을 때보다 코드를 간결하게 작성 할 수 있었습니다.
또 간결한 코드 덕분에 테스트코드에 더 집중할 수 있지 않았나 싶습니다..!

2022-06-28 04:12 UTC, GREENOVER commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +    func test_enqueue가_잘되는지() {
좋습니다!
정답이 있었던 부분은 아니고 저는 추가로 팀의 구성원들도 생각해봤어요.
만약 글로벌한 구성원들이 모여있는 집단이고 추후에도 그런 가능성이 있는 팀이라면 한글+영어 네이밍의 단점이 하나 더 추가될 순 있을것 같아요!
물론 지금 고민할건 아니고 정말 여러분의 생각이 궁금해서 여쭤봤습니다🙌

2022-06-28 05:30 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private var linkedList = LinkedList<T>()
기본 이니셜라이저(`init ( )`)를 이용해 초기화 시켜주는 것과 그렇지 않은 것(`init(head: nil, tail: nil)`)에 대한 차이를 여쭤보시는 걸까요..?

아니면 `CustomerQueue`의 이니셜라이저 (`init ( )`)로 초기화 시키는 것과 내부 프로퍼티(`private var linkedList = LinkedList<T>()`)에서 바로 초기화 시켜주는 것의 차이에 대해서 말씀하시는 걸까요..?😯

2022-06-28 05:39 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private var linkedList = LinkedList<T>()
앗 제 질문이 혼동되게 전달드렸군요ㅠㅠ
후자가 궁금합니다🙋🏻

2022-06-28 09:21 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func append(data: T) {
그린의 리뷰를 보고 "유지보수에 도움이 되는 방향으로 수정해보자!" 해서 양뱡향 LinkdeList 를 사용하는 방법으로  수정하고 , insert 함수를 구현했습니다.

[429c554](https://github.com/yagom-academy/ios-bank-manager/pull/183/commits/429c554f44f56d23e60c4a5f829baff718cb4261)

2022-06-28 09:22 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func remove() -> T? {
removeAt 메서드를 구현해봤습니다!

[429c554](https://github.com/yagom-academy/ios-bank-manager/pull/183/commits/429c554f44f56d23e60c4a5f829baff718cb4261)

2022-06-28 09:40 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +final class LinkedList<T> {
LinkedList의 모든 프로퍼티들은 Node타입으로 구현이 되어있어,
메서드에서 사용될 시 heap을 사용하여 메모리를 관리한다고 생각했습니다.
결국 linkedList 타입을 구조체로 구현해도 참조 타입처럼 쓰이는 것 같습니다.

이렇게 생각을 해봤을 때, 
LinkedList가 구조체로 되어 있으면 "구조체는 값타입인데 왜 프로퍼티들은 참조값인지"에 대한 혼동을 줄 수 있을 것 같았습니다.
어차피 참조타입으로 쓰인다면, 명시적으로 class라 적어주는 편이 제 3자가 코드를 읽을 때 이런 혼동을 줄여주지 않을까 생각합니다..!

혹시 저희가 생각한 것이 다르거나 더 좋은 방향이 있다면 말씀 부탁드립니다 😊🙇🏻‍♀️

2022-06-28 09:56 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func append(data: T) {
좋습니다! 괜찮아요 ㅎㅎ
쭉쭉 앞으로 더 좋은 방향의 코드를 짜실 수 있을거에요!
저도 지금 짜고 한달뒤에 보면 마음에 안들듯이 항상 여러번 볼 때마다 발전하실 수 있으니 조급하게 생각하지 않으셔도 됩니다🙌

2022-06-28 09:57 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +final class LinkedList<T> {
오호 그렇군요!
여러분이 충분히 근거를 가지고 결과를 도출하셨기에 더 할 나위없습니다!
그 방향으로 킵고잉하시죠🙌

2022-06-28 11:06 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private var linkedList = LinkedList<T>()
이니셜라이저로 초기화 시키는 것과 내부 프로퍼티에서 바로 초기화 시켜주는 것의 차이는 의존성 주입 여부가 아닐까 싶습니다..!

이니셜라이저를 사용해 초기화 하는 경우엔 의존성을 주입해 줄 수 있습니다.
반면에 내부 프로퍼티에서 초기화 시켜주면 의존성을 주입할 수 없습니다.

의존성 주입을 해주게 되면 코드의 재활용이나 유지보수 면에서 이점이 있다고 알고 있습니다.
추후 유지보수에 초점을 맞춘다면 이니셜라이저를 사용하는 것이 저희의 방향성에 유리하겠네요..!

혹시 답변이 부족하거나, 잘 못 알고 있거나, 그린이 생각하시던 차이가 아니라면 피드백 부탁드립니다🥺

2022-06-28 11:21 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private var linkedList = LinkedList<T>()
이해하신것이 제가 궁금했던 부분이고 파악하신것이 정확하십니다! ㅎㅎ

2022-06-28 11:32 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    func dequeue() -> T? {
nil일 경우, throw로 에러를 던져주게 수정했습니다😊

2022-06-28 12:07 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private var linkedList = LinkedList<T>()
의존성 주입을 사용하는 방법으로 수정해봤습니다. 하지만 아직 의존성 주입 역전에 대해 이해를 하지 못해서 protocol을 사용하는 방식은 적용하지 못했습니다!
조금 더 공부를 해보고 적용해보도록 하겠습니다!

[87b1a59](https://github.com/yagom-academy/ios-bank-manager/pull/183/commits/87b1a5953d60b53033bcdc71e10d3cfcaf271d2f)

2022-06-29 01:39 UTC, GREENOVER approved these changes
@seohyeon2 @Groot-94 
두분 리팩토링 하시느라 너무 고생 많으셨어요!
훨씬 더 제네릭해지고 범용성도 좋아지고 코드의 질도 향상된게 눈에 보이네요👍👍
추가적으로 재리뷰하면서 이후 스텝에서 고쳐보면 좋을 부분들과 컴파일 이슈가 발생하는 부분들에 대해 코멘트를 드려봤습니다!
한번 전체적으로 이후 스텝에서 확인해보시면 좋을것 같아요ㅎㅎ
로직의 고민은 계속하시면 훨씬 더 더 나은 코드가 될거라 생각합니다!
우선 스텝1은 여기서 어프로브  > 머지 하겠습니다🙌
다음 스텝도 화이팅입니다🥳🥳

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        index -= 1
이 구조면 만약 데이터가 전혀없이 remove 호출 시 nil의 data값은 반환하면서 동시에 index는 0에서 -1로도 처리될것 같은데 괜찮을까요~?🙋🏻

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        guard !isEmpty else { return nil }
isEmpty를 토글하여 사용하는것보다 isNotEmpty 프로퍼티를 만드는게 조금 더 가독성이 좋아보인다고 개인적으로 생각하는데 여러분 생각은 어떠신가요?🙋🏻

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func removeAt(index: Int) -> T? {
remove와 removeAt에서의 다른점은 Index 차이와 그에따른 삭제로직일텐데 이 둘을 합쳐볼 순 없을까 생각이 듭니다..!

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func searchNode(index: Int) -> Node<T>? {
해당 메서드는 테스트 코드 제외하고 외부에서 호출될 일이 있나요~?

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/QueueError.swift
> +}
에러 타입을 만들어주신것 너무너무 좋네요!!👍👍

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +        sut = CustomerQueue()
의존성 주입으로 바꿔주셨기에 해당 코드도 수정되야하지 않을까해요..!
아마 테스트가 안돌아갈것 같습니다!

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +        XCTAssertEqual(result, 1)
아마 result의 타입이 변했기에 정상 작동을 하지 않을것 같습니다🙋🏻

2022-06-29 01:39 UTC, GREENOVER commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +        XCTAssertEqual(result, nil)
dequeue 자체가 throw 메서드이기에 실제적으로 해당 부분에서 try catch를 해야 되지 않을까 싶습니다🤔
아마 현재 코드로는 컴파일 에러가 날것 같아요..!

2022-06-29 01:39 UTC, merged

2022-06-29 07:28 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        index -= 1
guard 문을 이용해서 노드가 존재하지 않으면 nil값을 반환하도록 수정했습니다!

2022-06-29 07:28 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        guard !isEmpty else { return nil }
isNotEmpty 구현해서 수정했습니다😆

2022-06-29 09:09 UTC, Groot-94 commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +        XCTAssertEqual(result, 1)
수정했습니다!

2022-06-29 09:10 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func removeAt(index: Int) -> T? {
removeAt 메서드로 병합했습니다.
또한 매개변수에 기본값을 추가하여, 기존의 remove 메서드처럼 매개변수가 없는 형태도 가능하게 수정하였습니다.

2022-06-29 09:10 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func searchNode(index: Int) -> Node<T>? {
없습니다..! private 키워드 추가했습니다!