은행창구매니저[STEP1] 예톤,웡빙
yagom-academy/ios-bank-manager pull request #187
Opened 2022-06-28 06:29 UTC by wongbingg

안녕하세요 Ryan Son!!🦁@ryan-son 
이번 프로젝트를 함께 진행한 웡빙과 예톤입니다! @wongbingg @yeeton 은행창구 프로젝트 Step1 PR 보냅니다
잘 부탁드립니다 !! ☺️☺️

# STEP 1

### 1. 작업 내용

- 단방향 연결리스트 구현 
    - 프로퍼티 `head`를 만들어서 리스트의 첫번째 노드를 가리키도록 해주었습니다.
    - `isEmpty`, `peek`은 리스트를 확인하는 용도로만 사용되어 연산 프로퍼티로 선언해주었고, `append`, `removeFirst`, `clear`는 실제 동작을 하기 때문에 메서드로 선언해주었습니다.
- 큐 구현
    - 단방향 연결리스트로 큐를 구현해주었습니다. 

### 2. 테스트 방법

- CommandLineTool 에서 Unit테스트를 추가해주는 방법은 달랐습니다! 

1. unitTest를 추가해준 뒤에 unit test를 할 각 파일에 Target Menbership 창에서 해당 Test에 체크를 해준다.

<img src="https://i.imgur.com/aaKWsyY.png" width="250" height="140"/>

2. Test Scheme 을 추가해준다 

<img src="https://i.imgur.com/XJrNhAS.png" width="300" height="350"/>

3. 유닛 테스트 프로덕트를 추가해준다.

<img src="https://i.imgur.com/4Qy6EyN.png" width="600" height="350"/>

### 3. UnitTest
- NodeTests
- LinkedListTests
- CustomerQueueTests

[참고 링크](https://jwonylee.tistory.com/entry/XCode-Swift-Command-Line-Tool-프로젝트에서-유닛-테스트-하기)

### 4. 스텝 핵심 경험

- [x] Linked-list 자료구조의 이해 및 구현
- [x] Queue 자료구조의 이해 및 구현
- [x] Generics 개념이해 및 적용

### 5. 고민한 점

- 저희가 step2까지의 기능 명세서를 보았을 때는 리스트 중간에 데이터가 추가될 일이 없어보였고, 또 tail 변수를 만들어주어야 할 필요성을 느끼지 못해서 양방향 연결리스트가 아닌 단방향 연결리스트로 구현해주었습니다. 추후 확장성도 고려해봤을 때 양방향 연결리스트로 구현하는 것이 좋았을지 여쭤보고 싶습니다.

- 큐와 연결리스트의 기능이 같아보이는데 따로 연결리스트와 큐 타입을 만들어서 큐에서 연결리스트의 기능을 가져와서 사용하는 것이 이해가 가지 않았습니다. 그냥 큐에서 바로 연결리스트의 기능을 구현해주면 되지 않나? 라고 생각했었습니다.
    -  찾아보니 큐는 구현 방법이 정의되어 있지 않은 자료형이고 연결리스트는 다음 데이터의 위치를 저장하는 방식인 자료구조기 때문에 따로 구현해줘야 함을 알게되었습니다! 저희가 생각한 것이 맞는지 궁금합니다.

- CustomerQueue를 구조체로 만들어 주었는데, 안에 쓰이는 Node 인스턴스는 클래스(참조타입) 입니다. 이렇게 만들어줄 경우 CustomerQueue도 결국 참조타입이 되는 것인지 궁금합니다.

이상 PR 마치겠습니다! 감사합니다 라이언

2022-06-29 07:09 UTC, ryan-son requested changes
예톤, 웡빙, 안녕하세요. Step 1 수행하시느라 고생 많으셨습니다.

커밋이 잘 정리되어 있어 여러분께서 프로젝트를 어떤 방향성을 가지고 Step 1을 진행하셨는지 파악하기 용이했습니다. 세부적인 피드백은 개별 코멘트를 참고해주세요.

# 개별 피드백 P 태그 안내
각 코멘트에는 P1 ~ P5까지의 태그가 포함되어있습니다. 태그의 의미는 아래와 같으니 참고하세요. [뱅크샐러드 개발 문화](https://blog.banksalad.com/tech/banksalad-code-review-culture/)에서 차용하였습니다.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/69730931/176375527-04436d3c-bb00-4abd-a1d9-224b1c65b9eb.png">

# PR 질의응답
>* 저희가 step2까지의 기능 명세서를 보았을 때는 리스트 중간에 데이터가 추가될 일이 없어보였고, 또 tail 변수를 만들어주어야 할 필요성을 느끼지 못해서 양방향 연결리스트가 아닌 단방향 연결리스트로 구현해주었습니다. 추후 확장성도 고려해봤을 때 양방향 연결리스트로 구현하는 것이 좋았을지 여쭤보고 싶습니다.

이런 경우 개발자들 사이에서도 의견이 나뉠 수 있는데, 개인적으로는 향후 반드시 사용되는 기능이 아니라면 구현하지 않는 방향이 좋다고 생각합니다. 좋게 표현하면 확장성, 나쁘게 표현하면 오버엔지니어링이니까요. 사용되지 않는 인터페이스를 유지할 필요는 없을 것이고, 필요하다면 해당 시기에 기능을 확장해나가면 되지 않을까요? 개발자는 불필요하다고 판단된다면 여러분처럼 과감하게 구현하지 않는 결단력도 있어야 한다고 생각합니다.

>* 큐와 연결리스트의 기능이 같아보이는데 따로 연결리스트와 큐 타입을 만들어서 큐에서 연결리스트의 기능을 가져와서 사용하는 것이 이해가 가지 않았습니다. 그냥 큐에서 바로 연결리스트의 기능을 구현해주면 되지 않나? 라고 생각했었습니다.
>    * 찾아보니 큐는 구현 방법이 정의되어 있지 않은 자료형이고 연결리스트는 다음 데이터의 위치를 저장하는 방식인 자료구조기 때문에 따로 구현해줘야 함을 알게되었습니다! 저희가 생각한 것이 맞는지 궁금합니다.

물론 그렇게 구현해도 됩니다. 하지만 지금은 기능 명세에서 지정이 되어있으니 최대한 방향에 맞추어 구현해보는 것에 의의가 있다고 생각해요. 이렇게 구현했을 때의 장점은 여러분이 말씀하신 것처럼 큐를 구현하는 방법 (알고리즘)이 여러가지 존재하기 때문에 큐를 구성하는 알고리즘을 단위 테스트를 통해 검증할 수 있다는 것, 그리고 상황에 따라 더 높은 성능을 가지는 알고리즘으로 구현된 타입을 변경하며 사용할 수 있다는 장점이 있겠네요.

>* CustomerQueue를 구조체로 만들어 주었는데, 안에 쓰이는 Node 인스턴스는 클래스(참조타입) 입니다. 이렇게 만들어줄 경우 CustomerQueue도 결국 참조타입이 되는 것인지 궁금합니다.

내부 프로퍼티 타입의 성질에 따라 그것을 가진 타입의 성질이 결정되지는 않습니다. 하지만 값 타입이 참조타입을 가질 경우 값 타입이 복사될 때마다 값 타입 내부의 참조 타입 인스턴스가 불필요하게 복사되는 경우가 발생할 수 있습니다.

![image](https://user-images.githubusercontent.com/69730931/176368201-7a1b0199-c297-4747-969c-f9b43f9151b6.png)

- [Understanding Swift Performance - WWDC16](https://developer.apple.com/videos/play/wwdc2016/416/?time=893)

자세한 내용을 학습해보시기를 희망하신다면 위 링크 13분 30초부터의 내용을 참고하세요.

# 유닛 테스팅 번들 Target과 Scheme 관련 참고사항

## 유닛 테스팅 번들 타겟 구성
현재는 유닛 테스트를 위한 타겟을 타입 단위로 생성하시고 계시는 것으로 확인했어요.
![image](https://user-images.githubusercontent.com/69730931/176370139-7eb9fd05-8d5c-4efa-8ca9-92662f465bfb.png)

이후 활동학습에서 Project, Target, Scheme과 관련해서 학습을 하시겠지만, 현재는 로직이 프로젝트 또는 타겟 단위와 같은 모듈로 구성되는 것이 아니라면 테스팅 번들 타겟을 하나로 가져가도 좋을 것 같습니다. 이런 경우 테스팅 타겟의 이름은 일반적으로 `모듈+Tests`라고 짓습니다 (`BankManagerConsoleAppTests`). 물론 더 좋은 이름이 있다면 사용해도 괜찮아요.

## 추가 참고사항 (`Scheme`에서 테스트 대상 지정 방법)
`LinkedListTests`를 `BankManagerConsoleAppTests`라고 가정하겠습니다.

Choose Scheme > LinkedListTests 선택 > Edit Scheme...

![image](https://user-images.githubusercontent.com/69730931/176373259-7f1d5bd7-2e98-480b-92c8-f6a4ee3efe53.png)

좌측 Test 탭 > 상단 Info 탭 > 좌측 하단 + 버튼 선택

![image](https://user-images.githubusercontent.com/69730931/176373477-f9d5ce6e-4bba-4f67-b74e-f5a541c12c04.png)

모든 유닛 테스팅 번들 타겟을 선택 후 추가 버튼 선택 > Close

![image](https://user-images.githubusercontent.com/69730931/176373585-2b4ed0b2-c8de-41f7-b150-4d22e3fa3783.png)

선택된 `Scheme`에서 `Command + U` 단축키를 실행하면 모든 유닛 테스팅 번들 타겟이 실행되는지 확인

## 추가 참고사항 (타겟별 `Scheme` 나누기)
타겟을 여러개로 나누셨다면 빌드와 실행의 단위가 되는 `Scheme`을 나눠주셔야 합니다. 그렇지 않으면 해당 타겟을 빌드할 수 없어요. 다른 방법으로 하나의 `Scheme`에서 복수의 타겟을 함께 빌드할 수 있도록 `Scheme`에 타겟을 포함하는 방법이 있습니다. 

현재 `Scheme`은 아래와 같이 구성되어 있는데, 이 경우 여러분이 의도하신 것처럼 `NodeTests` 타겟과 `CustomerQueueTests`만을 대상으로 빌드를 할 수 없습니다.

![image](https://user-images.githubusercontent.com/69730931/176370696-b1e81a12-6e83-452f-8128-f33e2dda5cc3.png)

`Scheme`을 생성하는 방법은 Choose Scheme... > New Scheme... > 타겟 선택 > OK 순서로 진행하시면 됩니다.

![image](https://user-images.githubusercontent.com/69730931/176371791-0745c72c-c501-4793-b84b-8ef5551277d1.png)

![image](https://user-images.githubusercontent.com/69730931/176371865-90771bad-56a2-43ee-92dc-cb3ab98986ac.png)

![image](https://user-images.githubusercontent.com/69730931/176371914-070f6e64-3ebf-47b0-9640-420795a0dcfc.png)

타겟을 대상으로 `Scheme`을 생성하여 테스트 대상에 자동으로 추가된 모습을 `Edit Scheme` 탭에서 확인하실 수 있습니다.

![image](https://user-images.githubusercontent.com/69730931/176372259-39d5fc13-e09c-4846-85d5-d78573875603.png)

Target과 Scheme 구성은 회의실에서 만나서 한 번 이야기 나누도록 해요.

고생 많으셨습니다! 궁금한 점 있으시면 말씀해주세요~

2022-06-29 11:23 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +    var queue: LinkedList<T>
queue의 접근제어자를 private(set) 으로 변경 해주었습니다. 여기서 궁금한 점이 생겼습니다. 
```swift
struct CustomerQueue<T> {
    private(set) var queue: LinkedList<T>
~ // code
~
}
```
```swift
class CustomerQueueTests: XCTestCase {
    var sut: CustomerQueue<Int>!
    
    override func setUpWithError() throws {
        try super.setUpWithError()
        sut = CustomerQueue(queue: LinkedList())
    }
~ // code
~
}
```
CustomerQueueTests 코드에서 CustomerQueue를 초기화 시켜줄 때, memeberwise initializer를 통해 queue에 값을 넣어주게 되는데, 이 경우는 set에 해당하는 것이 아니어서 접근제어자가 private(set) 임에도 불구하고 값 설정이 가능한 것 일까요?

2022-06-30 08:38 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +struct CustomerQueue<T> {
Queue 프로토콜을 생성하여, CustomerQueue 구조체에 적용 시켜주었습니다! 오늘 배웠던 POP방식을 사용하여 큐를 생성해볼 수 있어서 좋은 경험이 되었습니다 ㅎㅎ 구조 변경에 따른 테스트코드도 함께 수정 하였습니다!

2022-06-30 08:40 UTC, yeeton37 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +    var queue: LinkedList<T>
```swift
struct CustomerQueue<Customer>: Queue {
    private(set) var queue: LinkedList<Customer>
    init(elements: [Customer] = []) {
        queue = LinkedList()
        elements.forEach {
            self.enqueue(data: $0)
        }
    }
}
```
```swift
func test_큐에값을2개넣어줄때_peek을하면_첫번째값이반환되는지() {
        // given
        let firstValue = Customer(number: 3)
        let secondValue = Customer(number: 7)
        sut = CustomerQueue(elements: [firstValue, secondValue])
        // when
        let result = sut.peek
        // then
        XCTAssertEqual(firstValue, result)
    }
```
위와 같이 CustomerQueue에 initializer를 생성해주어 테스트 코드에서 한번에 값을 넣어줄 수 있도록 변경해주었습니다!

2022-06-30 08:43 UTC, yeeton37 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +    }
```swift
var isEmpty: Bool {
        head == nil
    }
```

`head == nil` 자체가 Boolean 타입을 반환하고 있는 것을 확인하고 위와 같이 변경해주었습니다! 매우 직관적이고 깔끔하네요 ㅎㅎ

2022-06-30 08:49 UTC, yeeton37 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/LinkedList.swift
> +        }
```swift
func append(data: T) {
        if head == nil {
            head = Node(data)
        } else {
            var node = head
            
            while node?.next != nil {
                node = node?.next
            }
            node?.next = Node(data)
        }
    }
```
if문에서 return으로 탈출하고 else를 사용하지 않는 방식과 if-else를 사용하는 방식에 대한 의견이 분분하여 고민했었는데, 정답은 없다고 생각하여 위와 같이 변경해주었습니다!

2022-06-30 08:51 UTC, wongbingg commented on BankManagerConsoleApp/CustomerQueueTests/CustomerQueueTests.swift
> +    func test_초기상태일때_dequeue를하면_nil이반환되는지() {
말씀주신대로 test케이스 네이밍을 수정 하였습니다!

2022-06-30 08:53 UTC, yeeton37 commented on BankManagerConsoleApp/CustomerQueueTests/CustomerQueueTests.swift
> +    func test_초기상태일때_isEmpty의반환값이true인지() {
수행할 수 있는 기능 정의서처럼 표현하기 위해 더 일반적인 표현을 사용하면 좋다는 점은 처음 알게되었네요!🚀  라이언의 말씀에 따라 더 일반적인 표현인 `test_큐의요소가비어있을때_dequeue를하면_nil이반환되는지`, `test_큐에값을3개넣어줄때_dequeue를하면_첫번째값이_제거되고반환되는지` 와 같이 테스트 코드 메서드를 변경해주었습니다!

2022-06-30 08:54 UTC, yeeton37 commented on BankManagerConsoleApp/CustomerQueueTests/CustomerQueueTests.swift
> +        sut.enqueue(data: 7)
위에서 달아주신 코멘트 부분 참고하여 동일하게 고쳐주었습니다!

2022-06-30 08:59 UTC, yeeton37 commented
라이언, 정말 섬세한 리뷰 감사드립니다!
많은 도움이 되었습니다,,ㅠㅠ
디코에서 말씀해주신 내용과 달아주신 코멘트 모두 적용하여 리팩토링 완료했습니다🚀🚀

2022-06-30 10:38 UTC, ryan-son approved these changes
예톤, 웡빙! 고생 많으셨습니다.

# `Code Coverage`
테스트에 관심이 많아보이셔서 `Code Coverage`라는 기능을 소개해 드릴게요. `Code Coverage`는 테스트를 통해 검증된 코드 범위를 나타낸 것으로, 테스트 중 한 번이라도 실행되었다면 테스트를 통해 코드가 검증되었다고 판단할 수 있어요.
오늘 회의실에서 이야기 나눈 `Scheme`에서 설정하실 수 있어요.

1. Edit Scheme...
<img width="259" alt="image" src="https://user-images.githubusercontent.com/69730931/176653590-7c257f25-1a82-4c9d-8a82-5afcb56906c6.png">
2. Test 탭 선택 > Options 탭 선택 > Gather Coverage for 체크박스 on > 수집 타겟 범위 all targets 선택
<img width="931" alt="image" src="https://user-images.githubusercontent.com/69730931/176655704-14dadb66-920c-46e0-818b-b3ffbfda8ae8.png">
3. 테스트 실행
4. Xcode 좌측 상단 Report Navigator에서 마지막으로 수행한 테스트의 Coverage 선택
<img width="296" alt="image" src="https://user-images.githubusercontent.com/69730931/176654817-88bfc3e9-707e-4806-9a62-eb0c8c9a0b71.png">
5. 파일/메서드/프로퍼티별 코드 커버리지를 %로 확인 가능
<img width="584" alt="image" src="https://user-images.githubusercontent.com/69730931/176655874-8913c20a-1875-4829-9f1f-8728089ead8f.png">
6. 개별 파일로 이동하면 어떤 코드가 몇 번 실행되었는지와 테스트에서 커버되지 않은 구간 확인 가능
<img width="595" alt="image" src="https://user-images.githubusercontent.com/69730931/176656107-1e1dc56f-e3a5-4dee-b82d-e737ac79c306.png">

올바른 방식으로 테스트가 짜여져있을 경우 코드 커버리지가 높다는 것은 코드에 신뢰성이 있다는 것을 의미합니다. 개발자라면 코드 커버리지를 높이기 위해 노력해야하는 것은 맞지만, 저희는 코드 커버리지만을 위해 개발을 하는 것은 아니니 단순히 코드 커버리지를 높이는 것만을 중시하여 테스트를 구성하지는 않아야 합니다. 물론 코드 커버리지가 높다는 것이 더 좋은 제품임을 보증하는 것은 아니니 커버리지 % 수치 자체에 연연하시지 않으셨으면 좋겠습니다.

# 불필요 Scheme 제거
더 이상 활용하지 않는 `LinkedListTests`가 Scheme에 포함되어 있네요. 제거해도 괜찮을 것 같습니다.
<img width="245" alt="image" src="https://user-images.githubusercontent.com/69730931/176657265-57a76f5a-5c7b-4ab5-a076-09031f46e645.png">

Step 1 요구사항을 훌륭이 수행하셔서 머지하도록 하겠습니다.

다음 스텝에서 만나요~ 👋

2022-06-30 10:38 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/CustomerQueue.swift
> +    private(set) var queue: LinkedList<Customer>
[P2]
`queue`가 `Customer` 타입을 다루도록 명시하고 있으니 `CustomerQueue`는 제네릭 형태가 아니어도 괜찮을 것 같아요.

2022-06-30 10:38 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Queue.swift
> +    associatedtype Element
`associatedType`는 어떤 역할을 수행하나요?

2022-06-30 10:38 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Queue.swift
> +    var currentList: [Element?] { get }
프로토콜에서는 왜 `let`을 사용할 수 없을까요?

2022-06-30 10:38 UTC, ryan-son commented on BankManagerConsoleApp/CustomerQueueTests/NodeTests.swift
> +
공백이 생겼네요~

2022-06-30 10:39 UTC, merged

2022-07-01 01:43 UTC, yeeton37 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Queue.swift
> +    associatedtype Element
`Associated Type`은 프로토콜의 일부로 사용되는 타입을 위한 placeholder 역할을 합니다. `associated type`은 정의하는 프로토콜이 채택되기 전까지 실제 타입이 명시되지 않는 것으로 알아보았습니다!

2022-07-01 01:51 UTC, yeeton37 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Queue.swift
> +    var currentList: [Element?] { get }
프로토콜은 어느타입에서나 청사진의 역할을 해야 하므로 프로퍼티를 정의하거나 저장해서는 안되고, 구현하는 곳에서 유동적으로 값을 결정할 수 있도록 해야하므로 변수로 선언하는 것으로 생각됩니다!

2022-07-01 01:56 UTC, yeeton37 commented on BankManagerConsoleApp/CustomerQueueTests/NodeTests.swift
> +
앗 그러네요..! 없애주었습니다!