은행 창구 매니저 [STEP1] 휴, 보리사랑
yagom-academy/ios-bank-manager pull request #190
Opened 2022-06-28 10:20 UTC by yusw10

@kcharliek 
안녕하세요 찰리! 
은행창구 매니저 STEP1 리뷰 잘 부탁드립니다....!

## 구현 기능 및 작업내용
- Cocoapods를 사용하여 SwiftLint 라이브러리를 적용
- 양방향 연결 리스트 구현을 위한 노드 구현
  - 노드 내부에는 데이터 및 이전 노드와 다음 노드를 가리키는 프로퍼티 생성
  - 데이터는 Generic타입
- 양방향 연결 리스트를 통해 큐 구현
  - Node타입의 head와 tail로 내부 요소에 접근
  - 명세서에서 요구한 enqueue, dequeue, isEmpty, clear, peek 메서드 구현
- 연결 리스트의 테스트 코드 작성

<br>

## 고민한 점

### 큐를 구현할 타입 
- 연결리스트와 이 리스트의 노드를 구현함에 있어서 이들을 Class와 struct 둘중 어느것으로 해야할지 고민 했습니다. 
- **노드 -> Class**
  - 내부에 이전 노드와 다음노드의 주소를 저장해야하는데 이 프로퍼티들이 구조체로 구현할 경우 본인과 같은 타입을 참조할 수 없게 되어있어서 노드를 class로 구현하였습니다. 
 
- **CustomerQueue -> Class**
  - class와 struct의 차이점에 대해 이야기 하면서 데이터를 저장하는 타입은 struct로 구현하는것이 좋다고 알고 있었습니다. 다만 이번 프로젝트의 queue의 메서드들은 내부 프로퍼티를 수정할 경우가 많다고 판단했습니다(head 및 tail값 변경). 이럴경우 메서드들을 mutating으로 처리해주어야 하는데 mutating은 지양하는것이 좋다고 들어(값을 새로 만들어 덮어씌우는 방식이므로 비효율적) mutating을 쓰는것 보다는 class로 구현하는것이 좋다고 판단했습니다.

<br>

## 궁금한 점 

### 연결 리스트 타입과 CustomerQueue의 차이점. 
![](https://i.imgur.com/BXFwUeo.png)

프로젝트 명세에는 위와같이 Queue 타입 구현을 위한 Linked-list를 구현하라고 명세가 되어있습니다. 저희는 **'Queue를 연결리스트로 구현하면 되겠구나'** 라고 생각하여 현재의 코드로 작성을 해보았습니다. 다만 다른 캠퍼들의 경우 연결리스트를 구현하고 이 연결리스트를 소유하고 그대로 메서드를 사용할 뿐인 큐를 하난 더 만드는 방식으로 진행하는걸 확인했습니다. 
```swift 
func dequeue() -> data {
    return self.linkedList.pop()
}
```
<br>

위 코드처럼 연결리스트로 구현한 코드를 그대로 사용하는 방식인데 이렇게 하면 굳이 불필요한 데이터타입을 작성한 것이라고 생각했습니다. 

연결리스트와 큐타입을 구현함에 있어서 타입은 분리를 진행하는게 좋은 방법일까요?

### 테스트 방법에 관하여 
- `CustomerQueue`타입의 테스트를 진행하던 중 `XCTAssert`의 기능으로는 인스턴스끼리의 비교를 할 수 없었습니다. 이를 위해서는 Equtable을 상속받아 직접 비교하는 로직을 구현해야함을 확인했습니다. <br>
이렇다 보니 내부의 data를 임의로 비교하여 동작을 확인하거나, isEmpty를 사용하여 `enqueue`와 `dequeue`를 테스트하게 되었는데 맞는 방법인지 아직 잘 모르겠습니다. 
이렇게 사용자 정의 타입을 테스트 할 때 어떤식으로 진행하시는지 궁금합니다... !

### 연결 리스트
- 이번 프로젝트 명세서를 보면 연결 리스트의 장점을 활용하지 못한다고 생각합니다. 명세서에서 연결 리스트를 활용해 큐를 구현하라고 나와있어 양방향 연결 리스트를 이용해 큐를 구현했습니다. 연결 리스트를 이용해야 하는 이유가 궁금합니다.(배열을 사용하면 내부 메서드를 이용해 dequeue, isEmpty, enqueue도 쉽게 구현이 가능할 거라 생각합니다.)
[본심1 : 솔직히 왜 연결 리스트로 구현해야 하는지 이유를 찾지 못했습니다...😭]
[본심2 : 단방향 연결 리스트는 한번 구현해 본 적이 있어 공부를 위해 양방향 연결 리스트로 구현했습니다.]

![](https://i.imgur.com/rtKIhzO.png)

2022-06-29 14:38 UTC, kcharliek commented
## 궁금한 점에 대해

1. 연결리스트 방식으로 Queue 구현 vs 연결리스트를 이용해서 Queue를 구현

지금과 같은 경우 큰 차이가 없을 것 같기는 합니다만,
연결리스트의 재사용을 고려한다면 연결리스트를 구현하고 이를 이용해서 Queue를 구현하는 것이 좋겠죠~
그리고 그렇게 했을 때 연결리스트 고유로직과 Queue의 고유 로직을 분리할 수 있어서, 파일이 가벼워지고 읽기에 수월하다는 점이 있겠네요~
그런데 이런 식의 분리는 때로는 오버엔지니어링을 만들기도 합니다~ 이 과제의 경우 어느 것을 선택해도 괜찮다고 생각합니다.

2. 테스트 관련해서

인터페이스(메서드, 프로퍼티 등)가 열려있지 않은 상황에서 테스트를 해야할 때가 있습니다.
그럴 때에는 말씀주신 isEmtpy라던지, 지금 테스트를 작성하신 것 처럼 dequeue를 이용해서 enqueue를 테스트해야해요.
저는 이걸 '간접적인 테스트다' 라고 말하고있습니다. 지금 작성하신 테스트 아주 잘 해주셨어요.
A 기능을 테스트하기 위해 A메서드의 동작을 검증하기는 사실 어려워요. 그리고 테스트를 위해 data 접근을 오픈하는 것도 무리가 있고요.
그러니 지금 작성하신 것 처럼 해주시면 됩니다 :)
정확히 답변이 됐는지 모르겠습니다. 더 궁금하신 내용이 있으시면 discord 주세요~! 

3. Queue를 왜 연결 list로 구현해야하는가 ..

array vs linked list 는 다른 문서를 보시는것이 나으실 것 같고요.  https://stackoverflow.com/questions/7477181/array-based-vs-list-based-stacks-and-queues

어떤 구현이든 트레이드오프가 있겠죠~ 그 때 그 때 상황 마다 어떤 선택이 더 나은가에 대해서는 정답이 없는거같아요.
성능이 항상 좋다고 해서 선택되는 것도 아니고요. 쉽게 개발할 수 있다고 해서 선택되는 것도 아니고요.
상황에 맞게, 시간이 없다면 빠르게 개발할 수 있는걸로. 시간 여유가 있다면 조금 걸려도 나은 성능을 보여주는 것으로.
유지보수가 중요하다면 비교적 읽기 쉬운 로직으로. 등등의 기준으로 선택할 수 있겠네요~

2022-06-29 14:49 UTC, kcharliek requested changes
1. dequeue, enqueue, peek만 남기기
2. Node 숨기기

위 두 내용 반영부탁드립니다~

2022-06-29 14:49 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +final class CustomerQueue<T> {
이름이 CustomerQueue 일 필요는 없어보여요.
보리와 휴가 구현하신 건 Queue고, 쓰는 쪽에서 Customer 전용으로 쓰는거니까요~
쓰는 쪽에서 variable naming을 customerQueue로 하고, 이쪽 구현은 Queue가 적당해보입니다~

2022-06-29 14:49 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private(set) var head: Node<T>?
https://docs.oracle.com/javase/7/docs/api/java/util/Queue.html

enqueue, dequeue, peek 을 제외하고 다른 인터페이스 전부 숨겼으면 합니다~
우리는 Queue라는 아주 대표적인 자료구조를 만드는거니까요~ 
정석을 따랐으면 해요~

2022-06-29 14:49 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    func enqueue(inputNode: Node<T>?) {
enqueue 대상은 Node가 아니라 T가 되어야합니다.

Node, Linked-List 는 구현 방법이지 사용 방법이 되어서는 안되어요.

Queue를 쓰는 사람은 내부가 어떻게 구현되어있는지 관심이 없습니다.

그저 Queue답게, 데이터(T)를 넣고싶을 뿐이에요~

2022-06-30 07:05 UTC, Hugh-github commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private(set) var head: Node<T>?
clear를 private으로 처리해 외부에서 접근하지 못하도록 하였습니다.

찰리가 주신 문서를 보면 java같은 경우 clear 메서드를 상위 클래스에서 상속받아 사용이 가능한 것 같은데 그렇다면 저희도 해당 메서드를 사용해도 되는 게 아닌지 궁금합니다... 
아니면 이번 프로젝트 특성상 모든 은행 업무가 종료되는 시점에는 대기열이 비어있기 때문에 clear를 사용할 일이 없을 것 같다는 생각을 해봤습니다.

2022-06-30 07:05 UTC, Hugh-github commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    func enqueue(inputNode: Node<T>?) {
enqueue와 dequeue의 파라미터와 반환 타입을 입력하고 싶은 데이터 타입(제네릭 타입)으로 변경해주었습니다.
그 과정에서 enqueue 메서드는 Node를 생성해서 데이터를 담는 역할을 하고 있습니다. enqueue 메서드명 그대로 데이터만 넣고 싶은데 Node 까지 생성하다 보니 어색하다는 느낌을 받았습니다. 그래서 저희는 Queue 자체에서 Node를 생성하는 메서드를 따로 분리하는 방법과 다른 타입에서 노드를 만들어 저희가 만든 큐에 노드를 넘겨주는 방식을 고민해 봤습니다.

2022-06-30 07:11 UTC, kcharliek commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +    private(set) var head: Node<T>?
java에서 구현했다면 그렇게 하셔도 되어요~~

2022-06-30 07:12 UTC, kcharliek commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +        sut.enqueue(inputData: firstData)
👍

2022-06-30 07:13 UTC, kcharliek commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +    var firstData: Int!
data를 array로 선언했어도 좋았겠어요~

2022-06-30 07:13 UTC, kcharliek approved these changes
아주 잘 해주셨습니다 :)

2022-06-30 08:12 UTC, merged