은행 창구 매니저 [STEP2] 현이, 그루트
yagom-academy/ios-bank-manager pull request #192
Opened 2022-06-30 10:04 UTC by Groot-94

@GREENOVER 안녕하세요 그린! 🍀
현이@seohyeon2 와 그루트@Groot-94 입니다! 🧏‍♂️
Step 2 PR 보냅니다! 이번 프로젝트 잘 부탁드립니다!
## 📌 배경
- 은행 창구 매니저 앱
- 고객 타입 및 업무를 처리하는 타입 구현
## 📌 작업 내용
### Bank
- 은행 전반적인 업무를 담당하는 타입을 구현했습니다.
### BankManager
- 은행 업무를 수행하는 타입 구현을 구현 했습니다.
### Customer
- 고객 타입을 구현했습니다.    
## 📌 테스트 방법
- `main` 파일을 실행하여 테스트 
## 📌 리뷰 노트
#### POP와 OOP 중 어떤 방식으로 구현할지 고민을 했습니다. 
- 결국엔 아직 POP에 익숙하지 않고 타입을 어떤 식으로 나눌지에 대한 정리가 되지 않아서 OPP 방식으로 구현했습니다. 만약 그린이 POP의 방식으로 구현한다면 어떤 식으로 타입을 나누실지 궁금합니다.

2022-06-30 18:54 UTC, GREENOVER requested changes
@Groot-94 @seohyeon2 
두분 스텝2 구현 너무 고생 많으셨습니다!
은행 매니저가 이제 로직적인 부분을 많이 생각해보고 또 객체지향적인 부분에서도 근간을 요하는 좋은 프로젝트이자
어떻게 보면 처음 접하다보니 머리가 아플 수 있는 프로젝트인데 아주 잘 해주셨어요👍
스텝2에서 사실 많은 코드가 필요하거나 그런 부분이 없지만 은근 신경써줘야할 부분들이 있어요.
예를들어 타입을 어떻게 관심사별로 나눠서 역할을 부여할지 같은것들에서요ㅎㅎ
이번 리뷰 코멘트는 대부분 그쪽에 초점을 맞춰서 드려보겠습니다!
이번 스텝에서는 정말 타입 추상화 및 일반화 요것만 부셔보면 충분해서요🙌
***
### 칭찬 드리고 싶은 부분
- 일정을 아주 빠르게 잘 소화해주시고 또 간결한 코드였습니다 💯
- 리드미에서 감탄하고 갑니다 💯
- 전체적으로 메서드 및 프로퍼티 네이밍 작문 실력이 향상되신것 같아요 💯
- Bank, BankManager 등 역할을 구분지어 객체지향스럽게 첫걸음을 잘 나아가신점 💯
***  
### 리뷰노트에 요청하신 궁금하신 부분에 대한 저의 의견
- POP와 OOP 중 어떤 방식으로 구현할지 고민을 했습니다.
  - 우선 여러분들이 POP 방식으로 하려는 이유와 왜 그 방식이 어떤면에서 좋은 이점을 가지고 있는지 파악하신 의견이 궁금합니다🙋🏻
  그것과 별개로 대게 POP 방식처럼 구현하려면 여러분이 리뷰노트에 써주셨던것처럼 타입을 확실히 정의하고 해당 타입에서 어떤 역할을 공통적으로 가지고 있는지만 확고해지면 아주아주 쉽게 프로토콜을 만들어 채택해서 사용하실 수 있을거에요.
  예를들어, 현재로써는 BankManager라는 타입만 있는데 예를들어 은행에 은행원 말고 경비원도 있을수 있고 미화원도 있을 수 있을거에요.
  그럼 해당 타입들의 공통점은 `work` 일을 하는것이죠.
  그렇다면 work라는 메서드를 가진 `BankEmployee` 프로토콜을 만들 수 있을것 같아요.
  work를 넘어 모든 타입에 해당하는 공통적인 프로퍼티나 메서드가 있다면 충분히 해당 프로토콜에 담아 우리는 각 직업 타입을 구성하면서 해당 프로토콜을 채택하고 프로토콜에서 정의된 work라는 메서드를 구현해주면 될거에요.
아주 단순하게 설명은 했지만, 여러분도 이미 알고 있던 개념일 수도 있지만..! 그게 다입니다🥲
어려운것이 아니라 더 딥하게 설명하기가 힘드네요..! 여러분들이 지금 타입을 어떤식으로 추상화 시킬지가 딱 정해지지 않아서 아마 POP 적용이 어려웠다고 생각되고 우선 타입을 조금 더 딱 관심사별로 추상화를 먼저 설계하면 좋을것 같습니다ㅎㅎ
***
### 개선되면 좋을 부분에 대한 저의 의견
1. 타입 설계
- 코멘트에도 남겼지만 각 타입이 하는 역할 즉 관심사에 대해 한번 다시 고찰해보면 어떨까합니다🙋🏻
이 타입이 콘솔뿐 아니라 UI에서도 쓰일 수 있을것이고 무궁무진할텐데 현재는 딱 요구사항에만 맞춰진 타입으로 보여져요.
조금 더 넓고 멀리봐서 기본으로 돌아가 OOP에서 타입이란 즉 객체란 무엇인지 돌이켜보고 현재로써의 타입이 본인의 역할이 아닌 다른 부분까지도 관심사를 다 끌어안지 않았나 한번 되짚어보면 도움이 될것 같습니다🙋🏻
2. 테스트 코드의 실패 케이스
- 현재 테스트 코드 너무너무 잘 짜주셨는데 다 성공 케이스인것 같아요..!
실패를 하는 상황들을 케이스로도 만들고 검증해보면 어떨까요?
***
두분 스텝2 하느라 옆에서 아주 아주 잠깐이지만 열심히 하시는걸 봐서 더 대단하다고 생각듭니다ㅎㅎ
언제든 이해가 안가는 코멘트 및 의견에 대해 여쭤보셔도 됩니다!
한번 전체적으로 되짚는다 생각하고 리팩토링 해보면 좋을것 같아요🙌
화이팅입니다..!!

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +import Foundation
import할 필요가 있을까요~?🙋🏻
만약 필요없다면 왜 필요 없을까요?

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +		05FB96F4286DA15D001D5B7B /* BankStatus.swift in Sources */ = {isa = PBXBuildFile; fileRef = 05FB96F3286DA15D001D5B7B /* BankStatus.swift */; };
현재 모든 파일이 BankManagerConsoleApp의 폴더 안에서 같은 계층 구조를 가지고 있어서 점차 파일이 늘어날수록 헷갈릴 여지가 많아 보입니다🤔
각 관심사별로 폴더 그룹화를 시켜주면 어떨까요?🙋🏻

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +bank.execute(totalCustomerCount: Int.random(in: 10...30), workTime: 0.7)
현재 구조로는 은행 개점하여 일을 처리한 후 다시 "1"을 입력받아 은행개점 업무를 처리하여도 매번 초기 랜덤으로 들어갔던 고객수가 유지될것 같아요..!
메인에서는 execute만 시켜주고 랜덤한 고객 수를 만들고 하는 과정을 Bank 내부 혹은 별도의 콘솔 매니저를 두어 처리해줘야 정상 기능 동작을 만족시키지 않을까 싶습니다🙋🏻

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    menuLoop:
해당 코드가 필요한것과 택하신 이유가 궁금합니다🙋🏻

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private func executeWork(_ totalCustomerCount: Int, _ workTime: TimeInterval) {
언더스코어 사용도 좋지만 현재의 메서드 시그니쳐만 봐서는 사용부에서 읽어볼때
`excuteWork totalCustomerCount workTime`으로 직역을 그대로 해보면 `업무를 실행하다 전체고객수 일 시간` 처럼 해석이 될것 같아요.
여기서 중요한것은 파라미터의 모든것 자체를 메서드 시그니쳐로 볼 수 있으며 이는 자연스럽게 읽힐 수 있도록 구성하는게 좋습니다!
그래서 제가 추천드리는건 이럴 경우 전치사 label을 붙이면 어떨까해요.
예를들어 `work(during workTime: Int)`처럼 (제가 만든겁니다 코드와 상관없어요..!)
직역하면 "일을한다 xx시간동안"처럼 전치사가 있다면 뒤의 파라미터와 어떤 연관이 있으며 메서드 시그니쳐만 보고 해당 메서드가 할 일을 유추하기가 더욱 편리하겠죠?

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            }
dequeue 시 에러를 throw했을때 여기서 받을것 같은데 별도의 콘솔에서의 안내 및 처리 없이 빠져나가게 될텐데 괜찮을까요~?🙋🏻

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                customerQueue.enqueue(data: Customer(name: "\(number + 1)번"))
고객의 데이터를 집어넣어주는것은 해당 메서드의 관심사와 조금 다르다고 생각해요🙋🏻
해당 메서드는 excuteWork로 딱 은행업무 처리만 해줘야하지 않을까 싶어요.
즉 고객의 수를 받아서 enqueue 해주는 이런 역할을 Bank가 이닛될때 별도 private한 메서드를 구성해서 그쪽에서 처리해주는게 관심사가 맞지 않을까 싶습니다🤔

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func execute(totalCustomerCount: Int, workTime: TimeInterval) {
해당 메서드의 역할을 Bank가 해주는게 맞을까요?
왜냐하면 Bank는 딱 은행 업무만을 해줘야할것 같아요.
1, 2 입력을 받거나 콘솔에 어떤 print 구문을 찍어주는것 자체는 Bank가 할일이 아닌 Console이 할일이라고 보여집니다.
이렇게 된다면 Bank는 Console에서만 사용되는 타입이 될 것이고 범용적인 객체가 되지 않습니다🥲
즉 OOP의 근간에서 벗어나게됩니다.
저는 콘솔을 다룰 수 있는 ConsoleManager 같은 타입을 하나 별도로 만들어 main에서 해당 타입을 호출하는것을 추천드립니다🙋🏻

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private func printStartMessage() {
요 메서드도 어떻게 보면 Bank가 할일이 아닌 콘솔에서 할일로 보여질 수 있을것 같아요🙋🏻
요점은 Bank는 딱 Bank일만 할 수 있도록 구성하는게 좋을것 같습니다!

2022-06-30 18:54 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func removeAt(index: Int = 0) -> T? {
기본값 사용 좋네요👍

2022-06-30 18:54 UTC, GREENOVER commented on README.md
> +# 은행 관리 매니저
리드미 진짜 최곤데요!?
바로 포폴로 써도 될만큼 틀 너무 잘 잡아주셔서 어후.. 완성도 있는 리드미 아주 잘 봤습니다ㅎㅎ
분명 곧 여러분들의 무기이자 장점으로 돌아올거에요👍👍

2022-07-01 04:44 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +import Foundation
import 할 필요 없어서 삭제했습니다😌
Foundation 프레임워크안에 있는 것들을 사용하지 않아서 필요 없습니다..ㅎㅎ

2022-07-01 06:32 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private func printStartMessage() {
Bank일만 할 수 있도록 해당 메서드는 `ConsolManager` 타입 안에 넣어주었습니다

2022-07-01 06:35 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +		05FB96F4286DA15D001D5B7B /* BankStatus.swift in Sources */ = {isa = PBXBuildFile; fileRef = 05FB96F3286DA15D001D5B7B /* BankStatus.swift */; };
특성을 생각해서 나눠봤습니다!

[912fe8c](https://github.com/yagom-academy/ios-bank-manager/pull/192/commits/912fe8ce87c97cd9b6931544c69c2f370215f415)

2022-07-01 06:36 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +bank.execute(totalCustomerCount: Int.random(in: 10...30), workTime: 0.7)
ConsolManager 라는 타입을 만들어서 메뉴 출력이나 사용자의 선택을 입력받도록 수정했습니다 :)

[3f8098f](https://github.com/yagom-academy/ios-bank-manager/pull/192/commits/3f8098fe08a959e0f7bed4d1a4ad0960918157e6)

2022-07-01 06:40 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func execute(totalCustomerCount: Int, workTime: TimeInterval) {
그린 말씀처럼 `ConsoleManager` 타입을 별도로 만들어 `Bank` 가 좀 더 범용적인 객체로 사용되게 수정했습니다.

현재 `Bank` 에서 하는 일은 아래와 같습니다🥳
1. `enqueueCustomer()` : 은행에 온 고객들을 고객 대기열(`CustomerQueue`)에 추가함 .
2. `executeWork(workTime: TimeInterval) -> Int`: 대기열에 있는 고객들의 업무를 수행함.

2022-07-01 06:47 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                customerQueue.enqueue(data: Customer(name: "\(number + 1)번"))
해당 코드를 `enqueueCustomer()` 라는 메서드로 따로 만들어 준 뒤, 초기화 할 때 호출되도록 수정했습니다!

2022-07-01 06:50 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    menuLoop:
어떤 부분을 말씀하시는지 조금 헷갈려서  두가지에 대한 이유를 말씀드려보겠습니다..
1. `private var customerQueue = CustomerQueue<Customer>(linkedList: LinkedList<Customer>())` 
- 고객 대기열 관리를 큐에 넣어서 하라는 제약사항에 맞게 큐에 넣도록 구현해봤습니다. 의존성 주입으로 큐를 생성해주려고 하니, 기존에 리스트의 초기화를 의존성 주입을 이용했기 때문에 코드가 굉장히 길어져서 구조체 안에서 직접 호출하는 방식으로 구현해봤습니다.
2.  `menuLoop:`
- while을 이용해서 무한루프에 넣고 switch로 사용자의 입력을 구분하여 "2" 일 때 종료를 하도록 구현했습니다
- 이 부분에서 그냥 break를 사용하면 while 루프를 빠져나가지 않고 switch를 빠져나갑니다. 
- 그래서 결국 무한루프에 빠지기 때문에 `Labeled Statements 을 사용해서 while 루프를 빠져나가게 구현했습니다.`

2022-07-01 06:54 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            }
catch 문 실행 시, 고객이 없다는 안내문을 출력하도록 수정했습니다!

[3f8098f](https://github.com/yagom-academy/ios-bank-manager/pull/192/commits/3f8098fe08a959e0f7bed4d1a4ad0960918157e6)

2022-07-01 07:07 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private func executeWork(_ totalCustomerCount: Int, _ workTime: TimeInterval) {
해석을 들으니 전치사의 필요성을 더욱 느낍니다..!

현재 메서드 중에 전치사가 필요해 보이는 곳에 전치사를 추가했습니다!
스텝 3에서도 전달인자 레이블을 적극적으로 활용해보겠습니다☺️

[a358772](https://github.com/yagom-academy/ios-bank-manager/pull/192/commits/a35877213700ac0c6bdd3c4e4b9a79b70f49f19f)

2022-07-01 07:30 UTC, GREENOVER approved these changes
@Groot-94 @seohyeon2 
두분 너무 리팩토링을 잘해주셔서 코드 리뷰하기 수월했습니다👍👍
현재 스텝 2의 요구사항은 충분히 만족시켰기에 머지하겠습니다ㅎㅎ
조금 더 생각해볼 여지가 있는 부분들을 코멘트로 몇개 남겨봤습니다!
다들 금요일인데 스텝2까지 잘 해주시느라 고생 많으셨어요🙌
다음 스텝도 화이팅입니다🥳

2022-07-01 07:30 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private func enqueueCustomer() {
기능은 enqueue가 맞지만 네이밍은 조금 더 자연스럽게 해보면 어떨까요?
예를들어 setCustomer같이 대중적인건 어떨까해요.
실제로 고객을 셋팅해주는 역할을 하니까요🤔

2022-07-01 07:30 UTC, merged

2022-07-04 06:25 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +			path = Error;
앗.. 폴더 생성할 때 다른 곳으로 생성해버렸네요😅
BankManagerConsoleAPP 폴더안으로 Error 폴더 옮겼습니다!

2022-07-04 06:26 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +                print("고객이 없습니다.")
콘솔매니저는 출력을 담당하는 역할로 생각하여, 해당 부분도 콘솔매니저로 옮겨주었습니다!

2022-07-04 06:26 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        print("\(customer.name) 고객 업무 시작")
위와 동일한 이유로 수정하였습니다!

2022-07-04 06:27 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private func enqueueCustomer() {
추천 해주신 `setCustomer`으로 네이밍 수정했습니다.