은행 창구 매니저[Step2] 언체인, 백곰
yagom-academy/ios-bank-manager pull request #193
Opened 2022-06-30 13:29 UTC by unchain123

# 은행 창구 매니저 STEP2 PR
@jryoun1 
안녕하세요 제이크 생각보다 일찍 끝나서 PR보냅니다.
잘부탁드립니다.🙇‍♂️🙇‍♂️

## 코드설명
- BankManagerNameSpace : 프로젝트 전체적인 코드에서 리터럴값을 의미있는 값으로 변경해주고 유지보수에 용이하도록 했습니다
- BankManager : 은행개점 선택시 BankManager에게 업무를 넘겨 처리합니다
- Customer : 고객에 해당하는 구조체로써 대기번호표를 가질수있습니다
- Bank: 은행 구조체
    - bankBusinessStart() : selectBankOpenAndClose()함수의 재귀를 막고 은행 업무를 시작하는 함수
    - printBankInterface() : 은행업무가 시작하면 은행 개점과 종료를 프린트 하는 함수
    - makeCustomerWaitingList() : BankItemQueue에 Customer타입을 받아서 각 고객에 번호를 부여하고 대기열에 넣는 함수
    - reportWorkResult() : 총 업무시간을 계산해서 업무를 처리한 고객의 숫자와 함께 프린트 해주는 함수
    - selectBankOpenAndClose() : BankManagerConsoleApp 프로젝트 시작시 첫 인터페이스 및 ReadLine 의 입력값에 따라 switch 문이 작동하는 함수
    - numberFormatter() : 총 업무시간을 나타내는 시간을 소수점 아래 2자리수로 만들어 주기 위한 함수

## 고민한점
- Customer를 대기열에 넣기 위해 enqueue를 해서 프린트를 한 결과 `Customer(bankNumberTicket: 1)` 이렇게 출력이 되었습니다. 프린트문에서 데이터에 직접 접근 하지 않고 BankItemQueue에서 dequeue한 값에 접근해서 나온 결과 였습니다. 그래서 dequeue한값의 내부 값(bankNumberTicket)에 접근 하여서 해결 해주었습니다.

- 소숫점 아래 2자리까지만 표현 해주기 위한 방법을 찾아 보던 중 `String(format: "%.2f", 숫자)`를 사용하는 방법을 찾게 되었는데 이 방법은 정규식을 사용하는 것 같았는데 아직 정규식에 대해 명확하게 공부가 안되있기 때문에 사용하지 않으려고 했습니다. 그래서 numberFormatter를 사용했습니다. 여기서도 처음에 `significantDigits`를 사용하였더니 원하는 결과 값을 얻지 못했는데 바로 공식문서를 확인하지 않아서 이게 어떤 숫자를 나타내는지 파악 못했습니다. 이후에 유효숫자를 나타내는 메서드인걸 확인하고 FractionDigits를 설정해서 소수점 아래 2자리를 적용할 수 있었습니다.

## 궁금한점
- 코드를 지연 시키는 방법이 sleep,usleep 이 있다고 찾았습니다. sleep에 비해 usleep 같은 경우에는 좀더 세세한 시간 컨트롤이 가능해서 usleep을 채택하여 사용하였지만 좀더 나은 방법이 있는지 궁금합니다.

-  기능 요구서에서 은행 업무가 끝나고 나면 총 업무시간을 출력하는 부분이 있었는데 이때 업무 시간을 구하기위해 업무를 처리하는 함수인 handleBanking()메서드가 시작하고 끝나는 시간을 타이머로 받아서 해주어야 하는지 고민 했습니다. 하지만 업무처리에 0.7초씩 텀이 있도록 했지만 실제로 함수가 돌아가는 시간이 0.7초가 아니기 때문에 은행의 업무시간과는 의미가 맞지 않다고 생각하여 단순히 0.7 * 고객수를 업무시간으로 사용했습니다.
-  여기에 대해서 제이크의 의견이 궁금합니다.
![](https://i.imgur.com/Qi7tGyj.png)

2022-07-02 08:40 UTC, jryoun1 requested changes
@unchain123 @Baek-Gom-95 안녕하세요~ 🙋‍♂️
step2를 잘 진행해주셨군요! 고생하셨습니다. 

전반적으로 은행, 은행원, 손님의 역할에 대해서 다시 한 번 고민이 필요해 보입니다. 
코멘트에서도 남겨드렸지만, 지금 작성하신 코드에서는 은행이 없다면 손님과 은행원은 존재할 수 없을 것 같습니다. 즉, 손님과 은행원 객체가 은행과의 결합도가 높기 때문에 이를 해결할 필요가 있어보입니다.

은행, 은행원, 손님은 전부 각각 따로 객체로 존재하고 은행이 은행원과 손님을 주입받아서 은행의 업무를 처리하는 방향으로의 개선을 통해서 각 객체들의 결합도를 낮춰줄 수 있을 것 같습니다. 🙏🏻

### 궁금한 점에 대한 답변
> 코드를 지연 시키는 방법이 sleep,usleep 이 있다고 찾았습니다. sleep에 비해 usleep 같은 경우에는 좀더 세세한 시간 컨트롤이 가능해서 usleep을 채택하여 사용하였지만 좀 더 나은 방법이 있는지 궁금합니다.

코드를 지연시키는 방법은 sleep, usleep, Timer, dispatchSourceTimer, asyncAfter 등이 있을 것 같네요. 이번 프로젝트의 경우에는 크게 사용자의 input을 받는 것도 아니기 때문에 sleep, usleep을 사용해도 충분할 것 같습니다.
위의 경우들에 대해서는 한 번 알아보시면 좋을 것 같네요. 
추가로 async, sync / concurrent, serial에 대해서도 알아보면 도움이 될 것 같아요 (매우 중요한 개념)

> 기능 요구서에서 은행 업무가 끝나고 나면 총 업무시간을 출력하는 부분이 있었는데 이때 업무 시간을 구하기위해 업무를 처리하는 함수인 handleBanking()메서드가 시작하고 끝나는 시간을 타이머로 받아서 해주어야 하는지 고민 했습니다. 하지만 업무처리에 0.7초씩 텀이 있도록 했지만 실제로 함수가 돌아가는 시간이 0.7초가 아니기 때문에 은행의 업무시간과는 의미가 맞지 않다고 생각하여 단순히 0.7 * 고객수를 업무시간으로 사용했습니다.

일단 저의 개인적인 의견으로는 단순히 시간을 계산하는 것이 아니라 실제 작업 시간이라고 생각을 했어요. 그러나 예시로 봤을 때는 정확히 7.0으로 나오는 것을 봐서는 계산을 한 것 같아보이긴하네요 🤔
이 부분은 기획을 작성한 야곰에게 정확한 의도를 물어보고 결정해도 될 것 같습니다 🙏🏻

2022-07-02 08:40 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/NumberFormatter.swift
> +func numberFormatter(number: Double) -> String {
numberFormatter()라는 전역 함수를 생성해주셨는데, 전역함수로 만들어주신 이유가 있을까요? 

이 부분을 String의 extension으로 만들 수 있을 것 같아보입니다.
또 다른 방법으로는 BanKNumberFormatter 객체를 만들어서 매번 NumberFormatter()를 생성하지 않도록 하는 방법도 있을 것 같습니다. 
왜 매번 생성하는 것이 좋지 않은지에 대한 [글](https://sarunw.com/posts/how-expensive-is-dateformatter/)도 한 번 읽어보시면 좋을 것 같아요 🙏🏻

2022-07-02 08:40 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/NumberFormatter.swift
> +    let result = numberFormatter.string(for: number) ?? "\(SetNumber.failNumberFormatter.rawValue)"
변환에 실패하는 경우에는 0을 반환해줄 것 같은데, 다른 오류 처리가 필요하지 않을까요 🤔

2022-07-02 08:40 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankManagerNameSpace.swift
> +enum BankComent: String {
m이 하나 빠졌네요!

2022-07-02 08:40 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankManagerNameSpace.swift
> +//  BankManagerNameSpace.swift
BankMananger에서 사용될 수 있는 String들을 잘 모아두셨네요 👏

2022-07-02 08:40 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            bankBusinessStart()
기능서에는 없지만 다른 입력이 들어왔을 때 
`보여지는 메뉴 중에서 선택해주세요` 라는 안내가 사용자에게 보여진다면 더 좋을 것 같습니다 🙏🏻
(필수는 아닙니다!)

2022-07-04 05:26 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func printBankInterface() {
함수 순서는 프로젝트 흐름의 순서대로 나열했습니다

2022-07-04 05:28 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func printBankInterface() {
넵 private를 붙여 주었습니다.

2022-07-04 05:28 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func printReportWorkResult(handledCustomer: Int, handledWorkTime: String) {
여기도 동일하게 private를 붙여주었습니다.

2022-07-04 05:34 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let requestInput = readLine()?.trimmingCharacters(in: .whitespaces) ?? BankComent.emptyValue.rawValue
ReadLine 로직은 main 으로 옮겨주었습니다 😊

2022-07-04 05:48 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        var clerk = BankManager()
은행원을 Protocol로 만들어 주어서 은행에서 채택할 수 있도록 만들어서 의존성 주입을 해주 었습니다.

2022-07-04 06:09 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankManagerNameSpace.swift
> +enum BankComent: String {
m 붙여서 수정해주었습니다

2022-07-04 06:27 UTC, unchain123 commented on BankManager.swift
> +    mutating func handleBanking(customerList: BankItemQueue<Customer>) {
은행원이 고객리스트가 아닌 고객만을 상대하도록 변경하여 주었습니다.

2022-07-04 07:11 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/NumberFormatter.swift
> +func numberFormatter(number: Double) -> String {
저희는 Double 의 Extension이 맞는거 같아 Double로 만들어 주었습니다 왜 String 으로  말씀하셨는지 궁금합니다  🤔

2022-07-04 07:28 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/NumberFormatter.swift
> +    let result = numberFormatter.string(for: number) ?? "\(SetNumber.failNumberFormatter.rawValue)"
Error타입을 만들어서 처리해 주었습니다.

2022-07-04 07:38 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            bankBusinessStart()
다른입력에 따른 처리 추가해주었습니다

2022-07-04 08:14 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/NumberFormatter.swift
> +func numberFormatter(number: Double) -> String {
제이크가 올려주신 저 글을 읽어봤었는데 저 글에서는 DateFormatter함수를 사용해서 실험을 했는데 선언 방법이나 생성 방법에 따라 확연한 시간차이를 보였습니다. 그래서 비슷하게 extesnsion과 구조체를 이용해서 테스트를 진행해봤는데 확연한 차이를 확인하지 못했습니다. 전역함수를 지양하고 extension을 활용하는게 어떤 코스트를 줄일 수 있는 건지 궁금합니다. 그리고 제가 만든 테스트에 방법이 잘못된건지도 궁금합니다. 사진으로 첨부 하겠습니다.
<img width="1412" alt="스크린샷 2022-07-04 오후 2 20 56" src="https://user-images.githubusercontent.com/98506825/177112093-8db00165-47ef-45c4-95ac-19b4104d5ef7.png">

2022-07-04 08:15 UTC, unchain123 commented
피드백에 대한 리펙토링 완료했습니다. 제이크.
리펙토링 과정에서 궁금한사항이 생겨서 댓글로 남겨놨습니다. 확인 부탁드릴게요 감사합니다.

2022-07-04 13:14 UTC, jryoun1 reviewed
수정하신 부분들과 질문 남겨주신 부분들 확인하고 답변 남겨드렸습니다.
고생하셨습니다. 👏 👍🏻

다만 아직 Customer 객체들을 Bank 내부에서 생성하고 있는 부분과 Bank 내부에서 Bank가 하는 역할이 아닌 다른 로직을 포함하고 있는 것 같아서 코멘트 남겨드렸습니다. 확인부탁드려요 🙏🏻

2022-07-04 13:14 UTC, jryoun1 commented on BankManager.swift
> +protocol BankManager {
그리고 protocol의 네이밍은 주로 ~able과 같은 형용사나 ~protocol이라고 네이밍합니다. 
따라서 만약 BankManager가 해야하는 일들을 프로토콜로 만들어주고 BankManager가 이를 채택하게하려고 한다면, 아래와 같이 프로토콜을 생성할 수 있을 것 같습니다. 
```swift
protocol BankManageable {
     func handleWork() 
}
```

2022-07-04 13:14 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            let customer = Customer(bankNumberTicket: ticketNumber)
이 부분은 아직 수정이 안된 것 같습니다. 확인부탁드려요 🙏🏻

2022-07-04 13:14 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankManagerNameSpace.swift
> +//  BankManagerNameSpace.swift
NameSpace인데 다른 Error, BusinessType enum타입들도 다 이 파일에 있는 것 같습니다.
파일을 분리시켜주세요!

2022-07-04 13:14 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        switch requestInput {
제가 말씀드린 부분은 사용자에게 input을 받고, 손님의 숫자를 랜덤으로 생성하는 부분 자체가 main이라는 파일에서 진행되고, 
이러한 로직 자체를 Bank 내부에서 수행할 이유가 없다고 말씀드렸던 것 입니다.

따라서 main 파일에서 
1. input을 받고, 손님의 수를 랜덤으로 생성
2. 랜덤으로 생성된 수 만큼 손님 객체를 생성한다 (큐를 사용해서 큐를 생성)
3. bankMananger 객체도 생성
4. switch 문에서 open인 경우에는 Bank에 bankManager 객체와 customer queue 혹은 손님 객체들을 init 할 때 같이 넣어줌

이러한 flow를 말씀드렸던 것 입니다. 
여기서 순서는 크게 상관없지만 bank는 손님과, bankManager를 내부에서 만들어주는 것이 아니라 init 시점에서 주입을 받아서 각각의 객체들간의 결합도를 낮출 수 있을 것 같습니다. 🙏🏻

2022-07-05 01:49 UTC, unchain123 commented on BankManager.swift
> +    func handleBanking(customer: Customer) {
WorkType구조체를 생성해서 매개변수로 처리해 주었습니다.

2022-07-05 02:03 UTC, unchain123 commented on BankManager.swift
> +protocol BankManager {
프로토콜로 처리하면 은행원이 여러명이 되어 일처리를 할 수 가 없다는 제이크 말씀 정확히 이해 했습니다. 프로토콜을 다시 구조체로 변경하여 의존성주입을 해주도록 하겠습니다.

2022-07-05 02:36 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/BankManagerNameSpace.swift
> +//  BankManagerNameSpace.swift
각각의 열거형 파일을 생성해서 분리 시켜주었습니다.

2022-07-05 02:39 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        switch requestInput {
1~4번 에 해당하는 작업을 main에 처리 해서 객체들간의 결합도를 낮췄습니다

2022-07-05 02:39 UTC, unchain123 commented
제이크 리펙토링 다시 완료했습니다!

2022-07-05 14:19 UTC, jryoun1 approved these changes
고생하셨습니다 👍🏻

잘 수정해주셔서 몇 가지 코멘트만 남겼는데, 해당 부분은 step3를 진행하시면서 수정하셔도 될 것 같습니다🙏🏻
step2는 여기서 머지하겠습니다! step3도 화이팅입니다 💪🏻

2022-07-05 14:19 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/WorkType.swift
> +struct WorkType {
이 부분은 enum타입인 BusinessType 쪽으로 합칠 수 있을 것 같아 보입니다! 🙏🏻
```swift
enum BusinessType {
       case banking 
       case loan 
       case counseling
        // 이런식으로 type과 업무에 필요한 시간을 지정해줄 수 있을 것 같습니다.
       // 추가로 반환값을 다르게 주고 싶다면 enum 내부에 computed property를 생성해서 반환해주는 방법이 있습니다. 
      
      var timeInSecond: Double {
             switch self { 
                    case .banking: return 0.7 
                     //
              }
      }
}
```

2022-07-05 14:19 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +func makeCustomer() -> BankItemQueue<Customer> {
main 파일에서만 사용된다면 private을 붙여도 될 것 같습니다!

2022-07-05 14:19 UTC, jryoun1 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    var bank = Bank(customer: makeCustomer(), bankmanager: bankManager)
의존성 주입을 통해서 결합도가 낮아졌네요👏 
여기서 bank가 var로 설정된 이유가 있을까요? 🤔

2022-07-05 14:19 UTC, merged