은행 창구 매니저 [STEP2] 재재, 나별
yagom-academy/ios-bank-manager pull request #194
Opened 2022-06-30 13:50 UTC by ZZBAE

안녕하세요 제이슨 @ehgud0670 !
은행 창구 매니저 STEP2 PR 보냅니다. 이번에 진행하면서 이런 저런 오류들이 있었는데, 바로바로 피드백 주셔서
프로젝트 진행하는데 큰 도움 주셔서 감사했습니다. 이번에도 리뷰 잘 부탁드리겠습니다!! 🥰👍🏻

# 🏦 은행 창구 매니저
> 프로젝트 기간 : 2022.06.29 수  ~ 2022.06.30 목 </br>
팀원: 재재, 나이든별</br>
리뷰어: 제이슨
---

## 💾 개발환경 및 라이브러리
[![swift](https://img.shields.io/badge/swift-5.6-orange)]()
[![xcode](https://img.shields.io/badge/Xcode-13.4.1-blue)]()

## 💡 Step 2 수행 중 핵심경험
- [x] Queue의 활용
- [x] 타입 추상화 및 일반화

## UML
<img width="627" alt="스크린샷 2022-07-01 오전 2 42 59" src="https://user-images.githubusercontent.com/98302604/176990518-3aa02c80-7c79-4776-bb5a-29fff4e31cd8.png">

## ✏️ 작업한 내용
1. **`Client`**
    - 은행에 온 고객을 대기번호를 기준으로 생각하여 Int로 설정해줍니다.
2. **`Clerk`**
    - `client`를 매개변수로 받아 `provideService`라는 메서드를 실행하는 구조체입니다.
3. **`BankManager`**
    - `openBank`로 시작을 해줍니다.
    - `Client`에게 `issueTickets`을 해줍니다.
    - `startWork`로 `client`를 데리고 와서 업무 진행 후 `servedClients`에 업무 처리한 고객의 수를 1씩 더해주고, 소요된 시간인 `timeSpent`에 0.7초씩 더해줍니다.
    - `finishWork`에서 `formattedTime`에 소요된 시간들의 합을 소수점 2자리까지 나타낼 수 있게 해준 뒤, 마감 문구를 print 해줍니다.

## ⁉️ 고민한 점
* **`switch`문을 사용할 때, `defer`의 사용에 대해 고민했습니다.**
    * 커맨드 라인 툴을 사용함에 있어, 메서드에서 메서드로의 흐름을 통해 전체 과정을 구현하는 데 집중했습니다.
    * 이 과정에서 `defer`를 사용해, 메서드가 `return`되고 다음 메서드를 불러오는 흐름을 사용했습니다.
    * 그러나 `switch`문 내부에서는 `defer`를 사용하면 안 되는 것으로 알고 있습니다. 하지만 은행 앱 초기 설정상 사용자가 1번을 선택해야 은행 업무를 시작하기 때문에, 이 경우는 어떻게 해야 할 지 고민했습니다.
    * 일단, 해당 `switch`문 안에서 다음 메서드를 불러오는 식으로 코드를 짰습니다. 하지만, 이렇게 되면 은행 앱이 작동을 멈출 때까지 `openBank()` 메서드가 살아 있을 것이라고 생각되기 때문에, 고민되는 지점이 있습니다.

## ⌨️ 커밋 규칙
* feat    : 기능 추가 (새로운 기능)
* fix      : 버그 수정
* refactor : 리팩토링 (네이밍 수정 등)
* style   : 스타일 (코드 형식, 세미콜론 추가: 비즈니스 로직에 변경 없음)
* docs    : 문서 변경 (문서 추가, 수정, 삭제)
* test    : 테스트 (테스트 코드 추가, 수정, 삭제: 비즈니스 로직에 변경 없음)
* chore   : 기타 변경사항 (빌드 스크립트 수정 등)

## 💻 코드 컨벤션
Swift Statements 형식 준수

2022-07-01 08:15 UTC, OldStarKR commented
`defer`에 대해서 좀 더 공부해본 결과, `switch`문 안에서 안 될 이유가 없는데?! 하고 적용해서 실행해보니 되는 것을 확인했습니다! 위쪽에, "그러나 switch문 내부에서는 defer를 사용하면 안 되는 것으로 알고 있습니다." 라고 했던 부분에 대한 의문은 해결되었다고 볼 수 있겠습니다😅

2022-07-03 07:23 UTC, ehgud0670 requested changes
고생하셨습니다 :)

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +extension BankManager {
extension 을 사용하신 기준이나 이유가 궁금합니다. 
현재 class 안에서는 변수만 있어서 너무 잘게 쪼개건 아닌가 해서요.
저는 보통 어떤 프로토콜을 채택하는 경우에만 extension을 사용합니다. 아니면 특정 경우에만 사용되는 메소드인 경우요!

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +            }
defer를 안써도 프로그램이 잘 돌아가는데 defer를 쓰신 이유가 궁금해요. 
defer를 보통 어느 경우에 쓰실까요? 
(defer를 쓰지 않아도 되는데 defer를 쓰면 어떤 의도가 있는지 알기 위해 코드를 보는데 더 시간이 오히려 들 수도 있을 것 같아요 🥲)

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        }
forEach 문도 쓰는 것을 고려해보세요 :)

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +            }
저는 아래 링크처럼 어떤 경우든 반드시 마지막에 호출되어야 하는 경우에만 defer 쓰임이 적절한 경우에만 보통 사용합니다. 
https://blog.logrocket.com/complete-guide-swift-defer-statement/
참고차 말씀드립니다 ㅎㅎ

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        }
여기도 안써도 되지 않아요?!

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +    var clients = CustomerQueue<Client>()
clients나 clerk을 init을 통한 의존성 주입을 해서 테스트 가능한 구조를 만들어 볼 수도 있겠습니다. 테스트도 가능할 것 같고요.
참고차 말씀 드립니다 ㅎㅎ

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        let customerNumber = Int.random(in: 10...30)
10과 30도 지금 매직넘버인데, 메소드의 지역변수로 빼거나 메소드 인자로 빼면 좀 더 가독성이 있을 것 같아요.

2022-07-03 07:23 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        }
여기도 안써도 될 것 같아요.

2022-07-03 07:37 UTC, ehgud0670 commented
클린코드 10장 클래스도 보시는 것 추천합니다. PrimePrinter 라는 클래스를 PrimePrinter, RowColumnPagePrinter, PrimeGenerator로 잘 분리한 케이스인데 자바 코드지만 보면 도움 많이 되실겁니다 👍

2022-07-03 08:43 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        switch selection {
selection에 대해서도 enum 사용하는 것도 고민해보셔도 좋을 것 같아요 :)

2022-07-04 06:11 UTC, ZZBAE commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +extension BankManager {
저희가 extension으로 나누어준 이유는 가독성을 위해 해주었습니다. 하지만 제이슨의 의견을 듣고 class안에 변수만 있는것이 잘게 쪼개진 느낌일 수 있다고 생각이 들어 프로토콜을 채택한 extension만 남기고 채택하지 않은 나머지 BankManager와 LinkedList안에 있던 extension들을 통합해주었습니다 :)

2022-07-04 06:22 UTC, ZZBAE commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +            }
보내주신 링크를 공부하면서 defer문을 사용하지 않아도 잘 돌아가고, 코드를 읽는 사람 입장에서 시간이 더 들 수도 있다는 제이슨의 의견에 동의합니다. 그래서 전면 수정해주었습니다! 
defer를 써주었던 이유는 return 이 된 이후에 실행되는 것들을 추가해주기 위함이였고, return 이후에 defer를 사용해주면 defer 이전의 메서드가 메모리에서 해제가 된다고 생각을 해서 사용해주었습니다. 참고 링크를 읽어보니까, 메모리와는 관계 없다는 느낌을 받았습니다. 제가 이해한 부분이 맞는 방향일까요?

2022-07-04 06:23 UTC, OldStarKR commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        switch selection {
선택의 기준으로 1과 2 이외의 다른 것을 사용하게 될 수도 있겠다는 생각을 하게 됐습니다. 해당 부분을 네임스페이스로 빼 주어 코드의 재사용성을 높였습니다😊

2022-07-04 06:24 UTC, OldStarKR commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        let customerNumber = Int.random(in: 10...30)
최소 고객 수, 최대 고객 수라는 개념으로 생각하여, 네임스페이스로 빼 주었습니다😃

2022-07-04 06:24 UTC, OldStarKR commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +        }
번호표 배열을 새로 지정해, forEach를 사용할 수 있게끔 했습니다😁

2022-07-04 06:29 UTC, OldStarKR commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +    var clients = CustomerQueue<Client>()
지정 이니셜라이저가 없어서 의존성 주입 및 테스트가 곤란한 코드일 수 있겠다고 생각했습니다😅 그래서 이니셜라이저를 만들어 주어서 의존성을 주입할 수 있게 했습니다.한편, 이니셜라이저에 기본값을 추가해 주어서 별도의 값을 넣지 않고도 실행할 수 있는, 저희가 main에서 원래 짰던 모양의 코드로도 실행될 수 있게 했습니다.

2022-07-04 09:09 UTC, ehgud0670 commented on BankManagerConsoleApp/BankManagerConsoleApp/Controller/BankManager.swift
> +            }
넵! 저는 예를 들어 try catch 처럼 분기되는 상황에도 마지막에 반드시 작업이 진행되어야 하는 코드만 defer 를 사용합니다. 
즉 분기되어 있는 상황이 아니라 defer를 사용하지 않아도 되는 상황이면, 이해하신대로 사용하지 않는게 오히려 코드를 보는데 더 유리하다는 차원에서 말씀드렸습니다! ㅎㅎ
메모리는 어차피 함수 끝나면 해제되니 그렇게까지 까다롭게 안봐도 괜찮을 것 같다는 의견을 조심스럽게 말씀드려 봅니다 :)

2022-07-04 09:15 UTC, ehgud0670 approved these changes
잘 반영해주셨네요!! 
고생하셨습니다 :)

2022-07-04 09:15 UTC, merged