은행 창구 매니저 [STEP2] Kiwi, Kay
yagom-academy/ios-bank-manager pull request #195
Opened 2022-07-01 03:43 UTC by KayAhnDS

안녕하세요 @corykim0829!
은행 창구 매니저 프로젝트의 두번째 PR 입니다!
좋은 코멘트 부탁드립니다!

# 🍎파일 및 함수 설명 :
- BankManagerConsoleApp 내 파일들을 그룹화 해주었습니다.
- Enum을 만들어 숫자(하드코딩)를 묶어 주었습니다.
- Customer 타입이 번호표를 가질수 있도록 프로퍼티로 추가.

# 📚배운개념  :
1. DispatchQueue
2. DispatchWorkItem
3. Thread.sleep

# 궁금한점 ❓ :

1. BankManager파일에서 이루어 지는 작업을 Class화 한다음 캡슐화를 시켜 main에서 호출을 하는 것을 시도해 보았으나, 같은 class 안에서 내부 프로퍼티를 사용함에 있어 계속 오류가 발생하였습니다. 이것을 해결하기 위해 static을 사용하는 것을 생각해 보았으나, 이는 좋은 방법이 아닌거 같아 사용을 하지 않고 일단 class화를 하지 않고 PR을 보내게 되었습니다. 혹시 코리가 생각하시는 좋은 방법을 알려주시면 정말 감사하겠습니다!

![](https://i.imgur.com/xh8tEE5.png)

2022-07-01 13:25 UTC, corykim0829 requested changes
수고하셨어요 Kiwi, Kay! 👏

제가 스텝 요구사항에서 봤을 때, `은행/고객 타입 외에 필요한 타입이 있다면 자유롭게 구현합니다` 라는 부분이 있었는데요. 은행 타입도 구현해주세요!

### 궁금한점

BankManager는 클래스or구조체로 구현해주세요! 클래스로 사용했을 때, 왜 내부 프로퍼티를 사용하지 못했는지 고민해보면 좋을 것 같아요.
내부 프로퍼티를 사용하지 못하면 어떻게 해야할지도 고민해봐요!

2022-07-01 13:25 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +let openBank = DispatchWorkItem {
여기 부분은 DispatchWorkItem으로 처리하신 이유가 뭔가요? 👀

2022-07-01 13:25 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        guard let verifiedCustomer = lineOfCustomers.dequeue() else { return }
guard let으로 생성된 상수값은 해당 블록 안에서만 사용되기 때문에 간단하게 `customer`라고 적어도 됩니다. `verifiedCustomer`처럼 형용사가 붙게되면 가독성이 떨어지게 됩니다! 참고하세요!

2022-07-01 13:25 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +struct Banker {
사용하지 않는 구조체나 코드는 특별한 경우가 아니면 PR에 포함하지 않는게 좋습니다.

2022-07-01 13:25 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +DispatchQueue.global().sync(execute: openBank)
global, sync로 처리한 이유가 무엇인가요?

2022-07-01 13:25 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        if let verifiedInput = userInput {
여기도 위에 해드린 피드백과 마찬가지로 verified라는 형용사는 없어도 될 것 같아요.
나중에 실제로 verification이 필요한 상황에서 쓰는게 더 적절한 것 같아요

2022-07-03 12:23 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        let customer: Customer = Customer(customerNumber: element)
말씀해주신대로 삭제해주었습니다.

2022-07-03 12:23 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    var customerNumber: Int
말씀해주신대로 수정 하였습니다.

2022-07-03 12:24 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/Time.swift
> +    case perPerson = 0.7
수정 하였습니다 !!

2022-07-03 12:24 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        totalTimeOfWork += Time.perPerson.rawValue
연산프로퍼티로 가져오게끔 수정하였습니다!

2022-07-03 12:24 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +//  BankManager.swift
넵 객체로 처리하였습니다!

2022-07-03 12:24 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +let openBank = DispatchWorkItem {
DispatchQueue를 상수화 하여 가독성을 높이고 나중에 쉽게 호출이 가능하도록 하기 위해서 사용을 해주었습니다!

2022-07-03 12:24 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        guard let verifiedCustomer = lineOfCustomers.dequeue() else { return }
수정하였습니다!!!

2022-07-03 12:25 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +struct Banker {
말씀해주신대로 삭제하였습니다.

2022-07-03 12:36 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +DispatchQueue.global().sync(execute: openBank)
main.async와 global().async는 사용하였을때, DispatchQueue에 Task를 던지고 종료 됩니다. 하지만 global().sync를 사용하게 되면 DispatchQueue에서 작업을 다른 스레드에 넘기지않고 바로 수행하기 때문에 global().sync를 사용했습니다.

2022-07-03 12:39 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        if let verifiedInput = userInput {
말씀해주신대로 수정하였습니다!

2022-07-04 01:42 UTC, corykim0829 requested changes
수고하셨습니다. 이전보다 코드가 많이 깔끔해지고, 가독성이 좋아졌습니다! 👍

이전에 피드백 드렸었던, DispatchWorkItem을 변수로 처리했을 때, 에러 났던 부분 설명도 해주실 수 있을까요? (에러의 이유, 해결방안에 대한 근거)
변수로 처리해도 해당 에러를 피해서 작동하게 할 수는 있습니다! 이 해결방안까지 고민해보면 좋을 것 같아요.

이 부분만 빠르게 수정하고 다음 스텝으로 가면 좋을 것 같아요!

2022-07-04 01:42 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func openBank() {
이제보니, 이 함수 내부에서 input 관련 처리는 bankManager 객체에서 처리하는게 BankManager가 너무 많은 일을 하는 것 같아요.
객체의 할일을 잘 분리시키는 것은 객체지향적으로 코드를 작성하는데 큰 도움이 됩니다! 참고하세요!

2022-07-04 01:42 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    private func handle() {
함수명이 추상적이여서 어떤 일을 하는지 코드를 읽지 않으면 유추하기 어렵습니다! 수정해보면 좋을 것 같아요!

2022-07-04 01:42 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        let handleCustomers = DispatchWorkItem {
개인적으로는 DispatchWorkItem 프로퍼티를 함수 내부 변수로 처리한다면, 변수로 만드는 의미가 크게 없어보입니다.

2022-07-04 05:25 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    private func handle() {
수정하였습니다!!!

2022-07-04 05:26 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func openBank() {
openBank() 메서드가 하는 일은 Bank가 하는일이 더 적합한것 같아 위치를 옮겨주었습니다.

2022-07-04 05:27 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        let handleCustomers = DispatchWorkItem {
코멘트 해주신것을 보고 WorkItem을 보니 정말 "메서드 내부에서만 쓰이는데 꼭 필요할까?" 라는 생각이 들어 수정 해주었습니다.

2022-07-04 05:34 UTC, kiwi1023 commented
하나의 Class 내에서 내부 프로퍼티를 다른 메서드에서 사용할때, 내부 프로퍼티가 초기화 되기도 전에 사용을 하여 오류가 발생하였었는데 이를 self 키워드를 사용하여 해결을 하게 되었습니다!

2022-07-04 06:52 UTC, corykim0829 approved these changes
수고하셨습니다! 고쳐야할 부분은 다음 스텝에서 같이 진행해주세요!

2022-07-04 06:52 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    func openBank() {
Bank 구조체는 데이터만 가지고 있는 모델 처럼 보이는데, 메뉴를 출력하는 기능을 해서 어색해보여요.
그리고 BankManager는 여전히 input을 처리하고 있어요!
input을 처리하는 객체를 따로 만들어보는건 어떨까요?

2022-07-04 06:53 UTC, merged