은행창구매니저 [STEP2] 웡빙, 예톤
yagom-academy/ios-bank-manager pull request #198
Opened 2022-07-01 08:05 UTC by wongbingg

안녕하세요 라이언 @ryan-son  step2 수행 후 pr 보냅니다 ! ☺️☺️ 잘 부탁드립니다
@wongbingg @yeeton37
## Step 2
### UML

<img width="813" alt="스크린샷 2022-07-01 오후 5 00 53" src="https://user-images.githubusercontent.com/98514397/176851733-4ea2ff97-1645-415c-abe7-b1c2f1783216.png">
### 작업내용
- **[타입 구현]**
    - **Bank** : 은행의 전반적인 기능을 작성 해주었습니다 
    - **BankManager** : 은행원의 수행역할을 작성 해주었습니다
    - **Customer**: 고객의 번호를 저장할 수 있는 타입을 작성 하였습니다
- **[랜덤한 고객의 수]**
    - 10~30사이 숫자의 고객이 방문한다고 가정했습니다
    - `Int.random(in range: ClosedRange<Int>)`를 이용하여 무작위 수를 생성 해주었습니다. 
- **[하나의 작업 당 0.7초씩 부여]**
    - BankManager가 고객을 응대하는 시간을 명당 0.7초로 정의 해주었습니다.
    - 작업의 시작과 끝 사이에 시간을 멈춰주었습니다.
    - `Thread.sleep(forTimeInterval: TimeInterval)`을 이용했습니다.
- **[전체 작업을 실행하는 메서드 구현]**
    - Bank의 각 작업을 시작하는 `start()` 메인 메서드를 구현했습니다
    
### 스텝 핵심 경험
- [x] Protocol Oriented Programming으로 `CustomerQueue`를 구현
- [x] Queue의 활용
- [x] 타입 추상화 및 일반화
- [x] 유닛 테스트의 번들 Target과 Scheme 

### 고민한 점들

### 1. private(set)
- 클래스 Queue에서 내부 프로퍼티를 private(set)으로 설정해주었습니다.
- 저희는 private(set)은 외부에서는 읽기만 가능하고 쓰기는 안되기 때문에 내부 프로퍼티를 외부에서 초기화해주는 것 또한 불가능할 것이라고 생각했습니다. 
- 하지만 초기화는 프로퍼티의 처음 상태를 설정해주는 것이기 때문에 private(set)으로 설정된 프로퍼티에 초기값을 할당하는 것은 가능하고, 할당된 프로퍼티에 접근해서 새로 할당을 하는 것은 불가능하다는 것을 알게되었습니다.

[코드]
```swift
struct CustomerQueue<T> {
    private(set) var queue: LinkedList<T>
}
```
```swift
class CustomerQueueTests: XCTestCase {
    var sut: CustomerQueue<Int>!
    
    override func setUpWithError() throws {
        try super.setUpWithError()
        sut = CustomerQueue(queue: LinkedList())
    }
} // 정상 실행
```

### 2. 큐의 초기 조건을 설정해줄 수 있도록 이니셜라이저 추가
[라이언의 코멘트 1]

> 타입에서 큐의 초기 조건을 설정해줄 수 있도록 이니셜라이저를 추가해주면 좋을 것 같아요. 
현재 유닛테스트할 때 큐에 미리 아이템이 들어간 상황을 연출하려면 enqueue(data:) 메서드를 사용할 수밖에 없는데, 
그렇게 되면 enqueue(data:)의 실행 결과에 다른 테스트들이 영향을 받아 테스트의 신뢰성을 떨어뜨릴 수 있을 것 같아요

[라이언의 코멘트 2]
> peek의 기능을 검증하기 위한 테스트인데, enqueue의 로직과 성공 여부에 테스트 성공 여부가 달려있어 테스트의 독립성이 떨어진다는 의견이 나올 수 있을 것 같네요. 이니셜라이저를 통해 queue의 초기상태를 지정할 수 있는 기능을 추가해보는건 어떨까요?
[변경한 코드]
```swift
struct CustomerQueue: Queue {
    private(set) var queue: LinkedList<Customer>
    
    init(elements: [Customer] = []) {
        queue = LinkedList()
        elements.forEach {
            self.enqueue(data: $0)
        }
    }
}
```
- 라이언의 코멘트에 따라 CustomerQueue에 initializer를 추가해주었습니다.
    -  elements에 아무것도 담기지 않았을 경우 빈 배열로 설정되도록 default initializer로 만들어 주었습니다.
    -  배열인 elements 안의 요소를 foreach로 돌면서 빈 배열에 데이터를 넣어주었습니다.
    
### 3. 테스트 코드 네이밍 수정 
[라이언의 코멘트]
> 우리가 제공하는 Queue의 기능 범위는 무엇인가?
- isEmpty, peek, enqueue, dequeue, ...
    - 어떤 기능인가?
        - isEmpty: Queue가 비어있는지 판단할 수 있음 -> 검증할 것: 비어있을 때/비어있지 않을 때 -> queue가 빈 상태인지 판단할 수 있다.
        - peek: Queue의 첫번째 요소를 알 수 있음, 없으면 nil -> 검증 할 것: 첫 요소 있을 때/없을 때 -> queue의 첫번째 요소를 확인할 수 있다. (없는 경우는 별도의 테스트케이스로 구성 - 첫 요소가 없으면..~)
        - ...

[변경 코드]
- `test_3과7과5를넣었을때_dequeue의반환값이3인지` 
    -> `test_큐에값을3개넣어줄때_dequeue를하면_첫번째값이_제거되고반환된다`

### 배운 키워드
`code coverage`, `Protocol Oriented Programming`, `scheme`, `target`, `bundle`, `associatedtype`

## 트러블 슈팅
- 유닛테스트에서 정확한 검사를 위해 현재 연결 리스트에 쌓여있는 값들을 배열형태로 가져올 수 있도록 currentList 라는 연산 프로퍼티를 만들어 주었습니다. 
- 테스트 시, 타입을 찾을 수 없다는 오류발생, TargetMembership에 테스트파일 체크를 해주니 없어졌습니다![](https://i.imgur.com/2r7w6Ur.png)
- 각 테스트 마다 생성이 되어있던 번들을 하나로 통일 해주었습니다.

2022-07-03 16:32 UTC, ryan-son requested changes
웡빙, 예톤! Step 2를 금방 완성해주셨네요. 

이전 스텝에서 작업하신 내용을 적용해보는 단계라 방향성에 대한 부분에는 이견이 없어 요청하시면 바로 머지하도록 하겠습니다. 개별 코멘트 읽어보시고 말씀해주세요.

# 질의응답
>하나의 함수에 하나의 기능만 하도록 해주기 위해서 최대한 중첩함수를 지양하고 위와 같이 작성해주었는데 이렇게 하는 방법이 맞는 건지 라이언에게 여쭤보고 싶습니다!

다른 메서드에 대한 의존성을 줄이면 복잡도가 줄고 재사용성이 증가해서 분명히 장점이 있다고 생각해요. 방향도 적절하다고 생각합니다. 여러분들도 아시듯이 맞고 틀린건 없으니 동료들과 의견을 나누어보셨으면 좋겠네요.

피드백 관련해서 궁금하신 점이나 추가 질문이 있으시면 말씀해주세요. 고생하셨습니다! 👏

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var randomNumber: Int = 0
접근 제한이 잘 설정되어 있네요! 👍 

[P3]
`randomNumber` 같은 경우에는 어떤 목적으로 사용되는 프로퍼티인지 알려주기 위해 이름을 보완해보는건 어떨까요?

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            } else if selectedMenu == "2" {
[P3]
"1", "2"와 같은 literal string을 사용하기보다 열거형의 case를 정의하여 type-safe하게 사용한다면 더 안전하게 사용할 수 있을 것 같아요. "1", "2"에 해당하지 않는 경우에는 `none`과 같은 케이스를 정의하면 될 것 같네요.

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +""", terminator: " ")
[P4]
줄바꿈을 정리해볼까요?
```suggestion
        print(
            """
            1 : 은행 개점
            2 : 종료
            입력 :
            """, 
            terminator: " "
        )
```

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    mutating private func selectMenu() -> String {
[P5]
개인적으로는 메서드의 속성이나 특징을 나타내는 `mutating`, `static`과 같은 표현들은 접근제한자 이후에 표시하는 것이 자연스럽다고 보이네요. 여러분은 어떻게 생각하시나요?

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            guard let customer = queue.dequeue() else {
[P5]
`dequeue()`라는 메서드 이름에서 충분히 예상할 수 있지만, 명확히 하기 위해 `nextCustomer`라는 표현을 사용해도 좋을 것 같아요.

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +                                       bankManager.handlingTime * Double(randomNumber))
[P5]
이곳은 줄바꿈 형식이 이전과 다르네요. 통일시켜보는건 어떨까요?

```swift
let totalHandlingTime = String(
    format: "%.2f",
    bankManager.handlingTime * Double(randomNumber)
)
```

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Queue+Extensions.swift
>          return queue.isEmpty
[P3]
연산 프로퍼티 구현부에서 `isEmpty` 이외에는 명시적으로 `return`을 작성해주지 않고 있는데, 한 가지 방식으로 통일하는건 어떨까요? `dequeue()` 메서드도 암시적으로 반환하고 있네요.

2022-07-03 16:32 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
이렇게 실행될 때마다 무작위한 결과를 반환하는 메서드의 경우에는 유닛 테스트를 어떻게 수행해줄 수 있을까요? 이번 기회에 학습해두신다면 `UUID`와 같은 요소들에 의존하게 될 때 활용할 수 있을거에요.

2022-07-04 05:54 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var randomNumber: Int = 0
randomNumberOfCustomer 라는 네이밍으로 의도를 명확히 해주었습니다! ☺️☺️

2022-07-04 06:18 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +""", terminator: " ")
메뉴 문자열도 NameSpace로 분리 해주었습니다!

2022-07-04 06:21 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    mutating private func selectMenu() -> String {
사실 키워드를 두개씩 사용해 본 것이 처음인지라 어떻게 표현하는 것이 좋을지 판단하기 어려웠습니다.
 라이언의 말에 동의합니다 !

2022-07-04 06:24 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +            guard let customer = queue.dequeue() else {
첫 고객의 경우가 nextCustomer란 네이밍에 자연스럽게 스며들지 못하는 것 같아 그대로 사용하기로 결정햇습니다 ! 감사합니다 ㅎㅎ

2022-07-04 06:26 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +                                       bankManager.handlingTime * Double(randomNumber))
말씀 주신대로 변경 하였습니다! 🫡🫡

2022-07-04 06:27 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Queue+Extensions.swift
>          return queue.isEmpty
return을 제거하는 방향으로 통일성을 맞추었습니다!

2022-07-04 07:10 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
10 ~ 30 사이의 범위가 출력되는지 확인하기 위해 
첫 번째로, 결과값이 10 ~ 30 사이값이면 True 인지 확인하는 테스트를 진행했고 
두 번째로, 결과값이 10 미만 또는 30초과인 경우 False 인지 확인하는 테스트를 진행했습니다!!
혹시 random 한 값에 대해 더 수행 해주어야 할 유닛테스트가 있다면 어떤 것이 있을까요 !?!🧐

2022-07-04 10:27 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +""", terminator: " ")
커밋 해시값을 붙여넣으면 해당 커밋에 대한 링크를 남길 수 있어요. 앞 7자리 또는 처음부터 끝까지 다 작성하시면 링크가 걸리고 아래와 같이 앞 7자리만 표시합니다.
`c93adcbfd98a8edb6a1c0eeff8e9dbb8bff14cc5`로 작성: c93adcbfd98a8edb6a1c0eeff8e9dbb8bff14cc5
`c93adc`로 작성: c93adcb

2022-07-04 10:53 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
테스트 요건으로는 충분해 보이네요. 아무래도 정수형이라 이렇게 대응할 수도 있을 것 같습니다. 하지만 `UUID`와 같이 매번 수행 결과가 바뀌지만 결과를 전혀 예상할 수 없는 경우에는 아래와 같은 방식으로 대응할 수 있어요. 참고만 해두시면 될 것 같네요

랜덤한 요소에 대한 테스트는 일반적으로는 랜덤 요소를 제거하고 테스트 가능한 요소를 주입할 수 있도록 만드는 방식으로 수행합니다.

```swift
private mutating func updateCustomerQueue(customerCount: Int) { ... }

// Production
updateCustomerQueue(customerCount: Int.random(10...30))

// Unit test
updateCustomerQueue(customerCount: 1)
// 특정 숫자일 때에 대한 테스트 케이스 작성 가능하므로 엣지 케이스에 대한 테스트 가능
// `Int.random(_:)`은 개발자에게 배포되기 전 테스트를 마친 프레임워크에서 제공하는 메서드이므로 검증 대상에서 제외
```

같은 맥락으로 `UUID`의 경우에도 [`String`으로 `UUID`를 생성할 수 있는 이니셜라이저](https://developer.apple.com/documentation/foundation/uuid/3126814-init)를 제공하고 있습니다.

```swift
struct Person {
    let id: UUID
}

// Production
let person = Person() // Person with random UUID
// person.id // id: ??

// Unit test
let expectedID = UUID(uuidString: "00000000-0000-0000-0000-000000000000")
let person Person(id: id)

XCTAssertEqual(person.id, expectedID) // true
```

2022-07-04 10:56 UTC, ryan-son commented
고생 많으셨습니다! 머지할게요~

![image](https://user-images.githubusercontent.com/69730931/177140839-aa480deb-941d-4c77-9967-d6ceefc490f0.png)
같이.. 하고 계신 것 맞죠..? 번갈아가면서 작업하시면 더 좋을 것 같네요~!

2022-07-04 10:56 UTC, merged