은행 창구 매니저 [STEP2] minsson, derrick
yagom-academy/ios-bank-manager pull request #200
Opened 2022-07-03 08:14 UTC by minsson

@leejun6694
안녕하세요, 쿠마!🥰

은행창구매니저 프로젝트 9조 민쏜과 데릭입니다.

Step 2 PR 보냅니다.

아래와 같이 작업내용과, 저희의 생각의 흐름을 작성해보았습니다.
저희가 생각한 방향에 대해 쿠마는 어떻게 생각하시는지 피드백 부탁 드립니다! 😁

## 👀 고민했던 점
### 1. Client 객체의 생성 및 Bank 타입으로의 데이터 전달 방법
현실 세계 관점의 추상화와 컴퓨터 세계 관점의 추상화 측면에서 고민했습니다.

요구사항의 `은행에는 n명의 고객이 업무처리를 위해 대기합니다`와 관련, Bank 객체 내부에 Client 객체를 담기 위한 clientQueue 속성을 정의했습니다.
이때, Client 객체를 생성해 clientQueue에 할당하는 방법과 관련하여 아래와 같이 고민했습니다.

#### 처음 생각했던 것 (현실 세계 관점의 추상화)
##### 구조 측면
- 현실 세계에서 고객은 은행 외부로부터 입장하므로, 은행이 자신의 내부에 고객을 생성하는 것은 자연스럽지 않다고 생각했습니다.
- 따라서, `ClientManager`라는 별도의 객체를 두고, 요구사항에 맞는 ClientQueue를 생성해 Bank의 clientQueue 속성에 데이터를 전달했습니다.

##### 네이밍 측면
- Bank 객체 내에 `meet(_: Client)`라는 네이밍의 메서드가 있었습니다.
- Bank 내부의 clientQueue 속성에 외부로부터 파라미터로 전달 받은 Client 객체를 enqueue하는 메서드였습니다.
- 코드 내에서 사용시 `bank.meet(client)`와 같은 형태가 되어 무척 자연스러운 네이밍이라고 생각했습니다.

#### 고민 후 결정한 것 (컴퓨터 세계 관점의 추상화)
Bank 객체 내부에 아래와 같은 메서드를 정의했습니다.
```swift
mutating func generateClients() {
    let clientAmount = Int.random(in: 10...30)
    let task: Request = .task
        
    for amount in 1...clientAmount {
        clientQueue.enqueue(Client(request: task, waitingNumber: amount))
    }
}
```
##### 구조 측면
- 컴퓨터 세계 관점에서 추상화한다면, Client는 Bank 객체 내부에서만 사용될 객체이므로, Bank 객체 내부에서 생성되는 것이 효율적이라고 생각했습니다.

##### 네이밍 측면
- `meet(_: Client)`라는 현실 세계의 관점에서 고객이 입장하는 것을 표현한 것이지만, 네이밍만으로는 어떤 기능을 하는 메서드인지 추론하기 어려웠습니다.
- Bank 객체 내부에서 Client 객체를 생성하는 것이므로 `generateClients()`라고 네이밍했습니다. 메서드의 기능이 더 명료해졌다는 생각이 들었습니다.

### 2. Bank 객체에서 Client 객체를 생성하고 접근할 때의 은닉화

아래 코드는 Client 객체 정의부입니다.
```swift
struct Client {
    private(set) var waitingNumber: Int // 고객의 대기 번호를 표현
    private(set) var request: Request // 고객이 은행에서 처리하고자 하는 업무
    
    init(request: Request, waitingNumber: Int) {
        self.waitingNumber = waitingNumber
        self.request = request
    }
}
```
위 코드를 작성하며, `waitingNumber`를 리턴하는 메서드를 정의하는 방안에 대해 고민했습니다.
하지만 아래와 같은 이유로 `private(set)`을 사용하기로 결정했습니다.
- 저장속성의 데이터를 `읽기` 수준에서 접근하는 것과 동일한 리턴값을 가진다는 측면에서 `private(set)`과 은닉화 수준도 동일하다고 생각했습니다.
- 속성에 `private` 접근제어자를 사용하기 위해 불필요한 메서드를 정의하는 것이 합리적이지 않다고 생각했습니다.
- `캡슐화` 측면에서도 단순히 저장속성을 리턴해주는 메서드를 `캡슐화`라고 표현하기 어렵다고 생각했습니다.

### 3. `BankManager` 타입의 업무 시작/완료를 표현하기 위한 메서드
- 아래의 두 메서드는 동일한 결과를 도출합니다.
- 하지만 업무를 진행한 후 종료 하기 위해 DispatchQueue의 메서드를 사용하였습니다.

#### 1) Thread.sleep(forTimeInterval:) 활용
주어진 업무처리 시간만큼 메인 Thread를 정지시킵니다.
```swift
startTask(for: client)

Thread.sleep(forTimeInterval: .now() + processingTime)

finishTask(for: client)
```
#### 2) DispatchQueue.global().asyncAfter(deadline:) 활용

DispatchQueue의 asyncAfter메서드로 deadline을 설정하여 해당 시간이 지난 후 업무 종료를 알립니다.
    
```swift
taskGroup.enter()  
startTask(for: client)
DispatchQueue.global().asyncAfter(deadline: .now() + processingTime) {
    finishTask(for: client)
    taskGroup.leave() 
}
taskGroup.wait()
```

## 🚥 UML
![](https://i.imgur.com/Mcczhb5.jpg)

## 🗂 폴더 구조

```swift 
BankManagerConsoleApp
├── Extension
│   └── Double+Extensions
├── Model
   ├── AppManager
   │        ├── BankAppManager
   │        └── BankSystem
   ├── Bank
   │    ├── Queue
   │    │    ├── Node
   │    │    ├── LinkedList
   │    │    ├── ClientQueue
   │    │    └── Queue
   │    ├── Bank
   │    └── BankManager
   └── Client
         ├── Client
         └── Request
```

2022-07-04 15:54 UTC, leejun6694 requested changes
@minsson @derrickkim0109 안녕하세요!
step 1 에 이어서 step 2 까지 많은 고민이 담겨있는 코드로 느껴집니다 : )
conflict 이 있는데, 이 부분 수정 부탁드려요~!

2022-07-04 15:54 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/BankManager.swift
> +struct BankManager {
은행원의 역할을 하고 있는 것 같네요~!
step 3 에서는 어떻게 변할지 궁금합니다ㅎㅎ

2022-07-04 15:56 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/AppManager/BankAppManager.swift
> +            var bank = Bank()
수정을 바라는게 아닌 같이 논의해봤으면 하는 점들을 코멘트로 남깁니다.
-
`bank` 를 매번 생성해야할까요?

2022-07-04 15:59 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Bank.swift
> +    mutating func generateClients() {
수정을 바라는게 아닌 같이 논의해봤으면 하는 점들을 코멘트로 남깁니다.
- 고객 생성을 `Bank` 에서 해야할까요?

2022-07-05 02:08 UTC, minsson commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank/Bank.swift
> +    mutating func generateClients() {
# 코멘트 주신 내용과 관련, 처음 생각했던 내용 

현재 코드를 작성하기 전, 우선 여러 생각을 하며 코멘트 하단의 `# 전체코드`에 작성했던 코드 중 이 내용과 관련된 파일의 코드를 첨부합니다. (초안이라 네이밍, 메서드 기능 분리 등이 잘 안되어 있는 점 양해 부탁드려요 😅)

초기에는 아래와 같이 생각했었습니다.

1) `Bank` 내부에서 고객이 생성되는 것은 어색하며, 외부에서 고객을 생성해서 `Bank`에 넣어주는 것이 자연스러워 보인다
```swift
// BankAppManager.swift 코드 일부 발췌
 private enum BankSimulator {
        private static let minimumClientNumber = 10
        private static let maximumClientNumber = 30
        private static var RandomNumberClients = Int.random(in: minimumClientNumber...maximumClientNumber)
        
        static func makeVirtualClients() -> [Client] {
            let virtualClientsNumber = BankSimulator.RandomNumberClients
            var virtualClients: [Client] = []
            for number in 1...virtualClientsNumber {
                let client = Client(request: .taskA, waitingNumber: number)
                virtualClients.append(client)
            }
            
            return virtualClients
        }
    }
```
2) `Bank`는 고객을 한 명씩 받는다

```swift
// Bank.swift 코드 일부 발췌
    mutating func meet(_ client: Client) {
        clientQueue.enqueue(client)
    }
```
3) 프로퍼티 옵저버를 이용해, 고객이 입장할 때마다, 즉, `clientQueue`에 `enqueue` 될 때마다 고객의 업무를 처리해준다
```swift
// Bank.swift 코드 일부 발췌
    private var clientQueue = ClientQueue<Client>() {
        didSet {
            arrangeClient(to: tellerA) // 은행원 A(즉, 은행원 A라는 이름의 하나의 스레드 역할)에게 업무 할당
        }
        willSet {
            totalDoneClient += 1 
        }
    }
```

# 질문 👀
위와 같이 생각했었고, 메서드 기능 분리, 네이밍 등만 개선하여 제출하려고 했었습니다.
하지만 `PR 코멘트의 고민했던 점 1번`의 내용과 같은 고민과 토론이 시작되었고, 결과적으로 PR에 제출한 코드와 같이 수정했습니다.

저희가 고민했던 점과 관련하여, 쿠마는 어떻게 생각하시나요?
처음 작성했었던 코드에 대해서는 어떻게 생각하시나요?




# 초안 중 일부 파일 전체 코드 

### BankAppManager.swift
```swift
import Foundation

struct BankAppManager {
    private enum BankSimulator {
        private static let minimumClientNumber = 10
        private static let maximumClientNumber = 30
        private static var RandomNumberClients = Int.random(in: minimumClientNumber...maximumClientNumber)
        
        static func makeVirtualClients() -> [Client] {
            let virtualClientsNumber = BankSimulator.RandomNumberClients
            var virtualClients: [Client] = []
            for number in 1...virtualClientsNumber {
                let client = Client(request: .taskA, waitingNumber: number)
                virtualClients.append(client)
            }
            
            return virtualClients
        }
    }
    
    func runAppLoop() {
        showMenu()
        
        guard let input = readLine() else {
            return
        }
        
        switch input {
        case "1":
            openBank()
            runAppLoop()
        case "2":
            break
        default:
            break
        }
    }
}
    
private extension BankAppManager {
    func showMenu() {
        print("1: 은행 개점")
        print("2: 종료")
        print("입력 : ", terminator: "")
    }
    
    func openBank() {
        var clients: [Client] = BankSimulator.makeVirtualClients()
        
        var bank = Bank()
        
        for _ in 1...clients.count {
            let client = clients.removeFirst()
            bank.meet(client)
        }

        bank.reportSummary()
    }
}
```

### Bank.swift
```swift
struct Bank {
    private var totalProcessingTime: Double = 0.0
    private var totalDoneClient = 0
    
    private let tellerA = BankManager()
    
    private var clientQueue = ClientQueue<Client>() {
        didSet {
            arrangeClient(to: tellerA)
        }
        willSet {
            totalDoneClient += 1
        }
    }

    func reportSummary() {
        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalDoneClient)명이며, 총 업무시간은 \(String(format: "%.2f", totalProcessingTime))초입니다.")
    }
    
    mutating func meet(_ client: Client) {
        clientQueue.enqueue(client)
    }
    
    private mutating func arrangeClient(to bankManager: BankManager) {
        guard let client = clientQueue.dequeue()?.data else {
            return
        }
        
        bankManager.processRequest(from: client)
        
        totalProcessingTime += client.request.processingTime
    }
}
```

2022-07-05 06:28 UTC, leejun6694 approved these changes
LGTM

2022-07-05 06:28 UTC, merged