은행 창구 매니저 [STEP3] Kiwi, Kay
yagom-academy/ios-bank-manager pull request #201
Opened 2022-07-05 08:13 UTC by kiwi1023

안녕하세요~!! @corykim0829 😁
많이 어려웠던 STEP3 PR 보냅니다 !!
부족하지만 잘 부탁드리겠습니다~!! 감사합니다!

# 은행 창구 매니저 STEP 3

# 파일 및 함수 설명:

## Bank 🏦 :
프로젝트에서 요구하는 은행의 역할이 현실세계의 은행과 조금 다른점이 있습니다.
해당 Bank클래스의 역할은 BankManager(은행원), Customer(고객)에서 하지 않는 모든 업무를 수행하고 있습니다. Bank클래스를 크게 3가지로 나누면 아래와 같습니다.
1. 은행의 개점과 종료를 사용자에게 입력받아 해당 작업 수행.
2. 임의의 수 생성 후 해당 수만큼 고객을 큐에 넣어주는 작업.
3. 업무를 고객의 요구에 따라 나눠 BankManager가 수행하도록 하는 작업.

- inputMenu: 은행이 개점을 하거나 종료를 할 때 사용자에게 입력에 필요한 정보를 제공하는 메서드
- generateRandomNumberOfCustomers: 프로젝트의 요구사항에 따라 10이상 30이하의 임의의 수를 생성하고 numberOfCustomers 프로퍼티에 대입 역할의 메서드
- insertCustomersIntoQueue: 생성된 임의의 수 만큼 고객을 생성해 큐에 넣어주는 메서드.
- distributeTask: 고객의 요구에 따라 업무를 처리하는 메서드.
- openBank: 사용자로부터 "종료"입력을 받지 않는 이상 계속 은행 업무를 수행하는 메서드.
 
## BankManager 👩‍💻 :
고객들의 업무를 처리하는 기능을하는 클래스

- handleDepositCustomers: 예금업무에 관한 기능을 담은 메서드 이기때문에 BankManager의 역할에 부합하여 해당 클래스에 구현하였다.
- handleLoanCustomers: 예금업무와 마찬가지로 대출업무도 BankManager의 역할이라 생각하여 해당 클래스에 구현하였다.

## Customer 🧑🏻‍💼 :
- 고객번호와 고객의 업무를 프로퍼티로 갖는 클래스

# 배운개념 📚 :
- DispatchSemaphore
- DispatchGroup

# 궁금한점 ❓ :

- 저희가 BankManager 클래스 내 handleDepositCustomers와 handleLoanCustomers 메서드에서 DispatchQueue.global().async를 사용해 아래와 같이 group.notify 함수 내 파라미터에 .global()을 넣어주었습니다.
- ![](https://i.imgur.com/9ONgOFU.png)
```swift=
group.notify(queue: .global())
``` 
- 하지만 파라미터에 .main을 넣으면 실행이 되다가 멈추게 되는데 이유를 찾지 못했습니다. 이 부분에 대해서 알려주시면 감사하겠습니다.

2022-07-05 15:23 UTC, corykim0829 requested changes
수고하셨습니다!!

GCD 쪽이 개념도 어렵고 코드도 어려워서 고생 많으셨습니다 🥲👏👏👏

main 쓰레드 관련해서 물어보신 부분은
세마포어와 main 쓰레드 관계를 한번 찾아보면 좋을 것 같습니다 :)

남겨드린 피드백 바탕으로 개선해봅시다!!

2022-07-05 15:23 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    private var bank: Bank
여기에 선언되어있는 bank 프로퍼티는 실제로 사용하고 있지 않네요..!

BankManager는 객체명만 봤을 때 bank의 상위 객체로써 Bank객체를 관리하는 역할을 할 것 같은데, 실제로 하는 일은 Bank의 일은 분리해서 하는 하위객체처럼 보입니다.

구조와 역할에 대해서 좀 더 고민해보면 좋을 것 같아요!

2022-07-05 15:23 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    private static let loanSemaphore = DispatchSemaphore(value: 1)
이런 구조에서는 은행원 요구사항이 변경된다면, 요구사항에 맞는 Semaphore value을 처리하기 위해서 다시 객체 코드를 작성해줘야할 것 같아요.
만약 외부에서 은행원 값이 넘어온다고 했을 때 어떻게 처리해야할지 고민해보면 좋을 것 같아요

2022-07-05 15:23 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private func inputMenu() {
이 함수에서는 실제로 input을 받지 않고 있어서 inputMenu라고 하기 보다는 출력에 관한 함수명으로 변경해야할 것 같아요!

2022-07-05 15:23 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func openBank() {
이 함수를 실제 사용하는 곳에서 보면,
let bank = Bank()
bank.openBank
가 되어서 은행 객체가 은행을 연다로 읽어져서 어색한 부분이 있습니다!
함수명이나, 변수명은 실제 사용하는 부분에서 한번 더 체크해보면 가독성을 올리는데 조금 더 도움이 됩니다! 참고하세요!

2022-07-06 01:38 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            if customer.business.name == "예금" {
business 기준으로 분기처리 해주었습니다!

2022-07-06 01:38 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private func distributeTask() {
은행원에게 일을 시키다라는 이름으로 변경해주었습니다!

2022-07-06 01:39 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    private var bank: Bank
해당 프로퍼티는 제거를 해주었습니다!

2022-07-06 01:39 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/WorkType.swift
> +enum WorkType: CaseIterable {
"Bank"라는 키워드를 추가해서 수정했습니다. 조금 더 구체적인 enum 타입명으로 바뀌어 가독성이 높아진것 같습니다!

2022-07-06 01:39 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private func inputMenu() {
printMenu로 이름 변경해주었습니다!

2022-07-06 01:40 UTC, kiwi1023 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func openBank() {
startwork로 이름을 변경해주어 은행객체 스스로 일을 시작한다는 느낌으로 설정해주었습니다!

2022-07-06 01:42 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    static var lineOfCustomers = BankManagerQueue<Customer>()
이전 코드에서  lineOfCustomers 큐는 Bank에서 선언되고, BankManager에서 사용되던 프로퍼티였습니다. 하지만 더 이상 사용하지 않아 제거 해주었습니다.

2022-07-06 01:42 UTC, KayAhnDS commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +    private static let loanSemaphore = DispatchSemaphore(value: 1)
연산프로퍼티로 만들어 주었습니다!

2022-07-06 13:21 UTC, corykim0829 approved these changes
Kay, Kiwi 수고 많으셨습니다!! 
제가 남겨드린 피드백은 참고만 하시고, 시간이 여유가 되면 고치면 좋을 것 같아요!

마지막 스텝 시작하기 전에 시간을 포함한 목표일정을 저에게 말씀해주시고 스텝 진행해주세요!!

2022-07-06 13:21 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +final class Customer {
final 명시 좋네요 👍

2022-07-06 13:21 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +                if input == "1" {
input 값도 상수로 정리하면 좋을 것 같습니다 :)
1, 2가 아닌 값이 들어가는 경우도 생각을 해줘야할 것 같아요 참고하세요!

2022-07-06 13:21 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    func runBusiness() {
구조나 함수 네이밍에 있어서 실세계에 있는것과 같이 동작이나 이름을 지으려고 하면, 나중에 더 혼란을 야기할 수 있어요. Business라는 부분은 실세계에서만 사용하는 단어같아서 말씀드려요! 참고만하세요 :)

2022-07-06 13:21 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +    private let loanSemaphore = DispatchSemaphore(value: BankWorkType.loan.semaphoreValue)
semaphore value 값을 상수로 처리하는 것도 좋은 방법이지만, 외부에서 주입할 수 있도록 하면 더 동적으로 대응할 수 있을 것 같아요! 참고하세요 :)

2022-07-06 13:21 UTC, merged