은행 창구 매니저 [STEP3] 현이, 그루트
yagom-academy/ios-bank-manager pull request #203
Opened 2022-07-05 09:44 UTC by Groot-94

@GREENOVER 안녕하세요 그린! 🍀
현이@seohyeon2 와 그루트@Groot-94 입니다! 🧏‍♂️
Step 3 PR 보냅니다! 이번 프로젝트 잘 부탁드립니다!
## 📌 배경
- 은행 창구 매니저 앱
- 고객 타입 및 업무를 처리하는 타입 구현
## 📌 작업 내용
### BankStatus
- 은행 영업 및 종료에 대한 타입을 구현했습니다.
### BankBusiness
- 은행 업무 및 시간에 대한 타입을 구현했습니다.
### ConsolManager
- 콘솔에서 이루어지는 작업들을 구현했습니다.
## 📌 테스트 방법
- `main` 파일을 실행하여 테스트 
## 📌 리뷰 노트
#### DispatchQueue와 OperationQueue 중 어떤 방식으로 큐를 구현할지 고민을 했습니다. 
- Operation의 경우 상태를 알려주는 메서드를 활용해 실행 상태를 알 수 있습니다.
또한 종속성 추가, 재사용, 취소, 일시 중지 등과 같은 작업을 진행할 수 있습니다.
고객 업무에 따라 다른 쓰레드에서 처리해주는 작업은 위와 같은 메서드가 필요없었기에 최종적으로 DispatchQueue를 사용하였습니다.

#### `notify()` 사용 시 DispatchGroup에 등록한 작업들이 끝나기를 기다리지 않고 다음 코드를 실행하는 문제가 있어 고민을 했습니다.
- notify 메서드는 DispatchGroup의 모든 작업이 끝나기를 기다렸다가 코드 블록을 실행시켜준다고 알고 있습니다.
원래는 코드 블록안에 `printCloseMessage()` 를 넣어줘서 호출하려고 했지만, 
`notify()` 메서드를 사용하는 순간 아래 사진과 같은 현상이 나타났습니다.
`wait()`를 사용하여 이 문제를 해결했지만 왜 `notify()`가 기다리지 않고 main의 다음 작업(`printStartMessage()`)을 실행하는지 궁금합니다!

- 실행 코드 
```swift
struct ConsolManager {
    func execute() {
    menuLoop:
        while true {
            printStartMessage()
            switch readLine() {
            case BankStatus.opening.menu :
                let totalCustomer = executeWork()
            case BankStatus.closed.menu :
                break menuLoop
            default :
                print("잘못된 입력입니다.")
            }
        }
    }

    func executeWork() -> Int {
        let bankManagers = DispatchGroup()
        // ... 코드 생략
        let totalCustomer = bank.customerQueue.count
        let startTime = CFAbsoluteTimeGetCurrent()
        
        // ... 코드 생략
        
        let totalTime = CFAbsoluteTimeGetCurrent() - startTime
        
        // ⭐️notfiy 사용 부분
        bankManagers.notify(queue: .main) {
            printCloseMessage(totalCustomer, totalTime)
        }
        return totalCustomer
    }
        
    // ... 코드 생략
}
```

<image src = "https://i.imgur.com/K8wBUhS.png" width="180" height="700">

2022-07-05 22:20 UTC, GREENOVER requested changes
@Groot-94 @seohyeon2 
스텝3까지 아주아주 잘 구현해주셨네요!! 
고생 많으셨어요🥳🥳🥳
기능 동작과 요구사항에 이상없고 짜임새 있게 잘 해주셨네요👍
그럼 궁금하신 부분을 여기 코멘트에서 답변 드리며 리뷰 코멘트로는 놓치셨던 부분만 체킹해보면 좋을것 같습니다!
***
### 칭찬 드리고 싶은 부분
- 코드 관심사를 잘 나눠주어 각 타입이 하는 역할이 명확해졌어요 💯
- 깔끔하고 간결한 코드로 가독성이 좋네요 💯
- 객체지향적이네요 💯
***
### 궁금하신 부분에 대한 저의 의견
- notify() 사용 시 DispatchGroup에 등록한 작업들이 끝나기를 기다리지 않고 다음 코드를 실행하는 문제가 있어 고민을 했습니다.
  - 요 부분에 대한 저의 의견을 말씀드리겠습니다..!
  우선 디스패치 그룹을 사용하려면 디스패치큐들이 해당 그룹에 enter가 되야하고 작업이 비동기적으로 처리된 후 leave를 통해서 빠져나와야하는걸로 알고 있어요. 그렇기에 위 예시로 해주신 코드만 본다면 사실상 `group.enter(), group.leave()`와 같은 처리가 보이지 않는데 이와 연관이 있지 않을까요??
즉 해당 구조에서는 전체적인 업무의 시작과 끝에서 만들어둔 그룹을 이용하려면 enter와 leave를 통해 실제적인 사용처리가 있어야할것 같아 보여요.
그렇다면 원하시던 notify 사용이 문제없을거라 생각합니다🙋🏻
해당 notify를 정의한 코드 이전에 앞서 말한 업무 처리들이 쭈욱 다 이뤄지게끔 구성하면 원하는 결과를 도출할 수 있을거라 생각해요!
이와 관련해서 여러분과 동일하다고 생각되는 문제에 대한 레퍼런스를 공유드립니다!
https://stackoverflow.com/questions/49376157/swift-dispatchgroup-notify-before-task-finish
***
이번 스텝에서 요구하는 부분은 전부 소화하셨다고 생각합니다!
잘해주셔서 크게 코멘트 드릴께 없는 스텝이였네요🥲
다만 활동학습때 하셨을거라 생각되는? 플레이그라운드 코드도 같이 딸려들어간것 같습니다..!
필요없는 파일이라면 제거되면 좋을것 같아요ㅎㅎ
고생 많으셨고 제거되면 리뷰 재요청 해주세요!
확인 후 다음 스텝으로 바로 넘어가시죠🙌

2022-07-06 05:37 UTC, Groot-94 commented on BankManagerConsoleApp/MyPlayground.playground/Contents.swift
> +import Foundation
삭제했습니다!

[5c83327](https://github.com/yagom-academy/ios-bank-manager/pull/203/commits/5c8332776b0bd343a244886556d65ca1872696a6)

2022-07-06 05:42 UTC, Groot-94 commented on BankManagerConsoleApp/BankManagerConsoleApp/Consol/ConsolManager.swift
> +                let startTime = CFAbsoluteTimeGetCurrent()
3명의 은행원이 동시에 업무를 시작하고, 대출과 예금업무의 끝나는 시점이 다르기 때문에 각각의 상대적인 시간을 구하는 방법이 아닌, 가장 마지막에 끝난 업무의 시간을 기준으로 총 업무시간을 구해야한다고 생각했습니다.

2022-07-06 08:53 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
>          (0..<Int.random(in: 10...30)).forEach { number in
주입으로 수정했습니다! 

[4361d1b](https://github.com/yagom-academy/ios-bank-manager/pull/203/commits/4361d1b52df458b4efff33385d73159c4949ee41)

2022-07-06 08:54 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Consol/ConsolManager.swift
> +    func executeWork() -> Int {
없습니다..!

앞에 private 붙여서 수정했습니다!
[54bee7b](https://github.com/yagom-academy/ios-bank-manager/pull/203/commits/54bee7b5bd847690e157bfb66816ab7e93eec2d1)

2022-07-06 08:54 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Consol/ConsolManager.swift
> +            var customer: Customer
값 변경 될 일이 없어서 상수로 수정했습니다!

[54bee7b](https://github.com/yagom-academy/ios-bank-manager/pull/203/commits/54bee7b5bd847690e157bfb66816ab7e93eec2d1)

2022-07-06 08:56 UTC, seohyeon2 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
>  import Foundation
불필요한 코드라 삭제했습니다!

[6298e73](https://github.com/yagom-academy/ios-bank-manager/pull/203/commits/6298e7366171129015cfb1148f48f25924144fa0)

2022-07-06 23:28 UTC, GREENOVER approved these changes
고생 많으셨습니다!
제가 테스트 시 놓친 부분까지 바로 잡아 주셨네요👍👍👍
최종 스텝으로 넘어가시죠!ㅎㅎ

2022-07-06 23:28 UTC, merged