은행 창구 매니저 [STEP3] 언체인, 백곰
yagom-academy/ios-bank-manager pull request #205
Opened 2022-07-06 06:08 UTC by unchain123

# 은행 창구 매니저 STEP3 PR
@jryoun1 
안녕하세요 제이크 
세번째 PR입니다. 이번에도 잘 부탁드리겠습니다.

## 코드설명
- LinkedList
  - count: BankItemQueue에 있는 고객의 수를 반환해줍니다
- Bank
  - depositSemaphore: 예금업무를 처리할 은행원의 수(쓰레드 수)
  - loanSemaphore: 대출업무를 처리할 은행원의 수(쓰레드 수)
  - giveTask(): while let 문 안에 은행원이 업무 처리하는 방식을 switch문으로 대출업무인지 예금업무인지 구분하여 처리해주었고 각 업무는 Semaphore 를 사용해 접근할수있는 스레드수를 제한해 예금업무는 2개 대출업무는 1개 즉 은행원의 숫자로 지정해주고 비동기 그룹으로 묶은후 wait 처리해주었습니다.
- BankManager
  - 은행업무시 지연처리를 usleep -> Thread.sleep 으로 변경하였습니다.
  
## 고민한점

- 비동기적으로 업무를 처리할 때 단순히 async만 사용했을 때는 그 코드블럭만 글로벌 쓰레드로 보내고 그 뒤의 함수들은 작동하는 현상이 발생해서 우리가 원하는 코드블럭을 그룹으로 만든 뒤 그룹에 wait()메서드를 붙여줘서 해결을 했습니다.

| 첫번째생각 | 두번째 생각 | 최종 선택 사항 |
| :--------: | :--------: | :--------: |
| <img src ="https://i.imgur.com/j6tSCXR.png" width = 350>| <img src ="https://i.imgur.com/2sbE9Ku.png" width = 350>     | <img src ="https://i.imgur.com/xNPfLO5.png" width = 350>   |
|  <img src ="https://i.imgur.com/4cZkOLr.png" width = 350 height = 200>  |<img src ="https://i.imgur.com/11IYe0P.png" width = 350 height = 400>     | <img src ="https://i.imgur.com/9XYGHIA.png" width = 350>  |
|  처음 생각했던 부분인데 <br> 단순하게 은행원이 업무를 하는 스위치 구문에만 <br> 비동기를 걸어줘서 바로 스레드로 <br>넘기고 뒤의 코드를 <br> 진행해 버렸습니다. |   두번째로 생각했던 부분 입니다.<br> 스위치문을 디스패치워크아이템으로<br> 묶어주어서 asyncandWait를<br> 해줬습니다.<br> 비동기로 처리된 후 <br> 작업이 끝나기를 <br>기다릴것이라고 생각했었는데<br>아이템으로 묶어준<br>내부의 작업을 하나씩 기다리면서<br>sync와 비슷하게 작동하는<br> 것을 확인했습니다. | 최종적으로 해결하게 된<br> 방법입니다.<br> async(group: bankingroup)<br>으로 묶어준 그룹을 <br> wait()메서드를 이용해서 내부의 작업이 <br>다 끝날 때까지 기다리도록 했습니다. |

## 궁금한점
- 업무시간 설정을 하는 부분에서 기존에 사용했던 단순 곱하기 식을 바꿔주었습니다.
- CFAbsoluteTimeGetCurrent함수를 이용해서 현재의 시간을 측정하고 함수실행이 끝난 뒤에 현재의 시간에서 시작할 때의 함수시간을 빼줌으로써 전체 업무시간을 입력해 주었는데 Date타입을 넣어서 하는 방법도 있는 것으로 확인했는데 둘 중에 더 선호되는 방식이 있는 건지 지금 해준 방법으로도 사용을 하는게 맞는건지 궁금합니다. 아니라면 다른 더 좋은 방법이 있을까요?

| 시작시간 | 종료시간 |
| -------- | -------- |
| ![](https://i.imgur.com/f6mnPWF.png) | ![](https://i.imgur.com/LR8TM18.png) |

2022-07-07 13:00 UTC, jryoun1 requested changes
@unchain123 @Baek-Gom-95 
step3 고생하셨습니다 👏

네이밍과 기존에 있던 타입을 사용하지 않아서 코멘트 드린 부분이 거의 대부분인 것 같고 나머지는 잘 진행 해주신 것 같습니다! 👍🏻
몇 가지 코멘트 남겼으니 확인부탁드려요 🙏🏻

### 궁금한점
> 업무시간 설정을 하는 부분에서 기존에 사용했던 단순 곱하기 식을 바꿔주었습니다.

이 부분은 실제 업무시간으로 계산이 되어야하므로 제대로 변경해주신 것 같네요!

> CFAbsoluteTimeGetCurrent함수를 이용해서 현재의 시간을 측정하고 함수실행이 끝난 뒤에 현재의 시간에서 시작할 때의 함수시간을 빼줌으로써 전체 업무시간을 입력해 주었는데 Date타입을 넣어서 하는 방법도 있는 것으로 확인했는데 둘 중에 더 선호되는 방식이 있는 건지 지금 해준 방법으로도 사용을 하는게 맞는건지 궁금합니다. 아니라면 다른 더 좋은 방법이 있을까요?

절대 시간을 사용해서 잘 계산해주신 것 같습니다. 👍🏻 
둘 중에 뭐가 선호되는 방식인지는 저도 잘 모르겠지만 저라면 CFAbsoluteTimeGetCurrent을 통해서는 지금과 같이 실제 함수, 혹은 알고리즘 등의 실행시간을 계산하기 위해서 사용할 것 같고, date를 통해서는 좀 더 날짜와 관련된 걸 비교하거나 계산하는데 사용할 것 같네요. 
두 방법 모두 시간을 측정할 수 있으므로 구현이 쉽거나, 명시적인 것을 사용하시면 될 것 같습니다.

2022-07-08 01:44 UTC, Baek-Gom-95 commented on BankManager.swift
> +    func handleBanking(for customer: Customer) {
Customer 타입의 티켓넘버를 출력해줘야 되서 businessType으로 해결이 불가능 할거같습니다

2022-07-08 01:46 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let depositSemaphore = DispatchSemaphore(value: NumberOfBankManager.deposit.rawValue)
DispatchSemaphore 는 자원에 접근할 수 있는 스레드의 수를 제어해주는 역할을 합니다.

2022-07-08 01:48 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let bankingGroup = DispatchGroup()
DispatchGroup은 비동기적으로 처리되는 작업들을 묶어 주어서 그룹 단위로 작업 상태를 추적할 수 있는 기능입니다.
비동기적으로 처리되는 작업들은 완료시점을 정확히 파악하기가 힘들기 때문에 Group으로 묶어서 완료시점을 추적하고 그후에 특정 동작을 하도록 해줄 수 있습니다. 
이번에 저희가 사용한 메서드는 wait()로 Group으로 묶여있는 비동기 작업들이 끝나기 전까지 기다리도록 하게 만드는 메서드 입니다.

2022-07-08 01:49 UTC, unchain123 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let depositSemaphore = DispatchSemaphore(value: NumberOfBankManager.deposit.rawValue)
Race Condition을 방지하기 위해 사용했습니다.

2022-07-08 01:51 UTC, Baek-Gom-95 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let loanSemaphore = DispatchSemaphore(value: NumberOfBankManager.loan.rawValue)
각각의 세마포어가 예금과 대출 업무에 접근할수있는 은행원의 수 라고 생각했습니다 그래서  해당 코드를 보시면
```swift
DispatchQueue.global().async(group: bankingGroup) {
                switch completeCustomer.bankingType {
                case .deposit:
                    self.depositSemaphore.wait()
                    self.bankmanager.handleBanking(for: completeCustomer)
                    self.depositSemaphore.signal()
                case .loan:
                    self.loanSemaphore.wait()
                    self.bankmanager.handleBanking(for: completeCustomer)
                    self.loanSemaphore.signal()
                }
            }
```
비동기로 작업을 진행하는데 세마포어를 따로 만들어주지 않는다면 대출업무에도 은행원이 2명이되는 것 처럼 보여서 따로 만들어
주었습니다

2022-07-08 09:07 UTC, jryoun1 approved these changes
@unchain123 @Baek-Gom-95 
수정하신 부분 확인했습니다!
잘 수정해주셨네요 👍🏻 

네이밍 관련해서 한가지 정도만 코멘트 남겼습니다!
해당 부분은 필수 수정은 아니라서 여기서 step3는 merge하도록 하겠습니다!
2주 동안 프로젝트 진행하시느냐 고생 많으셨습니다!!

2022-07-08 09:07 UTC, merged