은행창구매니저 [STEP 3] 웡빙, 예톤
yagom-academy/ios-bank-manager pull request #208
Opened 2022-07-06 07:25 UTC by yeeton37

안녕하세요 @ryan-son! 웡빙(@wongbingg) 과 예톤(@yeeton37)입니다! 
step3 PR 보냅니다. 잘부탁드립니다 :fire::fire:

# Step3 

### 1. 작업 내용
- CustomerQueue에 쌓여있는 손님들을 한명씩 빼서 각 손님마다 원하는 업무에 맞게 해당 업무 줄로 보내주었습니다.
- 각각의 업무 줄은 CustomDispatchQueue로 만들어 주었습니다.
- 대출담당 큐에서는 접근가능 스레드 수의 제한을 1로 설정 해주었습니다.
- 예금담당 큐에서는 접근가능 스레드 수의 제한을 2로 설정 해주었습니다.
---
- Business Enum 타입 선언
    - loan
        - name
        - processTime
    - deposit
        - name
        - processTime
- Business 별 CustomDispatchQueue 상수 생성 
    - loanBusinessQueue
    - depositBusinessQueue 

- Business 별 DispatchWorkItem 생성
    - `makeWorkItem()` 메서드 이용
    - loanWorkItem
    - depositWorkItem
- 작업시간 측정 
    - CFAbsoluteTimeGetCurrent() 를 이용하여 handleCustomer 메서드의 시작과 끝에 선언해주어 메서드 실행 시간을 측정 해주었습니다.

### 2. 스텝 핵심 경험

- [x] 동시성 프로그래밍 개념의 이해
- [x] 동시성 프로그래밍을 위한 기반기술(GCD, Operation) 등의 이해
- [x] 스레드(Thread) 개념에 대한 이해
- [x] GCD를 활용한 동시성 프로그래밍 구현
- [x] 동기(Synchronous)와 비동기(Asynchronous) 동작의 구현 및 적용

### 3. 고민한 점

1. 이번 프로젝트의 조건이 은행원 3명이 동시에 업무를 하기 때문에 큐와 스레드를 어떻게 적절하게 분배해줄지에 대해서 고민했습니다. 첫 번째 생각한 방법은 큐를 1개로 설정해주고 큐에서 스레드 3개로 보내는 것을 은행원 3명이라고 보는 방법이었고, 두 번째는 큐를 2개로 설정해서 하나의 큐는 loan 업무를 하고 하나의 큐는 deposit 업무를 하도록 나누어주는 방법이었고, 세 번째는 큐를 3개로 설정해서 각 큐를 은행원이라고 보는 방법이었습니다.
    - 이 중에서 저희는 큐를 예금 업무를 하는 큐, 대출 업무를 하는 큐 두개로 나누어주어 예금 업무를 하는 큐는 semaphore value를 2로 지정해주어 공유자원에 접근하는 스레드가 2개가 되도록 해주었습니다. 마찬가지로 대출 업무를 하는 큐는 semaphore value를 1로 지정해주어 공유자원에 접근하는 스레드가 1개가 되도록 해주었습니다.
    - 아래 그림과 같이 큐와 스레드의 구조를 작성해봤는데 잘 작성한 것인지 라이언에게 여쭤보고 싶습니다!
    
 ![image](https://user-images.githubusercontent.com/98514397/177487869-9b899ec7-2e62-4801-83df-6561e8bcdc6a.jpeg)
 

### 4. Trouble Shooting
- end message가 출력되는 위치에 대한 오류
- 맨 처음에 group을 사용하지 않고 출력을 했더니 아래와 같은 오류가 발생
[오류 발생한 콘솔창]

<img width="663" alt="스크린샷 2022-07-06 오후 4 03 34" src="https://user-images.githubusercontent.com/98514397/177489752-91345ea6-fbe4-4d26-847a-4abca3d3942f.png">

- 큐의 작업들이 모두 끝난 뒤에 업무 그룹으로 묶인 작업들이 언제끝나는지에 대해 시점을 알고, 그 이후에 end message를 `group.wait()`을 사용해주었습니다.
- 결론적으로 아래와 같이 정상적으로 end message가 출력되는 것을 확인할 수 있었습니다.

<img width="638" alt="스크린샷 2022-07-06 오후 4 08 23" src="https://user-images.githubusercontent.com/98514397/177490554-dd3c5182-aa6c-4084-ac39-0495b710ff2e.png">

### 5. 배운 키워드
`CFAbsoluteTimeGetCurrent`, `DispatchGroup`, `DispatchSemaphore`, `DispatchWorkItem`, `CaptureList`

### 📄 6. 참고
[참조 블로그](https://babbab2.tistory.com/83)

이상 PR 마치겠습니다 잘부탁드립니다 🍀🍀🍀

2022-07-07 19:26 UTC, ryan-son requested changes
예톤, 웡빙! 빨리 돌아오셨네요. PR이 자세하게 작성되어 있어 여러분의 사고를 따라가기 편했습니다.

결과물과 작성해주신 내용을 미루어보아 GCD를 포함해 동시성에 관련된 개념들을 잘 파악하고 계신 것으로 생각되네요. 구현해주신 방향으로는 이미 경험해보셨으니 이후에 기회가 있으시다면 `NSLock`, `OperationQueue` 등 다른 개념도 살펴보시고, `DispatchGroup`의 enter, leave, notify는 무엇이고 어느 경우에 사용할 수 있을지를 학습해보시면 더 좋을 것 같습니다.

# 질의응답
>   * 아래 그림과 같이 큐와 스레드의 구조를 작성해봤는데 잘 작성한 것인지 라이언에게 여쭤보고 싶습니다!

- Semaphore value 제한에 따라 loan queue는 기존의 업무를 끝내지 못하면 다음 업무를 스레드에 dispatch 해주지 못합니다. deposit queue도 동시에 두 개의 스레드를 이용할 수 있을 뿐 loan queue의 사정과 다르지 않죠. 스레드가 일을 하고 있으면 다음 일을 분배받지 못합니다. 그리고 큐가 반드시 사용하던 스레드에 일을 맡긴다는 보장은 없으니 특정한 스레드에 계속해서 업무를 분배하는 그림은 적절하지 않을 수 있어요. GCD는 스레드에 업무를 분배하는 복잡한 과정을 추상화 해놓은 것이기에 조금 더 면밀히 살펴보아야 이해가 잘 되실거에요. 오늘 시간 되실 때 회의실에서 관련 개념을 함께 살펴보도록 하시죠~

# 테스트 정상화하기
- 로직을 고치다보니 테스트가 동작하지 않는데 확인해주세요~ 보통은 PR과 같은 작업에서 CI (Continuous Integration) 결과로 문제 여부를 자동적으로 파악할 수 있지만, 지금은 제출 전에 테스트가 잘 돌아가는지 수동으로 확인해보셔야 할 것 같아요. 기왕이면 공들여 작성해둔 테스트를 최대한 활용해봅시다~

 피드백이 많지 않으니 오늘 이야기하면서 해결하고 바로 머지해도 괜찮을 것 같아요. 고생 많으셨습니다 !

2022-07-10 03:26 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        let workItem = DispatchWorkItem { [self] in
클로저 안에서 클로저 바깥의 값을 가져와서 사용할 경우, 그 값이 나중에 바뀌게 된다면 바뀐 값으로 클로저 내부에서 적용이 되는데, 이를 방지하기 위해 그 순간의 값을 캡쳐 합니다! 이 경우도 마찬가지로 참조하는 값이 바뀌는 경우를 대비하여 캡쳐리스트를 이용했습니다!

2022-07-10 03:34 UTC, yeeton37 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private let depositSemaphore = DispatchSemaphore(value: 2)
loanQueue의 세마포어를 지우고, serial queue로 만든 다음 디버깅을 해본 결과, 이전에 해주었던 방식과 비슷한 결과값이 도출되었습니다. 이렇게 두 방식이 같은 결과를 내는 경우 어떤 기준을 가지고 선택하면 좋을지 라이언에게 여쭤보고 싶습니다!

2022-07-10 03:35 UTC, yeeton37 commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/NameSpace.swift
> +}
라이언의 말씀대로 타입 이름이 NameSpace인 것은 한눈에 파악하기 어려울 것 같다는 생각이 들었습니다. 
따라서 enum의 이름을 Menu로 변경하고, case one-> startProcess, two-> endProcess로 변경해주었습니다!

2022-07-10 03:38 UTC, wongbingg commented on BankManagerConsoleApp/BankManagerConsoleApp/Enum/Business.swift
> +    }
말씀주신데로 통일성있게 작성 해주기위해 name 계산프로퍼티를 processTime 계산프로퍼티의 형태와 같게 만들어 주었습니다

2022-10-06 08:59 UTC, closed without merging