은행 창구 매니저 [STEP1] 토털이, 애런
yagom-academy/ios-bank-manager pull request #214
Opened 2022-10-31 13:01 UTC by tottalE

@junbangg 
안녕하세요!
반갑습니다 알라딘:) 이번 스탭은 간단했지만 잘 부탁드립니다 :)

## 개발한 내용
1. Node 구현

2. LinkedList 구현

3. Queue 구현

4. CustomerQueueTest 구현

## 고민한 점
### 1. 테스트시 접근 제어자로 인한 문제
- 테스트시에 private 접근 제어자에 접근할 수 없어, 임시로 접근 제어자를 풀어준 후에 테스트를 하고, 이후 접근제어자를 붙여주었는데 맞는 방법인지가 궁금합니다!!
- 테스트 전
```swift
final class CustomerQueue<T> {
    let customerList = LinkedList<T>()
    
...
}

 // 테스트 코드
func test_one을_deque했을_때_Aaron이_나오는지() {
        sut.customerList.head = Node(one)
        let result = sut.dequeue()
        XCTAssertEqual(result, "Aaron")
}
```
    
- 테스트 후
    
```swift
final class CustomerQueue<T> {
    private let customerList = LinkedList<T>()
    
...
}
```
### 2. Customer Queue구현시 Linked List의 사용에 대한 고민
```swift
final class CustomerQueue<T> {
    private let customerList = LinkedList<T>()
    ...
}
```
위와 같이 Liked List의 타입을 미리 구현한 다음 은행 방문 손님을 담는 큐에서 해당 타입의 프로퍼티를 구현했습니다.
Customer Queue자체를 Linked List로 할지 해당 타입의 프로퍼티를 내부에 구현할 지 고민 되었지만 어떠한 타입의 정의는 범용적이여야 한다고 생각되어 프로퍼티를 가지는 방식으로 구현했습니다. 둘중 어떠한 방식이 더 적합할지 고민되었습니다!🤔🤔🤔🤔🤔

2022-11-02 12:23 UTC, junbangg requested changes

2022-11-02 12:23 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        self.tail = node
여기서는 `self` 를 사용해주셨네요???? 다른 곳은 안쓰이고 있는데 `self` 를 사용하신 기준?같은게 있으실까요??

2022-11-02 12:23 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        self.tail = node
`self.tail = node`  가 두번 있는데 이걸 한번만 쓸 수 있도록 리팩토링 할 방법은 없을까요??🤔

2022-11-02 12:23 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        self.tail = nil
`tail` 도 `nil` 처리가 필요한가요???🤔

2022-11-02 12:28 UTC, junbangg commented
```
1. 테스트시 접근 제어자로 인한 문제
```
테스트 할때 이게 항상 문제죠:) 
실제 코드에서는 `private` 인게 맞다면 그거는 테스트에서 제외시켜서라도 지키는게 맞지 않을까 싶습니다 개인적으로🤔
테스트는 어떠한경우에도 실제 코드와는 분리되어야하고 영향을 끼치면 안되니까요! 
```
2. Customer Queue구현시 Linked List의 사용에 대한 고민
```
질문 주신 내용이 `Queue` 가 지금처럼 `Linked List` 프로퍼티를 갖고 있게 구현하는게 맞을까? 인거죠??
저는 지금이 맞다고 생각하긴 합니다:) 
두분은 어떤 이유로 `Queue`를 `LinkedList` 로 바로 구현 안하고 지금 처럼 하신걸까요??

2022-11-03 10:13 UTC, tottalE commented on BankManagerConsoleApp/CustomerQueueTest/CustomerQueueTest.swift
> +    let two = "Aladin"
네 반복되는 상수 선언을 피해주기 위해서 전역으로 선언해 주었습니다!

2022-11-03 10:36 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        }
네 생략해 주었습니다 :)
> [d25de62](https://github.com/yagom-academy/ios-bank-manager/pull/214/commits/d25de627f38dcb8b4c0ec7b57effeda41d7a77a6)

2022-11-03 10:40 UTC, Hashswim commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +final class CustomerQueue<T> {
좀더 타입과 의미에 맞게 Queue로 수정했습니다!

2022-11-03 10:52 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        self.tail = nil
tail에서 가르키는 인스턴스가 있어 RC 카운트가 사라지지 않을 것 같은데 저희가 이해한 바가 맞나요?

2022-11-03 10:53 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        self.tail = node
`self.tail = node`가 한번만 쓰이도록 수정해 주었습니다!
> [eba1e9f](https://github.com/yagom-academy/ios-bank-manager/pull/214/commits/eba1e9f052f874584e140a9d039c101a3243da00)

2022-11-03 14:27 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            head = node
엇 이렇게 하면 의도한대로 연결이 되나요??? `isEmpty` 일때 `tail.next = node` 여도 되는건가요??🤔

2022-11-03 14:27 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
>      func pop() -> Node<T>? {
`pop` 는 스택의 마지막 원소를 뽑는 연산 이름 아닌가요??🤔

저번 리뷰때 놓친 부분이네요 😅

2022-11-03 14:49 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        self.tail = nil
넵 이해한것이 맞습니다!!
그럼 1->2->3->4 형태에서 `removeAll()` 을 호출하면 중간에 있는 2,3 은 어떤 동작으로 없어지는걸까요???

2022-11-03 15:02 UTC, Hashswim commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            head = node
함수 의미상 맞지는 않지만, isEmpty 값이 true여도 tail과 head에 알맞게 push 됩니다..
push시에 queue의 마지막에 넣고 isEmpty가 true라면 head에도 할당하면 된다고 생각했습니다..!

2022-11-04 07:16 UTC, merged