은행 창구 매니저 [STEP 1] 하모, SummerCat
yagom-academy/ios-bank-manager pull request #217
Opened 2022-10-31 14:52 UTC by lxodud

@wonhee009
안녕하세요, 라자냐! 은행 창구 매니저에서 함께하게 된 하모, 썸캣입니다.
STEP-1 구현 완료하여 PR보냅니다!!

## 고민했던 점
- 어떤 의존성 관리도구를 사용해야하는지에 대한 고민
    - SwiftLint를 사용하기 위해서 의존성 관리도구를 사용해야 했습니다.
    - Swift Package Manager(SPM)는 애플이 만든 First-Party Tool이기 때문에 가능하면 SPM을 사용해 보려고 했습니다.
    - 그런데 SwiftLint는 SPM을 제대로 지원하지 않아서 CocoaPods를 사용하게 되었습니다.

- `Undefined symbols:` 오류
    - BankManagerConsoleApp`과 같은 Command Line App에서는 `@testable import`로 타겟을 불러올 수 없어 오류가 발생했습니다.
    - 테스트 타겟에서 사용하는 파일들의 Target Membership에 테스트 타겟을 추가해주니 해결되었습니다.

- 타입구현 클래스 VS 구조체
    - `Node`의 경우 다른 요소들과 연결하기 위해서 참조값을 사용하기 때문에 class로 구현하였고, 내부에서 자기 자신의 타입을 가진 프로퍼티를 멤버로 가지고 있기 때문에 struct는 사용이 불가능합니다.
    - `LinkedList`, `Queue`의 경우 참조나 상속이 필요하지 않고, 의도하지 않은 데이터 변경을 방지하기 위해서 struct를 사용하였습니다. 

## 조언을 얻고 싶은 부분

- Queue와 LinkedList를 각각 구현해야 하는 이유
    - Queue 타입 구현을 위한 LinkedList 타입을 직접 구현하도록 되어 있어 Queue 타입과 LinkedList 타입을 별개로 구현해 주었습니다.
    - 하지만 그냥 큐를 LinkedList 구조로 구현해도 되지 않을까? 라는 생각이 들었고, Queue와 LinkedList를 각각 따로 구현했을 때와의 차이점이 무엇일지 고민해 보았는데 따로 구현했을 때의 이점이 크게 생각나지 않았습니다. 이 부분에 대한 라자냐의 의견이 궁금합니다.

2022-11-01 22:42 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요~

- 링크드리스트와 큐가 비슷해 보이긴 하지만 가지고 있는 의미가 다르다고 생각합니다. 큐는 무조건 선입선출인게 링크드리스트와 다른점이라고 생각하고요. 링크드리스트는 큐의 요소(element)를 구성하기 위한 것이고 선입선출에 대한 컨셉은 큐가 가져간다고 생각했습니다.

2022-11-01 22:42 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
```suggestion
    var isEmpty: Bool {
        return head == nil
    }
```
이렇게도 가능할거 같습니다.

2022-11-02 05:20 UTC, lxodud commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
오 훨씬 간결해졌네요!!
감사합니다 👍👍👍👍

2022-11-02 16:28 UTC, wonhee009 approved these changes
수고하셨습니다!

2022-11-02 16:28 UTC, merged