은행 창구 매니저 [STEP 1] 써니쿠키, inho
yagom-academy/ios-bank-manager pull request #219
Opened 2022-11-01 02:19 UTC by inho-98

@wonhee009 
안녕하세요 라쟈냐! 🙇🏻‍♀️🙇
Step1 PR드립니다.
잘부탁드립니다

## 📝 STEP 진행 중 경험하고 배운 것
- 단방향 `Linked-list` 자료구조
     ☑️ 단방향 연결리스트를 코드로 구현해보기
     ☑️ `Generic Type` 개념이해와 적용하기
- `Queue` 자료구조
     ☑️ `Linked List`를 이용한 `Queue` 타입 코드로 구현해보기
     ☑️ `Generic Type` 개념이해와 적용하기

## ⚒️ 코드 구현내용 
### 1️⃣ Node 
- `Generics` 타입의 데이터를 담을 `data`프로퍼티와 다음 노드 정보를 나타내는 `next`프로퍼티를 생성하였습니다.

### 2️⃣ LinkedList
- 큐 타입 구현을 위한 `LinkedList`타입을 구현했습니다.
- 첫번째와 마지막 노드를 담는 `head`, `last`프로퍼티를 생성하였습니다.
- 큐에 필요한 기능을 구현하기 위한 메서드들을 가지고 있습니다.
    - `append(datda:)`
    - `removeFirst()`
    - `removeAll()`

### 3️⃣ Queue
- 다양한 타입의 데이터를 담을 수 있도록 Generics를 이용하였습니다.
- 구현해야할 필수 기능들을 구현했습니다.
    - `isEmpty` 
    - `claer()`
    - `enqueue()`
    - `peek()` : 삭제없이 첫번째 노드의 데이터를 확인합니다.
    - `dequeue()`: 첫번째 노드를 삭제하고, 해당 데이터를 리턴합니다.

## 💭 고민한 부분
### `SwiftLint` 라이브러리 이용여부 
- 프로젝트 요구사항에는 없지만 아카데미 학습활동 중 의존성 관리도구를 이용해 현재 프로젝트에 `SwiftLint` 라이브러리를 적용해보자는 미션이 있었습니다.
- 코코아팟을 이용해 `SwiftLint` 라이브러리를 `BankManagerUIApp` 파일에 적용해 보았고, 실제 프로젝트 진행에서도 이 라이브러리 사용을 계속 유지할까 고민했습니다. 상의 후 배운내용을 경험해보자하여 `BankManagerUIApp`파일에서 적용시키기로했습니다.

### `SwiftLint` 라이브러리 데이터를 `git ignore`에 담아야할지 여부 
- 의존성 관리도구와 `git`을 사용할때, 소스코드를 담고있는 `Pods`폴더를 포함하여 푸쉬하게 되면 깃의 용량이 늘어나서 `git ignore`에 포함하는게 좋다고 생각하였습니다.
- 그런데 코코아팟에서 작성한 내용 중, `Pods` 폴더를 포함했을때 다른 사람이 `pod install`을 실행하지 않아도 해당 라이브러리를 사용수 있다는 장점을 확인할 수 있었습니다.
- 또한 라쟈냐가 사용하는 의존성관리도구의 종류에 관계없이 저희 코드를 확인할 수 있을 것 같다는 생각에 포함하였습니다.

2022-11-01 22:37 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요.
현재 pod 관련한 사항들도 같이 올라온거 같은데요. gitignore 이용해서 해당 사항들은 올라오지 않도록 설정 부탁드립니다.

2022-11-01 22:37 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
`last`는 호출 될때마다 currentNode부터 끝까지 탐색하는건가요?

2022-11-01 22:37 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
```suggestion
    var isEmpty: Bool {
        return head == nil
    }
```
로도 가능할거 같습니다.

2022-11-02 02:13 UTC, sunny-maeng commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
감사합니다 👏🏻

2022-11-02 02:17 UTC, sunny-maeng commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
추가로, 코멘트 남겨주신 Pod관련 사항들에 대해서도 수정했습니다
> 수고하셨습니다:) 코멘트 남겨두었으니 확인 부탁드려요. 현재 pod 관련한 사항들도 같이 올라온거 같은데요. gitignore 이용해서 해당 사항들은 올라오지 않도록 설정 부탁드립니다.

git ignore파일로 pod 관련한 사항들은 해당되지 않도록 하였습니다 감사합니다 😂

2022-11-02 02:17 UTC, inho-98 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
```swift
private(set) var last: Node<T>?
```
- `last`프로퍼티가 매번 끝까지 탐색하면 비효율적인것 같아서 위 코드처럼 직접 노드를 가리키도록 수정했습니다! `last`프로퍼티를 지정하기 위해서 `LinkedList`에 새로운 노드가 추가될때마다  마지막 노드를 가리키도록 `append(_:)`메서드의 로직도 함께 수정하였습니다.

2022-11-02 16:27 UTC, wonhee009 approved these changes
수고하셨습니다!

2022-11-02 16:27 UTC, merged