은행창구 매니저 [STEP 1] zhilly, 미니
yagom-academy/ios-bank-manager pull request #221
Opened 2022-11-01 05:19 UTC by leegyoungmin

안녕하세요 Tony(@Monsteel) 🙌🙌🙌🙌
이번 프로젝트 같이 하게 된 zhilly랑 미니입니다.
Step1 구현 완료되어서 PR 발송합니다.

### 고민했던 점
> `Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다.`의 의미

지난번 큐를 구현하는 과제에서는 Linked-list를 구현하는 방식을 활용하여서 큐를 구현하였습니다. 하지만 `Queue 타입 구현을 위한 Linked-list` 라는 구문을 보고 Queue를 구현하기 위한 새로운 타입을 구현하라는 의미인지에 대해서 고민하게 되었습니다. 이에 대해서 추상적인 자료구조를 구현하기 쉽고, 재사용성을 높일 수 있는 Linked-list 타입을 구현하였습니다. 또한, Linked-list 타입을 구현함으로써 재사용성을 높이는 것과 다른 코더가 보았을 때 이해하기 쉬운 코드 중 어떤 것을 활용해야 더 적절한 것인가에 대해서 고민했습니다.
 
> LinkedList는 `struct` vs `class`

LinkedList 타입을 정의하기 위해서 어떤 사용자 정의 타입을 활용하는 가에 대해서 고민하게 되었습니다. 저희가 사용하는 Node 타입은 ARC를 이용해서 관리 해줘야 한다고 생각했습니다. 하지만, LinkedList는 큐 타입 내부에서 선언되어서 활용되는 변수이기 때문에 ARC로 관리되지도 않고, 추가적인 상속을 구현하지 않을 것이라고 생각하였습니다. 그래서 애플에서 기본적으로 struct를 사용하라고 권장하기 때문에 우선적으로 struct로 구현하였습니다.

> `SwiftLint` 라이브러리를 SPM으로 관리할지, CocoaPods으로 관리할지

SPM이 first-party이기 때문에 쉽게 관리할 수 있다고 생각하였습니다. 하지만, CocoaPods 이 제일 기본적인 방법이라고도 생각했고, 라이브러리도 제일 많기 때문에 이번에 프로젝트에 `SwiftLint`를 추가할 때에는 CocoaPods을 이용해보았습니다.

### 조언을 얻고 싶은 부분
> 현업에서 컨벤션을 조율하는 방법
- 현업에서는 컨벤션을 어떻게 조율하나요?
- 컨벤션을 조율하기 위해서 `SwiftLint`와 같은 외부 라이브러리를 적극 활용하나요?
- 만약 활용한다면, 내부에 구현되어 있는 규칙들을 활용하게 되나요? 아니면, 직접 규칙을 구현하여서 활용하게 되나요?

> 만약 여러개의 라이브러리를 사용할 때 어떤 라이브러리는 CocoaPods만 지원하고 다른 라이브러리는 SPM만 지원한다고 했을 때, 하나의 프로젝트에서도 CocoaPods과 SPM을 같이 사용하기도 하나요??

2022-11-02 02:47 UTC, Monsteel requested changes
zhilly랑 미니 :) 반갑습니다!
이번에 함께하게된 Tony라고 합니다!

Step1 수고 많으셨습니다! 👍 

첫번째 스텝은 전체적으로 잘 구현해 주셨고, 생각해봄직한 포인트들이 몇가지 있어서 코멘트로 남겨보았습니다!

조언을 얻고 싶은 부분에 대한 제 생각은 아래에 적어볼게요!

> 현업에서 컨벤션을 조율하는 방법
> * 현업에서는 컨벤션을 어떻게 조율하나요?
> * 컨벤션을 조율하기 위해서 SwiftLint와 같은 외부 라이브러리를 적극 활용하나요?
> * 만약 활용한다면, 내부에 구현되어 있는 규칙들을 활용하게 되나요? 아니면, 직접 규칙을 구현하여서 활용하게 되나요?

1. zhilly와 미니의 생각은 어떠신가요? 현업에서의 조욜 방법이 꼭 정답은 아닙니다. 지금 처해있는 상황을 고려해서, 두분에게 적절한 좋은 방법은 무엇인지 고민해보는것도 좋을것 같아요 👍 

2. 많은 사람들이 모이거나, 규칙이 많아지면 관리하기 어려워지기 마련인데요, Swiftlint와 같은 다른 도구를 활용해서 활용하긴 합니다!

3. 만들어져 있는 규칙들은 적극적으로 활용하고 그렇지 않다면, 직접 규칙을 구현해 활용하는 방법도 검토할 수 있을것 같아요. 하지만 저희 회사에서는 직접 규칙을 구현해서 활용한 사례는 아직 없네요 👍


> 만약 여러개의 라이브러리를 사용할 때 어떤 라이브러리는 CocoaPods만 지원하고 다른 라이브러리는 SPM만 지원한다고 했을 때, 하나의 프로젝트에서도 CocoaPods과 SPM을 같이 사용하기도 하나요??

* 저희 회사에서는 Cocoapods으로 일원화 하여 관리포인트를 하나로 일원화했습니다.
지원하지 않는 라이브러리의 경우 podspec을 custom하게 정의하여, coocapods에서 사용할 수 있도록 했습니다.

2022-11-02 02:47 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func append(data: T) {
mutating 키워드는 어떤 의미를 가지는 키워드인가요~?!

2022-11-02 02:47 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +struct CustomerQueue<T> {
`그래서 애플에서 기본적으로 struct를 사용하라고 권장하기 때문에 우선적으로 struct로 구현하였습니다.`
애플에서 struct사용을 권장하는 이유는 무엇일까요?

2022-11-03 01:13 UTC, leegyoungmin commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func append(data: T) {
`mutating` 키워드는 값타입 속성에서 수정을 하기 위해서 붙이는 키워드 입니다. 이것이 의미하는 바는 `self` 프로퍼티에 새로운 인스턴스를 할당할 수 있다는 것을 의미하게 됩니다.

2022-11-03 01:25 UTC, zhilly11 commented on BankManagerConsoleApp/BankManagerConsoleApp/CustomerQueue.swift
> +struct CustomerQueue<T> {
Swift의 구조체에는 다른 언어의 클래스로 제한된 많은 기능을 제공한다고 하고 있습니다. 구조체에 저장 프로퍼티, 연산 프로퍼티, 메서드를 사용할 수 있고, 또한 Swift의 구조체는 프로토콜을 채택하여 기본 구현을 통해 작성할 수 있습니다. 그리고 Swift의 표준 라이브러리들의 데이터들 역시도 대부분 구조체로 작성되어 있기도 합니다.

따라서 클래스를 사용해야 할 명확한 이유가 없다면 기본값으로 구조체를 사용하는 게 맞는다고 생각합니다.

2022-11-03 02:10 UTC, merged