은행 창구 매니저 [STEP 2] 망디, 메네
yagom-academy/ios-bank-manager pull request #229
Opened 2022-11-03 02:34 UTC by JaeKimdev

@1Consumption
안녕하세요, 올라프
STEP2 완료되어 PR드립니다.

이번에도 아낌없는 리뷰 부탁드립니다. 🙏🏻

## 고민했던 점

- Bank 타입에서 은행을 열었을 때 처리할 작업을 나타내는 메서드 네이밍을 `open`으로 하려고 하다가 `open`이 시스템 예약어라서 다른 이름을 사용하기 위해 `openUp`이라는 이름으로 설정해 주었습니다.

- UIApp에서 만들었던 파일을 ConsoleApp으로 가져오는 방법을 고민해 보았습니다.
    - UIApp에서 만든 Node, CustomerQueue파일을   
ConsoleApp으로 복사하기위해 파일을 끌어서 놨는데   
ConsoleApp의 Node, CustomerQueue파일의 내용을 변경할때 UIApp에서의   
Node, CustomerQueue내용이 같이 변경된다는점을 발견했습니다.   
이를 해결하기 위해여 아래와 같이 진행했습니다.  

        <img src="https://i.imgur.com/ZCu8pbB.png" width=400>  

        finder에서 consoleApp폴더에 복사붙여넣기한상태로,finder에서는 붙여넣기한 파일들이 보이지만
아래사진에서 Xcode에는 반영이 안된걸 알수있습니다.  

        <img src="https://i.imgur.com/Livq2wW.png" width=400>  

        (적용이 안된상태)

        <img src="https://i.imgur.com/7TRXOZx.png" width=600>  

        그래서 finder에 추가한 파일들을 그대로 끌어다가 놓으면 이런 창이 뜨게 됩니다.
여기서 Copy Items if needed를 꼭 체크해주고  

        <img src="https://i.imgur.com/fM0mOjf.png" width=400>  

        finish를 눌러 파일이 잘 들어온걸 확인할수있었습니다.
        이제 더이상 AppUI의 파일과 내용을 공유하지않았습니다.

- 고객업무를 처리하기 위해 Bank 타입의 `allocateCustomer` 메서드에서 customer를`dequeue`로 제거할 때 리턴값을 사용하지 않기 위해 CustomerQueue 타입에서`@discardableResult`를 붙여주었습니다.

- `allocateCustomer` 메서드에서 모든 고객을 처리한 후 처리시간이 노출될 때 소숫점 2자리까지만 노출되도록 `String(format: "%.2f")`을 적용해 주었습니다.

- 처음 한번 실행 한 후에 나타나는 메뉴에서 다시 `1`을 선택하여 주는 경우, 재실행 되지 않고 바로 종료되는 문제를 해결하기 위해 고민해 보았습니다.
    - 큐가 비었는지 확인하는 `isEmpty` 메서드의 조건을 `{ front == nil }`로 수정하여 해결하였습니다.

## 조언을 얻고 싶은 부분

- STEP 2까지의 요구사항을 확인했을 때 `BankManager` 타입의 역활이 정확하게 그려지지 않았습니다. 뱅크를 여러개 생성할 수 있고 그것을 아우르는 상위 타입의 Manager 타입인 것인지, 뱅크에서 일하고 있는 은행원이라고 생각해야 하는지 의견이 있었고 일단, 뱅크에서 일하고 있는 은행원의 역할을 `BankManager` 타입으로 구현하였습니다.
    - ➡️ 올라프의 생각은 어떠신지 궁금합니다. 🧐

- `Escaping closure captures mutating 'self' parameter`에러가 뜨는 문제
    - `allocateCustomer` 메서드에서 작업 할당 시, `let work = DispatchWorkItem`이런 방법으로 선언하여 주고 `DispatchQueue.global().sync(execute: work)`로 호출하여 주고 싶었으나 `Escaping closure captures mutating 'self' parameter`에러가 노출되어 사용할 수 없었습니다.
    - STEP2 에서는 `DispatchQueue.global().sync { }` 클로저 안에 코드를 넣어 실행되도록 했지만 이 방법도 `DispatchQueue.global().async { }` 에서는 동일한 에러가 노출되어 사용할 수 없었습니다.
    - Bank 타입이 struct로 설정되어 있어서 class로 변경하면 해결 할 수 있었지만 struct를 유지하면서 해결할 수 있는 방법이 있는지 찾아보았지만 아직 발견할 수 없었습니다.
    - ➡️ 이것에 대해 올라프가 혹시 조언해 주실 부분이나 공부할 키워드를 알려주실 수 있을까요? 🧐

2022-11-03 15:08 UTC, 1Consumption requested changes
안녕하세요 @JaeKimdev @MangDi-L
고생하셨습니다.

고민하신 점에 대한 제 생각을 적어볼게요.

STEP 2까지의 요구사항을 확인했을 때 `BankManager` 타입의 역활이 정확하게 그려지지 않았습니다. 뱅크를 여러개 생성할 수 있고 그것을 아우르는 상위 타입의 Manager 타입인 것인지, 뱅크에서 일하고 있는 은행원이라고 생각해야 하는지 의견이 있었고 일단, 뱅크에서 일하고 있는 은행원의 역할을 `BankManager` 타입으로 구현하였습니다.
- ➡️ 올라프의 생각은 어떠신지 궁금합니다. 🧐

> 글쎄요.. 망디와 메네가 만든 객체니까 본인들이 왜 그렇게 생각했는지가 중요해보입니다. 또 아직 객체가 너무 작아서 역할을 나누는게 무의미해 보일수도 있겠네요. 일단 계속 만들어보시죠.

`Escaping closure captures mutating 'self' parameter`에러가 뜨는 문제
    - `allocateCustomer` 메서드에서 작업 할당 시, `let work = DispatchWorkItem`이런 방법으로 선언하여 주고 `DispatchQueue.global().sync(execute: work)`로 호출하여 주고 싶었으나 `Escaping closure captures mutating 'self' parameter`에러가 노출되어 사용할 수 없었습니다.
    - STEP2 에서는 `DispatchQueue.global().sync { }` 클로저 안에 코드를 넣어 실행되도록 했지만 이 방법도 `DispatchQueue.global().async { }` 에서는 동일한 에러가 노출되어 사용할 수 없었습니다.
    - Bank 타입이 struct로 설정되어 있어서 class로 변경하면 해결 할 수 있었지만 struct를 유지하면서 해결할 수 있는 방법이 있는지 찾아보았지만 아직 발견할 수 없었습니다.
- ➡️ 이것에 대해 올라프가 혹시 조언해 주실 부분이나 공부할 키워드를 알려주실 수 있을까요? 🧐

> https://www.swiftbysundell.com/articles/capturing-objects-in-swift-closures/ 이 링크를 참고해보세요.
struct를 캡쳐하면 어떻게 되나요? 그리고 캡쳐 리스트에 캡쳐된 변수는 var로 전달되나요 let으로 전달되나요?

2022-11-04 02:01 UTC, JaeKimdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                }
이것도 위의 코멘트와 맥락이 비슷한데요, 처음에는 한명의 manager를 가지고 혼자서 고객을 처리하도록 구현하였다가 n명의 manager를 가질 수 있게 수정하면서 고객 대기열에서 한명씩 메네, 망디, 메네, 망디.. 이런식으로 순차적으로 처리할 수 있도록 구현해 보았습니다.

2022-11-04 02:05 UTC, MangDi-L commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        DispatchQueue.global().sync {
은행원이 한명이기때문에 처음에 main으로 async를 주면 되겠다 생각했는데 (main.sync는 교착상태유발)
main.async를 하게되면 `Escaping closure captures mutating 'self' parameter` 에러가 떴습니다.
그래서 처음 의도와는다르게 여러 스레드를 사용하는 global.sync는 정상작동이 되서 사용하게되었습니다.
그런데 또 global.async는 안되어서 이것에 대해 파헤쳐보고있습니다.

2022-11-04 02:17 UTC, MangDi-L commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    var numberOfCustomer: Int
[2936806](https://github.com/yagom-academy/ios-bank-manager/pull/229/commits/2936806fd4abaceeb847dc550b73393ac52c0e13)
초반에 이것저것 수정해보다가 var로 선언해주고 못본것같아요 😅
수정했습니다!

2022-11-04 02:23 UTC, MangDi-L commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                }
main파일에서
```swift
let mene = BankManager(name: "mene")
let mangdi = BankManager(name: "mangdi")
var kbBank = Bank(
    manager: [mene, mangdi],
```
은행원 mene, mangdi를 추가해주고 실행해보면
![managerTwo](https://user-images.githubusercontent.com/49121469/199871426-8ed38297-eda7-4f80-8501-9860209595c6.gif)
한명씩 번갈아가며 처리해주고있습니다!

2022-11-04 15:59 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
굳이 Array를 명시하지 않아도 `(0..<numberOfCustomer).forEach { ~~ }` 로 치환할 수 있겠네요.

2022-11-04 16:03 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        DispatchQueue.global().sync {
이게 main이냐 global이냐의 문제일까요? 그리고 global queue에서 실행하더라도 지금 코드라면 하나의 작업으로 실행될거같네요.

2022-11-04 16:04 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                }
번갈아가며 처리를하면 안되고 동시에 2명이 처리를해야하는게 맞지 않나요? 물론 스텝2 내용은 아니지만요.

2022-11-06 16:30 UTC, merged

2022-11-06 16:31 UTC, 1Consumption commented
스텝 3에서 더 고민해보도록하죠.
다음 스텝을 진행하셔도 좋습니다.

2022-11-06 16:55 UTC, MangDi-L commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                }
![modify](https://user-images.githubusercontent.com/49121469/200183805-7b18bbf5-731e-4116-8643-918b800f0547.gif)
두명의 은행원이 각각 일을 수행하고 작업을 완료하면 다음일을 수행하도록 수정해보았습니다!