은행창구 매니저 [STEP 2] Baem, Bella
yagom-academy/ios-bank-manager pull request #230
Opened 2022-11-03 09:57 UTC by Dylan-yoon

@uuu1101 
안녕하세요 태태! 🙌🏼
은행창구 매니저 [STEP 2] p.r을 보냅니다! 잘 부탁드립니다! 🙆🏻‍♀️🙆🏻‍♂️ 

### [고민했던 점]
#### 동기 비동기 사용
- Bank 내에서 동기 비동기를 사용하여 각각의 은행원에 고객을 할당해야 한다고 생각했는데, 명세서 확인 후 흐름만을 구현하는 것이 목적이라고 판단해서, 명세서 대로 구현하는 것을 목표했습니다!

#### Bank 타입 내부 getWorkTimeAfterRunTask() 메서드 네이밍
- 기능 분리를 위해 기존의 startTask() 메서드에서 해주었던 일을, 추가 함수를 만들어 startTask() 내부에서 호출하고자 하였습니다.
- 그 과정에서 고객대기열에 넣어주었던 랜덤한 값을 빼내어주는 일과, 과정을 거쳐 시간을 반환하는 일을 나타내는 메서드명을 고민하여 짓게 되었습니다. 저희가 고심하여 지은 네이밍이 현재 메서드가 하는 일을 나타내기에 적합한지 궁금합니다. 

### [조언이 필요한 점]

#### 고객 타입의 구현과 적용
- 요구 명세서에 충실하고자 [STEP 2] 고객타입내부에 간단한 고객의 수를 가지도록 구현하였는데, 현재 단계에서 고객 타입에 대해 더 구현하거나 적용해야 하는 점이 있는지 궁금합니다.

2022-11-04 03:28 UTC, uuu1101 requested changes
안녕하세요 Bella, Baem! 
STEP2 진행하시느라 고생하셨습니다.

몇가지 코멘트 남겨두었어요.

**고객 타입의 구현과 적용에 대해서**
관련하여 코멘트 남겨두었습니다!

2022-11-04 03:28 UTC, uuu1101 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            return receiveUserInput()
다시 `receiveUserInput` 을 호출해주신 이유가 궁금합니다

2022-11-04 03:28 UTC, uuu1101 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomer)명이며, 총 업무시간은 \(taskTime)초입니다.")
프로젝트에서 업무를 처리한 고객이 총 고객의 수가 되는 구조를 가지고 있긴하지만, 총 고객의 수와 업무를 처리한 고객의 수를 따로 관리해보는건 어떨까요?

2022-11-04 03:28 UTC, uuu1101 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            print("\(currentCustomer!.number)번 고객 업무 시작")
옵셔널 강제추출(!)을 사용하지 않고 작성해볼수 있을까요?

2022-11-04 03:28 UTC, uuu1101 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    let number: Int
고객의 수라고 하셨는데, 고객의 수가 총 고객의 수인가요? 
고객의 수를 Customer가 가지고 있는이유가 궁금합니다.
각 고객의 접수번호처럼 생각을 하였었는데, 고객의 수라고 한다면 은행이 가지고 있는게 더 자연스럽지 않을까요?

2022-11-04 07:59 UTC, hyhy0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomer)명이며, 총 업무시간은 \(taskTime)초입니다.")
[36b0d17](https://github.com/yagom-academy/ios-bank-manager/pull/230/commits/36b0d171ea787b183450b99ab3aff56e45dd60ed)
아하! 태태 피드백대로 변경하면, 추후 처리된 고객의 수를 파악하는데 용이 할 수 있을 것 같아 분리하여 관리하는 방향으로 수정해보았습니다! 🙌🏼

2022-11-04 08:15 UTC, Dylan-yoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            print("\(currentCustomer!.number)번 고객 업무 시작")
https://github.com/yagom-academy/ios-bank-manager/pull/230/commits/12d16af96f1c6ab56de5d4e0d4457caf6319e7cf

네 확인했습니다. 저희가 처음에 옵셔널 바인딩을 하지않고 값을 확인하려다가 잊어버리고 변경하지않았습니다..😭
확인후 변경했습니다!

2022-11-04 08:21 UTC, hyhy0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    let number: Int
[0e0c00](https://github.com/yagom-academy/ios-bank-manager/pull/230/commits/40e0c00531958a310bbc87b2cdb94d565f18e166) 조금 더 명확한 네이밍을 주는 것이 좋다고 생각하여, Customer 내부 프로퍼티 명을 변경하였습니다!

2022-11-07 10:37 UTC, uuu1101 commented
고생하셨습니다 ! step3 도 화이팅 !!

2022-11-07 10:37 UTC, merged