은행창구 매니저 [STEP 2] 애종, stone
yagom-academy/ios-bank-manager pull request #231
Opened 2022-11-03 10:41 UTC by lws2269

# STEP 2 PR
안녕하세요. 제임스(@inwoodev)!
STEP2 구현이 완료되어 PR요청 드립니다!
리뷰해주신 제네릭 타입과, Node가 Class타입인 이유에 대해 한번 더 복습할 수 있었던 것 같습니다.
이번 스텝도 잘부탁드립니다.감사합니다!
🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍
## 구현내용
- **.swiftlint.yml -> disabled_rules**
    - trailing_whitespace : 코드와 코드사이에 뒤에붙는 공백이 존재하면 warning을 표출하는데, 이 규칙을 제외하기위해 추가했습니다.
    - redundant_discardable_let : 테스트 코드에서 dequeue작업을 수행하는 반복문에서 반환 값을 사용하지 않기위해 추가했습니다.
    - line_length : print문을 출력하는 곳에서 120개의 문자를 넘게 작성하기 위해 추가했습니다.

- **Decimal+Extension -> doubleValue 연산프로퍼티**
    - Decimal타입을 확장하여 Decimal 타입의 값을 NSDecimalNumber클래스를 이용하여 Double값을 리턴해주는 연산프로퍼티를 구현하였습니다.

## 실행화면

![](https://i.imgur.com/hJDg4bb.gif)

## 고민되었던 점
- Bank의 manager의 Type을 무엇으로 설정할 지 고민했습니다
    - 명세서에 따르면 n명의 은행원이 근무하기 때문에 처음에 `[BankManager]` 배열의 형태로 만들어주었지만 이후 BankManager가 어떤 방식으로 일하는지 알지 못하고, step2에서는 한명의 직원이 일하고 있다고 표현해 `manager: BankManager`타입으로 결정했습니다.

- Decimal을 사용할 경우 소수점 아래 자릿수가 불규칙적으로 출력되는 현상에 대한 고민
    - 처음 구현할 당시 Double타입으로 0.7초씩 더해주니 부동소수점의 연산오류로 인해 13.999999999과 같이 출력되었습니다. 
Decimal타입으로 바꿔 계산하니 결과는 정확하게 나왔지만 소수점 아래 자리가 없는 수도 `7.0초 `처럼 출력되게 구현하고자 했습니다.
```swift
extension Decimal {
    var doubleValue: Double {
        return NSDecimalNumber(decimal: self).doubleValue
    }
}
```
> 위와 같이 Decimal타입에 extension을 통해 doubleValue로 출력해주는 연산프로퍼티를 구현해줌으로써 해결했습니다.

## 조언을 얻고 싶은 부분
- 이번 스텝에서는 testcase를 작성하여 진행하지 않았지만, 지난 @testable에 대한 오류를 해결하지 못했습니다.. `Could not find module for target 'x86_64-apple-macos'; found: arm64-apple-macos`해당 오류를 해결하면 `No such Module` 오류가 나오고 무언가 굴레에 빠진 느낌이 들었습니다..😭😭 
    - https://stackoverflow.com/questions/32008403/no-such-module-when-using-testable-in-xcode-unit-tests
    - https://levenshtein.tistory.com/396
    - https://woongsios.tistory.com/162
- 위 자료들을 참고하여 진행해보았는데 해결되지 않았습니다 ㅠㅠ

2022-11-04 13:59 UTC, inwoodev requested changes
스텝 2도 빠르게 구현하셨군요! 정리도 잘하시고 습득도 빠르셔서 저도 더 자극받게 되네요~ 💪💪💪

@testable import 문제 같은 경우 어떤 문제를 겪으시는건지 조금 실마리가 보여서 디코에 남겨 봤어요~ 확인 후 그래도 안되면 같이 화면 공유해서 해결 해 봅시다!! :)

이번 PR Review에서는 확장성에 많이 강조했습니다만. 또 생각 해 보니 조금은 더 실마리를 드리는게 맞다고 생각해서 키워드 몇 개 남겨봅니다:
- 타입 추상화
- 높은 응집도, 낮은 결합도
- 의존성 주입

관련되서 찾아보시고 공부하신 내용을 기반으로 리팩토링 해 보시고 또 시간이 되신다면 저에게도 공유 해 주시면 더 알찬 프로젝트가 되지 않을까 조심스럽게 생각해 봅니다~ 코멘트 확인 해 주시고 궁금한점 있으시면 언제나와 같이 DM 주시면 같이 고민 해 봅시다 :)

2022-11-04 13:59 UTC, inwoodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    var totalWorkTime: Decimal = 0.0
manager라는 이름은 매우 직관적입니다. 하지만 조금 더 확장성있게 설계할 수 있을거 같아요! 음 현재 상황에서는 손님을 받을 수 있는 객체는 오직 BankManager으로 한정됩니다. 음 실생활에서는 만약 BankManager가 모종의 이유로 일을 나오지 못한다면? 뱅크 매니저가 아니라 차장 또는 더 윗사람이 해당 작업을 해야 할 상황이 있지 않을까요? 실제 회사에서 프로젝트를 진행할 때에도 기획의 변경에 대비할 수 있게 객체의 확장성을 고려하는 측면도 실생활의 예시와 비슷한 맥락일거 같아요. 저희도 BankManager를 사용함에 있어서 조금 더 확장성 있게 수정해 볼 수 있지 않을까요?

2022-11-04 13:59 UTC, inwoodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    var totalWorkTime: Decimal = 0.0
아 그리고 `totalWorkTime`은 접근제한이 internal인데 특별한 이유가 있을까요?

2022-11-04 13:59 UTC, inwoodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/BankManager.swift
> +    func provideService(to customer: Customer?) {
전달인자레이블을 적절히 사용하셨군요!! 👏👏👏 여기도 위에 남긴 코멘트와 비슷한 얘기입니다~ VVIP 손님, vip손님, 대출받으려는 손님, 예금하려는 손님, 보든 손님 타입에게 서비스를 주는 객체로 보다 확장성 있게 설계 해 볼 수 있지 않을까요?

2022-11-07 09:52 UTC, lws2269 commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    var totalWorkTime: Decimal = 0.0
`totalWorkTime` 의 접근제어자는 처음에 BankManager에서 `totalWorkTime` 값을 변경하다보니 internal 접근제어자를 채택하여 진행했었는데, 나중에 리팩토링 하는과정에서 BankManager가 `totalWorkTime`을 관리하도록 리팩토링 했습니다. 이 과정에서 접근제어자에 대해 생각하지 못했었습니다😭
이번 리팩토링을 통해 private 접근제어자를 채택했습니다..!

2022-11-07 10:08 UTC, lws2269 commented
안녕하세요 제임스!

의존성 주입을 위해 `init(manager: Workable, customerList: Queue<Customer>)` 생성자를 사용해 외부에서 객체를 주입하는 식으로 리팩토링 진행하였고, 

Workable, Customer 프로토콜을 통해 확장성을 가질 수 있도록 구현해보았습니다.

Workable 프로토콜에서 `provideService(to customer: Customer?)`메서드 구현을 요구함으로써 일하는 사람은 손님에게 서비스를 제공하는 메서드를 추상화 하였습니다.

Customer 프로토콜에서 `number: Int`를 요구하도록 구현하려했으나, 예를 들어주신 VVIP나 VIP고객같은 경우에는 번호표 없이 상급자를 만나는 경우를 생각하여 빈 프로토콜로 구현하였습니다.


높은 응집도, 낮은 결합도를 위해 클래스나 함수가 하나의 책임을 수행하는 `단일책임원칙`을 따르게 하려고 했습니다. 사용자의 입력을 받는 부분과 입력을 처리하는 부분을 handleBankSystem()메서드로 분리해줌으로써 분리하고, manager에게 업무를 나누어주는 startWork() 메서드 또한 분리해주었습니다.

---
### 궁금한 점..!
폴더구조 관련해서 프로토콜 파일들의 구조가 궁금합니다. 프로토콜 파일들도 Model로 구분하여 분리를 하는 것이 좋은지 아니면 프로토콜폴더를 따로 가지고 분리를 하는 것이 좋은지 궁금합니다. 또, Queue LinkedList Node 세가지 파일에 대해서 폴더 분리를 어떻게 가져가면 좋을까요?

2022-11-08 10:12 UTC, inwoodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Models/Bank.swift
> +    }
이제 객체 내부 세부 구현사항에 변경이 있거나 다른 객체가 사용되어도 변경되는 부분이 적어지겠네요 🙌🙌🙌.

2022-11-08 10:21 UTC, inwoodev approved these changes
> 폴더구조 관련해서 프로토콜 파일들의 구조가 궁금합니다. 프로토콜 파일들도 Model로 구분하여 분리를 하는 것이 좋은지 아니면 프로토콜폴더를 따로 가지고 분리를 하는 것이 좋은지 궁금합니다. 또, Queue LinkedList Node 세가지 파일에 대해서 폴더 분리를 어떻게 가져가면 좋을까요?

일단 폴더구조에 있어서는 명확한 답이 없다고 생각합니다. 다만 제 생각을 물어보시니 말씀을 드리자면 저는 업무의 효율성에 초점을 맞추고 폴더구조를 짜는 편입니다. 연결점이 짙은 파일들을 동일 폴더에 넣어놓는 편이구요. 이 때문에 저는 개발함에 있어서 더 나은 효율을 추구합니다. 물론 회사에 들어가시게 되면 팀 컨벤션도 따로 있기에 이에 맞춰야하겠지만 현재로서는 여러분이 빠르게 파악하기 쉬운 구조로 만드는건 어떤지 조심스럽게 의견 남겨봅니다. 음...그리고 들어보셨을 수도 있는데 클린아키텍처를 한 번 찾아보시면 폴더 구조 관련해서도 내용이 있거든요. 참고 해 보시고 폴더구조를 정하시는 것도 좋을거 같아요~

스텝2도 고생하셨습니다~ 의존성 주입에 대해서도 나름 많이 공부하신거 같고 단일책임원치에 대해서 충분히 고려하신 흔적이 보여서 매우 인상적이었습니다~ 다음 스텝으로 넘어가도 좋습니다!

2022-11-08 10:21 UTC, inwoodev commented on BankManagerConsoleApp/BankManagerConsoleApp/Namespace/Namespace.swift
> +}
🙌🙌🙌 이런식으로 상수를 관리하니 문자열을 잘못 입력하는 실수를 방지할 수 있겠네요!

2022-11-08 10:21 UTC, merged