## 은행 창구 매니저 [STEP 2] minii, zhilly
yagom-academy/ios-bank-manager pull request #238
Opened 2022-11-04 08:00 UTC by zhilly11

@Monsteel
안녕하세요 토니~
저희 STEP-2 구현이 완료되어 PR보냅니다!!

### 고민했던 점
> Bank가 BankManager를 프로퍼티고 가지고 있는게 맞는가? 아니면 BankManager가 Bank를 프로퍼티로 가지고 있는게 맞는가?

`BankManager가 Bank를 관리하는 역할을 가진다면, Bank를 프로퍼티로 가지고 있어야 하는 가?`에 대해서 고민을 하게 되었습니다.
저희 이에 대해서 해결하기 위해서 실생활에 빗대어서 타입들을 생각해보았습니다. Bank 타입이 스스로 문을 열고, 스스로 업무를 시작하게 하는 것은 적절하지 않다고 생각하였습니다. 또한 Bank 타입의 역할을 은행 창구 뒤 편에서 일어나는 일에 대한 책임을 가지기 때문에 위와 프로퍼티로 소유하는 것이 적절하다고 결론내렸습니다. 따라서 BankManager 타입이 Bank 타입을 프로퍼티로 소유해서 관리할 수 있도록 하였습니다.

> Bank 타입 내에서 큐 타입의 Optional 적용

Bank 타입 내에서 항상 customerQueue가 있다고 단정 지을 수 없었습니다. 개점을 하면 대기열이 생성되고 마감을 하면 대기열이 없어져야 한다고 생각해서 이 부분도 조금 더 실생활에 빗대어서 생각을 했습니다. 즉, 은행의 업무에 대해서 완벽하게 코딩을 했을 지라도, 어떤 이유로든 초기의 상태로 돌아가지 못한 경우가 발생할 수 있다고 생각하였습니다. 따라서 customerQueue타입을 Optional 타입으로 구현하고 오픈하면 인스턴스화 해주고, 마감을 하면 안에 혹시 모를 남아있을 Customer에 대해서 초기화 시켜주고 customerQueue를 nil로 해제시켜 주었습니다.

### 조언을 얻고 싶은 부분
> 디스패치 큐 어떻게 공부해야하죠? 디스패치 큐를 연습하는 것에 대해서 어떤 방법으로 접근을 해야 하는지 감이 잡히지 않아서 여쭤봅니다. 다양한 방법으로 어떻게 디스패치 큐가 동작하는지 알아보는 방법으로 공부하는 것에는 한계가 있다고 생각이 들었습니다 ㅜ

2022-11-07 08:11 UTC, Monsteel approved these changes
안녕하세요! minii, zhilly~ 이번 스텝도 수고 많으셨습니다!
지난 스텝에서 생성한 요소들 잘 활용해서 이번 스텝도 구현해주신것 같아요 👍 

수고하셨습니다 :)

코드 리뷰는 아래 코멘트를 참고부탁드립니다!

추가로, 조언을 구하신 부분에 대한 제 생각을 남겨봅니다!

> 디스패치 큐 어떻게 공부해야하죠? 디스패치 큐를 연습하는 것에 대해서 어떤 방법으로 접근을 해야 하는지 감이 잡히지 않아서 여쭤봅니다. 다양한 방법으로 어떻게 디스패치 큐가 동작하는지 알아보는 방법으로 공부하는 것에는 한계가 있다고 생각이 들었습니다 ㅜ

사실 학습에도 자신에게 맞는 학습 방법이 있어서, 어떠한 방법으로 공부하는것이 정답이다! 라고 정의하기 어렵습니다. 사실 이런 여러가지 요소들을 거치면서 스스로 학습하는 방법을 터득해서, 새로운 기술들이 나왔을 때 스스로 능동적으로 학습할 수 있는 힘을 기르는게 중요하다고 생각합니다.

당장 혼자 학습하기 어려우시다면, 옆 동료와 함께 이야기를 나누어보거나, 의존모둠을 활용해서 학습 방법을 공유하고, 각자 이해한 방향을 공유하는 등, 함께 고민하는 과정을 거쳐보면 어떨까 합니다! 👍

이번 스텝도 수고많으셨고, 머지 준비되시면 다시 말씀 부탁드립니다! 👍

2022-11-07 08:11 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
customerQueue가 nil 인 경우, queue에 값이 있다고 판단하시는걸까요?! 👀

2022-11-07 08:11 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                time += (700000 / 1000000)
요 숫자들을 조금 더 가독성 좋게 다룰 수 있는 방법은 없을까요!?

2022-11-07 08:11 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let workedTime = round(duringTime * 1000) / 1000
이 부분의 숫자도 가독성 좋게 다룰 수 있는 방법은 없을까요!?

2022-11-07 08:11 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +        switch userInput {
이후 확장성을 위해 `switch` 문을 작성해주신것 같아요 👍  좋습니다!

2022-11-07 08:11 UTC, Monsteel commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +struct Customer {
`Customer` 객체를 별도로 생성하여, 구조적으로 안정되어 보입니다 👍 좋습니다!

2022-11-07 08:13 UTC, Monsteel requested changes
리뷰 상태를 정정합니다 😓

2022-11-07 12:47 UTC, zhilly11 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
앗 오타가 있었네요!
저희가 의도한 바는 `customerQueue가 nil 인 경우, queue가 비어있다. 즉 isQueueEmpty가 true 이다.`
라고 작성하려고 했습니다! 오타 수정하였습니다~

2022-11-07 12:47 UTC, leegyoungmin commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                time += (700000 / 1000000)
숫자들에 대한 가독성을 높일 수 있도록 사용하는 메서드를 `Thread.sleep` 로 변경하였고, 추가적으로 상수에 대한 네임스페이스를 적용할 수 있도록 하였습니다.

2022-11-07 12:50 UTC, zhilly11 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let workedTime = round(duringTime * 1000) / 1000
`Double` 타입을 `extension`으로 확장해서 기능을 추가해 주고, 매직 리터럴도 제거하였습니다.
또한, 소수점 2자리까지 표시 안되던 버그도 수정했습니다~

2022-11-07 12:57 UTC, zhilly11 commented
![image](https://user-images.githubusercontent.com/99257965/200314849-9fb40973-0421-4258-8ec8-15d3da982144.png)

@Monsteel 토니 리팩토링을 하던 과정 중에 추가적으로 궁금한 점이 있습니다.

위에 사진처럼 `Double`에 `extension`을 활용하여 메서드를 작성해 주려고 했는데 에러가 발생해서 `rounded`메서드를 활용해 작성했습니다.

저희가 추측하기론 `round()`메서드는 `mutating` 메서드고 `rounded()`메서드는 일반 메서드여서 이러한 차이점 때문에 위와 같은 에러가 나는 것 같습니다만, 혹시 자세한 설명이나 검색해 볼 만한 키워드를 알려주실 수 있을까요?

2022-11-08 06:36 UTC, Monsteel approved these changes
수고하셨습니다! ✌️

2022-11-08 06:36 UTC, merged