은행 창구 매니저 [STEP 2] 토털이, Aaron
yagom-academy/ios-bank-manager pull request #242
Opened 2022-11-07 10:19 UTC by tottalE

@junbangg
안녕하세요!
반갑습니다 알라딘:) 이번 스탭도 잘 부탁드리겠습니다! 💪🏽

## 개발한 내용
- 고객, 은행, 은행원 타입 구현
- 은행 내에 `open()`, `close()`, `menu()` 구현
- 은행에서 10~30사이의 랜덤한 명수의 손님들을 생성
- 은행에서 은행원이 손님들을 처리하도록 로직 구현
- `CFAbsoluteTimeGetCurrent()` 을 사용하여 시작 및 종료 시간을 측정해서 완료시에 보여주도록 함
- `CFAbsoluteTime`의 extension으로 fomat된 2자리 소수점의 string을 반환하도록 구현

## 고민한 점

### 1. 은행 업무 처리시간 sleep 메서드 사용
스위프트의 런타임 시간 지연방법중 `sleep()`메서드를 사용해 진행했지만 `Duration`타입의 파라미터에서 1초 미만의 시간을 설정하는데 어려움을 겪었습니다.

 Dispatch group을 사용하는 방법과 Timer를 사용하는 방법등 여러 방법을 사용해보다 
`usleep()` 메서드를 사용해 구현했습니다.

```swift
func work(for customer: Customer) {
        print("\(customer.number)번 고객 업무 시작")
        usleep(useconds_t(700000))
        print("\(customer.number)번 고객 업무 완료")
    }
```

### 2. DispatchQueue의 사용

- `DispatchQueue.main.asyncAfter()`을 사용하려 했지만 제대로 동작하지 않았고, DispatchGroup을 사용하여 이렇게 구현을 할 수 있는데, 불필요하다고 생각이 되어 일단 `usleep()`으로 구현을 해 주었습니다.
```swift
func work(for customer: Customer) {
    let group = DispatchGroup()
    group.enter()
    DispatchQueue.global().asyncAfter(deadline: .now() + 0.7) {
        print("\(customer.number)번 고객 업무 시작")
        group.leave()
    }
    group.wait()
}
```

2022-11-07 15:11 UTC, junbangg requested changes

2022-11-07 15:11 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        Array(repeating: 0, count: Int.random(in: 10...30)).enumerated().forEach { index, number in
여기서 배열을 만들어서 하신 특별한 이유가 있나요???

2022-11-08 09:17 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func startBankJob() {
기능 분리를 해 주었습니다~
> [6e9b9e0](https://github.com/yagom-academy/ios-bank-manager/pull/242/commits/6e9b9e0c5fbac9b7c8bbeaf0936246fc5efe15f8)

2022-11-08 09:21 UTC, Hashswim commented on BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift
> +
해당 부분 줄바꿈 제거했습니다!

2022-11-08 09:21 UTC, Hashswim commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func menu() {
`menu`메서드를 다시 확인해보며 기능 분리 및 네이밍 수정했습니다..!

2022-11-08 09:24 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func close() {}
종료시에 기능이 있을것이라고 생각하고 남겨둔 함수입니다! exit을 사용해주는 것보다 나을 것 같아서 함수를 정의해 주었습니다.

2022-11-08 09:52 UTC, Hashswim commented on BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift
> +        usleep(useconds_t(700000))
`Thread.sleep(0.7)`은 작동됩니다! sleep(0.7)만 작동 안되었습니다..!

2022-11-08 09:53 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func setupRandomCustomerQueue() {
[4b69759](https://github.com/yagom-academy/ios-bank-manager/pull/242/commits/4b69759e536051a119ecdbbad191d30e9bd16035)
주입해 줄 수 있도록 수정하고 다른 것들도 주입해 줄 수 있는 것들은 분리해서 프로퍼티로 선언해 주었습니다!

2022-11-08 09:54 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        Array(repeating: 0, count: Int.random(in: 10...30)).enumerated().forEach { index, number in
다른 방법으로는 크게 for문이 떠오르는데, 고차함수를 활용해주고 싶어서 배열을 만들어 큐에 넣어주었습니다.

2022-11-08 09:55 UTC, tottalE commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    let clerk = BankClerk()
[4b69759](https://github.com/yagom-academy/ios-bank-manager/pull/242/commits/4b69759e536051a119ecdbbad191d30e9bd16035)
은행이 여러명이 될 수있도록 수정해 주었습니다.!

2022-11-10 02:01 UTC, junbangg approved these changes

2022-11-10 02:01 UTC, junbangg commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func startBankJob() {
넵 확인했습니다~ 메서드로 잘 분리 해주셨네요! 그런데 28번째 줄에 있는 `print`에 대해서는 어떻게 생각하시나요???🤔

2022-11-10 02:02 UTC, merged