은행 창구 매니저 [STEP 3] 망디, 메네
yagom-academy/ios-bank-manager pull request #243
Opened 2022-11-07 15:29 UTC by MangDi-L

@1Consumption 
안녕하세요, 올라프
STEP3 완료되어 PR드립니다.

이번에도 아낌없는 리뷰 부탁드립니다. 🙏🏻

## 고민했던 점
- 처음에는 BankManager 타입이 업무를 처리하는 은행원이라고 생각해서 `mene`, `mangdi`, `bella` 3명의 BankManager를 생성하고 forEach문으로 은행 대기열에서 고객을 한명씩 배정해주는 방법으로 구현하였다가 이번 STEP에서는  depositSemaphore와 loanSemaphore를 각각 2명 / 1명으로 설정하여 각각 처리해 주도록 변경하였습니다.

    - forEach로 BankManager를 받아와서 돌리는 경우 대기열에 1,2,3번 고객이 모두 `대출` 고객인 경우 3명이 모두 할당이 된 상태에서 하나의 쓰레드만 사용 할 수 있었기 때문에 동시에 처리되지 않고 기다리게 되어 원하는 대로 구현이 되지 않았습니다.
    - `Semaphore의 vlaue`가 `은행 업무를 처리하는 은행원의 수`로 구조를 변경하여 처리하였습니다.

- 클로저의 캡쳐와 캡쳐리스트에 대해 고민하고 공부해보았습니다.
    - 클로저를 캡쳐하면 참조 / 값 타입에 상관없이 참조 타입으로 저장이 되고, 값 타입으로 사용하고 싶다면 캡쳐 리스트를 사용해서 저장해야 한다는 것을 새롭게 알게 되었습니다. 이 경우, 캡쳐 리스트에 캡쳐된 변수는 `let`으로 전달됩니다.

- 업무가 완전히 종료되기 전에 마감 메세지가 노출되는 문제를 해결하기 위해 고민해 보았습니다.
    - DispatchGroup를 사용하지 않고 작성 시, 업무배정이 완료되면 마감 메세지가 먼저 노출되는 문제가 있어, DispatchGroup의 wait 메서드를 이용하여 모든 작업이 완료된 후 노출되도록 하였습니다.

## 조언을 얻고 싶은 부분

```swift
private mutating func allocateCustomer() {
        let group = DispatchGroup()
        let depositSemaphore = DispatchSemaphore(value: 2)
        let loanSemaphore = DispatchSemaphore(value: 1)
        
        processTime {
            while customerQueue.isEmpty == false {
                guard let customer = customerQueue.dequeue() else { return }
                if customer.requestingTask == .deposit {
                    DispatchQueue.global().async(group: group) { [self] in
                        depositSemaphore.wait()
                        DispatchQueue.global().sync {
                            processTask(customer)
                        }
                        depositSemaphore.signal()
                    }
                } else {
                    prepareTask(to: loanSemaphore, for: customer, group)
                }
            }
            group.wait()
        }
    }
```

9번째줄의 if문의 첫번째 블록에서는 `DispatchQueue.global().async(group: group) { [self] in` 이렇게 [self] in을 붙여야 에러가 뜨지 않는데 
18번째줄 else 블록의 prepareTask 메서드는
```swift
private func prepareTask(to banker: DispatchSemaphore,
                             for customer: Customer,
                             _ group: DispatchGroup) {
        DispatchQueue.global().async(group: group) {
            banker.wait()
            DispatchQueue.global().sync {
                processTask(customer)
            }
            banker.signal()
        }
    }
```
동일한 코드임에도 불구하고 이친구는 왜그랬는지 모르겠지만 [self] in을 붙여주지 않아도 괜찮았습니다. 

```swift
private func processTask(_ customer: Customer) {
        print("\(customer.waitingNumber)번 고객 \(customer.requestingTask.name) 업무 시작")
        if customer.requestingTask == .deposit {
            usleep(700000)
        } else {
            usleep(1100000)
        }
        print("\(customer.waitingNumber)번 고객 \(customer.requestingTask.name) 업무 완료")
    }
```
processTask는 그저 출력하는 용도인데 if문 첫번째블록 안에 이친구만 빗금처리(//) 해도 [self] in 입력을 하지않아도 괜찮았습니다.
왜 이렇게 동작하는건지 잘 모르겠습니다 ㅠㅠ 올라프의 조언이 필요합니다!

2022-11-08 22:27 UTC, 1Consumption requested changes
고생하셨습니다.
코드가 전제척으로 깔끔하고 읽기 좋네요.
또 기능도 잘 구현해주셨습니다.

다만 아쉬운 점이 있다면 일부 커밋이 한번에 두개의 역할을 한다는 점입니다. 우리는 커밋을 왜 역할별로 나눠야할까요? 이 부분에 대해서 조금 더 고려해주시면 감사하겠습니다.

또 질문 해주신점에 대해서는 저도 이상하다고 생각이 되네요. escaping closure 내부에서 self의 기능을 사용하니까(언제 실행될지 모르니까) self를 캡쳐하는게 맞다고 생각되는데... 이상하네요🫠

2022-11-08 22:27 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +
불필요한 변경사항은 커밋하지 말아주세요.

2022-11-08 22:27 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let loanSemaphore = DispatchSemaphore(value: 1)
이 변수들이 Bank의 멤버변수가 아니라 메소드 내부에 선언된 이유가 있나요?

2022-11-08 22:27 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
메소드의 구성이 이상하다고 생각됩니다. 메소드 이름 자체는 prepare인데, 내부에서 process까지 하고있네요. 함수를 분리하거나 이름을 바꿔보시죠.

2022-11-08 22:27 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
따로 커스텀 DispatchQueue를 만들지 않고 global queue를 사용한 이유가 있을까요? 
물론 지금도 잘 동작하고, 제대로 이해하고 사용한 느낌이 듭니다.

2022-11-08 22:27 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let loanSemaphore = DispatchSemaphore(value: 1)
semaphore value가 1인 경우는 serialQueue로 대체할 수 있습니다.

2022-11-08 22:27 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                guard let customer = customerQueue.dequeue() else { return }
``` swift
while let customer = customerQueue.dequeue() {
 // ~~
}
```

위와 같이 바꿀수도 있겠네요.

2022-11-08 22:27 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private func processTime(closure: () -> ()) {
closure는 타입 자체의 이름이고, 조금 더 용도에 맞는 이름을 지어보는건 어떨까요?

2022-11-09 01:57 UTC, MangDi-L commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let loanSemaphore = DispatchSemaphore(value: 1)
모든 메서드가 사용하는게 아닌 allocateCustomer메서드와 allocateCustomer메서드가 호출하는 prepareTask메서드 두곳에서만 사용하기때문에 Bank의 전역변수로 두지 않았습니다.

2022-11-09 01:58 UTC, JaeKimdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +
네~ 커밋할 때 좀 더 신경써서 분리하고 내용도 확인하도록 해보겠습니다.👍

2022-11-09 02:01 UTC, JaeKimdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let loanSemaphore = DispatchSemaphore(value: 1)
요구사항에 은행은 n명의 은행원이 근무합니다. 라는 것이 있어서 Bank의 멤버변수로 전역으로 설정해 주어도 괜찮을 것 같네요, 망디와 리팩토링 하면서 좀 더 상의해 보겠습니다.

2022-11-09 02:03 UTC, JaeKimdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
처음에는 processTask 메서드만 존재했었는데 크기가 커져서 함수를 분리하면서 네이밍이 어려워서 저렇게 나누었는데, 말씀하신대로 prepare안에서 process를 하는 것이 이상하네요.. 리팩토링 시 좀 더 고민해 보겠습니다.

2022-11-09 02:04 UTC, JaeKimdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let loanSemaphore = DispatchSemaphore(value: 1)
네, serial queue를 만들어서 사용해도 되겠다는 생각도 해 보았는데, 추후 은행원의 숫자가 변경되는 경우 Semaphore의 숫자만 변경해주면 손쉽게 확장이 가능할 것 같아서 일단 1로 사용해 보았습니다.

2022-11-09 02:15 UTC, MangDi-L commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
커스텀DispatchQueue로 qos나 autoreleaseFrequency같은 파라미터들을 활용할 부분이 없어서 사용할 필요성을 못느꼈습니다.
global() 로 간단하게 구현이 가능해서 사용하게 되었습니다!

2022-11-09 02:30 UTC, JaeKimdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private func processTime(closure: () -> ()) {
https://github.com/yagom-academy/ios-bank-manager/pull/243/commits/6c2b4450a061e450cd26d6f004ad03499ed60e9f
메서드 명도 `checkTime`으로 클로저의 이름도 `process`로 변경하였습니다.

2022-11-09 02:36 UTC, MangDi-L commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                guard let customer = customerQueue.dequeue() else { return }
[bf445f9](https://github.com/yagom-academy/ios-bank-manager/pull/243/commits/bf445f9106205bfa9b4a5f67d6f91e4567e8e817)
while 문 안에 guard let 을 사용해주는상황이 오면 while let으로 간추릴수있다는 생각을 가져야겠습니다 ㅎㅎ

2022-11-09 02:47 UTC, JaeKimdev commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let loanSemaphore = DispatchSemaphore(value: 1)
https://github.com/yagom-academy/ios-bank-manager/pull/243/commits/357e817e073792b9aebbcc8d8afdc02347a2f484

전역으로 설정해 주었습니다.

2022-11-09 05:04 UTC, 1Consumption approved these changes
고생하셨습니다. 다음 스텝을 진행하세요.

2022-11-09 05:04 UTC, merged