은행 창구 매니저 [STEP 3] 하모, SummerCat
yagom-academy/ios-bank-manager pull request #245
Opened 2022-11-08 08:17 UTC by lxodud

@wonhee009
안녕하세요, 라자냐!
STEP-3 구현 완료하여 PR보냅니다!!

## UML

![](https://i.imgur.com/XrmdGcP.png)

## 고민했던 점

- Bank 타입 class로 변경
    - `Bank` 타입이 `struct`일 때 `DispatchQueue`의 `async` 메서드를 이용하여 해당 구조체를 캡처하면 오류가 발생했습니다.
    - 이는 `async`메서드에 전달되는 클로저가 캡처 후 외부에서 해당 구조체를 변경할 수 있기 때문에 발생한다고 생각했습니다.
    - 따라서 이를 해결하려면 `capture list`를 통해서 값 타입을 상수로 캡처하고 내부에서 변경이 일어나지 않는다고 표현해주어야 한다고 생각했습니다.
    - 이렇게 해결했을 때 캡처해온 값을 수정하지 못하는데 저희 프로젝트에서는 클로저 내부에서 `finishedCustomerCount`를 수정해주어야 하기 때문에 `class`로 변경하였습니다.

- POP를 어디에 적용할 것인가?
    - `Bank`와 `Queue`를 확장할 수 있는 가능성이 있다고 판단하여 적용해보았습니다.
    - `Bank`의 경우 `Bankable`이라는 프로토콜을 만들어서 공통적인 프로퍼티나 메서드를 추상화하고 `BankManager`는 `Bank`라는 구체적인 타입이 아닌 추상적인 `Bankable`을 의존하여 `DIP`를 준수하도록 하였습니다.
    - `Queue`의 경우 `Queueable` 프로토콜로 추상화했을 때 다양한 타입을 요소로 받기 위해 `associatedType`을 사용하여 구현하였는데 프로토콜과 구조체, 클래스에서 해당 프로토콜을 타입으로 사용할 때 다양한 에러가 발생했고 이를 해결해주려면 모든 타입에 제네릭을 붙여주고 프로토콜을 더 구현해주어야 하는 오버엔지니어링이 발생하여 필요없다고 판단하였습니다.

- 예금 업무를 2명의 은행원이 처리하는 상황, 처리한 고객 수 카운트의 Race Condition 해결
    - Race Condition을 해소하기 위한 방법으로는 크게 뮤텍스락, 세마포어, 시리얼 큐, 배리어를 활용하는 4가지 방법이 있습니다. 이 중에서 **세마포어를 활용**하는 방법을 선택했습니다.
      - 뮤텍스락: `lock()`과 `unlock()`을 일일이 직접 넣어주어야 해서 휴먼 에러가 발생하기 쉽고, **공유 자원에 동시에 접근할 수 있는 프로세스의 수가 1개**이기 때문에 **은행원 2명이 접근해야 하는 상황에서는 적절하지 못하다**고 판단했습니다.
      - 시리얼 큐: 시리얼 큐를 이용할 경우 각 은행원마다 시리얼 큐를 생성해 sync로 작업을 처리하게 하는 방식으로 구현이 가능합니다. 하지만 이런 방식으로 구현할 경우, 예금 업무를 처리하는 두 개의 은행원 큐에 예금 고객을 보낼 때 **각 큐에 쌓여있는 작업의 개수를 매번 확인해서 더 적은 쪽으로** 고객을 보내야 합니다.
      - 배리어: 배리어는 **특정한 작업이 실행되기 전까지 해당 작업을 실행하지 않는** 개념이라고 생각해서 이 상황에 활용하기에는 적절하지 못하다고 판단했습니다.
      - 세마포어: **공유 자원에 동시에 접근할 수 있는 프로세스의 개수를 제한**하는 방법으로, 예금 업무를 2명의 은행원이 처리하는 상황에 가장 적합하다고 생각해 세마포어를 활용했습니다. `depositQueue`의 semaphore를 2로, `finishedCustomerCount`의 semaphore를 1로 제한해 경쟁 상태를 방지했습니다.
        
- 업무 처리 시간 딜레이를 주는 방법 선택 (Thread.sleep vs asyncAfter)
    - `Thread.sleep(forTimeInterval: )`을 이용해서 딜레이를 주는 방법
        - STEP 2에서 `usleep()`으로 딜레이를 주었던 이유는, `sleep()`이 매개변수로 `Int` 타입만 받을 수 있기 때문이었습니다.`Thread.sleep(forTimeInterval: )`을 이용하면 `Double`을 매개변수로 받을 수 있어 `Thread.sleep`으로 수정했습니다.
        - 하지만 `Thread.sleep()`, `sleep()`을 활용해 의도적으로 딜레이를 발생시킬 경우, 코드가 실행되는 스레드를 지연시키기 때문에 성능을 저하시킬 수 있습니다.

    - asyncAfter를 이용해서 딜레이를 주는 방법
        - `"시작"`이 끝난 후 1.1초 후에 `"종료"`가 되도록 하는 코드
        - `loanQueue`와 `DispatchQueue`로 큐가 2개가 되어 둘 다 작업을 계속 async로 던지기 때문에 `loanQueue` 하나만 사용할 때보다 스레드를 더 많이 생성하게 되어 성능이 저하될 수 있다.

        ```swift
        case .loan:
            loanQueue.async(group: dispatchGroup) {
                self.sema.wait()
                DispatchQueue.global().async {
                print("시작")
                self.sema.signal()
            }
            self.sema.wait()
            DispatchQueue.global().asyncAfter(deadline: .now() + 1.1) {
            print("종료")
            self.sema.signal()
            }
        ```
        
- 위의 두 가지 방법을 비교했을 때, 스레드의 수가 늘어나는 것이 성능 저하에 더 큰 영향을 줄 수 있다고 생각해 최종적으로 `Thread.sleep`을 사용했습니다.

## 출처
http://swiftrien.blogspot.com/2016/12/implementing-delay-in-swift.html
https://stackoverflow.com/questions/70649135/escaping-closure-captures-mutating-self-parameter-struct

2022-11-09 03:26 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겼으니 확인 부탁드려요.

2022-11-09 03:26 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    let banking: BankService
BankService가 `timePerService`,  `serviceName`들을 프로퍼티로 들고 있는데요.
이런 값들을 Customer가 알아야하나요?

2022-11-09 03:26 UTC, wonhee009 commented on BankManager.swift
> +        let customers: Int = try createCustomer()
은행 open에서 해당 메서드를 호출하지 않고 init시에 생성해줘도 되지 않을까 생각 듭니다.

2022-11-09 03:26 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private var customerCountSemaphore: DispatchSemaphore = DispatchSemaphore(value: 1)
customerCount가 비동기적으로 작동하나요?

2022-11-09 08:39 UTC, ttokin commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private var customerCountSemaphore: DispatchSemaphore = DispatchSemaphore(value: 1)
원래의 코드에는 `async`로 던지는 클로저 안에서 `customerCount`를 조작하고 있어서 해당 변수에 비동기적으로 접근하고 있었습니다.
현재는 해당 변수를 `async` 코드블럭 밖에서 조작하여 비동기적으로 접근하지 않는 방향으로 코드를 수정하였습니다.

2022-11-09 08:44 UTC, lxodud commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    let banking: BankService
해당 정보를 BankService 열거형이 아닌, 각 업무를 처리하는 부서가 채택하는 프로토콜인 Departmentable에 구현하는 것으로 변경하였습니다!!!

2022-11-09 08:51 UTC, lxodud commented on BankManager.swift
> +        let customers: Int = try createCustomer()
init시에 고객을 생성할 경우, open() 에서 Bank를 init()하도록 변경해서 은행 업무를 개시할 때마다 새로운 은행 인스턴스를 생성하게 되는데 이러면 오픈할때마다 새로운 은행이 생긴다는 의미로 받아들여져서 어색하다고 느꼈습니다.
그리고 BankManager는 Bankable 타입의 bank 프로퍼티를 가지고있고 BankManager를 생성할 때 외부에서 주입받는 구조를 생각했는데 open() 메서드에서 Bank 인스턴스를 생성하여 할당해주면 의미가 없어지는게 아닐까라는 생각이 들었습니다.

라자냐의 의도가 어떤것이었는지 궁금합니다!!

2022-11-10 12:30 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    let banking: BankService
protocol로 구현한 이유가 있을까요?
현재 기능들이 재사용되는 기능들이 아니고 프로토콜을 채택한 곳에서 로직을 구현하는 것도 아녀서 질문 드립니다.

2022-11-10 12:33 UTC, wonhee009 commented on BankManager.swift
> +        let customers: Int = try createCustomer()
"open() 에서 Bank를 init()하도록 변경해서 은행 업무를 개시할 때마다 새로운 은행 인스턴스를 생성하게 되는데" 어떤 과정인가요?.?

2022-11-10 14:01 UTC, lxodud commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    let banking: BankService
부서를 추상화해서 중복되는 기능들을 기본 구현하여 각 부서의 구체타입에 채택해주려고 하였습니다.
근데 두 부서의 로직이 완전히 동일해서 분리할 이유가 없다는 것을 라자냐의 의견을 통해서 알게 되었고 리팩토링 하였습니다.
280368cbc06dab7152ecbb59918b0e8aae89cecb

2022-11-10 14:17 UTC, lxodud commented on BankManager.swift
> +        let customers: Int = try createCustomer()
저희는 "init시에 생성한다"의 의미를 Bank를 init 할 때 생성한다의 의미로 이해했습니다. 이럴 경우, open() 할 때마다 Bank를 init해주지 않으면 새로운 고객을 생성하지 못하게 됩니다. 이를 해결하려면 open 했을 때 은행의 인스턴스를 새로 만들어줘야 새로운 랜덤한 수의 고객을 생성할 수 있다고 생각했습니다.

2022-11-11 10:55 UTC, lxodud commented on BankManager.swift
> +        let customers: Int = try createCustomer()
Customer를 외부에서 생성하여 BankManager를 init할 때 주입해주게되면 다시 Bank를 오픈했을 때 Customer를 생성하는 로직이 BankManager 내부에 있어야 된다고 생각하여 외부에서 Customer를 생성하고 BankManager의 메서드로 주입해주는 방식을 선택하였습니다!!!

2022-12-15 05:11 UTC, closed without merging