은행 창구 매니저 [STEP 3] 써니쿠키, inho
yagom-academy/ios-bank-manager pull request #247
Opened 2022-11-08 15:04 UTC by inho-98

@wonhee009
안녕하세요 라쟈냐! 🙇🏻‍♀️🙇
동시성으로 여러 실험을해보고, 고민이 많아 늦게서야 Step3 PR드립니다.😂
고민의 양만큼 PR이 무척이나 길어져버렸네요...!
Race Condition에서 정상작동을 위해 `DispatchSemaphore`와 `serialQueue`를 활용하는 방법을 각각 이용해보았고 결론적으로 저희 코드에서는 각 은행원이 SerialQueue를 갖고 동시성을 진행하는 방법으로 구현했습니다.
코드의 방향이 프로젝트 방향과는 다르게 빙빙 돌아왔나하는 의구심도 있어서 가감없는 리뷰 부탁드리겠습니다 🤣

## 📝 STEP 진행 중 경험하고 배운 것
- 동시성 프로그래밍 (Concurrency Programming)
    ☑️ GCD(Grand Central Dispatch)활용해 멀티 스레드 구현하기
    ☑️ 동기(Synchronous)와 비동기(Asynchronous) 동작의 구현 및 적용
    ☑️ Race Condition 해결하기 - `SerialQueue` 활용 / `DispatchSemaphore`활용
- POP (Protocol Object Programming)
    ☑️ Protocol의 Extension에 기본구현(Defalult Implementation)하기
    ☑️ Protocol 채택으로 특정 타입에 기능 부여하기

---
## 📱 코드 실행화면
|<img src="https://i.imgur.com/Qfi8qrR.gif" width=400>|
|---|

## ⚒️ 코드 구현내용
### 1️⃣ `BankManager`
- `Bank`와 `Customer`를 생성하고, 프로그램 실행 및 사용자 입력을 받는 메서드를 가지고 있는 타입으로 전체 실행을 담당합니다.
    - `startManagement()`: 메뉴를보여주고 사용자 입력에 따라 (1)은행문을열거나 (2)종료합니다.
    - `setupBank()`: 은행 객체를 만들고, 은행업무를 진행하기위해 은행문을 엽니다.
    - `receiveCustomer()`: 10~30명 사이의 랜덤한 수로 고객을 받습니다.
    - [enum] `Constant` : `BankManager`의 네임스페이스입니다.
### 2️⃣ `BankClerk`
- 은행원을 나타내는 타입으로, 업무 종류, 작업 처리 시간, 업무 창구를 가지고 있는 타입입니다.
    - `bankingType`: 업무 중 예금 혹은 대출 업무를 담당합니다.
    - `processingTime`: 업무 처리 시간을 나타냅니다.
    - `counter: DispatchQueue`: 시리얼큐로 구현될 은행창구로, 은행원이 한번에 한명의 고객을 처리하기 위한 것입니다.

### 3️⃣ `Servable` protocol + extension
- 손님을 상대하는 기능을 포함하고 구현한 프로토콜입니다.
    - `serve(customer: group:)`: 매개변수로 받은(자신에게 온) 손님의 업무를 담당하는 기능으로, 업무 처리시간만큼 손님의 업무를 처리하고, 진행과정을 출력해줍니다.

### 4️⃣ `BankingType`
- 은행 내 업무의 종류로 예금과 대출을 포함하고 있습니다.
    - `deposit`
    - `loan`
---

## 💭 고민한 부분
### 1️⃣ `RaceCondition`해결방법 -`DispatchSemaphore` / `serialQueue`
- `BankClerk` 3명이 `Queue`에 담긴 손님(업무)을 동시에 처리하기위해서 `GCD`를 이용해 멀티쓰레드환경을 구현해주었습니다. 이 과정 중에 하나의 데이터에 동시에 접근하여 생기는 `RaceCondition`을 해결하기 위해서 여러가지 시도를 해보았습니다.

#### **채택한 코드 : `BankClerk`프로퍼티에 `serialQueue`사용** 
- 요구사항에 제시된 3명의 은행원들이 각자의 은행업무에 맞는 손님을 차례로 응대하기 위해 은행원의 프로퍼티에 `DispatchQueue`를 추가했습니다. 은행원은 한번에 한명의 손님을 처리할 수 있기 때문에 `serial`큐로 초기화합니다. 손님을 순서대로 `dequeue`하고 전달받은 후에는 자신의 시리얼큐에 비동기로 작업을 넘기도록 구현했습니다.
- 은행원을 나타내는 `BankClerk`의 인스턴스를 의도한대로 활용하기 위한 코드를 고민했습니다.
    ```swift
     while !customers.isEmpty {
        bankClerks.forEach { bankClerk in
            guard let customer = customers.dequeue() else { return }

            bankClerk.serve(customer: customer, group: group)
            ...
        }
    }

    func serve(customer: Customer, group: DispatchGroup) {
        counter.async(group: group) { //counter는 자신의 시리얼 큐입니다.
            //업무 시작 및 종료 출력
        }
    }
    ```
- 👉 **첫번째 시도 : `DispatchSemaphore`사용**
    <details>
        <summary>details</summary>
    
    - 동시에 처리할 수 있는 손님이 은행원 인원과 같기 때문에 `쓰레드 수 = 은행원 인원` 이라고 생각했습니다. 
    - `DispatchSemaphore`의 `value = 은행원 인원` 으로 지정하여 은행원 수만큼만 동시진행 될 수 있도록 구현했었습니다.
        ```swift
        struct Bank {
            let cumstomers: Queue<Customer> = Queue()
            let depositBankeClerks: [DopositBankClerk]// 2명
            let loanBankClerks: [LoanBankClerk]  // 1명 

            private mutating func startBanking() {
                let depositSemaphore = DispatchSemaphore(value: depositBankeClerks.count) // 2
                let loanSemaphore = DispatchSemaphore(value: loanBankClerks.count) // 1
                
                while !customers.isEmpty {
                    guard let customer = customers.dequeue() else {
                        return
                    }

                    DispatchQueue.global().async { [self] in
                        switch customer.bankingType {
                        case .deposit :
                            depositSemaphore.wait()
                         👉 DepositBankClerk.serveCustomer(number: customer.waitingNumber)  //손님 업무 시작과 끝프린트 출력하는 함수
                            depositSemaphore.signal()
                        case .loan:
                            loanSemaphore.wait()
                         👉 LoanBankClerk.serveCustomer(number: customer.waitingNumber) //손님 업무 시작과 끝프린트 출력하는 함수
                            loanSemaphore.signal()
                        }
                    }
                }
            }
        }

        struct DepositBankClerk {
            static func serveCustomer(number: Int) {
                // 손님 업무 시작과 끝을 Print하는 코드
            }
        }
        ```
    - 😵채택하지 않은 이유😵
        - 1) BankClerk의 인스턴스를 활용하지 않기 때문이었습니다.
            (=인스턴스 메서드 대신 타입메서드를 사용하는 문제였습니다)
            BankClerk타입을 구현해놓고, `serveCustomer(number:)`로 손님을 처리하는 함수를 사용할 때, 은행원 각자의 인스턴스 메서드를 사용하지 못해서 의도한 방향과 다르다고 생각했습니다.(사용하더라도, 은행원이 두명인데 한명의 것만 사용하게됐습니다). 타입메서드가 아닌 은행원(인스턴스)들이 가지고있는 인스턴스 메서드를 사용해 손님을 처리하는게 맞는 방향이라고 생각했습니다. 
        - 2) 1)의 문제로 애초에 BankClerk 타입 구현을 하지않고 (인스턴스를 생성할 일이 없게 되고), Bank 내부에서 각 은행원의 인원수를 Int로 갖는 프로퍼티를 구현하는 방법도 생각했었습니다. 하지만 객체지향 프로그래밍과 맞지 않다고 생각했습니다. </br></br>  
</details>
    
- 👉 **두번째 시도 : `serialQueue`사용 & `customers Queue` 분류없이 직접 처리하기**
    <details>
        <summary>details</summary>
    
    - PR드린 코드는 손님이 담겨있는 `Queue`를 은행업무 종류에 따라 `depositQueue`와 `loanQueue`로 다시 분류해서 `Queue`에 담아준 후 타입이 같은 은행원이 손님처리를 하는 로직인데 손님분류 없이 손님의 은행업무타입이 섞여있는 원래의 `Queue`에서 바로 손님처리를 할 수 있는 코드를 구현하고 싶었습니다. 
    - 처음엔 `bankClerk` 이 담긴 `Array`에 `forEach`를 사용해 업무타입을 `Switch`문으로 구분해서 손님을 처리하도록 구현해주었었습니다. 예금은행원 두명이 공평하게 반씩 차례로 손님을 처리하지 않고 중간에 대출손님이 껴있으면 순서가 꼬이는 문제가 있었습니다. 그래서 순서에맞게 손님을 처리하기 위해 `bankClerk Array`에서 한 은행원씩 차례로 불러줘야했습니다. 0부터 +1씩 올라가는 변수에 은행직원 인원보다 커지면 다시 0으로 돌아가도록 설정한 변수를 선언하고 `Array index`로 사용해 은행원이 번갈아가며 손님을 처리할 수 있도록 구현했었습니다.
        ```swift
        func serveCustomer() {
            let depositMaximun = depositBankClerk.count - 1
            let loanMaximum = loanBankClerk.count - 1
            var depositPossible: Int = 0 {
                didSet(oldValue) {
                    depositPossible = oldValue > depositMaximun ? 0 : oldValue
                }
            }
            var loanPossible: Int = 0 {
                didSet(oldValue) {
                    loanPossible = oldValue > loanMaximum ? 0 : oldValue
                }
            }
            
            while !customers.isEmpty {
                guard let customer = customers.dequeue() else {
                    return
                }

                switch customer.bakingType {
                case .deposit:
                    depositBankClerk[depositPossible].call(customer: customer)
                    depositPossible += 1
                case .loan:
                    loanBankClerk[loanPossible].call(customer: customer)
                    loanPossible += 1
                }
            }
        }

        struct banker {
            func call(customer: Customer) {
                counter.async(group: group) {
                    // 손님 업무 시작과 끝을 Print하는 코드
                }
            }
        }
        ```
    - 😵채택하지 않은 이유😵
        - 이 시도는 `customers Queue`를 `BankingType`별로 분류해 다시 두개의 `Queue`(예금별, 대출별)를 생성하는 작업을 하지 않기 위해 시도해본 코드였는데, 작성 후에 비교해보니 `Queue`를 분류해서 처리하 코드가 더 깔끔하고 보기 좋은 것 같다고 판단해서 채택하지 않았습니다.  
    </details>   

### 2️⃣ `Servable`프로토콜과 익스텐션의 활용 
- 은행원의 업무를 `손님을 응대할 수 있는`기능이라 판단했고, 이 기능 구현이 코드를 작성하는 중간에 재사용되기도 하여 프로토콜로 분리하였고, `extension`을 통해 기본 구현을 추가했습니다. 이 프로토콜 내에는 은행원이 손님을 응대하는 과정에 필요하다고 생각한 요소들을 포함하였습니다.
- `counter: DispatchQueue`: 은행 창구를 나타내면서, 코드 실행중에는 비동기로 작업을 처리하기 위한 요소입니다. 은행원은 한번에 한명의 손님을 처리해야 하고, 순서가 중요하기 때문에 해당 큐를 `serial`로 초기화 하였습니다.
- `serve(customer:, group:)`: 매개변수로 받은 손님을 자신의 시리얼 큐로 비동기 처리한 후, 고객과 업무종류를 출력하고, 처리하는 기능을 합니다.
```swift
protocol Servable {
    var processingTime: Double { get }
    var counter: DispatchQueue { get }
    func serve(customer: Customer, group: DispatchGroup)
}

extension Servable {
    func serve(customer: Customer, group: DispatchGroup) {
        counter.async(group: group) {
            print("\(customer.waitingNumber)번 고객 \(customer.bankingType.name)업무 시작")
            ...
        }
    }
}
```

### 3️⃣ `Command Line Tool`에서 `main`스레드의 런루프가 종료되는 문제
- 프로젝트를 실행할때, `DispatchQueue.main.async`가 작동되지 않고, 다른 스레드의 비동기 작업도 끝까지 기다리지 않고 프로그램이  [...]

2022-11-09 03:56 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요.

- runloop를 어떻게 사용하셨는지 궁금합니다.
- protocol에 네임스페이스를 어떤 경우에 추가하려고 하셨는지 궁금합니다.
- 코드에 정답은 없기 때문에 현재 방향도 괜찮다고 생각합니다. 다만, 은행원이 본인 업무가 끝났다면 delegate/notification 등등을 이용해 본인 창구가 비었음을 알리고 어딘가에서 은행원에게 고객을 지정해주는 방식으로 디벨롭할 수 있을거 같습니다.

2022-11-09 03:56 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +                                     counter: DispatchQueue(label: "depositCounter1"))
processingTime은 bankingType에 따라 동일할거 같은데요.
BankingType의 프로퍼티로써 가지고 있는건 어떤가요?

2022-11-09 03:56 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +                               counter: DispatchQueue(label: "loanCounter1"))
여기서 인스턴스를 직접 만드는거보다 Bank에 init 인터페이스를 추가하는건 어떤가요?
`Bank(depositClerkCount: Int, loanClerkCount: Int)` 이렇게요.

2022-11-09 03:56 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Servable.swift
> +    var counter: DispatchQueue { get }
counter는 어떤 의미로 사용한건가요?

2022-11-09 03:56 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankingType.swift
> +    case loan = 2
rawValue가 필요한가요?

2022-11-09 03:56 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    mutating func sortCustomer() -> (Queue<Customer>, Queue<Customer>) {
sortCustomer여서 정렬을 하는줄 알았는데요.
로직은 정렬은 아녀서 네이밍이 바뀌면 좋을거 같습니다.

2022-11-09 03:56 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
예금 업무를 하는 은행원은 거의 동시에 일을 시작할 수밖에 없을거 같은데요. 맞을까요?

2022-11-09 08:38 UTC, inho-98 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +                                     counter: DispatchQueue(label: "depositCounter1"))
저희도 이 부분을 고민했었는데요, 실제로는 은행 업무에 소요되는 시간이 업무의 종류보다는 처리하는 은행원에 따라 달라지는 부분이라고 생각해서 은행원의 프로퍼티로 적용해봤습니다! 말씀해주신 방향으로 코드를 구현한다면 아래와 같이 적용할 수 있을 것 같습니다! 
(연산프로퍼티 혹은 rawValue 사용)
```swift
//예시 코드
var processingTime: Double {
    switch self {
    case .deposit:
        return 0.7
    case .loan:
        return 1.1
    }
} 
```

2022-11-09 08:45 UTC, inho-98 commented on BankManagerConsoleApp/BankManagerConsoleApp/Protocol/Servable.swift
> +    var counter: DispatchQueue { get }
은행 직원이 담당하는 `은행 창구` 라는 의미로 사용하였습니다.
비슷한 단어들로 `window`, `booth` 등을 고려했는데 `counter`가 적절하다고 판단하여 사용했습니다!

2022-11-09 08:48 UTC, inho-98 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankingType.swift
> +    case loan = 2
코멘트 남겨주셔서 `rawValue`를 사용하지 않는 방향을 생각해 보다가 `enum`의 `allCases`를 적용했습니다!
```swift
guard let bankingType = BankingType.allCases.randomElement() else { return }
...
```
위 코드와 같이 수정하였습니다.
추후에 은행업무 종류에 다른 case가 추가되는 상황에도 적용 가능해서 코드가 더 나아진 것 같습니다! 감사합니다 😀

2022-11-09 08:51 UTC, inho-98 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    mutating func sortCustomer() -> (Queue<Customer>, Queue<Customer>) {
말씀해주신대로 `sort`이름의 메서드가 배열 등에서 정렬하는 역할을 하고 있고,
저희가 작성한 메서드의 기능은 손님을 은행 업무에 따라 `나누는` 기능을 수행하고 있습니다.
그래서 `divideCustomer()`라는 네이밍으로 수정하였습니다!
> 9173935

2022-11-09 08:56 UTC, sunny-maeng commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
네 맞습니다..!

은행원이 손님을 처리하는 `serve`메서드 내부 로직을 설명하면,  은행원의 `Counter(작업대)`는 `SerialQueue`로  한명 씩 차례차례 손님을 처리하게 됩니다. 이 때 은행은 여러 은행원들이 동시에 손님을 처리하게 하기 위해서 손님을 직원들(`SerialQueue`)에게  보내는 작업을 비동기적(`async`)으로 보내줍니다. 은행원들은 여러명을 받았지만 `SerialQueue`이기 때문에 차례로 한명씩 처리해 나가게 됩니다.

예시로 예금은행원들이 작업 처리하게 되는 순서를 적어보자면, 은행에서 한 손님을 `dequeue()` 해서 첫번째 예금직원의 작업대로 보내줍니다. 그러면 그 직원은 0.7초에 걸치는 작업을 시작합니다. 이 때 은행은 손님을 비동기적(`async`)으로 직원에게 보내주기 때문에 0.7초를 기다리지 않고 바로 다음 손님 `dequeue()`해 두번째 예금직원에게 보내줍니다. 이렇게 연달아 예금직원을 번갈아서 모든 손님을 보내줍니다. 그러면 모든 예금직원 작업대에는 손님들이 줄 서있게 되는데  `serialQueue`이기 때문에 한명씩 차례로 처리하게됩니다.

2022-11-09 09:42 UTC, sunny-maeng commented
저희가 질문을 상세하게 못해서 죄송합니다 ㅜㅜ
달아주신 코멘트에서 질문주신것에 대한 답변입니다!

1. RunLoop 사용
> runloop를 어떻게 사용하셨는지 궁금합니다.

```swift
mutating func runBankingCycle() {
    ...
    let group = DispatchGroup() 
    matchClerk(to: &customers.deposit, of: .deposit, group: group)
    matchClerk(to: &customers.loan, of: .loan, group: group)
    //group.wait()
    RunLoop.current.run() // 혹은 RunLoop.main.run()
    closeBanking()
}
```
- 위 코드에서 기존 코드인 `group.wait()`대신 `RunLoop.current.run()`를 적용했었는데요, `run`메서드를 사용하면 `matchClerk()`이후의 코드가 작동하지 않고, 프로그램도 종료되지 않았었습니다. `run()` 메서드를 공부해보니 그 쓰레드를 계속 사용한다는 메서드인 것을 알고 `run(until:)`에 매개변수를 전달하여 적절한 시간 후에 종료되게도 해보았습니다. 하지만 실행시 마다 바뀌는 실행 시간을 계산하는 방법을 찾지 못했습니다.
- runLoop로 해결하려는 방법이 잘못된 접근 방식인지, 아니면 저희가 아직 찾지못한 runLoop를 이용한 다른 해결방법이 있나 궁금합니다. 😂 

---

2. Protocol Extension과 네임스페이스
> protocol에 네임스페이스를 어떤 경우에 추가하려고 하셨는지 궁금합니다
```swift
extension Servable {
    func serve(customer: Customer, group: DispatchGroup) {
        counter.async(group: group) {
            print("\(customer.waitingNumber)번 고객 \(customer.bankingType.name)업무 시작")
            Thread.sleep(forTimeInterval: processingTime)
            print("\(customer.waitingNumber)번 고객 \(customer.bankingType.name)업무 종료")
        }
    }
}

//step2에서 사용했던 네임스페이스
enum Constant {
    static let startMessage = "%d번 고객 업무 시작"
    static let endMessage = "%d번 고객 업무 종료"
}
```
- step2에서는 고객업무 시작과 종료를 출력하는 구문을 상수로 만들어주기 위해서 `namespace`를 사용했었습니다. 그리고 이 네임스페이스는 출력구문이 사용되는 `클래스의 extension`에서 구현되어있었습니다.
- step3를 진행하면서 출력구문이 있는 메서드를 `프로토콜 extension`으로 옮겨주게되면서 `nameSpace`도 같이 옮겨주고 싶었습니다. 전역으로 구현하기에는 프로토콜 내부에서만 쓰이기 때문에 프로토콜이 갖고있으면 좋겠다고 생각했는데 방법을 찾지 못했습니다.

2022-11-10 12:35 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +                                     counter: DispatchQueue(label: "depositCounter1"))
"처리하는 은행원에 따라 달라지는 부분" 이라는 말이 명세서에 있는 말일까요?
명세서에는 "고객이 원하는 업무의 종류와 소요시간은 아래와 같습니다. 대출 : 1.1초, 예금 : 0.7초"라고 써져 있는데요. 이 말은 업무의 종류에 따라 소요시간이 달라진다는 말과 동일하지 않을까요?
또한 지금 코드처럼 은행원을 생성해준다면 개발자 휴먼에러의 가능성이 있을거 같습니다.
0.7을 0.8이라고 입력한다든지...?

2022-11-10 12:50 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
1. 모든 손님을 업무의 종류(예금/대출)에 따라 나눈다.
2. 나눈 손님을 forEach문을 통해 미리 은행원 SerialQueue에 넣는다.

이 순서로 이해했는데요.
결국 forEach를 돌면서 dequeue하는데 async인게 의미가 있나요? 어차피 순차적으로 진행될텐데요.

2022-11-10 13:04 UTC, wonhee009 commented
- [해당 포스트](https://babbab2.tistory.com/68)가 도움이 될 것 같습니다.
- 네임스페이스를 static 키워드를 사용해서 지정할텐대요. `static` 키워드에 대해 알아보는 것도 좋을거 같습니다.

2022-12-15 05:11 UTC, closed without merging