은행창구 매니저 [STEP 3] Baem, Bella
yagom-academy/ios-bank-manager pull request #248
Opened 2022-11-08 15:27 UTC by hyhy0429

@uuu1101 
안녕하세요 태태! 🙌🏼
은행창구 매니저 [STEP 3] p.r을 보냅니다! 잘 부탁드립니다! 🙆🏻‍♀️🙆🏻‍♂️ 

### [고민했던 점]
#### 동기 비동기 사용
- 예금 업무와 대출 업무를 `DispatchQueue.global().sync` 로 보내게 될 경우에, 예금 업무와 대출 업무가 동시에 처리되지 않고 하나씩 처리되어 프로젝트의 요구사항과 맞지 않다고 생각되어, `async`로 처리하게 되었습니다. 

#### DispatchSemaphore 사용
- 예금과 대출 업무를 `global.async` 를 이용하여 보낼 경우에, 랜덤하게 생성한 고객 수 만큼(필요한 만큼) 쓰레드를 생성하게 되었습니다. 이를 해결하기 위해, `DispatchSemaphore`와 `SerialQueue` 두 가지 방법 중에 고민하게 되었으며 예금 업무와 대출 업무의 쓰레드의 개수를 DispatchSemaphore의 value 를 이용하여 지정해주게 되었습니다. 

#### 큐의 사용
- 처음 `예금 큐` `대출 큐` 를 따로 만들어서 사용하고자 하였습니다. 그러나, Bank 타입 내부에 예금 매니저 2명과 대출 매니저 1명을 생성했고, 예금 매니저에게 예금 큐에 들어있는 고객을 처리하도록 구현해보았으나 구현에 실패하게 되었습니다.🥲
그래서, 일단은 구현에 목적을 두고 고객대기열을 단일 큐로 만들었으며 고객을 enqueue() 할 때에 예금과 대출 업무를 랜덤하게 넣어주게 되었습니다. 

### [조언이 필요한 점]

#### 뱅크매니저
- 앞서 큐의 사용에서 기재한 내용과 이어지는 부분입니다. `BankManger` 를 은행원이라 생각 한 후 예금처리하는 은행원 2명, 대출 처리하는 은행원 1명이라 생각하고 `Bank` 타입을 은행 창구라고 생각해서 은행원들을 처리해주는 곳에 따라 넣어주고자 하였습니다. 
하지만 너무 방대한 생각이여서, 결국은 하나의 고객대기열에 각각의 업무에 따라 쓰레드가 접근하도록 하였으며 접근할 수 있는 스레드의 개수를 `Semaphore`를 사용해서 예금과 대출 업무를 처리하도록 구현하였습니다.

``` swift
mutating private func startTask() {
    ...

    
        while lineOfLoanCustomer.isEmpty == false {
            guard let currentCustomer = lineOfLoanCustomer.dequeue() else { break }
            DispatchQueue.global().sync {
                loan1.task(customer: currentCustomer)
            }
        }
        while lineOfDepositCustomer.isEmpty == false {
            guard let currentCustomer = lineOfDepositCustomer.dequeue() else { break }
            DispatchQueue.global().sync {
                depo1.task(customer: currentCustomer)
            }
        }
// 위에서 이미 lineOfDepositCustomer가 비어있는 상태라, 아래 코드가 실행되지 않음!!🥲
        while lineOfDepositCustomer.isEmpty == false {
            guard let currentCustomer = lineOfDepositCustomer.dequeue() else { break }
            DispatchQueue.global().sync {
                depo2.task(customer: currentCustomer)
            }
    ...
        }
```

#### Struct, class로 변경 (클로저 캡쳐)
- `struct Bankmanager` 의 타입이 Struct일 때, `Bank`의 DispatchQueue 에서 사용하면 불변하는 값이기 때문에 변경 할 수 없다라는 클로저 캡처와 관련된 오류가 발생 하였습니다. 아래 사진 첨부했습니다!

![](https://i.imgur.com/2CUCsq8.png)

- 고민해보며 캡쳐드리스트를 이용하여 오류를 해결해보고자 하였으나 해결되지 않았고, 어떻게 해야할지 몰라 타입 자체를 struct -> class로 변경하여 오류를 해결 했습니다.

2022-11-10 06:18 UTC, uuu1101 requested changes
안녕하세요 ! 뱀,벨라!
몇가지 코멘트 남겨두었습니다 ! 확인부탁드려요 !

**[조언이 필요한 부분에 대한 답변]**
- 기존에 구현을 어떤방식으로 접근했는지 궁금합니다.
고객 리스트 업을 하는 동시에 각 고객에게 업무를 부여하고 그 부여된 업무에 따라서 각 대기열로 보내주거나 두 분이 작성하신것 처럼 각각 다시 줄을 세워 그 줄에 대한 대기열로 보내주는 방식이 있을 것 같아요.
대기열은 각 업무마다 하나씩 있으면 될 것 같은데 예금 업무에 대해 2개의 대기열을 작성하시려고 한 이유가 있으실까요? (스레드라는 개념이 있기 때문에 질문드려요)

- Struct, Class에 대한 부분
해당 하는 오류 부분을 `struct` + `mutating` 키워드를 통해 수정을 하게 되면 마지막에는 Bank.swift 의 71번째 줄에서 에러 메세지를 만나게 될텐데요. 
71번째에서 사용한 `DispatchQueue.global().async(group: group)` 코드가 어떻게 구현이 되어 있는건지 group에 해당하는 부분은 어떤 타입이 파라미터로 들어가야하는지 확인해보시면 좋을것 같습니다.

2022-11-10 09:59 UTC, hyhy0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let group = DispatchGroup()
[94fceaf](https://github.com/yagom-academy/ios-bank-manager/pull/248/commits/94fceaf5b7fb070ca9b2bb517fd33aa695a1bec3)

업무처리를 위해 DispatchQueue에 보내주는 일을 하는 그룹이라고 생각하여, 조금 더 어떤 그룹인지 명확히 알 수 있도록 네이밍을 변경해주었습니다!

2022-11-10 10:10 UTC, Dylan-yoon commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +            usleep(1100000)
[94fceaf](https://github.com/yagom-academy/ios-bank-manager/pull/248/commits/94fceaf5b7fb070ca9b2bb517fd33aa695a1bec3)

언더바를 사용 할 수 있다는 것을 알고는 있었는데, 숫자 에서 언더바를 사용하는건 그냥 무시 처리가 되는건지 궁금합니다.
또한 `let _ : String = "UnderBar"`, 전달인자 레이블에서의 사용 에서 "아무것도 없다" 의미로 알고 있는데, 
스위프트에서는 언더스코어(_)가 어떤의미인지 알 수 있을까요? 
또 다른곳에서 언더스코어(_) 사용하는 곳이 있나요?

2022-11-10 11:39 UTC, Dylan-yoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private let depositFront = 2
[f6e4848](https://github.com/yagom-academy/ios-bank-manager/pull/248/commits/f6e4848d2afc8b1019f499585a36000174de54d8)

저희는 Task에서 업무를 관리 할 것이라고 생각했습니다
따라서 Task에서 loanFront, depositFront관련된 front 프로퍼티를 만들어 관리해주면 좋을 것 같아 변경했습니다!🤡

2022-11-10 13:55 UTC, Dylan-yoon commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +    var loanTimer: Double = 0
[d066103](https://github.com/yagom-academy/ios-bank-manager/pull/248/commits/d0661039e36f073d62d2db682e0c12485acc61b3)

확인했습니다! 
다른 커밋과 같이 리펙토링하여 변경했습니다!

2022-11-10 14:07 UTC, hyhy0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
[d066103](https://github.com/yagom-academy/ios-bank-manager/pull/248/commits/d0661039e36f073d62d2db682e0c12485acc61b3)
처음에는 예금과 대출 업무에 따라 일처리를 하는 메서드인 `task()`만 뱅크매니저가 들고 있게끔 코드를 구현하였는데, 태태의 피드백을 듣고 생각해보니 업무를 큐에 보내는 작업 또한 은행원이 가지고 있는게 일관성 있다고 생각이 들었습니다.
또한 `dispatchTask()` 를 옮기다보니 일을 시작하고 마무리 짓는 함수들도 `BankManager`가 가지고 있도록 수정해보았습니다!

2022-11-10 14:11 UTC, Dylan-yoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
```
func startTask(_ customerList: LinkedList<Customer>) {
         let loanSemaphore = DispatchSemaphore(value: loanFront)
         let depoSemaphore = DispatchSemaphore(value: depositFront)
         var lineOfCustomer = customerList
...
```
추가로 고객 대기열을 매개변수로 받아 큐를 꺼내오는 작업을 위해 변수로 값을 할당 해주었는데 이렇게 사용해도 되는지 궁금합니다!

2022-11-11 06:00 UTC, uuu1101 commented
질문 관련된 부분 Discord 통해서 대화 나누었습니다.
STEP3 고생하셨습니다 ! 👏🏻👏🏻👏🏻

2022-11-11 06:01 UTC, merged