Step3 -  innie, odongnamu
yagom-academy/ios-bank-manager pull request #25
Opened 2021-01-13 18:56 UTC by odong-Tree

Step3 
BankManager ConsoleApp 

[주요 구현 사항]
- 각 은행원들이 모두 같은 본사에 접근해야하기 때문에 본사는 싱글톤으로 구현했습니다. static 명은 ‘본사’와 가장 잘 어울린다고 생각한 main으로 만들었습니다. 

- Step2에서의 DispatchQueue 구현 내용을 OperationQueue로 변경하여 구현해보았습니다. Single OperationQueue로 구현했을 때, Thread-safe가 보장되어서 코드가 보다 간결하게 구현되었습니다. step2에서 사용했던 DispatchSemaphore와 DispatchGroup의 기능을 짧은 코드로 대체할 수 있었습니다. 

- BankClerk 타입을 삭제하고 Client를 Operation을 상속받는 ClientOperation 타입으로 변경하여 기존의 BankClerk의 기능과 Client의 정보를 함께 캡슐화해보았습니다.

- 출력 문자열을 관리하는 열거형을 만드는 실험적인 시도를 해보았습니다. 수정에 용이하게 만들어보고자 시작했으나 이러한 경우 몇가지 장점과 단점이 있었습니다.

장점: 한 곳에서 문자열을 관리하고 있기 때문에, 만약 전체적인 콘솔 출력문이 수정될 경우에 유리하다. 수정을 위해 코드 구석구석을 찾아다닐 필요가 없다.
단점: 응집도가 낮아지고 결합도가 높아졌다. 코드와 관련된 출력 문자열이 다른 객체에 있기 때문에 관련된 정보가 흩어지는 느낌이 있다. 또한 새로운 객체가 생성되고 서로 소통해야하는 상황이 되므로 결합도가 높아졌다고 볼 수 있다.

결론은 프로젝트나 앱의 성격상 출력문이 자주 수정이 되거나, 출력문 관리가 아주아주 중요할 경우에는 채택할 수도 있을 법한 방법이라는 생각이 들었습니다. 하지만 일반적인 경우에는 객체지향적인 프로그래밍에는 좋은 영향을 준다고 생각되지는 않는 것 같습니다. 

이 부분을 구현하면서 팀원끼리도 여러번 의견이 갈리거나 고민하게되는 상황들이  발생했는데, 혹시 리뷰어 분은 이렇게 문자열을 한 곳에서 관리하는  것에 대해서 어떻게 생각하시는지요 ? 혹은 실무에서 이렇게 사용하는 경우가 있나요?

리뷰 부탁드립니다 :)

2021-01-15 07:08 UTC, yagom requested changes
DispatchQueue와 OperationQueue는 정말 비슷해보이지만 다른 부분이 꽤 많죠?ㅎㅎ
더 적절한 선택으로 코드가 훨씬 간결해졌네요!

BankClerk 타입을 삭제하고 다른 타입과 통합하는 것을 시도한 것이 굉장히 인상깊습니다.
프로그래밍을 할 때 정말로 세성의 모습 그대로를 녹여내려고 하는 경향이 없지않아 있는데, 이렇게 타입을 구현하다보면 세상의 모습을 그대로 가져오는 것보다 코드 세상에 맞게 타입을 추상화 하는 능력과 센스도 필요해요. 정말 좋은 관점의 전환입니다! 칭찬 백만개 박을게요! 👍👏

문자열은 대체적으로 따로 떼어 관리하는 경우가 많습니다.
그 이유는 여러가지 있지만 관리의 용이성과 유연함이 가장 큽니다.
오동나무가 코멘트에서 언급했듯이 여기저기 찾아다닐 수고도 없죠.
안내문구는 언제든 수정가능하기 때문에 코어타입 내부의 코드를 수정하는 것보다 따로 관리하고 있는 string 파일이나 문자열 관리 타입을 수정하는 것이 훨씬 안전하겠죠.
지역화(localization)을 위해서도 꼭 필요하기도 하고요.
굉장히 의미깊은 고민이었습니다!

딱 한가지 업무 프로세스에서 수정해야 할 부분이 있어서 수정 요청합니다 :)

2021-01-15 07:08 UTC, yagom commented on BankManagerConsoleApp/BankManagerConsoleApp/HeadQuarter.swift
> +    }
대출심사 진행이 본사와의 소통을 하는 것이 아니라 일정시간 대기하는 형태로 구현되어있습니다.
본사의 허락을 받아야 대출을 수행할 수 있는데, 승인을 기다리지않고 시간만 떼우는 것에는 업무 프로세스의 문제가 있을것 같습니다.
이 부분은 꼭 수정해봐야겠습니다. 본사의 승인을 얻은 후에 일을 진행하려면 어떻게 하는것이 좋을까요?

2021-01-15 15:36 UTC, odong-Tree commented
[코드 수정 방향]
- 고객이 대출 적격자인지 부적격자인지를 판단할 수 있는 isLoanQualified 프로퍼티를 ClientOperation에 추가했습니다.
- ClientOperation의 isLoanQualified에 따라 본사의 대출  심사 결과가 달라지도록 구현하였습니다.

2021-01-16 03:04 UTC, yagom approved these changes
네, 고생 많았습니다.

고민 중에 노티피케이션, 딜리게이션, 컴플리션 핸들러 등 다양한 수단이 있었을 것 같은데, 지금의 모습으로 구현한 이유도 궁금하네요 :) 
이번 스텝 여기서 머지합니다!

2021-01-16 03:04 UTC, merged