은행 창구 매니저 [STEP 1] 혜모리, 레옹아범
yagom-academy/ios-bank-manager pull request #257
Opened 2023-03-06 07:40 UTC by fatherLeon

@July911
안녕하세요 줄라이! 레옹아범, 혜모리 인사드립니다 🙇🏻‍♂️🙇🏻‍♀️
이번 은행 창구 매니저 프로젝트 리뷰 잘 부탁드립니다.

---
## 고민했던 점

둘 다 이전에 진행한 계산기 프로젝트에서 Linked List Queue를 구현한 적이 있어 어렵지 않게 작업할 수 있었습니다.

### 1️⃣ LinkedList와 Queue 타입의 유닛테스트 진행방법

- 현 시점에서 `Queue` 타입은 `LinkedList` 타입의 프로퍼티와 메서드를 그대로 호출하고 있어 어떻게 각각 유닛테스트를 진행할지 고민하다가 `LinkedList` 테스트는 혜모리가, `Queue` 테스트는 레옹아범 쪽에서 주도하여 진행하는 것으로 결정했습니다.

---
## 조언이 필요한 점

### 1️⃣ Unit test 오류

Unit test 시 접근 수준이 internal인 타입에 접근하기 위해 아래와 같이 프로젝트를 import하였습니다.

``` swift
@testable import BankManagerConsoleApp
```

그러나 Unit test를 돌리니 아래 이미지와 같은 오류가 발생했습니다.

![](https://i.imgur.com/ZQ0wCij.png)

구글링을 해보니 확실치 않지만 UITest에 `@testable import`를 하면 Undefined symbol 오류가 발생한다고 합니다.
우선은 Node, LinkedList, Queue 타입의 `Target Membership`에서 각 Unit test를 추가하는 것으로 해결했습니다.
iOS 프로젝트의 경우 이런 문제가 발생하지 않았는데 해당 문제가 CommandLineTool이라서 이런 문제가 발생한건지? 발생한 원인을 알 수 없어 조언을 구하고 싶습니다.

### 2️⃣ Queue와 LinkedList 테스트케이스 중복

```swift
struct Queue<T> {
    private var queue = LinkedList<T>()
    var peek: T? { queue.peek }
    var isEmpty: Bool { queue.isEmpty }
    
    mutating func enqueue(_ data: T) {
        queue.appendLast(data)
    }
    
    mutating func dequeue() -> T? {
        return queue.removeFirst()
    }
    
    mutating func clear() {
        queue.removeAll()
    }
}
```

- `Queue`의 프로퍼티와 메소드는 전부 `LinkedList`에 종속?, 의존?되어 있는 형태이며 똑같은 과정과 결과를 내는데 Queue와 LinkedList각각 테스트 케이스를 작성해야할지 궁금합니다.
- `Queue` 혹은 `LinkedList`가 가지고 있는 고유한 프로퍼티 혹은 메소드가 있을 때에만 사용하는게 좋을것 같은데 어떻게 생각하시나요?

2023-03-06 19:03 UTC, July911 requested changes

2023-03-06 19:03 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        let node = Node(orderNumber: data)
mutating은 왜 붙여주었을까요 ?

2023-03-06 19:03 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Node.swift
> +    var orderNumber: T
final 키워드는 왜 사용하셨나요 ?

2023-03-06 19:03 UTC, July911 commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +        XCTAssertTrue(condition)
지금은 removeAll을 안해도 둘다 nil아닌가요 ? 아무것도 append하지 않는걸로 보여서요

2023-03-06 19:18 UTC, July911 commented
일단 빠른 시간안에 많은 구현을 하신점 정말 훌륭합니다. 
### Unit test 오류
맞습니다. 
Command line tool 은 GUI framework을 사용하고 있지 않습니다.
### Queue와 LinkedList 테스트케이스 중복
현재로서는 충분하다고 생각합니다. 단순한 자료구조를 구현해놓으신 것 같아서요. 
하지만 테스트 하는 방향이 맞냐는 건 다른 문제라고 생각합니다. 
코멘트를 한번 보시고 어떤 방향으로 테스트하는게 맞는지 다시 한번 생각해보시면 좋을 것 같습니다. 

두분 다 정말 고생 많으셨습니다. 

추가적으로, 다음 스텝부터는 커밋단위를 조금 작게 해보시는걸 권장드립니다.

2023-03-07 01:06 UTC, fatherLeon commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Node.swift
> +    var next: Node?
은행에 도착한 고객의 순번을 나타내기위해 orderNumber를 사용하였습니다

2023-03-07 01:17 UTC, hyemory commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Queue.swift
> +    private var queue = LinkedList<T>()
- `Node` : 노드 하나를 구성하는 Node 클래스의 경우, 하나의 노드에서 다음 노드의 포인터를 가지고 있기 때문에 각각의 참조를 알 수 있어야한다고 생각했습니다.
- `LinkedList`, `Queue` :  하단 링크에 따라서  objective-C를 사용하지 않고, 참조하거나 상속할 필요가 없어 구조체로 구현하였습니다.
- https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes

2023-03-07 01:21 UTC, hyemory commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Queue.swift
> +    var isEmpty: Bool { queue.isEmpty }
100자가 넘어가지 않고 한 줄일 경우 return을 생략하고 한 줄로 표현하기로 하였습니다.

2023-03-07 01:24 UTC, fatherLeon commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +    var sut: LinkedList<String>!
* system under test의 약자입니다.
* cut - class under test, out - object under test 등등 축약어가 많지만 이를 전부 포함하는 SUT를 사용하였습니다.

2023-03-07 01:28 UTC, hyemory commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +        try super.setUpWithError()
- `override` : 부모 클래스의 프로퍼티나 메서드를 재정의하여 사용할 수 있는 키워드입니다.
- `super.` : 부모 클래스에 있는 메서드를 호출하고 싶을 때 사용하는 키워드입니다.

2023-03-07 01:34 UTC, fatherLeon commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +        try super.tearDownWithError()
* `setUpWithError`: 각각의 테스트케이스가 실행되기 전에 호출되는 메소드로 무언가의 초기 값을 주기위해 사용합니다.
* `tearDownWithError`: 테스트케이스가 끝난 후 호출되는 메소드로 초기화를 시켜주기 위해 사용합니다.
* 각각의 테스트케이스가 고유한 LinkedList를 가지기 위해서 위 메소드를 통해 `sut`를 정의하거나 초기화해주는 역할을 하고 있습니다.

2023-03-07 01:53 UTC, hyemory commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +
아무것도 추가하지 않았을 때 리스트가 비어있는지 확인하는 테스트를 추가하였습니다.

``` swift
func test_List에초기값은_비어있다() {
    // given
    
    // when
    let result = sut.isEmpty
    
    // then
    XCTAssertTrue(result)
}
```

2023-03-07 01:58 UTC, fatherLeon commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +        XCTAssertEqual(result, expectation)
```swift  
func test_removeFirst호출시_List에1하나만있는경우_반환된orderNumber는_1이다() {
      // given
      sut.appendLast("1")
      let expectation = "1"

      // when
      let result = sut.removeFirst()

      // then
      XCTAssertEqual(result, expectation)
  }
```

* `expectation`을 "1"로 주어서 만약 `result`값이 nil이라면 실패하도록 변경하였습니다.

2023-03-07 02:08 UTC, hyemory commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +        XCTAssertEqual(result, expectation)
기존 의도는 1을 추가하였을 때 `peek`와 `removeFirst`의 값이 동일할 수 밖에 없다고 생각했습니다.
모두 nil인 경우를 고려했을때 `peek`와 `removeFirst`를 비교하기 보다는
`peek`의 값을 중점적으로 테스트하기 위해 아래와 같이 테스트를 변경하였습니다.

``` swift
func test_빈List에_1을_추가할_경우_peek의_값은_1이다() {
    // given
    sut.appendLast("1")
    let expectation = "1"

    // when
    let result = sut.peek

    // then
    XCTAssertEqual(result, expectation)
}
```

2023-03-07 02:11 UTC, fatherLeon commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        let node = Node(orderNumber: data)
* `LinkedList`의 내부 프로퍼티를 변경하기 때문에 `mutating`을 붙여주었습니다.

2023-03-07 02:16 UTC, hyemory commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Node.swift
> +    var orderNumber: T
`final` 키워드를 사용한 class는 더이상 상속, 재정의를 할 수 없게됩니다.
- vTable : 클래스 내부에서 어떤 메서드를 실행할 지 결정하는 테이블 (동적 디스패치 지원)

런타임에 vTable이 상속받은 메서드를 호출할 지, 오버라이딩한 메서드를 호출할 지 확인한다고 합니다.
final 키워드를 사용하면 이러한 확인 과정을 줄여줄 수 있어 성능상의 이점이 있다고 이해하였습니다.

2023-03-07 02:20 UTC, fatherLeon commented on BankManagerConsoleApp/LinkedListTests/LinkedListTests.swift
> +        XCTAssertTrue(condition)
```swift
func test_빈List에_1과_2를_추가하고_removeAll호출시_head와tail모두nil이된다() {
    // given
    sut.appendLast("1")
    sut.appendLast("2")
    
    // when
    sut.removeAll()
    
    let head = sut.head
    let tail = sut.tail
    var condition: Bool {
        head == nil && tail == nil
    }
    
    // then
    XCTAssertTrue(condition)
}
```

* `appendLast` 메소드를 통해 값을 추가하고 이후 `removeAll`을 실행하는것으로 테스트를 변경하였습니다.

2023-03-07 04:58 UTC, fatherLeon commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/Node.swift
> +    var next: Node?
### Node
* `value`의 경우 init할때만 값을 주면 되고, 외부(LinkedList)에서 값을 확인해줘야하므로, private(set)으로 접근제어자를 수정하였습니다.
* `next`의 경우 LinkedList에서 `append`를 사용함으로 값을 변경해주기 때문에 기본 접근제어자를 사용하였습니다.
* `init`의 경우 `value`만 설정하고 `next`는 `append`메소드 호출 시 설정해주므로 `value`만 인자로 받게끔 구현하였습니다.

### LinkedList
* `head`와 `tail`은 유닛테스트 시 확인하기 위하여 private(set)으로 접근제어자를 설정하였습니다.
* 이 외에 연산프로퍼티는 getter이기 때문에 따로 접근제어자를 설정하지 않고 기본접근제어자를 사용하였습니다.

### Queue
* `queue`프로퍼티의 경우 외부에서 접근을 허락할 이유도 없으며, 메소드로 `queue`내부의 LinkedList를 수정해주므로 `private`로 설정하였습니다.

2023-03-07 05:25 UTC, merged