은행창구 매니저💰 [STEP 1] Rowan, 릴라
yagom-academy/ios-bank-manager pull request #258
Opened 2023-03-06 07:43 UTC by juun97

@1Consumption
안녕하세요 올라프! 릴롼 인사드립니다 🧑🏻‍🔬🧑🏻‍🔧
이번 프로젝트간 리뷰 잘 부탁드립니다 🙏

# 고민한 점

##  접근 제어자 설정 🔒

`Linked List` 를 이용한 `Queue` 구현은 지난 프로젝트에서 진행을 했었기에 큰 어려움은 없었습니다. 마침 활동학습으로 오픈소스 라이브러리 제작에 대해 공부하기도 해서 접근제어자를 좀 더 디테일하게 설정해보려 했습니다.

### 1️⃣
```swift
struct LinkedList<T> {
    private(set) var head: Node<T>? = nil
    private(set) var tail: Node<T>? = nil
    private(set) var count: Int = 0
    //...
}
```

처음에는 LinkedList의 경우 프로퍼티들에 대한 접근이 필요하나 수정권한은 필요없기 때문에 `private(set)` 을 설정 했습니다.

### 2️⃣

```swift
struct LinkedList<T> {
    final private class Node<T> {
        var next: Node? = nil
        let data: T
        
        init(data: T) {
            self.data = data
        }
    }
}
```

구현 한 Node 타입을 외부에서는 모르게 하고 싶었기에 LinkedList 내부 `Nested Type` 으로 옮겨주었습니다.

하지만 내부로 옮겨 주면서 아래와 같은 에러가 발생 했습니다.
<img src="https://i.imgur.com/lYFVObu.png" width = 500>
</br>
     
Node type의 값을 갖는 프로퍼티의 접근 제어자는 nested type `Node` 클래스의 접근 제어자보다 높은 제어 수준을 가질 수 없었습니다.

### 3️⃣

그렇기에 기존에 `private(set)`으로 구현한 Node 타입에 대한 접근제어자를 `private` 으로 수정하고 해당 프로퍼티의 data를 리턴해주는 get only 연산프로퍼티를 추가 구현 했습니다.

```swift
struct LinkedList<T> {
    final private class Node<T> {
    //...
    }
    
    private var head: Node<T>? = nil
    private var tail: Node<T>? = nil
    private(set) var count: Int = 0
    
    var headData: T? {
        return head?.data
    }
    //...
}
```

이렇게 수정함으로써 자연스럽게 CustomerQueue도 Node에 대해 모르게 되었습니다 👀

2023-03-06 15:49 UTC, 1Consumption requested changes
고생하셨습니다. @juun97 @Kyeongjun2 

유닛 테스트를 잘 작성해주셨네요!👍 
앞으로도 테스트하는 습관을 들이고, 유지했으면 좋겠습니다.

스텝이 워낙 작아 따로 더 할 말은 없습니다.

코멘트를 참고해주세요.

2023-03-06 15:49 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/CustomerQueue.swift
> +    }
optional을 그대로 반환해도 좋겠습니다.

```suggestion
    @discardableResult
    mutating func dequeue() -> T? {
        return list.removeFirst()
    }
```

2023-03-06 15:49 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/CustomerQueue.swift
> +}
여기도 마찬가지입니다.

2023-03-06 15:49 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        if count == 0 {
count로 비교를 하지 마시고, head와 tail을 가지고 비교해보세요.

2023-03-06 15:49 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        guard isEmpty == false else { return nil }
굳이 isEmpty를 체크하지 않아도 반환값이 옵셔널이니 괜찮을듯 합니다.

2023-03-06 15:49 UTC, 1Consumption commented on BankManagerConsoleApp/UnitTest/CustomerQueueTest.swift
> +        let result = sut?.count
count가 정말 현재 필요한 기능일까요? 아니면 테스트를 위해 만든 프로퍼티일까요? 저라면 dequeue로 확인할거 같아요.

2023-03-06 15:49 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +struct LinkedList<T> {
클래스와 스트럭트를 구분지은 기준이 있을까요?

2023-03-07 01:15 UTC, Kyeongjun2 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +/* End PBXShellScriptBuildPhase section */
swiftlint는 삭제하였습니다!!

2023-03-07 01:25 UTC, juun97 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +	objectVersion = 54;
> 파일 형식의 변경 사항을 의미합니다. 

저희 프로젝트에서 로완과 저의 mac OS 버전이 달라 버전이 더 낮은 제쪽에서 테스트코드가 실행되지 않는 이슈가 있었습니다. 그 이슈를 해결하기 위해 xcode의 mac OS  deployment 를 12.0 으로 낮추면서 변경사항이 생긴것 같습니다.

2023-03-07 01:41 UTC, juun97 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        if count == 0 {
d18fdc629792ebd17dbc3f7f86878ba8bf302b3a

비교방식을 기존 count 에서 head 로 수정 했습니다

2023-03-07 01:44 UTC, juun97 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        guard isEmpty == false else { return nil }
해당 메서드에서 count 를 1 차감해주는 코드가 있습니다. 조건문을 통한 빠른 종료가 이루어지지 않는다면 해당 코드는 반드시 실행되어 count 가 0 밑으로 내려가는 일이 발생할 수 도 있습니다. 

```swift
    func removeFirst() -> T? {
        guard let node = head else { return nil }
        
        head = head?.next
        
        if head == nil {
            tail = nil
        }
        
        count -= 1
         
        return node.data
    }
```

head 가 비어있는지에 대한 검사를 한번 진행 후 로직을 이어 가는 방향으로 결정했습니다.

2023-03-07 01:45 UTC, Kyeongjun2 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +    private(set) var count: Int = 0
다음 스텝에서 사용될 것으로 예상되고 dequeue와 peek 메서드의 차이점을 테스트에서 나타낼 수 있어서 step1의 필수 요구조건은 아니지만 구현해두었습니다.

2023-03-07 01:45 UTC, Kyeongjun2 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +        if count == 0 {
head 기준으로 비교할 수 있도록 조건문 수정하였습니다

2023-03-07 01:51 UTC, juun97 commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +struct LinkedList<T> {
[공식문서](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes) 에서 `class` 를 선택할 이유가 없다면 기본적으로 `struct` 로 구현을 하라고 나와있습니다.

처음에는 굳이 클래스로 구현해야 겠다는 이유를 찾지 못해 `struct` 로 구현을 했습니다.
하지만 `LinkedList` 가 struct 로 구현되면서 요구하는 `mutating` 키워드가 상당히 많아졌고 Queue 에서도 `var` 로 List를 가지고 있기때문에 List 의 인스턴스가 변경될 수 있는 위험이 있었습니다.

위와 같은 이유로 기존 struct로 구현된 LinkedList 를 class 로 수정 하였습니다.

2023-03-07 02:04 UTC, Kyeongjun2 commented on BankManagerConsoleApp/UnitTest/CustomerQueueTest.swift
> +        let result = sut?.count
위에서 말씀드린대로 dequeue와 peek 메서드의 차이점을 테스트에서 나타낼 수 있어서 사용해도 괜찮을 것 같다고 생각합니다 🤔

2023-03-07 02:04 UTC, juun97 commented on BankManagerConsoleApp/UnitTest/CustomerQueueTest.swift
> +        let result = sut?.count
3aa54407a8f3a84d4d4ea7798e8bff3add77b567

2023-03-07 14:35 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/DataStructure/LinkedList.swift
> +    private(set) var count: Int = 0
음... 저는 예상해서 만들기 보다는 항상 기능을 추가하기 좋은 구조를 짜는게 더 좋다고 생각해요.(지금 프로젝트랑은 관련이 없긴 합니다.)
필요하다고 생각해서 만들었는데 사용되지 않을수도 있고, 필요 없다고 생각했는데 필요한 경우가 있으니까요. 
지금같은 경우는 count만을 위한 추가 코드가 조금 보여서 이부분은 약간 아쉽다고 생각했어요.

2023-03-07 14:35 UTC, merged