은행창구매니저 [STEP 1] sehong, Rhode
yagom-academy/ios-bank-manager pull request #259
Opened 2023-03-06 07:43 UTC by Rhode-park

@junbangg 
안녕하세요 알라딘🪔! sehong, Rhode입니다.
배웠으면 하는 부분, 알려주시고 싶은 부분 다양한 조언 언제든지 감사하게 듣겠습니다. 부족하지만 열심히 하는 저희에게 많은 꿀팁 부탁드려요!남은 기간 잘 부탁드립니다.🙇🏻‍♀️

# 고민했던 부분

# 조언을 받고 싶은 부분
## 1. testable import를 했는데도 모듈을 찾을 수 없는 문제

 ![](https://i.imgur.com/q7qe0VL.png)
사진과 같은 에러와 함께 `Undefined symbol: _$s21BankManagerConsoleApp0A5QueueV7dequeuexSgyF` 경고가 계속 발생하였고, 해결 방법으로 testable을 사용하지 않고 target을 지정하여서 해결 했는데 이런 문제가 발생한 이유가 뭔지 해결 방법에 대한 키워드 얻고 싶습니다ㅠㅠ  

## 2. linkedList로 queue를 구현했을 때 다른 기능 없이 test를 진행하는 방법
`enqueue`, `dequeue` 등을 사용하지 않으면서 `sut`를 구현하고, `peek`을 사용하지 않으면서 `sut`의 상태를 알 수 있는 방법을 알고 싶습니다.

계산기에서도 test를 진행하였는데요. 그 때는 배열이 있는 queue를 만들거나 doubleStack이 있는 queue를 만들어서 `init`을 사용하여 아래와 같이 초기 상태와 결과 상태를 손쉽게 설정해놓을 수 있었습니다:

```swift
func test_dequeue호출시_큐가비지않았을경우_첫번째요소를빼서반환한다() {
    //given
    sut = .init([1.0, 2.0, 3.0])
    let expectedResult = 1.0
    let expectedData = [3.0, 2.0]
    
    //when
    let result = sut.dequeue()
    
    //then
    XCTAssertEqual(expectedResult, result)
    XCTAssertEqual(expectedData, sut.dequeueStack)
    
}
```

그런데, 현재 저희는 linkedList로 queue를 구현하였기 때문에 그런 부분에서 어려움을 겪었습니다. 그래서 test를 진행하면서 `enqueue` 메서드나 `peek`프로퍼티 등을 사용하여 test를 진행하였습니다:

```swift
func test_peek호출시_값을하나넣으면_하나를반환한다() {
    //given
    sut = .init()
    sut.enqueue(1.0)
    
    //when
    let result = sut.peek
    let expectedData = 1.0
    
    //then
    XCTAssertEqual(result, expectedData)
}
```

그런데, 이렇게 테스트를 하게 되면 `peek`의 기능만을 test하는 목적이 퇴색된다고 생각합니다. 그래서 순수하게 `peek`만을 test하기 위해서 `sut`을 잘 설정하고 싶습니다. 그런데, 저희끼리는 그 방법을 찾지 못했습니다. 어떤 방법을 사용해야 순수하게 `peek`만을 test할 수 있을까요? 알라딘의 조언을 얻고 싶습니다.

2023-03-06 16:50 UTC, 1Consumption requested changes
고생하셨습니다.

유닛테스트를 잘 작성해주셨네요.
그런데 아직 커밋 나누기가 덜 익숙한듯 합니다.
정말 6개의 커밋으로 이번 스텝을 끝낼 수 있을까요? 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/37682858/223175312-07de12b5-b80b-4a05-8a66-51b8daefe4e0.png">

저는 커밋이 너무 크다고 생각합니다. 커밋은 기능 단위로 나뉘어야하며, 하나의 역할만 해야합니다. 그런데 지금은 전혀 그러고 있지 않습니다.
다음 스텝부터는 커밋을 역할별로 쪼개는데 집중해보세요.

아래는 고민하신점에 대한 제 코멘트입니다.

1. testable import를 했는데도 모듈을 찾을 수 없는 문제
https://developer.apple.com/forums/thread/52211 를 참고해보세요. GUI 프레임워크, 즉 코코아터치 프레임워크를 기반으로 하는 경우에만 테스트 번들이 작동하기 때문입니다.
> Right. That’s because the machinery to load your test bundle within a process only works if the process is based on a GUI framework (like Cocoa or Cocoa Touch). A command line tool typically does not use a GUI framework and thus the test machinery is unable to load your bundle into that tool. 

2. linkedList로 queue를 구현했을 때 다른 기능 없이 test를 진행하는 방법
저는 지금도 괜찮다고 생각합니다. 정말 다른 메소드를 통하지 않고 peak을 테스트하고 싶다면, head를 외부에서 주입해줘도 될 듯 합니다.

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +	objectVersion = 54;
이 변경사항은 뭘 의미하나요?

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +		3673979F29B59E48007AF8FA /* .swiftlint.yml */ = {isa = PBXFileReference; lastKnownFileType = text.yaml; path = .swiftlint.yml; sourceTree = "<group>"; };
프로젝트 제약사항에 `외부 라이브러리를 사용하지 않습니다.`라는 사항이 있습니다. 외부 라이브러리 사용을 자제해주세요.
다음부터는 프로젝트 제약사항을 꼼꼼하게 읽어주세요.

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankLinkedList.swift
> +    }
이 메소드들을 굳이 나눈 이유가 있나요? 이유를 잘 모르겠습니다.

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankLinkedList.swift
> +
불필요한 공백 같습니다.

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankLinkedList.swift
> +    }
pop이라는 메소드 이름은 일반적으로 stack에 사용되는 이름이니 다른 이름을 고려해보세요.

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +}
Node를 클래스로 만든 이유가 있을까요? 다른 객체들은 스트럭트여서요.

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankQueue.swift
> +    }
굳이 이니셜라이저로 `LinkedList`타입을 넣어준 이유가 있을까요?

2023-03-06 16:50 UTC, 1Consumption commented on BankManagerConsoleApp/BankQueueTest/BankQueueTest.swift
> +    var sut: BankQueue<Double>!
외부에서 몰라도 되는 프로퍼티 같습니다.

2023-03-06 16:52 UTC, 1Consumption requested changes

2023-03-07 01:08 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankLinkedList.swift
> +    }
4f81fd07b77079ea745ccd06cb8c09f952eca907

해당 부분 push를 없애고 append하나로 합쳐주었습니다. 감사합니다

2023-03-07 01:18 UTC, Rhode-park commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankLinkedList.swift
> +    }
`pop`이라는 이름이 부적절하다고 하셔서 구글링을 해봤습니다. 그리고 java에서는 어떻게 사용하고 있는지에 대한 블로그들을 발견했습니다. [Oracle Help Center - Class LinkedList<E>](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html)를 참고해보았습니다. java에서는 linkedlist의 메서드로 `pop`이라는 이름을 사용하는 것 같습니다.
![](https://i.imgur.com/BABn9cU.png)
*removes and returns the first element of this list*라고 나와있습니다. 그래서 `pop`이라는 이름이 적절하다고 생각했습니다. 앞에 stack에 대한 부분이 나와있긴 한데, `pop`은 linkedList로 stack을 구현할 때 사용할 법한 이름인 것일까요? 어떤 이름이 적절하다고 여겨질 수 있을까요? `dequeue`라는 이름은 아직 queue를 적용하기 전이라서 사용하기 조심스럽습니다. `shift`정도는 혹시 괜찮을까요? 혹시 네이밍에 대해서 추천해주실 수 있을까요 올라프?

2023-03-07 01:31 UTC, Rhode-park commented on BankManagerConsoleApp/BankQueueTest/BankQueueTest.swift
> +    var sut: BankQueue<Double>!
BankQueueTest의 var sut은 외부에서 몰라도 되는 프로퍼티일 것 같아서 `private`붙여 은닉화 진행해주었습니다. 뿐만 아니라 test 메서드들에 대해서도 은닉화 진행하였습니다.

2023-03-07 01:35 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankQueue.swift
> +    }
0016500ddfc24d54b98324d9c3ba16817a64377d

해당 부분 필요없는 코드로 확인하고 삭제하였습니다.

2023-03-07 01:37 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankNode.swift
> +}
LinkedList내에서 참조타입으로 사용되기 때문에 class로 구현하게 되었습니다.

2023-03-07 02:04 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +		3673979F29B59E48007AF8FA /* .swiftlint.yml */ = {isa = PBXFileReference; lastKnownFileType = text.yaml; path = .swiftlint.yml; sourceTree = "<group>"; };
2d658533f68efda79f34269080790bd5d4ce83e4

활동학습 시간에 이번에 진행하는 프로젝트에 swiftLint를 적용해보았고, 그것을 그대로 프로젝트에 적용시켜서 진행하는 줄 알았습니다!
저희의 착오로 swiftLint를 삭제하였습니다.

2023-03-07 02:04 UTC, Rhode-park commented on BankManagerConsoleApp/BankQueueTest/BankQueueTest.swift
> +    var sut: BankQueue<Double>!
[e47e892](https://github.com/yagom-academy/ios-bank-manager/pull/259/commits/e47e8925106308d5f619a98104990c1da3eab11f)

test 메서드들에 대해서는 은닉화가 불필요하다는 것을 깨달아서 제거했습니다..ㅎㅎ..ㅠㅠ

2023-03-07 02:09 UTC, Rhode-park commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +				D01A1B2129B5B3DC0028B601 /* BankNode.swift in Sources */,
[`6e47b12`](https://github.com/yagom-academy/ios-bank-manager/pull/259/commits/6e47b12b5417202a3fe7d49bd2a62573a5f70dd6)

불필요한 `Bank` prefix들을 삭제하였습니다.

2023-03-07 02:14 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +	objectVersion = 54;
해당 변경 사항은 정확한 답변을 찾지 못했으나 
swiftLint.yml 파일이 추가되었을때 objectVersion이 54로 변경되고 
해당 파일을 삭제했더니 50으로 다시 돌아가는걸 확인했습니다..
저희가 확인하고 이해한 부분이 맞는지 답변 부탁드립니다..!

2023-03-07 14:38 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp.xcodeproj/project.pbxproj
> +	objectVersion = 54;
엑스코드 버전을 의미하는거로 알고 있는데, 이 질문을 한 취지는 `본인들이 어떤걸 커밋하는지 알고 커밋하면 좋겠다`입니다. 모두 스테이지에 올리지말고, 어떤 부분이 변경되는지 확인하면서 커밋하는 습관을 들이는게 중요해요.

2023-03-07 14:46 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/BankQueue/BankLinkedList.swift
> +    }
올려주신 사진에 그대로 나와있는데, `Stack`의 요소를 `pop`한다고 나와있네요. 코멘트에 적어주신대로 `Queue`를 적용하기 전이라`dequeue`가 조심스럽다면 `pop`도 조심스러워야 할 거 같은데요?
그리고 우리는 `Swift`로 개발을 하니 `Java` 컨벤션을 따라야하나 싶습니다. 어느정도 참고하는건 좋아요. 저라면 `Array`의 메소드 이름인 `removeFirst`를 가져올거같아요.

2023-03-07 14:48 UTC, 1Consumption commented on BankManagerConsoleApp/BankQueueTest/BankQueueTest.swift
> +    var sut: BankQueue<Double>!
commit revert를 한번 알아보세요. 똑같은 작업을 반복하지 않아도 됩니다.

2023-03-07 14:53 UTC, merged