은행창구매니저 [STEP 1] Goat, Andrew
yagom-academy/ios-bank-manager pull request #260
Opened 2023-03-06 08:15 UTC by Andrew-0411

@lina0322 안녕하세요 엘림! STEP1 PR 보내드립니다.

## 고민했던점 && 조언을 얻고 싶은 점

### Linked-list 사용시 단방향 연결리스트, 양방향 연결리스트 중에 고민

- Linked-list에 단방향, 양방향 중에서 메모리 절약을 위해 단방향 Linked-list를 사용하였습니다.
- 은행창구 프로젝트의 사이즈나 디테일한 구현정도를 알지못해서 일단 단방향리스트만으로 충분할거같다는 생각이 들어서 단방향 리스트로 구현했습니다.

2023-03-06 09:11 UTC, lina0322 requested changes
수고하셨습니다~ 상당히 빨리 작업하셨네요ㅎㅎ
생각할 수 있는 부분들이 있어서 코멘트 남겼습니다.
이번 프로젝트 화이팅합시다~

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        init(data: T?, next: Node? = nil) {
init을 별도로 생성할 필요가 있을까요? 추가로 data가 nil인 노드가 필요한지도 궁금합니다~

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    mutating func enqueue(data: T?) {
mutating은 무엇인가요??

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        }
초반에 return이 되는거라면 guard가 낫지 않을까요. swift 공식문서에서 guard는 어떤 타이틀을 가지고있나요?

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    @discardableResult
discardableResult을 사용하셨네요!👍
Swift Attributes는 또 뭐가있을까요?

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    }
head만 nil로 바꿔도 전부 사라지나요?ㅎㅎ 그렇다면 메모리는 어떻게 동작되나요?👀

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    }
이 함수를 enqueue나 dequeue에서 활용할 수 있지 않을까요??

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        if head == nil { return nil }
어떤 기준으로 줄바꿈을 하나요?

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    }
return을 쓰지 않으면 어떻게되죠??

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
> +    var sut: BankQueue<Double>!
sut을 사용하셨네요!👍 Test Double은 어떤것이 있고 sut을 선택한 이유가 궁금합니다~

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
> +        XCTAssertTrue(sut.isEmpty())
XCTAssertFalse를 사용하는 테스트도 만들어보면 어떨까요??

2023-03-06 09:11 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
> +        XCTAssertEqual(input, result)
enqueue 테스트는 안보이네용? 어짜피 만들거라면 다 만드는게 좋지않을까요ㅎㅎ

2023-03-07 01:57 UTC, Goatt8 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    final class Node<T> {
Class만 사용할 수 있는 기능이나 특징인 상속을 사용해야 하는경우, 참조타입의 값을 사용해야 하는 경우, 소멸자를 사용해야 하는 경우 등이 아니라면 Swift는 Struct를 사용하는것을 권장한다고 Apple Developer 문서에서 공부했기 때문에 BankQueue는 struct로 사용하였고 Node는 참조타입의 값이 필요하기 때문에 Class로 구현하였습니다.

2023-03-07 02:04 UTC, Goatt8 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        init(data: T?, next: Node? = nil) {
클래스타입은 init을 하지않으면 안된다고 알고 있습니다.
추가로 next = nil인 노드가 필요하냐고 여쭤본게맞을까요? (오타)
연결리스트다보니 다음값을 가리키는 next는 뒤에 올 값이없다면,즉 초기값이라면 nil로 설정하는게 맞다고 생각합니다

2023-03-07 02:08 UTC, Goatt8 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        if head == nil { return nil }
return 문이 짧을 떄는 보통 하나의 문장으로 컨벤션을 지키는 편입니다!

2023-03-07 02:12 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        }
- Early Exit(이른 탈출) 특정 조건을 만족하지 않으면 방어 코드로 사용하여 하단 로직을 사용할지 말지를 결정한다고 나와있습니다 
[Swift guard문](https://jusung.gitbook.io/the-swift-language-guide/language-guide/05-control-flow)
enqueue함수뿐만아니라 dequeue에도 guard문이 변경해야 될 부분이 있어서 변경하였습니다

2023-03-07 02:13 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    @discardableResult
- 가장 많이 사용했던건 button의 event를 주기 위한 @objc가 있습니다.
    **Swift가 Objective-C 코드에 접근할 수 있도록 해줍니다**
- AppDelegate에 Entry Point(시작점) 역할을 하는 @main도 있습니다.
- StoryBoard와의 연결고리 역할을 하는 @IBAction, @IBOutlet도 있습니다.
- Swift버전, OS버전, 특정플랫폼(iOS, macOS, watchOS, tvOS)에 제약을 걸때 사용하는 @available

2023-03-07 02:46 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    }
```swift
guard isEmpty() == false else {
            head = Node(data: data)
            return
}

guard isEmpty() == false else { return nil }
```
isEmpty로 변경하였습니다

2023-03-07 02:51 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    }
return을 사용하지 않아도 실행하는데 문제가 없지만 반환타입을 명시해주었다는건 반환값이 있기때문에 
return을 사용해야 된다고 생각이 들어서 return문을 사용하였습니다.

2023-03-07 03:05 UTC, Goatt8 commented on BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
> +    var sut: BankQueue<Double>!
Unit Test를 작성하는 동안 production에 사용될 객체와 동일하게 동작하지만 단순화된 버전이 필요한 경우가 있다. 우리는 이런 종류의 객체들을 Test Doubles 이라고 한다

* Dummy: 아무것도 하지 않고 자리만 채울 때
* Fake: 동작하는 구현을 가지고있지만 실제프로덕션에는 적합하지않은 객체, 불필요한 부분 제거됨
* Stub: 테스트에서 호출된 요청에 대해 미리 준비해둔 가짜결과제공
* spy : stub의 역할을 가지면서 호출된 내용에 대해 약간의 정보를 기록
* Mock: 호출에 대한 기대를 명세하고, 해당내용에 따라 동작하도록 프로그래밍된 객체

- Test 용어 중에서 sut는 (System Under Test) 라는 약자를 가지고 있다고 들어서 sut를 사용하였습니다.

2023-03-07 03:10 UTC, Goatt8 commented on BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
> +        XCTAssertTrue(sut.isEmpty())
isEmpty() 매서드에 관련해서 XCTAssertFalse testcase도 작성해봤습니다!

2023-03-07 03:12 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
> +        XCTAssertEqual(input, result)
테스트 파일에 24번째줄에 보시면
test_enqueue함수호출로_값을넣으면_값이삽입되는지확인하는함수()를 작성하였었는데 다른 테스트가 필요할까요?

2023-03-07 03:23 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        var next: Node?
- private var 로 선언후 내부함수로 변경하라는 말씀이 맞으실까여?
- 아직 구체적인 내부함수를 외부에서 변경할일이 없는거 같아서 내부함수를 만들지는 않았습니다
- 제네릭 타입은 어떤 타입에도 유연하게 대응해야 할 때 사용합니다

2023-03-08 09:20 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        var next: Node?
변경할 일이 없다면 let으로 선언하면 될거같은데요??👀

2023-03-08 09:21 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        init(data: T?, next: Node? = nil) {
아하 struct로 제가 착각했네요~
오타 아닙니다. data = nil 이 필요한지 여쭤본거 맞습니다. 
예를 들어 은행에서 대기하는 큐를 만들때, 대기 번호가 없거나 대기하는 사람이 없는 빈값의 노드가 필요한지에 대한 의문이었습니다~

2023-03-08 09:21 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    mutating func enqueue(data: T?) {
mutating을 사용하면 어떤식으로 동작할까요?? 왜 값타입은 프로퍼티의 값을 수정할 수 없나요??

2023-03-08 09:22 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    }
`않을까요` 보다는 좀 더 확신을 가지고 말씀해주시면 좋겠네요! 
왜 그렇게 생각하는지 이유를 더 자세히 설명해도 좋을거같아요~ㅎㅎ

2023-03-08 09:24 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIAppTests/BankManagerUIAppTests.swift
> +    var sut: BankQueue<Double>!
어디서 복붙하시나요??ㅋㅋㅋ 말투가 왜 이랬다저랬다 하나요. 
복붙해도 상관없지만! 자신의 언어를 사용해서 작성해보시면 머리에 좀 더 남을 것 같네요~

2023-03-08 09:31 UTC, lina0322 reviewed
간단하게 추가 코멘트 남겼습니당! 

이번 스텝에서 답변주셔도 되고 
원하시면 머지해드릴테니 다음 스텝에서 하셔도 됩니댱!!

2023-03-08 14:07 UTC, merged

2023-03-09 05:29 UTC, Goatt8 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        var next: Node?
맞네요 생각해보니 data는 변경될일없고 다음에 올 값인 next만 바뀌는게 연결리스트의 구조인거같습니다
따라서 아래와같이 수정했습니다!
```swift
let data: T?
```

2023-03-09 05:51 UTC, Goatt8 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +        init(data: T?, next: Node? = nil) {
`data = nil` 구문이 필요한지 궁금하다고하셨는데, 그렇다면 queue에 아무 데이터가 없다는 뜻이고
그상황에서는 queue를 enqueue하거나 dequeue할 수없게 이미 저희가 옵셔널 처리를 해주었었네요
```swfit
guard isEmpty() == false else { return }
```
`let data: T`로 수정했습니다

2023-03-09 06:12 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    mutating func enqueue(data: T?) {
- Apple Developer 문서에서 Method의 `Modifying Value Types from Within Instance Methods` 주제에서 mutating 원리를 알아봤습니다.
* 값 타입인 struct 의 경우, stack 영역에 실제 데이터의 복사본이 저장됩니다.선언한 인스턴스에는 실제값의 복사본이 저장되있는 것입니다
* -> 따라서 인스턴스프로퍼티(원본값의 복사본)를 변경한다고한들 원본값은 변경되지않습니다
* -> mutating 키워드 사용시 **원본구조체의 인스턴스를 변경된 인스턴스의 값이 대체합니다**

2023-03-09 06:23 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/BankQueue.swift
> +    }
Struct와는 달리 원본의 주소값을 참조하는 타입인 Class를 사용했기 때문에 Node Class를 할당한 head에게 nil값을 주면, `var head: Node<T>` 선언때 reference count가 +1 되었던것이 ARC로 인해서 reference count가(-1) 0이 되면서 Node Class가 메모리에서 해제된다고 생각합니다