은행 창구 매니저 [STEP1] 리지, 무리
yagom-academy/ios-bank-manager pull request #263
Opened 2023-03-06 11:13 UTC by parkmuri

# 은행창구 매니저
@uuu1101
안녕하세요 태태! 
이번 프로젝트 리뷰이 리지, 무리입니다! 이번 프로젝트동안 잘부탁드려요😊 !
그럼 Step1 PR 보내며 코멘트 기다리고 있겠습니다!

---

## 고민했던 부분

### 1️⃣ LinkedList clear 구현 
- clear 의 기능은 enqueue된 값을 모두 삭제하는 것이라 생각하였습니다. 처음 생각한 점은 값을 하나씩 삭제를 해줘야하나? 고민하였는데, 연결리스트의 특성상 노드가 다음 값의 주소값과 연결되어 있으므로 head와 tail을 nil로 변환하면 가르키는 주소값이 사라지게 되고 결국 swift의 ARC가 자동으로 메모리를 해제한다는 점을 고려하여 코드를 구현하게 되었습니다.

### 2️⃣ build 실행 시 scheme 관련 이슈
- consolApp으로 옮겨 실행하던 중 build 실행하면 scheme 관련 문제가 생겨 build가 실행되지 않는 문제가 있었습니다. edit scheme으로 들어가서 Run을 확인해보니 Executable이 none으로 되어있어 실행되지 않았던 것을 알게되었습니다. 그래서 BankManagerConsoleApp으로 설정을 변경하고 build를 실행하니 제대로 작동하였습니다.

---

## 조언을 얻고싶은 부분

### 1️⃣ BankMangerUIApp vs BankMangerConsoleApp의 목적
- 프로젝트를 시작하며 App이 두개가 존재하는것을 확인하고 어디에 코드를 구현해야할지 고민이 되었습니다. ConsoleApp의 의미를 정확하게 파악하지 못해 일단 익숙한(최근에 했던) UIApp에 구현을 해보는쪽으로 의견이 좁혀졌습니다.
코드 작성을 끝마치고 ConsoleApp을 살펴보았는데 캠프 초반에 만들던 command line을 사용하는 프로젝트였고, UI를 다루지 않고있어서 작성한 Console에 옮기는게 맞지않을까?하는 고민을 하다 코드를 이동시켜보았습니다.
- 하지만 ConsoleApp과 UIApp이 나뉜 이유나 목적에 대해 파악하기가 어려운것같습니다🥲 UI와 기능적인 코드를 분리하려는 이유일까요? 
- 또 커밋 기록또한 저희의 과정이라고생각하여 삭제하지않고 남겼는데 이런 상황이 생긴다면 태태는 어떻게 하실지도 궁금합니다!

2023-03-07 10:35 UTC, uuu1101 requested changes
안녕하세요 리지 무리 ! @yijiye @parkmuri  
이번 프로젝트 동안 잘 부탁드립니다.

유닛 테스트를 잘 작성해주셨네요 ! 👍

몇가지 코멘트 남겨두었습니다. 확인 해주세요 !

1️⃣ BankMangerUIApp vs BankMangerConsoleApp의 목적
---
ConsoleApp과 UIApp이 나뉜 이유나 목적에 대해 파악하기가 어려운 것 같습니다
🥲 UI와 기능적인 코드를 분리하려는 이유일까요?

> UI와 기능적인 코드를 분리하는 목적 보다는 앱의 목적이 어디에 있냐로 나뉘는 것 같습니다.
UI App 도 기능적인 부분의 코드와 UI적인 부분의 코드를 분리하여 관리하기 때문이죠.
Console App 같은 경우는 UI가 필요하지 않고, ComandLine을 통해서 앱을 실행하고 UI App 같은 경우에는 UI가 필요한 경우 UI App으로 작업을 진행하고 있습니다. 
아마 이런 맥락으로 말씀하신거라면 제 생각도 같습니다! :) 좋은 고민점이네요.

또 커밋 기록또한 저희의 과정이라고생각하여 삭제하지않고 남겼는데 이런 상황이 생긴다면 태태는 어떻게 하실지도 궁금합니다!

> 커밋 기록은 작업했던 코드를 추후 보거나 어떤 문제가 있었는지 확인하는데에도 아주 중요한 요소라고 생각합니다. 따라서 여러분들의 과정이기 때문에 삭제하지 않고 남겨두는 것이 좋을 것 같습니다. 
저의 경우에도 이러한 상황이 있다면 기존 브랜치나 커밋들을 삭제하지 않고 남겨둘 것 같습니다.
커밋 내역이 지저분해지거나 하는 것은 git이 제공하는 기능들로 해결가능 합니다 :)

STEP1 진행하시느라고 고생하셨습니다 👍

2023-03-07 10:35 UTC, uuu1101 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +struct LinkedList<T> {
`struct` 와 `class` 선정 기준이 궁금합니다 :)

2023-03-07 10:35 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Queue.swift
> +struct Queue<T> {
`T`로 작성하시고 있는 제네릭에 대해서 설명해 주실 수 있을까요? 👀

2023-03-07 10:35 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Queue.swift
> +    mutating func enqueue(_ data: T) {
`mutating` 키워드는 어떨때 사용하나요?

2023-03-07 10:35 UTC, uuu1101 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +        if isEmpty {
코드 초반에 return (early Exit)을 한다면 guard을 사용해 보시는 건 어떨까요? 
[공식문서 Early Exit](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/)을 한번 읽어보셔도 좋을 것 같습니다.

2023-03-07 10:35 UTC, uuu1101 commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +    var sut: Queue<String>!
sut을 사용하셨네요 👍, sut은 무엇이며, `Test Double`은 어떤 것들이 있을까요?

2023-03-07 11:34 UTC, parkmuri commented on BankManagerConsoleApp/.swiftlint.yml
> +- trailing_newline
- 외부 라이브러리 삭제하며 함께 삭제해주었습니다!

a083ffe0b260d1d856796b79f7d5d8fcdd31a7f0

2023-03-07 11:42 UTC, yijiye commented on BankManagerConsoleApp/Model/LinkedList.swift
> +struct LinkedList<T> {
swift 에서는 기본값으로 struct 사용을 권장하고 있으므로 꼭 class로 구현해야하는 경우가 아니면 struct을 사용하였습니다! 이 프로젝트에서 연결리스트로 큐를 구현할 때, 상속이 필요하거나 인스턴스는 바뀌지 않고 내부 프로퍼티만 변경하는 등 class를 선택해야하는 이유가 없어 struct을 사용하였습니다 😀

2023-03-07 12:08 UTC, parkmuri commented on BankManagerConsoleApp/Model/Queue.swift
> +struct Queue<T> {
- 제네릭은 타입에 의존하지않는 범용적인 코드를 작성할때 사용합니다. 어떠한 타입이던 유연하게 대응 가능하며 코드의 중복을 줄일 수 있다는 장점 등이 있습니다! 
제네릭 대신 타입을 정하고 사용하면 `Any`가 아닌 이상 같은 타입으로만 사용해야 하며, 범용성이 떨어지는 코드를 작성하게 될것같습니다. 대신 `Any`를 사용하게된다면 다른 타입의 값을 `Any`타입 변수에 넣어 사용해야하는 번거로움이 있습니다. 
제네릭을 사용한다면 제네릭의 실제 타입은 호출되는 순간에 정해지며, 어떠한 타입이던 받아서 사용할 수 있게됩니다!
- 플레이스홀더로 `T`를 사용한 것은 가장 널리 쓰이는 것이라고 생각되어 사용했습니다..!

2023-03-07 12:15 UTC, yijiye commented on BankManagerConsoleApp/QueueTest/QueueTest.swift
> +    var sut: Queue<String>!
sut는 System Under Test의 약자로 test할 타입을 명시해주는 것이라 생각했습니다.  여기서는 Queue의 Unit Test를 진행하여 sut를 Queue<String> 으로 명시하였습니다! 
Test Double을 사용해 본적은 없지만.. 아래와 같이 5개가 있다고 배웠습니다 😅 

 Dummy - 기능이 구현되어 있지 않으며 객체를 전달하기 위한 목적으로 사용
 Stub -  Dummy가 실제로 동작하는 것 처럼 만들어 실제 코드를 대신해서 동작해주는 객체
 Fake - stub 보다 구체적이지 않지만 코드의 동작을 단순화하여 구현한 객체
 Spy - stub의 역할을 가지면서 일부 정보를 기록하는 객체
 Mock - 실제 객체와 가장 비슷하게 구현된 수준의 객체
 
 Test Double은 테스트를 진행하기 어려운 경우에 대신하여 테스트를 진행할 때 사용할 수 있을 것 같습니다!

2023-03-07 12:30 UTC, parkmuri commented on BankManagerConsoleApp/Model/LinkedList.swift
> +        if isEmpty {
- 공식문서의 Early Exit 참고하여 guard로 수정하였습니다. 조금 더 가독성이 좋아진 것 같아요!

7d6aff526b8484894365c07efae3541fd9a748f9

2023-03-08 05:58 UTC, uuu1101 commented
고생하셨습니다 :) 다음 STEP 진행해주시면 될 것 같아요 ! 👏

2023-03-08 05:58 UTC, merged