은행창구 매니저 [STEP2] kaki, songjun
yagom-academy/ios-bank-manager pull request #265
Opened 2023-03-07 08:46 UTC by kak1x

# 은행창구 매니저 [STEP2] kaki, songjun
@AppleCEO
안녕하세요 도미닉! Step2 PR입니다! 이번 리뷰도 잘부탁드립니다!

## 구현 내용
### Step2 요구사항 구현
- Step2 요구사항에 맞게 구현을 완료하였습니다.
- 메뉴에 없는 숫자를 눌렀을 시 에러를 처리해주는 과정을 추가해줄지 고민하였는데, 요구사항에 없는 내용이라 따로 구현하지 않았습니다.
- 고객이 총 몇명인지 확인할 수 있게 Queue 내부에 `size` 프로퍼티를 추가해주었습니다.

## 조언이 필요한 점
### BankManager 내부에서의 함수 분리 
- BankManager 구조체 내부에 `setupWaitingQueueAndClientNumber`, `startBusiness`메서드가 있습니다.
- 이 메서드 내부에는 여러기능들이 존재합니다. 크게보면 업무시작과 함께 기능하는 작동들이라 한 메서드에 정의해주었는데, 이 기능들을 세분화할 경우 main에서 코드를 진행시킬 때 여러 함수들을 실행시켜야 해서 고민이 됩니다.
- 기준을 크게 잡아 한 번에 실행시킨 지금의 방식이 좋을지, 아니면 조금 더 세분화하여 여러개의 함수를 실행시키는 방식이 좋을지 조언 주시면 감사하겠습니다.
```swift
mutating func setupWaitingQueueAndClientNumber() {
    for number in 1...Int.random(in: 10...30) {
        waitingQueue.enqueue("\(number)번 고객")
    }
    
    clientNumber = waitingQueue.size
}

mutating func startBusiness() {
        while !waitingQueue.isEmpty {
            guard let client = waitingQueue.dequeue() else { return }
            print("\(client) 업무 시작")
            Thread.sleep(forTimeInterval: 0.7)
            print("\(client) 업무 완료")
        }
        
        let businessHours = Double(clientNumber) * 0.7
        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(clientNumber)명이며, 총 엄무시간은 \(String(format: "%.2f", businessHours))초입니다.")
    }
```

2023-03-08 12:55 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@kak1x , @kimseongj 이번 스텝도 빠르게 구현하셨네요.
고생하셨습니다!

# 질문 답변
1. 다른 인풋들에 대한 처리를 해줄까 고민하셨다고 하셨는데 유저가 어떻게 입력을 할지 예측하기는 힘듭니다. 간단하게 1,2. 가 아닌 숫자가 들어오면 다시 입력해달라고 추가 미션으로 해보실 수 있을까요?
2. BankManager 내부에서의 함수 분리 -> 함수는 하나의 동작만 해야합니다. 여러 동작을 하고 있다고 생각하시면 함수를 나누는 것이 좋습니다. 여러 개를 호출해주는 것이 부담스러우면 외부에서는 startBusiness 메소드만 호출하고 이 메소드 안에서 여러 메소드를 호출해주면 어떨까요?

2023-03-08 12:55 UTC, AppleCEO commented on BankManager.swift
> +        for number in 1...Int.random(in: 10...30) {
random 함수를 사용해보셨군요! 🔢 
1...Int.random(in: 10...30) 이렇게 작성하면 저는 약간 헷갈리네요.
위에서 상수에 Int.random 을 넣어주고 1...상수로 작성해보면 어떨까요?

2023-03-08 12:55 UTC, AppleCEO commented on BankManager.swift
> +    private var clientNumber = 0
고객 숫자라고 해석은 되는데요.
Number 는 이 고객의 번호인지, 고객이 몇 명인지 명확하게 의미가 드러나지는 않네요.
더 명확한 이름으로 개선해 볼 수 있을까요?

2023-03-08 12:55 UTC, AppleCEO commented on BankManager.swift
> +//  Created by kaki, songjun.
작성자를 바꿔준 것 아주 좋습니다! 💯

2023-03-08 12:55 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> -import Foundation
오호... 이 임폴트 코드를 제거한 이유가 있을까요?

2023-03-08 12:55 UTC, AppleCEO commented on BankManager.swift
> +    mutating func startBusiness() {
비지니스를 시작한다는 번역이 되는데요.
코드 내용은 비지니스가 진행되는 함수로 보이네요.
더 적절한 메소드명이 있을까요?

2023-03-08 12:55 UTC, AppleCEO commented on BankManagerConsoleApp/QueueTests/QueueTests.swift
> +    func test_peek했을_경우_dequeue될_데이터를_반환한다() {
디테일하게 맞춤법을 맞춰준 것 좋네요~ 🥇

2023-03-08 12:55 UTC, AppleCEO commented on Queue.swift
> +        while (current != nil) {
스위프트에서는 () 를 사용하지 않는 것이 권고됩니다.
빼주면 좋겠네요.

2023-03-09 06:46 UTC, kak1x commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> -import Foundation
Foundation Framework의 기능을 사용하지 않으므로 불필요하다 생각되어 제거해주었습니다.

2023-03-09 06:46 UTC, kimseongj commented on BankManager.swift
> +        for number in 1...Int.random(in: 10...30) {
확인했습니다! 위와 같은 부분은 확실히 가독성 측면에서 어려움을 겪을거 같군요. 수정했습니다!

2023-03-09 06:47 UTC, kak1x commented on BankManager.swift
> +    mutating func startBusiness() {
비지니스를 진행한다, 처리한다 라는 의미인 processBusiness로 함수명을 변경해주었습니다.

2023-03-09 06:47 UTC, kimseongj commented on BankManager.swift
> +    private var clientNumber = 0
변수명이 무엇을 의미하는지 더욱 명확하게 알 수 있게 `numberOfClient`로 변수명을 수정했습니다!
c3486726b5304f1c149b5e27b9f710cc2732181f

2023-03-09 06:47 UTC, kak1x commented on Queue.swift
> +        while (current != nil) {
확인 후 제거해주었습니다!

2023-03-09 06:50 UTC, kimseongj commented
질문 답변
1. 다른 인풋들에 대한 처리를 해줄까 고민하셨다고 하셨는데 유저가 어떻게 입력을 할지 예측하기는 힘듭니다. 간단하게 1,2. 가 아닌 숫자가 들어오면 다시 입력해달라고 추가 미션으로 해보실 수 있을까요?
-> 다른 번호가 입력될 시 "잘못된 입력입니다. 다시 입력해주세요"가 나오도록 수정했습니다!

2. BankManager 내부에서의 함수 분리 -> 함수는 하나의 동작만 해야합니다. 여러 동작을 하고 있다고 생각하시면 함수를 나누는 것이 좋습니다. 여러 개를 호출해주는 것이 부담스러우면 외부에서는 startBusiness 메소드만 호출하고 이 메소드 안에서 여러 메소드를 호출해주면 어떨까요?
-> `processBusiness`에서 업무가 끝난것을 알리는 기능을 `presentBusinessResult`로 나누어 수정하였습니다....

2023-03-09 08:34 UTC, merged