은행창구 매니저 [STEP 2] Goat, Andrew
yagom-academy/ios-bank-manager pull request #272
Opened 2023-03-09 06:35 UTC by Andrew-0411

@lina0322 안녕하세요 엘림! 은행창구 매니저 STEP2 PR 보내드립니다!
step1에서 추가 코멘트 주신 부분들은 step2에서 반영하고 코멘트 다시 달아두었습니다ㅎ
이번 리뷰도 잘 부탁드리겠습니다

## 고민했던점 && 조언을 얻고 싶은 점

### 값타입 사용시 Escaping closure captures mutating 'self' parameter 에러
-> **struct -> class 변경으로 해결**

* BankManager는 처음에 struct로 구현했는데, 클로저에서 self키워드 사용시 위와같은에러 **Escaping closure captures mutating 'self' parameter**라는 에러가 나왔습니다
* 찾아보니 DispatchQueue의 클로저 안에 구현된 self가 struct구조(값타입)의 값을 전달받아오거나 변경할 수 없다는 내용으로 이해했습니다.
* 따라서 구조체에서 참조타입으로 class로 변경해 위와같은 에러를 해결했습니다

### BankQueue 파일위치이동 -> UI, Console 두개프로젝트 모두 적용되게끔 이동
<img src="https://i.imgur.com/nSPmIKQ.png" width= 80%>

*  지금은 `BankManagerUIApp` 프로젝트를 사용하지않지만 저희는 처음에 Queue를 UI쪽에 구현했습니다. 그러나 이번스텝은 `BankManagerConsoleApp`콘솔앱에 요구사항이 있었습니다. 콘솔앱에 프로젝트를 진행하는 외에도 추후에 UI앱쪽에도 `BankQueue`와 `BankManager`를 사용할 일이 있을거같아 위처럼 두개의 파일을 공동파일로 위치를 변경해주었는데 적절할까요?
-> `BankQueue`를 UIApp폴더 내에서 ios-bank-manager 파일로 이동

### usleep()과 sleep() 차이점
- sleep과 usleep은 기능은 같지만 usleep 초단위를 좀 더 세밀하게 동작할 수 있다는 차이점이 있습니다. 
- 초 단위를 0.7초 주어야 하는데 sleep은 Int 데이터형식으로만 표현할 수 있어서 usleep을 사용하였습니다.

### STEP1에서 만든 Queue 활용
```swift
func doBanking() {
    for i in 1...bankCustomers {
        let workItem = DispatchWorkItem {
            self.bankCustomer.enqueue(data: i)
            guard let customer = self.bankCustomer.peek() else { return }

            print("\(customer)번 시작")
            usleep(700000)
            self.bankCustomer.dequeue()
            print("\(customer)번 종료")
            usleep(700000)
        }
        DispatchQueue.global().sync(execute: workItem)
    }
    print("모두끝")
}
```
- BankManager파일의 doBanking 메서드를 보시면 STEP1에서 만든 Queue를 활용해 보왔습니다.
- Queue를 enqueue로 값을 넣고 peek로 첫번째값을 확인한다음 dequeue로 값을 빼는 방식으로 작성하였습니다.
- Queue가 없어도 ConsoleApp이 실행되는데 문제가 없지만 STEP2의 요구사항인 `고객의 대기열은 Step 1에서 구현한 Queue 타입을 활용합니다.`을 충족시키기 위해서 Queue를 활용해보았는데 여기에 대해서 고쳐야될점이 있는지 엘림의 의견이 궁금합니다

2023-03-09 07:59 UTC, lina0322 requested changes
여러분, 고생 많으셨습니다ㅎㅎ..

PR에 남겨주신 부분 struct -> class로 변경한 부분에 대해서는 어떤 상황이었는지
왜 변경하셨는지 좀 더 자세히 설명해주실 수 있을까요?!

전체적으로 정말 열심히 하신것 같은데, 논리가 지금 조금 안맞는게 많은거같아요.
지금 내용에서 객체로 존재해야하는 것들이 누구누구가 있는지 다시 생각해보시고
각 함수들의 역할을 누가 가져가야하는지, 대기열은 무엇인지! 좀 더 고민해봐야할거같아요~

코드를 짜는게 중요한게아니라, 돌아가는게 중요한게아니라 전체적인 논리와 맥락이 맞아야하고
객체의 역할들이 잘 분리가 되어있어야하는데, 지금은 돌아가는거에 많이 포커스가 되어있는 것 같아요!!

조금 더 예쁘게 수정해봅시당🥹
모르는거 있으면 DM 주십숑!!

2023-03-09 07:59 UTC, lina0322 commented on BankManager.swift
> +    var customerQueue = BankQueue<Int>()
customerQueue인데, 실제로는 Int queue아닌가요?
Customer는 어디있죠!👀

2023-03-09 07:59 UTC, lina0322 commented on BankManager.swift
> +    var bankCustomers: Int = 0
bankCustomers는 마치 [BankCustomer] 타입으로 보이는 네이밍입니다!

2023-03-09 07:59 UTC, lina0322 commented on BankManager.swift
> +    var bankCustomers: Int = 0
타입 명시를 하나요, 안하나요? 컨벤션도 중요한 것 중에 하나에요~
또한, 이 둘 모두 바깥에서 접근하고, 변경이 있기때문에 internal var로 설정하신거죠?!

2023-03-09 07:59 UTC, lina0322 commented on BankManager.swift
> +    func doBanking() {
bankManager.doBanking()
`뱅크매니저가 은행업무를 본다` 정도의 뜻으로 하신거같은데... 음 더 좋은 네이밍은 없을까요?

2023-03-09 07:59 UTC, lina0322 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +let a = BankManager()
이 코드는 뭔ㄱㅏ요?!

2023-03-09 07:59 UTC, lina0322 commented on BankQueue.swift
> +struct BankQueue<T> {
왜 이름을 **Bank**Queue라고 지엇나요?!

2023-03-09 07:59 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +}
이 명령어들을 실행하는 주체는 누구죠? 너무 전역적으로 사용되고있는데요 지금😅

2023-03-09 07:59 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    }
magic number 사용을 줄여주세요..!

2023-03-09 07:59 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +}
menuMessage() 라는 함수명도 다소 이상해보입니다! 함수는 동사로 시작하는 것을 기본규칙으로 잡아보세요!

2023-03-09 07:59 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    let bankManager = BankManager()
while을 돌면서 매번 BankManager를 생성하고 있는데, 의도한 부분인가요?

2023-03-09 07:59 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +        menuMessage()
만약에 매번 생성할거라면, 입력 숫자가 1일때만 생성하면 되지 않나요?
(이런 경우라면 bankCustomers의 접근 제어자는 private이 되어도 되겠죠?)

매번 생성하지 않을거라면, 여기서 bankCustomers를 변경해주는 방법을 쓸 수 있겠어요.
(그래도 직접적으로 접근하지않고, 함수를 통해서 변경해주는 방식이 더 좋아보입니다.)

무엇이든 상관없는데, 지금 다소 코드가 정리가 안될걸로 보이네요~ㅎㅎ 
if문말고 switch를 써도 괜찮을 것 같고, 각각의 케이스에서 동작하는 내용을 다른 메서드로 분리하는것도 방법이 될 수 있을거같아요

2023-03-09 07:59 UTC, lina0322 commented on BankManager.swift
> +    }
이건 Double을 extension하면 될거같네요

2023-03-09 07:59 UTC, lina0322 commented on BankManager.swift
> +    }
지금 여기가.. 음 뭘 원하는진 알겠는데 생각할게 많아보여요.

1. 은행원이 매번 생성되는 것이 맞나요?
2. 은행원이 큐에 i를 넣고, 방금 넣은 i를 다시 costomer로 굳이 찾아서 peek하는게 논리적으로 이상한거같은데요..
직원이 한명을 데려와서 줄을 세우고 업무를 보고 다시 내보내는거면, 사람들이 대기열에 서있는건 아니네요? 매번 한명만 있는것으로 보이는데요👀
3. `print("\(customer)번 고객 업무 시작"), print("\(customer)번 고객 업무 완료")` 이 두가지의 역할은 뱅크 매니저에 있는건가요 bankClerk에 있는건가요? 뱅크 매니저의 역할이 무엇이죠?? 
4. usleep시 멈추는 스레드는 어디인가요?
5. DispatchQueue.global().sync(execute: bankClerk)는 어떤 이유로 사용하셨나요??
DispatchQueue에는 어떤 큐들이 있나요? sync와 async는 무엇이 다른가요?
7. 업무 시간 계산하고 출력하는건 분리해주는게 좋지 않을까요?

2023-03-09 11:43 UTC, Goatt8 commented on BankManager.swift
> +    var bankCustomers: Int = 0
그러네요 배열로 보일 수 있을거같아서 `var = bankCustomer`로 변경했습니다ㅎ

2023-03-09 11:52 UTC, Andrew-0411 commented on BankManager.swift
> +    var customerQueue = BankQueue<Int>()
타입이 Int형이여서 숫자만 enqueue를 하기 때문에 변수명을 customerCounterQueue로 변경하였습니다
```swift
var customerCounterQueue = BankQueue<Int>()
```

2023-03-09 12:17 UTC, Goatt8 commented on BankManager.swift
> +    var bankCustomers: Int = 0
타입명시를 하는걸로 컨벤션을 수정했습니다ㅎ
customerQueue같은경우에는 외부접근이 지금 없는거같아 `private`선언 해주었습니다

2023-03-09 12:26 UTC, Andrew-0411 commented on BankManager.swift
> +    func doBanking() {
뱅크매니저가 은행을 관리한다는 뜻으로 manageBanking로 변경하였습니다

2023-03-09 12:29 UTC, Andrew-0411 commented on BankManagerUIApp/BankManagerUIApp/ViewController.swift
> +let a = BankManager()
UIApp에서도 Test를 해본 코드 삭제를 깜빡했습니다. 코드를 삭제하였습니다

2023-03-09 12:47 UTC, lina0322 commented on BankManager.swift
> +    var bankCustomers: Int = 0
변수 타입이 `Int`인데요! 
이러면 숫자와 어울리는 네이밍으로 변경하는게 맞을 것 같습니다. 
고객들의 수를 나타내는거라면 `customerCount`라는 네이밍이 더 맞겠네요.

만약 bankCustomer라면 ` var bankCustomer: BankCustomer = BankCustomer(...) ` 이런식으로 선언됐을거같네요🧐

2023-03-09 13:06 UTC, Goatt8 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +}
넵 너무 전역적으로 사용되고있는거같아 실행구문을 Struct BankDesk(은행업무보는곳)으로 파일분리후 실행만 main파일에서 하도록 수정했습니다

2023-03-09 13:26 UTC, Andrew-0411 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +}
동사로 시작하는 showMenuMessage로 변경하였습니다.

2023-03-09 13:27 UTC, Goatt8 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    let bankManager = BankManager()
아 의도한 부분이 아닙니다 .이부분 while BankManager 생성하는 오류도 struct BankDesk로 분리하면서 같이 바깥으로 빼주어 변경했습니다

2023-03-09 13:55 UTC, Goatt8 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +        menuMessage()
음 그러네요 customerCount프로퍼티를 자꾸 while로 재생성하는게 의미가 없어보여서 while 문밖으로 빼내주었습니다
BankDesk에서 `bankCustomer`에 값을 할당하는 식으로 변경해주었습니다
```swift
let customerCount = Int.random(in: 10...30)
bankManager.bankCustomer = customerCount
```

2023-03-09 14:13 UTC, Goatt8 commented on BankManager.swift
> +    }
넵 digitFormatter 매서드 Extension 파일분리후 Double Extension으로 재정의했습니다

2023-03-09 14:58 UTC, Andrew-0411 commented on BankManager.swift
> +    }
1. 매번 생성되는건 부적절해보입니다 for문 밖으로 일단 빼보았습니다

2. STEP1에서 만든 Queue를 최대한 활용을 하고 싶어서 코드가 돌아가는 선에서 적용해봤었는데, 불필요하다면 제거도 가능할 것 같아 제거했습니다. queue에는 고객들이 담기고 첫번째 고객을 peek으로 끌어와 업무처리, 종료후에 dequeue로 내보내고 두번째 고객을 peek으로 선정해 불러오는 식의 코드였습니다.

3. 기존엔 두가지의 역할을 bankClerk에서 하고있다고 봐야합니다. for문안에 dispatchQueue 상수를 선언하다보니 상수명과 클래스명을 다르게 적어 오해를 불러일으킨것 같습니다. for문때문에 기존 코드에서 오류가 많이 발생한것 같네요. for문 안 bankClerk를 제거하고 bankManager클래스가 manageBanking()매서드를 수행한다는 의미로 전달될 수 있게끔 코드를 수정했습니다.

4. 지금 코드에선 global로 선언한 멀티스레드가 정지하고있다고 봐야되겠네요

5. 은행원이 한명인데 왜 global로 선언했는지.. 오류가 있었네요ㅜ 메인스레드에서 sync로 선언해줘도 충분할 것 같습니다.
DispatchQueue ( main / global ) ( sync / async )
    * main - 말그대로 메인스레드입니다. 한개만 존재하고 직렬의성질을 가지며 주로 빠르게나타나야하는 UI작업을 처리합니다
    * global - 멀리스레드로서 메인스레드와 동시성으로 작업을 진행하는 스레드들입니다
    * sync - 동기적 프로그래밍으로서 스레드.sync시 작업을 순차적으로 진행합니다
    * async - 비동기적 프로그래밍으로서 스레드.async시 작업을 동시다발적으로 진행합니다

6. calculateBankingTime 메서드를 작성하여 분리하였습니다

2023-03-13 06:58 UTC, Andrew-0411 commented on BankManager.swift
> +    var bankCustomers: Int = 0
아 저희가 너무 짧게 생각한거 같습니다 말씀하신대로 customerCount로 변경하였습니다.

`만약 bankCustomer라면 var bankCustomer: BankCustomer = BankCustomer(...) 이런식으로 선언됐을거같네요🧐`
예시를 들어주시니 이해가 잘 되었습니다

2023-03-13 07:52 UTC, Andrew-0411 commented
**문제 화면**
![](https://i.imgur.com/1FOg4OV.png)
- BankManager를 Struct로 했을 시 DispatchWorkItem을 사용하는 과정에서 에러가 발생했습니다.
- `Escaping closure captures mutating 'self' parameter`
- closure가 struct의 변경 가능한 self를 참조할 수 없다는 규칙이 있어서 에러가 발생되었다고 생각되서 BankManager를 class로 변경하였습니다

2023-03-13 11:20 UTC, lina0322 reviewed
음, 조금만 더 수정해봅시다...ㅠ
줄세우기에 대한 부분이 잘 정립이 안된거같아요.
손님의 일을 봐주면서 하는게아니라, 줄은 매니저가 쭉 세우고(예를들어 대기표를 나눠주는 기계),
직원은 그 대기 줄에 접근해서 한명씩 데려가는거죠! 그래야 여러 직원일때도 대응이 가능해질거같아요~

2023-03-13 11:20 UTC, lina0322 commented on BankDesk.swift
> +    func showMenuMessage(){
private을 붙이는 걸 기본으로하고, 개방해야할때만 지우는 방식으로 해보세요!

2023-03-13 11:20 UTC, lina0322 commented on BankDesk.swift
> +    func showMenuMessage(){
여기 `(){` 사이에 띄어쓰기 해주세요~

2023-03-13 11:20 UTC, lina0322 commented on BankDesk.swift
> +        print(menuMessage.input, terminator: "")
하나의 print로 출력할 수 있는 방법이 있을까요? 굳이 수정할 필요는 없고, 방법을 아시는지 궁금합니다ㅎㅎ
그리고 지금 1번메뉴랑 2번메뉴랑 앞쪽 띄어쓰기가 다른거같아요~

2023-03-13 11:20 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/TextEnum.swift
> +enum menuMessage {
이거 왜 소문자로 시작하나요??

2023-03-13 11:20 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/TextEnum.swift
> +}
menuMessage를 사용하는 곳이 BankDesk인것 같은데 따로 파일을 분리할 필요 없이, BankDesk가 소유하고 있는게 좋지 않을까요? 모든 객체들이 접근할 필요가 있나 해서요

추가로 Menu라는 enum안에, case로 open과 close가 있고 그 enum안에서 "은행 개점", "종료"를 가지고 있는게 자연스러울 것 같아요~

2023-03-13 11:20 UTC, lina0322 commented on BankDesk.swift
> +        bankManager.customerCount = customerCount
`inputNumber == "1"`인 경우에만 동작하면 될거같아요.

2023-03-13 11:20 UTC, lina0322 commented on BankDesk.swift
> +            } else if inputNumber == "1" {
매직 넘버가 아직 사용중인 것으로 보입니다?!

2023-03-13 11:20 UTC, lina0322 commented on BankDesk.swift
> +        }
showMenuMessage가 반복되네요~ 
repeat-while을 사용하는 방법도 있겠어요.

2023-03-13 11:20 UTC, lina0322 commented on BankManager.swift
> +    }
음, 줄을 먼저 세우고 한명씩 꺼내서 하는게 맞는거같아요.
줄세우기함수를 따로 분리해서 손님들을 줄세우고, 직원이 큐에서 꺼내는거죠🧐
즉, enqueue랑 dequeue가 한 함수내에서 이뤄지면 안되고, enqueue를 모두 끝낸 후에
거기서 한명씩 dequeue하면서 업무를 봐줘야하는 것 같아요.
이렇게되면 대기줄에 그냥 들어갔다 나오는거지 줄을 서있는게 아니잖아요?ㅎㅎ... 이해가 가나여..??

2023-03-13 11:20 UTC, lina0322 commented on BankManager.swift
> +    }
extension 하기로 하지 않았나요??

2023-03-13 11:20 UTC, lina0322 commented on BankManager.swift
> +    func calculateBankingTime() {
private 붙여주세요~

2023-03-13 11:20 UTC, lina0322 commented on BankManager.swift
> +    func calculateBankingTime() {
calculate하면서 print의 역할도 하는 것으로 보여요

2023-03-13 11:20 UTC, lina0322 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +bankDesk.inputBankingMenu()
이전보다 나아졌어요!

2023-03-13 11:22 UTC, lina0322 commented on BankManager.swift
> +    }
`serial queue를 사용하고 한개만 존재하며 직렬의성질을 가지며 주로 빠르게 나타나야 하는 UI작업을 처리하는 메인쓰레드입니다.`
그럼 메인 스레드가 정지해도 될까요??

2023-03-13 12:16 UTC, Goatt8 commented on BankManager.swift
> +    }
아 extension적용했는데 commit하면서 누락된거같아여ㅠ 다시 적용해놓겠습니다

2023-03-13 12:18 UTC, Goatt8 commented on BankManager.swift
> +    }
넵 이해했습니다 한번 매서드를 분리해서 시도해볼게요!

2023-03-14 00:32 UTC, Goatt8 commented on BankManager.swift
> +    }
필요에 따라 정지시킬 수 있다고 생각합니다. 보통 어플리케이션에서는 메인스레드가 정지하면 사용에 불편함이 발생하기때문에 비동기, 동시성 프로그래밍을 적용시키는거라고 생각합니다.

2023-03-14 01:02 UTC, Goatt8 commented on BankDesk.swift
> +            } else if inputNumber == "1" {
1과 2는 스트링으로 처리했을때 가독성이 더 떨어지는거같아서 입력은 그냥 1, 2로 표시해두는게 낫다고 판단해서 그대로 두었습니다!

2023-03-14 01:19 UTC, Andrew-0411 commented on BankDesk.swift
> +    func showMenuMessage(){
private을 붙이고 에러가 발생하면 지우는 방식으로 수정하였습니다

2023-03-14 01:20 UTC, Andrew-0411 commented on BankDesk.swift
> +        print(menuMessage.input, terminator: "")
\n을 사용하여 print문 하나로 수정해보았습니다

2023-03-14 01:23 UTC, Andrew-0411 commented on BankManagerConsoleApp/BankManagerConsoleApp/TextEnum.swift
> +enum menuMessage {
😣 대문자로 변경하였습니다....

2023-03-14 02:21 UTC, Andrew-0411 commented on BankDesk.swift
> +        bankManager.customerCount = customerCount
넵 createCustomerCount라는 메서드로 만들어서 빼주고 입력값이 1일때만 동작하게끔 수정하였습니다

2023-03-14 02:25 UTC, Andrew-0411 commented on BankManagerConsoleApp/BankManagerConsoleApp/TextEnum.swift
> +}
BankManager에 `고객 업무 시작`,`고객 업무 종료`와 같이 String 타입을 따로 빼줘야 할것들이 있는것처럼 프로젝트를 진행할 수록 다른 파일에서도 String 타입을 따로 빼줘야 할 경우의 수가 생길수 있기 때문에 TextEnum 파일은 유지하기로 선택하였습니다.

2023-03-14 02:48 UTC, Andrew-0411 commented on BankDesk.swift
> +        print(menuMessage.input, terminator: "")
저희가 STEP1에서 말씀드렸던것처럼 return문이 짧으면 한줄로 사용하고 길면 들여쓰기를 한다고 말씀드렸는데 이것도 print로 출력하는게 적다면 print문 한개로 전부 기입하고 길면 print문을 여러개 생성해서 따로따로 기입하는 식으로 상황에 맞춰서 사용한다고 생각하면 될까요?

2023-03-14 02:50 UTC, Andrew-0411 commented on BankDesk.swift
> +        }
```swift
func inputBankingMenu() {
    showMenuMessage()
    while let inputNumber = readLine() {
        if inputNumber == "1" {
            createCustomerCount()
            bankManager.manageBanking()
        } else if inputNumber == "2" {
            print(MenuMessage.bankClose)
            break
        } else {
            print(MenuMessage.inputErrorMessage)
        }
        showMenuMessage()
    }
}
```
showMenuMessage를 if문 바깥으로 빼내어서 중복을 한번 줄이는것까지 고쳐봤습니다.
하지만 while문 바깥에 있는 showMenuMessage를 줄이는것까지는 하지못하였고 엘림이 말씀하신 repeat-while 방법을 사용은 할줄 아는데 어떻게 사용해서 반복을 줄여야할지를 구현하지 못하였는데 힌트를 받을 수 있을까요?

2023-03-14 03:10 UTC, Andrew-0411 commented on BankManager.swift
> +    func calculateBankingTime() {
포맷팅과 print문을 분리하는 방법과 메서드명을 변경하는 방법을 고민했고 메서드를 변경하는 방법을 선택하였습니다
은행이 종료될때 사용하는 메서드이기 때문에 메서드 이름을 closeBanking으로 변경하였습니다

2023-03-14 04:42 UTC, lina0322 commented on BankDesk.swift
> +        print(menuMessage.input, terminator: "")
ㅎㅎㅎ앗, 제가 말한 방식은 `여러줄 문자열 리터럴`이었습니당!

```swift
let quotation = """
The White Rabbit put on his spectacles.  "Where shall I begin,
please your Majesty?" he asked.

"Begin at the beginning," the King said gravely, "and go on
till you come to the end; then stop."
"""
```

> 저희가 STEP1에서 말씀드렸던것처럼 return문이 짧으면 한줄로 사용하고if ... { return ... } 길면 들여쓰기를 하기로 정했다고 말씀드렸는데 이것도 print로 출력하는게 적다면 print문 한개로 전부 기입하고 길면 print문을 여러개 생성해서 따로따로 기입하는 식으로 상황에 맞춰서 사용한다고 생각하면 될까요?

뭐든지 상황에 맞게 사용하는거라 정답은 없습니다~
하다보면 점점 사람들이 많이 사용하는 방식들이 보이고 여러분들도 편한 방식이 생길거에요!

아, 개인적으로는 저는 return은 짧아도 모두 줄바꿈을 하는 편입니다.
이유는 break point잡을때 편한거랑 전체적으로 통일감을 주려고요ㅎㅎㅎ..!
이런식으로 여러분만의 이유를 점점 만드시면 돼요!

2023-03-14 04:43 UTC, lina0322 commented on BankManager.swift
> +    }
흠.. 요거는 천천히 좀 더 생각해보죠~

2023-03-14 04:45 UTC, lina0322 commented on BankDesk.swift
> +            } else if inputNumber == "1" {
왜 가독성이 떨어지죠? 흠.. 숫자를 그냥 사용하는건 불편함이 클거같은데요.
지금은 화면이 1개지만, 3개가 되고 20개가 되는데, menu 값을 여기저기서 사용해야한다면 어떨까요?
갑자기 닫기 숫자를 1로 변경하자고 하면요? 그럼 1 검색해서 전부 값을 변경해야할까요??🥲
더 넓은 시야로 생각해봅시다!

2023-03-14 04:51 UTC, lina0322 commented on BankDesk.swift
> +        }
지금과 같은 방식도 좋습니다~! 중복을 줄이는게 목적이니까요~😀

2023-03-14 04:51 UTC, lina0322 commented
우선 여기까지 진행하고, 추가 수정할 부분은 다음 스텝에서 더 고쳐봅시당!!

2023-03-14 04:51 UTC, merged

2023-03-14 06:21 UTC, Andrew-0411 commented on BankDesk.swift
> +        }
```swift
func openBanking() {
    while true {
        showMenuMessage()
        if let inputNumber = readLine() {
            if inputNumber == "1" {
                createCustomerCount()
                bankManager.insertCustomerCountToQueue()
                bankManager.manageBanking()
            } else if inputNumber == "2" {
                print(MenuMessage.bankClose)
                break
            } else {
                print(MenuMessage.inputErrorMessage)
            }
        }
    }
}
```
이렇게 다시 바꿔서 showMenuMessage()를 2개에서 하나로 줄여봤습니다 !