은행창구 매니저 [STEP3] kaki, songjun
yagom-academy/ios-bank-manager pull request #274
Opened 2023-03-10 06:03 UTC by kak1x

# 은행창구 매니저 [STEP3] kaki, songjun
@AppleCEO
안녕하세요 도미닉~! STEP3 구현이 완료되어 PR 드립니다!
STEP3 리뷰도 잘 부탁드릴게요~🙇🏻

## 구현 내용
### 업무 처리 비동기화
- 업무를 비동기 처리 해주기 위해 `processBankTask` 메서드를 구현해주었습니다.
- 대출 업무를 담당하는 은행원은 1명, 예금 업무를 담당하는 은행원은 2명이라는 요구사항을 충족시키기 위해 `DispatchSemaphore(value:)`를 사용하여 스레드의 숫자를 지정해주었습니다.
- 비동기 처리가 끝난 이후 다음 코드가 진행될 수 있도록 `DispatchGroup`의 `group.wait()`을 사용하였습니다.

### 소요 시간 계산
- 프로그램의 소요 시간을 계산하기 위해 `CFAbsoluteTimeGetCurrent()`를 사용해주었습니다.
- 이를 사용하여 코드가 끝나는 시간 - 코드가 시작되는 시간의 계산을 통해 소요 시간을 계산하였습니다.

## 고민한 점
### 비동기 코드를 넘기고 바로 뒤의 코드를 실행시키는 현상
- 업무에 관한 코드를 전부 비동기로 설정해주었더니 비동기 코드를 바로 끝내고 아예 기다리지 않은 채 뒤의 코드를 실행시키는 문제가 발생하였습니다.

![](https://i.imgur.com/seTy6Jj.png)

### 해결방법
```swift
mutating func processBusiness() {
    while !waitingQueue.isEmpty {
        guard let client = waitingQueue.dequeue() else { return }
        processBankTask(client)
    }
    group.wait()
    
    presentBusinessResult(time: wasteTime)
}

private func processBankTask(_ client: Client) {
    if client.requstedTask == .loan {
        DispatchQueue.global().async(group: group) {
            loanSemaphore.wait()
            loanSemaphore.signal()
        }
    } else {
        DispatchQueue.global().async(group: group) {
            depositSemaphore.wait()
            depositSemaphore.signal()
        }
    }
}
```

- DispatchGroup을 이용하여 비동기적으로 처리되는 작업들을 그룹으로 묶어주고, group.wait()을 사용하여 DispatchGroup의 수행이 끝나는것을 기다리게 해주어 문제를 해결하였습니다.

2023-03-10 12:50 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@kak1x , @kimseongj  고생하셨습니다!
프로젝트를 열어봤을 때 파일 수가 많지 않고 코드 수도 길지 않아서 정돈된 느낌을 받았습니다.
구현하기 힘든 프로젝트였을텐데 빠른 시간 안에 잘 수행하셨네요!
몇가지 개선하면 좋은 점들 남겨봤습니다.
확인 부탁드려요~

2023-03-10 12:50 UTC, AppleCEO commented on BankManager.swift
> +    private let group = DispatchGroup()
group 이라는 프로퍼티명은 포괄적인 의미라고 생각해요.
더 명확한 이름으로 변경해 볼 수 있을까요?

2023-03-10 12:50 UTC, AppleCEO commented on BankManager.swift
> +                                requstedTask: .init(rawValue: Int.random(in: 1...2)) ?? .deposit)
여기서도 )) 에다가 ?? 도 붙어서 어떤 코드인지 쉽게 이해가 안되네요!
줄이 길어져도 명확하게 잘 이해되도록 풀어서 쓰는 것이 좋겠습니다~

2023-03-10 12:50 UTC, AppleCEO commented on BankManager.swift
> +        let wasteTime = CFAbsoluteTimeGetCurrent() - startTime
wasteTime 은 시간 낭비라고 번역되는데요.
이 시간은 낭비된 시간을 나타내는 것 같지 않네요!
어떤 시간일까요?

2023-03-10 12:50 UTC, AppleCEO commented on BankManager.swift
> +        } else {
else 를 쓰는 것도 좋지만 task의 종류가 명확하다면 else if 로 그 task 인지 확인하는게 더 좋습니다.
지금은 else 에 들어가는 것이 deposit 뿐이겠지만 업무의 종류가 추가되면 여러 업무가 이 else 문에서 동작하는 버그가 발생할 수 있어요~

2023-03-10 12:50 UTC, AppleCEO commented on BankManager.swift
> +                Thread.sleep(forTimeInterval: 1.1)
이 1.1 을 하드코딩하지 않고 어떤 시간인지 변수 등에 저장해놓고 사용해 볼 수 있을까요?

2023-03-10 12:50 UTC, AppleCEO commented on BankManager.swift
> +                Thread.sleep(forTimeInterval: 0.7)
위에 if문과 이 시간만 차이 난다면 혹시 중복을 제거해 보면 어떨까요?

2023-03-10 12:50 UTC, AppleCEO commented on BankManager.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(numberOfClient)명이며, 총 엄무시간은 \(String(format: "%.2f", time))초입니다.")
줄이 조금 여러 줄로 늘어나도 쭉 읽히는 것이 좋은 코드입니다.
여기서는 String으로 형변환을 하는데 숫자의 아래 두자리까지만 자르는 코드가 함께 있으니 한 눈에 딱 들어오지 않네요!
저번에 리뷰한 것처럼 상수 같은 곳에 순차적으로 저장해서 변환되는 과정이 잘 보여지면 좋겠습니다!

2023-03-10 12:50 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        case deposit = 2
여기 = 2 를 생략하면 어떻게 동작할까요?

2023-03-10 12:50 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    enum Banktask: Int {
열거형을 활용하기 좋은 곳이네요! 🥇

2023-03-13 06:35 UTC, kimseongj commented on BankManager.swift
> +    private let group = DispatchGroup()
`bankTaskGroup`로 프로퍼티명을 수정했습니다!

2023-03-13 06:35 UTC, kimseongj commented on BankManager.swift
> +                                requstedTask: .init(rawValue: Int.random(in: 1...2)) ?? .deposit)
줄바꿈을 수정했습니다.

2023-03-13 06:37 UTC, kak1x commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        case deposit = 2
위 코드에서 2만 생략해주어도 1부터 순차적으로 할당되기에 2가 할당될 것입니다.
프로젝트에선 원시값에 할당해준 1, 2를 전부 제거해주어 기본적으로 할당되는 0과 1을 사용하는 것으로 수정하였습니다.

2023-03-13 06:38 UTC, kak1x commented on BankManager.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(numberOfClient)명이며, 총 엄무시간은 \(String(format: "%.2f", time))초입니다.")
`totalTaskTime`라는 지역변수를 생성하여 String 포멧하는 과정을 따로 빼주었습니다.

2023-03-13 06:38 UTC, kimseongj commented on BankManager.swift
> +        let wasteTime = CFAbsoluteTimeGetCurrent() - startTime
소요시간을 표현했던거 같습니다. `wasteTime`을 `leadTime`으로 수정했습니다! 
9d450454fef0ec8cb9b4f7bfb7c1e4f80b7a7e44

2023-03-13 06:38 UTC, kak1x commented on BankManager.swift
> +                Thread.sleep(forTimeInterval: 0.7)
중복되는 부분만을 `processPersonalBankTask` 함수로 정의하여 사용해주었습니다.

2023-03-13 06:38 UTC, kimseongj commented on BankManager.swift
> +        } else {
`else if`문으로 수정했습니다!

2023-03-13 06:39 UTC, kimseongj commented on BankManager.swift
> +                Thread.sleep(forTimeInterval: 1.1)
Client 구조체에 있는 BankTask에 추가적인 연산프로퍼티를 구현하여 하드코딩을 수정했습니다.
baf6447e4513304c5f3474cafc111bf040c481d2

2023-03-13 06:40 UTC, kak1x commented on BankManager.swift
> +                Thread.sleep(forTimeInterval: 1.1)
Client의 BankTask 열거형 안에 taskTime이라는 계산 속성을 추가해주어 각 case에 따라 다른 시간값(Double)을 리턴해주도록 수정하였습니다.

2023-03-13 08:51 UTC, AppleCEO approved these changes
많이 개선되었습니다~
몇가지 코멘트 남겼는데 다음 스텝을 진행하면서 보셔도 될 내용들이라고 생각합니다.
머지를 원하시면 연락주세요!
고생하셨습니다.

2023-03-13 08:51 UTC, AppleCEO commented on BankManager.swift
> +            let client = Client(clientNumber: number, requstedTask: .init(rawValue: Int.random(in: 0...1)) ?? .deposit)
오~ 한 줄로 작성해보셨군요 👍 
저는 위에서 여러번 했던 것처럼 Int.random(in 0...1) 을 상수에 넣어서 처리하는 것을 원했습니다!
다음 스텝을 진행하면서 이런 코드들 전체적으로 수정해보시면 좋겠습니다~

2023-03-13 08:51 UTC, AppleCEO commented on BankManager.swift
> +        let leadTime = CFAbsoluteTimeGetCurrent() - startTime
leadTime 은 어떤 시간일까요? 🔢

2023-03-13 08:51 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +        case deposit
지워보셨군요! 꼭 지우는 것을 의도하지는 않았습니다. ㅎㅎ

2023-03-13 08:51 UTC, AppleCEO commented on BankManager.swift
> +                Thread.sleep(forTimeInterval: NumberCase.depositTime)
하드코딩을 지운 것 좋네요!
보통 이렇게 하드코딩된 숫자를 지우는 것을 더 좋은 코드로 생각합니다~ 💯

2023-03-13 08:51 UTC, AppleCEO commented on BankManager.swift
> +    }
오 반복된 코드를 함수로 빼낸 것 너무 좋은데요~ 🥇

2023-03-13 08:51 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +            }
이 숫자가 어디선가 반복되는 것 같은데? 한 곳으로 통일해봐도 좋겠네요~

2023-03-13 08:51 UTC, AppleCEO commented on BankManager.swift
> +        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(numberOfClient)명이며, 총 업무시간은 \(totalTaskTime)초입니다.")
제가 의도한 것입니다~ 👍

2023-03-13 09:10 UTC, merged

2023-03-15 02:20 UTC, kak1x commented on BankManager.swift
> +        let leadTime = CFAbsoluteTimeGetCurrent() - startTime
`리드 타임(상품 생산 시작부터 완성까지 걸리는 시간), 소요시간` 이라는 뜻을 사전에서 찾았기에 leadTime으로 네이밍해주었습니다.