은행 창구 매니저[STEP3] 리지, 무리
yagom-academy/ios-bank-manager pull request #276
Opened 2023-03-10 07:04 UTC by yijiye

@uuu1101
안녕하세요 태태~! 드디어 STEP3 PR을 보내네요...!
뭔가 이번 스텝 진행하면서 초반에 했던 생각이 다 바뀌는 바람에 많이 헤맨 것 같아요...🥲
그럼 리뷰 기다리고있겠습니다😊!

---
## 고민했던 부분

### 1️⃣ 은행원이 누구일까?
> 은행에는 3명의 은행원이 근무합니다(예금담당 2명, 대출담당 1명)
- 은행에는 은행원이 세 명 근무하도록 안내되어있었습니다. `BankClerk`타입을 구현 해 놓은 후라서 "세 개의 global 스레드 안에 각각 BankClerk 인스턴스를 만들어주면 되지 않을까?" 생각을 했습니다. 

#### `BankClerk()` 인스턴스로 생각했을 때 (문제발생)
- 저희가 처음 생각한 부분은 은행이 은행원에게 대기줄에 있는 손님들을 async로 줄세워주고, 손님들을 받은 은행원들은 동기적으로 일을 처리한다고 생각했습니다.
그래서 은행이 client의 watingLine에서 dequeue하여 bankClerk에게 전달하는 행위자체를 `DispatchQueue.global().async { }` 로 구현하였습니다. 
그리고 client를 전달받은 `BankClerk()`이 3명이 존재하므로 3개의 `DispatchWorkItem`안에 `BankClerk()` 인스턴스를 각각 만들어주었고, client의 방문 목적에 따라 if문을 통하여 deposit/loan으로 나뉘어 세 개의 스레드 중 해당 업무를 처리하는 `BankClerk()`이 존재하는 스레드로 보내주었습니다.
- 위와같이 생각하고 구현을 한 결과, 다음과 같은 문제들이 발생했습니다.
    1. deposit 목적의 client는 두 개의 스레드를 거쳐서 중복으로 출력된다.
    2. 세 개의 스레드 안에 존재하는 `BankClerk()`들이 동기적으로 일을 하지 못한다.
    
```swift
private func dispatchQueue(_ currentClient: Client) {
    DispatchQueue.global().async { // 은행원에게 고객을 주는 과정이라고 생각
        let depositServiceA = DispatchWorkItem() { //은행원이 고객을 담당하여 업무를 처리하는 과정이라고 생각하여 총 3명의 은행원을 직접 구현
            let bankClerk = BankClerk()
            bankClerk.service(to: currentClient)
        }
        let depositServiceB = DispatchWorkItem() {
            let bankClerk = BankClerk()
            bankClerk.service(to: currentClient)
        }
        let loanService = DispatchWorkItem() {
            let bankClerk = BankClerk()
            bankClerk.service(to: currentClient)
        }

        if currentClient.purposeOfVisit == .deposit {
            DispatchQueue.global().sync(execute: depositServiceA)
            DispatchQueue.global().sync(execute: depositServiceB)
        } else {
            DispatchQueue.global().sync(execute: loanService)
            }
}
    
```

#### `Thread` 로 생각했을 때 (해결방법)
- 인스턴스로 직접 만들어서 구현하니 위와같은 문제가 발생하여 BankClerk의 인스턴스로 은행원의 실체를 만드는 것이 아니라, 은행원을 하나의 스레드로 생각 하고 서비스를 제공하는 BankClerk의 인스턴스 한개를 전역변수로 구현하였습니다. 그리고 **접근하는 스레드의 수 (=은행원)** 를 `Semaphore`로 제한함으로써 총 3명의 은행원이 일을 처리하도록 구현하였습니다.
```swift
// Bank.swift
private var bankClerk = BankClerk()
private let loanBankClerk = DispatchSemaphore(value: 1)
private let depositBankClerks = DispatchSemaphore(value: 2)

private func dispatchQueue(_ currentClient: Client) {
    let depositService = DispatchWorkItem() {
        depositBankClerks.wait()
        bankClerk.service(to: currentClient)
        depositBankClerks.signal()
    }
    let loanService = DispatchWorkItem() {
        loanBankClerk.wait()
        bankClerk.service(to: currentClient)
        loanBankClerk.signal()
    }

    if currentClient.purposeOfVisit == .deposit {
            DispatchQueue.global().async(execute: depositService)
    } else {
        DispatchQueue.global().async(execute: loanService)
    }
}
```

### 2️⃣ 스레드 실행 순서

- 은행원을 스레드로 생각하여 `DispatchQueue.global().async` 로 3명의 은행원에서 고객들을 비동기적으로 처리하도록 구현하였는데, 메인스레드가 아닌 다른 스레드에서 작업을 처리하여 작업이 끝나기 전에 메인스레드에 있는 `notifyTaskCompletion` 메서드가 실행되어 함수 내부의 print문이 출력되는 오류가 있었습니다.
실행 순서 문제를 해결하고자 `DispatchGroup`을 전역상수로 두고`DispatchQueue.global().async`를 group로 묶어준 후 `group.wait()` 메서드를 사용하였습니다. 이때, 시간을 계산하고 print문이 출력되어야 하므로 doTask() 일이 끝나는 곳에서 `group.wait()`메서드를 실행하였습니다.

```swift
// Bank.swift
private let group = DispatchGroup

mutating func doTask() {
    for _ in 1...waitingLine.count {
        guard let currentClient = waitingLine.dequeue() else { return }
        dispatchQueue(currentClient)
    }

    group.wait()
}

private func dispatchQueue(_ currentClient: Client) { 
    // ...
    if currentClient.purposeOfVisit == .deposit {
        DispatchQueue.global().async(group: group, execute: depositService)
    } else {
        DispatchQueue.global().async(group: group, execute: loanService)
    }
}
```

2023-03-13 18:50 UTC, uuu1101 commented
고민하신 부분과 해결까지 STEP별로 잘 해결해 나가고 계시네요 💯
몇가지 코멘트 남겨두었습니다 :) 
비동기 프로그래밍에 대해서 잘 이해해 나가고 계신 것 같아요.
여유가 되신다면, GCD 와 OperationQueue 의 차이도 한번 훑어보시면 좋을 것 같습니다 ! 

이번 스텝도 고생하셨습니다 👏👏👏👏

2023-03-13 18:51 UTC, uuu1101 requested changes
고민하신 부분과 해결까지 STEP별로 잘 해결해 나가고 계시네요 💯

몇가지 코멘트 남겨두었습니다 :) 
비동기 프로그래밍에 대해서 잘 이해해 나가고 계신 것 같아요.

여유가 되신다면, GCD 와 OperationQueue 의 차이도 한번 훑어보시면 좋을 것 같습니다 ! 
이번 스텝도 고생하셨습니다 👏👏👏👏👏

2023-03-13 18:51 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Bank.swift
> +    private let group = DispatchGroup()
어떤 그룹인지 명확하게 표현해보시는 것도 좋아보여요 :)

2023-03-13 18:51 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Task.swift
> +}
enum 타입을 사용하셨네요 👍

2023-03-13 18:51 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Bank.swift
>      mutating func lineUpClient() {
외부에서 알아야하는 메서드가 아니라면 접근제어자를 붙여주는건 어떨까요?

2023-03-13 18:51 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Bank.swift
> +    mutating func calculateTaskTime() -> String {
위와 동일합니다 :)

2023-03-13 18:51 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Bank.swift
>      mutating func doTask() {
위와 동일합니다 :)

2023-03-13 18:51 UTC, uuu1101 commented on BankManagerConsoleApp/Model/Bank.swift
>      }
해당 부분은 실제로 은행을 빗대보면 어떤 역할을 하는 부분일까요?
`dispatchQueue` 라는 메서드명은 어떤 것을 의미하나요..? 👀

2023-03-13 18:51 UTC, uuu1101 commented on README.md
> +# 트러블 슈팅
리드미를 정말 꼼꼼하게 잘 작성하고 계시네요 :)
캠프를 하는 동안 그리고 끝나고도 아주 좋은 자료들이 될거에요 ! 👍

2023-03-14 01:24 UTC, parkmuri commented on BankManagerConsoleApp/Model/Bank.swift
> +    private let group = DispatchGroup()
- 업무를 수행하는 그룹이라는 의미로 `taskGroup`으로 리네이밍해보았습니다!

2023-03-14 01:25 UTC, yijiye commented on BankManagerConsoleApp/Model/Bank.swift
>      mutating func lineUpClient() {
아 넵! 접근제어자 설정하였습니다.

2023-03-14 01:25 UTC, yijiye commented on BankManagerConsoleApp/Model/Bank.swift
> +    mutating func calculateTaskTime() -> String {
접근제어자 설정하였습니다!

2023-03-14 01:25 UTC, parkmuri commented on BankManagerConsoleApp/Model/Bank.swift
>      }
- 줄을 세운 클라이언트들을 은행원에 배정해준다고 생각하여 `assignToBankClerk`으로 리네이밍해보았습니다!

2023-03-14 01:25 UTC, yijiye commented on BankManagerConsoleApp/Model/Bank.swift
>      mutating func doTask() {
접근제어자 설정하였습니다!

2023-03-14 15:20 UTC, uuu1101 commented
고생하셨습니다 ! 다음 STEP 진행해주세요 :) 👍

2023-03-14 15:20 UTC, merged