은행 창구 매니저 [STEP 3] Rhode, sehong
yagom-academy/ios-bank-manager pull request #277
Opened 2023-03-10 07:46 UTC by Rhode-park

@1Consumption
안녕하세요 올라프!⛄️⛄️⛄️⛄️ 
STEP3 PR 보냅니다.
다중처리하는 부분에 있어서 반복되는 코드가 생겨 어려움이 있었던 것 같습니다.
항상 바쁘신 와중에 리뷰해주셔서 감사합니다. 
이번에도 리뷰 잘 부탁드립니다.
감사합니다.⛄️

# 조언을 얻고 싶은 부분
## 1. manageClientQueue 메서드 client 생성자 분리하면서 발생하는 문제 

step2에서 손님 정보는 외부에서 생성자로 주입해줘도 좋을 것 같다는 조언을 얻어
```swift=
private mutating func manageClientQueue() -> Queue<Client> {
        var clientQueue = Queue<Client>()
        let randomClients = Int.random(in: 10...30)
    ....
```

수정후 아래와 같이 조금 더 직관적인 코드로 보기 좋게 수정되었습니다. 

```swift=

var bank = Bank(clientCount: Int.random(in: 10...30))

...

init(clientCount: Int) {
        self.clientCount = clientCount
    }

```

코드를 수정하고나서 무슨 문제인지ㅠ 고객의 수가 지정되어 업무를 마감하고 다시 은행 개점을 하면 같은 고객의 수가 반복되어 지정되는 문제가 발생하게 되었습니다. 해당 부분은 어떤식으로 해결해야할지 몰라서 원상태로 돌려뒀는데 원인을 알고싶습니다ㅠ

## 2. 업무는 동시적으로 처리되지만, 업무시간은 누계로 나오는 문제
업무는 동시적으로 처리가 되지만, 업무시간은 모든 업무의 누계로 나오는 문제가 발생하고 있습니다. 그러한 문제로 인하여 리팩토링을 하려고 하는데, 저희 코드 로직의 문제인지 아니면 `endTime.timeIntervalSince(startTime)` 코드의 문제인지 모르겠습니다. 

**다음은 저희가 겪고 있는 문제입니다**

이해를 돕기 위하여 고객의 수를 4명으로 정해보았습니다:

![](https://i.imgur.com/1pKZklN.png)

1번 고객은 대출업무를, 234번 고객은 예금 업무를 받습니다. 은행원은 A, B, C 세 명으로 A와 B는 예금 업무를, B는 대출업무를 처리합니다. 이 때 걸리는 시간은 다음과 같습니다:
 - A: 2번 고객(0.7초) -> 4번 고객(0.7초) => 1.4초
 - B: 3번 고객(0.7초) => 0.7초
 - C: 1번 고객(1.1초) => 1.1초
 - total: 1.4초

그런데, 저희의 코드는 총 3.21초를 나타내고 있습니다. 이는 1.4초와 0.7초와 1.1초를 더한 3.2초에 근사한 값입니다.

위와 같은 문제때문에 리팩토링을 하려고 합니다. 그런데, 무엇이 문제인지 파악할 수 없습니다.

콘솔창에는 2번->3번->1번->4번의 순서로 업무가 시작되고 종료되어 동시적으로 일을 처리하는 것처럼 보입니다. 그래서 저희의 코드가 동시적으로 업무를 처리하는 것에서 실패를 겪고 있는지 여부를 확인하기가 어렵습니다. 어떤 부분이 잘못 되었기에 업무시간이 누계로 나오는 것일까요? 올라프의 혜안을 나눠주시면 감사하겠습니다🥹🥲

2023-03-12 03:19 UTC, 1Consumption requested changes
고생하셨습니다.

피알을 빨리 보내는것도 중요하지만, 퀄리티있게 보내는것도 중요합니다.
이번 스텝은 메소드 역할분리, 변수 네이밍 등이 조금 아쉽습니다.

또한 `Bank`에 대한 유닛테스트가 없는게 아쉽습니다. 
계속해서 말씀 드리는거 같은데, 유닛테스트 작성하는 습관을 들이는게 중요합니다.
당장 코드를 빨리 짜는데는 도움이 안될 수 있습니다. 다만, 길게 본다면 유닛테스트를 작성하는게 필히 좋을 것입니다.

---------------------------------

아래는 고민하신 점에 대한 제 코멘트입니다.

## 1. manageClientQueue 메서드 client 생성자 분리하면서 발생하는 문제 
말씀하신대로 동작하는게 당연합니다. 현재 `Bank`는 딱 한번만 생성이 되니까요. 그러면 당연히 생성자로 받는 random 변수도 딱 한번만 생성되겠네요.
루프를 Bank 외부에서 돌리고, input도 Bank 외부에서 받아 매번 Bank를 생성하면 현재 문제는 해결될거 같습니다.

## 2. 업무는 동시적으로 처리되지만, 업무시간은 누계로 나오는 문제
지금 semaphore가 하나인게 문제같네요.

2023-03-12 03:19 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
대출 고객, 예금 고객을 각각 만들고 싶은거 같은데, 너무 복잡합니다.
1. 대출 고객이 몇 명인지 정한다
2. 총고객 수에서 대출 고객 수를 뺀다. <- 예금 고객 수
3. 업무별로 객체를 생성한다.

이렇게 하면 좀 더 코드가 깔끔해지고 간략해질거 같습니다.

2023-03-12 03:19 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +
불필요한 공백 같습니다.

2023-03-12 03:19 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>                      semaphore.signal()
메소드로 나눠주세요. 너무 길어요.

2023-03-12 03:19 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                    semaphore.signal()
이 세마포어는 value가 몇인가요?

2023-03-12 03:19 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>                      semaphore.signal()
이 세마포어는요? 혹시 value가 1인 동일한 세마포어를 공용으로 사용하고 있는거 아닌가요?
세마포어의 역할, 디스패치큐의 역할에 대해서 다시 한번 생각해보세요.

2023-03-12 03:19 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    enum BankingType {
`~Type`은 좋지 못한 네이밍입니다. swift는 모든것을 type으로 보기 때문에 뒤에 `~Type`을 붙이면 중복 네이밍입니다.

2023-03-12 03:19 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    }
`CustomStringConvertible`이라는 프로토콜에 대해서도 알아보세요.

2023-03-13 07:31 UTC, Rhode-park commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    enum BankingType {
`BankingType`을 `Banking`으로, `banking`을 `banking`으로 네이밍 수정하였습니다.

2023-03-13 07:32 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>                      semaphore.signal()
manageClientQueue() 메서드 전체적으로 수정되었습니다.

2023-03-13 07:33 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                    semaphore.signal()
예금 은행원은 2명이라 value2를 가질 수 있다고 생각합니다.

2023-03-13 07:34 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>                      semaphore.signal()
대출 은행원은 1인으로 세마포어를 사용할 필요가 없었습니다.

2023-03-13 07:34 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    enum BankingType {
해당 부분 참고하여 Banking 으로 수정하였습니다.

2023-03-13 07:36 UTC, Rhode-park commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    }
[`e15b19f`](https://github.com/yagom-academy/ios-bank-manager/pull/277/commits/e15b19f796e9d391aa72381b74f53be5ee170c82)

> CustomStringConvertible
>
> Types that conform to the CustomStringConvertible protocol can provide their own representation to be used when converting an instance to a string. 

이 프로토콜을 채택한 타입의 경우 인스턴스에 대한 설명을 `description`이라는 변수로 넣어줄 수 있습니다. 저희의 기존 코드가 `CustomStringConvertible`을 따르기에 좋은 형태이기 때문에, 이 프로토콜을 채택하여주었습니다.

2023-03-13 07:37 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
대출 고객, 예금 고객을 각각 만들지 않고 Banking타입을 랜덤으로 받아 고객을 나누는 방향으로 고객을 하나의 큐로 생성해주었습니다. 
```swift
func manageClientQueue() -> Queue<Client>  {
        var clientQueue = Queue<Client>()
        clientCount = Int.random(in: 10...30)
        
        for i in 1...clientCount {
            Client.Banking.allCases.randomElement().map {
                clientQueue.enqueue(Client(clientWaitingNumber: i, banking: $0))
            }
        }
        
        return clientQueue
    }
```

2023-03-13 07:38 UTC, Rhode-park commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>      }
[`6237a40`](https://github.com/yagom-academy/ios-bank-manager/pull/277/commits/6237a403b49ad86f8f1a33eca11ab777b49e25a9)

`manageClientQueue` 메서드를 전반적으로 수정하였습니다. 조언해주셔서 감사합니다.

2023-03-13 07:39 UTC, Rhode-park commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        var clientArray: [Int] = []
`manageClientQueue` 메서드를 전반적으로 수정하면서 이 부분이 사라졌습니다. 조언해주셔서 감사합니다.

2023-03-13 07:39 UTC, sehoong0429 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
>      }
manageClientQueue 메서드 수정하였습니다.

2023-03-13 07:40 UTC, Rhode-park commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +
`manageClientQueue` 메서드를 전반적으로 수정하면서 이 부분이 사라졌습니다. 조언해주셔서 감사합니다.

2023-03-13 08:06 UTC, Rhode-park commented
@1Consumption
안녕하세요 올라프!⛄️⛄️⛄️⛄️ 
STEP3 PR관련해서 추가적으로 질문드립니다.

# 질문 드리고 싶은 부분
## Bank를 class로 구현해야할지 struct로 구현해야할지
저희는 `ClientWaitingLine`을 제외한 모든 타입들을 struct타입으로 구현하였습니다. `Bank`, `BankManager`, `Client`가 struct로 구현되었습니다. 이 중 `BankManager`, `Client`는 struct로 구현되는게 적절하다고 생각합니다.

이유는 다음과 같습니다:

1. struct는 한 번 생성되면 immutable합니다.
값을 바꾸려면 새로운 struct를 생성해야합니다. `BankManager`는 프로퍼티를 가지고 있지 않기 때문에, 변경할 값 자체가 없습니다. `Client`는 프로퍼티를 가지고 있지만, 두 개의 프로퍼티는 고정적인 상수이고, 나머지 두 개는 `banking`에 따라 값을 반환해주는 연산프로퍼티입니다. 그래서 값이 변경될 일이 없습니다. 
2. 상속해주거나 상속받을 일이 없습니다.
struct가 class보다는 불변적이지만, 성능상의 이점이 있습니다. 그래서 상속해주거나 상속받을 일이 없으면 class보다는 struct를 사용하는 것이 좋다고 알고 있습니다.

그런데, `Bank`는 struct로 구현하는게 적절했을지 모르겠습니다.

이유는 다음과 같습니다:

**값이 변화될 필요가 있습니다.**
struct 내부의 값을 변화시키기 위해서 mutating func들을 구현하고 있는 상황입니다. mutating func을 통해 struct의 값을 바꿀 수 있지만, 클래스처럼 프로퍼티 값만 바꿔주는 것이 아니라 아예 새로운 copy를 생성하는 방식이라고 합니다. 이런 경우라면, 프로퍼티 값을 자체적으로 바꿔줄 수 있는 class가 더 적합하지 않을까 하는 의심이 듭니다.

위와 같은 이유로 `Bank`를 어떤 타입으로 구현해야할지에 대한 의문이 생기는 바입니다. 이 부분에 대해서 조언해주시거나 공부할 부분을 짚어주신다면 감사하겠습니다🥹🙏🏻

2023-03-13 12:47 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
생각하지 못한 좋은 방법이네요👍

2023-03-13 12:51 UTC, 1Consumption commented
https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes 이 문서를 읽어보세요.

swift는 기본적으로 struct를 사용하라고 합니다. 
또한 지금같은 경우는 참조를 공유할 필요가 없으니 굳이 class로 만들 이유가 없어보입니다.

2023-03-13 12:52 UTC, 1Consumption commented
추가적으로,
<img width="722" alt="image" src="https://user-images.githubusercontent.com/37682858/224707048-24c810a7-cbb0-4fef-8094-b3e4e53b4d51.png">

이 커밋에는 간략하게나마 `어떻게`가 들어가면 좋겠습니다. `어떻게`가 다 적기 너무 길다면 어쩔수 없겠지만요.

2023-03-13 12:53 UTC, sehoong0429 commented
커밋에 조금 더 신경써보도록 하겠습니다. 감사합니다.

2023-03-14 12:19 UTC, merged