은행창구 매니저 [STEP4] kaki, songjun
yagom-academy/ios-bank-manager pull request #280
Opened 2023-03-15 02:52 UTC by kimseongj

# 은행창구매니저 [STEP4] kaki, songjun
@AppleCEO
안녕하세요 도미닉! STEP4 PR입니다! 마지막 리뷰 잘 부탁드립니다!😁😁😁

## 구현 내용 및 고민한 점
### UI 구현
- 전체적인 구조를 StackView로 구현했습니다.

### Timer 구현
- Timer 클래스를 통해 타이머를 구현해주었습니다.
- DateFormatter를 사용하여 초와 분을 표현했습니다.
```swift
private let timeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "mm:ss:SSS"
        return formatter
}()
```
- `Date(timeIntervalSince1970: timeCount)`, 즉 타이머가 진행되는 시점을 과거 1970으로 지정해서 구현했습니다. 만약 현재 시간(`now`)으로 타이머를 진행시키면 현재 시간이 기본값이 되기 때문입니다.
- 시간이 흐름에 따라 label을 업데이트해주는 방법을 사용했습니다.
```swift
@objc func updateTime() {
        timeCount += 0.001
        updateTimeLabel()
}
```

### OperationQueue 구현
- 기존에 사용하던 DispatchQueue를 제거하고 OperationQueue로 구현해주었습니다.
- 초기화 기능 구현 시, 초기화를 누르면 스레드가 하던 일도 cancel이 되어야 하는데 DispatchQueue에는 이러한 기능이 없어 OperationQueue로 변경해주었습니다.

## 조언이 필요한 점
![](https://i.imgur.com/ThluwpE.png)
- OperationQueue로 변경한 이유가 한가지 더 있었는데, main 스레드에서 작업 처리 시 dispatch_semaphore_wait 및 dispatch_group_wait을 사용하는 경우 에러가 발생하여 이를 해결하기 위해서 변경해주었습니다.
- [Diagnosing performance issues early](https://developer.apple.com/documentation/xcode/diagnosing-performance-issues-early) 해당 내용에 관한 공식문서 입니다.
- 우선 순위 반전때문에 발생하는 에러라고 설명되어 있는데, 명확하게 이해가 되지 않아서 조언 주시면 감사하겠습니다 😂

2023-03-16 05:57 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
@kimseongj @kak1x 고생하셨습니다!
제 폰에서는 대출만 추가되네요~
확인 부탁드려요.

조언이 필요한 점
- 보통 저 보라색 줄은 메인 쓰레드가 아닌 쓰레드에서 View를 바꾸거나 하면 보였던 것으로 기억합니다.
- 쓰레드 관련 오류로 보이는데 공유해주신 문서를 보니 높은 QOS 작업에서 낮은 QOS 작업이 락 걸린 거로 보이네요.

2023-03-16 05:57 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Controllers/BankViewController.swift
> +        formatter.dateFormat = "mm:ss:SSS"
오... SSS는 처음 보네요~ 밀리세컨드인가요?

2023-03-16 05:57 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Controllers/BankViewController.swift
> +        bankView.processClientStackView.arrangedSubviews.forEach { $0.removeFromSuperview() }
$0 을 사용하지 않고 기본형으로 풀어서 써볼까요?

2023-03-16 05:57 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Controllers/BankViewController.swift
> +                let label = $0 as? UILabel
여기서도 $0 을 한번 지워볼까요?

2023-03-16 05:57 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +protocol BankManagerDelegate: AnyObject {
오 AnyObject 를 사용해보셨군요! 이 것은 어떤 역할을 하나요?

2023-03-16 05:57 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +            let client = Client(clientNumber: numberOfClient, requstedTask: .init(rawValue: randomNumberOfTask) ?? .deposit)
?? 으로 기본값을 줄 수 있죠.
?? 을 한번 지워보면 어떨까요?

2023-03-16 05:57 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +struct BankManager {
구조체로 BankManager 를 구현해보셨군요~ 👍 
클래스로 구현할 때와 어떤 차이가 있을까요?

2023-03-16 05:57 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +        } else if client.requstedTask == .deposit {
else if 이쁘네요!
혹시 else 를 쓰지 않고 if 만으로 이와 같은 동작을 하게 수정해 볼 수 있을까요?

2023-03-16 07:05 UTC, AppleCEO commented
이 문서를 보면 보라색 에러에 대해 설명이 좀 되어있는데요.
저도 정독해보고 내용 공유드릴게요~
https://codeburst.io/finding-bugs-using-xcode-runtime-tools-1b185f91fe0a

2023-03-16 11:16 UTC, kak1x commented on BankManagerUIApp/BankManagerUIApp/Controllers/BankViewController.swift
> +        formatter.dateFormat = "mm:ss:SSS"
넵! 밀리세컨드입니다~

2023-03-16 11:19 UTC, kak1x commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +protocol BankManagerDelegate: AnyObject {
protocol에 어떤 class를 제한할지 미리 정할 수 없는 경우에 AnyObject를 사용합니다.
이를 통해 이 protocol은 오직 class에서만 사용 가능하다 라는 뜻이 됩니다.

2023-03-16 11:19 UTC, kimseongj commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +struct BankManager {
애플에서는 특별한 경우를 배제하고는 struct 사용을 권장합니다. `BankManger`의 경우 클래스의 기능 중 필요한 기능이 없어보여 struct를 사용했습니다.

2023-03-16 11:20 UTC, kimseongj commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +            let client = Client(clientNumber: numberOfClient, requstedTask: .init(rawValue: randomNumberOfTask) ?? .deposit)
nil coaleascing을 삭제하고 enum값에 생성자를 생성하여 수정하였습니다.
608bdbad6ed14f8136561710e3a12b4dc0da58c4

2023-03-16 12:55 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
> +        } else if client.requstedTask == .deposit {
안 좋다고 하기는 그렇지만 추가 미션으로 드리기도 했습니다.
저는 else if 를 지양하긴 합니다!

2023-03-16 13:00 UTC, AppleCEO approved these changes
고생하셨습니다~ 코멘트 확인해주시면 좋겠어요!

2023-03-16 13:00 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Controllers/BankViewController.swift
> +        }
오우... 좋은데요~ 아직은 기본형에 조금 더 익숙해지면 좋겠어요!

2023-03-16 13:00 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
>          }
이렇게 작성하면 이전에 else if가 있을 때와 똑같이 동작하게 될까요? 위에 if문 도 동작하고 아래에 이 세 줄도 동작하게 되는 거 아닐까요?

2023-03-16 13:00 UTC, AppleCEO commented on README.md
> +}
오우 해결 방법을 정리해보셨군요. 저도 내일 중에 보라색 오류에 대해 댓글에 남긴 글을 번역해서 공유드릴게요!

2023-03-16 13:50 UTC, kak1x commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
>          }
if문과 else if문을 사용하면 if문이 참일 시 if문의 코드 블럭만 실행하고 else if문에
대한 참, 거짓 여부를 확인하지 않고 넘어갈 것입니다. 하지만 if문만 2번 사용하면 위에서 참, 거짓 여부를 확인했어도 아래 if문의 참, 거짓 여부를 판단할 것이기에 else if를 사용하는 것이 성능면에서 조금이라도 더 좋다고 생각되는데 도미닉의 의견을 듣고 싶습니다!

2023-03-17 04:58 UTC, AppleCEO commented on BankManagerUIApp/BankManagerUIApp/Models/BankManager.swift
>          }
오호... 그렇게 생각할 수 있겠네요. 제가 의도한 것은 
```swift
if(~~) { 
  ... 
  return 
} 

depositQueue.maxConcurrentOperationCount = 2
depositQueue.addOperation {
  processPersonalBankTask(client)
}
```

이런 식으로 작성해서 if 조건에 해당할 경우 if문 안에 코드가 실행되고 조건에 해당되지 않을 경우 아래에 코드가 else 없이 동작하는 것을  제안 드리고 싶었습니다. 이렇게 작성하는 것을 저는 선호하는데요. 어떤 차이가 있을지 한번 고민해보셔도 좋겠네요!

2023-03-17 12:08 UTC, merged

2023-03-17 12:11 UTC, AppleCEO commented
프로젝트를 완벽하게 수행했습니다. 그동안 고생하셨습니다!