은행창구 매니저[STEP4] 리지, 무리
yagom-academy/ios-bank-manager pull request #283
Opened 2023-03-16 09:41 UTC by parkmuri

@uuu1101
태태! 잘 지내셨나요! 리지&무리 STEP4 PR입니다.
이번에 UI부터 타이머까지 어느하나 쉬운게 없었습니다...🥲

그럼 코멘트 기다리고있겠습니다!

---
## 이번 프로젝트에서 적용한 기술 
- LinkedList & Node 
- Queue
- DispatchQueue
- OperationQueue
- 코드로 UI구현
- Canvas
- Delegate Pattern
- Timer
- fmod()

## 고민했던 점
### 1️⃣ Operation Queue의 사용
- 먼저 STEP3에서는 DispatchQueue를 이용하여 비동기 프로그래밍을 구현했는데, Delegate를 적용한 후 UI 업데이트를 위해 이야기를 나누다가 `초기화`버튼을 위한 DispatchQueue의 Cancel에 대해서도 의견을 나누게 되었습니다. 
그러다 문득 태태의 STEP3 코멘트 중 `OperationQueue`의 권유가 위의 이유도 포함한게 아닐까? 하는 생각이 들어 OperationQueue로 변경하여 진행하게되었습니다.    
    
### 2️⃣ 비동기처리 UI에 띄우기
- 비동기로 다른 스레드에서 처리하는 업무를 UI에 어떻게 띄워야 하는지가 이번 과제의 핵심 중 하나라고 생각합니다. 그래서 이부분을 해결하는데 오랜 시간이 걸렸는데요...! 
먼저 UIKit은 thread safe 하지 않아 Race Condition이 발생할 위험이 있기 때문에 main 스레드에서 띄워줘야 한다고 알고있습니다. 그렇기 때문에 bank에서 일어나는 데이터의 변화를 delegate로 ViewController에 전달해주고, ViewController에서 위임하여 UI에 띄워주도록 구현하였습니다.

#### 순서
  - ViewController `고객 10명 추가` 버튼 클릭
  - bank.lineUpClient() 실행
     - delegate?.sendData(of: currentClient) : enqueu되는 고객 정보를 넘김
  - bank.doTask() 실행
     - assignToBankClerk() 비동기 처리가 시작되면서 delegate를 통해 전달

```swift
struct Bank {
    
    var delegate: BankDelegate?
    // 생략
    private func assignToBankClerk(_ currentClient: Client) {
        let process = BlockOperation {
            delegate?.startTask(of: currentClient)
            bankClerk.service(to: currentClient)
            delegate?.completeTask(of: currentClient)
        }

        switch currentClient.purposeOfVisit {
        case .deposit:
            depositClerk.maxConcurrentOperationCount = 2
            depositClerk.addOperation(process)
        case .loan:
            loanClerk.maxConcurrentOperationCount = 1
            loanClerk.addOperation(process)
        }
    }
}
```

```swift
protocol BankDelegate {
    func sendData(of client: Client)
    func startTask(of client: Client)
    func completeTask(of client: Client)
}
```

- 전달받은 정보를 viewController가 화면에 업데이트

```swift
extension BankAppViewController: BankDelegate {
    func sendData(of client: Client) {
        //대기중 화면에 고객 정보 띄우기 (코드 생략)
    }
    func startTask(of client: Client) {
        //대기중에 있는 고객을 업무중으로 넘기기 (코드 생략)
    }
    func completeTask(of client: Client) {
        //업무가 완료되면 업무중 고객에서 삭제하기 (코드 생략)
    }
}
```

### 3️⃣ timer 설정 

- 프로젝트에서 앱이 시작되는 동안 걸리는 시간을 실시간으로 보여주는 기능을 구현해야 해서 처음 timer 기능을 사용해보았습니다.
실시간으로 시간을 측정해서 00:00:000 포맷에 맞춰 어떻게 구현하면 좋을까 많이 고민해보았습니다. 

#### 시간측정-시도한 내용

- 먼저 client가 10명 추가될때 타이머가 시작되어야 한다고 생각했고, ViewController에 `var startTime` 변수를 생성하여 `고객 10명 추가` 버튼이 눌릴 때 실행되는 `addTenClients()`메서드 안에 `self.startTime = Date()`를 설정하였습니다.
그리고 타이머가 시작되면 `let timeInterval = Date().timeIntervalSince(self.startTime)`를 설정하였고 현재의 `timeInterval`과 `startTime`을 비교하여 그 차이를 타이머라벨에 띄우게 되었습니다.
- 위와같이 실행하니 `고객 10명 추가` 버튼을 누를때마다 00:00:000으로 초기화되는 문제와 업무가 종료될때 타이머를 멈추게 하는 방법을 찾아야했습니다. 

#### 시간측정-수정한 내용

- 앱의 시작 종료를 `isOpened` 라는 bool 타입 변수를 만들어 구분하였습니다.
`고객 10명 추가` 버튼이 눌렸을 때, 앱이 시작됨과 동시에 `isOpened == true` 로 바뀌면서 시간을 측정하고 업무중인 고객과 대기중인 고객이 없을 때 `isOpened == false`로 바뀌면서 앱이 종료되도록 하였습니다. 
- 이때 `taskTime`을 전역변수로 두어 `isOpened == true`가 되면서 `taskTime += 0.001 `이 증가하고 이를 label에 넣어 화면에 띄웠습니다.

#### 00:00:000 포맷 맞추기

- timer를 작동시키는 메서드로` setUpTimer()`를 구현하고 selector에 들어가는 메서드인 `timeUp()` 메서드 안에서 포맷을 설정하였습니다.

```swift
private func setUpTimer() {
        self.timer = Timer.scheduledTimer(timeInterval: 0.001, target: self, selector: #selector(timeUp), userInfo: nil, repeats: true)
    }
    
@objc private func timeUp() {
    if isOpened == true {
            taskTime += 0.001
    }
    let timeInterval = taskTime
    let minute = (Int)(fmod((timeInterval/60), 60))
    let second = (Int)(fmod(timeInterval, 60))
    let milliSecond = (Int)((timeInterval - floor(timeInterval))*1000)
        
    let minuteLabel = String(format: "%02d", minute)
    let secondLabel = String(format: "%02d", second)
    let milliSecondLabel = String(format: "%03d", milliSecond)
    taskTimerLabel.text = " 업무시간 - \(minuteLabel) : \(secondLabel) : \(milliSecondLabel)"
    }
```

- 이때 `fmod(_,_)`메서드를 활용하였습니다. 이 메서드의 기능은 첫번째 인자를 두번째 인자로 나눴을 때, 딱 맞게 떨어지지 않는 나머지 부분을 반환해주는 것으로 위의 식을 사용하여 초를 기준으로 분, 초, 밀리세컨드 초를 계산하여 반환해주도록 하였습니다.
- 또한 소수점 값은 불필요하다고 생각하여 `Int`로 타입을 맞춰주고, 자릿수를 지정하기 위해 `String(format:,_)`을 사용하였습니다.

---

## 해결되지 않은 점
### 1️⃣ 기기마다 scrollView가 다르게 작동하는 현상
|<center>14</center>|<center>14 pro</center>|
|---|---|
|<img src="https://i.imgur.com/DSl07Ri.gif" width="200">|<img src="https://i.imgur.com/nq38P7O.gif" width="200">|

- 위와같이 같은 설정에서 14의 경우에는 scroll에는 문제가 없으나, 14 pro에서는 업무 중 밑의 stackView가 가로로 스크롤이 되는 현상이 발견되었습니다😭 
대기중, 업무중 밑의 각각의 스택뷰에는 동일한 attribute를 설정해주었는데 왜 이런 현상이 발생하는지 궁금합니다...!

    

## 조언을 구하고 싶은 점

### 1️⃣ view 객체 파일 분리 / 하나의 파일안에 생성 
- 먼저 요구사항에 올라온 사진을 보고 stackView를 여러개 두어야 할것같다는 생각을 했고, ViewController에서 작업 시 너무 길어질것같다는 생각을 하게되었습니다. 그래서 UI에 관련된 코드들은 따로 파일을 분리시켜 만들어 주는 방향으로 진행하게되었습니다.
- 파일을 분리시켜 작업하니 나뉘어져있어 보기에는 깔끔했지만 ViewController에서 작업 시 `queueStackView.waitingQueueStackView.waitingScrollView.waitingClientStackView.arrangedSubviews`같이 접근이 어려운 부분도 있었고, Delegate로 client에 대한 정보를 받아오고 그에 맞는 정보를 넣어줘야했기때문에 View 폴더에 분리해놓은 `ClientLabel`을 삭제하고 ViewController 내부에 `makeLabel(of: Client)`메서드를 따로 만들기도 했습니다.
   - `ClientLabel`을 삭제하지 않고 사용하는 방법도 있었지만, 결국엔 ViewController에서 고객의 목적에 따라 색상을 변경시켜준다던지, label.text를 설정해준다던지 하는 이유때문에 ViewController에서 작업을 하기로 했습니다.
- 이런 경우 객체를 분리시킨다면 어디까지 분리시켜야 할지(분리 시키되 한개의 파일 안에 혹은 뷰마다 쪼개지않고 관련있는 뷰들은 같이 생성한다던지...), 혹은 ViewController 내부에서 작업했을때의 단점에 대해 태태의 생각이 궁금합니다!
    
### 2️⃣ 업무 종료시 업무시간 멈추도록 설정
- 처음 시도했던 점은 `업무중stackView`가 비어있으면 `is
Fed == false` 조건을 걸어 업무중인 고객이 없으니 업무시간이 올라가지 않도록 구현하였습니다.
그런데 `업무중stackView`, `대기중stackView`둘다 비어있어야 제대로 작동하였고, `업무중stackView`만 비어있다는 조건을 걸게되면 다끝나지 않았는데 시간이 멈춰버리는 오류가 생겼습니다. 
- 저희가 생각한 이유는 예금 업무 종료 후 대출 업무만 남아있는 상황에서 업무가 끝난 고객은 `업무중stackView`에서 삭제되고 대기중인 대출 고객이 업무중으로 넘어오는 그 텀에 `업무중stackView`가 비어진걸로 인식해서 `isOpened == false`가 되어 다끝나지 않았는데 시간이 멈춰버리지 않을까..? 생각했습니다. 태태의 생각은 어떤지 궁금합니다. 저희가 생각한 이유가 맞을까요?

2023-03-17 20:43 UTC, uuu1101 requested changes
2주간 은행창구 매니저 하시느라 고생하셨어요 :) 👏

코드 컨벤션이 아주 보기 좋았습니다 👍
UI 그리는 것도 어려우셨을텐데 잘 그려주셨네요 ! 

몇가지 코멘트 남겨두었습니다 확인 부탁드립니다.

해결되지 않은 점
1️⃣ 기기마다 scrollView가 다르게 작동하는 현상
--- 
해당 문제를 해결하는 방법은 여러가지가 있을수 있어요.
해당 스크롤뷰의 `.isScrollEnabled = false` 로 둘 수도 있구요. 
전체를 감싸고 있는 뷰의 레이아웃을 설정해 주면 해결 될 것 같습니다.
![스크린샷 2023-03-18 오전 5 10 37](https://user-images.githubusercontent.com/49808034/226032526-41d42ebd-4404-4c64-b3e5-f8fd32d8f2e1.png)
위 스크린샷이 힌트가 될 수 있겠네요. (한쪽 ScrollView만 indicator가 존재하네요 왜그런지 한번 찾아보셔도 좋을 것 같아요.)

1️⃣ view 객체 파일 분리 / 하나의 파일안에 생성
--- 
저의 경우에는 파일을 분리하는 방식을 많이 사용을 합니다. 다만 뷰의 구조를 어떻게 가져갈지, 어떤 단위로 뷰를 쪼개는게 좋을지는 프로젝트나 주어진 화면구성에 따라 구조를 가져가고 있기 때문에 어떤것이 더 좋다라는 것은 없는것 같습니다. 
MVC 디자인 패턴에서는 ViewController 내부에서 작업하는 경우가 많습니다. ViewController가 비대해지는 단점이 있습니다. 이것은 MVC 디자인 패턴에 대해서 찾아보시면 좋을 것 같습니다 !

2️⃣ 업무 종료시 업무시간 멈추도록 설정
---
네 , 여러분들이 생각하신 부분이 맞습니다 ! :)

3️⃣ 메인스레드 클로저 약한참조
---
`unowned`는 어떤경우에 사용해야 할까요? 이 질문에 대한 답을 보시면 적절하게 사용하신것에 대한 답이 될 것 같습니다.
`weak` 와 `unowned` 를 한번 비교하여 정리해보면 좋을 것 같아요 !

2023-03-17 20:43 UTC, uuu1101 commented on BankManagerUIApp/BankManagerUIApp/BankAppViewController.swift
> +import SwiftUI
SwiftUI를 사용하신 이유가 궁금합니다

2023-03-17 20:43 UTC, uuu1101 commented on BankManagerUIApp/BankManagerUIApp/View/QueueStackView/QueueStackView.swift
> +        self.axis = .horizontal
해당 부분의 기본값은 무엇인가요?

2023-03-17 20:43 UTC, uuu1101 commented on BankManagerUIApp/BankManagerUIApp/View/QueueStackView/QueueStackView.swift
> +        self.translatesAutoresizingMaskIntoConstraints = false
해당 부분은 무엇을 위한 것일까요?

2023-03-26 01:10 UTC, yijiye commented on BankManagerConsoleApp/Model/Bank.swift
> +    private let loanClerk = OperationQueue()
- OperationQueue는 DispatchQueue를 객체지향적으로 만든 것으로 Task라 불리는 코드블록들을 캡슐화하고 객체화했다는 차이가 있습니다. 기능적으로는 OperationQueue에서는 DispatchQueue와 다르게 다양한 프로퍼티를 사용할 수 있고 스케쥴링에 용이하다고 생각합니다!

2023-03-26 01:15 UTC, yijiye commented on BankManagerUIApp/BankManagerUIApp/View/ButtonStackView/AddClientButton.swift
> +    }
view 객체는 NSCoding을 채택하고 있고 init(coder:) 이니셜라이저는 required init으로 필수생성자 이기 때문에 필요하다고 생각합니다.

2023-03-26 01:19 UTC, yijiye commented on BankManagerUIApp/BankManagerUIApp/BankAppViewController.swift
> +import SwiftUI
저희가 스토리보드 없이 앱을 구현하다보니 매번 앱을 실행하면서 UI를 확인했는데, SwiftUI의 canvas 기능을 사용하면 앱을 돌려보지 않아도 바로바로 UI를 확인할 수 있어 사용해보았습니다 👀

2023-03-26 01:23 UTC, parkmuri commented on BankManagerUIApp/BankManagerUIApp/BankAppViewController.swift
> +    @objc private func addTenClients() {
swift에서 Objective-C를 사용한다는 의미입니다.
**target-action**같은 Objective-C API는 메서드나 프로퍼티 이름을 파라미터로 허용한 다음 해당 이름을 사용하여 메서드나 프로퍼티를 동적으로 호출하여 접근합니다. 스위프트에서는 `#selector` 및 `#keyPath` 표현식을 사용해 해당 메서드, 프로퍼티 이름을 selector, keypath로 나타낸다고 합니다.
- [Apple Developer : Using Objective-C Runtime Features in Swift](https://developer.apple.com/documentation/swift/using-objective-c-runtime-features-in-swift)

2023-03-26 01:30 UTC, parkmuri commented on BankManagerUIApp/BankManagerUIApp/View/QueueStackView/QueueStackView.swift
> +        self.axis = .horizontal
`.translatesAutoresizingMaskIntoConstraints`의 기본값은 true이며, `.axis`의 기본값은 horizontal입니다. 축에 대해 기본값을 작성한 이유는 View를 파일별로 나눔으로써 혼동되는 부분이 생겨... 명시해줌으로써 헷갈리지 않기 위함이었습니다..🥲

2023-03-26 02:12 UTC, yijiye commented on BankManagerUIApp/BankManagerUIApp/View/QueueStackView/DoingTaskStackView/DoingTaskStackView.swift
> +    override init(frame: CGRect) {
공식문서를 확인해보고 아래와 같이 정의를 할 수 있었습니다.
- `override init(frame: CGRect) ` : 지정된 프레임 직사각형으로 초기화 된 뷰를 반환한다.
- `required init(coder: NSCoder)` :  주어진 언아카이버의 데이터에서 초기화된 객체를 반환한다. 

언아카이버는 인터페이스 빌더로 구현할 때, 컴파일 하는 시점에서 컴파일러가 인식할 수 있도록 코드로 변환해주는 과정으로 스토리보드로 구현하면 이미 기본값이 세팅되어 있어 `required init(coder: NSCoder)` 필요 없는 반면, 코드로 구현시 `required init(coder: NSCoder)`는 view가 NSCoding을 채택하고 있어 필수구현 해야합니다.
`override init(frame: CGRect)`는  새로운 view 객체를 만들 때 사용하는 UIView의 지정 이니셜라이저라고 생각합니다.

2023-03-26 02:21 UTC, yijiye commented on BankManagerUIApp/BankManagerUIApp/View/QueueStackView/QueueStackView.swift
> +        self.translatesAutoresizingMaskIntoConstraints = false
Autolayout을 코드로 설정해주기 위한 코드로 불필요한 곳에서는 삭제하였습니다 🙂

2023-03-26 02:35 UTC, parkmuri commented
`DoingTaskScrollView`에서 가로로 스크롤되는 부분은 `isScrollEnabled`를 이용하여  스크롤을 비활성화 해주었습니다. 태태가 말씀해주신 

>전체를 감싸고 있는 뷰의 레이아웃을 설정해 주면 해결 될 것 같습니다.

를 제대로 이해하지 못해서 사용하지 못했습니다🥲... 가장 바깥쪽에 있는 ScreenStackView 대신 레이아웃을 잡을 수 있는 View로 대체하라는 말씀이실까요?

다른 프로젝트때문에 아주늦은 코멘트가 되어버렸네요. 혹시나 여유로우실때 확인이 가능하시다면 부탁드리겠습니다🥹...!

2023-06-22 09:11 UTC, closed without merging