은행창구 매니저 [STEP 4] vetto, kokkilE
yagom-academy/ios-bank-manager pull request #284
Opened 2023-03-16 13:01 UTC by kokkilE

@havilog
안녕하세요 하비! 코낄이, 베토입니다.
어렵사리 step4 구현을 다 하고 PR 보냅니다.

## 고민했던 점 & 조언받고 싶은 점
### 1️⃣ 동시성 구현 방법
- 저희가 step4를 진행하면서 기존의 `DispatchQueue`를 사용하던 방식을 `OperationQueue`를 사용하는 방식으로 수정하였습니다. 그 이유는 한번 작업이 `DispatchQueue`에 들어가게 되면 대기중인 작업을 취소하는 방법을 구현하는 것이 마땅치 않아 대기중인 작업을 쉽게 취소하고 정지할 수 있는 `OperationQueue`의 `cancalAllOperations` 메서드를 이용하여 구현하기 위해 `OperationQueue`를 이용하여 구현하는 것을 바꾸었습니다. 초기화 버튼을 눌렀을 때 모든 작업을 정지 및 취소가 되는 것을 구현할 때 `DispatchQueue`로도 구현이 가능한 지 궁금합니다.

### 2️⃣ ViewController
* 현재 저희 코드를 보면 `BankManagerViewController`에서 `View`를 그리는 메서드들에 의해 코드 길이가 길어지며 `ViewController`가 많은 역할을 하는 것을 알 수 있습니다. 이렇게 되면 가독성도 좋지 않고 `ViewController`가 너무 무거워지는 것을 볼 수 있는데 고객정보 표현할 때처럼 `Custom View`를 만든 것처럼 `Custom View`로 하나하나 만드는 방법이 좋을까요? `View` 그리는 것을 어떻게 분리해야 좋은지 궁금합니다. 

### 3️⃣ 타이머 타입 분리
- 업무 시간을 나타내는 `UILabel`과 시간을 측정하는 기능을 포함하며 하나의 `TimerStackView`타입으로 분리하였습니다.
<img src="https://i.imgur.com/fEEPAYw.png" width=300>

### 4️⃣ Notification 주고받는 방향성
- 이벤트 전달을 양방향으로 주고받다 보니, 코드상으로 이벤트의 송수신을 추적하기 어려워진 것 같습니다.

<img src="https://i.imgur.com/1FSZN7t.png" width=600>

- 저희는 양방향으로 서로간의 전달이 필요하다고 생각해서 위와 같이 구현하였는데, 저희가 구현한 코드도 `여기서 post하는 이 이벤트를 어디서 받더라?` 고민할 때가 종종 있습니다.. :cry:
- 가독성을 좀 개선할 방법이 있을지 조언을 받고 싶습니다.

2023-03-16 14:55 UTC, havilog requested changes
> 1️⃣ 동시성 구현 방법

GCD는 취소를 지원해주지 않아서, 끝났을 때 아무 동작도 해주지 않는 방식으로 구현할 수 있을 것 같아요.

> 2️⃣ ViewController

뷰를 그리는데에 정답은 없지만,
저는
재사용이 될 가능성이 있는 뷰 => 커스텀뷰
역할이 뚜렷하고, 따로 분리되면 좋을거 같이 생긴 뷰 => 커스텀 뷰로 만들어서 뷰컨 파일에 파일 프라이빗
해당 뷰에만 종속된 버튼이나 레이블 => 그냥 뷰에 그려줌
으로 그리고 있고,
코멘트에도 남겼듯이 initializer 위쪽 부분만 UI Component를 선언하는 부분,
그 init 아래에는 view를 configure하고 event 를 핸들링하는 부분으로 나누고 있어요.

> 3️⃣ 타이머 타입 분리

코멘트로 대체할게여

> 4️⃣ Notification 주고받는 방향성

코멘트로 대체할게여

2023-03-16 14:55 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/View/ClientStackView.swift
> +final class ClientStackView: UIStackView {
상황에 따라 달라지긴 하겠지만,
커스텀 뷰의 역할은 데이터를 받아서 뷰를 보여주기만 하는게 확장성이 좋다고 생각해요.
지금은 MVC 구조이니, ViewController에서 어떤 뷰를 지우고 추가할지에 관한 `로직`이 들어가고,
커스텀뷰나 서브뷰들은 뷰의 역할만 하는게 좋지 않을까 하는 생각이 들어요.

2023-03-16 14:55 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Business.swift
> +    }
enum 자체가 String이 될 수도 있을 것 같고, `CustomStringConvertible`을 활용해보는 것도 좋을 것 같아요.

2023-03-16 14:55 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/View/TimerStackView.swift
> +    private var timer = Timer()
지금 상황에서는 조금 힘들겠지만,
위 코멘트와 같이 타이머 또한 보여주는 것과 동작하는 것은 분리되어야할 것 같아요.
또한 타이머라는 객체는 우리가 제어하기 힘든 의존성에 속하구요,
따라서 init 시점에 의존성을 주입받음으로써 테스터블하게 짜는 것도 고려해보셔야할 것 같아요.

2023-03-17 01:30 UTC, kokkilE commented on BankManagerUIApp/BankManagerUIApp/Controller/BankManagerViewController.swift
> +        addScrollView()
08bfa756ae7c1d942fce4508b039ca9d53681c06
`configureUI()` 메서드 구현하여 UI 관련 메서드 묶어주었습니다.

2023-03-17 01:31 UTC, kokkilE commented on BankManagerUIApp/BankManagerUIApp/Controller/BankManagerViewController.swift
> +            name: Notification.Name("startBankBusiness"),
08bfa756ae7c1d942fce4508b039ca9d53681c06
`Event` 타입을 생성하여 `Notification.Name`을 네임스페이스화 하였습니다.
``` swift
enum Event {
    static let startBankBusiness = "startBankBusiness"
    static let endBankBusiness = "endBankBusiness"
    static let touchUpResetButton = "touchUpResetButton"
}
```

2023-03-17 01:33 UTC, gzzjk159 commented on BankManagerUIApp/BankManagerUIApp/View/Base.lproj/Main.storyboard
> +                <viewController id="BYZ-38-t0r" customClass="BankManagerViewController" customModule="BankManagerUIApp" customModuleProvider="target" sceneMemberID="viewController">
main Storyboard를 삭제하고 SceneDelegate에서 BankManagerViewController를 생성하여 화면에 띄워주도록 하였습니다. 93577522a3f9897a8c3706ed15dc00ab1345743d

2023-03-17 01:52 UTC, kokkilE commented on BankManagerUIApp/BankManagerUIApp/Controller/BankManagerViewController.swift
> +    private func setupMainStackView() {
5d0cc2d2b792688094f838d7b87dffd13569f9a7
다음과 같이 mainStackView를 initialize 하는 시점에 설정할 수 있는 프로퍼티값을 클로저로 설정해주었습니다!
``` swift
private let mainStackView: UIStackView = {
        let stackView = UIStackView()
        stackView.axis = .vertical
        stackView.spacing = 12
        stackView.translatesAutoresizingMaskIntoConstraints = false
        
        return stackView
    }()
```

다만 상위 객체인 `view`가 필요한 설정은 클로저로 설정해줄 수 없었습니다.

``` swift
private func setupMainStackView() {
        view.addSubview(mainStackView)
        
        NSLayoutConstraint.activate([
            mainStackView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            mainStackView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
            mainStackView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
            mainStackView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor)
        ])
    }
```

2023-03-17 01:58 UTC, gzzjk159 commented on BankManagerUIApp/BankManagerUIApp/Controller/BankManagerViewController.swift
> +        bank.addNotificationObserver()
더 이상 viewController에서 실행해주지 않고 bank인스턴스가 init될 때 넣어주어 notificationObserver가 추가 될 수 있게 해주었습니다. 9f5b18c4c85b2f2f3ac4a90b10ff3586e50cfe23

2023-03-17 02:44 UTC, gzzjk159 commented on BankManagerUIApp/BankManagerUIApp/View/ClientStackView.swift
> +        guard let superScrollView = superview else { return }
0041f34939465be730596c6f5f63ca65de11c21f
stackView안에 setAutoLayout메서드를 삭제하고 ViewController에서 setupStackViewAutoLayout메서드를 생성하여 상위 뷰에서 오토레이아웃을 잡도록 하였습니다.

2023-03-17 02:57 UTC, kokkilE commented on BankManagerUIApp/BankManagerUIApp/View/ClientStackView.swift
> +        label.font = .systemFont(ofSize: 24)
의견 반영하여 tag를 주고 tag로 비교를 하는 것 보다 `client` 자체를 비교하는 의미로 읽힐 수 있도록 수정하였습니다!

``` swift
extension BankClient: Equatable {
    static func ==(lhs: BankClient, rhs: BankClient) -> Bool {
        return lhs.waitingNumber == rhs.waitingNumber
    }
}
```
``` swift
final class ClientLabel: UILabel {
    let client: BankClient
    
    init(_ client: BankClient) { ... }
    ...
}
```

2023-03-17 02:57 UTC, gzzjk159 commented on BankManagerUIApp/BankManagerUIApp/Model/Business.swift
> +    }
803056f59e8bfe675b05a20a757c7623914ba9bc
Business타입에 CustomStringConvertible을 채택하여 type을 붙히지 않고도 예금과 대출을 출력할 수 있게 하였습니다.
- 수정 전
```swift
label.text = "\(client.waitingNumber)-\(client.business.type)"
```

- 수정 후
```swift
label.text = "\(client.waitingNumber)-\(client.business)"
```

2023-03-17 03:14 UTC, kokkilE commented on BankManagerUIApp/BankManagerUIApp/Controller/BankManagerViewController.swift
> +    private func addNotificationObserver() {
Delegate, Notification, KVO 의 장단점에 대해서는 어느정도 이해를 하고 있다고 생각합니다. (closure로 전달하는 방식은 좀 더 공부해봐야 할 것 같습니다..)

- 이 프로젝트에서는 이벤트가 발생했을 때 데이터를 수신하는 객체가 한 군데 뿐이라 Delegate 패턴을 적용하는게 가독성도 좋고 적합할 수 있다고 생각했습니다.
- 그럼에도 Notification 방식으로 구현한 이유는 Notification 방식은 데이터를 주고받는 객체가 서로의 정보(메서드)를 알 필요가 없기 때문에 타입 간의 의존성이 낮아진다는 점 때문이었습니다.
- 또한 Delegate 패턴을 적용할 경우, Bank와 viewController가 서로의 Delegate를 프로퍼티로 들고 있어야 하는데, 이 부분에 대해서는 어떻게 생각하시는지 하비의 의견을 여쭙고 싶습니다 🤔

2023-03-17 09:03 UTC, kokkilE commented on BankManagerUIApp/BankManagerUIApp/Controller/BankManagerViewController.swift
> +    private func setupMainStackView() {
0e2f2b52da94c2bbb45e91fb3c08ddecb74e7dc6
`mainStackView`를 lazy var로 정의하여  initialize하는 시점에 closure를 통해 넣어주는 방식으로 수정하였습니다!

2023-03-17 09:03 UTC, gzzjk159 commented on BankManagerUIApp/BankManagerUIApp/View/ClientStackView.swift
> +final class ClientStackView: UIStackView {
8732442835e6ea466c0f494e39c07b09c6870e3f
현재 ClientStackView에서 하던 메서드들을 다시 ViewController에 넣어주고 View에서는 보여주는 역할만 하도록 코드를 수정하였습니다.

2023-03-17 09:07 UTC, kokkilE commented on BankManagerUIApp/BankManagerUIApp/View/TimerStackView.swift
> +    private var timer = Timer()
c1592989793c9ed1229eb63c09dcb3d9ea2461eb
`TimerStackView`가 수행하던 기능을 `BankTimer` 로 분리하였습니다!
`BankTimer` 내 `TimerStackView`의 delegate를 프로퍼티로 보유하도록 구현했습니다.

`TimerStackView`가 수행하던 기능을 `BankTimer`라는 모델로 분리함으로써 더 테스터블하게 되었다고 생각할 수 있을까요? 🤔

2023-03-17 11:31 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Business.swift
> +    }
```swift
enum Something: String {
...
}
```
하면 Something.rawValue와 같은 식으로도 접근할 수 있어요

2023-03-17 11:36 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankManagerViewController.swift
> +    private func addNotificationObserver() {
Notification같은 경우에는 1:N의 관계에 적합한 통신방식인거 같아요.
의존성이 낮아진다는 말은 어떤 의미인지 조금 애매한데요, 
노티를 쏠 경우 원하지 않는 객체에서 해당 노티에 접근할 수도 있고, removeObserver를 안해줄 경우 메모리릭이 발생할 수도 있어요.

상위-하위가 명확한 뷰 계층인 경우에는 delegate를 통해 전달해주는게 더 명확하지 않을까 하는 생각이 있어요.
delegate를 weak 만 신경써주면 프로퍼티로 들고 있는건 당연한거 같아요.

2023-03-19 05:47 UTC, merged