은행창구 매니저[STEP 1] Kobe, Hamg
yagom-academy/ios-bank-manager pull request #296
Opened 2023-07-11 09:25 UTC by devKobe24

은행창구매니져 [STEP 1] Kobe, Hamg
# STEP 1

안녕하세요 그린(@GREENOVER)! 🙌
이번에 은행창구매니저 리뷰를 받게 된 Kobe, Hamg 입니다.🙋‍♂️
첫 PR을 보내게 된 날이 우연히도 복날이네요 :)
맛있는 식사 시간 되시길 바랍니다.🍗 
리뷰 잘 부탁드립니다!🙇🏻‍♂️

## 고민되었던 점
1️⃣ 링크드리스트와 큐의 구현
지난 프로젝트 중 계산기 프로젝트에서 단방향 링크드 리스트를 활용하여 큐를 구현한 경험이 코비와 햄지 모두 있었습니다.
그래서 함께 회의를 한 결과 큐 내부에 링크드 리스트를 구현하는 것이 조금 더 실용적이라고 생각을 했습니다.
그러나 제약사항을 다시 꼼꼼하게 읽어본 결과 링크드 리스트를 따로 빼서 구현해야 한다는 점을 알게 되었고, 프로젝트의 목적성을 다시금 알게 되었습니다.
그 관계성에서 큐와 링크드 리스트를 분리하는 과정 속에서 고민을 많이 했던 것 같습니다.

2️⃣ XCTest 진행이 안되었던점
XCTest파일을 만들고 테스트를 진행하려고 했는데 알수없는 에러가 발생하여 문제가 되었습니다. 테스트를 하려고 진행시에 알수없는 타입이라 생각을 하게 되었고 Model로 만들었던 `Queue`, `LinkedList`, `Node` 등 모두 `Targer Membership`에서 Tests에 대한 체크를 진행하여 테스트 시에 알수있게 하게끔 진행하였고 Model을 알 수 있었기에 테스트가 진행 되었습니다.

## 조언을 구하고 싶은 점
1️⃣ 테스트 구현 과정
현재 테스트 구현과정이 콘솔 앱에서 맞게 이루어지는 궁금합니다.
알 수 없는 에러 속에서 타겟 멤버십의 타겟을 체크해가면서 해결한 테스트 구현과정이라 저희도 이것이 정확한 테스트 구현 과정인지 궁금합니다.

2023-07-11 12:13 UTC, GREENOVER requested changes
@devKobe24 @hemg2 
안녕하세요! 이번 은행창구 매니저 프로젝트 같이 하게된 그린입니다 🙇🏻
다시 한번 인사드려요~!
저또한 2주간 잘 부탁드리며 같이 프로젝트 잘 완주해봐요ㅎㅎ
우선 빠르게 구현을 해주시고 구성도 잘잡아주셔서 저도 빠르게 리뷰를 드려보겠습니다😃
***
### 칭찬 드리고 싶은 부분
- 접근 제한자 등 세밀한 부분도 신경쓰신게 돋보입니다 💯
- 전체적으로 큐를 위해 핵심적인 기능들 구현이 잘 되었어요 💯
- 커밋 메시지 깃모지 사용한거 이뻐요ㅋㅋㅋ (두분 커밋 메시지 스타일도 통일되면 좋을까 하는 의견도 있습니다) 💯
***
### 궁금하신 부분에 대한 저의 의견
- 테스트 구현 과정
  - 네! 지금 프로젝트 코드로 보았을때는 의도하신대로 테스트를 위해 각 테스트할 타입들의 타겟에 테스트를 잘 심어주셨고 현재 결과물은 이상없어 보입니다 👍
  2번 고민하셨던 부분에서 이미 왜 에러가 발생하였는지 잘 파악하고 해결하신 결과물인것 같아 크게 드릴 첨언 드릴 부분은 없어보여요ㅎㅎ
***
### 반대로 저도 궁금한 부분
- Node / LinkedList / Queue의 타입을 구조체 혹은 클래스로 설정하셨는데 각각 왜 해당 타입으로 구성하셨는지 여러분들의 이유가 궁금합니다 🙋🏻
(잘못되었다는 소리가 아니라 다양한 방법이 있고 정말 여러분들의 해당 코드 선택 이유가 궁금해서!!)
***
### 보완되면 더 좋을 부분
- 코멘트에서도 잠깐 남겼지만 현재 Queue를 위한 Linked List가 된것 같습니다🥲
물론 앞으로 프로젝트하면서 해당 기능 및 구현으로 모두 커버될 수도 있겠지만 두개를 분리하셨으니 이왕이면 Linked List는 Queue 말고도 범용적으로 사용될 수 있게 Linked List 그 자체의 기능을 더 보완해서 구현해보면 어떨까 싶어요🙋🏻
Linked List의 장점은 무엇인지 어떤 특징들이 있는지를 더 살펴보면서 범용적으로 기능을 다 담아보면 어떨까요~?
- 테스트 코드 너무 잘짜주셨어요!
욕심을 조금 더 내보자면 더 다양한 케이스 (실패 등)도 만들어보면 훨씬 보완될것 같습니다!
요 부분은 차차 스텝하면서 해보셔도 충분합니다 🫠
***
다시 한번 스텝 1 구현하시느라 고생 많으셨고 너무 잘하셨네요!
물론 아시겠지만 제 리뷰는 정답이 아닌 하나의 의견으로 보시고 꼭 검증해보시면서 타당한것은 받아들이고 두분의 코드 스타일이나 이유에 맞지 않다면 저를 설득시켜주시면서 킵고잉 해주셔도 됩니다🙌
우선 조금 더 보완해볼 여지가 있어 리퀘스트 체인지로 드릴께요!
언제든 리뷰 재요청을 해주시면 됩니다~

2023-07-12 01:02 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    var next: Node<T>?
#### 🙋‍♂️ 답변
- `var next: Node?` 로 선언시 타입의 안전성이 보장되지 않습니다. Node 인스턴스의 `next` 속성이 동일한 제네릭 타입 `T`를 가진 다른 Node 인스턴스를 가리키지 않고, 임의의 제네릭 타입을 가질 수 있는 Node 인스턴스를 가리킬 수 있습니다. 예를 들어, 제네릭 타입 `T`의 값이 `Int`인 Node 인스턴스의 `next` 속성이 `String` 타입의 값을 가진 Node 인스턴스를 가리킬 수도 있습니다.

- 단방향 링크드 리스트로 큐를 구현함으로써 이전 노드의 정보는 알 필요가 없다고 판단하였습니다.

2023-07-12 01:02 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +	mutating func dequeue() -> T? {
- 너무 좋은 방향 제시 감사합니다 추후에 스탭을 진행하면서 어려움을 느낄 수 있었던 부분에 대하여 방향을 잡아주셔서 스탭을 잘 진행해 나아갈수 있을 것 같습니다 :)
- 지금 어떠한 에러인지 잘모르고있어 추후에 명확한 에러 구문을 알게되면 에러타입를 추가하여 진행하도록하겠습니다!!

2023-07-12 01:02 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func appendNode(_ value: T) {
#### 🙋‍♂️ 답변
- insert, count 등 메서드 추가 진행하겠습니다!

2023-07-12 01:03 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            head = nil
- `removeFirst()`의 경우 head의 value를 리턴해주는 함수입니다.
    - 1. head의 value를 guard let을 활용하여 가져옵니다 없을 경우 nil을 리턴합니다.
    - 2. head의 위치를 head의 next로 변경해줍니다.
    - 3. isEmpty를 확인하여 head와 tail이 있는지 확인하고 없다면 head와 tail에 nil을 할당합니다.
    - 4. guard let을 활용하여 가져온 head의 value를 리턴합니다.
- isEmpty가 true를 리턴해주는 경우는 head가 nil 경우입니다. 만약 isEmpty를 먼저 확인하지 않고 `removeFirst()`를 사용할 경우에 isEmpty를 확인할 필요가 있다고 생각했습니다. 그래서 isEmpty를 확인하는 로직을 넣어주었습니다.

2023-07-12 01:03 UTC, devKobe24 commented on BankManagerConsoleApp/BankMangerQueueTests/BankMangerQueueTests.swift
> +    var sut: Queue<Int>!
#### 🙋‍♂️ 답변
- 유닛테스트의 조건 중 빠른 테스트의 구현을 위하여 강제 언래핑을 사용하였습니다. 또한 성공하는 케이스에서 강제 추출을 사용했을 때 옵셔널 바인딩에 실패하여 에러가 발생한다면 그것대로 에러를 잡아낸 것이라고 생각하여 사용해도 괜찮다는 생각이 들어 사용했습니다.
    - 강제 언래핑을 하지않고 진행하려고했을경우에 바인딩을 해야할꺼같아 테스트 함수내에서 바인딩을 진행하여 사용하게되 었습니다 이렇게 진행해도 될까요??(아래의 코드내용이 있습니다.)
    - 테스트 코드에서 강제 언래핑을 지양해야 하는 이유가 무엇인지 궁금합니다~? 🙌


```swift
var sut: Queue<Int>?
func test_5를_추가했을때_첫번째값이5인지() {
        //given
        guard var sut = sut else { return }
        let input = 5
        //when
        sut.enqueue(input)
        //then
        XCTAssertEqual(input, sut.peek)
    }
```

2023-07-12 01:04 UTC, hemg2 commented on BankManagerConsoleApp/BankMangerQueueTests/BankMangerQueueTests.swift
> +
- import를 한 부분에 있어 개행을한번하고 타입작성을 진행하려고했습니다. 다른부분에 있어 이부분과 같이 맞추도록 하겠습니다.

2023-07-12 01:05 UTC, devKobe24 commented on BankManagerConsoleApp/BankMangerQueueTests/BankMangerQueueTests.swift
> +    func test_5를_추가했을때_첫번째값이5인지() {
#### 🙋‍♂️ 답변
- 테스트 코드의 메서드명을 한글로 작성하게 된다면 명확하게 어떤 테스트인지 전달할 수 있다고 생각합니다. 영문으로 작성시 한글로서 전달할 수 없는 부분을 조금 더 디테일하게 그 뜻을 전달할 수 있다고 생각합니다.

2023-07-12 01:05 UTC, hemg2 commented on BankManagerConsoleApp/BankMangerQueueTests/BankMangerQueueTests.swift
> +        XCTAssertEqual(input, dequeue)
- 테스트를 조금 더 추가하여 보완했습니다 감사합니다 🙌

2023-07-12 01:42 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            head = nil
아하 상세한 설명 덕분에 이해했습니다! 감사해요 👍👍

2023-07-12 01:48 UTC, GREENOVER commented on BankManagerConsoleApp/BankMangerQueueTests/BankMangerQueueTests.swift
> +    var sut: Queue<Int>!
답변주신것처럼 무조건 강제 언래핑을 테스트 코드에서 지양해서 사용할 필요는 당연히 없습니다!
특히 바인딩 실패로 에러를 캐치하는것도 의도라면 찬성입니다.
테스트 코드뿐 아니라 실제 코드에서도 강제 언래핑을 의도적으로 사용하는 경우도 있지만 에러 캐치는 다른 방법으로 가져가면서 바인딩을 사용하도록 구현하는 습관을 들이는게 추후에 도움이 될 것 같아서 말씀드렸습니다~!🙋🏻
즉, 무조건 지양해야한다가 아닌 꼭 강제 언래핑을 사용하지 않아도 된다면 가급적 지양해보자 라는 취지입니다~ㅎㅎ

2023-07-12 01:49 UTC, GREENOVER commented on BankManagerConsoleApp/BankMangerQueueTests/BankMangerQueueTests.swift
> +    func test_5를_추가했을때_첫번째값이5인지() {
답이 정해지지 않은 부분에 생각을 말씀해주셔서 감사해요ㅎㅎ
현재 두분의 프로젝트와 팀구성에는 한글이 가장 적합하다고 생각합니다!
나중에 글로벌한 팀원들과 협업을 할때는 영문 작성이 필요하기에 영문으로도 디테일하게 전달할 수 있는 방법을 생각해봐도 좋을것 같습니다🙋🏻

2023-07-12 02:04 UTC, devKobe24 commented
### Node / LinkedList / Queue의 타입을 구조체 혹은 클래스로 설정하셨는데 각각 왜 해당 타입으로 구현하셨나요? 
#### 답변 🙋‍♂️
- Node를 클래스로 구성한 이유는 참조 타입의 특성을 활용하기 위해서 입니다. 단방향 링크드 리스트는 Node 간의 연결을 나타내는 구조 이므로, 각 노드가 다음 노드를 참조할 수 있어야 하기 때문입니다.
- LinkedList와 Queue를 구조체로 구성한 이유는 Swift의 기본 선호사항이 값 타입인 구조체이기 때문입니다. Swift는 구조체를 사용하도록 권장합니다. 그 이유는 불변성, 스레드 안정성, 성능이 있습니다 또한 Linked List와 Queue를 딱히 다른곳에서 상속 받을 곳이 없기 때문에 구조체로 선언했습니다. 값을 참조 할 필요성이 없다고 생각되었습니다.

2023-07-12 02:12 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func appendNode(_ value: T) {
- 추가적으로 insert, count 을 테스트할 수 있는 함수를 만들어 진행해 봤습니다. 하지만 지금 count 같은 경우에는 Queue도 쓰일 거 같은데 inset 같은 경우 Queue 타입에서는 안 쓰이는 거 같아 Queue 타입에는 추가하지 않고 Linked에서만 추가 진행하여 커밋을 진행했습니다. 혹시 이 부분에 대해서 조언을 얻을 수 있을까요? Queue에도 추가를 해야 할지? 아니면 Linked에서 두고 추후에 필요로 할 때 추가를 진행하거나? 따로 Linked 타입의 인스턴스를 생성하여 진행해야 할지 의문이 생깁니다.

2023-07-12 02:15 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func appendNode(_ value: T) {
별개로 생각하면 좋을것 같아요!
큐는 순차적이니 LinkedList에서만 지금 구현하신것처럼 가면 될것 같습니다👍

2023-07-12 02:16 UTC, GREENOVER commented
@devKobe24 
명확한 이유와 답변 감사해요!
리팩토링이 완료된 후 아실 수 있겠지만 리뷰 재요청을 원하시면 우측 상단 Reviewer부분에서 
![스크린샷 2023-07-12 오전 11 16 28](https://github.com/yagom-academy/ios-bank-manager/assets/72292617/bf61f282-7893-4035-8098-cde56aabd6fd)
리프레쉬 버튼을 눌러주시면 감사하겠습니다ㅎㅎ

2023-07-12 03:56 UTC, GREENOVER approved these changes

2023-07-12 03:56 UTC, merged