은행창구 매니저 [STEP 2] Kobe, Hemg
yagom-academy/ios-bank-manager pull request #305
Opened 2023-07-14 00:56 UTC by devKobe24

# STEP 2

안녕하세요 그린(@GREENOVER)! 🙌
벌써 두 번째 PR입니다.
요즘 장마가 무섭습니다.
항상 건강과 비 조심하십시오.
이번 리뷰도 잘 부탁드립니다!🙇🏻‍♂️

## 고민되었던 점
1️⃣ 시간 체크
처음에는 고객 수의 0.7배를 곱하여 시간을 구하는 방법으로 시간을 구했습니다.
그러나 그 방법은 정확한 시간을 구하는 방법이 아니라고 생각했습니다.
그래서 고민을 많이 한 결과 `TimeCheck`라는 메서드를 따로 만들게 되었습니다.

2️⃣ Queue의 활용
DispatchQueue를 사용해야 할 지 혹은 자체적으로 구현한 Queue를 활용해야하는지 고민이 많았습니다.
스텝 핵심 경험과 저희가 만든 Queue의 목적성을 곰곰히 생각해보니 Queue를 활용하는 것이 옳다고 생각하여
자체적으로 구현한 Queue를 사용하게 되었습니다.

## 조언을 구하고 싶은 점
🙋‍♂️ 이번 스텝에서 OperationQueue나 DispatchQueue를 사용했다면 어디에 어떻게 적용했으면 좋았을까요?
접근 방법과 감이 잘 안잡혀서 조언을 구하고 싶습니다 🙌

2023-07-14 03:38 UTC, GREENOVER requested changes
@devKobe24 @hemg2 
두분 스텝2도 잘 완성해주셨네요!
고생 많으셨습니다 🎉🎉🎉
스텝 2에서는 크게 로직적인 부분을 중점적으로 보면서 확인했어요ㅎㅎ
리뷰에 대해 언제든 의견이 다르거나 확고하신 부분이 있다면 전달 부탁드립니다!
***
### 칭찬 드리고 싶은 부분
- 에러 처리를 생활화 하시는 점 💯
- 전체적인 로직 플로우가 이해가 잘되도록 객체지향적으로 설계하신 점 💯
***
### 고민하시는 부분에 대한 저의 의견
- 우선 현재에서는 크게 DispatchQueue 사용을 고민하실 필요는 없어 보입니다.
왜냐하면 고객도 동일한 업무로 순차적으로 들어오고 은행원 조차도 1명이기에 비동기로 처리하거나 하는 경우가 없기 때문이죠.
그렇기에 현재 스텝2에서는 스텝1에서 만드신 큐를 이용하는것이 적절하다고 생각해요!
이제 앞으로 나올 스텝들에서 어떤 요구사항에서는 DispatchQueue를 통해 비동기로 처리하는것도 분명 있을 수 있으니 그때가서 찐하게 겪으시면 될것 같습니다🙃
***
### 보완되면 좋을 부분
- 현재 스텝 1에서 만드신 Queue가 아닌 LinkedList를 사용하신것 같아요 🤔
큐를 활용해보면 어떨까요~?
- 파일들이 점점 늘어나는데 목적에 맞게 그룹핑 시키면 더 파일 구조를 빠르게 캐치할 수 있을것 같아요 🙋🏻
(요참에 불필요한 파일이 있다면 제거해보시는것도 좋아 보입니다 👍)
***
코멘트가 쪼오금 많긴 한거 같은데... 정말 궁금해서 여쭤보는것도 많으니 편하게 봐주시면 좋겠습니다 ㅎㅎ..
우선 보완될 부분이 있다고 판단되어 리퀘스트 체인지 드릴께요..!
언제든 편하게 리팩토링 후 리뷰 재요청 해주시면 감사하겠습니다 😊

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		let numberOfCustomers = Int.random(in: 10...30)
추후 확장성을 위해 BankService의 프로퍼티와 이니셜라이저로 요런 변경될 친구(고객 수)들은 그쪽에서 관리하는것은 어떨까요~?

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		print("은행 업무 시작")
이런 프린트문에 들어갈 문자열들을 NameSpace처럼 한곳에서 관리가 된다면 추후 유지보수 시 더 쉬울것 같은데 어떠신가요~?

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +class Customer {
클래스인 이유가 궁금합니다~🙋🏻

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +		self.user = id
user/id가 달라 조금 혼동인데 고객은 몇번째 손님인지만 알면된다면 waitingNumber와 같은 그런 느낌의 비슷한 네이밍으로 명확하게 가져가는것도 좋을것 같아보입니다 🙋🏻

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +	func start() {
메서드 정의 및 구현 순서 스타일을 어떻게 두분은 가져가시는 편인가요~?
예를들어 현재 generate > process > > printMenu > start 순으로 실제 메서드 흐름 호출 순서가 아닌 종속을 가진 순으로 선언되어 있는것 같아서 어떤 기준으로 가져가시는지 궁금해서 여쭤봐요 🙋🏻

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +				totalCustomers = currentCustomer.user
정말 만약에 고객이 20명이고 나중에 20번째 고객이 19번째 고객보다 긴급으로 빨리 할 경우 (실생활에서 종종 일어날 수도..) 있는 경우에는 업무 마감 안내 시 19명의 고객처리 했다고 인지될것 같은데,
그보다 이미 generateCustomerQueue로 고객의 총 숫자를 판단해왔을텐데 업무 종료되면 그 숫자를 반환해주는게 심플하지 않을까 싶어요🤔

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		let banker = Banker()
추후 여러명의 뱅커가 같이 업무를 한다면..!?
스텝2 요구사항에 아래와 같이 N명의 뱅커를 위한 타입 구현이 명세되어 있는데 현재 코드에서는 그 부분이 누락된것 같아요🫠
![스크린샷 2023-07-14 오후 12 13 06](https://github.com/yagom-academy/ios-bank-manager/assets/72292617/7c19c033-ed8a-4ec8-a366-0b9a721c0b29)

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomers)명이며, 총 업무시간은 \(workTime)초입니다.")
0.7초씩 업무 시간을 잡았지만 실제로 시간이 흐른건 예를들어 고객이 14명이면 9.8초가 아닌 9.86초로 잡히는건 왜 그럴까요~?

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/InputError.swift
> +    case invalidInput
`InputError.invalidInput`으로 호출될텐데 input이 뭔가 중복되는 느낌이라, invalid로 충분하지 않을까 싶어요.
왜냐하면 우리는 모두 이 에러가 InputError에서 발생한 에러로 명확하게 알고 있을테니 말이죠 🙃

2023-07-14 03:38 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +	private func generateCustomerQueue() -> LinkedList<Customer> {
스텝 1에서 만들어진 Queue를 사용하지 않는 이유가 있으신가요~?

2023-07-14 10:10 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +class Banker {
#### 답변
- 고객의 업무가 끝난점에 있어서 다른곳에서도 알아야한다는생각에 class로 우선 참조를넣어야 겠다는 생각으로 진행을 하게되었습니다. 결과적으로 동작이 완성된 프로그램을 봤을땐 하나의 지점에서만 이 타입을 받아 사용하면 되는 점이라 값 타입인 struct로 사용해야 할꺼같아 변경을 진행 했습니다.

2023-07-14 10:11 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +    func processCustomer(customer: Customer) {
#### 답변
- 네 알겠습니다 기존 `processCustomer`에서 은행원이 은행 업무를 처리한다는 느낌으로  `processBankerTask` 로 변경을 진행했습니다.

2023-07-14 10:11 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +	private func generateCustomerQueue() -> LinkedList<Customer> {
- Linked를 테스트를 해보고 Queue로 변경했어야 했는데 이부분에 있어 누락이 있었던거같습니다. 이부분 Linked -> Queue 로변경 진행했습니다.(감사합니다!🤩)

2023-07-14 10:12 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +				banker.processCustomer(customer: currentCustomer)
#### 답변
- 말씀 주신대로 시작 알림 / 일처리 시간 / 업무 종료 알림 이 세가지를 은행원이 주체가되어 처리해야 하는것 같습니다. 나중에 다양한 종류의 업무와 업무 처리 시간이 모두 다를 경우 각각 다른 은행원을 두어 처리해야 하기 때문입니다.

2023-07-14 10:12 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/InputError.swift
> +    case invalidInput
- 네 알겠습니다 수정 진행했습니다. 감사합니다!😆

2023-07-14 10:12 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		var isExit: Bool = true
#### 답변
- 아하 반대로 생각을 하고 작성을 하게된것 같습니다. 수정하여 변경 진행하겠습니다!

2023-07-14 10:12 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomers)명이며, 총 업무시간은 \(workTime)초입니다.")
- `timeCheck` 메서드에서 시간을 계산한 후 `numberFormatter`를 사용하여 `String` 값으로 리턴해줍니다. 그 과정에서 소숫점 뒤 둘 째 자리까지 나올 수 있도록 `maximumFractionDigits`을 2로 설정을 해주었습니다.

2023-07-14 10:13 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		let banker = Banker()
- 감사합니다! 프로퍼티를 생성하여 은행원을 변경 할 수 있도록 진행했습니다.

2023-07-14 10:13 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +				print(error)
#### 답변
```swfit
catch let error as InputError {
                print(error.localized)
            } catch {
                print(error.localizedDescription)
            }
```
- 타입캐스팅을 통해서 에러를 알수있게 변경하여 진행했습니다!

2023-07-14 10:14 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/TimeCheck.swift
> +}
#### 답변
- 실제로 의미가 있는 코드는 아닌것 같습니다 따로 에러처리를 할 수 있도록 수정 및 보안하겠습니다.

2023-07-14 10:15 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +let bank = BankService()
#### 답변
- 접근 제한자를 설정하도록하겠습니다.

2023-07-14 10:15 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +class BankService {
#### 답변
- 참조 타입이 아닌 값타입으로 변경 진행했습니다. 생각이 부족했습니다!

2023-07-14 10:15 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +				totalCustomers = currentCustomer.user
```swift
 private func processBankWork() {
        var customerQueue = generateCustomerQueue()
        let customerCount = customerQueue.count
        ........
        let workTime = timeCheck {
              ..........
                print("\(currentCustomer.user)번 고객 업무 시작")
                Thread.sleep(forTimeInterval: sleepTime)
                banker.processCustomer(customer: currentCustomer)
                
            }
        }
        print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(customerCount)명이며, 총 업무시간은 \(workTime)초입니다.")
    }
```

- while문으로 들어가면 `dequeue`에 의해 카운트 값이 -1 로 계속 감소하기때문에 들어가기전인 `enqueue`상태의 카운트 값을 표현하면 될꺼같아 상수를 만들어 나타낼수있도록 진행했습니다.

2023-07-14 10:15 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		let numberOfCustomers = Int.random(in: 10...30)
#### 답변
```swift
private var numberOfCustomers: Int = 0
    
    init(numberOfCustomers: Int) {
        self.numberOfCustomers = numberOfCustomers
    }
```

```swift
let bank = BankService(numberOfCustomers: 10)
bank.start()
```
- 이렇게 변경을 진행하였는데요 인스턴스 생성시에 고객 수를 정하여 관리하도록 하는게 맞을까요?

2023-07-14 10:15 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +	func start() {
- 정리를 했어야했는데 실수가 있었습니다 객체 안에서 호출되는 순서로 메서드 나열하는방식으로 기준을 정하여 진행 하도록 하겠습니다!

2023-07-14 10:16 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		print("은행 업무 시작")
#### 답변
- 따로 enum으로 NameSpace를 관리하도록 하겠습니다.

2023-07-14 10:16 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +		self.user = id
- 아하 네 알겠습니다 사용할때의 가독성을 위해 `waitingNumber`로 변경을 진행 했습니다!

2023-07-14 10:18 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +class Customer {
#### 답변
- 메서드에서 랜덤한 고객의 수가 나오기때문에 창구 업무를 할때 값타입이 아니라 참조타입을 해서 서로(고객수가 줄어드는것에 있어) 알아야한다고 생각을 했었습니다.

2023-07-14 10:37 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		let numberOfCustomers = Int.random(in: 10...30)
요렇게 기본값을 두고 generate메서드 같은곳에서 해당 고객의 데이터를 넣어줘도 괜찮을것 같아요!
초기값을 0으로 주는게 거슬린다면 옵셔널로 초기에는 고객 값이 아예 없어도 되구 스타일의 차이로 가져가면 좋을듯해요!
말씀드린 핵심은 여러 메서드에서 사용되는 프로퍼티들은 전역적으로 (현재는 해당 generate 메서드를 process에서 불러 사용하기에 영향은 없지만) 가도 관리가 좀 더 편하지 않을까해서 말씀드렸습니다~!

2023-07-14 10:40 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +class Customer {
음 요건 단순한 고객 타입 같은데 말씀하신 답변은 전체 고객의 줄 같은 느낌, 고객 큐 같은 느낌으로 이해가 되는데요.
현재 큐를 활용하는곳이 없는데 CustomerQueue와 같은걸 구성해서 실제 BankService에서 사용하는 형태는 어떤가요?

2023-07-14 10:41 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +class Customer {
즉, 위 Customer는 각각의 단일 고객으로 구현을 이해했는데 그렇다면 단일 고객들에서 고객수가 줄고 있거나 참조가 필요한 경우가 있을까 합니다..!

2023-07-14 10:43 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +		print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomers)명이며, 총 업무시간은 \(workTime)초입니다.")
넵 이해했습니다~!
제가 여쭤봤던건 0.7초씩 14명이면 딱 9.8초 소수점 2자리까지 나온다면 9.80초가 되야 할것 같은데 왜 9.86초로 계산되는지의 이유를 여쭤봤습니다ㅎㅎ

2023-07-14 23:47 UTC, GREENOVER approved these changes
리팩토링 수고하셨습니다!
답변드린것에 대해 재답변 사항들과 새 리뷰에 대해서는 다음 스텝에서 충분히 고민해보시고 수정해봐도 될 것 같아 어프로브 하겠습니다~
다음 스텝도 화이팅이에요!

2023-07-14 23:48 UTC, merged

2023-07-19 03:06 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Model/TimeCheck.swift
> +public func timeCheck(_ block: () -> Void) -> String {
은행 업무 시간 자체를 체크하는 것이 가장 핵심적인 비즈니스 로직이라고 생각했기 때문에 모델에 폴더링 했습니다.

2023-07-19 03:07 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Model/Enum/BankManagerNameSpace.swift
> +enum BankManagerNameSpace {
BankManager 내부에서만 사용하기 때문에 그 하위 폴더링 구조로 만들었습니다.