은행창구 매니저 [STEP 2] yetti, redmango
yagom-academy/ios-bank-manager pull request #309
Opened 2023-07-14 14:09 UTC by redmango1447

안녕하세요 줄라이!(@July911)
PR이 조금 늦었습니다 
기능 분리를 하는데 많은 고민을 했고 아직 많이 부족합니다 ㅠㅠ
잘 부탁드립니다!

## 공부한 내용
### 1. **sync 와 async 의 차이는?**
    - 동기(Synchronous) 
       - 작업이 끝나기를 기다리는 것
           ex) 1의 작업이 끝난뒤 2의 작업을 시작한다
       - 즉 모든 작업이 순차적으로 일어난다.
       - 순차적으로 진행되기 때문에 설계가 간단하고 직관적이다
    - 비동기(Asynchronous)
        - 작업이 끝나기를 기다리지 않는 것
            ex) 1의 작업이 끝나지 않았는데 2의 작업을 시작한다
        - 즉 모든 작업을 동시에 진행한다.
        - 동기에 비해 설계가 복잡하다.(아마 끝나는 타이밍이 제각각인것 때문인 것 같습니다.)

### 2. **[weak self]는 무엇인가?**
- 메모리 누수의 해결책 중 하나로 순환참조를 방지하기 위해 사용되는 키워드입니다. 보통 클로저 내부에서의 약한 참조를 나타냅니다. swift에선 대부분의 참조 문제를 ARC로 해결이 가능하지만 2개 이상의 객체가 서로를 강한 참조하고 있는 경우에 메모리 누수가 발생할 위험성이 있고 그런 위험성이 예상될 때 [weak self]를 사용해줍니다. 보통 비동기 작업에서 [weak self]를 사용하여 클로저 내에서 self에 접근하는 경우가 많습니다. 이를 통해 메모리 누수를 방지하고 앱의 성능과 안정성을 향상시킬 수 있습니다.
(여러 문서와 개념들을 찾아보긴 했지만 아직 사용해본 적이 없어 완벽히 이해는 하지 못했습니다. step 3에서 순환참조의 문제가 발생하면 사용해보도록 하겠습니다!)

### 3. **DispatchQueue 는 무엇인가?**
- `DispatchQueue`는 `GCD`를 사용하기 위한 대기열로,`GCD`기술의 일부입니다.
`DispatchQueue`는 크게 `Serial Queue`와 `Concurrent Queue` 두 가지로 구분할 수 있습니다. `Serial`은 단일 스레드에서만 작업을 처리하고, `Concurrent`는 다중 스레드에서 작업을 처리합니다.
(`GCD`는 `Grand Central Dispatch`의 약자로 멀티 코어 환경과 멀티 스레드 환경에서 최적화된 프로그래밍을 할 수 있도록 애플에서 개발한 기술입니다.)
- 우리는 이 Queue에 작업을 추가해주기만 하면 시스템은 알아서 스레드를 관리하여 작업을 처리하도록 도와주기 때문에 아주 편하고 강력한 기능입니다.
- DispatchQueue에 작업을 넘길 때 `2가지`를 꼭 정해주어야 합니다.
    1. `단일 스레드(Serial)`를 사용할 것인가, `다중 스레드(Concurrent)`를 사용할 것인가
    2. `동기로 작업(sync)`을 처리할 것인가, `비동기로 작업(async)`을 처리할 것인가

## 고민했던 점
### 1. Bank와 BankManager의 역할분리
- 기존에 존재하던 파일인 `BankManager`와 새롭게 정의한 `Bank`파일의 역할에 대해 고민하였습니다. 실제 은행에서 필요한 기능들과 프로그램 내에서 그 기능들을 수행하기 위한 작업을 `BankManager`에서 해주기를 원했습니다. 하지만 실제로 총 고객을 세는 `finishedCustomerCount` 메서드나 총 업무시간을 세는 `check`메서드 등의 위치가 모호했습니다. 최종적으로 `Bank`파일 내부에 구현해주었습니다.

### 2. 오늘 업무처리한 고객의 수를 큐에서 가져와야 할지 카운트를 해줘야할지
- 요구사항에 `업무처리한 고객의 수`라고 써 있지만 또 다른 사항엔 `모든 고객의 업무가 끝나야 은행 업무를 마무리한다`는 조건 때문에 처음엔 `고객의 수 = 업무처리한 고객`으로 받아들였습니다. 그래서 `bankQueue`에서 `count`를 반환하는 메소드를 추가하려했지만 혹시 고객이 업무를 보지 못하고 순번이 지나가는 상황이 발생하면 `고객의 수 ≠ 업무처리한 고객`이기 때문에 별도로 카운트를 해주기로 했습니다.

## 조언이 필요한 점
### 1. 은닉화 관련하여
- 타입의 프로퍼티를 private으로 설정 후 이니셜라이저를 이용해 값을 주입해주고 접근을 차단하는 방식이 좋은 방식인지 이외에 메서드를 활용한 은닉화 방법 말고 또 어떤 은닉화 방식이 있는지 궁금합니다.

2023-07-16 11:59 UTC, July911 requested changes

2023-07-16 11:59 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    mutating private func check(to taskTime: Double) {
이름이 모호한 것 같습니다.

2023-07-16 11:59 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    mutating private func finishedCustomerCount() {
네이밍이 잘 된게 맞을까요 ?

2023-07-16 11:59 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                  let taskTime = bankers[0].task(currentCustomer) else {
같은 의미긴 하지만 bankers[0] 보다는 first 가 더 좋아보이네요.

2023-07-16 11:59 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +    mutating func task(_ customer: Customer) -> Double? {
task(_ customer: Customer) -> Double?
이름과 리턴값이 전혀 매치가 안되네요.

2023-07-16 11:59 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    mutating func receiveQueueNumber(queueNumber: Int) {
init에서 넣을수는 없었나요 ?

2023-07-16 11:59 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +let test = BankManager()
이름이 test인가요 ?

2023-07-16 11:59 UTC, July911 commented on BankManagerUIApp/BankManagerUIApp/BankManager.swift
> +        var isBankOpen: Bool = true
isBankOpened 가 맞지 않을까요 ?

2023-07-16 11:59 UTC, July911 commented on BankManagerUIApp/BankManagerUIApp/BankManager.swift
> +        var bank: Bank = Bank(bankers: bankers)
여긴 왜 타입이 들어가있죠 ?

2023-07-16 11:59 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private var bankers: [Banker]
bankers 는 변하나요 ?

2023-07-16 12:03 UTC, July911 commented
1. sync 와 async 의 차이는?
2.  [weak self]는 무엇인가?
3. DispatchQueue 는 무엇인가?

이 세가지 질문들에는 잘 대답해 주신 것 같습니다. 
또한 로직적인 부분이나 역할분리도 잘 해주신 것 같습니다. 
하지만 전체적으로 코드가 안읽히는 것 같습니다. 
그 이유는 너무 모호한 네이밍과 과한 축약이 들어간 것 같습니다. 
꼭 수정 부탁드립니다.  

1. 은닉화 관련하여
타입의 프로퍼티를 private으로 설정 후 이니셜라이저를 이용해 값을 주입해주고 접근을 차단하는 방식이 좋은 방식인지 이외에 메서드를 활용한 은닉화 방법 말고 또 어떤 은닉화 방식이 있는지 궁금합니다.

 이외에 라는 단어가 잘 이해가 안됩니다. 접근제어자를 달아줘서 외부에서 접근이 안되게 한다거나 set만 안되게 한다거나의 방식으로 충분히 잘 해주신 것 같습니다.

2023-07-17 08:39 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    mutating private func check(to taskTime: Double) {
checkWorkTime이라는 네이밍으로 수정했습니다. 추가적으로 매개변수로 taskTime을 받지않고 Banker타입을 받아와서 Banker타입에서 정의한 notifyWorkTime메서드를 통해 총 업무시간을 계산할 수 있도록 수정해주었습니다.

2023-07-17 08:40 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    mutating private func finishedCustomerCount() {
메서드라는 점을 고려해 동사로 시작할 수 있도록 countFinishedCustomer라는 이름으로 수정해주었습니다.

2023-07-17 08:40 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +                  let taskTime = bankers[0].task(currentCustomer) else {
first로 수정해주었습니다!

2023-07-17 08:40 UTC, redmango1447 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private var bankers: [Banker]
지금의 요구조건으로 생각해본다면 변하지 않을것으로 예상되기에 let으로 수정해 주었습니다.

2023-07-17 08:41 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Banker.swift
> +    mutating func task(_ customer: Customer) -> Double? {
기능 분리를 통해 workTime만 리턴해주는 메서드를 생성하고 task메서드에서는 반환값이 없도록 수정해주었습니다. 추가적으로 task라는 네이밍도 어떤 task인지 명시되있지 않아서 동사적인 느낌보다 명사적인 느낌으로 와닿을 수 있을 것 같아 work라는 동사표현으로 수정해주었고 프로그램 내에 전체적인 표현도 task에서 work로 수정해주었습니다.

2023-07-17 08:41 UTC, redmango1447 commented on BankManagerUIApp/BankManagerUIApp/BankManager.swift
> +        var bank: Bank = Bank(bankers: bankers)
저희가 이해한 바로는 통일성 관련해서 말씀해주신 것 같아서 변수 bank를 타입추론형식으로 수정했습니다. 아니라면 말씀해주시면 감사하겠습니다!

2023-07-17 08:41 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    mutating func receiveQueueNumber(queueNumber: Int) {
현실에 빗대어 생각해볼때 Customer가 queueNumber를 부여받는게 초기화될 때가 아니라 bank에서 lineUp메서드를 통해 enqueue될 때(줄을 설 때) 부여받는게 맞다고 생각해서 따로 메서드를 만들어 주었습니다.

2023-07-17 08:42 UTC, redmango1447 commented on BankManagerUIApp/BankManagerUIApp/BankManager.swift
> +        var isBankOpen: Bool = true
컨벤션적인 부분에서 뭐가 맞는 표현인지 헷갈려서 자료를 찾아본 후 isBankOpened이 옳다는 걸 알게되었습니다!

[Bool변수 네이밍에 참고한 자료 링크](https://soojin.ro/blog/naming-boolean-variables)

2023-07-17 08:42 UTC, redmango1447 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +let test = BankManager()
test를 위해 썼던 네이밍을 깜빡하고 수정하지 못했습니다. bankManager로 수정했습니다!

2023-07-18 01:54 UTC, merged