은행창구 매니저 [STEP 3] Kobe, Hamg
yagom-academy/ios-bank-manager pull request #315
Opened 2023-07-19 03:01 UTC by devKobe24

안녕하세요 그린(@GREENOVER)!
더운 여름 KWDC에서 아주 좋은 연사였습니다!!😍
고생 많으셨습니다!!🙇🏻‍♂️
스유에 대해서 잘모르지만 뭔가 배워보고싶고 해보고싶은 동기부여를 얻게 되었습니다.🙌
이번 리뷰를 받게 된 Kobe, Hamg 입니다. 잘 부탁드립니다!

## 고민되었던 점
### 은행원 이슈 
- 이번 스탭에서 은행원이 3명이라 지정을 해줘서 Banker에 3명을 주어 2명은 예금을 하게끔 1명은 대출을 하게끔 진행해야한다고 생각했습니다.
```swift
for _ in 1...depsit {}
for _ in 1...loan {}
```
- 이런식으로 예금, 대출에 맞게 진행을 해야하나 생각하면서 스텝을 진행하려고하였고 생각처럼 방법을 구현하지를 못했습니다. 그래서 다른 방법으로 예금큐, 대출큐 를 구현하여 진행 하고자 했습니다
```swfit
depositBankerQueue = OperationQueue()
loanBankerQueue = OperationQueue()
depositBankerQueue.maxConcurrentOperationCount = 2
loanBankerQueue.maxConcurrentOperationCount = 1
```
- 이런식으로 구현을 하게 되면 대출,예금따로 진행을 하게 되는것을 알게되었는데요, 이렇게 된다면 `Banker`가 하는일이 없어지게 되었는데요 이렇게되면 이번 스텝에 있어 잘못알고 진행을 하게 된걸까요? 이상이없이 구현을 해낸거라면 `Banker` 를 지우는게 맞을까요??

## 조언을 구하고 싶은 점
### 스레드를 그래프로 확인하는 방법에 대해서 알고 싶습니다.
저희가 코드를 구현하면서 콘솔로만 확인하다보니 제대로 구현이 되었는지 확인하는 방법에 많은 고민을 하였습니다.
그러다가 KWDC에서 우연히 다른 동기로부터 전해들었던 그래프로 확인할 수 있는 방법을 concurrency에서 봤다는 이야기들 전해 들었습니다.
그리하여 구글링을 하였는데 제대로된 자로가 많이 없었습니다.
최대한 많은 자료를 긁어 모아 확인해 본 결과가 아래와 같았습니다.

<img src = "https://github.com/devKobe24/images/blob/main/%E1%84%89%E1%85%B3%E1%84%85%E1%85%A6%E1%84%83%E1%85%B3%E1%84%80%E1%85%B3%E1%84%85%E1%85%A2%E1%84%91%E1%85%B3.png?raw=true">

이 그래프만 봤을 때 어떤 의미로 해석해야 할지도 모르겠습니다.
그래서 어떻게 그래프를 보고 해석해야 하는지 조언을 구하고 싶습니다.
좋은 글이나 문서 혹은 블로그가 있다면 알려주시면 더욱 감사할 것 같습니다!!

2023-07-19 09:36 UTC, GREENOVER requested changes
두분 스텝3도 잘해주시느라 고생 많으셨습니다!ㅎㅎ
KWDC도 좋은 경험으로 느껴지셨다니 다행이에요 👍👍
그럼 리뷰 드려보겠습니다~
***
### 칭찬 드리고 싶은 부분
- 에러에 대해 이제 신경쓰실줄 알게 되신것 같아요 💯
- 대출/예금 큐를 잘 구성했네요! 💯
***
### 궁금하신 부분에 대한 저의 의견
- 이런식으로 구현을 하게 되면 대출,예금따로 진행을 하게 되는것을 알게되었는데요, 이렇게 된다면 Banker가 하는일이 없어지게 되었는데요 이렇게되면 이번 스텝에 있어 잘못알고 진행을 하게 된걸까요? 이상이없이 구현을 해낸거라면 Banker 를 지우는게 맞을까요??
  - 뱅커가 하는 역할은 그것과 다르지 않은가 싶습니다!
  대출/예금은 단순한 고객의 업무 종류이기에 구현하신 대출/예금 큐에 줄세우는것 그 이상도 이하도 아니라 생각이 들며, 뱅커는 대출/예금 모든 일을 처리할 수 있기에 별도로 생각하는게 맞지 않을까해요..!
- 스레드를 그래프로 확인하는 방법에 대해서 알고 싶습니다.
  - 어떤 부분을 여쭤보신지 제가 잘 유추하진 못했지만 저 그림에서라면 시간 흐름에 따라 메인 스레드가 언제 콜 되었고 돌고 있는지 유휴 상태인지에 대한 경과가 running 바처럼 나타나보이는데요.
  말씀하시는것이 스레드를 그래프로 어떤것을 명확히 확인하고 싶은지도 여쭤보고 싶어요🙋🏻
  참고할만한 문서는 저도 평소에 이런게 좋다! 라는 것이 명확하지 않아서 이참에 조금 탐색해봤는데, 이미 보셨을것 같아요!
  https://engineering.linecorp.com/ko/blog/about-swift-concurrency-performance
  이번 KWDC에서 concurrency 발표하신 윤재님 글이 저는 정리가 잘 되있긴 한거 같아요.
  다른 자료들도 괜찮은게 있으면 바로 공유드릴께요!
***
### 보완되면 좋을 부분
- 우선 현재 실제 구동시켜보면 딜레이가 되지 않고 1초만에 바로 끝나게 됩니다ㅠ
다만 업무 처리 총 시간과 고객 수 등 결과 프린트는 정상적으로 찍히는데 실제로 업무 처리되는 부분이 뭔가 이상한듯 해요🥲
한번 런 시켜서 확인해보시면 좋을듯 합니다~!
***
에러가 있는 동작은 아니나 정상적인 동작이 현재 되지는 않는것 같아서 우선 Request Changes로 해두겠습니다~!
언제든 재요청 부탁드려요ㅎㅎ

2023-07-20 00:55 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager/BankService.swift
> +                continue
✏️ 답변</br>

- `return`으로 변경 진행했습니다. 🙌 값이 존재하지 않는데 `continue`를 타면 문제가 있습니다. 그 이유는 어떤 업무를 처리해야 할지 모르기 때문입니다. 즉, "예금" 업무인지, "대출" 업무인지를 판별할 수 없습니다.🥲

2023-07-20 00:56 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Customer.swift
> +    let bankingWork: BankingOperations
✏️ 답변</br>

<img src = "https://github.com/devKobe24/images/blob/main/CustomerGithub.png?raw=true">

- 프로젝트 파일에서 코드를 봤을 때는 두 프로퍼티의 띄어쓰기 컨벤션이 정상적입니다 어떤 문제일까요 ?? 🥲

2023-07-20 00:56 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Model/BankingServiceTimeConverter.swift
> +    else {
- `TimeCheck`메서드에서 `guard let` 시에 `else`를 개행했었는데요 한줄에 100자가 넘을꺼같아 개행을 진행했었습니다. 이로 인해 `bankingServiceTimeConverter`에서도 개행을 진행했었습니다. 지금 확인해보니 `TimeCheck`에서 100자가 안되고 97자가 되기에 `guard let` 사용 부분에 있어 컨벤션을 맞추기위해 else을 개행 하지 않고 진행하고자 변경 했습니다!

2023-07-20 00:56 UTC, devKobe24 commented on BankManagerConsoleApp/BankManagerConsoleApp/Error/NumberFormatError.swift
> +    case convertToString
✏️ 답변</br>

<img src = "https://github.com/devKobe24/images/blob/main/EnumErrorCase.png?raw=true">

- Apple의 Docs를 참고하여 에러 케이스 명을 `convertedString`으로 수정해봤습니다. 그 이유는 `NumberFormatError`이 `Error`임을 이미 명시해주고 있으므로 케이스 명까지 `Error`이 들어가면 중복적인 단어가 쓰이는 것 같아 위와 같이 수정했습니다. 따라서 에러를 던져줄 때 `throw NumberFormaterError.convertedString` 과 같은 형태가 됩니다.🙌

2023-07-20 00:56 UTC, hemg2 commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +private var bank = BankService(numberOfCustomers: 10)
```swift
 for i in 1...Int.random(in: 10...numberOfCustomers){}
private var bank = BankService(numberOfCustomers: 30)
```
- 이렇게 고객수를 랜덤하게 정하여 업무를 진행 할수있게 변경하였습니다. 감사합니다!

2023-07-20 02:59 UTC, GREENOVER approved these changes
수고하셨습니다!
동작 이상 없음 확인했고 리팩토링도 잘 진행된것 확인했어요ㅎㅎ
나머지 코멘트 단 부분들이 있는데 그건 마이너해서 다음 스텝에서 같이 진행해보셔도 될것 같아 어프로브 및 머지하겠습니다 🎉🎉🎉
다음 스텝도 화이팅입니다!

2023-07-20 02:59 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager/BankService.swift
> +        for i in 1...Int.random(in: 10...numberOfCustomers) {
실제 고객 수를 생성하는건 은행이 할일이 아닌것 같은데 main에서 랜덤한 고객수를 생성하고 BankService의 numberOfcustomers에 주입해주는건 어떨까요🙋🏻
현재 main에서 뱅크서비스 이니셜 시 30으로 고정된 값을 넣어주는데 조금 맞지 않은 느낌이 들어서요..!
30으로 넣어준건 최대 고객수에 대한 제한 같아서 로직 변경이 조금 필요해보여요 🤔

2023-07-20 02:59 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager/Customer.swift
> +    let bankingWork: BankingOperations
엇 제가 프로젝트 파일에서 코드를 봤을때는 waitingNumber 프로퍼티만 2칸 인덴트가 되어 있었는데 착각했나봅니다 🥲

2023-07-20 02:59 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerConsoleApp/Error/NumberFormatError.swift
> +    case convertToString
보여주신 Docs에서 케이스 명에 NotSupported처럼 에러에 대한 어떤 케이스 즉, "멀티플씬이 지원되지 않음"의 케이스명을 가지는데 convertedString은 조금 다르지 않나 싶긴해서요 🙋🏻
docs와 같은 기조로 간다면 NumberFormatError.notConvertedToString처럼 되야 하는게 아닌가 싶어 여쭤봅니다~!

2023-07-20 02:59 UTC, merged