은행 창구 매니저 [STEP 3] Dasan, Mary
yagom-academy/ios-bank-manager pull request #317
Opened 2023-07-20 04:44 UTC by DasanKim

안녕하세요 올라프!⛄️(@1Consumption)
드디어 STEP3로 인사드립니다🙇‍♀️🙇‍♀️

올라프에게 더 많은 것을 배우고 싶은데, 벌써 시간이 이렇게 흘렀네요...🥹
마지막까지 열심히 배우겠습니다! 잘 부탁드립니다!😊

감사합니다:)

----

# STEP 3

## 🔍 고민되었던 점

### 1. GCD로 동시성 구현하기
- `Semaphore`는 `공유 자원` 및 `임계영역(Critical Section)`에 접근할 수 있는 스레드의 수를 제어해주는 역할을 합니다.
- 이에, **Semaphore의 수를 은행원의 수**라고 생각하여 아래와 같이 동시성을 구현하였습니다.
    - 각 은행원들이 고객 대기줄을 `dequeue`하는 것이 아니라 **Bank 타입에서 dequeue한 뒤**, 고객이 받고자하는 서비스에 따라 `담당 부서`에게 고객을 `배정`하였습니다.
    - 그 이후 담당부서에서는 은행원의 수(semaphore의 수)만큼 — `DispatchSemaphore(value: numberOfBankTeller)` — 아래 코드를 비동기적으로 처리하도록 하였습니다.
    ```swift
    // bank.swift
    while let currentCustomer = customerQueue.dequeue() {
        switch currentCustomer.service {
        case .deposit:
            depositDepartment.takeOnTask(for: currentCustomer,
                                         startHandler: printStartMessage,
                                         completionHandler: printFinishMessage)
        case .loan:
            loanBankDepartment.takeOnTask(for: currentCustomer,
                                          startHandler: printStartMessage,
                                          completionHandler: printFinishMessage)
        }
    }
    ```
    ```swift
    // BankDepartment.swift
    init(responsibility: BankingService, numberOfBankTeller: Int, group: DispatchGroup) {
        (...)
        self.semaphore = DispatchSemaphore(value: numberOfBankTeller)
        (...)
    }

    func takeOnTask(for customer: Customer,
                    startHandler: @escaping (Customer) -> Void = { _ in },
                    completionHandler: @escaping (Customer) -> Void = { _ in }) {
        departmentQueue.async(group: group) {
            semaphore.wait()
            startHandler(customer)
            work()
            completionHandler(customer)
            semaphore.signal()
        }
    }
    ```

### 2. escaping closure
⚠️ **문제점** <br>
- 비동기 task를 정의한 `takeOnTask`메서드에서 startHandler 및 completionHandler에 escaping 키워드를 붙이지 않으면 다음과 같은 오류가 발생하였습니다.
![](https://hackmd.io/_uploads/Hku4BfU9h.png)
- 해당 오류에 대한 원인 분석을 진행해보았습니다.
    - 현재 task는 비동기로, DispatchQueue에 작업만 넘기고 실제 작업은 언제 시작될 지 모릅니다. (시스템에서 자동으로 관리)
    - 만약 두 handler에 escaping 키워드를 붙이지 않으면 non-escaping closure가 되는데, 이는 함수의 실행이 종료되기 전에 무조건 closure의 실행이 완료되어야 합니다.
    - 하지만 startHandler와 completionHandler는 비동기 task 코드블럭 안에 위치하기 때문에 `takeOnTask` 함수가 종료된 후에도 실행될 가능성이 있습니다.

✅ **해결방법** <br>
- closure에 escaping 키워드를 붙여서 함수의 실행이 종료된 후에도 실행될 수 있도록 설정해줌으로써 해당 오류를 해결하였습니다.

#### Closure
- non-escaping closure
    - 함수의 실행이 종료되기 전에 실행되는 클로저
- escaping closure (`@escaping`)
    - 함수의 실행이 종료된 후에도 실행될 수 있는 클로저 

### 3. Bank 의존성 주입
⚠️ **문제점** <br>
- BankManager에서 Bank타입의 인스턴스를 만들어서 활용하기 때문에 MockBank를 이용해야하는 BankManager 테스트 시 어려움이 있었습니다.

```swift
struct BankManager {
    mutatin func runProgram() {
        var bank: Bank = createBank()
        ...
    }
    
    private func createBank() -> Bank {
        let randomNumber = generateRandomNumber()

        return Bank(numberOfCustomer: randomNumber)
    }
    ...
}
```

✅ **해결방법** <br>
- 다음과 같은 방법을 이용하여 `Bank`와 `BankManger`의 의존성을 없애고 Unit test가 용이한 형태로 변경해주었습니다.
    - `BankManager` 타입에서 Bank 인스턴스 생성하는 것 대신 Bank 타입을 주입받는 형태로 변경하였습니다.
    - Openable 프로토콜을 생성하고 Bank 타입이 채택하도록 만들어주었습니다.

```swift
protocol Openable {
    mutating func open(numberOfCustomer: Int)
}

struct Bank: Openable {
    mutating func open(numberOfCustomer: Int) { ... }
}

struct BankManager {
    var bank: Openable

    init(bank: Openable) {
        self.bank = bank
    }
    
    ...
}
```

### 4. 시간 계산 방법
- 기존 은행원이 한명이었을 때에는 `소요시간 * 고객수`로 계산해주었습니다.
- 현재는 비동기적으로 3명의 은행원이 작업을 각각 `다른 소요시간`, `다른 고객수`를 처리하므로 `DispatchGroup`으로 묶인 작업이 `시작`되고, `끝나는` 지점을 DispatchGroup의 `wait` 메소드로 추적하여 시간을 계산해주었습니다.

<br>

## 🙏 조언을 얻고 싶은 부분

Console에서 값을 입력받는 형태의 unit test는 처음이라 올바른 방법으로 구현한 것인지 궁금합니다. 
- 예를 들어, 사용자 입력으로 5를 받아서 프로그램이 다시 시작되는 지 확인하는 테스트를 하고 싶었으나 테스트 결과를 확인하려면 무조건 2를 입력해서 프로그램을 종료 시켜야 했습니다. 
- 따라서 테스트 이름을 "test_runProgram메서드실행후_5을입력후_2를입력하였을때_bank의_isOpening은_false이다()" 처럼 조건을 2개(5입력, 2입력)로 설정해주었습니다.

혹시 올라프께서 주로 사용하시는 스타일이 있으시다면 조언 부탁드립니다! 🙇‍♀️

<br>

## 📚 참고 링크
- [🍎Apple Docs: Closures](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/)
- [🍎Apple Docs: Dispatchsemaphore](https://developer.apple.com/documentation/dispatch/dispatchsemaphore)
- [🌐 야곰닷넷: 동시성 프로그래밍](https://yagom.net/courses/%EB%8F%99%EC%8B%9C%EC%84%B1-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-concurrency-programming/)
- [🌐 Blog: [OS] Semaphore, Mutex](https://velog.io/@xogh20321/OS-Semaphore-Mutex)
- [🌐 Blog: [OS] wait(), signal(), 이진, 계수형](https://jhnyang.tistory.com/101)

<br>

2023-07-20 13:06 UTC, 1Consumption requested changes
고생하셨습니다. 코멘트 참고해주세요.

2023-07-20 13:06 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +        self.service = BankingService.allCases[Int.random(in: range)]
아래와 같이 변경해보는건 어떨까요? `Customer`에서는 굳이 몰라도 되는 정보 같아요.
```swift
enum BankingService {
    
    // ...

    static func random() -> Self {
        return BankingService.allCases.randomElement() ?? .deposit
    }
}
```

2023-07-20 13:06 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleTests/BankManagerTests/MockBank.swift
> +}
mock과 stub은 어떻게 다른가요? 그리고 지금 올려주신 객체는 mock이라고 볼 수 있을까요?

2023-07-21 01:34 UTC, DasanKim commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var timer = Timer()
(근무) 시간을 기록한다는 의미를 가진 `TimeTacker`로 이름을 변경하였습니다:)

2023-07-21 07:25 UTC, DasanKim commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankDepartment.swift
> +    private let numberOfBankTeller: Int
말씀해주신 대로 꼭 필요한 프로퍼티가 아닌 것 같아 해당 프로퍼티들을 삭제하였습니다😊

2023-07-21 07:26 UTC, DasanKim commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Customer.swift
> +        self.service = BankingService.allCases[Int.random(in: range)]
올라프 말씀대로 고민하고 수정하였더니, 더 깔끔하고 `Customer`가 알아야하는 정보만 남게 되었습니다🙌

2023-07-21 09:28 UTC, DasanKim commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankDepartment.swift
> +            semaphore.wait()
- **DispatchSemaphore**
  - 기존 카운팅 세마포어를 사용하여 리소스에 대한 동시 액세스를 제어하는 객체로써, `공유 자원` 또는 `임계 영역(Critical Section)`에 접근할 수 있는 **동시 작업 개수를 제어**해주는 역할을 합니다. 
  - 객체를 생성할 때, 설정해주는 value으로 작업 개수를 설정해줄 수 있습니다.
 
- **NSLock**
  - 동일한 애플리케이션 내에서 여러 실행 `스레드`의 작업을 조정하는 객체로, 애플리케이션의 전역 데이터에 대한 액세스를 중재하거나, 코드의 중요한 부분을 보호하여 `원자 단위`로 실행할 수 있습니다.
  - `NSLock`으로 설정된 `임계 영역(Critical Section)`에는 오직 `하나`의 스레드만 진입을 허용하여 객체를 사용하는 스레드가 끝날 때까지 다른 스레드들의 접근을 제한합니다.

위와 같이 `NSLock`은 오직 하나의 스레드 진입만을 허용하므로, 예금을 담당하는 은행원이 `2명`이 있다하더라도 한번에 `1명`만 해당 작업(임계영역)을 처리하게됩니다. 따라서 `NSLock`을 사용하지 않고, `Dispatch Semaphore`를 사용하였습니다☺️

2023-07-21 14:57 UTC, DasanKim commented on BankManagerConsoleApp/BankManagerConsoleTests/BankManagerTests/MockBank.swift
> +}
저희가 만들었던 `MockBank` 객체는 `BankManager` 객체를 테스트 하기위하여 만든 `collaborator` 객체입니다.
현재 입력값에 따라 `BankManager`에서 Bank의 `open`메서드를 호출하는지 `isOpening` 프로퍼티를 통하여 상태를 검사합니다.
또한 **실제 구현이 없고** 메서드를 호출하는지를 확인하기 위한 프로퍼티만 가지고 있습니다.

따라서 `MockBank` 객체는 `Test Double`들 중에서 Mocks보다 `Stubs`으로 보는 것이 맞다고 판단하였고, `BankStub`로 객체 이름을 수정하였습니다.☺️

----

테스트 결과를 검증하는 방법에는 `state verification`(상태 검증)과 `behavior verification`(행위 검증)이 있습니다.
- State Base Test(상태 기반 테스트)
    - 상태를 검사하여 실행된 메서드가 올바르게 작동했는지 확인합니다.
    - 메서드를 호출하고 그 결괏값과 예상값을 비교하는 식으로 동작하는 테스트입니다.
- Behavior Base Test(행위 기반 테스트)
    - 예상되는 행위들에 대한 시나리오를 만들어 놓고, 시나리오대로 동작했는지에 대한 여부 확인합니다.

### Test Double
테스트 목적으로 실체 객체 대신 사용하는 모든 종류의 가짜 객체를 통칭하는 용어입니다.

#### Stubs
- 테스트 중 걸려온 호출에 대해 미리 준비된 답변을 제공하며, 일반적으로 **테스트를 위해 프로그래밍된 것 이외의 것에는 전혀 응답하지 않습니다.**
- 실제 구현이 없거나 `간단한 특정 기능만`을 가진 객체입니다.
- 보통 Stubs는 `상태` 기반 테스트이지만 `행위` 검증도 가능합니다.

#### Mocks
- 수신할 것으로 예상되는 호출의 사양(설명서)을 형성하는 기대치로 미리 프로그래밍된 객체입니다.
- `실체 객체`와 **가장 비슷**하게 구현된 수준의 객체입니다.
- Mocks는 `행위` 기반 테스트입니다.

2023-07-21 17:06 UTC, DasanKim commented on BankManagerConsoleApp/BankManagerConsoleTests/BankManagerTests/BankManagerTests.swift
> +    }
#### 숫자 입력받는 부분 의존성 분리
- 숫자를 입력받는 부분을 외부 의존성으로 분리하기 위하여 `Enterable` 프로토콜을 생성한 뒤, 
  ```swift
  protocol Enterable {
      func enterUserInput() -> String?
  }
  ```
- `Enterable` 프로토콜을 채택한 구조체 타입 인스턴스를 bankManager.runProgram 메서드의 `매개변수`로 전달하여 의존성을 주입해주었습니다.
  ```swift
  bankManager.runProgram(enterable: enterable)
  ```

#### 테스트 시, while문 내 무한루프 문제
- 입력값이 2가 아니면 runProgram 내 while문이 무한루프를 도는 문제를 해결하기 위하여, `BankManagerMock` 개체를 만들고 아래와 같이 처리하여  무한루프를 돌지 않도록 하였습니다.
  ```swift
   // BankManagerMock.swift
   switch inputValue {
       case Menu.bankOpening.number:
            bank.open(numberOfCustomer: generateRandomNumber())
            shouldContinue = false
       case Menu.quit.number:
            shouldContinue = false
       default:
            shouldContinue = false
  }
  ```

2023-07-21 17:11 UTC, MaryJo-github commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private var numberOfCustomer: Int = 0
현재 저희는 BankManager 타입에서 Bank 타입을 생성자로 주입받고 있으며, runProgram 메서드 내에서 사용자 입력이 2일때까지 프로그램을 반복하고 있습니다.
이 경우, Bank타입의 `numberOfCustomer`를 상수로 선언하여 초기값을 받게된다면 한 개의 값으로 고정되어 은행을 방문하는 고객수가 매일 같아지는 형태가 됩니다.

따라서 날마다 고객 수가 랜덤하게 달라지도록 변수로 선언해주었습니다!

2023-07-24 06:03 UTC, closed without merging