은행창구 매니저 [STEP 4] kyungmin, maxhyunm
yagom-academy/ios-bank-manager pull request #318
Opened 2023-07-20 09:17 UTC by maxhyunm

안녕하세요, 하비@havilog! STEP 4 PR 올려드립니다. 늦어져서 죄송합니다!
화면을 그리면서 동시에 로직 처리가 되도록 구현하는 부분에서 어려움을 느낀 스텝이었습니다.
마지막까지 잘 부탁드립니다!

## 🤔 고민했던 점
### 🌟 **대기중인 고객과 처리중인 고객 분리**
처음에는 `OperationQueue` 자체에 접근하여 해당 내용을 처리하려고 생각했습니다. `OperationQueue`에는 다음과 같은 프로퍼티가 있고, 각각 `KVO`로 업데이트 알림을 받을 수 있습니다.
- `operationCount` : 큐에 추가된 모든 작업의 수
- `operations` : 큐에 추가된 작업 리스트(각 작업별로 상태값 등 확인 가능)

하지만 위의 두 항목은 모두 `deprecated` 예정으로 되어 있어, 이 내용을 활용하는 것은 그다지 좋은 방법이 아닌 것 같았습니다. 또한 각 작업의 상세 내용(고객번호와 작업내용)을 가져오도록 만드는 부분에서도 어려움이 있었습니다.
때문에 고민을 하다가, STEP 3 기준으로 `print`문이 출력되는 시점에 대신 `UI`단의 대기/작업중 상태를 변경해주면 되겠다는 결론을 내렸습니다.
해당 내용을 처리하기 위해서는 `UI`가 업데이트되어야 하는 타이밍에 `Notification`을 발생시키거나, `delegate`를 통해 적절한 처리를 진행해야 했습니다. 여기서는 발생하는 이벤트를 오로지 한 곳에서만 받아 처리하면 되기 때문에 전체 알림을 발송하는 `NotificationCenter`보다는 `delegate` 패턴이 알맞을 것 같다고 판단하여, 후자로 진행하였습니다.
```swift
private func addTask(_ customer: Customer) {
    let task = BlockOperation {
        self.delegate?.moveCustomerToProcessQueue(customer)
        Thread.sleep(forTimeInterval: customer.duration)
        self.delegate?.popProcessingQueue(customer)
    }
    ...
}
```
### 🌟 **UI 관련 코드 main 스레드에서 실행시키기**
`delegate`나 `NotificationCenter`를 활용하면 `UI`를 변경하는 시점은 정확히 정할 수 있지만 한가지 문제가 있었습니다. `UI` 관련 내용은 `main` 스레드에서만 실행이 되어야 하는데, `OperationQueue` 작업 중에 해당 부분이 호출되면서 `main` 스레드가 아닌 곳에서 `UI`에 접근하는 형태가 된 것입니다. 때문에 컴파일러가 빌드를 진행하지 못하였습니다.
이 문제를 해결하기 위해 `UI`를 그리는 작업을 `OperationQueue.main`에 따로 `addOperation`을 통해 추가해주는 방식으로 진행하여 문제를 해결하였습니다.
```swift
OperationQueue.main.addOperation {
    ...
    self.waitingStackView.addArrangedSubview(customerView)
    ...
}
```

### 🌟 **Queue 처리가 완료되기 전에 실시간으로 UI 그리기**
처음에는 `OperationQueue`의 처리가 완료되기 전에는 `CustomerView`에 담긴 내용이 보이지 않았습니다. 데이터는 제대로 전달되지만, UI에 그리는 작업 자체가 실시간으로 진행되지 않는 것으로 보였습니다.
<img src="https://hackmd.io/_uploads/Syo3LE852.png" width="200">

어째서 비동기 큐를 쓰는데 작업을 기다리는지, `Task/await`을 써야 하는지 다양한 고민을 하다가 아래 코드를 발견했습니다. STEP 3에서 모든 일과가 마무리된 후 마감 메시지를 출력하기 위해 추가했던 부분이었습니다.

```swift
depositBankerQueue.waitUntilAllOperationsAreFinished()
loanBankerQueue.waitUntilAllOperationsAreFinished()
```
`waitUntilAllOperationsAreFinished()` 메서드는 큐의 모든 작업이 끝날 때까지 다음 작업을 대기합니다. 해당 부분을 삭제하자 `UI`가 정상적으로 그려지는 것을 확인할 수 있었습니다.
<img src="https://hackmd.io/_uploads/Hk8DeOIq2.png" width="200">

### 🌟 **대기-업무 상태 변화에 따라 알맞은 CustomerView 이동하기**
`StackView`에 추가된 `CustomerView`를 상태값에 따라 이동/삭제해주는 과정에서, 각 `StackView`의 `subview`들을 하나씩 훑으며 작업을 진행하게 되면 반복문이 너무 많아 비효율적이라는 생각이 들었습니다. 각 `View`에 `identifier`나 `key`값을 부여할 수 있는 방법이 있을지 고민하다가, `Dictionary`를 활용하는 방식을 선택하였습니다.
```swift
private var waitingDictionary: Dictionary<Customer, CustomerView> = [:]
private var processingDictionary: Dictionary<Customer, CustomerView> = [:]
```
이렇게 하면 `customer` 정보만 있어도 고객 상태값을 정확히 이동시킬 수 있고, 또 각 스택뷰가 비어있는지 여부를 확인할 때도 유용하다고 생각했습니다.(스택뷰가 모두 비어있는지를 확인하는 내용은 타이머를 일시정지시킬 때 활용하였습니다. - 대기/업무 스택이 모두 비어있으면 정지)
```swift
if self.processingDictionary.isEmpty && self.waitingDictionary.isEmpty {
    self.pauseTimer()
}
```

### 🌟 **UI가 그려지기 전에 완료된 Task 처리**
간혹 대기에서 업무로 넘어가지 않는 고객들이 있어 확인해보니, 대기중 `StackView`에 해당 고객 정보를 추가하는 작업이 `main` 스레드에서 진행되고 있을 때 `Bank`의 `OperationQueue`(별도의 스레드에서 작업)에서 이미 `Task`가 실행/종료되어 대기->업무로 넘어가는 작업을 정상적으로 거치지 못하는 것으로 보였습니다.
|<img src="https://hackmd.io/_uploads/rJZol_Lc2.png" width="200">|<img src="https://hackmd.io/_uploads/r1WslOIq3.png" width="200">|
|-|-|

이를 해결하기 위해 대기중인 고객을 업무중으로 변경하는 `moveCustomerToProcessQueue()` 메서드에 아래와 같은 내용을 추가하였습니다.
```swift
if waitingDictionary[customer] == nil {
    OperationQueue.main.waitUntilAllOperationsAreFinished()
}
```
이를 통해 대기->업무로 넘기는 작업을 진행하라는 요청이 넘어왔을 때 해당 고객이 대기중 `Dictionary`에 존재하지 않는다면 일단 `main` 스레드의 작업이 모두 끝날 때까지 대기한 후 다시 찾아볼 수 있도록 하였습니다.

### 🌟 **타이머에 millisecond 표시**
처음에는 `TimeInterval`의 포맷을 조절할 수 있는 `DateComponentsFormatter`를 활용해보려고 했습니다. 하지만 해당 포매터에서 다룰 수 있는 내용에는 millisecond가 누락되어 있었습니다. 즉, 초 단위까지밖에 포맷이 적용되지 않았습니다. 결국 원하는 형태로 타이머를 구현하기 위해 `TimeInterval` 자체를 minute/second/millisecond 단위로 계산하여 스트링 포매터를 사용하는 방식을 선택하였습니다.
해당 내용은 확장성을 고려하여 `Double` 타입에 `extension`으로 구현하였습니다.
```swift
extension Double {
    func formatTimeIntervalToString() -> String {
        let minutes = String(format: "%02d", Int((self/60).truncatingRemainder(dividingBy: 60)))
        let seconds = String(format: "%02d", Int(self.truncatingRemainder(dividingBy: 60)))
        let milliseconds = String(format: "%003d", Int(self.truncatingRemainder(dividingBy: 1) * 1000))

        return "\(minutes):\(seconds):\(milliseconds)"
    }
}
```

### 🌟 **StackView의 정렬**
대기/업무중인 고객의 `CustomerView`가 제대로 상단에 정렬되지 못하고 세로 길이가 멋대로 늘어나는 등 문제가 발생하였습니다.
<img src="https://hackmd.io/_uploads/HJesW_L92.png" width="200">

처음에는 대기/업무 `StackView` 내부 요소에 `setContentHuggingPriority`를 낮게 설정한 `emptyLabel`을 추가하여 조절해보았습니다. 하지만 그렇게 하니 매번 `Task`가 진행될 때마다 `emptyLabel`을 `SuperView`에서 제거한 후 마지막에 다시 추가하는 작업을 거쳐야 해서 번거로웠습니다.
```swift
OperationQueue.main.addOperation {
    customerView.removeFromSuperview()
    self.waitingDictionary[customer] = nil
    self.emptyProcessingView.removeFromSuperview()
    self.processingStackView.addArrangedSubview(customerView)
    self.processingDictionary[customer] = customerView
    self.processingStackView.addArrangedSubview(self.emptyProcessingView)
}
```

해당 부분은 두 개의 `StackView`를 담는 `Horizontal StackView`에서 `alignment`를 `top`으로 조절하여 해결하였습니다.
```swift
stackView.alignment = .top
```

### 🌟 **Bank 타입 변경**
`OperationQueue`를 위한 `Task` 클로저에서 타입 내부의 메서드와 프로퍼티에 접근하려면 값 타입이 아닌 참조 타입이어야 했기에 `Bank` 타입을 `class`로 변경하였습니다.

2023-07-21 11:45 UTC, havilog requested changes
두 분 모두 고민 많이 하셨을거 같은데 고생하셨어요!

1. 은행창구 매니저에서 사용하고 싶으신 기술을 쓰신건 이견 없지만, 개인적인 의견으로는 GCD, OperationQueue는 거의 deprecated된 거 같아요.
GCD와 OperationQueue에 관한 내용을 알고 있고, 면접에서 대답할 수 있을만큼 써보신 다음 async/await 기반으로 공부하시는걸 추천드릴게요.
또한 KVO도 요즘은 안쓰구요, noti와 delegate는 1:다, 1:1의 관계라는 큰 차이가 있어서 잘 활용하시면 좋을 것 같아요.
또한 delegate로 안연결하고 콜백 클로저를 달아줄 수도 있으니 고것도 고민해보세영

2. 전반적으로 요구사항을 구현하는것도 중요하지만, 코드의 readability를 많이 챙겨주시면 좋을 것 같아요.
코드를 먼저 쓰는게 아닌, 객체를 구성하고, 객체와 객체간의 관계를 연결하고, 요구사항을 정의하고,
이 코드가 다른 사람에게 어떻게 읽힐지를 많이 고민해보시면 좋을 듯 합니다.

칭찬하는 재주가 없어서 파워T답게 현실만 말씀드렸는데 혹여나 상처받지 마시구 화이팅 하세여 : )

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        button.setTitle(Namespace.addCustomer, for: .normal)
요런것도 취향이긴 한데.. 저는 오히려 이런 부분에 네임스페이스가 잡혀있으면 한 번 코드점핑해야해서 읽기가 더 힘들어지더라구요 ㅎㅎ

요거는 계속 개발하시면서 맞춰 나가시면 될 것 같습니다!

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +extension BankViewController {
```suggestion
private extension BankViewController {
```

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        bank.work()
함수 이름은 resetUI인데, 뱅크를 다시 시작하는 부분이 있네요.
함수 이름을 reset으로 바꾸던가, UI를 다시 그리는 부분과 시작하는 부분이 분리되어있는게 좋을 것 같습니다.

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        guard let isTimerOn = timer?.isValid, isTimerOn else {
isTimerOn이라는 지역변수를 잡아서 메모리를 사용하기 보다는, timer?.isValid == true로 바로 판단하는건 어떨까요?

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    private var processingDictionary: Dictionary<Customer, CustomerView> = [:]
UIView는 뷰를 그려주기만 해야하고, 뷰와 로직은 분리되어있어야 할 것 같아요.
딕셔너리에 뷰가 들어간다면, 뷰에 따른 비지니스 로직이 생길거고 이는 유지보수를 어렵게 해요!

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            delegate?.addWaitingQueue(customer)
이게 동기로 일어나면,
addTask로 비동기작업이 실행되는 동안
UI는 아직 다 그려지지 못한 상태일수도 있을거 같은데 혹시 고민해보셨을까요?

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +    }
코드는 요구사항을 모르는 사람이 봐도, 자연스럽게 읽히는게 좋을 것 같은데,
현재 변수명, 함수명을 보고는 이 함수가 어떤 행동을 하는지 유추하기 어렵다는 생각이 들어요.

1. 은행의 업무가 시작되면,
2. random한 고객을 waitingQueue에 추가하고,
3. 대기중인 고객을 업무중으로 이동시키며 업무를 시작한다

라는 게 더 잘 드러났으면 하는 바람입니다 ㅎㅎ

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            dailyTotalCustomer += 1
dailyTotalCustomer 요 변수는 왜 존재하는 아이일까요?
Customer의 waitingNumber는 for-in 문에서 생략된 _에서 가져올 수도 있을 거 같아서요

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            Thread.sleep(forTimeInterval: customer.duration)
저번에도 말씀드렸는지 안드렸는지 잘 기억이 안나서 적습니다 ㅎㅎ

Thread.sleep은 현실세계의 시간과 달라서 0.5초를 sleep시키면, 현실에서는 0.4xxx ~ 0.5xxx가 흘러가요!
현재는 Date()를 기준으로 판단하고 계신거 같아서 이 코드는 테스트를 하게 된다면 실패할 거 같아요 ㅎㅎ

당장은 힘들더라두 요런 부분들 더 고민해보시면서 개발하시면 좋을 것 같아요!

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Double+.swift
> +}
요런건 Model폴더보단 extension폴더를 만들어서 넣으셔야할것 같아요!

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/View/CustomerView.swift
> +class CustomerView: UILabel {
```suggestion
final class CustomerView: UILabel {
```

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/View/CustomerView.swift
> +class CustomerView: UILabel {
요런 커스텀 뷰는 UILabel을 상속받기 보다는, UIView를 상속받아서 Customer 모델을 프로퍼티로 들고 있고, 레이아웃을 잡아주는게 더 관리하기 편하실 거에요

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/View/CustomerView.swift
> +        if purpose == Bank.Work.loan.name {
purpose는 enum으로 관리되면 좋을 것 같네요.
`self.textColor = purpose.color`처럼 읽히게 되는걸 고민해보시면 좋을 것 같아요

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Customer.swift
> +struct Customer: Equatable, Hashable {
같은 프로토콜이 중복으로 적용되어있네요!

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        view.backgroundColor = .systemBackground
요 줄은 configureUI()와는 별개인걸까요?

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        resetUI()
뷰가 로드 되었을 때, UI를 구성하고, reset시킨다. 라고 읽히는데 의도하신 내용일까요?

2023-07-21 11:45 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    @objc private func didTapReset() {
```suggestion
    @objc private func didTapResetButton() {
```
```suggestion
    @objc private func resetButtonTapped() {
```

어떤 UIComponent가 눌렸는지까지 명시해주는게 좋을 것 같아요

2023-07-23 02:07 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/App/SceneDelegate.swift
> +        let mainViewController = BankViewController()
네이밍 수정하였습니다!

2023-07-23 02:10 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +extension BankViewController {
private 추가하였습니다.

2023-07-23 02:14 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        bank.work()
bank.work()를 호출하는 위치를 변경하였습니다.

2023-07-23 02:16 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        guard let isTimerOn = timer?.isValid, isTimerOn else {
합치니 훨씬 깔끔하네요!! 수정하였습니다.

2023-07-23 02:23 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            delegate?.addWaitingQueue(customer)
해당 부분 PR에 작성드린  [UI가 그려지기 전에 완료된 Task 처리] 항목에 관한 내용이 맞을까요? 저희는 UI를 그리는 main 스레드에서 작업을 한 번 기다릴 수 있도록 처리하였습니다!

2023-07-23 02:31 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +    }
메서드명 수정하였습니다..!

2023-07-23 02:38 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            dailyTotalCustomer += 1
처음에는 for 문에서 와일드카드 대신 waitingNumber로 가져와서 활용을 했었습니다(step3)! 그런데 step4에서 10명 추가 버튼이 새로 생겼고, 기존 로직으로는 10명을 추가할 때마다 대기번호가 1부터 다시 시작하게 되었습니다. 고객을 추가한 것인데 대기번호가 리셋되는 것은 이상하다고 생각이 되어서, 마지막 고객번호를 전역변수로 남겨두고 이를 토대로 하루치 누적 고객 번호를 전달해야겠다는 의도로 dailyTotalCustomer를 활용하였습니다.

2023-07-23 02:43 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            Thread.sleep(forTimeInterval: customer.duration)
해당 부분 CFAbsoluteTimeGetCurrent()를 활용하여 수정하였습니다! 앞으로도 참고하여 고민하며 작업하겠습니다🙇‍♀️

2023-07-23 02:45 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/View/CustomerView.swift
> +class CustomerView: UILabel {
final 추가했습니다!

2023-07-23 03:19 UTC, YaRkyungmin commented on BankManagerUIApp/BankManagerUIApp/Model/Customer.swift
> +struct Customer: Equatable, Hashable {
`Hashable`만 채택하게 해줬습니다:)

2023-07-23 03:22 UTC, YaRkyungmin commented on BankManagerUIApp/BankManagerUIApp/View/CustomerView.swift
> +        if purpose == Bank.Work.loan.name {
`Customer`타입 내부에 `Purpose`타입을 `nested`하게 가지고 있게 옮겨줬습니다.
`color`프로퍼티도 추가해줬습니다.

2023-07-23 03:23 UTC, YaRkyungmin commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        view.backgroundColor = .systemBackground
옮겨줬습니다:)

2023-07-23 03:24 UTC, YaRkyungmin commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    @objc private func didTapReset() {
명시해줬습니다ㅎㅎ

2023-07-23 03:37 UTC, YaRkyungmin commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +        resetUI()
`resetUI()`안의 타이머 로직을 분리시켜준 뒤 `setTimer()`를 하도록 했습니다:)

2023-07-23 04:06 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    private var processingDictionary: Dictionary<Customer, CustomerView> = [:]
넵 수정했습니다!

2023-07-23 04:14 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    private var processingDictionary: Dictionary<Customer, CustomerView> = [:]
딕셔너리를 빼고 arranged subviews에 반복문을 돌려 해당 로직을 처리해보려 했는데, 현재 UI가 그려지기 전에 Task가 넘어가버리는 것을 방지하는 부분에서도 딕셔너리를 사용하고 있어서 이 부분 처리가 어려워서 딕셔너리는 그대로 남겨두었습니다😭 async/await에 대한 추가 공부를 진행하고 추후에 수정해보도록 하겠습니다! 감사합니다...!

2023-07-23 04:26 UTC, maxhyunm commented on BankManagerUIApp/BankManagerUIApp/View/CustomerView.swift
> +class CustomerView: UILabel {
UIView로 수정하였습니다!

2023-07-23 05:46 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Controller/BankViewController.swift
> +    private var processingDictionary: Dictionary<Customer, CustomerView> = [:]
이 부분은 어싱크랑은 관련 없을거 같고,
객체간의 데이터 전달을 어떻게 해야 할지에 대한 구조 설계를 더 고민해보시면 좋을 것 같습니다!

2023-07-23 05:49 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            Thread.sleep(forTimeInterval: customer.duration)
아마 CFAbsoluteTimeGetCurrent도 정확한 현실시간이랑 비교가 되는지는 잘 모르겠어요

2023-07-23 06:15 UTC, havilog commented on BankManagerUIApp/BankManagerUIApp/Model/Bank.swift
> +            delegate?.addWaitingQueue(customer)
아뇨 그거랑은 다르게 36번 라인이 실행되고 나서 37번에서 델리게이트로 레이블을 그릴때까지 걸리는 시간을 고민해보셨을지에 대한 내용이였어요

2023-07-23 06:16 UTC, merged