은행창구 매니저 [STEP 3] yetti, redmango
yagom-academy/ios-bank-manager pull request #320
Opened 2023-07-21 07:33 UTC by redmango1447

안녕하세요 줄라이!(@July911)
PR이 많이 늦었습니다 ㅠㅠ
비동기에 대해  아직도 모르는게 많고 고민이 되는 부분도 많았습니다
잘 부탁드립니다 ㅠㅠ

## 고민했던점
### 1. 예금큐와 대출큐를 따로 만들어야할지 하나의 큐로만 관리해야할지
- 처음 큐를 구현했을 때 각 고객마다 업무타입에 대해서 지정을 해준 후 하나의 큐에 담아서 관리를 해주었습니다. 하지만 이렇게 큐를 구현하게되면 다음과 같은 상황에 문제가 생겼습니다.
[현재 예금 고객의 업무가 모두 종료되었지만 다음 대기하는 고객이 대출 고객일경우 그 고객이 빠지지 않으면 다음 예금 고객을 받을 수 없다.]
해당 문제점을 업무 타입마다의 큐를 만들어서 은행원의 업무가 종료되면 다시 새로운 고객을 바로 받을 수 있도록 해주었습니다.

### 2. 스레드를 작업시마다 생성,삭제가 반복되게 해야할지 유지해야할지
기존엔 `dispatchQueue`를 `Banker타입의 work메서드` 내부에서 사용하여
work메서드가 실행될때마다 새로운 스레드가 생성되는 방식이였습니다. 그로인해 불필요해보이는 스레드가 많이 생겼고, 작업을 끝내면 사라지는 스레드라고 하지만 애초에 은행원 수 만큼의 스레드만 생성되는게 맞다고 생각하여 수정해 보았습니다.

#### 실행결과

|  | 기존 | 수정후 |
| -------- | -------- | -------- |
| 실행화면    |<Img src =  "https://hackmd.io/_uploads/rkkWcqPqn.gif" width="300" height="600">| <Img src =  "https://hackmd.io/_uploads/H1Yqj9v53.gif" width="300" height="600">|
|git 링크|[Before](https://github.com/iOS-Yetti/ios-bank-manager/commit/cf4cdf8a7666ab39920a6fc8c364636d79e4a67e) |[After](https://github.com/iOS-Yetti/ios-bank-manager/blob/daa1cfea50fef6e79e41a77128bf3f29dc66f74f/BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift) |

## 조언이 필요한 점
### 1. DispatchQueue.global().async과 mutating
구조체인 Bank타입의 DispatchQueue.global().async내부에서 mutating이 붙은 메서드를
호출하면 에러가 발생하였습니다.
값타입인 구조체를 여러 스레드에서 동시에 접근하여 수정하면 스레드 안전성을 보장할 수 없기 때문에 에러를 발생시킨다는 것이였습니다.
구조체를 클래스로 변경하여 해결하였습니다만 
1. 참조타입은 왜 문제가 되지 않는지
2. 비동기 내부에서 호출한 메서드에 self가 붙어야하는 이유가 무엇인지
    - 현재 스레드의 참조(self)의 메소드를 뜻하는 것 같은데 맞을까요?
3. 또한 저번에 말씀하신 weak self가 관련이 있는 것같은데 이때 적용하는게 맞을지 궁금합니다

2023-07-21 07:48 UTC, July911 requested changes

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            DispatchQueue.global().async(group: group) { [self] in
[self] 는 어떤 의도인건가요 ?

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +class Bank {
상속하나요 ?

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private var loanQueue: CustomerQueue<Customer> = CustomerQueue()
꼭 밖에 있어야하나요 ?

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private func workFinish() {
workFinish 는 일 종료를 의미하는건가요 ? 
그렇다면 위의 이름들과 통일성이 없는 컨벤션 같습니다.

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +                       Banker(task: .loan)]
지금은 2명 1명으로 고정된 deposit, loan 업무를 맡는 은행원이지만, 파라미터로 확장성을 줄 수 없을까요 ?

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        let customerNumbers = Int.random(in: 10...30)
10...30 는 타입으로 어떻게 쓸 수 있을까요 ?

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankTask.swift
> +enum BankTask: CaseIterable {
CaseIterable 은 무엇이고 iteration는 무엇일까요 ?

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +    private(set) var task: BankTask
task가 바뀌나요 ?

2023-07-21 07:48 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    init(queueNumber: Int? = nil, task: BankTask) {
(queueNumber: Int? = nil, task: BankTask) 
옵셔널인 값이 뒤에 오는게 좋아보이네요.

2023-07-21 08:01 UTC, July911 commented
## 1. 스레드를 작업시마다 생성,삭제가 반복되게 해야할지 유지해야할지
기존엔 dispatchQueue를 Banker타입의 work메서드 내부에서 사용하여
work메서드가 실행될때마다 새로운 스레드가 생성되는 방식이였습니다. 그로인해 불필요해보이는 스레드가 많이 생겼고, 작업을 끝내면 사라지는 스레드라고 하지만 애초에 은행원 수 만큼의 스레드만 생성되는게 맞다고 생각하여 수정해 보았습니다.

아주 잘하셨습니다 ! 

질문.  DispatchQueue.global().async과 mutating

## 2. 커밋명 
 [fec762e](https://github.com/yagom-academy/ios-bank-manager/pull/320/commits/fec762e057e9dd88957e5b3b3890a3d51a5ec273)

이 커밋 이름이 이게 맞을까요 ? 

## 3. 질문 

1.비동기 내부에서 호출한 메서드에 self가 붙어야하는 이유가 무엇인지

답변: https://jusung.gitbook.io/the-swift-language-guide/language-guide/07-closures -> self. 로 검색 

2.현재 스레드의 참조(self)의 메소드를 뜻하는 것 같은데 맞을까요?
3. 저번에 말씀하신 weak self가 관련이 있는 것같은데 이때 적용하는게 맞을지 궁금합니다 
-> 맞습니다. 그래서 저번 스텝에서 공부를 한 뒤 이번 스텝에 적용시켜보는게 좋다고 생각해서 미리 말씀드린겁니다. ! 

참고1. ARC https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/ 
참고2. https://www.donnywals.com/closures-in-swift-explained/


2023-07-21 08:04 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            DispatchQueue.global().async(group: group) { [self] in
1. [ ] 는 뭐라고 부르나요 ?

2023-07-21 08:05 UTC, July911 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private var loanQueue: CustomerQueue<Customer> = CustomerQueue()
밑에서 class로 수정하셨는데, 그럼 var일 이유가 있나요 ?

2023-07-23 07:43 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Customer.swift
> +    init(queueNumber: Int? = nil, task: BankTask) {
두 매개변수의 위치를 바꿔주었습니다

2023-07-23 07:43 UTC, redmango1447 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +            DispatchQueue.global().async(group: group) { [self] in
capture list입니다. capture list는 closure 안에서 사용할 객체를 정의하는 목록입니다. DispatchQueue.global().async메서드는 인자 excute로서 escaping 클로저가 전달됩니다. escaping 클로저가 인자로 전달되는 경우 함수가 끝나 함수의 인자가 없어져도 클로저가 작동될 수 있는데 이는 암묵적으로 주변환경을 capture했기 때문입니다. 이때 capture한 변수나 상수등을 사용할때 self.을 명시적으로 언급해야하는데 캡쳐리스트에 [self]를 명시함으로서 self.접두사를 반복사용하지 않아도 self를 참조하게 할수 있습니다. 다만 이때 self는 강한 참조임으로 순환 참조가 발생 할 수 있어서 [weak self]를 사용하는게 권장된다고하여서 기존의 [self]를 [weak self]로 수정하였습니다.

2023-07-23 07:44 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Banker.swift
> +    private(set) var task: BankTask
task는 변하지 않기 때문에 let으로 수정해주었습니다.

2023-07-23 07:44 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankTask.swift
> +enum BankTask: CaseIterable {
CaseIterable은 열거형의 모든 case들을 배열처럼 순회(iteration)할 수 있도록 도와주는 프로토콜입니다. `BankTask.allCases.randomElement()`를 사용하여 고객의 업무를 랜덤하게 지정해주기 위해서 채택하였습니다.

2023-07-23 07:45 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +        let customerNumbers = Int.random(in: 10...30)
10...30이라는 범위를 타입으로 표현하는 방법에는 `ClosedRange<Int>`라는 타입으로 선언하는 방법이 있습니다. 그래서 해당 타입으로 수정해주었는데 `1...customerNumbers` 이렇게 범위 연산자를 사용해 반복문을 돌리려다보니 `Int`타입이아니라 `ClosedRange<Int>`타입이라 에러가 발생했습니다. 해당 문제를 for문이 아닌 forEach반복문을 이용하는 방법으로 해결해주었습니다.

2023-07-23 07:45 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/BankManager.swift
> +                       Banker(task: .loan)]
매개변수로 각 업무의 은행원 수를 받을 수 있는 메서드로 수정해주었습니다!

2023-07-23 07:45 UTC, redmango1447 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +class Bank {
상속을 하지 않아 final 키워드를 붙여주었습니다!

2023-07-23 07:45 UTC, iOS-Yetti commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private func workFinish() {
`startBankService()`메서드와의 통일성을 고려해`notifyEndBankService()`라는 메서드명으로 수정해주었습니다!

2023-07-23 07:47 UTC, redmango1447 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank/Bank.swift
> +    private var loanQueue: CustomerQueue<Customer> = CustomerQueue()
>꼭 밖에 있어야하나요 ?

group은 꼭 밖에 있을 필요가 없어서 메서드 내부로 옮겼지만 Queue와 bankers는 상의끝에 은행타입이 가지고 있어야하는 속성이라고 생각되어 밖에 선언해주었습니다. 

>밑에서 class로 수정하셨는데, 그럼 var일 이유가 있나요 ?

CustomerQueue를 class로 수정해주었기 때문에 상수로 설정해주면 값 변경은 불가능하지만 내부 속성은 변경 가능합니다. enqueue, dequeue를 통해 내부 속성만 변경해주기 때문에 let으로 수정해주었습니다.

2023-07-24 06:03 UTC, closed without merging