은행창구 매니저 [STEP 4] Erick, Serena
yagom-academy/ios-bank-manager pull request #321
Opened 2023-07-21 12:06 UTC by h-suo

@YebinKim 
안녕하세요.
Erick & Serena 조입니다⭐️
은행창구 매니저 프로젝트 마지막 PR 보냅니다.
항상 꼼꼼히 챙겨주셔서 감사합니다!
리뷰 잘 부탁드립니다~!

-----

## 구현한 내용
`Console App`에서 구현하였던 은행을 `UI App`에서도 구동될 수 있도록 하였습니다.
은행의 업무가 진행된 시간을 알 수 있는 타이머를 구현하였습니다.
> 주요 내용 : UI 코드 구현, MVC, Timer

-----

## 고민한 부분
### 🔥 화면 회전 / scrollview
- 화면 회전을 해도 `UI`가 정상적으로 출력될 수 있도록 `scrollView`를 뷰의 안전구역 내에 위치해주도록 해주기 위해 `view.safeAreaLayoutGuide`와 `constraint`를 설정해주었습니다.
    ```swift
    private func setUpScrollViewConstraints() {
        NSLayoutConstraint.activate([
            scrollView.frameLayoutGuide.leadingAnchor.constraint(equalTo: safeAreaLayoutGuide.leadingAnchor),
            scrollView.frameLayoutGuide.trailingAnchor.constraint(equalTo: safeAreaLayoutGuide.trailingAnchor),
            scrollView.frameLayoutGuide.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor),
            scrollView.frameLayoutGuide.bottomAnchor.constraint(equalTo: safeAreaLayoutGuide.bottomAnchor)
        ])
    }
    ```
- 화면 스크롤을 `대기중/업무중` `stackView`만 스크롤이 되도록 할지 전체 화면을 모두 스크롤을 할지 고민했습니다.
    - 앱을 이용할 때 화면 내 뷰객체가 스크롤되는 것보단 전체 화면을 스크롤 하는 쪽이 접근성이 더 좋다고 생각하여 전체화면이 스크롤 되도록 설정하였습니다.
    - 특히 야곰 닷넷을 통해 배운 내용 또한 활용하였습니다. 스크롤뷰 설정 시 frame과 multiply을 1로 맞춘 후 constant 1값을 주면 contentview의 크기가 작아도 드래그 및 스크롤의 효과를 내었습니다

### 🔥 Operation
- `GCD`로 구현되어 있던 비동기 로직을 `Operation`으로 변경하였습니다.
    - `BankClerk`을 업무별로 나눠 인스턴스를 생성하는 것이 아닌 업무별로 `OperationQueue`를 나눠 생성하여 스레드 관리를 하였습니다.
    - 그리고 `BankClerk.carryOutBankService`를 `BlockOperation`으로 타입화하여 업무별 `Queue`에 넣어주는 것으로 비동기 처리를 하였습니다.
    - `초기화` 버튼을 눌렀을 때 이미 큐에 들어간 작업을 `cancelAllOperations`를 이용하여 취소하였습니다.
- `Operation`으로 작업을 타입화 시켜줄 수 있고, `Queue`를 이용한 작업관리가 더 쉬워 코드가 간결하며 가독성이 좋아져 `Operation`으로 변경하였습니다.
    ```swift
    class Bank {
        // ...
        private let loanOperationQueue: OperationQueue = {
            let operationQueue = OperationQueue()
            operationQueue.maxConcurrentOperationCount = WorkType.loan.numberOfBankClerk

            return operationQueue
        }()

        private let depositOperationQueue: OperationQueue = {
            let operationQueue = OperationQueue()
            operationQueue.maxConcurrentOperationCount = WorkType.deposit.numberOfBankClerk

            return operationQueue
        }()
        
        // ...
        private func startBankService() {
            while !waitingLine.isEmpty {
                guard let currentCustomer = waitingLine.dequeue() else { return }
                let operation = BlockOperation { BankClerk.carryOutBankService(for: currentCustomer) }

                switch currentCustomer.workType {
                case .deposit:
                    depositOperationQueue.addOperation(operation)
                case .loan:
                    loanOperationQueue.addOperation(operation)
                default:
                    print("workType이 nil입니다.")
                }
            }
        }

        func stopBankService() {
            // ...
            depositOperationQueue.cancelAllOperations()
            loanOperationQueue.cancelAllOperations()
        }
    }
    ```

### 🔥 MVC
- `Model`, `View`, `Controller`의 역할에 대해 고민했습니다.
    - 또한 객체가 서로의 프로퍼티에 직접 접근하는 것이 아닌 메서드를 통한 의사소통을 해야한다고 생각했습니다.
- **View**: `View`는 `View`객체를 프로퍼티로 가지고 `Constraints` 코드와 `View`객체에 데이터를 세팅할 수 있는 메서드를 가지고 있습니다.
- **Model**: 비즈니스 로직을 실행시킬 수 있는 코드와 `Controller`에서 이를 실행 시킬 수 있는 메서드를 가지고 있습니다.
- **Controller**: `View`와 `Model`을 객체로 가지고 있고 사용자의 입력이나 특정 이벤트가 발생했을때 뷰를 업데이트 시키거나 `Model`의 로직을 실행시킵니다.

### 🔥 Swift Package Manager를 활용하여 콘솔앱과 UI
- 기존에 구현한 콘솔앱 프로젝트를 활용하여 새롭게 UI프로젝트를 진행함에 있어 어떻게 파일을 합칠지 고민을 했습니다. 콘솔앱 프로젝트에 구현한 파일의 경로를 추적하여 파일을 공유하는 방법도 가능하지만 이 방법을 사용할 경우 UI프로젝트를 위해 파일을 변경할 경우 콘솔앱의 프로젝트도 함께 수정된다는 단점이 존재했습니다.
- 콘솔앱과 UI 프로젝트 모두 `Queue`, `Linked-List`, `Customer` 등 큐 구조와 `Customer` 내용을 로컬 `framework`로 만들었습니다. 프레임워크를 활용하는데 `CocoaPods`, `Carthage`, `SPM` 등 여러 방법이 있지만 로컬로 바로 연동이 가능한 `SPM`을 사용하여 콘솔앱 프로젝트의 공통 내용을 UI 프로젝트에 적용하였습니다

### 🔥 Public 키워드
- `swift packmanager`를 사용하여 `customer` 로컬 패키지를 생성하여 활용하는 과정에서 직접 만든 패지를 활용하다보니 새로운 문제에 직면했습니다. 기본적으로 설정되어있는 `internal`을 모듈 외부에서도 사용가능하게 수정해야하는 문제였습니다. 모듈 외부에서 사용 가능하게 하는 접근제어자에는 `public`과 `open`이 있습니다. 이 둘의 차이점을 고려하여 적용하고자 하였습니다.
- `open`과 `public`은 모두 외부에 개방이 되어 있어 모듈 밖에서 모두 접근이 가능하다는 공통점이 있지만, `open`의 경우 오버라이드, 서브클래싱이 가능하지만 `public`의 경우 오버라이드, 서브클래싱이 불가능합니다. 이러한 차이를 고려을했을 때 정형화된 큐와 `Customer` 객체를 공유하고자 프레임워크를 생성한 저희의 의도에는 `public`이 더 적절하다 생각하여 `public`을 을각 메소드, 프로퍼티별로 추가하였습니다.
    ```swift
    public struct Customer {
        public let waitingNumber: Int
        public let workType: WorkType? = WorkType.allCases.randomElement()
    
        public init(waitingNumber: Int) {
            self.waitingNumber = waitingNumber
        }
    }
    ```

### 🔥 스크롤 시 타이머 멈춤
- 화면을 스크롤 시 타이머가 멈추는 문제가 있었습니다.
- 사용자가 스크롤을 했을 때 `RunLoop`가 `tracking `모드로 바뀌어 타이머가 실행되지 않는 문제였습니다.
- 이를 해결하기 위해 현재 런루프에 타이머를 `.common` 모드로 등록하였습니다.
    - `.common`: 하나 이상의 다른 실행 모드를 포함한 모드
    ```swift
    RunLoop.current.add(timer, forMode: .common)
    ```

-----

## 조언을 얻고 싶은 부분
### ⭐️ Timer vs. DispatchSourceTime의 차이
**Timer**
- 특정 시간 간격이 경과한 후 대상 개체에 지정된 메시지를 보냅니다.
- 주로 메인 스레드에서 실행되며 단순한 반복작업을 수행할 때 사용한다고 이해했습니다.

**DispatchSourceTimer**
- 타이머를 기반으로 이벤트 핸들러 블록을 제출하는 디스패치 소스입니다.
- GCD에서 제공하는 기술로 타이머가 멀티 스레드에서 실행될 수 있어 백그라운드 환경에서도 실행될 수 있습니다.

타이머를 구현할 수 있는 두가지 방법 중 현재 앱은 백그라운드에서는 타이머가 실행이 안되고 업무 중일때만 실행이 되며 단순한 반복작업(타이머 카운트에 대한 UI 업데이트)만 수행하면 된다고 생각하여 `Timer`를 이용하여 구현하였습니다.
저희가 선택한 방법이 적절한지 `Timer`와 `DispatchSourceTimer` 선택에 대한 븨븨의 기준이 있는지 궁금합니다!
또한 DispatchSourceTimer에 대한 자료가 많이 없어서 활용 시 어려움이 많았습니다. 특히 cancel, suspend 등 메소드들을 적극적으로 활용해보고자 노력해보았는데 이를 효율적으로 사용모하지 못해서 아쉬운 점이 많았습니다. 이런 부분에서 븨븨께서 조언을 주신다면 적극적으로 배워보고 싶습니다!

-----

## 참고자료
- [🍎 Apple Developer: Operation](https://developer.apple.com/documentation/foundation/operation)
- [🍎 Apple Developer: Accesscontrol](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol/)
- [🍎 Apple Developer: Timer](https://developer.apple.com/documentation/foundation/timer)
- [🍎 Apple Developer: Dispatchsourcetimer](https://developer.apple.com/documentation/dispatch/dispatchsourcetimer)

2023-07-21 20:21 UTC, YebinKim requested changes
세레나, 에릭 안녕하세요! 😆
은행창구 매니저 프로젝트 마지막 스텝의 진행까지 고생 많으셨습니다 👏👏

고민한 부분을 공유해주신 덕분에 코드를 이해하는 데 도움이 되었어요! 특히 MVC 아키텍쳐의 구현과 SPM 을 활용하신 부분이 인상깊었어요 🤩

아키텍쳐의 Controller 와 View 가 잘 분리될 수 있도록 `ViewController` 에서 `View` 를 분리하고 델리게이트 패턴을 채택한 방법은 멋진 구현이었다고 생각합니다 👍

그리고 저는 콘솔앱과 UI앱이 코드를 공유하며 기존 콘솔앱의 코드를 수정하지 않고 그대로 UI 구현만 진행할 수 있도록 스텝을 진행하는 방법을 생각했는데, 코드 공유로 인해 발생할 수 있는 문제점을 의도적으로 피하고 SPM을 활용하는 것도 하나의 방법이었다고 생각합니다.

---

### 1. Timer vs. DispatchSourceTime의 차이

제가 `DispatchSourceTimer`를 사용해본 적이 없어서 이번에 처음 고민해보게 되었는데요 🤔
우선 말씀해주신 차이점과 더불어 `Timer` 는 런루프를 기반으로 동작하고 `DispatchSourceTimer` 는 GCD를 기반으로 동작한다는 점 또한 차이가 있는 것으로 보여요.
또한, 간단한 구현이 가능하다고 말씀해주신 것과 같이 `Timer` 는 class 타입으로 인스턴스를 생성해 바로 사용할 수 있지만, `DispatchSourceTimer` 는 protocol 타입으로 해당 타입을 채택해 타이머 동작을 위한 코드를 작성해줘야 하기 때문에 좀 더 저수준의 API를 제공한다는 점도 주요한 차이점에 해당한다고 생각했어요. (저수준의 API를 제공할수록 구현 시 더 많은 커스텀 동작을 추가할 수 있기 때문)

현재 상황에서 두 방법 중 어떤 방법이 뚜렷하게 더 나은가는 정답이 없다고 생각해요 😄
동작 메커니즘이 다르기 때문에 성능 차이 또한 발생할 수 있겠지만 현재의 요구사항 안에서는 유의미한 차이가 발생하지 않는다고 생각하고, 앞서 발생했던 문제점인 `스크롤 시 타이머 멈춤`의 상황에서 터치 이벤트와 타이머 이벤트가 둘 다 런루프 기반으로 동작하기 때문에 충돌이 발생해서 문제를 해결할 수 없었다면  `DispatchSourceTimer` 또는 이번에 언급되지 않은 구현 방식인 Combine의 Timer 등을 고려해볼 수 있었겠지만 `Timer` 를 사용하는 현재 잘 해결되었기도 하구요.

그래서 두 방법 중 무언가를 고르는 데 정답이 없고 현재와 같이 요구사항이 백그라운드에서의 타이머 실행이 필요하지 않다는 점 그리고 더 간단한 구현 방식을 채택한 것 또한 충분히 납득 가능한 이유라고 생각합니다!

---

이번 스텝에서의 핵심 경험은 아래와 같았는데요.
<img width="416" alt="Step4" src="https://github.com/yagom-academy/ios-bank-manager/assets/38066039/20e62aa1-4a31-4b42-b0a1-dd1ef6e0525c">

이에 관해서는 모두 충분히 경험하셨다고 생각해요!! 👍👏

다만, 사용하지 않는 타입의 삭제와 관련해 p2 코멘트가 있어 Request Changes 로 리뷰 의견 드렸어요~
그 외에도 코멘트 몇 가지 남겨두었는데, 혹시 궁금하신 점이 있다면 편히 연락 주세요 🔥🚀

2023-07-21 20:21 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/ViewController/ViewController.swift
> +class BankManagerViewController: UIViewController {
p3;

마찬가지로 상속 가능성이 없는 클래스라면 `final` 키워드를 붙여보면 어떨까요? 👀

2023-07-22 12:48 UTC, h-suo commented on BankManagerUIApp/BankManagerUIApp/Model/Bank/Bank.swift
> +    func addCustomer() -> [Customer] {
`[Customer]`를 반환하는 메서드이니 `addedCustomer`로 리네임하였습니다!

2023-07-22 12:48 UTC, h-suo commented on BankManagerUIApp/BankManagerUIApp/Model/Bank/Bank.swift
> +class Bank {
`final` 키워드 추가하였습니다!

2023-07-22 12:48 UTC, h-suo commented on BankManagerUIApp/BankManagerUIApp/ViewController/ViewController.swift
> +class BankManagerViewController: UIViewController {
`final` 키워드 추가하였습니다!

2023-07-22 12:52 UTC, serena0720 commented on BankManagerUIApp/BankManagerUIApp/Model/Bank/BankManager.swift
> +}
콘솔앱의 구조를 최대한 살리면서 UI앱의 구조를 짜보고자 하는 과정에서 Bankmanager의 역할을 고민했습니다. 프로젝트 끝까지 Bankmanager의 역할을 고민하다보니 Bankmanager가 비어있는 채로 프로젝트를 마무리하게된 거 같습니다😅 Bankmanager의 역할은 없는 듯 하여 삭제하였습니다! 꼼꼼한 리뷰 감사합니다~

2023-07-22 13:02 UTC, serena0720 commented on BankManagerUIApp/BankManagerUIApp/Model/Bank/Bank.swift
> +        issuedWaitingNumber += 10
넵! `BankNameSpace` 선언하여 매직 넘버 수정하였습니다!

2023-07-22 13:07 UTC, h-suo commented on BankManagerUIApp/BankManagerUIApp/Model/WorkTimer.swift
> +    var isRunning: Bool = false
`private(set)`으로 외부에서 읽기로만 접근할 수 있도록 접근제한을 하였습니다!

2023-07-22 13:08 UTC, h-suo commented on BankManagerUIApp/BankManagerUIApp/View/BankManagerView.swift
> +    var waitAndWorkStackViewisEmpty: Bool {
`isWaitAndWorkStackViewEmpty`로 `Bool` 타입 프로퍼티 네이밍 규칙에 맞게 리네임하였습니다!

2023-07-22 13:08 UTC, serena0720 commented on BankManagerUIApp/BankManagerUIApp/Model/WorkTimer.swift
> +enum WorkTimerNameSpace {
꼼꼼한 리뷰 감사합니다!😍 private으로 접근제어하였습니다!

2023-07-22 13:19 UTC, h-suo commented on BankManagerUIApp/BankManagerUIApp/ViewController/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(deleteCustomerToWork(_:)), name: NSNotification.Name("업무종료"), object: nil)
`Notification.Name`를 확장하여 `workStart`, `workEnd` 프로퍼티 생성하여 `Notification.Name`을 재사용할 수 있도록 하였습니다.

2023-07-22 13:47 UTC, YebinKim commented on BankManagerUIApp/BankManagerUIApp/Model/Bank/Bank.swift
> +    func addCustomer() -> [Customer] {
복수형의 메서드 네이밍 적용 또한 필요해보입니다 👀

2023-07-22 14:06 UTC, YebinKim approved these changes
에릭, 세레나 안녕하세요~
Step4 수정까지 고생 많으셨습니다!! 🙌

코멘트 남겨주신 내용들 모두 확인했어요! 이번 스텝은 여기서 머지하도록 할게요.
은행창구 매니저 프로젝트 완주 축하드려요 🥳🎉

2023-07-22 14:06 UTC, merged