은행창구 매니저[Step2] 토이, 쥬봉이
yagom-academy/ios-bank-manager pull request #327
Opened 2023-11-16 11:28 UTC by DevWooHyeon

@1Consumption
안녕하세요 올라프☃️ step2 PR 보냅니다!!
잘부탁드립니다~

### 고민이 되었던 점
1. Bank Manager Package의 역할
- package는 console app과 UI app에서 채택하기때문에 프로젝트를 구현하는데 있어 이 두 앱의 공통적인 사항을 가지고 있는 모듈로 생각하였습니다.
- CustomerQueue, LinkedList, Node, BankManager는 `두 앱에서 모두 사용된다고 생각`하여 `구조체 또는 클래스로 구현하`여 packages에 넣어주었습니다.
- 위의 모델 외에 Bank, BankClerk, Customer는 `앱에 따라 내부 구현이 달라진다고 생각`하여 각각의 `모델의 공통사항을 담은 protocol`을 만들어 Pacakage에 넣어주었습니다.
    - Bank -> BankBusinesable protocol
    - BankClerk -> Receivable protocol
    - Customer -> CustomerNumbering protocol
- console 앱에서는 각 프로토콜을 채택하여 구현하였습니다.

2. 각 모델의 역할
- `bank manager` : 고객을 순서에 맞게 대기시키고(enqueue), 고객을 순서대로 은행원에게 배정하는 역할(dequeue)을 합니다.
- `customer` : number를 가지고 있는 고객입니다.
- `bankClerk ``: pace(일 속도) 프로퍼티를 가지고, 고객의 일을 처리하는 역할(업무 시작과 끝 print)입니다.
- `bank` : 위의 모델들이 활동하는 공간으로 고객 수에 맞게 고객 인스턴스를 만들어 Bank manager에게 전달합니다. open 메서드 속에서 bank manager와 bank clerk이 일을하고, 일이 끝나면 close를 호출해 print하고 업무가 종료됩니다.
- `console manager` : console 메뉴를 출력하고 사용자의 입력을 받아 Bank를 실행시키거나 프로그램을 종료하는 역할을 합니다. enum으로 만들어 인스턴스를 만들지 않고 사용 가능하도록 구현하였습니다.

3.총 업무시간 생성 방법 : 실제 작동 시간 vs 연산으로 만든 시간
- 코드에 실제 작동시간을 구현 하였는데 연산으로 만든 시간을 출력하는 것은 연산하는 코드를 추가해야 하기 때문에 불필요한 코드 작성이라고 생각 하여 연산으로 만든 시간을 적용하는 것이 적절하지 않다고 판단하였고 실제 작동시간을 그대로 출력하도록 구현 하였습니다.

- 그리고 소수점 2번째 자릿수 까지만 프로젝트에 표현되어 있어서 `String(format:_:)`을 사용하여 요구사항에 맞게 구현하였습니다.

- [CFAbsoluteTimeGetCurrent()](https://developer.apple.com/documentation/corefoundation/1543542-cfabsolutetimegetcurrent) 사용 : 현재 시스템의 절대 시간을 반환하는 함수입니다.

### 조언을 구하고 싶은 부분
1. `usleep과 Thread.sleep 선택`이 고민됩니다.
- 현재 `bankClerk이 일을 처리할 때 0.7초 소요되는 것을 나타내기위해` usleep을 사용하고 있습니다.
- `Thread.sleep(forTimeInterval:)` : thread를 해당 시간만큼 멈추는 함수로 thread를 잠재우는 것은 적절하지 않다고 판단해서 사용하지 않았습니다.
- `sleep(), usleep()` : c언어로부터 온 함수로 공식문서에는 해당 함수가 없어 작동 원리는 찾기 어려웠습니다. 일단 찾아본바로는 [sleep_in_ios](https://gist.github.com/SheldonWangRJT/0cb2997e51ba96bcee97fc4edd6e68dc)에서는 이 함수들이 operation을 멈추는 것으로 추정된다고 나와있습니다. 그래서 이 함수들을 선택했고, 두 함수 모두 UInt32를 매개변수로 받기에 0.7초를 변형하여 사용할 수 있는 usleep()을 사용하였습니다.
- 해당 부분이 적절한지 궁금합니다.

2. protocol을 사용하여 구현한 현재 모델의 방향성이 적절한지 고민됩니다.
- Bank, BankClerk, Customer에 각각의 프로토콜을 구현하여 Library에 추가하고 해당 타입에서 해야할 최소한의 요구조건들을 구현하였습니다. 모델의 분리가 적절한지 그리고 저희가 만든 프로토콜의 방향성이 적절한지 조언을 구하고 싶습니다.
    - Bank -> BankBusinesable protocol
    - BankClerk -> Receivable protocol
    - Customer -> CustomerNumbering protocol
- api-design-guidelines을 읽었음에도 프로토콜 네이밍이 어렵습니다🥲 예를들어 위처럼 특정타입을 구현하기위한 프로토콜을 어떤 이름으로 짓는게 좋은지 잘 모르겠습니다.
> Protocols that describe what something is should read as nouns (e.g. Collection).
Protocols that describe a capability should be named using the suffixes able, ible, or ing (e.g. Equatable, ProgressReporting).

### 구현 화면
![콘솔](https://hackmd.io/_uploads/B1No2dXVT.gif)

2023-11-16 12:47 UTC, 1Consumption requested changes
고생하셨어요. @DevWooHyeon @jyubong 

고민하신 점에 적어주신 부분은 코멘트에 달았다고 생각됩니다.

다른 궁금한 점이 있으면 언제든 말씀해주세요.

2023-11-16 12:47 UTC, 1Consumption commented on BankManager/Sources/BankManager/Protocol/Receivable.swift
> +}
`Receivable`이라는 이름은 너무 추상적이네요. 조금 더 구체적으로 지으면 좋을 것 같아요.

2023-11-16 12:47 UTC, 1Consumption commented on BankManager/Tests/BankManagerTests/BankManagerTests.swift
>  }
파일 자체를 없애도 될 것 같아요.

2023-11-16 12:47 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +enum ConsoleManager {
enum으로 만든 이유가 궁금해요~

2023-11-16 12:47 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +        }
"1", "2" 같은 매직넘버가 아니라, enum case로 만들면 더 좋을 것 같아요.

2023-11-16 12:47 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +    }
computed property와 method를 나누는 기준이 있을까요?

2023-11-16 12:47 UTC, 1Consumption commented on BankManager/Sources/BankManager/Protocol/BankBusinesable.swift
> +    var bankManager: BankManager<Bankclerk> { get }
이 프로퍼티가 꼭 필요할까요? 외부에서는 `open` 메소드만 알면 될 것 같은데요.

2023-11-16 12:47 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        }
for in loop을 사용하지 않은 이유가 궁금해요

2023-11-16 12:47 UTC, 1Consumption commented on BankManager/Sources/BankManager/Protocol/Receivable.swift
> +    var pace: Double { get }
사실 이 정보도 외부에서 알 필요가 있나싶어요.

2023-11-16 12:47 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        usleep(uSeconds)
> `이 함수들이 operation을 멈추는 것으로 추정된다고 나와있습니다.`

라고 적어주셨는데, 그럼 그 operation은 어디서 실행되는건가요? 결국 쓰레드에서 실행되는 것 아닌가요?

2023-11-16 12:47 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        print("\(number)번 고객 업무 완료")
이런 print문은 테스트하기 어려워요. 그래서 이런 경우는 클로저를 주입해주면 테스트하기 훨씬 수월해집니다.

2023-11-17 03:19 UTC, jyubong commented on BankManager/Sources/BankManager/Protocol/Receivable.swift
> +}
https://github.com/yagom-academy/ios-bank-manager/pull/327/commits/73a2d9aed3c7e2c542458df56439f55f9ef16811
Receivable을 `CustomerReceivable`로 수정하여 `고객을 응대할수있는`의미로 변경해보았습니다.

2023-11-17 03:22 UTC, DevWooHyeon commented on BankManager/Tests/BankManagerTests/BankManagerTests.swift
>  }
해당 파일을 삭제 했습니다!
https://github.com/yagom-academy/ios-bank-manager/commit/9a2b56a710917953c5ff31c08da90f2f3fb0f891

2023-11-17 03:22 UTC, DevWooHyeon commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +        }
중첩타입을 사용해서 Message 열거형을 만들어 매직넘버를 해결하였습니다.
https://github.com/yagom-academy/ios-bank-manager/commit/02f14fd752e86e2409f294e563b0985c8475886e

2023-11-17 03:23 UTC, DevWooHyeon commented on BankManager/Sources/BankManager/Protocol/BankBusinesable.swift
> +    var bankManager: BankManager<Bankclerk> { get }
해당 프로퍼티가 protocol에 요구사항으로 필요하지 않다고 생각되어 protocol에서 open메서드만 요구사항으로 가질수 있도록 수정하였습니다.
https://github.com/yagom-academy/ios-bank-manager/commit/a856abcd1687e79f463b1a42b7497c1e1eae320b

2023-11-17 03:23 UTC, DevWooHyeon commented on BankManager/Sources/BankManager/Protocol/Receivable.swift
> +    var pace: Double { get }
작업 시간을 가지는 pace프로퍼티는 외부에서 알필요가 없다고 생각되어 프로토콜 요구사항에서 제거하였습니다.
https://github.com/yagom-academy/ios-bank-manager/commit/327465f180dc777b54cc9fca7ab252c5ce9e0c44

2023-11-17 03:26 UTC, jyubong commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +enum ConsoleManager {
enum과 struct 중에 고민을 하였습니다.
console manager는 여러 객체를 생성할 필요성이 없다고 생각했습니다. 그래서 인스턴스를 만들지 않고 타입으로 접근해 메서드를 부르기위해 enum을 선택하였습니다.

2023-11-17 03:29 UTC, jyubong commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +    }
매개변수 없이 return만 필요하고 비교적 구현이 간단하다면 computed property를, 그외에는 method로 구현하고 있습니다.
해당 메서드는 return만 있으므로 computed property로 구현하는 것이 적절하다고 생각하여 변경해주었습니다.

2023-11-17 03:37 UTC, jyubong commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        usleep(uSeconds)
집어주신대로 sleep() 또한 thread를 일시정지시키는 함수로 생각됩니다.
그래서 Thread.sleep()과 sleep() 모두 이 점은 동일하기에 double를 매개변수로 쓸 수 있는 Thread.sleep()으로 변경하였습니다.

2023-11-17 03:37 UTC, DevWooHyeon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        }
for문과 foEach의 차이점은 반복문과 클로저라는 차이점이 있습니다. forEach에서는 반복문과 switch문에서 사용가능한 `break` 와 `continue` 키워드를 사용할 수 없습니다. 하지만 저희가 작성한 코드에서는 해당 키워드가 필요하지 않습니다. 그리고 시간복잡도도 O(n)으로 동일합니다. 마지막으로 for문에 비해 forEach를 사용하는 것이 코드의 가독성이 좋다고 생각되어 forEach를 사용하여 구현하였습니다.

2023-11-17 03:40 UTC, jyubong commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankClerk.swift
> +        print("\(number)번 고객 업무 완료")
말씀해주신 내용을 토대로 클로저를 매개변수로 주입받도록 구현해보았습니다.

```swift
struct BankClerk: CustomerReceivable {
    private let pace = 0.7
    
    func receive(customer: Customer, start: ((UInt) -> Void), finish: ((UInt) -> Void)) {
        let number = customer.number

        start(number)
        Thread.sleep(forTimeInterval: pace)
        finish(number)
    }
}
```
```swift
public struct BankManager<BankClerk: CustomerReceivable> {
    public func assignCustomer(to bankClerk: BankClerk) {
        while let customer = customerQueue.dequeue() as? BankClerk.Customer {
            bankClerk.receive(customer: customer) { number in
                print("\(number)번 고객 업무 시작")
            } finish: { number in
                print("\(number)번 고객 업무 종료")
            }
        }
    }
}
```

2023-11-17 04:00 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +enum ConsoleManager {
> console manager는 여러 객체를 생성할 필요성이 없다고 생각했습니다.

사실 이 이유가 제일 궁금해요.

2023-11-17 04:02 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +        }
코멘트의 의도는 enum의 static 변수가 아니라 String을 받아 enum case로 변환 후 switch문을 통해 분기치는 것이었어요.
제한된 인풋이고, 범위를 좁히면 가독성이 더 좋다고 생각하기 때문이에요.

2023-11-17 04:04 UTC, 1Consumption commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +    }
https://www.swiftbysundell.com/tips/computed-properties-vs-methods

이런 아티클도 한번 참고해보셔도 좋을 것 같아아요.

2023-11-17 10:50 UTC, jyubong commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +enum ConsoleManager {
적절한 이유가 없어 struct로 변경하였습니다.
enum을 사용했을 경우 함수와 프로퍼티에 static을 붙여 사용했는데 전역으로 쓰이지 않는 부분도 적절하지 않은것으로 판단했습니다.

2023-11-17 10:58 UTC, jyubong commented on BankManagerConsoleApp/BankManagerConsoleApp/ConsoleManager.swift
> +        }
올라프께서 주신 조언을 바탕으로 해당 방향으로 구현해보았습니다.

2023-11-17 11:21 UTC, merged