은행창구 매니저 [Step3] Hisop
yagom-academy/ios-bank-manager pull request #332
Opened 2023-11-23 11:03 UTC by Hi-sop

@stevenkim18 
안녕하세요! STEP3 PR입니다.

## 고민이 되었던 점
GCD / Operation으로 각각 구현해보았습니다.
Operation이 가독성이나 구현이 편리하다는 장점이 있었던 것 같고, GCD는 제가 의도한대로 스레드가 동작했다는 장점이 있었습니다. 

### GCD
c6962b1c42284f1f0f6e5274d25ea8153284a0fa
업무를 처리하는 은행원을 각각의 스레드로 보았고
스레드를 직접 생성했기 때문에 은행원의 수와 스레드의 수가 같습니다.

###  operation
5869f5d4e060d3453972290d075b0f96eb140b43
예금, 대출 operationQueue를 생성하여 한번에 처리할 수 있는 max값을 은행원의 수로 보았습니다.
큐에 work를 등록할때마다 스레드가 추가되고 동시에 처리되는 스레드와 은행원의 수가 같습니다.

## 조언을 구하고 싶은 부분

await / async를 사용할 때 비동기로 실행되는 작업을 기다리게 하는 방법이 있을까요?
GCD의 wait(), operation의 waitUntilAllOperationsAreFinished() 같은 느낌의 동작을 수행하고 싶은데 찾지 못했습니다.

2023-11-23 15:11 UTC, stevenkim18 commented
>GCD / Operation으로 각각 구현해보았습니다.
>Operation이 가독성이나 구현이 편리하다는 장점이 있었던 것 같고, GCD는 제가 의도한대로 스레드가 동작했다는 장점이 있었습니다.

어떤 장단점이 있었나요?

2023-11-23 15:22 UTC, stevenkim18 commented
>GCD

>https://github.com/yagom-academy/ios-bank-manager/commit/c6962b1c42284f1f0f6e5274d25ea8153284a0fa
>업무를 처리하는 은행원을 각각의 스레드로 보았고
>스레드를 직접 생성했기 때문에 은행원의 수와 스레드의 수가 같습니다.

>operation

>https://github.com/yagom-academy/ios-bank-manager/commit/5869f5d4e060d3453972290d075b0f96eb140b43
>예금, 대출 operationQueue를 생성하여 한번에 처리할 수 있는 max값을 은행원의 수로 보았습니다.
>큐에 work를 등록할때마다 스레드가 추가되고 동시에 처리되는 스레드와 은행원의 수가 같습니다.

앗! 커밋으로 변경사항이 보이니까 보기가 좀 어렵네요😭
직접 코드를 첨부해주셨으면 더 좋았을 것 같습니다!

2023-11-23 16:01 UTC, stevenkim18 requested changes

2023-11-23 16:01 UTC, stevenkim18 commented on BankManager/Sources/BankManager/Bank.swift
> +        }
한 함수에서 많은 역할을 하고 있는 것 같아요!!

조금 더 함수로 분리 할 수는 없을까요?

2023-11-23 16:01 UTC, stevenkim18 commented on BankManager/Sources/BankManager/Business.swift
> +enum Business: String, CaseIterable {
`CaseIterable`를 사용하신 이유가 있으신가요?

2023-11-24 07:10 UTC, Hi-sop commented on BankManager/Sources/BankManager/Bank.swift
> +        }
makeWork에서 work를 만들어 줄 때 completionBlock내용도 같이 추가해주도록 변경해보았습니다.

2023-11-24 07:12 UTC, Hi-sop commented on BankManager/Sources/BankManager/Business.swift
> +enum Business: String, CaseIterable {
Customer를 생성할 때 Customer.Business속성에 랜덤한 업무를 부여해주기 위해 썼습니다. `Business.allCases.randomElement()`

2023-11-24 07:38 UTC, Hi-sop commented
opration은 큐에 addOperation을 넣어주면 알아서 실행된다는 장점이 있었습니다.
하지만 동시에 n개의 업무를 진행하는데 n개 이상의 여러 스레드들이 생성된다는 점이 단점이라고 생각합니다.

GCD는 제가 요청한 n개의 스레드만 생성되어 낭비가 없게 설계할 수 있다는 것이 장점이었지만
업무를 수행하는 큐와 대기열 큐가 하나 더 필요해 불편했습니다. 대기열을 수동으로 구현해야된다는 점이 단점이었습니다.
추가로 비동기로 수행시킨 업무는 반복적으로 큐에 접근해야했기에 그에 따른 세마포어도 지정해주어야했습니다.

정리하자면 opertaion은 일시정지, 종료시 실행, 의존성 등 Item을 관리하기 편하나 오버헤드로 인한 자원 소모가 있을 것 같고
 GCD는 동작이 간결하고 빠른 대신 operation에 존재하는 특수 기능들을 사용할 수 없어 불편했습니다.

2023-11-25 16:29 UTC, closed without merging