Step1 Steven, Sookim
yagom-academy/ios-bank-manager pull request #34
Opened 2021-04-28 13:17 UTC by stevenkim18

# **[STEP 1] 은행창구매니저 🏦**

@corykim0829 
안녕하세요 cory~ 😄

steven과 함께 서로 리뷰 후 리팩토링하면서  프로젝트를 진행해봤어요

리뷰 잘 부탁드립니다 ~ 

## 클래스 다이어그램
![BankManager](https://user-images.githubusercontent.com/35272802/116409960-4ce75f80-a86f-11eb-88c9-8a5a2ffb3da4.jpg)
- Bank: 은행 클래스, BankManager 인스턴스를 가지고 있음.
- BankManager: 은행 안에서 모든 것을 컨트롤하는 클래스
- CustomerMaker : 고객 인스턴스를 배열로 가지는
- Customer : 은행업무 인스턴스와 대기번호를 가지는 구조체
- BankTask : 은행 업무에 관한 작업을 하는 클래스 (Operation 상속)
- BankPrinter: 은행 프로그램에서 출력해야 될 것을 출력하는 구조체
- Inputer: 사용자의 입력을 받는 구조체

## Step1 콘솔 동작 화면
![--2021-04-28--8 27 59](https://user-images.githubusercontent.com/35272802/116410014-57095e00-a86f-11eb-8ffd-176ad5d63425.gif)

---

# **고민되었던 점, 해결되지 않은 점, 궁금한 점 ❗️❓**

## 창구 번호와 대기 순번

프로젝트 요구사항에 보면

- `은행원은 각 창구를 하나씩 담당하며, 창구에는 번호가 있습니다`
- `고객이 은행에 방문하면 대기순번을 부여받습니다`

이라고 되어있습니다.

`GCD` 대신 `Operation` 을 사용하라고 하셔서 저희는 `OperationQueue`를 사용해서 알아서 Task들이 각각의 쓰레드로 이동하게 구현했습니다.

한개의 쓰레드가 은행원 한명 혹은 한개의 창구라고 생각했어요.

그런데 이렇게 되면 각 Thread에 창구번호를 부여하고 싶은데 `OperationQueue`가 알아서 Thread를 관리해 주니 접근 할 수 있는 방법을 찾지 못하였습니다.

어떻게 하면 좋을까요?

그리고 대기 순번 같은 경우도 `CustomerMaker` 가 `Customer` 배열을 만들어 주기 때문에 따로 구현을 하지 않았습니다.. 배열에 있는 순서대로 `OperationQueue`에 들어가게 구현을 했는데... 현실 은행에서는 언제 고객이 올지 모르는데... 이렇게 구현하는 것이 맞는 걸까요?

## 시간 측정시 약간의 오차 발생

저희가 구현한 코드에서 총 업무시간을 측정하는 부분이 약간의 오차가 있는데 이 부분은 출력을 하는 부분 때문에 작은 밀리초 단위로 오차가 발생합니다.

요구사항에는 정확하게 `7.00초` 이렇게 되어 있는데 오차는 무시해도 괜찮을까요? (Timer, Date() , processTime을 고민해보았는데 모두 비슷한 오차가 있었어요 😅)

2021-04-29 21:45 UTC, corykim0829 requested changes
수고하셨습니다 👏👏👏👏

코드 깔끔하게 잘 구현하셨네요! 
좋은 고민들을 하고 계신 것 같아요! 지금 하나의 파일에 클래스나 구조체가 있지 않는데, 되도록이면 하나에 파일에는 하나의 객체가 들어가도록 해보세요!

> 한개의 쓰레드가 은행원 한명 혹은 한개의 창구라고 생각했어요.
그런데 이렇게 되면 각 Thread에 창구번호를 부여하고 싶은데 OperationQueue가 알아서 Thread를 관리해 주니 접근 할 수 있는 방법을 찾지 못하였습니다.
어떻게 하면 좋을까요?

➡️ 이 부분은 좀 더 고민을 해봐야겠네요! 먼저 다른 부분 먼저 개선해봅시다! 저도 더 고민해볼게요!

> 그리고 대기 순번 같은 경우도 CustomerMaker 가 Customer 배열을 만들어 주기 때문에 따로 구현을 하지 않았습니다.. 배열에 있는 순서대로 OperationQueue에 들어가게 구현을 했는데... 현실 은행에서는 언제 고객이 올지 모르는데... 이렇게 구현하는 것이 맞는 걸까요?

➡️ 맞아요! Customer 객체를 만들 때가 아니라 작업이 들어갈 때 번호를 부여하는 방법으로 개선하면 좋을 것 같아요!

> 시간오차

➡️ 시간 오차는 일단은 놔두고 다른 것부터 개선해봅시다!

2021-04-30 04:30 UTC, stevenkim18 commented on BankManager.swift
> +class CustomerMaker {
네 분리 했습니다!!

2021-04-30 04:30 UTC, stevenkim18 commented on BankManager.swift
> +
밖에 있는 파일을 삭제했어요!!

2021-04-30 04:30 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +class BankTask: Operation {
네네 ㅎㅎ 이 친구도 분리했어요 ㅎㅎ

2021-04-30 04:34 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +struct Inputer {
InputHelper로 변경했어요 ㅎㅎ

2021-04-30 04:45 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            return blank
아 네!! nil을 리턴하게 했습니다!!
nil을 리턴해도 `open` 함수에서 옵셔널 처리를 안해줘도 되는게 신기하네요!

2021-04-30 04:52 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func printToTwoDecimalPoint() -> String {
소수점 2자리수까지 자르는 함수라서 `cutNumberToTwoDecimalPoint`로 변경했습니다

2021-04-30 05:01 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Customer.swift
> +    init(taskTime: Double, _ waitingNumber: Int) {
아 와일드 카드를 안쓰게 되면 인스턴스를 생성 할 때 `waitingNumber: waitingNumber` 이렇게 되서 사용 한건데.. 일단 코리 의견에 따라서 와일드 카드는 제거 했습니다.

2021-05-02 16:18 UTC, corykim0829 approved these changes
수고하셨습니다! 해드린 피드백은 다음 스텝 진행하면서 수정해보세요!

그리고 BankManager를 따로 만들어서 처리하는 이유가 궁금합니다!

정말 수고 많으셨습니다! 화이팅입니다!

2021-05-02 16:18 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +struct BankPrinter {
이 파일에도 너무 많은 객체가 존재하군요! 분리하면 더 좋을 것 같습니다 :)

2021-05-02 16:18 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    static func printFinishPharse(_ totalCustomerNumber: Int, _ totalSecond: Double) {
여기도 굳이 wildcard 쓸 필요가 없을 것 같아요. 이 함수를 쓰는 사람은 설명이 없으면 각 파라미터가 어떤 역할을 하는지 알기 어려울 것 같아요!

2021-05-02 16:18 UTC, corykim0829 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
guard문은 길어서 개행이 필요하지 않으면 다음과 같이 쓰는게 더 깔끔하고 보기 좋습니다!
```suggestion
        guard let input = readLine() else { return nil }
```

2021-05-02 16:19 UTC, merged

2021-05-03 07:42 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +struct BankPrinter {
네!! 모든 구조체 클래스 enum 타입을 한 파일에 분리했습니다!

2021-05-03 07:42 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    static func printFinishPharse(_ totalCustomerNumber: Int, _ totalSecond: Double) {
여기도 와일드카드를 제거해주었습니다!

2021-05-03 07:43 UTC, stevenkim18 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        }
이 부분도 한줄로 처리해주었어요 ㅎㅎ