[STEP 1] 🏦 은행 매니저 💸 Yun, Ryan
yagom-academy/ios-bank-manager pull request #37
Opened 2021-04-30 04:13 UTC by ryan-son

@AppleCEO 

안녕하세요, 도미닉! 한 주동안 열심히 관련 내용을 학습하고 코드를 작성하여 Step 1 PR을 보냅니다!
이번 주에는 `Process`와 `Thread`, `Operation`과 `OperationQueue`의 개념을 익히고 적용하는데 주안점을 두었습니다. 도미닉의 의견을 듬뿍 담아 따끔한 피드백을 많이 받을 수 있으면 좋겠습니다! 😄

# Class Diagram
![image](https://user-images.githubusercontent.com/69730931/116639565-c97b5a80-a9a3-11eb-93c3-9a7906cc33c1.png)

# 각 타입의 역할
## `BankManager`
- 프로그램 사용자가 프로그램을 시작하고 종료할 수 있는 기능을 제공합니다.
  - `selectMenu() throws -> Int`: 사용자의 입력을 받아 입력한 숫자를 반환합니다. 정수가 아닌 입력을 할 경우 에러를 throw합니다.
  - `start()`: 프로그램을 시작하고 입력에 메뉴 이동을 수행합니다.
- 인스턴스 생성 시 이니셜라이저를 통해 `Bank` 타입에서 근무할 은행원의 수를 설정할 수 있습니다.

## `Bank`
- 은행 개점과 마감, 업무 처리 시 총 소요 시간을 계산하는 기능을 제공합니다.
- `assignTeller()`: 인스턴스 생성 시 입력 받은 `numberOfTeller` 전달 인자를 통해 한 번에 처리할 `Operation` 수를 설정합니다(`OperationQueue.maxConcurrentOperationCount`).
- `visitNewClient() -> [Client]`: 지정 범위의 임의의 수 생성 및 `OperationQueue`에 `Operation`을 할당합니다.
- `totalProcessedTime(_:) -> Double`: 전달 인자로 입력받은 클로저 내부에 입력된 메서드의 처리에 걸리는 시간을 측정하여 `processedTime` 프로퍼티에 할당합니다.

## `Client`
- `Operation` 클래스를 상속받은 타입으로 `waitingNumber` 프로퍼티를 가지고 있습니다.
- `Operation`이 실행되면 재정의된 `main()` 메서드를 통해 업무 처리 상태를 출력합니다.

# 요구 기능과 구현 방식
## 타입구현
- 은행에는 n명의 은행원이 근무합니다
  - `Bank` 타입 `waitingQueue: OperationQueue`의 `maxConcurrentOperationCount` 프로퍼티를 통해 은행원 수를 설정하였습니다.
- 은행에는 n명의 고객이 업무처리를 위해 대기합니다
  - `Bank` 타입 `visitNewClient()` 메서드에서 은행에 방문할 총 고객 수를 설정합니다. 최소/최대 인원수는 `Bank` 타입에 위치한 `NumberOfClient` 열거형에 정의된 상수로써 설정할 수 있습니다.
- 대기 중인 고객의 업무가 모두 끝나면 은행업무를 마감합니다
  - `Bank`의 `open()` 메서드는 모든 업무가 처리되면 은행을 마감하는 `close()` 메서드를 실행합니다.
- 업무를 마감할 때 "업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 XX명이며, 총 업무시간은 XX초입니다."라고 출력합니다
  - `Bank` 타입의 `close()` 메서드가 해당 기능을 담당합니다.
  - 총 소요시간은 `close()` 메서드 실행 이전에 `totalProcessedTime(_:) -> Double` 메서드를 통해 계산됩니다.
  - `totalProcessedTime(_:)` 메서드는 `CFAbsoluteTimeGetCurrent()` 메서드를 사용하여 업무 처리에 소요된 실제 시간을 산출합니다.
- 은행원은 각 창구를 하나씩 담당하며, 창구에는 번호가 있습니다
  - 창구에 번호를 부여하는 방법을 해결하지 못하였으며, 아래 `해결이 되지 않은 점`에 내용을 상세히 설명하였습니다.
- 은행원은 고객의 업무를 처리합니다
  - `visitNewClient()` 메서드에서 `OperationQueue`에 `Operation`을 할당하는 작업을 수행하여 업무를 처리하도록 하였습니다.
- 각 고객의 업무를 처리하는 데 걸리는 시간은 0.7초입니다
  - `Operation`을 상속받은 `Client`에 `TimeForProcessingTask` 열거형에 업무에 소요되는 시간을 작성하였습니다.
- 은행원이 한 번에 처리할 수 있는 고객은 한 명입니다
  - `OperationQueue`의 `maxConcurrentOperationCount` 프로퍼티를 통해 쓰레드 수를 설정함으로써 한 번에 처리할 고객 수를 설정할 수 있었으며, 하나의 쓰레드는 하나의 `Operation`을 처리함을 확인하였습니다.
- 대기중인 고객의 업무처리를 시작할 때 아래와 같이 출력합니다
    - "3번 고객 업무 시작"
    - `Operation`을 상속받은 `Client`의 인스턴스가 재정의된 `main()` 메서드를 통해 출력합니다.
- 고객의 업무를 처리하면 아래와 같이 출력합니다
    - "5번 고객 업무 완료"
    -  `Operation`을 상속받은 `Client`의 인스턴스가 재정의된 `main()` 메서드를 통해 출력합니다.
- 고객이 은행에 방문하면 대기순번을 부여받습니다
  - `visitNewClient()` 메서드가 은행에 방문한 총 고객수를 이용하여 반복문으로 `Client` 인스턴스를 생성하며 이니셜라이저를 통해 대기번호를 부여합니다.
- 고객은 업무를 처리할 담당 은행원이 배정될 때 까지 대기합니다
  - 별도로 실행하지 않으면 `Operation`이 `OperationQueue`에 할당되기 전에 실행되지 않음을 확인하였습니다.

## 콘솔앱 구현

- Step 1의 은행에는 한 명의 은행원이 근무합니다.
  - 초기 `BankManager` 인스턴스 생성 시 근무할 은행원 수를 1로 설정하였습니다.
- 앱을 실행하면 두 개의 메뉴를 출력합니다.
  1 : 은행 개점
  2 : 종료
  - `BankManager` 타입의 `selectMenu()` 메서드가 메뉴 출력을 담당합니다.
- 사용자가 1을 입력하면 은행을 개점하고 10명~30명의 고객이 방문합니다. 10에서 30 사이의 임의의 수 만큼의 고객의 업무를 처리하면 은행문이 닫히고 다시 메뉴를 출력합니다.
  - 타입 구현에서 설명한 내용입니다.
- 사용자가 2를 입력하면 프로그램을 종료합니다.
  - `BankManager` 타입의 `start()` 메서드가 이를 담당합니다.

# 실행 화면
![image](https://user-images.githubusercontent.com/69730931/116645455-e4a09700-a9b0-11eb-8476-4ca04c0c8e50.png)
![image](https://user-images.githubusercontent.com/69730931/116645491-f6823a00-a9b0-11eb-9088-6e54a2c9fdf5.png)

# 해결이 되지 않은 점 / 조언을 얻고 싶은 부분
- **은행원은 각 창구를 하나씩 담당하며, 창구에는 번호가 있습니다**라는 요구사항을 만족시키지 못했습니다.
  - `OperationQueue`의 `maxConcurrentOperation` 프로퍼티를 설정함으로써 창구 수를 설정할 수 있게끔 하였습니다.
  - 저희가 아직 잘 모르는 것일 수 있지만, 이 방법을 적용할 경우 순간순간 작동하는 쓰레드의 이름을 설정할 수 없었습니다.
  - 요구사항을 만족시키는 방법으로 `OperationQueue`를 창구 수만큼 생성하고 `OperationQueue.name` 프로퍼티를 이용하여 창구 번호를 붙인 후 `OperationQueue.operationCount` 프로퍼티를 활용하여 비어있는 `OperationQueue`에 `Operation`을 할당하는 방식으로 처리할 수 있을 듯 합니다. 하지만 이 경우 제공되는 `maxConcurrentOperation` 프로퍼티를 활용하지 않고, 각 `OperationQueue`에 작업을 할당하는 로직을 직접 만들어 사용해야하기에 적합하지 않다고 판단하였습니다. 이렇게 요구사항과 구현 방법에서 충돌이 발생하는데, 도미닉은 이 이슈에 대해 어떻게 생각하시나요? 어떤 방식으로 대응하면 좋을지 궁금합니다.

- 은행에 방문한 손님이 처리할 업무 대상인 `Operation`이므로 아래와 같이 `main()` 메서드를 가지게 되었습니다. 손님이 업무 처리와 관련된 메서드를 가지고 있는 것이 논리적으로 어긋나는 부분이 있는 것 같은데, `Client`를 `Operation`으로 두고 진행하는 방향이 적절한지 문의 드리고 싶습니다 (손님의 네이밍을 BankingTask와 같이 변경하면 더 적절해보이기도 합니다.).  

- 대부분의 메서드가 `print` 등으로 적절한 반환값이 없는 형태라 모든 메서드에 대한 유닛 테스트를 수행할 수 없었습니다. 추가로 테스트해보면 좋을 메서드가 있을까요?
- 테스트 한 메서드 중 테스트 방식이 적절하지 않은 것이 있을 경우 알려주시면 감사하겠습니다!
  - 테스트한 메서드
    - `visitNewClient()`
    - `assignTeller()`
    - `close()`
    - `totalProcessedTime()`

그럼 오늘도 즐거운 하루 보내세요! 🚀

2021-05-01 04:00 UTC, AppleCEO requested changes
Yun & Ryan 고생하셨습니다!
설계를 자세하게 작성해주셔서 읽고 파악하는데 도움이 되었습니다.

은행원은 각 창구를 하나씩 담당하며, 창구에는 번호가 있습니다라는 요구사항을 만족시키지 못했습니다.
- 스레드마다 큐를 만들어서 할당하는 것은 힘들 것 같아요. 기본적으로 스위프트에서 제공해주는 OperationQueue를 활용해보는 것이 어떨까요? 업무를 할당해주는 로직을 짜는 부분은 어떤 큐에 할당해주는 것을 결정해주는 로직이 어렵다는 말씀이시죠? 저는 어려운 문제를 항상 쉬운 여러개의 문제로 나누고 하나씩 정복합니다. 너무 어렵게 생각하지 말고 우선 각 은행원에게 순차적으로 1번째 은행원, 그리고 2번째 은행원 이렇게 할당해주는 것이 어떨까요?

 손님이 업무 처리와 관련된 메서드를 가지고 있는 것이 논리적으로 어긋나는 부분이 있는 것 같아요
- 저도 이 부분은 어색해보이긴 하네요. delegate pattern을 이용한다든가 해서 은행원이 업무를 처리하도록 개선해볼 수 있을 것 같아요.

대부분의 메서드가 print 등으로 적절한 반환값이 없는 형태라 모든 메서드에 대한 유닛 테스트를 수행할 수 없었습니다. 추가로 테스트해보면 좋을 메서드가 있을까요?
- print를 하고 있는 메소드들이 문자열을 리턴해주도록 바꿔볼 수 있을 것 같아요. 그래서 결과값을 print 해주는 식으로 개선하면 문자열이 제대로 반환되는지 테스트를 추가할 수 있습니다!

테스트 한 메서드 중 테스트 방식이 적절하지 않은 것이 있을 경우 알려주시면 감사하겠습니다!
- 위에 질문에서 얘기한 것처럼 내부에서 print를 하는 메소드들에게 문자열을 리턴하게 해서 추가적으로 테스트를 작성할 수 있을 것 같습니다. 해당 코드에 코멘트 남겼지만 스위프트의 기본적인 기능은 테스트하지 않아도 된다고 생각합니다.

테스트를 위해 유닛 테스트 파일에서 사용되는 메서드나 참조가 필요한 프로퍼티에는 private 접근수준을 설정하지 못하였습니다. 테스트를 위한 접근 수준을 별도로 설정하거나 private이라도 테스트에서는 접근할 수 있게 설정하는 방법이 있을까요?
- 그 방법은 없다고 알고 있습니다. 하지만 메소드를 사용하면서 private 접근수준의 상태값을 활용하고 변경시켜 나가게 되어있기 때문에 그런 메소드들을 잘 테스트하면 굳이 private 접근 수준의 상태값을 직접 테스트하지는 않아도 될 것 같아요~

2021-05-03 13:33 UTC, ryan-son commented on BankManager.swift
> +    }
저희는 `BankManager`를 은행원이 아니라 프로젝트명으로 보았기 때문에 `Bank` 타입을 `BankManager`의 프로퍼티로 두었습니다.

2021-05-03 13:39 UTC, ryan-son commented on BankManager.swift
> +        }
말씀하신 점을 고려하여 아래와 같이 코드를 수정해보았습니다.
- 반환 타입을 `String`으로 변경하였습니다.
- `selectMenu()` 메서드 내부에 위치한 옵셔널 바인딩의 결과가 `else` 구문으로 실행되는 경우가 없다고 판단하여 (아무 입력을 하지 않아도 빈 문자열 ("")으로 입력) 에러 타입의 연관값 구문을 삭제하였습니다.
```swift
private func selectMenu() throws -> String {
    guard let userInputText: String = readLine() else {
        throw BankManagerError.invalidMenu
    }
    return userInputText
}
```

2021-05-03 13:47 UTC, ryan-son commented on BankManager.swift
> +        print(Menu.text, terminator: "")
피드백을 반영하여 해당 `print` 구문을 호출 시 메뉴 텍스트를 반환하는 `menuText()` 메서드로 변경하였습니다. 반환 받은 문자열을 `print`로 콘솔에 출력하는 방식으로 동작합니다.

2021-05-03 13:56 UTC, ryan-son commented on BankManager.swift
> +        }
저희가 `move(to:)` 메서드에서 `exit`을 사용한 것은 `return` 키워드로는 상위 메서드인 `start()` 메서드를 종료할 수 없었기 때문입니다. 그래서 `exit`을 사용할 수 있는 곳이 메인 메서드인 `start()` 뿐이라면 저희로서는 `exit` 대신 `return`을 사용하고자 합니다. 하지만 이러한 방식으로 작성하면 가독성을 위해 메서드로 만들었던 `move(to:)` 메서드를 삭제해야 하는데 괜찮은 방향으로 가고 있는걸까요?

2021-05-03 13:58 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        let totalProcessTime: Double = measureTime { processTasks(of: clients) }
클로저 사용 시 익숙해질 때까지 축약표현을 사용하지 않도록 하겠습니다!

```swift
let totalProcessTime: Double = measureTime { () -> Void in
    return processTasks(of: clients)
}
```

2021-05-03 13:59 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +        guard number >= 1 else { return clients }
알겠습니다! 코딩 컨벤션을 지켜서 작성하도록 하겠습니다!

```swift
guard number >= 1 else {
    return clients
}
```

2021-05-03 14:06 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            clients.append(Client(waitingNumber))
피드백을 반영해서 아래와 같이 수정해보았습니다. 한 가지 질문 드리고 싶은 점은 아래와 같이 작성했을 때 반복문 내부에서 `client`라는 상수를 저장하고 `clients.append`를 통해 배열 내부로 요소가 들어가니 동일하게 작동하는 것이 아닌지 궁금합니다.
```swift
for waitingNumber in 1...number {
    let client: Client = Client(waitingNumber)
    clients.append(client)
}

2021-05-03 14:11 UTC, ryan-son commented on BankManagerConsoleApp/BankManagerTest/BankManagerTest.swift
> +    }
저희는 새로 작성한 `measureTime(_:)` 메서드를 테스트 하기 위해 위와 같은 테스트 메서드를 작성했습니다. `measureTime(_:)` 클로저 내부에 위치한 함수를 처리하는데 걸리는 시간이 정확하게 측정되는지를 판단하고자 하였습니다. `floor(_:)` 메서드의 경우 `measureTime(_:)` 메서드가 아주 작은 소수점 단위까지 측정하여 이를 정리해주기 위해 사용하였습니다. 이런 과정도 기본 동작을 테스트하는 것에 해당하나요?

2021-05-03 15:07 UTC, ryan-son commented
@AppleCEO 

도미닉! 남겨주신 피드백을 바탕으로 코드를 일부 수정해보았어요. 이번에도 잘 부탁드립니다!

## 수정한 내용
- `print`로 콘솔에 출력하기만 하던 내용을 메서드가 문자열을 반환하게끔 하여 테스트가 가능하도록 구성해 보았습니다.
  - `startTask()`, `endTask()`, `close()`, `menuText()`
- 클로저 작성 시 타입과 반환 키워드 등을 생략하지 않고 일반형으로 작성하였습니다.
- `guard`의 `else` 구문을 코딩 컨벤션에 부합하게 작성하였습니다.

## 질문
- 도미닉의 아래 코멘트에 대해 잘 이해하지 못했어요. 저희가 생각한 진행 방향을 함께 이야기 해보겠습니다.

> 은행원은 각 창구를 하나씩 담당하며, 창구에는 번호가 있습니다라는 요구사항을 만족시키지 못했습니다.
> 스레드마다 큐를 만들어서 할당하는 것은 힘들 것 같아요. 기본적으로 스위프트에서 제공해주는 OperationQueue를 활용해보는 것이 어떨까요? 업무를 할당해주는 로직을 짜는 부분은 어떤 큐에 할당해주는 것을 결정해주는 로직이 어렵다는 말씀이시죠? 저는 어려운 문제를 항상 쉬운 여러개의 문제로 나누고 하나씩 정복합니다. 너무 어렵게 생각하지 말고 우선 각 은행원에게 순차적으로 1번째 은행원, 그리고 2번째 은행원 이렇게 할당해주는 것이 어떨까요?
- `OperationQueue`는 기존의 `Bank` 타입에서 `waitingQueue`에서 사용하고 있었지만, 도미닉이 의도한 내용과는 달랐던 것 같아요. 
- **1 번째 은행원, 2 번째 은행원**이라는 말씀은 `OperationQueue`를 은행원마다 하나씩 할당하고 `OperationQueue.name` 프로퍼티를 통해 이름을 주라는 뜻이셨나요?
- 만약 맞다면, 왜 `OperationQueue`를 여러 개를 만들어야 하는지 의문이 듭니다. `OperationQueue`의 `maxConcurrentOperationCount` 프로퍼티를 조정하면 한 번에 처리할 Operation 수를 조정할 수 있으니 은행원이 여러 명 근무하는 것과 동일한 효과가 있지 않나요? 이 프로퍼티를 활용하면 `OperationQueue`는 하나이기에 `Operation`을 어떤 `OperationQueue`가 처리하도록 할지에 대한 로직을 구성하지 않아도 되고, 오히려 어떤 쓰레드에서 해당 `Operation`을 처리할지 자체적으로 처리해주기에 이와 같이 진행하는 것이 좋지 않을까 생각합니다. 도미닉의 의견이 필요해요~! 🙇🏻

> 손님이 업무 처리와 관련된 메서드를 가지고 있는 것이 논리적으로 어긋나는 부분이 있는 것 같아요
> 저도 이 부분은 어색해보이긴 하네요. delegate pattern을 이용한다든가 해서 은행원이 업무를 처리하도록 개선해볼 수 있을 것 같아요.
- 의도하신 `delegate` 패턴을 적용해보려 했지만 지식이 짧아 성공하지 못했습니다.. Delegate 패턴을 아래와 같이 적용하는게 맞을까요?
- 만약 맞다면 Client가 은행원인 Teller를 프로퍼티로 가지는 형태가 되는데, 이 방향도 선뜻 납득하기 어렵네요..
- 차라리 `Client` 타입의 이름을 `BankingTask`로 변경하거나, `Client`가 `Operation` 클래스를 상속받은 `BankingTask` 타입을 프로퍼티로 가지게 하는 방향에 대해서는 어떻게 생각하시나요?

```swift
protocol OperationDelegate {
    func main()
}

class Client: Operation, OperationDelegate {
    let teller = Teller()

    init() {
        teller.delegate = self
    }

    override func main() {
        // 고객 업무 시작 및 종료
    }
}

class Teller {
    var delegate: OperationDelegate?

    func processTask() {
        delegate?.main()
    }
}
```

감사드립니다~! 즐거운 하루 보내세요~

2021-05-04 12:43 UTC, AppleCEO commented on BankManager.swift
> +        }
move 함수에서 어떤 값을 리턴해서 start() 메소드에서 종료시킬 수 있지 않을까요?

2021-05-04 12:44 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            clients.append(Client(waitingNumber))
동일하게 동작하지만 읽기 좋은 코드가 되었습니다!

2021-05-04 12:48 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerTest/BankManagerTest.swift
> +    }
제 생각에는 동일한 값이 들어가기 때문에 기본 동작을 테스트한 것으로 보이네요.
풀어서 쓰면 0.01 * 100 / 100 == 0.01 이라서 Thread.sleep(forTimeInterval: 0.01) 이라는 스위프트의 기본 동작이 잘 동작한다고 믿는다면 불필요한 테스트이지 않을까 해서요

2021-05-04 12:49 UTC, AppleCEO commented
OperationQueue는 기존의 Bank 타입에서 waitingQueue에서 사용하고 있었지만, 도미닉이 의도한 내용과는 달랐던 것 같아요.
1 번째 은행원, 2 번째 은행원이라는 말씀은 OperationQueue를 은행원마다 하나씩 할당하고 OperationQueue.name 프로퍼티를 통해 이름을 주라는 뜻이셨나요?
만약 맞다면, 왜 OperationQueue를 여러 개를 만들어야 하는지 의문이 듭니다. OperationQueue의 maxConcurrentOperationCount 프로퍼티를 조정하면 한 번에 처리할 Operation 수를 조정할 수 있으니 은행원이 여러 명 근무하는 것과 동일한 효과가 있지 않나요? 이 프로퍼티를 활용하면 OperationQueue는 하나이기에 Operation을 어떤 OperationQueue가 처리하도록 할지에 대한 로직을 구성하지 않아도 되고, 오히려 어떤 쓰레드에서 해당 Operation을 처리할지 자체적으로 처리해주기에 이와 같이 진행하는 것이 좋지 않을까 생각합니다. 도미닉의 의견이 필요해요~! 🙇🏻
-> 많은 고민 해보셨군요! 말씀해주신 방법도 일리가 있는 것 같습니다. 스레드에게 번호를 할당할 수 있으면 가능할 것 같네요. 다음 스텝을 진행하면서 한번 시도해보시면 될 것 같습니다.

손님이 업무 처리와 관련된 메서드를 가지고 있는 것이 논리적으로 어긋나는 부분이 있는 것 같아요
저도 이 부분은 어색해보이긴 하네요. delegate pattern을 이용한다든가 해서 은행원이 업무를 처리하도록 개선해볼 수 있을 것 같아요.
의도하신 delegate 패턴을 적용해보려 했지만 지식이 짧아 성공하지 못했습니다.. Delegate 패턴을 아래와 같이 적용하는게 맞을까요?
만약 맞다면 Client가 은행원인 Teller를 프로퍼티로 가지는 형태가 되는데, 이 방향도 선뜻 납득하기 어렵네요..
차라리 Client 타입의 이름을 BankingTask로 변경하거나, Client가 Operation 클래스를 상속받은 BankingTask 타입을 프로퍼티로 가지게 하는 방향에 대해서는 어떻게 생각하시나요?
-> 후자의 방법은 좋아보입니다! 아니면 Client가 등급과 업무 타입을 가지고 있고 그 내용을 확인해서 은행원이 업무를 처리하는 방식도 있겠어요

2021-05-04 12:49 UTC, merged

2021-05-04 12:49 UTC, AppleCEO commented
고생하셨습니다!