[STEP 2] JM, Summer
yagom-academy/ios-bank-manager pull request #43
Opened 2021-05-02 12:54 UTC by alwaysblu

안녕하세요 STEP 1 PR 드립니다!

# 📌 코드를 작성할 때 고민되었던 점 :

# 📌 해결이 되지 않은 점:

# 📌 조언을 얻고 싶은 부분 :

그외에 코드 전반적인 조언 부탁드립니다!

감사합니다!

2021-05-03 14:20 UTC, wonhee009 commented on BankManagerConsoleApp/Type/BankManager.swift
> +}
오호... `extension`을 사용해 Array를 확장하셨군요🎉

여기서 사용한 `@inlinable`이란 무엇이고 어떤 이유로 사용하셨는지 알 수 있을까요?

```swift
if self.isEmpty {
   return false
}
return true
```
로 isNotEmpty 로직을 짜셨는데
기존의 isEmpty 프로퍼티를 반전한 값을 return해줄 수 있지 않을까요?

```swift
return !self.isEmpty
```
이렇게요!😀

2021-05-03 14:52 UTC, wonhee009 requested changes
스텝2 PR🎉 수고하셨습니다!
이전 스텝과 동일하게 메서드들을 적절하게 나누려 노력해주셔서 코드 따라가기 쉬웠습니다.☺️

- 재귀함수에 대해 다음 스텝에서 고민해보자 했는데 적절하게 잘 개선해주신거 같아요! 그럼 이번 스텝에서는 이 반복문을 좀 더 개선해보면 좋을거 같아요! 아래에 코멘트 남겨두었습니다.🌝

- > Thread가 현재 생성되어있는 수와 재귀함수의 call stack을 확인하는 방식으로
재귀함수를 몇번 호출하게 한 후에
마우스를 이용해서 코드에 breakpoint를 걸어서
Debug navigator를 이용해서 call stack과 Thread를 확인했는데
이 방법이 적절한 방법이었는지 조언을 얻고 싶습니다.

이 부분은 저도 이렇게 확인하고 있습니다!ㅎㅎ

코멘트 확인하고 이해 안 되는 부분이나 같이 의논하고 싶은 부분이 있다면 언제든 연락주세요! 연락 가능할때 바로 답장하도록 할게요!😉
그럼 화이팅입니다!👍



감사합니다!

2021-05-03 14:52 UTC, wonhee009 commented on BankManagerConsoleApp/Type/BankManager.swift
> +            }
`startBank()`에서 while문을 사용했고 그 안에서 `manageBank()`에서 while문을 사용했네요!
🤔코드를 풀어보면
```swift
while true {
   do {
      while true {
         ...
      }
   } catch {
   }
}
```
이렇게 이중으로 반복문을 돌고 있네요?!
사용자가 입력이 잘못 되었을때에도 계속 프로그램이 동작하도록 하기 위해서 `startBank()`에서도 반복문을 사용한거로 생각되요!
그렇다면 이중 반복문을 줄여볼 수 있을까요?
(이 부분은 궁금하거나 막히는 부분이 있다면 언제든 연락 주세요! )

2021-05-03 14:52 UTC, wonhee009 commented on BankManagerConsoleApp/Type/BankManager.swift
> +}
오호... `extension`을 사용해 Array를 확장하셨군요🎉

여기서 사용한 `@inlinable`이란 무엇이고 어떤 이유로 사용하셨는지 알 수 있을까요?

```swift
if self.isEmpty {
   return false
}
return true
```
로 isNotEmpty 로직을 짜셨는데
기존의 isEmpty 프로퍼티를 반전한 값을 return해줄 수 있지 않을까요?

```swift
return !self.isEmpty
```
이렇게요!😀

2021-05-03 14:52 UTC, wonhee009 commented on BankManagerConsoleApp/Type/Client.swift
> +    var taskType: String
`Client`에 고객우선순위 등급과 업무의 종류가 추가되었군요!
제가 파악한 바로는 `grade`와 `priority`가 우선순위를 의미하는 프로퍼티인거 같아요!
`grade`는 우선순위 문자열 (vvip, vip, 일반)이고, `priority`는 우선순위 숫자를 의미하는거 같아요.

🤔 첫번째 궁금한 점은 `grade`와 `priority`는 문자열/정수로 다른 표현법을 가진 동일한 우선순위를 의미하는데 둘 다 `Client`의 프로퍼티로 정의한 이유가 궁금해요.
🤔 두번째 궁금한 점은 `grade`와 `taskType`을 문자열로만 관리하는 이유가 궁금해요.

2021-05-03 15:07 UTC, alwaysblu commented on BankManagerConsoleApp/Type/BankManager.swift
> +            }
@inlinable는 swift의 속성 중 하나입니다.
이 속성의 목적은 애플리케이션의 성능을 높이는 데 사용할 수있는 특정 마이크로 최적화(optimizations) 세트(set)를 활성화하는 것입니다.

이미 @inlinable이 isEmpty에서 선언되어있으니 중복사용되는 것 같습니다. 삭제했습니다.

<img width="720" alt="스크린샷 2021-05-04 오전 12 05 31" src="https://user-images.githubusercontent.com/75533266/116894090-9c150200-ac6c-11eb-9f51-4e9461cb1aed.png">


```swift
return !self.isEmpty
```

위의 방법이 더 좋은 방법인 것 같습니다!

2021-05-03 15:09 UTC, alwaysblu commented on BankManagerConsoleApp/Type/BankManager.swift
> +}
@inlinable는 swift의 속성 중 하나입니다.
이 속성의 목적은 애플리케이션의 성능을 높이는 데 사용할 수 있는     
특정 마이크로 최적화(optimizations) 세트(set)를 활성화하는 것입니다.

이미 @inlinable이 isEmpty에서 선언되어있으니 중복사용되는 것 같습니다.😭 삭제했습니다.      

<img width="720" alt="스크린샷 2021-05-04 오전 12 05 31" src="https://user-images.githubusercontent.com/75533266/116894090-9c150200-ac6c-11eb-9f51-4e9461cb1aed.png">


```swift
return !self.isEmpty
```

위의 방법이 더 좋은 방법인 것 같습니다! 수정했습니다!

2021-05-03 15:48 UTC, alwaysblu commented on BankManagerConsoleApp/Type/Client.swift
> +    var taskType: String
># 🤔 첫번째 궁금한 점은 grade와 priority는 문자열/정수로 다른 표현법을 가진 동일한 우선순위를 의미하는데 둘 다 Client의 프로퍼티로 정의한 이유가 궁금해요.
동일한 의미를 가진 프로퍼티가 2개있을 필요는 없는 것 같습니다. priority 프로퍼티를 삭제했습니다!    

<br>     

> # 🤔 두번째 궁금한 점은 grade와 taskType을 문자열로만 관리하는 이유가 궁금해요.
grade를 정렬할때 코드의 가독성을 위해 Int형으로 변경하였습니다.
taskType은 정렬이 필요 없어서 가독성을 위해 Int형으로 관리할 필요가 없다고 생각하였고   
오히여 문자열로 관리하는 것이 좀 더 직관적으로 보여서 가독성에 있어서 좋다고 생각하여서 문자열로 관리하였습니다!

2021-05-03 16:14 UTC, alwaysblu commented on BankManagerConsoleApp/Type/BankManager.swift
> +            }
```swift
private func checkInputValidation() throws -> Bool {
        guard let userInput = readLine(), let userInputNumber = Int(userInput) else { throw BankError.userInput }
        if userInputNumber == BankMenu.start {
            return true
        } else if userInputNumber == BankMenu.exit {
            return false
        }
        throw BankError.userInput
    }
```

위와 같이 에러를 throw하도록 함수를 변경하였습니다!

```swift
func startBank() {
        let numberOfBanker: Int = 3
        while true {
            startBankMenu()
            do {
                let isValid = try checkInputValidation()
                guard isValid else { return }
            } catch {
                print(error.localizedDescription)
                continue
            }
            let numberOfClient = createClient(numberOfClient: Int.random(in: 10...30))
            bank.totalNumberOfClinet = numberOfClient
            createBanker(numberOfBanker: numberOfBanker)
            operationQueue.waitUntilAllOperationsAreFinished()
            bank.closeBusiness()
            removeAllObserver(numberOfObserver: numberOfBanker)
        }
    }
```

manageBank 함수를 위의 함수와 같이 변경해서 중복되는 무한루프를 없앴습니다.     
그리고 기존 startBank 함수를 없애고 manageBank함수이름을 startBank로 변경하였습니다!

2021-05-03 16:22 UTC, summer0817 commented
@wonhee009 

늦은 시간에도 코드 리뷰 해주셔서 감사합니다.
리뷰 해주신 피드백 내용을 적용하여 코드를 수정하였습니다.
검토해주시면 감사하겠습니다. 🙏

2021-05-04 06:08 UTC, wonhee009 commented on BankManagerConsoleApp/Type/BankManager.swift
> +            }
오호 이렇게 개선해 보셨군요!
이 방법도 이중 반복문을 개선하는 하나의 방법이 될 수 있겠어요🎉

2021-05-04 06:20 UTC, wonhee009 approved these changes
스텝2 수고하셨습니다!🎉
다음 스텝에서 보도록할게요!!😃

2021-05-04 06:20 UTC, wonhee009 commented on BankManagerConsoleApp/Type/BankManager.swift
> +    private let lock = NSLock()
접근제한자를 사용했군요🎉

2021-05-04 06:20 UTC, merged