[Step2] - Sookim, Steven
yagom-academy/ios-bank-manager pull request #44
Opened 2021-05-03 12:14 UTC by sookim-1

# **[STEP 2] 은행창구매니저 🏦**

@corykim0829 
안녕하세요 cory~ 😄

steven과 함께 step1피드백을 반영하여 코드를 수정한 후 step2를 진행해봤어요. 👍

## 수정된 클래스 다이어그램

![2BankManager](https://user-images.githubusercontent.com/55218398/116874485-5ea47a80-ac54-11eb-836b-6ad1b3110fe6.jpg)

## 동작 화면
![Untitled](https://user-images.githubusercontent.com/55218398/116874492-6106d480-ac54-11eb-84d9-e531de0a84c2.gif)

## Step1 피드백 받은 부분

> BankManager를 따로 만들어서 처리하는 이유

- BankManager구조체가 하는 일은 주로 오퍼레이션큐에 오퍼레이션을 보내서 작업을 처리하는 일을 하는데 Bank구조체에서 이 일을 맡은다면 너무 많은 일을 하게 될 것 같아서 따로 처리하도록 했어요 😅

> 그리고 대기 순번 같은 경우도 CustomerMaker 가 Customer 배열을 만들어 주기 때문에 따로 구현을 하지 않았습니다.. 배열에 있는 순서대로 OperationQueue에 들어가게 구현을 했는데... 현실 은행에서는 언제 고객이 올지 모르는데... 이렇게 구현하는 것이 맞는 걸까요?
➡️ 맞아요! Customer 객체를 만들 때가 아니라 작업이 들어갈 때 번호를 부여하는 방법으로 개선하면 좋을 것 같아요!

- 이부분에 대해서 고민해봤는데..  `Customer` 인스턴스 배열을 만들어서 `addOperations` 하기 때문에 그냥 인스턴스를 생성할 때 대기 번호를 주기로 했습니다.

## 고민한 부분

- `BankTask` 클래스 내에서 `BankTaskType` enum 타입을 랜덤으로 지정해주는데,  나중에 `taskType` 이 지정되서 오는 경우를 생각하면 Customer클래스에서 지정해주는 게 나을꺼 같은데 Cory의 의견이 궁금해요?

### 저희가 작성한 코드

```swift
// BankTask.swift

init(waitingNumber: Int, grade: CustomerGrade) {
        self.taskType = BankTaskType.random
        self.taskTime = taskType.taskTime
        self.waitingNumber = waitingNumber
        self.customerGrade = grade
        super.init()
        super.queuePriority = customerGrade.queuePriority
    }
```

### 고민해 본 코드

```swift
// BankTask.swift

init(waitingNumber: Int, grade: CustomerGrade, taskType: BaskTaskType) {
        self.taskType = taskType
        self.taskTime = taskType.taskTime
        self.waitingNumber = waitingNumber
        self.customerGrade = grade
        super.init()
        super.queuePriority = customerGrade.queuePriority
    }
```

- `Customer`와 `BankTask`클래스 내에서 `CustomerGrade`, `waitingNumber` 프로퍼티를 중복으로 사용하고 있습니다. `BankTask` 클래스 안에서 대기 번호, 고객 등급을 모두 사용해야 되서 이렇게 구현하게 되었는데.. 좋은 설계는 아닌것 같아요... 더 좋은 방향이 있을까요?

- `CustomerGrade`, `BankTaskType` 을 열거형으로 만들어 주었습니다. 그리고 열거형에 안해서 필요한 부분들을 연산프로퍼티로 선언했는데.. 그래서 enum 타입들이 커진것 같습니다. 더 좋은 방법이 있을 까요?

- 추가로 접근제어자는 잘 썼는지도 같이 봐주시면 감사하겠습니다 🙂

2021-05-04 10:09 UTC, corykim0829 requested changes
👍👍👍👍

와 너무너무 깔끔하게 잘 구현하셔서 놀랐어요! 👀
커밋 로그도 잘 나누셨고 너무 잘하셨습니다 👏👏👏👏

> Customer와 BankTask클래스 내에서 CustomerGrade, waitingNumber 프로퍼티를 중복으로 사용하고 있습니다. BankTask 클래스 안에서 대기 번호, 고객 등급을 모두 사용해야 되서 이렇게 구현하게 되었는데.. 좋은 설계는 아닌것 같아요... 더 좋은 방향이 있을까요?

➡️ 중복이라기 보다는 모두 필요한 프로퍼티인데 타입만 같다고 생각이 드네요! 
그런데 현재 구조를 보니 Customer에 BankTask 프로퍼티가 있는데 이 프로퍼티를 사실상 사용하지 않고 있는 것 같아요. Customer에 BankTask가 꼭 필요한가요?

Customer와 BankTask 관계만 잘 정리하면 될 것 같아요!

> CustomerGrade, BankTaskType 을 열거형으로 만들어 주었습니다. 그리고 열거형에 안해서 필요한 부분들을 연산프로퍼티로 선언했는데.. 그래서 enum 타입들이 커진것 같습니다. 더 좋은 방법이 있을 까요?

➡️ 별로 커지지 않았습니다. 연산프로퍼티도 잘 사용하셨구요 👍

> 추가로 접근제어자는 잘 썼는지도 같이 봐주시면 감사하겠습니다 🙂

➡️ 변하지 않는 값들은 let을 쓰는 것도 좋은 방법이에요!

2021-05-04 14:35 UTC, sookim-1 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankTask.swift
> +        self.taskTime = taskType.taskTime
오!! 그러네요!! 삭제해주었어요 ㅎㅎ

2021-05-04 14:36 UTC, sookim-1 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManager.swift
> +        waitingLine.addOperations(customers.map({ $0.bankTask }), waitUntilFinished: true)
깔끔하게 쓰려고 했는데 오히려 가독성을 해쳤네요.. 
baskTasks 라는 배열로 분리했습니다!

2021-05-04 14:41 UTC, sookim-1 commented
> ➡️ 중복이라기 보다는 모두 필요한 프로퍼티인데 타입만 같다고 생각이 드네요!
그런데 현재 구조를 보니 Customer에 BankTask 프로퍼티가 있는데 이 프로퍼티를 사실상 사용하지 않고 있는 것 같아요. Customer에 BankTask가 꼭 필요한가요?

저희가 처음부터 구조를 설계할 때 이 부분에 대해서 이야기를 해봤었는데 `OperationQueue`가 실행되는 메서드를 가지는 클래스가 `BankTask` 가지고 있는게 맞다고 생각했을 때는 `BankManage`에 있는게 맞다고 생각했습니다. 

고객(Customer)

2021-05-04 14:51 UTC, stevenkim18 commented
그런데 BankTask가 대기번호를 가지는 것이 이상하고 은행을 구현할 때 실제로 고객 객체가 있어야 할 것 같아서 `Customer` 객체를 만들고 그 안에 업무인 `BankTask`를 들고 있게 구현을 했습니다.

2021-05-05 14:08 UTC, corykim0829 commented
수고하셨습니다! 👍👍👍

다시 보니까 map 고차함수를 통해서 한번 Customer에 있는 BankTask를 사용하기는 하는군요!
저는 아예 사용하지 않는 줄 알았네요 ㅎ 저의 실수입니다 😅
지금 BankManager에서 구조를 보면 Customer를 만들어서 Customer 안에있는 BankTask를 꺼내서 watingLine에 넣고 있는 방식이여서 조금 비효율적인 느낌이 듭니다.
이 부분은 좀 더 고민해보고 개선해보면 좋을 것 같아요! 

이 부분은 step3하면서 더 개선해보면 좋을 것 같아요! 머지해드리겠습니다 😃

2021-05-05 14:08 UTC, corykim0829 approved these changes
수고하셨습니다! 👍👍👍

다시 보니까 map 고차함수를 통해서 한번 Customer에 있는 BankTask를 사용하기는 하는군요!
저는 아예 사용하지 않는 줄 알았네요 ㅎ 저의 실수입니다 😅
지금 BankManager에서 구조를 보면 Customer를 만들어서 Customer 안에있는 BankTask를 꺼내서 watingLine에 넣고 있는 방식이여서 조금 비효율적인 느낌이 듭니다.
이 부분은 좀 더 고민해보고 개선해보면 좋을 것 같아요!

이 부분은 step3하면서 더 개선해보면 좋을 것 같아요! 머지해드리겠습니다 😃

2021-05-05 14:08 UTC, merged