[Step2] Fe
yagom-academy/ios-bank-manager pull request #45
Opened 2021-05-03 12:46 UTC by inwoodev

@AppleCEO 
도미닉, 안녕하세요. 오랜만에 다시 또 PR 보내봅니다~!!✍️ 🔥

# 배경:
Step1에 이어서 은행원을 thread로 봐야할지 아니면 OperationQueue자체로 봐야할지 계속 고민하였습니다.
@yagom 과 도미닉의 피드백을 저희가 이해한 바로는 OperationQueue를 은행원으로 봐야한다고 생각하였습니다.
그래서 fezz와 같이 머리를 맞대고 모델을 짜본 결과 아래와 같은 방식으로 step2를 구현하려 하였습니다.
![은행창구2](https://tva1.sinaimg.cn/large/008i3skNgy1gq1y03pbl0j31sz0u014w.jpg)
Step2에는 은행원이 3명 필요하기에 일단 3개의 OperationQueue를 생성한 뒤 해당 Queue로 Operation들을 스케줄링을 통해 더해주려 하였으나 알고리즘을 구현함에 있어서 아래와 같은 어려움을 겪었기 때문에 다른 방법으로 step2를 진행하기로 하였습니다. 
<br/>
**[Trouble]**
OperationQueue의 상태를 고려하지 않고 순차적으로 Operation을 넣어주려하니 간헐적으로 우선순위가 낮은 작업이 우선순위가 높은 작업보다 먼저 실행되는 문제가 있었습니다.
위 문제를 해결하고자 아래와 같은 알고리즘을 짜봤습니다
``` swift
private func scheduleService() {
        let sortedTotalClient = Array([vvipQueue, vipQueue, normalQueue].joined())
        for (number, order) in sortedTotalClient.enumerated() {

            if bankWindows[number % bankWindows.count].isSuspended == false {
                bankWindows[number % bankWindows.count].addOperation(order)
                bankWindows[number % bankWindows.count].isSuspended = true
                order.completionBlock = {
                    self.bankWindows[number % self.bankWindows.count].isSuspended = false
                }
            } else {
                if bankWindows.prefix(while: { $0.isSuspended == false }).first == nil {
                    bankWindows[number % bankWindows.count].addOperation(order)
                    bankWindows[number % bankWindows.count].isSuspended = true
                    order.completionBlock = {
                        self.bankWindows[number % self.bankWindows.count].isSuspended = false
                    }
                } else {
                    bankWindows.prefix(while: { $0.isSuspended == false }).first?.addOperation(order)
                    bankWindows.prefix(while: { $0.isSuspended == false }).first?.isSuspended = true
                    order.completionBlock = {
                        self.bankWindows.prefix(while: { $0.isSuspended == false }).first?.isSuspended = false
                    }
                }
            }
        }

        for workQueue in bankWindows {
            if workQueue.isSuspended {
                workQueue.isSuspended = false
                workQueue.waitUntilAllOperationsAreFinished()
            }
        }
    }
```

isSuspended메서드를 활용하여 OperationQueue의 로직을 짜봤습니다. 그럼에도 불구하고 간헐적으로 우선순위를 무시하고 우선순위가 낮은 작업이 실행되는 것을 발견하였습니다.
<img src="https://raw.githubusercontent.com/inwoodev/uploadedImages/uploadedFiles/20210503210709.png" alt="빨간줄" width = "50%" />

이러한 이유 때문에 OperationQueue를 하나로 통일하고 thread의 숫자의 제한을 두어서 은행원이 3명씩 vvip고객을 우선적으로 상대하도록 구현하였습니다. 저희의 모델은 아래와 같습니다.
![은행창구3](https://raw.githubusercontent.com/inwoodev/uploadedImages/uploadedFiles/20210503174100.png)

# ​작업내용
- Operation class이름을 Client → Task로 변경
  - Operation자체가 작업을 의미하는데 클라이언트를 작업클래스로 생성하는 것은 목적에 맞지 않다고 판단하여 Task로 rename하였습니다.

- 작업 신용 등급에 맞는 우선순위 부여 (아래 코드 참조)
``` swift
private func assignPriority(_ task: Task) {
        guard let rate = task.creditRate else { return }
        switch rate {
        case .vvip:
            return task.qualityOfService = .userInteractive
        case .vip:
            return task.qualityOfService = .userInitiated
        case .normal:
            return task.qualityOfService = .default
        }
    }
```
- 신용등급별 고객의 작업을 랜덤하게 생성하는 코드 구현
- 랜덤으로 여러 신용등급 그리고 여러 업무를 하는 작업을 for문을 통해 생성한 뒤 배열에 넣은 뒤 모든 작업을 OperationQueue로 한 번에 넣어줘서 비동기적으로 작업이 실행되도록 구현하였습니다 (아래 코드 참조)
``` swift
var taskList: [Task] = []
                let totalCustomer = customerNumber()
                for waitNumber in 1...totalCustomer {
                    let randomClientAttribute = acceeptRandomClient()
                    let taskPerClient = Task()
                    taskPerClient.waitingNumber = waitNumber
                    taskPerClient.creditRate = creditRatings[randomClientAttribute.0]
                    taskPerClient.typeOfWork = typeOfWorks[randomClientAttribute.1]
                    assignPriority(taskPerClient)
                    taskList.append(taskPerClient)
                    taskPerClient.completionBlock = {
                        guard let typeOfTask = taskPerClient.typeOfWork else { return }
                        workTime += typeOfTask.duration
                    }
                }
                bankWindow.addOperations(taskList, waitUntilFinished: true)
                print("업무가 마감되었습니다. 오늘 업무를 처리한 고객은 총 \(totalCustomer)명이며, 총 업무시간은\(String(format: "%.2f", workTime))초 입니다.")
```

# ​노트: 궁금한 점 / 피드백 요청
- 저번 스텝부터 지속되었던 은행원 == thread? 은행원 == OperationQueue? 문제가 아직도 딜레마 입니다. 일단 위에서 보셨다시피 두 가지 방법 다 시도하였습니다만, OperationQueue에 은행원 역할을 맡기니 스케줄알고리즘이라는 벽에 부딪히게 되었습니다. 도미닉은 이 문제를 어떻게 생각하시는지 궁금합니다.
- 일단 저희는 클라이언트가 하나의 클래스로서 존재하는 것 보다 task의 일부라고 생각되었기에 따로 Client 타입을 만들어주지 않았습니다. 도미닉이 생각하시기에는 클라이언트와 task의 분리가 필요하다고 생각하시나요?
- 저희가 3개에 OperationQueue에 작업을 적절히 분리하여 우선순위 작업부터 각 OperationQueue의 하나의 thread가 비동기적으로 작업을 처리하도록 시도해보았습니다만 로직의 문제때문인지 간헐적으로 스케줄링이 올바르게 되지 않는 것을 확인하였습니다. 혹시나 위에 짜 놓은 알고리즘을 보시고 개선할 부분이 보이신다면 도와주신다면 정말 감사할 것 같습니다:)

# ​스크린샷: 
![은행창구 콘솔로그1](https://raw.githubusercontent.com/inwoodev/uploadedImages/uploadedFiles/20210503175543.gif)

2021-05-04 12:26 UTC, AppleCEO requested changes
Fezz, James 안녕하세요 도미닉입니다
이번 스텝도 고생하셨습니다!
코멘트들 확인해보세요~

- 저번 스텝부터 지속되었던 은행원 == thread? 은행원 == OperationQueue? 문제가 아직도 딜레마 입니다. 일단 위에서 보셨다시피 두 가지 방법 다 시도하였습니다만, OperationQueue에 은행원 역할을 맡기니 스케줄알고리즘이라는 벽에 부딪히게 되었습니다. 도미닉은 이 문제를 어떻게 생각하시는지 궁금합니다.
-> 저는 회의에서 얘기했던 것처럼 1,2,3번 창구 순서대로 할당을 해줄 거에요. 지금도 정렬을 해서 vvip부터 순서대로 처리를 하시던데 그것을 OperationQueue에도 적용할 수 있을 것 같아요. 그림으로 그려보면 

1번 창구 | 2번 창구 | 3번 창구
VVIP     |     VVIP    |      VIP
VIP       |    VIP        |     VIP
VIP       |     일반      |      일반
일반

이런 식으로 창구를 할당해주면 되지 않을까요?

- 일단 저희는 클라이언트가 하나의 클래스로서 존재하는 것 보다 task의 일부라고 생각되었기에 따로 Client 타입을 만들어주지 않았습니다. 도미닉이 생각하시기에는 클라이언트와 task의 분리가 필요하다고 생각하시나요?
-> 분리가 필요하다고는 생각하지 않아요. 다만 task보다 클라이언트라는 용어가 나을 것 같고 이 클라이언트가 왔을 때 클라이언트의 등급, 업무 종류를 보고 BankManager가 업무를 수행하는게 맞다라는 의견입니다.

- 저희가 3개에 OperationQueue에 작업을 적절히 분리하여 우선순위 작업부터 각 OperationQueue의 하나의 thread가 비동기적으로 작업을 처리하도록 시도해보았습니다만 로직의 문제때문인지 간헐적으로 스케줄링이 올바르게 되지 않는 것을 확인하였습니다. 혹시나 위에 짜 놓은 알고리즘을 보시고 개선할 부분이 보이신다면 도와주신다면 정말 감사할 것 같습니다:)
-> 로직은 잘못된 것은 없어보여요. 저번 PR에 공유해준 링크처럼 completionBlock이 정확히 해당 코드가 완료될 때 실행되는 것을 애플에서 보장해주지 않는 상황 때문에 발생하는 문제이지 않을까 싶네요!

2021-05-04 13:24 UTC, Fezravien commented on BankManagerConsoleApp/BankManagerConsoleApp/BankService.swift
> +    }
`WorkType.rawValue` 를 사용하는 것보다 `WorkType.duration` 이 좀더 명확하다고 생각해서 사용했어요 !

2021-05-04 13:28 UTC, Fezravien commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +                continue
고객을 랜덤하게 받고,  속성들을 넣는 작업을 다른 메소드로 빼볼게요 !

2021-05-04 13:29 UTC, Fezravien commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    }
콘솔 앱을 트리거하는 객체 (main) 뱅크 객체(Bank)로 나눠보도록 해볼게요 !

2021-05-04 13:31 UTC, Fezravien commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +                    taskPerClient.typeOfWork = typeOfWorks[randomClientAttribute.1]
`randomClientAttribute.0`. `randomClientAttribute.1` 부분을 다른 상수에 넣어 가독성을 높힐 수 있을 것 같아요 !

2021-05-04 13:34 UTC, Fezravien commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +    }
`client` 객체에서 랜덤한 수와 고객의 등급, 업무 종류를 부여하게 할 수 있을 것 같아요 !

2021-05-04 13:35 UTC, Fezravien commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +        guard let rate = task.creditRate else { return }
```swift
guard let ~ else { return }
guard let ~ else {
    return 
}
```

하는 방식에 어떤 차이가 있는지 궁금해요 !

2021-05-04 13:50 UTC, Fezravien commented on Task.swift
> +        }
- if let 
성공과 실패 두 분기로 나눠 원하는 작업이 가능하다. 
`지역`변수로만 사용이 가능하다.

- guard let 
실패에 대해서만 코드작업을 해주는데 `제어 전달문` 으로 빠른 처리가 가능하다.
변수는 `전역`으로 사용이 가능하다.

저희는 `guard let` 이 두 분기로 나눠서 처리 하는 것 보다 더욱 간결하게 처리할 수 있다고 생각했어요 !

2021-05-05 04:26 UTC, merged

2021-05-05 04:29 UTC, AppleCEO commented on BankManagerConsoleApp/BankManagerConsoleApp/main.swift
> +        guard let rate = task.creditRate else { return }
동작에 차이는 없습니다! 공부하는 동안에는 기본형을 활용하는 것이 가독성은 더 좋다는 의견입니다. 
아래처럼 여러 방식으로 guard let 구문을 쓸 수 있을텐데요. 이런 것이 어떤게 보기 좋은지는 나중에 팀끼리 의논을 해서 하신 것처럼 한 줄로 작성하도록 결정할 수 있을 것 같습니다. 아직은 기본형을 활용하는 것을 권장드려요!
guard let ~ else 
{ return }

guard let ~ else { return
}

2021-05-05 04:31 UTC, AppleCEO commented on Task.swift
> +        }
네 두가지 방식 중 어떤 것이 좋을지는 여러번 사용하면서 파악해야될 것 같아요. guard let만 사용하지 말고 어떤 때 if let을 사용하면 좋을지 고민해보고 섞어서 써보면 더 좋을 것 같아요~

2021-05-05 04:31 UTC, AppleCEO commented
고생하셨습니다! DM으로 의견주신 대로 다음 스텝을 진행하며 수정하도록 merge 드릴께요~