은행 창구 매니저 [Step1] 샤피로, 산체스
yagom-academy/ios-bank-manager pull request #65
Opened 2021-07-27 07:57 UTC by shapiro711

@TaeJoongYoon 
안녕하세요 타일러!!! 저희 step1을 완성시켜서 PR 보냅니다~
잘부탁드려요 :)

## 구현한 부분 
---
1. LinkedList를 이용하여 Queue 타입 구현
2. Queue 클래스내 메서드 테스트 코드 작성

## 궁금한 점
---
1. Queue 클래스 메서드에서 구현해 놓은 LinkedList내 메서드를 호출하는 부분이 대부분입니다. 이러한 경우 따로 타입을 빼서 Queue를 구현하는 것이 맞는지 궁금합니다. 저희는 LinkedList 이용한 Queue 자료구조를 외부에서 사용하기 때문에 따로 타입을 빼서 구현했습니다.
2. 이번 프로젝트에서 콘솔앱과 ui앱 프로젝트가 따로 존재하는데 BankManager 파일이 연동이 되는것을 보았습니다. xcode에서 프로잭트 파일 관리가 전반적으로 어떻게 되는지 궁금합니다.

2021-07-27 11:14 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +class Node <T> {
Generic을 활용하신 점 너무 좋습니다 💯 

하나만 고친다면 아래와 같이 클래스명과 제네릭선언사이에 공백이 없으면 좋을것 같아요 ㅎㅎㅎ
`class Node<T>`

2021-07-27 11:14 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    weak var next: Node<T>?
강한순환참조가 일어나지 않게 `previous`와 `next`중 하나를 `weak`으로 선언하신 점 좋습니다 ㅎㅎ

2021-07-27 11:29 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func peek() -> T? {
단순 리턴값만 존재하는 함수라면 연산 프로퍼티로 바꿔도 좋을것 같아요 ㅎㅎ

2021-07-27 11:53 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    }
위 코멘트와 마찬가지로 연산 프로퍼티로 변경하면서 앞에 get이 사라지면 더 swift스러울것 같아요 :)

2021-07-27 11:53 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    private let linkedList = LinkedList<T> ()
여기도 띄어쓰기 한번만 확인해주세요 !

2021-07-27 11:53 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    func enqueue(_ vlaue: T) {
`value`에 대한 오타인것 같아요 ㅎㅎㅎ

2021-07-27 11:53 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
큐에서 `dequeue`시에는 제거된 element를 반환도 같이 해주는데요 ㅎㅎㅎ 이 내용도 같이 적용되면 좋을듯 합니다 :)

2021-07-27 11:53 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    }
앞선 코멘트처럼 연산 프로퍼티로 바꿀수 있겠죠?!

2021-07-27 12:02 UTC, TaeJoongYoon requested changes
안녕하세요 샤피로, 산체스~ 이번 프로젝트 리뷰를 맡은 타일러입니다 :)

STEP1은 자료구조에 대한 STEP이었는데 로직상 큰 문제는 보이지 않지만 컨벤션에 관한 부분들이 보여서 코멘트 남겨놨으니 한번 확인 부탁드려요 ㅎㅎㅎ
그럼 남겨주신 질문들 봐볼게요 ㅎㅎ

---
## 1. Queue 클래스 메서드에서 구현해 놓은 LinkedList내 메서드를 호출하는 부분이 대부분입니다. 이러한 경우 따로 타입을 빼서 Queue를 구현하는 것이 맞는지 궁금합니다. 저희는 LinkedList 이용한 Queue 자료구조를 외부에서 사용하기 때문에 따로 타입을 빼서 구현했습니다.

네네 잘하셨습니다 ㅎㅎ LinkedList와 Queue는 엄연히 다른 자료구조이기 때문에 따로 구현을 하는게 맞아요. 지금은 비슷한 특성만 사용하기 때문에 그렇게 느껴지시는 것 같아요. LinkedList로는 Queue말고도 다른 다양한 자료구조를 만들 수 있고, 또 Queue도 LinkedList말고도 다른 자료구조로 만들어 질 수 있기 때문에 각각의 특성에 맞게 분리하여 구현하는게 맞아보입니다 :)

## 2. 이번 프로젝트에서 콘솔앱과 ui앱 프로젝트가 따로 존재하는데 BankManager 파일이 연동이 되는것을 보았습니다. xcode에서 프로잭트 파일 관리가 전반적으로 어떻게 되는지 궁금합니다.

Xcode에서 프로젝트 파일 > Target 선택 > Build Phase > Complie Sources에 가보시면 해당 타겟에 사용할 수 있는 파일들이 있을텐데 두 프로젝트 모두 확인해보니 BankManager파일이 들어가있네요 ㅎㅎㅎ. 이러면 양 프로젝트에서 사용가능합니다.
그리고 한 프로젝트파일에서 BankManager파일을 눌러보시면 우측에 Target Membership이 보이실거에요. 여기서도 체크박스를 이용하여 현재 프로젝트에서 어느 타겟에 사용될 수 있는지 선택할 수 있습니다 :)

---

2021-07-28 07:04 UTC, shapiro711 commented
타일러 상세한 리뷰 정말 감사합니다~!!!
산체스와 리뷰를 같이 보고 수정을 좀 해보았습니다.

### 수정 부분
1. 띄어쓰기 문제 해결
2. 간단한 계산의 함수 계산 프로퍼티로 변경
3. 오탈자 수정

위의 부분들을 수정하고 다시 푸시 했습니다 :) 잘부탁드려요~

2021-07-28 09:37 UTC, TaeJoongYoon approved these changes

2021-07-28 09:38 UTC, merged