[Step1] 지스,건
yagom-academy/ios-bank-manager pull request #67
Opened 2021-07-27 11:59 UTC by jgkim1008

@leejun6694 
안녕하세요!!쿠마 저희 step1을 진행완료되서 PR을 보냅니다~
부족하지만 잘 부탁드려요 :)

# 구현한 부분
---
1. Node 생성하는 클래스 작성  
2. Node을 통하여 LinkedList 구현
3. LinkedList를 이용하여 Queue타입 구현

# 궁금한점
---
1. BankManagerQueue가 class여야 되는지 구조체 여야되는지 잘 모르겠습니다. 상속이나,참조할 이유가 없으면 구조체로 선언하면 된다고 알고 있어서 구조체로 진행하였는데요. 
구조체 내부 프로퍼티에 클래스 타입이 있을때,참조 오버헤드?? 이런게 발생해서 성능에 안좋다고 봐서 어떤 타입으로 선언해야되는지 감이 안잡힙니다.혹시 깊은 복사와 얕은 복사와 관련된건지 잘 모르겠습니다ㅠㅜ

2.LinkedList에서 removeFirst()와 peekFirst() 의 리턴값이 Node를 반환하고 있습니다.노드를 반환하는게 좋은건지 아니면 노드의 데이터를 반환해주는게 좋을지 잘 모르겠습니다.

3. 마지막은 저희가 대화방에 말해드린 내용인데요.참조 카운트 관련해서 removeFirst()시 다음 Node의 링크를 가르킬떄 기존 Node는 참조카운트가 없어져 자동으로 소멸되는게 맞을까요?? 이러한 관점에서 removeAll()도 head에 nil을 입력하면 연달아서 node의 참조 카운트가 다 없어지게 되는게 맞는건지 궁금합니다.

2021-07-28 16:26 UTC, leejun6694 requested changes
지스, 건 안녕하세요!
코드를 깔끔하게 작성해주셔서 읽는데 편했네요 🥇 

1. `상속이나, 참조할 이유가 없으면 구조체로 선언하면 된다`는 구조체의 장점을 담고 있는 말은 아닌 것 같네요ㅠㅡㅜ 참고한 자료가 있다면 저도 알려주세요~~! 확인해보겠습니다ㅎㅎ
2. 다음 노드의 정보를 알고 싶은 것은 아니여서, 현재처럼 데이터만 반환해줘도 괜찮을 것 같아요 👍 
3. 대화방에서 말씀 드렸어요!

리뷰 내용도 확인 부탁드려요~

2021-07-28 16:26 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func removeFirst() -> Node<T>? {
물론 이번 프로젝트에선 불필요할 수도 있는 내용이지만, `removeFirst()` method 의 경우 return 값을 사용하지 않는 케이스도 있을 것 같네요. 이런 경우엔 어떤 방법이 있는지도 알고 넘어가볼까요??

2021-07-28 16:26 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManagerQueue.swift
> +        linkedList.isEmpty
return 을 생략 가능한 경우, 생략할지 생략하지 않을지 컨벤션을 맞춰주세요ㅎㅎ
`peek()` 의 경우엔 작성하고 있네요 : )

2021-07-28 16:26 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        defer {
defer 를 사용해서 어떤 장점이 있었나요?

2021-07-29 11:12 UTC, jgkim1008 commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    var link: Node?
넵~ 일반적인 용어로 변경하는게 좋을것 같다고 저희도 생각되어 리팩토링 하였습니다.😀

2021-07-29 11:35 UTC, jgkim1008 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func removeFirst() -> Node<T>? {
반환을 하지 않은 메써드를 새로 만들거나, @discardableResult 을 선언해줘서 버릴수 있는 결과라고 알려줄수 있는 방법이 있을것 같아요
저희가 쿠마의 의도를 제대로 이해한게 맞을까요..??

2021-07-29 11:38 UTC, jgkim1008 commented on BankManagerConsoleApp/BankManagerConsoleApp/BankManagerQueue.swift
> +        linkedList.isEmpty
이번에 처음알았는데 반환값이 있을떄 무조건 return이 있어야하는줄 알았는데 아니었군요 :)
return을 써주는게 코드 읽을때 좀더 명확해지는것 같아서 isEmpty에도 return을 쓰기로 했습니다.

2021-07-29 12:03 UTC, hrjy6278 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        defer {
함수 종료 시점에 처리할 작업을 defer로 처리 할 수 있다는게 큰 장점이였던 것 같습니다!

2021-07-29 12:17 UTC, jgkim1008 commented
@leejun6694

안녕하세요 쿠마~ 리뷰받은 내용을 확인하고 다시 리팩토링 진행하였습니다.
잘부탁드립니다!

* 첫번쨰 질문에 구조체의 장점을 말해달라고 하셨는데요.
저희가 처음에 말씀드린건 구조체를 써야될떄를 생각해서 말씀드린거였습니다. 구조체의 장점은 스택에 저장되어 속도가 빠르고, 참조가 되지 않으니 값을 추적하는데 용이할것이고, ARC를 생각안해도 되서 편할것 같습니다.

* LinkedList에서 removeFirst()와 peekFirst() 의 리턴값이 Node를 반환하고 있습니다.노드를 반환하는게 좋은건지 아니면 노드의 데이터를 반환해주는게 좋을지 잘 모르겠습니다.  -> 다음 노드의 정보를 알고 싶은 것은 아니여서, 현재처럼 데이터만 반환해줘도 괜찮을 것 같아요 👍
이 부분에서 저희가 궁금했던 부분은 LinkedList 클래스에서 반환값을 Node로 할것인지에 대해 궁금했었는데요.사실 Queue 타입에서 데이터를 반환하고 있기에 크게 문제될만한건 없는데 궁금해서 여쭤보고 싶습니다 

* removeFirst()에서 defer관련해서 장점?? 이라고 생각할게 딱히 없는것 같습니다.
 반환해야할 첫번쨰 값을 미리 상수에 선언해두고 return으로 상수를 반환해도 결과는 똑같은데, defer를 사용하면 상수를 굳이 선언안해도 되는 것 밖에는 잘모르겠습니다.

2021-07-30 09:52 UTC, leejun6694 approved these changes

2021-07-30 09:52 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func removeFirst() -> Node<T>? {
네ㅎㅎ `@discardableResult` 이란 친구를 소개해주고 싶었어요 : )

2021-07-30 09:52 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +            return
`return` 이 필요할까요...!?

2021-07-30 09:52 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        let newNode = Node<T>(data: data, next: nil)
아마 높은 확률로 new node 생성 시, next 값은 nil 로 예상됩니다.
이런 경우, 우리는 어떤 방향을 생각해볼 수 있을까요!?

2021-08-01 09:59 UTC, leejun6694 commented
피드백 내용을 잘 반영해주셨네요 👍 

1. 말씀주신 내용처럼 구조체의 장점을 잘 활용할 수 있다면, 구조체로 구현해주시면 될 것 같네요! 저도 이 부분은 좀 더 공부하고 의견을 나눠보겠습니다!!
2. method 를 호출하는 곳에서 굳이 node 의 next 정보가 필요하지 않을 것으로 보이네요. 이런 경우 데이터만 넘겨주어도 될 것 같아요ㅎㅎ
3. 네! 적어주신 내용도 좋고, 가독성 관련해서도 생각해보면 좋습니다 : )

2021-08-01 09:59 UTC, merged