[STEP 1] Charlotte, Soll
yagom-academy/ios-bank-manager pull request #70
Opened 2021-07-28 08:48 UTC by soll4u

@leejun6694 @yaewonLee

안녕하세요, 스텝1 PR 보내드립니다 ㅎㅎ 
2주동안 잘 부탁드립니다! 🙏

### 고민한 점
1. 초반에 LinkedList와 Queue를 하나의 타입(LinkedListQueue)으로 작성했다가 분리하게 되었습니다.
사실 Queue에서 하는 게 LinkedList의 메서드를 호출하기만 하는데요,
분리할 필요가 있는지 궁금합니다.
2. Unit Test하는 과정에서 Queue에 `dequeue()`가 제대로 되었는지 확인을 위해 `isEmpty()`로 확인하는데요, 이런 방법없이 노드로 직접 접근해서 참조가 사라졌는지 확인하는 것이 더 좋은 방법일까요?
3. `dequeue()`나 `clear()`를 테스트하기 위해서 `enqueue(_:)`를 통해 값을 세팅해주는데요, 
이럴 때 `enqueue(_:)`가 항상 성공할거라는 보장을 얻을 수 있나요? 이 메서드가 실패하면
연쇄적으로 테스트가 실패할텐데, 이를 방지하고자 하는 방법이 있을까요?

2021-07-28 18:06 UTC, leejun6694 requested changes
Charlotte, Soll 안녕하세요 : )
코드 중간 중간에 좋은 아이디어가 보이네요 💯 

1. 음.. 분리했을 때 이유는 어떤 것이었나요?
2. 현재 isEmpty 로 queue 의 데이터가 없는지만 확인해도 될 것 같네요 : )
3. 반대로 말하면 이런 메서드가 실패할 수 있을지 확인하기 위해, 우리가 테스트 코드를 짜고 있을 수도 있겠네요ㅎㅎ 이를 방지하기 위해선 enqueue method 에 에러 처리가 필요하겠네요...!? 저도 좀 더 생각해보겠습니다!

리뷰 내용들도 확인 부탁드려요~~!

2021-07-29 11:09 UTC, yaewonLee commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        return count == 0
노드의 head가 nil인지 아닌지의 여부에 따라 empty 인지 판단가능할 것 같습니다! 16줄에서 count가 0일 경우 true를 반환하게끔 구현하였는데 count를 지운다는 표현이 어떤 의미인지 설명해주실 수 있을까요?

2021-07-29 11:10 UTC, soll4u commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func checkFirst() -> T? {
첫번째 노드의 value를 체크하는 메서드인데요,
`checkValueOfFirstNode`이렇게 바꾸는게 더 명확할까요?

2021-07-29 11:12 UTC, soll4u commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        if isEmpty() {
수정하겠습니다~!

2021-07-29 11:17 UTC, soll4u commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func remove() -> T? {
`removeFirstNode` 이름은 어떤가요? 👀
그리고 하단 부분을 삭제했습니다!
```swift
if isEmpty() {
    return nil
}
```

2021-07-29 11:27 UTC, soll4u commented
@leejun6694 
안녕하세요! 피드백에 따라 수정했습니다.
전에 질문에서 `LinkedList`와 `Queue`를 분리한 이유는 요구사항에서 `Queue 타입 구현을 위한 Linked-list 타입을 직접 구현합니다` 라고 되어있었습니다. 
수정사항 확인 부탁드릴게요! 감사합니다.

2021-07-30 10:13 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        return count == 0
아아 네ㅎㅎ 말씀주신 것처럼 head 로 충분히 isEmpty 를 판단할 수 있기 때문에 count 는 불필요한 property 로 판단했습니다.
불필요한 property 를 굳이 지우려고 하는 이유가 무엇일지 한번 고민해봤으면 해서 질문 드렸습니다 : )

2021-07-30 10:16 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func remove() -> T? {
`removeFirst` 로도 충분할 것 같네요ㅎㅎ

2021-07-30 10:16 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func remove() -> T? {
중간 로직들 없이 `head = head?.next` 로 구현한다면 어떨까요?

2021-07-30 10:20 UTC, leejun6694 commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    mutating func checkFirst() -> T? {
check 는 확인하는 의미로 쓰여서, 저는 보통 return 값으로 Bool 값을 많이 사용했던 것 같습니다.
혹시 이 의견은 어떠실까요~~!?

2021-07-30 11:04 UTC, leejun6694 commented
네! 요구 사항에 적혀 있는 내용처럼 Linked List 를 이용해서, Queue 를 구현하게 됩니다.
지금은 간단한 Queue 를 구현했기 때문에 Linked List 의 method 를 그대로 사용하고 있지만, 다른 기능이 추가된다면 좀 더 와닿을 수도 있겠네요.
여유가 있으시다면, 다른 자료 구조도 직접 구현해보는걸 추천 드립니다 : )

2021-07-30 11:05 UTC, leejun6694 approved these changes

2021-07-30 11:05 UTC, merged