은행창구 매니저[Step1] Nala, Tacocat
yagom-academy/ios-bank-manager pull request #71
Opened 2021-07-29 00:49 UTC by Ldoy

비비 안녕하세요~~~!! 질문을 정리하다보니 어느새 이렇게 많아졌네요...😭 잘 부탁드립니다!!!!
@YebinKim 

1. Queue를 구현할 연결리스트를 단일연결리스트와 이중연결리스트 중 무엇으로 만들지 고민했습니다.
    1. 프로젝트 요구사항을 구현하는 데는 이중연결리스트의 추가적인 기능이 필요하지 않다고 생각해 단일연결리스트로 구현하기로 하였습니다. 
        - 이중연결리스트의 특성상, 노드를 Head와 Tail 각각에서 양방향으로 접근할 수 있는데 현재 기능 요구사항에서는 굳이 필요하지 않다고 생각했습니다. 이중연결리스트를 구현하는 경우 메모리를 많이 차지해 메모리 효율이 낮아지므로 단일연결리스트를 사용해 구현하는 것이 더욱 좋다고 판단했습니다.

2. 코드의 가독성을 위해 `head`, `tail` 노드로 명명하였습니다. 
    1. 처음엔 head만 있어도 된다고 생각했지만 날라의 의견을 들어보니 head, tail로 나눈 것이 직관적이라는 것에 동의하였습니다. 
        1. head :  첫 Node 인스턴스 
        2. tail : 마지막 Node 인스턴스 

3. `Queue`와 `LinkedList` 클래스를 나눈 이유
    1. 처음엔 `LinkedList` 로 구현했습니다.
    2. 프로젝트 명세서에 Queue와LinkedList 타입을 구현하라고 하였기 때문에 위와 같이 하였는데 프로젝트 명세서에 없었다면 Queue 타입안에 LinkedLIst 타입을 한꺼번에 구현해도 되지않을까하는 생각이 듭니다. 

4. `Node`, `LinkedList`, `Queue` 구현 시 클래스 와 구조체 중 어느것으로 해야하는지 궁금해서 아래와 같이 생각했는데 타당한 이유인지 그리고 다른 이유들이 있는지 궁금합니다. 
    1. `Node`의 타입 Class vs Struct
        1. 클래스와 스트럭 중 어느것으로 할 것인가
            1. 클래스로 구현한 이유 : 클래스를 이용하면 하나의 노드(head)를 참조하게 되고 이 head에 연결된 노드들에 대해 참조할 수 있게 된다 
            2. 구조체로 구현하게 되면 생기는 단점 : 노드를 만들때마다(head.next, [head.next.next](http://head.next.next) ...) 스택에 모든 노드가 계속 복사되기 때문에 메모리 최적화 측면에서 효율적이지 않다고 판단
    2. `LinkedList`의 타입
        1. `클래스`로 구현 시 장점
            1. 클래스 안에 스트럭 타입의 속성이 생기면 해당 클래스의 인스턴스가 생길 때마다 내부의 속성에 대한 참조 카운트가 생길때마다 올라가서 클래스로 구현
        2. `스트럭`으로 구현하면 좋은 점과 이유
            1. 스택에 위치하기 때문에 빠른 접근이 가능하다 
            2. 스위프트에서 default 로 설정한 타입은 `Struct`

    b. `Node`를 `Class` 로 구현했다가 `Struct`로 바꾼 이유

    1. 참조 타입이기 때문에 노드를 추가하거나 제거할 때마다 기존 노드의 값을 변경해 주면되지만 구조체의 경우 매번 값을 복사해야하기 때문에 메모리 낭비가 생긴다고 판단했습니다. 
    2. 하지만 현재 Queue인스턴스를 한 개만 만들기 때문에 Struct안의 LinkedList 인스턴스에 대한 참조카운트 문제는 발생하지 않을 것이라고 생각했습니다. 

5. `queue`의 `clear` 메소드를 `haed`에 `nil`을 할당하는 형식으로 진행했는데 모든 `Node`인스턴스가 사라지는 이유를 이렇게 생각해 보았는데 비비의 생각이 궁금합니다

    ```swift
    let queue = Queue
    queue.enqueue(1)
    queue.clear
    ```

    1. 이유 
        1. Queue인스턴스의 위치를 가리키는 상수 `queue` 는 스택에 위치해 있고 이는 인스턴스의 값이 저장된 heap의 주소를 저장하고 있다. 
        2. 이 때 head를 가리키고 있는 head를 nil로 만드는 경우  haed의 next로 참조 되고있던 `Node(1,nil)` 또한 사라진다
        3. 이런 과정이 연쇄적으로 일어나면서 모든 `Node`가 사라진다  

6.  LinkedList 구조체 안의 removeAll 메소드에서 처음엔 head 만 nil 로 해 주었는데 아래와 같이 tail에 대한 참조 카운트가 남아있는 것을 확인했습니다. 코드에서 head 와 tail를 따로 참조하고 있기 때문에 모든 Node 인스턴스를 해제하는  removeAll 메소드를 구현하기 위해선 head 뿐 아니라 tail또한 nil로 해주어야 한다고 생각 했는데 맞는 판단인지 궁금합니다. 

    ```swift
    let linkedList = LinkedList<Int>()
    linkedList.append(1)
    linkedList.append(2)
    linkedList.append(3)

    print(CFGetRetainCount(linkedList.tail)) // 2

    linkedList.removeAll()

    print(CFGetRetainCount(linkedList.tail)) //1
    ```

     

7. MARK주석을 다는 것과 관련해 궁금한 점이 있습니다.
    1. `Node`클래스에서 프로퍼티에 `Properties`라는 주석을 달아주면서 `init()`에도 주석을 달아줘야하나 고민했는데요. 타입이라면 프로퍼티에 대한 `init()` 메소드는 당연히 항상 가지고 있는 것이기 때문에 굳이 달아주지 않아도 되겠다고 생각해 MARK주석을 써주지 않았습니다. 보통 이니셜라이저에도 주석을 달아주는지 궁금합니다.
    2. 주석의 위치 및 조건은 개발자의 주관이라고 생가하면 되는지 궁금합니다. 

8. 테스트코드를 구현할 때, 매직 넘버를 사용하는 것에 대한 고민을 했습니다. 1을 enqueue해주는 상황에서 저희는 `enqueue(1)`을 해주는 방식으로 코드를 작성했는데요.
이렇게 하지 않고 1을 `expectedInputValue`라는 상수로 따로 선언해주고 given에서 알려주는 방식이 더 좋은 방식인 것인지 궁금합니다.

    ```swift
    //1. 1을 숫자 그대로 사용
    //given
        var testQueue = Queue<Int>()

    //when
        testQueue.enqueue(1)
        let outputValue = testQueue.peek() ?? .zero
        let expectedResult = 2

    //2. 1을 상수로 선언해 사용
    //given
        var testQueue = Queue<Int>()
        let expectInputValue = 1
            
    //when
        testQueue.enqueue(expectInputValue)
        let outputValue = testQueue.peek() ?? .zero
        let expectedResult = expectedInputValue
    ```

9. 유닛테스트에서 테스트하는 메소드를 써도 되는지 궁금합니다
    - `Queue`가 제대로 작동하는지 `Queue`의 메소드를 검사하는 테스트를 구현해봤습니다. 그런데 각 메소드를 검사하는 로직에서, 테스트 대상인 다른 `Queue`의 메소드를 반복적으로 사용하게 되었습니다. 테스트는 각각이 의존적이면 안된다고 알고 있는데, 이런 식으로 테스트를 구성해도 되는 것인지 궁금합니다.
    만약 안 된다면, `Queue`의 메소드가 아닌 `LinkedList`의 메소드를 사용해 로직을 구현하는 방식은 괜찮은걸까요? `LinkedLis`t의 메소드들 역시 테스트가 되지 않은 것들인데 어떤 식으로 하는 게 좋은지, 유닛테스트의 범위가 어디까지여야하는지가 잘 이해가 가지 않습니다ㅠㅠ
    - 예를 들어, 현재 `enqueue` 테스트 함수와 `peek` 테스트 함수가 given과 when의 배치만 다르고 확인 로직이 똑같은 상황입니다. 이를 해결하기 위해 아래 코드와 같이 `LinkedList`클래스에서 `first`라는 프로퍼티를 만들어 밖에서 `head`를 읽을 수 있게 만들고, `head`의 `value`를 활용해 `enqueue` 메소드를 테스트해보는 방식을 생각해봤는데요.
    테스트를 위해 코드를 수정하는 것은 하면 안 되는 것으로 알고있어서 어떤 식으로 수정하는 것이 좋을지 비비의 의견이 궁금합니다!

        ```swift
        // LinkedList 클래스
        class LinkedList<Value> {
            var first: Node<Value>? {
                return head
            }
        }

        // enqueue테스트 함수
        func test_testQueue에_1을추가했을때_Queue의첫번째값이1이다() {
            //given
            var testQueue = Queue<Int>()
                
            //when
            testQueue.enqueue(1)
            testQueue.enqueue(2)
            let outputValue = testQueue.linkedlList.first?.value
            let expectedResult = 1
                
            //then
            XCTAssertEqual(outputValue, expectedResult)
        }
        ```

## 코드 Refactoring의 관점에서 생각해본 것들

1. 코드의 가독성(조건을 부정으로 준 것)과 guard와 if의 차이를 반영해 리팩토링 해 보았는데요, 비비의 생각은 어떠신가요?

    ```swift
    // 1. 이전 방식     
    guard !isEmpty() else
        head = Node(value: value)
        tail = head
        return
    }
            
    tail?.next = Node(value: value)
    tail = tail?.next

    // 2. 수정한 방식
    if isEmpty() {
        head = Node(value: value)
                tail = head
                return
    }

    tail?.next = Node(value: value)
            tail = tail?.next
    ```

2. 메소드 이름에 관하여 
    1. LinkedList타입으로 구현 시 사용하는 메소드 이름을 임의로 정해도 되는것인지 궁금합니다
        1. 상식적으로 선택되는 메소드 이름인 `enqueue`, `dequeue`등인건지 궁금합니다.
        2. 예를들어 스택에서는  자료를 추가 및 제거하는 메소드의 이름으로 push, pop을 사용했는데 Queue에서는 Enqueue, Dequeue의 이름으로 설명하는 경우도 있고 완전히 다른 이름으로 사용하는경우, 스택에서 썼던 push, pop 이라는 이름을 그대로 사용하는 경우 등을 찾았습니다. 
3. `Node` 클래스에서 노드를 콘솔에 프린트해보기 위해 2가지 방식을 생각해보았습니다. 굳이 `CustomStringConvertible`을 쓸 이유가 있을까 해서 메소드로 구현을 해봤는데요. 이 상황에서 메소드로 구현하는 것과 `CustomStringConvertible`을 채택해 쓰는 것에 어떤 차이가 있는지 궁금합니다!
    1. `printNodes()` 메소드

        ```swift
        extension Node {
            func printNodes() -> String {
                return "\(value) -> \(String(describing: next))"
            }
        }
        ```

    2. `CustomStringConvertible`

        ```swift
        extension Node: CustomStringConvertible {
          var description: String {
            return "\(value) -> " + String(describing: next)
          }
        }
        ```

4. `isEmpty` 연산프로퍼티와 메소드 구현 차이
    1. LinkedList의 isEmpty 메소드를 연산프로퍼티로 구현할 지 메소드로 구현할 지 고민하였습니다. 연산프로퍼티는 계산의 결과를 저장할 때 사용하고 메소드의 경우 한 번 사용하고 저장하진 않아도 되는 경우라고 생각했습니다. 그래서 현재와 같이 메소드로 구현했는데 비비의 생각은 어떠신지 궁금합니다. 

5. LinkedList, Queue, Node의 메소드를 `Extension`으로 구분하는 것에 대하여 
    1. 클래스에는 상수만 선언하고 메소드의 경우 extension으로구현하면 어떤 이점이 있는가에 대해서 생각해보았습니다.
        1.  Static Dispatch로 메소드가 구현되어 빠른 실행이 가능하다 

6. `defer`의 사용
    1. `remove` 메소드에서 head의 반환하면서 제거하기 위해 defer를 사용
    2. 다른 방법이 있을지 궁금합니다

2021-07-31 12:23 UTC, YebinKim requested changes
타코캣, 날라 안녕하세요~
은행창구 매니저 프로젝트 리뷰를 진행할 비비입니다 😄
미리 얘기 나눴던 대로 질문 가짓수가 꽤 많네요!
질문 대부분이 현재 구현한 부분에 대해 다른 사람의 의견을 구하는 종류의 질문이라고 생각돼서 저도 간략히 생각을 전달드리는 방식으로 리뷰를 진행해볼게요 ☺️
코드 작성에 정답은 없고, 제 의견과 근거는 어떤 맥락에서 이런 관점이 나올 수 있는지를 전달드릴테니 이 관점을 이해하며 다음 스텝 진행에 참고해주시면 좋겠습니다~!
그럼 하나하나 꼼꼼히 읽어보며 답변 위주로 리뷰를 진행해볼게요 😆🙌



---

### 1. 코드에 대해 고민한 점

#### 1-1. `Queue` 를 구현할 연결리스트를 단일 연결리스트와 이중 연결리스트 중 무엇으로 만들지

저도 **한 방향으로 자료가 삽입되고, 방출되는 경우**에는 단일 연결리스트를 사용하는 게 더 적절하다고 생각해요!
그래서 현재의 큐는 자료가 tail -> head 한 방향으로만 삽입되고 방출되기 때문에 단일 연결리스트를 활용하는 것이 적절하다고 생각합니다 😊
만약 큐에서 양방향으로 자료를 삽입해야 한다면 이중 연결리스트의 활용을 고려해볼 수도 있었을 거 같아요~ (이런 큐를 Deque 라고 해요)



#### 1-2. head / tail 네이밍 관련

큐에서 head와 tail로 나누는 것은 좋은 생각인 거 같아요! 현재 큐의 시작점과 마지막점에 모두 접근할 수 있게 되었으니까요.
네이밍은 현재의 head / tail 도 좋고 front / rear 로 표현하기도 한다는 것 참고로 알고 넘어가면 좋겠습니다! 😊

연결리스트에서 또한 큐와 같은 이유로 head와 tail을 구분해 나타내는 것이 좋다고 생각합니다~
네이밍은 현재와 같이 큐와 동일하게 맞추는 것이 이해하기 좋아보여요!



#### 1-3. `Queue` 와 `LinkedList` 클래스를 나눈 이유

두 클래스를 나누는 것에는 여러 이유가 있을 수 있겠지만.. 저는 두 타입의 **의존성 분리**와 **확장성** 측면에서 구분해주는 것이 필요하다고 생각해요~! 
큐와 연결리스트는 각각의 특징을 지닌 서로 구별되는 자료구조이고, 연결리스트는 큐에 종속된 속성이 아니며, LinkedList의 구현 목적이 Queue 의 구현 뿐만이 아닐 수 있기 때문이에요 ㅎㅎ
어떤 이유로 LinkedList 를 Queue 안에 구현해야 한다는 생각을 하게 되었을지가 더 궁금하기도 하네요 🤔



---

### 2. 프로젝트를 진행하면서 나온 질문들

#### 2-1. `Node`, `LinkedList`, `Queue` 구현 시 클래스 와 구조체 중 어느 것을 사용하면 좋을지

`Node` 의 타입은 클래스로 구현하는 것에 대해 말씀해주신 이유에 완전 동의합니다!! 😆👍
또한, 참조카운트를 사용해 `LinkedList` 와 `Queue` 의 삭제 메서드를 구현하고 있기 때문에 클래스로 구현한 현재의 형태가 적절하다는 생각이 드네요~
단, 구조체로 구현했을 때의 단점에 대해서는 복사때문에 메모리 최적화 측면에서 효율적이지 않다는 것에는 의문이 들어요 🤔

`LinkedList` 는 구조체로 구현한 현재의 형태가 적절해보이는데요. 왜냐하면 클래스의 특징을 사용하고 있지 않기 때문이에요 (상속, 참조 등)
`Queue` 또한 동일한 이유로 구조체로 구현하는 것이 적절해보여요~
클래스와 구조체 중 하나를 선택할 때 성능 또한 선택의 이유가 될 수 있지만 **클래스와 구조체의 특징과 기능**을 바탕으로도 생각해보면 좋을 거 같아요!

그리고 클래스 안에 있는 구조체 타입 속성에 대해 참조 카운트가 발생한다고 생각하셨을까요? 🤔
Swift 에서 디폴트로 설정한 타입이 구조체라는 것 또한 의문이 듭니다..!
대부분의 원시 타입을 구조체로 구현하고 있지만, 이게 Swift 타입의 표준이라고 생각하신 근거가 있을까요?

그리고 *`Node` 를 `Class` 로 구현했다가 `Struct` 로 바꾼 이유*에 대해서는
값타입의 경우 값복사에 대한 비용이 저렴하기 때문에 메모리 낭비가 발생한다고 보기는 어려울 거 같아요.
Queue 의 인스턴스가 하나인 것과 참조카운트 문제와는 관련이 없어보이는데 왜 둘을 연관지어 생각하게 되셨을까요?
그리고 현재 Node는 클래스가 아닌 구조체로 구현된 것으로 보이는데요. 혹시 현재 최신 커밋의 PR이 아닌걸까요? 🤔



#### 2-2. `Queue`의 `clear` 메서드 구현에 있어 `haed`에 `nil`을 할당했을 경우, 모든 `Node`인스턴스가 사라지는 이유

우선 head 에만 nil 을 할당하면 모든 Node 인스턴스가 사라지진 않습니다!
tail 에 대한 참조를 `Queue` 의 linkedList 인스턴스가 가지고 있디 때문에 tail 인스턴스가 남게 되는데요.

Queue 의 clear() 메서드가 동작 할 경우,
a는 `queue` 는 구조체기 때문에 인스턴스 또한 stack 에 저장될 것으로 보이며,
b는 head의 노드가 사라졌을 때, 그 다음 노드(NodeA)에 대한 참조가 사라지기 때문에 NodeA 또한 사라지는 것이 맞아요! 👍 단, 예시 코드와 같이 큐 안에 요소가 1개~2개 밖에 없을 때는 tail 참조가 남아있겠죠?
c는 모든 노드가 아닌 **tail 을 제외한 모든 노드**가 사라진다는 것이 정확한 설명이겠네요 ㅎㅎ

노드가 해제되는 것을 직접 확인하고 싶다면 아래와 같이 디이니셜라이저를 추가해보시면 콘솔창에서 확인해볼 수 있어요-!

```` swift
class Node<Value> {
    deinit {
        print("[deinit] Node value \(value)")
    }
}
````



#### 2-3. `LinkedList` 의 모든 요소를 삭제하는 메서드를 수행했을 때 참조카운트가 남아있는 문제 (메모리 누수 문제)

좋은 판단이라고 생각합니다! `LinkedList` 는 tail 에 대한 참조 카운트를 가지기 때문에 tail 또한 nil로 할당해주는 것이 필요했을  것으로 보여요!



#### 2-4. MARK 주석 관련

MARK 주석은 말씀하신 것 처럼 개발자의 주관에 따라 위치나 조건이 달라질 수 있는 영역이라고 생각해요~
저는 init() 메서드에도 주석을 달아주는 편이긴 한데요. 왜냐하면 프로젝트 인디케이터나 미니맵에 이니셜라이저가 이 영역에 있다는 것을 명확히 표시하기 위한 용도로 사용해요!
보통은 어떻게 사용하는가 하면.. 주석은 개발 조직, 개발자 개인에 따라 천지차이로 달라질 수 있는 부분이라 기준을 잡기는 어려울 거 같아요 😅

저는 주석의 중요성을 느끼는 순간이 과거의 제가 쓴 로직을 다시 볼 때나(사실 처음 보는 것과 다름 없죠🤣) 처음 보는 코드를 읽을 때인데요. 이런 경험이 늘다보면 주석을 어떻게 활용하는 게 좋을지 자신만의 방법을 찾아가게 될 거에요~!
그리고 저는 특히 MARK 주석은 파일의 라인수가 길어질 때 적극적으로 활용하는 편이에요 ㅎㅎ 위에서 말했듯 인디케이터나 미니맵을 통해 쉽게 찾기 위해서요.



#### 2-5. 테스트 코드 내에서의 변수 선언 및 매직넘버 관련

저는 매직넘버를 줄이는 2번의 방법이 더 좋다고 생각해요!
가독성과 코드의 수정 편의성을 생각하면 어떤 상황에서든 매직넘버의 사용과 하드코딩은 줄이는게 좋다고 생각하기 때문이에요 ㅎㅎ

코드로 UI를 작성할 때나 기타 특수한 상황을 제외하면 **가능하면 매직넘버의 사용을 지양하는 것**이 좋고, 이는 테스트코드를 작성할 때도 동일하다는 것으로 정리할 수 있겠습니다! 😊👐



#### 2-6. 유닛테스트 파일 안에서의 메서드 선언 관련

*테스트 대상인 다른 `Queue`의 메소드를 반복적으로 사용하게 되었습니다.* -> 이 부분이 이해가 잘 되지 않는데요..! 🤔
말씀하신 것 처럼 **각각의 테스트는 의존성을 띄면 안 되기 때문에** A 메서드에서 B 메서드의 프로퍼티를 사용하는 일은 없도록 작성하는 것이 필요할 거 같아요!

`Queue` 의 기능을 테스트하고자 한다면 `LinkedList` 의 메서드를 사용해 로직을 구현하는 방식은 좋지 않다고 생각하구요.
`LinkedList` 의 기능 테스트가 필요하다면 `LinkedList` 만의 테스트 로직을 별도로 작성해야 할 거 같아요~

예로 들어주신 상황에 따르면 LinkedList 에 수정이 필요한 상황이 맞는 걸로 보여요. 
하지만 이건 **테스트를 위한 수정이 아닌, 기본적으로 LinkedList 에서 제공해야 할 기능이 부족**하기 때문에 수정이 필요한 것이라 생각합니다!
Queue 또한 기본적으로 제공해야 할 기능을 더 보완해야 할 것으로 보이는데 이 부분과 관련해서는 아래 라인별 코멘트에서 언급해두었으니 확인 부탁드려요~



---

### 3. 코드 Refactoring의 관점에서 생각해본 것들

#### 3-1. 코드의 가독성을 위해 guard 구문과 if 구문을 분리한 건
예시로 들어준 코드에 대해서는 **if 로 작성한 현재의 방식이 더 이해하기 쉽다고 생각했어요~**
왜냐하면 if 구문은 true 조건을 분기로 검사하고 있기 때문인데요. 조건을 뒤집어서 사용할 경우 코드를 이해할 때도 한 단계 더 깊게 생각해야 하기 때문에 가능하면 true 조건을 분기로 작성해주는 것을 선호하는 규칙도 있다고 해요 😊

추가로 if 아래의 코드가 실행될 일이 없다면 else 블럭으로 묵어주는 것 또한 좋을 거 같네요!



#### 3-2. 메서드 네이밍 건

메서드 이름은 개발 조직 내에서 정의하기 나름이고 같은 맥락을 가지고 있다면 insert, push, add 등 무엇을 사용해도 문제없다고 생각해요!
다만, 단어의 뉘앙스와 자료구조의 특징에 따라 좀 더 선호하는 네이밍 규칙이 있긴 합니다.

질문에서 예로 들어주신 것 처럼 큐는 대기열에 넣다 / 빼다 라는 의미로서 enqueue / dequeue 를 주로 사용하고
스택은 자료를 밀어넣다 / 꺼내다 라는 의미로서 push / pop 을 주로 사용하고 있어요.

**연결리스트는 노드를 더하다 / 삭제하다 의 의미로 add / remove 를 주로 사용**하고
노드를 삽입하다 / 삭제하다 의 의미로 insert / remove 의 조합으로 사용하기도 하는 것으로 보여요~



#### 3-3. 프린트 로그를 작성할 때 `CustomStringConvertible` 프로토콜을 사용하는 것과 메서드를 작성하는 것의 차이

콘솔창에 로그를 프린트하기 위한 목적이라면 저는 **메서드를 사용하는 것**이 더 편리하고 명확한 표현이라고 생각해요!
왜냐하면 `CustomStringConvertible` 프로토콜을 사용할 경우 매번 `print(instance.description)` 와 같이 프린트 메서드를 별도로 써줘야 하고 instance 의 설명을 출력하겠다는 것으로 해석되지만,
메서드를 사용할 경우 `instance.printNodes()` 와 같이 메서드 호출만 하면 되기 때문에 편리하고 **로그를 출력**하겠다고 더 명확한 단어로 해석할 수 있기 때문이에요~



#### 3-4. `LinkedList` 의  `isEmpty` 연산 프로퍼티와 메서드 구현 차이의 건

저는 연산 프로퍼티와 메서드를 사용할 때 값의 저장 여부를 고려해보진 않았는데요 🤔
개인적으로 한 줄짜리 Bool 타입 반환 메서드는 연산 프로퍼티로 사용해주는 편이에요~
isEmpty 는 **타입의 상태 속성(프로퍼티)을 나타내고 있다**고도 생각하기 때문에 저라면 연산 프로퍼티로 사용할 거 같네요 ㅎㅎ
또한, 이 경우 메서드와 연산 프로퍼티로 구현하는 것에 큰 차이가 있다고 생각하진 않아요!



#### 3-5. `LinkedList`, `Queue`, `Node` 의 메소드를 `Extension` 에서 구현한 건

Node 와 같은 클래스에서는 말씀해주신 것 처럼 Static Dispatch로 메서드가 실행되는 이점이 있을 거 같아요! 이 부분까지 고려해서 설계하시다니 멋집니다 👏👏
추가로 extension 으로 그룹핑하는 것의 이점을 생각해보자면 **public 인터페이스와 private 메서드를 구분지어 사용가능한 메서드를 정리**해서 보여줄 수도 있고, **프로토콜을 채택**해 프로토콜 메서드를 그룹핑할 수도 있고, 그룹핑된 메서드의 **접근제어**를 따로 설정하는 등의 이점이 있을 거 같아요~
단, 클래스에서 extension 에 선언된 메서드는 상속될 수 없다는 것도 같이 생각하고 넘어가면 좋을 거 같아요 ☺️



#### 3-6. `defer` 블럭 사용의 건

defer 블럭을 멋지게 사용하셨군요!! 👍
defer를 사용하지 않으려면 아래와 같이 임시 변수를 사용해볼 수도 있어요~!

```swift
mutating func remove() -> Value? {
    let headValue = head?.value
    head = head?.next
    return headValue
}
```



---

리뷰가 꽤 길어졌는데요..!
많은 고민을 통해 코드를 작성한 노력이 보였어요!! ☺️👍
extension 과 defer 블럭의 활용 등 Swift 문법을 활용해보는 것 또한 훌륭했다고 생각합니다 😄

추가로, 현재 스텝에서 보완하면 좋을 점이 몇 개 보여서 Request changes 로 요청드렸어요~
`Node` 의 구현과 `LinkedList` 의 구현과 관련해 궁금한 점을 아래 라인별 코멘트에 남겨두었으니 이 부분과 위의 종합코멘트에서의 의문을 포함해서 다같이 회의실에서 만나 얘기를 나눠보면 좋을 거 같아요! 단체 DM 방에서 시간을 잡아봅시닷 😆🙏

2021-07-31 12:23 UTC, YebinKim commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +extension LinkedList {
LinkedList 에서 특정 위치에 **요소를 추가**하거나 **삭제**하는 기능, **특정 요소를 검색**할 수 있는 기능 또한 고려가 되면 좋을 거 같아요!
타입의 원활한 활용을 위해 추가, 삭제, 검색 기능은 반드시 필요하다고 생각해요~

2021-07-31 12:23 UTC, YebinKim commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var linkedList = LinkedList<Value>()
외부에서는 linkedList 에 대해 접근할 수 없게 private 프로퍼티로 지정해주면 좋을 거 같아요~
Queue 를 다루는 것은 Queue Manage Method 를 통해서만 이루어지도록 해주는 것이 Queue 타입을 제대로 활용하고, 타입의 추상화를 향상시킬 수 있는 방법이라고 생각해요!

2021-07-31 12:23 UTC, YebinKim commented on BankManagerConsoleApp/QueueMethodTest/QueueMethodTest.swift
> +        var testQueue = Queue<Int>()
testQueue 는 변경되지 않기 때문에 let 으로 선언할 수도 있을 거 같아요!

2021-07-31 12:23 UTC, YebinKim commented on BankManagerConsoleApp/QueueMethodTest/QueueMethodTest.swift
> +class QueueMethodTest: XCTestCase {
given-when-then 패턴의 활용!! 아주 좋습니다 😆
추가로 테스트 커버리지 또한 높은 것으로 보이는데요!
불필요한 nil 병합 연산자가 있는지 확인해보고, 자료가 없을 때에 대한 테스트 또한 추가된다면 테스트 커버리지가 더욱 높아질 것으로 보입니다 😊

<img width="859" alt="테스트커버리지" src="https://user-images.githubusercontent.com/38066039/127739656-f01fca75-6e45-4d4d-b961-33573d902620.png">

2021-08-01 04:25 UTC, Ldoy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func glance() -> Value? {
Queue에서 peek라는 메소드 명을 사용하려고 해서 peek와 비슷한 이름을 찾다 glance 를 사용하게 되었습니다😄

2021-08-02 01:19 UTC, Ldoy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        defer { head = head?.next }
으핳 감사합니다~~~🤩🤩

2021-08-02 01:20 UTC, Ldoy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +        return head?.value ?? nil
엇 맞습니다..ㅜㅜ 요 부분을 놓쳤네요! LinkedList의 remove메서드, Queue의 dequeue메서드 nil 병합연산자 부분 제거하는 쪽으로 수정했습니다!

2021-08-02 01:21 UTC, jazz-ing commented on BankManagerConsoleApp/QueueMethodTest/QueueMethodTest.swift
> +class QueueMethodTest: XCTestCase {
테스트 커버리지를 보는 것까지 생각해보지 못했는데 확인해주셔서 감사합니다! 
앞으로 유닛테스트를 하게되면 테스트 커버리지 확인을 해봐야겠어요 :)

2021-08-02 01:21 UTC, Ldoy commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +    func glance() -> Value? {
비비와의 대화 :  pick도 좋을 것 같다
(히스토리 기록 차 남겨둡니다.)

2021-08-02 01:23 UTC, jazz-ing commented on BankManagerConsoleApp/QueueMethodTest/QueueMethodTest.swift
> +        var testQueue = Queue<Int>()
Queue를 struct로 만들었다보니 let으로 선언하면 컴파일 오류가 뜨더라구요😭
일단은 var로 선언해두었습니다..!

2021-08-02 01:25 UTC, jazz-ing commented on BankManagerConsoleApp/BankManagerConsoleApp/Queue.swift
> +    var linkedList = LinkedList<Value>()
아하 그러네요!
Queue에서 linkedList에 접근하면 안된다는 생각을 미처 못했었습니다.
Queue는 Queue로만 작동할 수 있도록 linkedList에 접근제한자를 주는게 맞는 방향인 것 같습니다!
수정 반영했습니다 :)

2021-08-02 01:27 UTC, jazz-ing commented on BankManagerConsoleApp/BankManagerConsoleApp/LinkedList.swift
> +extension LinkedList {
프로젝트 기능구현에 초점을 맞추느라 LinkedList 자체에 대한 구현을 완전하게 하지 못한 것 같습니다.
생각해보니 LinkedList는 Queue를 구현하는 방식이니 Queue가 가진 특성과 다른 LinkedList만의 특성들이 있겠군요!
특정 인덱스에 접근하는 기능은 어떻게 구현할 수 있을까 생각해보겠습니다ㅎㅎ

2021-08-02 01:29 UTC, Ldoy commented
> ### 1. 코드에 대해 고민한 점
> #### 1-3. `Queue` 와 `LinkedList` 클래스를 나눈 이유
> 두 클래스를 나누는 것에는 여러 이유가 있을 수 있겠지만.. 저는 두 타입의 **의존성 분리**와 **확장성** 측면에서 구분해주는 것이 필요하다고 생각해요~!
> 큐와 연결리스트는 각각의 특징을 지닌 서로 구별되는 자료구조이고, 연결리스트는 큐에 종속된 속성이 아니며, LinkedList의 구현 목적이 Queue 의 구현 뿐만이 아닐 수 있기 때문이에요 ㅎㅎ
> 어떤 이유로 LinkedList 를 Queue 안에 구현해야 한다는 생각을 하게 되었을지가 더 궁금하기도 하네요 🤔
(비비와의 대화 히스토리기록차 남깁니다)
현재 LinkedLIst에 기능을 덜 구현해서 Queue와의 차이가 안 느껴지는 것이다. LinkedList와 Queue의  검색, 삭제, 삽입의 측면에서의 차이점은 Queue의 경우 FIFO, LInkedList의 경우 자료의 검색 및 삽입에 제한이 없다는 것 등에서 차이가 있는데 LinkedList의 기능을 충분히 구현한다면 Queue와의 차이가 확실히 느껴질 것 같다. Queue는 LinkeList의 기능을 어느정도 제한해서 구현하는 자료구조로 받아들이면 될 것 같다. 
> ### 2. 프로젝트를 진행하면서 나온 질문들
> #### 2-1. `Node`, `LinkedList`, `Queue` 구현 시 클래스 와 구조체 중 어느 것을 사용하면 좋을지
> 그리고 클래스 안에 있는 구조체 타입 속성에 대해 참조 카운트가 발생한다고 생각하셨을까요? 🤔
> Swift 에서 디폴트로 설정한 타입이 구조체라는 것 또한 의문이 듭니다..!
> 대부분의 원시 타입을 구조체로 구현하고 있지만, 이게 Swift 타입의 표준이라고 생각하신 근거가 있을까요?
> 
> 그리고 _`Node` 를 `Class` 로 구현했다가 `Struct` 로 바꾼 이유_에 대해서는
> 값타입의 경우 값복사에 대한 비용이 저렴하기 때문에 메모리 낭비가 발생한다고 보기는 어려울 거 같아요.
> Queue 의 인스턴스가 하나인 것과 참조카운트 문제와는 관련이 없어보이는데 왜 둘을 연관지어 생각하게 되셨을까요?
> 그리고 현재 Node는 클래스가 아닌 구조체로 구현된 것으로 보이는데요. 혹시 현재 최신 커밋의 PR이 아닌걸까요? 🤔
Node가 아니라 Queue, LinkedList타입이었는데 잘못 작성했네요. 죄송합니다 😭 디스코드에서 공유한 링크 아래에 히스토리 기록차 첨부합니다. 구조체 안에 클래스 인스턴스가 있는경우 해당 구조체 인스턴스를 여러번 복사하면  내부 클래스 인스턴스의 CFGetRetainCount값이 증가하는 것을 확인하여 위와 같은 맥락의 질문을 드렸습니다. 
https://swiftrocks.com/memory-management-and-performance-of-value-types

2021-08-02 01:33 UTC, Ldoy commented on BankManagerConsoleApp/BankManagerConsoleApp/Node.swift
> +    init(value: Value, next: Node? = nil) {
init 의 의도를 생각하지 않고 구현했던 것 같습니다.😭 비비가 얘기하셨던 것처럼 인스턴스를 만들 때 위의 코드처럼 init을 구현하는 경우 Node의 기본 값을 nil 로 제공하고 있는데 초기화 할 때도 마찬가지로 입력하라는 의미가 되므로 var next의 기본값을 nil로 설정하고 value의 값만 추가하는 init메서드와 value, next의 값 모두를 초기화 할 수 있는 init을 구현하는 방향으로 refactoring 하였습니다.

2021-08-03 04:13 UTC, YebinKim approved these changes
타코캣, 날라 Step1 고생 많으셨어요~
회의실에서 만나 얘기 나누었던대로 이번 스텝은 이대로 머지 진행하겠습니다~ 😊

컴파일러 워닝 관련해서 추가 코멘트가 하나 있는데요!
이 부분은 확인해보시구 그래도 컴파일 오류가 발생한다면 말씀해주세요~

2021-08-03 04:13 UTC, YebinKim commented on BankManagerConsoleApp/QueueMethodTest/QueueMethodTest.swift
> +        var testQueue = Queue<Int>()
해당 테스트에서는 queue의 값을 수정하지 않기 때문에 let 으로 선언했을 때 문제가 없어야 할 것으로 보이는데요 🤔
혹시 컴파일 오류가 발생했다면 (자주 그렇듯) XCode 문제일 수도 있으니 클린빌드 후 다시 한 번 확인해보시겠어요? 😄

2021-08-03 04:13 UTC, merged