ios-bank-manager[Step2]Jost, Hosinging
yagom-academy/ios-bank-manager pull request #78
Opened 2021-07-30 16:04 UTC by Hosinging

안녕하세요 라쟈냐 @wonhee009 
저희 Step2 PR보냅니다. 늦은 시간에 PR보내게되서 죄송합니다. 주말에 리뷰를 받고 싶다기보다 월요일에 학습활동도 있고, 팀원 모두가 스케쥴이 있어서 보낼 시간이 애매할 것 같아서 지금 보내게됐습니다. 양해부탁드립니다.

### UML
![image](https://user-images.githubusercontent.com/39648822/127678063-7d8e6fbc-f430-4b6d-a003-aff186ccc0c9.png)

---
### 궁금했던 점 & 고민했던 점

> TypeAlias를 Bank, BankManage 타입 내부에 있는 메서드의 리턴 타입으로 사용을 하기 때문에 의존 관계로 표현을 해봤는데 TypeAlias는 사용자 정의 타입이 아닌데 의존으로 보는게 맞을지 궁금합니다.

> UML 관련, Generic 타입이 매개변수와 리턴타입으로 사용되는경우, 이들과 연관관계로 표현을 하는 것이 맞느지 궁금합니다.

> Mark주석을 활용해 봤는데 작성하다보니 과하게 작성이 된 것 같은 느낌이 있는데 라자냐의 사내에서는 Mark주석에 대한 어떤 Convention을 가지고 있는지 궁금합니다.

> OOP설계 관련해서 역할과 기능 상세에 따라 타입 내 프로퍼티와 메서드를 타입의 역할에 맞게 만들려고 노력을 했습니다. 근데, 이 부분 관련해서 적절하게 설계가 된 것인지 의견부탁드립니다.

2021-08-02 06:27 UTC, wonhee009 requested changes
@Hosinging @YongHoonJJo Jost, Hosinging step2 수고하셨습니다!🎉
리뷰 남겼으니 확인해주세요🙏

> TypeAlias를 Bank, BankManage 타입 내부에 있는 메서드의 리턴 타입으로 사용을 하기 때문에 의존 관계로 표현을 해봤는데 TypeAlias는 사용자 정의 타입이 아닌데 의존으로 보는게 맞을지 궁금합니다.

typeAlias로 내가 원하는 타입을 만든다고 볼 수 있지 않을까요?

> UML 관련, Generic 타입이 매개변수와 리턴타입으로 사용되는경우, 이들과 연관관계로 표현을 하는 것이 맞느지 궁금합니다.

[이런 포스트](https://stackoverflow.com/questions/4786771/uml-class-diagram-and-generics)도 확인해보시면 좋을거 같아요.

> Mark주석을 활용해 봤는데 작성하다보니 과하게 작성이 된 것 같은 느낌이 있는데 라자냐의 사내에서는 Mark주석에 대한 어떤 Convention을 가지고 있는지 궁금합니다.

따로 가지고 있는 convention은 없습니다만, MARK 주석을 작성하면 갖을 수 있는 장점과 단점을 생각해보면 좋을거 같아요.

> OOP설계 관련해서 역할과 기능 상세에 따라 타입 내 프로퍼티와 메서드를 타입의 역할에 맞게 만들려고 노력을 했습니다. 근데, 이 부분 관련해서 적절하게 설계가 된 것인지 의견부탁드립니다.

이 부분에 대해서는 리뷰 확인하시고 개선하다보면 좀 더 개선될 수 있을거 같아요.

Jost와 Hosinging에게 궁금한 점도 남겨놓을테니 시간 될때 확인 부탁드립니다!

- 하나의 타입(class/struct)를 정희하고 그 밑으로 `extension`을 적극적으로 사용하셨네요. 어떤 기준을 가지고 extension을 나누는지 궁금했습니다.

2021-08-02 12:30 UTC, Hosinging reviewed
> Jost와 Hosinging에게 궁금한 점도 남겨놓을테니 시간 될때 확인 부탁드립니다!

하나의 타입(class/struct)를 정의하고 그 밑으로 extension을 적극적으로 사용하셨네요. 어떤 기준을 가지고 extension을 나누는지 궁금했습니다.

일단, Extension에 메서드를 작성하게 된 것은 메서드 호출 시 Direct Dispatch와 Dynamic Dispatch가 있는데 Extension에 메서드를 구현했을 경우, Direct Dispatch로 함수가 호출되고, 이 것이 성능적으로 더 좋다는 글을 보고, 해당 내용을 반영해보고자 했습니다. 

Extension을 여러 개로 분리 해서 메서드를 작성하게 된 것은 해당 타입 내에서 메서드의 접근제어레벨, 성격에 따라 나누어봤습니다.

2021-08-02 12:30 UTC, Hosinging commented on BankManager.swift
> +    }
참고 링크로 보내주신 LocalizedError프로토콜과  https://velog.io/@wonhee010/Enum%EA%B3%BC-Error%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC내용을 참고해서 아래 내용으로 변경해봤습니다.

1. Error프로토콜을 채택한 BankManagerErrorMessage를 선언하고, LocalizedError 프로토콜을 익스텐션에서 채택
2. inputFromUser() 메서드를 throwing function으로 변경 후 do catch블락에서 함수 호출.
3. showErrorDescription(message:)메서드 내부 구현 변경

LocalizedError에서 errorDescription인스턴스 프로퍼티가 옵셔널 스트링이라 옵셔널 바인딩으로 옵셔널을 처리해줬는데요.
오류가 발생한 경우에 에러 메시지 표시를 위해서 만든 타입인데, 굳이 옵셔널 스트링으로 되어있는 LocalizedError프로토콜의 errorDescription프로퍼티를 사용해 처리해줘야되는게 적절할지 조금 고민이 되었습니다. 이 부분을 LocalizedError프로토콜을 채택하지 않고, Error타입을 선언한 Enum타입만 선언 후 catch문에서 error.localizedDescription으로 에러를 보여주는게 조금 더 효율적인게 아닌가 이런 생각을 해봤습니다.

2021-08-03 01:17 UTC, wonhee009 commented on BankManager.swift
> +        let (numberOfClient, totalTaskTime) = bank.doTask()
타입 추론이 가능하지만 정의해둔 Typealias를 사용한다면 나중에 봤을때 알아보기 쉽지 않을까해서 의견 드렸습니다.

2021-08-03 03:12 UTC, wonhee009 requested changes

2021-08-03 03:12 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
> 은행의 작업이 다시 시작할 때마다 이전과 동일한 순서로 배치하는게 좋다고 생각

어떤 부분에서 좋다고 생각했는지 궁금해요.

> 이후 스텝에서 은행원이 여러 명이 될 수 있는 상황에 대해서 은행원들의 상태를 별도로 확인할 필요가 있다고 생각이 들어 배열로 관리하게 되었습니다.

이 부분은 큐에서는 은행원이 돌아가고 있고, array를 계속 돌면서 은행원이 일을하고 있는지 대기 중인지 확인해보겠다는 건가요?
만약 제가 생각한 부분이 맞다면 일이 다 끝난 은행원을 dequeue한 후 일을 할당하고 enqueue하는 것보다 array를 지속적으로 확인하는 비용이 더 클 것 같은데요. 의견 궁금합니다!

2021-08-03 03:12 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            if !bankTellerQueue.isEmpty(),
이런 부분은 `isNotEmpty`를 정의해 보는건 어떤가요?

2021-08-03 03:12 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/TaskCategory.swift
> +        }
업무할때 걸리는 시간을 가져오는거라서 get-으로 네이밍한거 같아요.
하지만 getTaskTime은 프로퍼티이니 그에 맞는 네이밍이 필요하지 않을까요?

2021-08-03 03:23 UTC, wonhee009 commented on BankManager.swift
> +    }
> 굳이 옵셔널 스트링으로 되어있는 LocalizedError프로토콜의 errorDescription프로퍼티를 사용해 처리해줘야되는게 적절할지

이런 생각 저도 해본적 있는데 현재는 errorDescription만 사용하고 있어서 그렇게 느끼는거 같아요.
LocalizedError 프로토콜 문서를 확인해 보고 다른 부분들도 점차 적용해보다 보면 이런 의문을 좀 더 지울 수 있을거 같아요.

2021-08-03 03:25 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    let tasks: [TaskCategory]
실생활을 고려해보는건 좋지만 명세서에 맞춰서 개발하는거도 중요한거 같아요.
현재 프로젝트에서 손님의 업무가 여러개가 될 가능성이 있느냐 없느냐가 중요할거 같습니다.

2021-08-03 05:10 UTC, Hosinging commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
issueQueueTicket을 issueWaitingNumberTicket으로 네이밍 변경했습니다.🙂

2021-08-03 05:27 UTC, Hosinging commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
순서대로 배치하는건 사실 크게 중요하진 않습니다. 
하지만 아래 질문 관련하여, 
은행원이 늘어났을 경우, 모든 은행원의 업무가 끝난 시점을 알아야 할 필요가 있다고 생각했습니다. 
이부분은 array 를 통해 지속적으로 확인해보려고 생각했던 것도 맞습니다. 
다만, 일이 다 끝난 은행원을 dequeue한 후 일을 할당하고 enqueue하는 것이 더 낫다고 하셨는데요, dequque 는 은행원의 대기열로 대기중인 고객이 있을때 발생해야 하는 Action 이라고 생각합니다. 

Role 의 관점에서 맞지 않다고도 생각을 합니다. 그리고 대기중인 고객을 처리하는 과정에서 비동기로 발생이 되는데, 이때마다 손님이 있으면 은행원의 대기열큐에서 dequeue 라는 과정을 진행해야하는데, 이러한 과정 도중에 모든 은행원의 업무가 끝난 시점을 알기 위해 은행원의 대기열 큐에서 함부로 dequeue 를 할 수도 없다고 생각을 합니다. 이러한 이유들로 인해 현재 스텝만 봤을 때는 불필요해보일수 있지만, 은행원이 여러명일 경우 필요하겠다고 생각이 되어 위와 같이 구성을 하였습니다

2021-08-03 05:29 UTC, Hosinging commented on BankManagerConsoleApp/BankManagerConsoleApp/Client.swift
> +    let tasks: [TaskCategory]
실생활을 고려해서 해보려고 했는데, 라자냐 말대로 기능 상세에 맞춰서 개발하는게 맞는 것 같습니다. 수정하겠습니다~!!

2021-08-03 05:58 UTC, Hosinging commented on BankManager.swift
> +        }
```swift
do {
  // Some statements
} catch {
  showErrorDescription(message: error)
}
```
catch문에서 error를 다운캐스팅하고, 에러 패턴 별로 분기해서 처리를 하고, 그 패턴 외의 나머지 에러들은 별도의 catach문에서 처리할 수 있게끔 의도해서 만들었었는데요. 
공식문서에 있는 ErrorHandling에서는 do catch의 catch문에서 에러 패턴별로 catch문을 작성하고, 그 외의 처리는 패턴이 없는 catach문을 통해 모두 처리할 수 있게 해주어서 만드는 패턴이었기에 저희가 만든 부분이 문제가 없다고 생각했었습니다. 
라자냐의 리뷰대로 아래와 같이 변경을 하긴했는데, 라자냐가 말씀하신 개선의 '의도'가 궁금했습니다.

```swift 
private func showErrorDescription(message: Error) {
  if let error = message as? BankManagerErrorMessage {
    switch error {
    case .wrongInput:
        print(error.errorDescription ?? "")
    }
  }
  print("예기치 못한 오류 발생. 프로그램을 종료합니다.")
}
```
BankManagerErrorMessage 열거형에서 익스텐션으로 채택한 LocalizedError프로토콜의 연산 프로퍼티인 errorDescription이 옵셔널 스트링 타입이지만, 그 리턴값으로 값을 넣어줬고, 접근할 때마다 그 값이 리턴되는 상황이라 실제 사용하는 showErrorDescription(message:)에서 옵셔널 바인딩을 해줄까 하다가 값이 항상 있으니 값이 없는 상황에 대한 위험도가 낮다고 생각해서 nil Collescing을 사용해서 옵셔널 값을 처리해줬습니다. 이 경우에 문제가 되는 부분이 있을까요?

2021-08-03 06:16 UTC, Hosinging commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            if !bankTellerQueue.isEmpty(),
말씀해주신 내용으로 isNotEmpty() 정의 후 적용해봤습니다.
하지만, 
isNotEmpty()를 별도로 정의해줘야되는 이유를 잘 모르겠습니다. 
기존에 isEmpty()는 true false를 리턴하기 때문에 위의 코드에서 처럼 !연산자를 통해 반대 의미를 표현할 수 있고, 아래와 같이 표현해 볼 수도 있을 것 같은데 isNotEmpty()를 별도로 정의해보는 것을 제안해주신 이유가 있을까요?
```swift
isEmpty() != true
```

2021-08-03 06:18 UTC, Hosinging commented on BankManagerConsoleApp/BankManagerConsoleApp/TaskCategory.swift
> +        }
taskTime이라는 네이밍으로 변경했습니다.

2021-08-03 07:10 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +            if !bankTellerQueue.isEmpty(),
가독성 떄문에 의견 드렸습니다.
현업에서도 많이 `isNotEmpty`는 따로 정의해서 사용하거든요.
물론 `!`를 사용해서 같은 의미로 사용할 수 있지만 코드를 읽다보면 가독성이 떨어지는 부분이 있거든요.

2021-08-03 11:29 UTC, wonhee009 commented on BankManager.swift
> +        }
문제가 되는 부분이 있는건 아닙니다.
제가 개선을 요청 드렸던 이유는 이후 재사용성 측면에서였습니다.
- 현재는 하나의 에러타입을 사용하고 있는데 이후 서비스가 확장된다면 여러 에러타입이 생겨나게 됩니다.
- 여러 에러타입이 생겨남에 따라 다양한 에러를 던지는 코드들이 생겨나게 됩니다.
이전의 코드에 위와 같은 상황을 대입해볼까요?
```swift
do {
     ...
} catch let error as Error1 {
     ...
} catch let error as Error2 {
     ...
} catch let error as Error3 {
     ...
}
```
위와 같은 코드가 생성되겠죠?
그리고 에러를 던지는 곳이 10곳이라면 10곳 모두에 위의 코드를 삽입해줘야하겠죠.
따라서 재사용성을 위해 개선 의견을 드렸습니다.

공식문서의 ErrorHandling 예제에 대해서 말씀해주셨는데 이 부분은 위에서 제가 말씀드린 상황에 대한 고려가 없는 Basic한 예제라고 생각됩니다.

2021-08-03 11:35 UTC, wonhee009 commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    }
제가 생각했던 Queue의 역할이 호싱잉이 생각하는 역할과 좀 차이가 있는거 같습니다.☺️

2021-08-03 11:36 UTC, wonhee009 commented
@Hosinging @YongHoonJJo 스텝2 수고하셨습니다.
다음 스텝에서 봐욥!

2021-08-03 11:36 UTC, merged