은행창구 매니저 [STEP 2] 요시킴, 엘렌
yagom-academy/ios-bank-manager pull request #82
Opened 2021-08-02 13:28 UTC by jcrescent61

안녕하세요 린생! Step2 PR입니다 ㅎㅎ 잘부탁드려요 ㅎ
이전 스탭 피드백 너무 감사했습니다 😁

## 고민한 점

### [1] 코드 가독성에 대해서 고민했습니다.

<img width="868" alt="Screen Shot 2021-08-02 at 10 12 39 PM" src="https://user-images.githubusercontent.com/80380535/127869282-c6556af9-10ea-430b-bd33-1db743652edd.png">

모든 타입안의 첫번째 메소드는 헤드라인처럼 핵심...?인 메소드로 위치를 지정했습니다.
신문기사처럼 읽힐 수 있도록 메소드 위치를 지정했습니다... 이런식으로 설계하면 가독성이 좋을지 모르겠네요!!!

---

### [2] 단일 책임 원칙에 대해서 고민했습니다.

하나의 메소드는 하나의 책임만 가지도록 설계했습니다.
이것도 위의 사항과 마찬가지로 잘 구현하고 있는 것인지 모르겠습니다ㅠㅠ

---

### [3] rawValue에 접근하는 방식이 좋은지 모르겠습니다.

```swift
enum MainMenuMessage: String {
    case firstSelection = "1"
    case secondSelection = "2"
}

private func displayIncorrectInput() {
        if userInput != MainMenuMessage.firstSelection.rawValue
            && userInput != MainMenuMessage.secondSelection.rawValue {
            print(MainMenuMessage.wrongInput.description)
        }
```

열거형 케이스 안의 원시값에 직접 접근하는 것은 좋지않다는 이야기를 들었습니다....?
어떤 사이드 이펙트가 생길 수 있는지 궁금합니다.

----

### [4] ReadLine의 옵셔널을 언래핑하지 않았습니다.

```swift
private mutating func getUserInput() {
        self.userInput = readLine()
}
    
private mutating func repeatUntilCollectSelection() {
        while userInput != MainMenuMessage.firstSelection.rawValue
                && userInput != MainMenuMessage.secondSelection.rawValue {
            displayMainMenuMessage()
            getUserInput()
            displayIncorrectInput()
  }
}
```

유저에게 1또는 2를 입력받아 옵셔널 자체로 선택지를 비교했습니다.
유저입력을 언래핑해도 그 값을 활용할 필요가 없기 때문에 불필요한 작업이라 생각되어 굳이 하지 않았습니다.
이런식으로 작성하면 문제가 생길지 궁금합니다.

---

### [5] Model에서 파일을 생성해서 나누는 단위를 어떻게 나눠야 할지 궁금합니다.

![2021-08-02_10 22 47](https://user-images.githubusercontent.com/80380535/127869139-98887109-f9be-4d37-8d31-5db98aa7a8b7.png)

코드의 연관성을 기준으로 파일을 나눴는데 이런식으로 나누는 것이 맞는지 궁금합니다.
또 파일을 생성할때 기준에 대해서 궁금합니다.

---

@jcrescent61 @taeyoung-Kim-KR @jungseungyeo

2021-08-02 15:10 UTC, jungseungyeo requested changes
### [1] 코드 가독성에 대해서 고민했습니다.

> 이 부분 좋아요! 함수의 순서도 호출 되는 순서로 변경이 되면 더욱 좋을거 같아요! 이렇게 작성하는 내용이 cleanCode에서 자세히 나와있어요. 처음 호출되는 함수는 추상적으로 작성하고 점차 내부적으로 들어 갈수록 구체적인 내용으로 작성하면 더욱 좋습니다.

### [2] 단일 책임 원칙에 대해서 고민했습니다.

> 하나의 책임을 가지는 건 중요해요. SRP(단일 책임의 원칙)을 위반하는 것이 하나 보여서 코멘트 남겼어요!

### [3] rawValue에 접근하는 방식이 좋은지 모르겠습니다.

> 이펙트는 생길 일은 없습니다. 원식값을 사용하는 것보다는 protocol을 활용하여 작성하는게 좋습니다. 하지만 크게 문제가 되는 부분은 아니예요. 이 부분은 rawValue를 사용하는 것보다는 검사하는 조건의 복잡도가 더 높아 가독성이 낮아지는거 같아요!

### [4]ReadLine의 옵셔널을 언래핑하지 않았습니다.

> 전혀 문제가 되지 않습니다! 

### [5] Model에서 파일을 생성해서 나누는 단위를 어떻게 나눠야 할지 궁금합니다.

> 파일을 나누는 기준은 각자 다를거 같아요! 각자 기준을 정하고 하는게 맞습니다. 현재 파일에서는 근데 모델을 찾을 수가 없는 거 같아요!. 모델의 역할이 무엇일까요? 현재 작성 된 파일들은 모델의 역할이 맞을까요??


@jcrescent61 @taeyoung-Kim-KR 너무 고생했어요! 코드를 볼 수록 완성도가 더 좋아지는거 같아요! 특히 테스트 코드를 작성하는 부분이 너무 좋습니다. 하지만 파일을 나누는 것이 아직 서투른거 같아요!  MVC를 기준으로 파일을 나누고 의존 관계가 있는 객체 끼리 뭉쳐두면 코드 점핑이 적어 좀 더 가독성이 좋아요! 한번 적용해보면 좋을거같아요!

2021-08-02 15:26 UTC, jungseungyeo commented
### [UML 리뷰]

UML을 너무 잘 만들어주셨어요! 클래스, 구조체, enum등을 나누고 의존 관계를 보여주는 형태가 너무 좋았습니다. 정석적으로 너무 잘 작성해주셨는데 실선과 점선이 차이는 있는데 실제 코드에서는 차이가 없는거 같아요!

https://www.nextree.co.kr/p6753/ 여기 내용을 보면 좀 더 도움이 될 거같아요! 
또한 이것을 잘 작성하는 tool도 사용해보면 좋을거같아요! -> https://staruml.io/

2021-08-03 06:12 UTC, taeyoung-Kim-KR commented on BankManagerConsoleApp/BankManagerConsoleAppTests/BankManagerConsoleAppTests.swift
> +    func test_enqueue_했을때_헤드가_nil이면_실패() {
아! 알겠습니다~!

2021-08-03 06:12 UTC, jcrescent61 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +    func start() {
MainManager의 인스턴스를 생성한 모듈에서만 start 함수를 사용할수있게 제한을 두고 싶었습니다!!!
main.swift이외에서는 사용할 일이 없는데 다른 모듈이 알 필요가 있을까 싶어서 internal로 변경했습니다 ㅎㅎ

2021-08-03 06:36 UTC, jcrescent61 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +            Thread.sleep(forTimeInterval: workingTime)
### 1. `Thread.sleep` 메소드를 사용한이유
- DispatchQueue를 활용해서 지연시간을 부여하고 싶었지만
아직 DispatchQueue에 대한 이해도가 높지 않아 실질적인 활용 단계는 Step3부터 진행해보고싶었습니다 ㅎ
결론을 말씀드리자면 공부부족이겠네요....


---
### 2. `Thread.sleep` 메소드란?
https://developer.apple.com/documentation/foundation/thread/1413673-sleep
아래는 공식문서의 내용입니다.

Sleeps the thread for a given time interval.
 No run loop processing occurs while the thread is blocked.
 지정된 시간 만큼 쓰레드를 sleep상태(수면상태)가 됩니다.
 스레드가 block된 동안에는 실행 루프 처리가 수행되지 않습니다.

아마 특정 Queue로 보내는 작업을 하지 않는 것으로 보아
메인 쓰레드를 block 하는 것 같네요!


---
### 3. 현재 프로젝트에는 사용해도 되지만 다른 프로젝트에서는 사용하면 안되는 이유
View와 관련된 작업(사용자의 터치 등)은 메인쓰레드에서 담당합니다.
결국 메인쓰레드를 block 한다는 것은 나중에 UI를 사용하는 프로젝트의 경우에는 절대 사용하면 안되는 메소드인 것 같습니다.
현재 프로젝트에서는 UI를 구성하지 않으므로 사용해도 문제가 없을거라 판단하여 `sleep`메소드를 사용했습니다.

2021-08-03 08:10 UTC, jcrescent61 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +        while userInput != MainMenuMessage.firstSelection.rawValue
안녕하세요 린생!!

이런식으로 내부에서 값을 비교하는 메소드가 필요한 경우에는
전부 extension을 사용해서 불리언을 반환하는 메소드를 따로 만들어서 사용해도 될까요?
BankManager 뿐만이 아니라 모든 타입에 대해서도 
더 나아가 앞으로 하게 될 프로젝트들의 메소드에서도
extension을 활용한 비교문들을 관리하는 설계를해도 될까요?

2021-08-03 08:13 UTC, jcrescent61 commented
안녕하세요 린생!

UML링크 정말 유용한 정보인 것 같습니다!!!
피드백에서 질문하신 사항에 대한 답변과 별도의 추가질문은 코멘트로 남겼습니다.
감사합니다!!!ㅎㅎㅎ

@jungseungyeo @taeyoung-Kim-KR

2021-08-03 13:18 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +            Thread.sleep(forTimeInterval: workingTime)
너무 잘 이해하고 있는거 같아요! 알아보신 내용을 꼭 잊지마세요! DispatchQueue는 step3에서 진행해보아요 :)

2021-08-03 13:33 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +        while userInput != MainMenuMessage.firstSelection.rawValue
## 전부 extension을 사용해서 불리언을 반환하는 메소드를 따로 만들어서 사용해도 될까요? 

> 아니여 그런 듯이 아니라 isEmpty와 같이 isNotEmpty 같은 함수를 만들어서 사용하면 보다 효율적이거라는 의미 였습니다.

2021-08-03 13:41 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +        displayBankClosed(workTime: durationTime)
너무 좋아요!

2021-08-03 13:41 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +    private var isInCorrectInput: Bool {
너무 좋습니다. 변수로 하는 것보다는 내부에서 변경이 안되는 함수로 하면 더 좋을거같아요!

2021-08-03 13:41 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +        repeatUntilCollectSelection()
단일 책임을 항상 잊지마세요!

2021-08-03 13:41 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    var watingQueueIsNotEmpty: Bool {
아하 검사 함수를 만들어 달라는 의미는 아니였구 isNotEmpty를 만들어서 검사 할 때 유용하게 쓰면 좋다는 의미였습니다!

2021-08-03 13:41 UTC, jungseungyeo commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +        while userInput != MainMenuMessage.firstSelection.rawValue
디코로 의견 주신내용을 보자면 

> if isResult == true {} 와 if isResult {} 의 가독성을 물어보신거 같아요.

저는 오른쪽의 있는것을 선호하는 편이예요! 이런 이유는 현재 어떤 bool 값이 와야 넘어가는지 좀 더 명확해서 좋은거 같아요!
어느 정도 메모리 소모를 가지고 가독성을 높이면 전 더 좋은 내용인거 같아요! 
단 이것을 사용 할 때 전 규칙이 있는데 !isResult 와 같이 앞에 ! <-을 쓰지 않쓰는 코드를 작성할려고 합니다. 참고 하면 좋을 거 같아요!

2021-08-03 13:47 UTC, jungseungyeo approved these changes
엘렌, 요시킴! 너무 고생하셨어요! 수정 사항을 너무 잘 적용했어요! 나머지 부분은 step3에서 적용해보면 좋을거같아요! step3에서는 DispatchQueue를 적용해보면 좋을거같아요!

너무 고생하셨습니다!

2021-08-03 13:47 UTC, merged

2021-08-03 13:50 UTC, jcrescent61 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +        repeatUntilCollectSelection()
네!!!

2021-08-03 13:53 UTC, jcrescent61 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/MainMenuManager.swift
> +    private var isInCorrectInput: Bool {
연산프로퍼티를 사용할때 염두해야할 부분중 하나가 더 추가됐네요!! 감사합니다 !

2021-08-03 13:53 UTC, jcrescent61 commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/BankManager.swift
> +    var watingQueueIsNotEmpty: Bool {
이해가 잘 안돼요 ㅠㅠ