은행 창구 매니저 [Step3] 산체스, 샤피로
yagom-academy/ios-bank-manager pull request #90
Opened 2021-08-05 04:42 UTC by shapiro711

@TaeJoongYoon 
안녕하세요 타일러!
스탭3를 완성시켜서 PR을 날립니다~!!
저희가 이번에 커밋에 신경을 많이 못 썼습니다...
완성된 코드 위주로 보시는것이 아마 더 편하실것 같아요...!

## 구현한 내용
---
1. 비동기 처리 - 예금, 대출 업무에 맞는 은행원들이 각각 비동기적으로 일을 하도록 구현했습니다.
2. Task 타입 구현 - TaskType과 짝지어서 업무의 종류에 맞게 큐와 은행원의 수를 관리하도록 했습니다. ([TaskType:Task] 딕셔너리 사용)

## 궁금한 내용
---
1. 클로저의 강한 참조 - 저희가 Bank 클래스 serveClient() 메서드의 dispatchqueue.async 사용했습니다. 클로저 내부에 self가 있을 경우에 참조 카운트를 올리지 않기 위해서 weak를 사용하는 것으로 알고 있습니다. 저희가 deinit을 사용하여 테스트를 해보았을때 캡처리스트에 self, weak self 둘다 정상적으로 해제가 되었습니다. 이럴 경우에는 어떻게 사용 하는 것이 좋을까요?
2. semaphore 사용 - 저희가 현재 clerk을 따로 관리를 해주고 있지 않고 semaphore로 clerk의 수를 정해주고 있습니다. 현재 저희가 구현한 코드에서는 손님이 들어오면 그 손님에 맞는 clerk을 새로 생성해주면서 매칭을 해주고 있는데, 이 방법이 괜찮은 방법인지 궁금합니다.
3. 프로토콜 사용 - Bank 타입에서 현재 BankClerk, BankClient에 직접 접근하지 않고 있습니다. 의존도를 낮추고 확장성을 고려해서 프로토콜을 통해서 접근을 하고 있는데, 저희 프로잭트에서 괜찮은 방법인지 그리고 타일러는 타입을 설계 할때 이러한 방법을 많이 사용하는지 궁금합니다. 추가로 프로토콜의 위치에 관해서도 고민을 했습니다. 파일을 따로 빼야 할지, 혹은 어떤 클래스 파일에 위치하면 좋을지에 대한 타일러의 기준이 궁금합니다.
4. nested type - 저희가 enum 타입을 구현 하면서 밖에 위치 해야할지 안에 위치 해야할지에 대한 고민을 했었는데 타일러는 어떤 기준을 두고 nested type을 사용하는지 궁금합니다.

2021-08-06 06:58 UTC, shapiro711 commented
@TaeJoongYoon
안녕하세요 타일러~!!!
저희 어제 말씀해주신 부분을 수정하고 푸시 했습니다!!
어제 잘 얘기 해주셔서 다른 방법으로도 접근 해볼 수 있었던것 같아요!! 감사합니다 :)

##수정 내용
---
1. 비동기 처리 부분 로직 변경 
2. bank 프로퍼티의 자료구조 설계 변경 - tasktype을 키로 은행원큐, 손님큐에 접근 하도록 변경

##궁금한 내용
---
1. 비동기 처리 - 저희가 함수를 통해서 TaskType별로 비동기 처리를 구현했습니다. 하지만 TaskType별 함수 내부의 각각의 은행원에 대한 일은 동기적으로 처리가 되는 것을 확인하였습니다. 어제 저희가 봤던 결과도 사실 동기적으로 돌았는데 착각한것 같아요... 그래서 함수 내부에서 다시 각각의 은행원에 대한 일을 비동기 처리를 해서 구현하였습니다. 어제 타일러와 말한 내용중에 저희가 함수 안은 동기적으로 돌지 않을까 하는 질문이 혹시 잘못 전달 된것이 아닐까 싶어서 다시 한번 질문 드립니다 :) 
2. 나머지 궁금한 내용은 위의 PR과 연결 됩니다!!!

2021-08-07 07:03 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +enum BankType: CaseIterable {
업무타입에 따른 enum을 구현하셨군요 ㅎㅎ 좋습니다 :)

2021-08-07 07:16 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func serveBanking(for client: BankClient, notifyEnd: @escaping (BankClerk) -> Void )
보통 이런경우에는 `notifyEnd`보단 `completion`이라는 네이밍으로 많이 사용하긴 합니다 ㅎㅎㅎㅎ

2021-08-07 07:16 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    private var bankTypeTask: [BankType: Task] = [:]
BankType과 Task를 딕셔너리로 관리하는 이유가 있을까요???

2021-08-07 07:16 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Task.swift
> +    let dispatchQueue = DispatchQueue.global()
별도의 user-defined DispatchQueue를 가지고 있는게 아니라 global큐를 사용할거라면 굳이 변수로 갖고 있을 필요는 없어보입니다 :)

2021-08-07 07:16 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Bank.swift
> +    func generateBankTypeTask() {
외부에서 사용하지 않는 함수라면 접근제어자를 통해 은닉화를 시켜주세요 :)
익숙하지 않으면 자주 놓칠수 있는 부분이기 때문에 항상 신경써주시는게 좋습니다 ㅎㅎㅎ

2021-08-07 07:27 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    }
상수관리를 아주 잘하셨네요 ㅎㅎ 훌륭한 방법입니다 💯

2021-08-07 07:27 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private let generateNewClients = { () -> Queue<Clientable> in
Client타입이 아닌 추상화한 Clientable 프로토콜로 제약시킨 방식이 좋아보여요 ㅎㅎㅎ 👍 👍

2021-08-07 07:27 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    private func generateBankMenuNumber() -> BankMenu? {
좀더 리턴값에 맞는 함수명으로 바뀌었군요! 좋습니다 ㅎㅎㅎ 뒤에 `Number`는 빠져도 좋을것 같아요 ㅎㅎㅎ

2021-08-07 07:27 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
>          }
bankMenu가 enum이라서 더 enum답게 사용하려면 switch문으로 바꿔줘도 좋을것 같군요 :)

2021-08-07 07:27 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Task.swift
> +    case loan = "대출"
예금/대출을 출력하기 위해서 rawValue를 사용하기 보다 별도의 String깂을 리턴하는 변수를 만드는것이 좋아보여요 ㅎㅎ
이러면 추후에 rawValue타입이 변경되어버리면 그에 따라 대응해야할 가능성이 생길것 같습니다 !

2021-08-07 08:08 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
>          group.wait()
DispatchGroup의 사용을 enter, leave, wait 말고도
globalQueue.async의 파라미터로 group을 넘겨주어서 notify함수를 이용하는 방법도 있습니다 :)
나중에 참고해보시면 좋을것 같아요~

2021-08-07 08:11 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +        let group = DispatchGroup()
DispatchGroup은 여러 Queue에서 작업중인 task들을 하나의 Group에서 관찰할 때 많이 사용하는데요 ㅎㅎ
지금과 같이 코드진행의 블로킹을 거는 목적이라면 다른방법들도 있을것 같아요!
이번에는 시간이 부족해서인지 몰라도 두 분이라면 충분히 좋은 방법들을 찾으실거라 믿습니다 ㅎㅎㅎ

2021-08-07 08:11 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +    func serveClient(semaphere: DispatchSemaphore, client: Queue<Clientable>, clerk: Queue<Clerkable>, endServe: @escaping () -> Void ) {
semaphere 오타난것 같아요 ㅎㅎㅎ

2021-08-07 08:11 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +                currentClerk.serveBanking(for: currentClient) { (endClerk) in
endClerk은 사용되지 않아보이네요~ 필요하지 않다면 제거해도 좋을듯 합니다!

2021-08-07 08:48 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/Model/Bank.swift
> +                endServe()
`endServe`가 `serveBanking`의 완료 closure밖에 있는데 이렇게 되면 실제로 업무완료 전에 `endServe`가 호출될것 같아요!

2021-08-07 08:49 UTC, TaeJoongYoon commented on BankManagerConsoleApp/BankManagerConsoleApp/BankClerk.swift
> +        Thread.sleep(forTimeInterval: workTime)
Thread.sleep을 사용하게되면 지정시간동안 쓰레드가 멈춰버립니다. 비동기 프로그래밍을 위해선 GCD의 `asyncAfter`함수를 이용하는게 더 좋아보여요 :)

2021-08-07 08:54 UTC, TaeJoongYoon requested changes
안녕하세요 산체스, 샤피로! 타일러입니다 :)

이번과제는 동기/비동기 프로그래밍이 들어가면서 새로운 작업들을 해야하다보니 아무래도 많은 어려움이 있었던것같아요.
우선 많은 시행착오끝에 STEP3까지 잘 마무리해주셔서 감사합니다. 지금은 완벽히 이해안되고 결과물이 마음에 들지 않더라도
지난 고민들은 머릿속에 남아있으니 앞으로 공부하실때 많은 도움이 될거에요. 화이팅입니다 💯 👍 

---
## 1. 클로저의 강한 참조

저번에 말씀드렸듯이, 자신과 closure가 강한순환참조를 일으키는 구조라면 weak으로 self 캡쳐링을 통해 순환참조를 막을 수 있습니다.
아래 자료도 참고해보시면 더 좋을듯 해서 링크남겨둘게요~
[You don`t always need weak self](https://medium.com/flawless-app-stories/you-dont-always-need-weak-self-a778bec505ef)

## 2. semaphore 사용

이 부분도 저번에 논의했었는데, 이렇게 되면 BankClerk 객체를 직접 다루어야 하는 상황이 생기면 유동적으로 수정하기 힘들 것 같아요. 그래서 저라면 clerk은 semaphore에 강하게 의존하지 않고 분리 시킨 뒤에 semaphore의 value만 관리해주는 방식으로 개발할 것 같아요 :)

## 3. 프로토콜 사용

네! 저도 이렇게 Protocol위주로 개발하고 있습니다. 객체를 정의하기 전에 먼저 Protocol로 어느 부분이 필요한 지 추상화를 해두고, 공통점이 생긴다면 공통 Protocol로 묶거나 분리하는 과정을 거쳐서 Protocol 기반으로 객체정보를 구성한 뒤, 객체정의 시에 해당 프로토콜을 준수하는 형식으로 개발합니다. 이렇게 작업하면 변경사항에 있어서 안전하고 기능별로 분리하기에 용이하고 테스트코드를 작성하는데도 유리하다고 생각합니다 ㅎㅎ
Protocol과 같은 타입 위치 같은 경우, 저는 해당 타입이 해당 파일/특정 객체 내에서 사용되는 지 혹은 프로젝트 전체적으로 사용되는 지에 따라서 위치를 구분하는 편입니다 :)

## 4. nested type

위 3번질문의 마지막 문장과 같은 생각입니다 :) protocol, enum, type 등등 저 기준을 가지고 위치시킵니다 ㅎㅎㅎ

## 5. 비동기 처리 - 저희가 함수를 통해서 TaskType별로 비동기 처리를 구현했습니다. 하지만 TaskType별 함수 내부의 각각의 은행원에 대한 일은 동기적으로 처리가 되는 것을 확인하였습니다. 어제 저희가 봤던 결과도 사실 동기적으로 돌았는데 착각한것 같아요... 그래서 함수 내부에서 다시 각각의 은행원에 대한 일을 비동기 처리를 해서 구현하였습니다. 어제 타일러와 말한 내용중에 저희가 함수 안은 동기적으로 돌지 않을까 하는 질문이 혹시 잘못 전달 된것이 아닐까 싶어서 다시 한번 질문 드립니다 :)

마지막 이전코드상태로 돌려보니 그렇네요 ㅎㅎㅎ

```swift
        group.enter()
        globalQueue.async { [self] in
            serveClient(semaphere: depositSemaphore, client: deposit.client, clerk: deposit.clerk) {
                totalNumberOfClients += 1
            }
            group.leave()
        }
        
        group.enter()
        globalQueue.async { [self] in
            serveClient(semaphere: loanSemaphore, client: loan.client, clerk: loan.clerk) {
                totalNumberOfClients += 1
            }
            group.leave()
        }
```

여기서는 각 업무타입에 따라 은행원들에게 손님들이 비동기적으로 배분되고

```swift
            DispatchQueue.global().async {
                currentClerk.serveBanking(for: currentClient) { (endClerk) in
                    clerk.enqueue(currentClerk)
                    semaphere.signal()
                }
                endServe()
                group.leave()
            }
```

여기서 분배된 손님들을 각 은행원들이 비동기로 응대하고 있군요. 하지만 이렇게 작업하는것 보단 위 [리뷰](https://github.com/yagom-academy/ios-bank-manager/pull/90#discussion_r684606297)에서도 남겼지만 GCD의 `asyncAfter`를 이용하는게 더 좋아보여요 ㅎㅎㅎ 지금은 쓰레드를 sleep시키기 때문에 은행원들이 비동기적으로 일을 못하고 앞의 은행원이 일을 마무리할때까지 기다리고 있는 상황이네요 :)

---

이번 프로젝트는 비동기 프로그래밍이 가장 주된 내용인걸로 보여요. 그래서 어렵기도 하고 중요하기도 한데요. 이번 프로젝트를 이대로 마무리 하더라도 동기/비동기 , 직렬/병렬 에 대한 개념은 꼭 이해하고 넘어가셨으면 좋겠습니다 ㅎㅎㅎ 실제 iOS프로그래밍할때 거의 항상 사용하고 컴퓨터 프로그래밍을 할때 중요한 개념이기 때문이에요. 지금 어렵더라도 자주 자료를 찾아보고 실제로 코드작성을 해보시면 더 이해가 빨라질것 같아요 :)

하지만 그래서인지 이번프로젝트에서는 네이밍이나 은닉화에 대한 부분은 살짝 아쉽게 느껴졌어요. 그래서 리뷰 코멘트에 대한 대부분의 내용이 그런 부분이네요. 비동기 프로그래밍도 중요하지만 네이밍과 은닉화 같은 부분도 마찬가지로 중요합니다. 실제로 개발할때 네이밍에 시간을 많이 할애하기도 해요. 해당 변수/함수에 가장 적합하고 의미있능 이름을 지어주는 습관을 가지신다면 더욱 좋을것 같아요 ㅎㅎ
이번프로젝트도 고생하셨습니다 :)

2021-08-25 08:23 UTC, closed without merging