은행 창구 매니저 [STEP1] July, 애플사이다
yagom-academy/ios-bank-manager pull request #99
Opened 2021-12-20 12:05 UTC by just1103

안녕하세요 그린 !!!! ( @GREENOVER )
앞으로 2주간 잘 부탁드립니다 :) 
저번 계산기 프로젝트에서 구현해본 `LinkedList`지만 다시 해보려고 하니 서툰부분 투성이네요 .. 
부족한 점이 많지만 잘 부탁드립니다.

## STEP1 구현 내용 
- 은행에 도착한 고객이 임시로 대기할 대기열 (Queue) 타입을 구현하는 것이 목표였습니다.
- 먼저 Linked-list 타입을 구현하고, 이를 활용하여 Queue 타입을 구현했습니다. 그리고 Queue 타입에 대해 Unit Test를 작성했습니다. 

## 🐥 고민한 점 및 궁금한 점 🐥
> 1. 타입

1.1 그린이 짚어주셔서 프로젝트 요구사항에서 Queue를 구현할 때 왜 성능이 좋은 `Double Stack Queue`가 아니라 `Linked-list`를 활용하라고 했을지 고민했습니다.  

먼저 `Linked-list`의 특징을 배열과 비교해봤습니다.
||배열|Linked-list|
|---|---|---|
|장점|임의 접근이 가능|임의의 요소 추가/삭제가 쉬움|
|단점|맨 앞의 요소를 제거하면 모든 요소 위치를 옮겨줘야 해서 비효율적 (시간복잡도 O(n))|임의 접근이 불가하고, head부터 찾아야 함|

그리고 `Double Stack Queue`는 배열을 뒤집는 메서드 `reversed()`의 시간복잡도가 O(1) 이므로 Queue로 활용했을 때 큰 장점이 있다고 알고 있습니다.
STEP2/3의 내용을 미리 알 수 없어서 추측해보았는데, `은행창구의 손님 대기열`이므로 중간에 줄 서서 기다리다가 나가는 손님이 발생하는 상황 등 Queue의 중간에 값을 추가/삭제하는 기능이 필요하여 `Linked-list`를 사용할 것으로 생각했습니다. 이 부분은 STEP2/3을 확인하고 다시 고민해보겠습니다. 😅

1.2 `ListNode` 및 `Linked-List`는 클래스로 구현하고, `CustomerQueue`는 구조체로 구현했습니다.
먼저 `클래스`를 사용한 이유는 저장할 데이터의 양이 매우 많아졌을 때, 실제 값을 매번 메모리 (Stack)에 올리는 것보다는, `참조`를 활용하는 것이 효율적일 것으로 판단했기 때문입니다.
그리고 `구조체`를 사용한 것은 `CustomerQueue`와 관련하여 상속 또는 참조 기능을 사용하지 않으므로 클래스보다 성능이 좋은 구조체를 사용하는 것이 적절하다고 생각했기 때문입니다.

1.3 `Linked-List`의 `scanAllValue` 메서드 반환타입을 배열 `[Element]`로 지정했는데, `[Element]?`와 같은 옵셔널로 하는 게 더 적절할지 고민했습니다. 즉, Linked List가 비어있을 때, 빈 배열을 반환할지, nil을 반환할지 고민했습니다.
원래 "값이 없음"을 나타낼 때는 `옵셔널` (nil)을 사용하는 것이 좋다고 알고 있지만, `빈 배열`도 값이 없는 상태를 나타내며 게다가 옵셔널 바인딩을 할 필요가 없으므로 이번 PR에는 빈 배열을 반환하는 것으로 작성했습니다.
그린이라면 어떻게 하실지 궁금합니다 ! (옵셔널 바인딩만 해봤지 ,, 옵셔널을 유용하게 쓰려니까 너무 힘듭니다 ..)

```swift
func scanAllValues() -> [Element] {
        var scanResult: [Element] = []
        
        guard var finderToTail = head else { return scanResult }

        scanResult.append(finderToTail.value)

        while let nextNode = finderToTail.pointer {
            scanResult.append(nextNode.value)
            finderToTail = nextNode
        }
        
        return scanResult  // Linked-list가 empty 상태라면 빈 배열을 반환
    }
}
```

1.4 NestType을 사용했습니다.

```swift
class LinkedList<Element> {
    class ListNode<Element> {
        var value: Element
        var pointer: ListNode?
        
        init(value: Element) {
            self.value = value
        }
    }
    
    typealias Node = ListNode<Element>
```
`Linked-list` 내부에서만 `ListNode`를 사용하므로 아래와 같이 중첩 타입을 사용했습니다. (그리고 `typealias`을 활용하여 자주 사용하는`ListNode<Element>`를 `Node`로 간결하게 타입 지정을 했습니다.) 적절한 방식이었는지 아니면 그래도 타입끼리는 분리해주는게 좋은지 궁금합니다 ! 

> 2. 네이밍
2.1 Node 클래스의 변수 `value`에 네이밍에 관하여 고민을 했습니다.
원래는 `data`라고 지었는데 너무 광범위한 단어라서 value로 수정했습니다.

또한 변수 `pointer` 역시 `next` 와 네이밍을 고민했습니다. 둘 다 적절하다고 생각하긴 하지만, 어느쪽이 더 직관적일지 궁금합니다. 

```swift
 class ListNode<Element> {
        var value: Element
        var pointer: ListNode?
// ...
}
```

## 조언을 듣고싶은 점
- Linked-list 클래스가 효율적으로 구현된 것인지 궁금합니다. 메서드에 반복적으로 활용되는 부분이 있어서 연산 프로퍼티 tail을 생성하여 활용했는데, 더 개선할 점이 있을 것 같아서 그린의 의견을 여쭤보고 싶습니다. `while let` 등으로 옵셔널 언래핑과 반복문을 사용했는데 이 부분도 적절한지 궁금합니다.
- 그외 다시 고민해볼 점이 있다면 어떤 내용이라도 피드백 부탁드립니다. :)

2021-12-20 14:12 UTC, GREENOVER requested changes
@just1103 @July911 
안녕하세요! 2주간 이번 프로젝트 리뷰를 맡아서 영광이에요ㅎㅎ
저도 정말 잘 부탁드립니다🙌
제일 빠르게 스텝 1을 진행해주시느라 오늘 많이 피곤하셨을텐데 두분 스텝1 수고 많으셨습니다!👍👍
그럼 리뷰해보겠습니다🙋🏻
*** 
### 칭찬 드리고 싶은 부분
- 파일명과 그룹핑이 아주 잘 되어 있습니다 💯
- 커밋도 잘 나눠서 진행해주셨네요 💯
- 변수나 메서드 네이밍들이 아주 좋네요 💯
- 기한에 잘 맞춰서 구현해주셨습니다 💯
***
### 고민하신점에 대한 저의 의견
1. DoubleStack VS LinkedList
- 큐 구현을 위한 더블스택과 연결리스트의 장단점을 아주 잘 파악해주셨고 잘 선택해주신것 같습니다!
이후 스텝이 어떻게 될지 모르는 상황에서 지금처럼 예측을 해보며 연결리스트를 가져가는 이점을 생각하신점도 아주 좋아요👍
앞으로도 어떤 프로젝트던 이런 방향으로 생각하시면 도움이 될거에요ㅎㅎ
2. 클래스와 구조체의 구현
- 고민하신점에 대해 잘 봤습니다! 고민의 흐름이 좋고 결과적으로 지금 구현하신것 좋습니다!
물론 도출해내신 의견도 맞아서 더 첨언할 부분이 없습니다👍
3. 빈배열 VS 옵셔널
- 정말 스타일 차이긴하지만 저는 평소 그럴때 옵셔널을 사용합니다.
다만 지금 두분이 구현하신 코드 상에서만 본다면 빈배열을 두고 사용하는게 더 나아보이기에
이대로 진행하시는것도 좋습니다!
4. NestType
- 결론부터 말씀드리자면 저는 적절하다고 생각합니다!
물론 타입별로 나누는게 좋다 라고 알고 계신것이 맞지만 이 경우는 특수한 경우라 생각됩니다.
연결 리스트의 노드일테고 그 정의나 구현부의 볼륨이 크지 않고 요기서 밖에 사용되지 않기에 중첩타입으로 표현하는것이
성능의 차이가 아닌 가독에서 더 좋다고 보여집니다!
추가로 별칭사용 아주 좋습니다👍
5. 네이밍
- 저는 value 네이밍 좋아요!
그리고 pointer와 next중에서는 next를 택했을것 같습니다!
뭔가 제 생각에는 next가 조금 더 직관적이지 않나 생각합니다.
pointer도 충분히 이해되고 직관적이지만 이것은 포인터라는 개념을 알고 있는 사람에게는 정말 next보다 친숙하게 다가오겠지만
만약 정말 만약에 C를 배우지 않았거나 그 외에 포인터라는 개념에 대해 알고 있지 않다면 조금 이해하기 힘든 네이밍일수도 있겠다는 생각이 있습니다. (물론 현업에서는 없을거에요.)
그렇기에 수정해도되고 안하셔도 됩니다!
저는 이 부분에 질문을 해주시기전에 pointer를 끄덕이면서 코드 리뷰를 했고 next로 왜 안했지? 라는 생각을 하지 못했습니다.😀
***
### 조언 요청에 대한 저의 의견
1. LinkedList 구현
- 제가 연결리스트 구현부에 대해 리뷰 코멘트로도 조금 남겨보았는데 정리해보겠습니다.
우선 지금 해당 구현은 큐를 의식하고 짜여진 축소된 범위의 연결리스트라는 생각이 들었습니다.
연결리스트의 장점들을 파악하셨지만 사실 코드상에서는 그 장점들이 구현된 부분이 보이지 않았어요🥲
큐의 구현이나 요구사항은 제쳐두고 연결리스트만을 보고 해당 타입을 구현해보는것이 어떨까 싶습니다🙋🏻
아 그리고 first/last 같은 연산 프로퍼티들을 만들 수도 있지만 꼭 필요하진 않습니다.
해당 프로퍼티들은 결국 head/tail의 value값을 좀 더 편하게 찾으려고 만드는것이기에 필수 구현은 아니라고 생각합니다.
결과적으로 제가 생각했을때 연결리스트만 바라보고 필수적이라고 생각되는 구현은 데이터를 원하는 위치에 삽입/삭제할 수 있는 기능입니다.
이 부분이 필요할것 같아 의견을 드려봅니다🙋🏻
2. private 메서드의 Unit Test
- 음.. 저는 직접적으로 private 메서드를 테스트해볼 수 있는 방법은 없는걸로 알고 있는데 확신할 순 없네요 제가 부족해서😭
다만 생각해봐야할게 private을 붙인 이유입니다.
기본적으로 유닛 테스트는 블랙박스 테스트이기에 내부 구현에 대해서 알 수 없습니다.
또한 제가 문서를 찾아보니 유닛 테스트 코드는 internal 이상의 메서드만 할 수 있다고 공식적으로 나와 있네요.
```
Note: @testable provides access only for “internal” functions; “private” declarations are not visible outside of their file even when using @testable.
```
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/04-writing_tests.html
그렇다면 추측해볼때 private을 한 이유가 있을테고 그것을 유닛 테스트라는 다른 모듈에서 테스트 하기 위해서는 직접적으로 호출하는것이 불가능하고 우회해서 테스트는 해볼 수 있을것 같아요.
예를들어 이런식으로요.
```swift
public func enqueueTest() {
        self.enqueue()
}
```
이렇게 접근할 수 있는 레벨의 메서드를 만들고 그안에 선언해서 하는 방법이 있을것 같습니다.
만약 다른 방법을 찾으신다면 저도 공유해주시면 감사하겠습니다🙏🏻
***
다시 한번 수고많으셨습니다!
요구사항들은 구현되었지만 어쩌다보니 리뷰 코멘트가 좀 생겼어요ㅠㅠ..
한번 확인해보시고 수정이 필요한 부분은 수정을 거친 다음 재리뷰 요청을 해주시면 확인 후 머지하는 방향으로 하겠습니다!🙌

2021-12-21 08:27 UTC, just1103 commented on BankManagerConsoleApp/BankManagerTests/CustomQueueTest.swift
> +class CustomQueueTest: XCTestCase {
저희가 놓친 부분인데 짚어주셔서 감사해요 👍

2021-12-21 08:35 UTC, just1103 commented on BankManagerConsoleApp/BankManagerTests/CustomQueueTest.swift
> +    var sut: CustomerQueue<Int>!
보통 `setUpWithError` 및 `tearDownWithError` 메서드에서 반드시 각각 `기본값` 및 `nil`을 할당하므로 `암시적 추출 옵셔널`을 사용하는 것으로 알고 있습니다.

이때 전역변수 sut을 옵셔널 타입 `CustomerQueue<Int>?`으로 지정하면, 각 테스트코드에서 언래핑해야 해서 번거로우므로 아래와 같이 수정했는데, 적절한 방법일까요?
```swift
var sut: CustomerQueue<Int> = CustomerQueue<Int>()

override func setUpWithError() throws {
    sut = CustomerQueue<Int>()
}

override func tearDownWithError() throws {
    sut.customers = LinkedList<Int>(value: nil)
}
```
보통 `tearDownWithError` 메서드에서는 `sut = nil`을 하는 것이 일반적인 것 같아서 어색하다고 느꼈습니다.

2021-12-21 08:54 UTC, July911 commented on BankManagerConsoleApp/BankManagerTests/CustomQueueTest.swift
> +    }
```swift
    func test_빈_큐에_1을_enqueue하면_1이_남는다() {
        sut.enqueue(value: 1)
        XCTAssertEqual(sut.customers.head?.value, 1)
        XCTAssertNil(sut.customers.head?.next)
    }
    
    func test_빈_큐에_1과2를_enqueue하면_1과2가_남는다() {
        sut.enqueue(value: 1)
        sut.enqueue(value: 2)
        XCTAssertEqual(sut.customers.head?.value, 1)
        XCTAssertEqual(sut.customers.head?.next?.value, 2)
        XCTAssertNil(sut.customers.head?.next?.next)
    }
``` 

말씀해주신대로, 굳이 scanAllValue라는 메서드를 사용하지 않고 노드의 특성에 따라 test 를 진행하는 방향으로 바꾸어 보았습니다 !
지적 감사합니다 ㅎㅎ

2021-12-21 08:56 UTC, GREENOVER commented on BankManagerConsoleApp/BankManagerTests/CustomQueueTest.swift
> +    var sut: CustomerQueue<Int>!
네! 예시로 보여주신 방향도 괜찮을것 같고 마지막으로 제안해주신 방향도 좋을것 같습니다.
저의 의도는 강제언래핑을 최대한 지양하자는것이여서 그것이 해결되는 방향이라고 봅니다!

2021-12-21 09:02 UTC, July911 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    class ListNode<Element> {
상속받지 않을 클래스에 `final`키워드를 적용했습니다.

2021-12-21 09:03 UTC, July911 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    }
`private(set) var head: Node? `
private(set) 으로 접근제어를 설정해주었습니다!

2021-12-21 09:37 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    }
말씀해주신 것처럼 테스트 코드로 사용할 목적으로 만들었는데, 위의 내용처럼 사용할 필요가 없어져서 삭제했습니다. 👍

2021-12-21 13:36 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +        }
매개변수로 받은 값이 명확한 상황이라서 전달인자 레이블로 underscore를 사용했습니다. 👍

2021-12-21 13:38 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    }
말씀해주신대로 `Linked-list`의 장점을 살릴 수 있는 `func insert(_ value: Element, at index: Int)` 형태의 메서드를 추가해봤습니다. 로직을 직접 짜보니 `Linked-list`에 대한 이해도가 높아진 것 같아요. 감사합니다.

2021-12-21 13:38 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    }
말씀해주신대로 `Linked-list`의 장점을 살릴 수 있는 `func insert(_ value: Element, at index: Int)` 형태의 메서드를 추가해봤습니다. 로직을 직접 짜보니 `Linked-list`에 대한 이해도가 높아진 것 같아요. 감사합니다.

2021-12-22 05:28 UTC, just1103 commented on BankManagerConsoleApp/Model/CustomerQueue.swift
> +    var customers: LinkedList<Element> = LinkedList<Element>(value: nil)
아하! 그 생각을 못했네요. LinkedList 내부에 `저장 프로퍼티`가 없어서 이니셜라이저를 구현하지 않아도 되네요. 수정하겠습니다 :)

2021-12-22 05:55 UTC, July911 commented on BankManagerConsoleApp/Model/CustomerQueue.swift
> +        return customers.removeFirst()
```swift 
    func dequeue() throws -> Element? {
        let headIndex = 0
        return try customers.remove(at: headIndex)
    }
``` 
이런식으로 만들어줬습니다 ! 감사합니다 !!!!

2021-12-22 05:57 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    }
생각해보니 새로운 Node를 추가할 때 enqueue 메서드를 호출하니까, (그리고 LinkedList에 저장 프로퍼티가 없으므로) 이니셜라이저가 필요 없네요! 삭제했습니다 👍

2021-12-22 06:50 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    }
tail을 `저장 프로퍼티`로 수정하고, 각 메서드에서 tail을 지정하도록 수정했습니다!

2021-12-22 06:50 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +        }
말씀하신 내용을 전체 메서드에 적용해보았습니다. :)

2021-12-22 07:09 UTC, GREENOVER approved these changes
고생 많으셨습니다!
에러도 고려하시고 테스트 케이스도 다양해지고
연결리스트도 별도로 명확해진것 같아요!
훨씬 더 멋져졌네요👍
마이너한 수정사항이 아닌 궁금증을 남겨보았어요~!
수정안해도됩니다. 의견을 들어보고 싶은 부분들이였어요ㅎㅎ
한번 쓱~ 편하게 확인해보시고 의견 남겨주시면 감사하겠습니다!
스텝1 요구사항은 전부 만족하고도 남아서 머지하겠습니다🙌
다음 스텝도 화이팅입니다🚀

2021-12-22 07:09 UTC, GREENOVER commented on BankManagerConsoleApp/Model/LinkedList.swift
> +        }
분기가 나눠져 있는데 조금 더 가독성이 좋도록 if elseif의 조건으로 묶어줄수도 있을까요?🤔

2021-12-22 07:09 UTC, GREENOVER commented on BankManagerConsoleApp/Model/LinkedList.swift
> +            indexNodeFinder = indexNodeFinder?.next
indexNodeFinder라는 네이밍만 따로 본다면 조금 모호한 표현 같은데 조금 더 명확한 네이밍을 찾을 수 있을것 같아요🙋🏻

2021-12-22 07:09 UTC, GREENOVER commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    @discardableResult
왜 필요한걸까요~?🧐
결과와 정말 상관이 없는건지 궁금합니다!

2021-12-22 07:09 UTC, merged

2021-12-22 11:05 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +        }
51번 코드와 61번 코드를 `if/if else`로 분기하라는 말씀이실까요? 저희도 고민해봤는데 57번 위치에 guard문이 위치하도록 한 이유는 `index`가 `0` 일 때 `newNode`를 추가하기 전에, 만약 `count`보다 `index`가 작으면 에러를 던지기 위함이었습니다. 이 의도를 포기해서라도 `if/if else`로 묶어주는 것이 좋을까요?

2021-12-22 11:09 UTC, just1103 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +            indexNodeFinder = indexNodeFinder?.next
이 부분에 대해 여러 번 고민했는데, 특정 `index`에 위치한 `Node`까지 이동하는 변수이므로 `FinderToNodeAtIndex`이면 더 명확할까요?

2021-12-22 11:10 UTC, July911 commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    @discardableResult
remove메서드가 test코드에서 쓰일 때, 삭제된 사실만 확인하고 리턴값은 필요없는 상황이 생겨서 적어주었습니다! 
혹시 test코드만을 위해서   @discardableResult 를 사용하면 부적절한걸까요 ...?

2021-12-22 23:09 UTC, GREENOVER commented on BankManagerConsoleApp/Model/LinkedList.swift
> +        }
아하 의도는 이해했습니다!👍
다만 index가 0일때 count보다 작을 수가 있는지 궁금해요🙋🏻
그리고 현재 코드에서 만약 빈 연결리스트에 index가 0인 데이터가 처음 들어오면 guard문의 index <= count와 걸릴것 같다고 생각하는데 이럴경우 에러를 뱉는것이 의도인건가요?🙋🏻
고렇다면 지금 코드가 나을것 같긴합니다!
만약 아니라면?
guard문 57~58 라인 코드 제외하고 51~55 / 61~65 라인을 묶어줄 수 있지 않을까? 라는 질문이였습니다🥲

2021-12-22 23:12 UTC, GREENOVER commented on BankManagerConsoleApp/Model/LinkedList.swift
> +            indexNodeFinder = indexNodeFinder?.next
저도 딱 어떤게 좋다고 명확하게 아직까지 네이밍이 떠오르진 않앗는데요.
타입을 본다면 저게 Node 타입이라고 보이는데 그렇다면 저 변수도 타입따라서 결국 node라고 보입니다.
그래서 네이밍만 봐도 아 어떤 노드구나! 하는 그런 네이밍이면 좋을것 같아요!

2021-12-22 23:14 UTC, GREENOVER commented on BankManagerConsoleApp/Model/LinkedList.swift
> +    @discardableResult
사실 테스트코드는 부수적이고 메인 로직 흐름 코드만 봤을때는 이게 왜 사용되었는지 유추하기 힘들어서 그랬습니다🙋🏻
부적절하진 않다고 봅니다! 이유가 있으니까요.
요것도 스타일의 차이라고는 보입니다만 테스트코드에서의 경고 심볼 정도는 무시해줘도 괜찮지 않을까라는 생각도 들었습니다.
(그냥 정말 개인적인 생각)
그것이 앱 성능이나 컴파일,런타임 에러를 유발하진 않으니까요!